export default {
  entity: {
    id: '02af10b3-2972-4837-874e-a4c001c66ea6',
    name: '红旗一九六四年第五期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/02af10b3-2972-4837-874e-a4c001c66ea6.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '在中国共产党广东省委党校的报告',
        authors: ['维·乔·威尔科克斯'],
        page_start: 3,
        page_end: 15,
        dates: [{ year: 1964, month: 2, day: 18 }],
      },
      {
        title: '把思想工作放在首要的地位',
        authors: ['红旗杂志评论员'],
        page_start: 16,
        page_end: 22,
        dates: [{ year: 1964 }],
      },
      {
        title: '做好工业企业车间的思想政治工作',
        authors: ['李野'],
        page_start: 23,
        page_end: 25,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '一个善于做思想政治工作的车间党支部',
        authors: ['张高'],
        page_start: 25,
        page_end: 30,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '加强史学方法论的研究和讨论',
        authors: ['东方明'],
        page_start: 31,
        page_end: 35,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '加强农业技术改革经济效果的研究',
        authors: ['杨均'],
        page_start: 36,
        page_end: 40,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '南斯拉夫有着怎样的“创作自由”',
        authors: ['牧惠'],
        page_start: 41,
        page_end: 47,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '不可救药的“肌肉僵化”症',
        authors: ['洪谷'],
        page_start: 48,
        page_end: 49,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '爬不出死胡同',
        authors: ['秋阳'],
        page_start: 49,
        page_end: 51,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '美元·链条·朋友',
        authors: ['淙林'],
        page_start: 50,
        page_end: 51,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
    ],
    ocr: { content_thresholds: [0.07, 0.177, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/02af10b3-2972-4837-874e-a4c001c66ea6.pdf',
};
