export default {
  entity: {
    id: '037434cb-cb09-486c-881f-67c54338ba91',
    name: '红旗一九七二年第十期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/037434cb-cb09-486c-881f-67c54338ba91.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '夺取新的胜利──庆祝中华人民共和国成立二十三周年',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        page_start: 8,
        page_end: 12,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
      {
        title: '中华人民共和国政府、日本国政府联合声明',
        authors: ['新华社'],
        page_start: 13,
        page_end: 14,
        dates: [{ year: 1972, month: 9, day: 29 }],
      },
      {
        title: '从路线上划清是非界限',
        authors: ['江汉'],
        page_start: 15,
        page_end: 20,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
      {
        title: '大家都来关心青少年的成长',
        authors: ['谭闻'],
        page_start: 21,
        page_end: 25,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
      {
        title: '继续落实党对知识分子的政策',
        authors: ['中国共产党清华大学委员会'],
        page_start: 26,
        page_end: 31,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
      {
        title: '克服经验主义——学习《唯物主义和经验批判主义》的一点体会',
        authors: ['倪志福'],
        page_start: 32,
        page_end: 36,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
      {
        title: '按党的原则办事',
        authors: ['甘戈'],
        page_start: 37,
        page_end: 39,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
      {
        title:
          '农业和工业互相促进——贯彻“以农业为基础、工业为主导”总方针的一点体会',
        authors: ['俞中远'],
        page_start: 40,
        page_end: 46,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
      {
        title: '毛主席指引瑶家走上了幸福路',
        authors: ['云南河口瑶族自治县瑶山公社党委会'],
        page_start: 47,
        page_end: 50,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
      {
        title: '挖掘潜力 增加生产',
        authors: ['中国共产党大庆油田石油化工总厂委员会'],
        page_start: 51,
        page_end: 54,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
      {
        title: '依靠群众治理海河',
        authors: ['江冀'],
        page_start: 55,
        page_end: 60,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
      {
        title: '更好地发展工艺美术生产',
        authors: ['钟青'],
        page_start: 61,
        page_end: 65,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
      {
        title: '北树南移的哲学启示',
        authors: ['上海市果品杂货公司宝山果园党支部'],
        page_start: 66,
        page_end: 70,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
      {
        title: '从工人中积极培养新干部',
        authors: ['中国共产党湖南水口山矿务局委员会'],
        page_start: 71,
        page_end: 74,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
      {
        title: '来信',
        authors: ['郭沫若'],
        page_start: 74,
        page_end: 74,
        dates: [{ year: 1972, month: 9, day: 8 }],
      },
      {
        title: '努力培养妇女干部',
        authors: ['广西梧州市郊区东兴大队党支部'],
        page_start: 75,
        page_end: 78,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
      {
        title: '青年工人要为革命学好技术',
        authors: ['田志松'],
        page_start: 79,
        page_end: 81,
        dates: [{ year: 1972, month: 10, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/037434cb-cb09-486c-881f-67c54338ba91.pdf',
};
