export default {
  entity: {
    id: '049332a3-8bed-4600-83fd-5023ef57bc2d',
    name: '红旗一九六四年第十九期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/049332a3-8bed-4600-83fd-5023ef57bc2d.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '高举毛泽东思想的革命旗帜前进——庆祝中华民族共和国成立十五周年',
        authors: ['红旗杂志编辑部'],
        page_start: 3,
        page_end: 8,
        dates: [{ year: 1964 }],
      },
      {
        title: '革命风雷',
        authors: ['曹禺'],
        page_start: 9,
        page_end: 12,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '战斗的社会主义文学',
        authors: ['刘白羽'],
        page_start: 12,
        page_end: 15,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '科学技术工作的革命化',
        authors: ['李四光'],
        page_start: 16,
        page_end: 19,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '受革命化教育的十五年',
        authors: ['周培源'],
        page_start: 20,
        page_end: 23,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '学习毛泽东思想，做好气象工作',
        authors: ['顾震潮'],
        page_start: 23,
        page_end: 25,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '在建设事业中贯彻革命精神',
        authors: ['李瑞环'],
        page_start: 26,
        page_end: 30,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '身居茅屋，眼看全球，教脚踩污泥，心怀天下',
        authors: ['董加耕'],
        page_start: 30,
        page_end: 31,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '永远做彻底的革命派',
        authors: ['黄祖示'],
        page_start: 31,
        page_end: 34,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '在贫农下中农中扎根',
        authors: ['张韧'],
        page_start: 35,
        page_end: 37,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '更好地为下乡上山的知识青年塑像',
        authors: ['牧惠'],
        page_start: 38,
        page_end: 43,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
    ],
    ocr: { content_thresholds: [0.07, 0.165, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/049332a3-8bed-4600-83fd-5023ef57bc2d.pdf',
};
