export default {
  entity: {
    id: '05553c80-edc7-44da-9c04-763802e9f833',
    name: '红旗一九六六年第四期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/05553c80-edc7-44da-9c04-763802e9f833.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title:
          '中国共产党中央委员会一九六六年三月二十二日给苏联共产党中央委员会的复信',
        authors: ['中国共产党中央委员会'],
        page_start: 3,
        page_end: 5,
        dates: [{ year: 1966, month: 3, day: 22 }],
      },
      {
        title: '苏联共产党中央委员会二月二十四日给中国共产党中央委员会的来信',
        authors: ['苏联共产党中央委员会'],
        page_start: 5,
        page_end: 5,
        dates: [{ year: 1966, month: 2, day: 24 }],
      },
      {
        title: '巴黎公社的伟大启示——纪念巴黎公社九十五周年',
        authors: ['郑之思'],
        page_start: 6,
        page_end: 20,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1966 }],
      },
      {
        title: '翦伯赞的历史观点应当批判',
        authors: ['戚本禹', '林杰', '阎长贵'],
        page_start: 22,
        page_end: 32,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1966 }],
      },
      {
        title: '焦裕禄同志是活学活用毛泽东思想的好榜样',
        authors: ['红旗杂志评论员'],
        page_start: 33,
        page_end: 36,
        dates: [{ year: 1966 }],
      },
      {
        title: '解放军某部侦察连的哲学故事会',
        authors: [],
        page_start: 37,
        page_end: 42,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1966 }],
      },
      {
        title: '实践出智慧',
        authors: ['宋乐山'],
        page_start: 43,
        ocr: { vsplit: 0.35 },
        page_end: 53,
        dates: [{ year: 1966 }],
      },
      {
        title: '日常工作中的辩证法',
        authors: ['王培建', '黄玉明', '姜大洪', '刘杰'],
        page_start: 54,
        page_end: 58,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1966 }],
      },
      {
        title:
          '简单一些好，还是复杂一些好？——从液压操纵箱的改革谈简单和复杂的辩证法',
        authors: ['徐永德', '顾舒'],
        page_start: 59,
        page_end: 61,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1966 }],
      },
      {
        title: '坚决突出政治反对折中主义',
        authors: ['倪志荣'],
        page_start: 61,
        page_end: 63,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1966, month: 3, day: 2 }],
      },
    ],
    ocr: {
      auto_vsplit: false,
      vsplit: 0,
      content_thresholds: [0, 0.1, 0, 0.1],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/05553c80-edc7-44da-9c04-763802e9f833.pdf',
};
