export default {
  entity: {
    id: '069d73a5-7e50-41cb-a25e-187d3e19269b',
    name: '无产阶级文化大革命资料汇编（第二篇）（上）（3）（水陆洲2011年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '水陆洲编',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/069d73a5-7e50-41cb-a25e-187d3e19269b.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title:
          '第二章 炮打资产阶级司令部 批判资产阶级反动路线 第八节 部队院校文革运动的开展',
        authors: ['水陆洲'],
        page_start: 1,
        page_end: 94,
        dates: [{ year: 2011, month: 8 }],
      },
      {
        title: '第三章 一九六七年一月的革命风暴 第一节 一月革命风暴',
        authors: ['水陆洲'],
        page_start: 95,
        page_end: 259,
        dates: [{ year: 2011, month: 8, day: 1 }],
      },
      {
        title: '第三章 一九六七年一月的革命风暴 第二节 上海市革命委员会成立',
        authors: ['水陆洲'],
        page_start: 260,
        page_end: 798,
        dates: [{ year: 2011, month: 8, day: 4 }],
      },
      {
        title: '第三章 一九六七年一月的革命风暴 第三节 山西省革命委员会成立',
        authors: ['水陆洲'],
        page_start: 799,
        page_end: 944,
        dates: [{ year: 2011, month: 8, day: 10 }],
      },
      {
        title: '第三章 一九六七年一月的革命风暴 第四节 贵州省革命委员会成立',
        authors: ['水陆洲'],
        page_start: 945,
        page_end: 975,
        dates: [{ year: 2011, month: 8, day: 8 }],
      },
      {
        title: '第三章 一九六七年一月的革命风暴 第五节 黑龙江省革命委员会成立',
        authors: ['水陆洲'],
        page_start: 976,
        page_end: 1090,
        dates: [{ year: 2011, month: 8, day: 9 }],
      },
      {
        title: '第三章 一九六七年一月的革命风暴 第六节 山东省革命委员会成立',
        authors: ['水陆洲'],
        page_start: 1091,
        page_end: 1241,
        dates: [{ year: 2011, month: 8, day: 11 }],
      },
      {
        title: '第三章 一九六七年一月的革命风暴 第七节 北京市革命委员会成立',
        authors: ['水陆洲'],
        page_start: 1242,
        page_end: 1723,
        dates: [{ year: 2011, month: 8, day: 13 }],
      },
      {
        title: '第三章 一九六七年一月的革命风暴 第八节 解决陶铸问题',
        authors: ['水陆洲'],
        page_start: 1724,
        page_end: 1986,
        dates: [{ year: 2011, month: 8, day: 15 }],
      },
      {
        title: '第三章 一九六七年一月的革命风暴 第九节 批刘保帅保肖',
        authors: ['水陆洲'],
        page_start: 1987,
        page_end: 2149,
        dates: [{ year: 2011, month: 8, day: 16 }],
      },
    ],
    ocr: {
      standard_paragraph_merge_strategy_threshold: 0.186,
      differential_paragraph_merge_strategy_threshold: 0,
      content_thresholds: [0.054, 0, 0, 0],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/069d73a5-7e50-41cb-a25e-187d3e19269b.pdf',
};
