export default {
  entity: {
    id: '070000f1-a495-40ca-be2d-fa73701a6c8b',
    name: '文革通讯第29期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '浙江工农兵美术大学毛泽东主义红卫兵战斗队、毛泽东主义红卫兵',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives15/main/070000f1-a495-40ca-be2d-fa73701a6c8b.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '特大喜讯',
        authors: ['《文革通讯》编辑部'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967, month: 5, day: 17 }],
      },
      {
        title: '毛主席万岁！',
        authors: ['《文革通讯》编辑部'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967, month: 5, day: 17 }],
      },
      {
        title: '中共中央关于处理四川问题的决定',
        authors: ['中共中央'],
        page_start: 1,
        page_end: 2,
        dates: [{ year: 1967, month: 5, day: 7 }],
      },
      {
        title: '周总理重要指示——五月六日给蒯大富同志',
        authors: ['周恩来'],
        page_start: 2,
        page_end: 2,
        dates: [{ year: 1967, month: 5, day: 6 }],
      },
      {
        title: '陈伯达同志传达中央决定',
        authors: ['陈伯达'],
        page_start: 2,
        page_end: 2,
        dates: [{ year: 1967, month: 5, day: 7 }],
      },
      {
        title: '中央首长谈形势',
        authors: ['中央首长'],
        page_start: 2,
        page_end: 2,
        dates: [{ year: 1967, month: 5, day: 5 }],
      },
      {
        title: '王力同志谈大批判——摘自二十九日中共中央对外国马列主义者的讲话',
        authors: ['王力'],
        page_start: 2,
        page_end: 3,
        dates: [{ year: 1967, month: 4, day: 29 }],
      },
      {
        title:
          '周总理、李先念副总理接见十四个省市夏季粮油征购会议全体人员的谈话',
        authors: ['周恩来', '李先念'],
        page_start: 3,
        page_end: 3,
        dates: [{ year: 1967, month: 5, day: 3 }],
      },
      {
        title: '陈伯达、关锋同志六日清晨对北京革命委员会的讲话',
        authors: ['陈伯达', '关锋'],
        page_start: 3,
        page_end: 3,
        dates: [{ year: 1967, month: 5, day: 6 }],
      },
      {
        title: '谢富治同志讲话',
        authors: ['谢富治'],
        page_start: 3,
        page_end: 4,
        dates: [{ year: 1967, month: 5, day: 5 }],
      },
      {
        title: '首都消息',
        authors: ['《文革通讯》编辑部'],
        page_start: 4,
        page_end: 6,
        dates: [{ year: 1967, month: 5, day: 17 }],
      },
      {
        title: '关于钢院目前运动的郑重声明',
        authors: ['新北大公社03《驱虎豹战斗队》'],
        page_start: 6,
        page_end: 6,
        dates: [{ year: 1967, month: 5, day: 8 }],
      },
      {
        title: '卢氏叛徒哲学',
        authors: ['教育部延安公社大字报'],
        page_start: 6,
        page_end: 7,
        dates: [{ year: 1967, month: 5 }],
      },
      {
        title: '北大动态报观察员给北邮东方红公社某些负责同志进一言',
        authors: ['北大动态报观察员'],
        page_start: 7,
        page_end: 7,
        dates: [{ year: 1967, month: 5 }],
      },
      {
        title: '祖国各地',
        authors: ['《文革通讯》编辑部'],
        page_start: 7,
        page_end: 8,
        dates: [{ year: 1967, month: 5, day: 17 }],
      },
      {
        title: '成都组织简介',
        authors: ['《文革通讯》编辑部'],
        page_start: 8,
        page_end: 8,
        dates: [{ year: 1967, month: 5, day: 17 }],
      },
    ],
    ocr: undefined,
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives15/070000f1-a495-40ca-be2d-fa73701a6c8b.pdf',
};
