export default {
  entity: {
    id: '09d81b4c-057f-4a37-bb4a-9cd08f23b44e',
    name: '红旗一九五八年第四期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/09d81b4c-057f-4a37-bb4a-9cd08f23b44e.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title:
          '在毛泽东同志的旗帜下——在北京大学庆祝党成立三十七周年大会上的讲演',
        authors: ['陈伯达'],
        page_start: 3,
        page_end: 14,
        dates: [{ year: 1958, month: 7, day: 1 }],
      },
      {
        title: '哪里找根据？',
        authors: ['艾思奇'],
        page_start: 15,
        page_end: 17,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958 }],
      },
      {
        title: '青年农民能不能成为科学家',
        authors: ['惠庶昌'],
        page_start: 18,
        page_end: 21,
        dates: [{ year: 1958 }],
        ocr: { vsplit: 0.35 },
      },
      {
        title: '为农业科学研究工作建立群众基础',
        authors: ['王顺桐', '孟庆哲'],
        page_start: 21,
        page_end: 23,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958 }],
      },
      {
        title: '群众在科学技术上创造精神的一个事例',
        authors: ['吴象'],
        page_start: 24,
        ocr: { vsplit: 0.35 },
        page_end: 27,
        dates: [{ year: 1958 }],
      },
      {
        title: '小麦增产对农业科学研究工作的革命意义',
        authors: ['于光远'],
        page_start: 28,
        page_end: 30,
        dates: [{ year: 1958 }],
      },
      {
        title: '我国小麦总产量压倒美国',
        authors: ['孟用潜'],
        page_start: 30,
        page_end: 32,
        dates: [{ year: 1958 }],
      },
      {
        title: '除四害的胜利是群众路线的胜利',
        authors: ['杨杰'],
        page_start: 33,
        page_end: 36,
        dates: [{ year: 1958 }],
      },
      {
        title: '福建一个乡的奇迹',
        authors: ['福建省教育厅'],
        page_start: 37,
        ocr: { vsplit: 0.35 },
        page_end: 39,
        dates: [{ year: 1958 }],
      },
      {
        title: '南充专区发展地方工业的几点经验',
        authors: ['戈润生', '卫广平', '曹延明'],
        page_start: 40,
        ocr: { vsplit: 0.35 },
        page_end: 43,
        dates: [{ year: 1958 }],
      },
    ],
    ocr: {
      auto_vsplit: false,
      vsplit: 0,
      content_thresholds: [0, 0.185, 0, 0.1],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/09d81b4c-057f-4a37-bb4a-9cd08f23b44e.pdf',
};
