export default {
  entity: {
    id: '0aade93c-c356-46d2-9807-b567596b7e45',
    name: '哲学笔记（人民出版社1974年版）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '列宁，人民出版社1974年版',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives5/main/0aade93c-c356-46d2-9807-b567596b7e45.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '马克思和恩格斯《神圣家族》一书摘要',
        authors: ['列宁'],
        page_start: 8,
        page_end: 45,
        dates: [{ year: 1895 }],
      },
      {
        title: '弗·宇伯威格《哲学史概论》一书札记',
        authors: ['列宁'],
        page_start: 46,
        page_end: 46,
        dates: [{ year: 1903 }],
      },
      {
        title: '弗·保尔《哲学引论》一书札记',
        authors: ['列宁'],
        page_start: 47,
        page_end: 49,
        dates: [{ year: 1903 }],
      },
      {
        title: '关于恩·海克尔《生命的奇迹》和《宇宙之谜》的书评的札记',
        authors: ['列宁'],
        page_start: 50,
        page_end: 50,
        dates: [{ year: 1904 }],
      },
      {
        title: '关于索尔邦图书馆中的自然科学和哲学书籍的札记',
        authors: ['列宁'],
        page_start: 52,
        page_end: 56,
        dates: [{ year: 1904 }],
      },
      {
        title: '关于索尔邦图书馆中的自然科学和哲学书籍的札记',
        authors: ['列宁'],
        page_start: 52,
        page_end: 56,
        dates: [{ year: 1909 }],
      },
      {
        title: '费尔巴哈《宗教本质讲演录》一书摘要',
        authors: ['列宁'],
        page_start: 58,
        page_end: 86,
        dates: [{ year: 1909 }],
      },
      {
        title: '黑格尔《逻辑学》一书摘要',
        authors: ['列宁'],
        page_start: 88,
        page_end: 106,
        is_range_date: true,
        dates: [
          { year: 1914, month: 9 },
          { year: 1914, month: 12 },
        ],
      },
      {
        title: '黑格尔《逻辑学》一书摘要',
        authors: ['列宁'],
        page_start: 88,
        page_end: 264,
        is_range_date: true,
        dates: [
          { year: 1914, month: 9 },
          { year: 1914, month: 12 },
        ],
      },
      {
        title: '关于论述黑格尔《逻辑学》的各家著作的书评的札记',
        authors: ['列宁'],
        page_start: 266,
        page_end: 274,
        dates: [{ year: 1914, month: 12 }],
      },
      {
        title: '黑格尔《哲学史讲演录》一书摘要',
        authors: ['列宁'],
        page_start: 276,
        page_end: 346,
        dates: [{ year: 1915 }],
      },
      {
        title: '黑格尔《历史哲学讲演录》一书摘要',
        authors: ['列宁'],
        page_start: 348,
        page_end: 360,
        dates: [{ year: 1915 }],
      },
      {
        title: '诺埃尔《黑格尔的逻辑学》一书札记',
        authors: ['列宁'],
        page_start: 366,
        page_end: 373,
        dates: [{ year: 1915 }],
      },
      {
        title: '让·贝兰《物理化学论文。原理》一书札记',
        authors: ['列宁'],
        page_start: 374,
        page_end: 374,
        dates: [{ year: 1914, month: 12 }],
      },
      {
        title: '盖诺夫《费尔巴哈的认识论和形而上学》一书札记',
        authors: ['列宁'],
        page_start: 376,
        page_end: 378,
        dates: [{ year: 1914, month: 12 }],
      },
      {
        title: '福尔克曼《自然科学的认识论原理》一书札记',
        authors: ['列宁'],
        page_start: 379,
        page_end: 380,
        dates: [{ year: 1915 }],
      },
      {
        title: '费尔伏恩《生物起源假说》一书札记',
        authors: ['列宁'],
        page_start: 381,
        page_end: 382,
        dates: [{ year: 1915 }],
      },
      {
        title: '丹尔曼《我们的世界图画是怎祥构成的？》一书札记',
        authors: ['列宁'],
        page_start: 383,
        page_end: 384,
        dates: [{ year: 1915 }],
      },
      {
        title: '路德维希·达姆施泰特《自然科学和技术历史指南》一书札记',
        authors: ['列宁'],
        page_start: 385,
        page_end: 385,
        dates: [{ year: 1915 }],
      },
      {
        title: '拿破仑《思想》一书札记',
        authors: ['列宁'],
        page_start: 386,
        page_end: 386,
        dates: [{ year: 1915 }],
      },
      {
        title: '阿尔都尔·埃利希·哈斯《现代物理学中的希腊化时期的精神》',
        authors: ['列宁'],
        page_start: 387,
        page_end: 387,
        dates: [{ year: 1915 }],
      },
      {
        title: '泰奥多尔·里普斯《自然科学和世界观》一书札记',
        authors: ['列宁'],
        page_start: 388,
        page_end: 388,
        dates: [{ year: 1915 }],
      },
      {
        title: '拉萨尔《爱非斯的晦涩哲人赫拉克利特的哲学》一书摘要',
        authors: ['列宁'],
        page_start: 390,
        page_end: 409,
        dates: [{ year: 1915 }],
      },
      {
        title: '谈谈辩证法问题',
        authors: ['列宁'],
        page_start: 410,
        page_end: 419,
        dates: [{ year: 1915 }],
      },
      {
        title: '亚里士多德《形而上学》一书摘要',
        authors: ['列宁'],
        page_start: 420,
        page_end: 430,
        dates: [{ year: 1915 }],
      },
      {
        title: '关于费尔巴哈全集和黑格尔全集的卷次札记',
        authors: ['列宁'],
        page_start: 431,
        page_end: 431,
        is_range_date: true,
        dates: [
          { year: 1914, month: 9 },
          { year: 1914, month: 12 },
        ],
      },
      {
        title: '费尔巴哈《对莱布尼茨哲学的叙述、分析和批判》一书摘要',
        authors: ['列宁'],
        page_start: 432,
        page_end: 446,
        dates: [{ year: 1915 }],
      },
      {
        title: '普连厄《马克思和黑格尔》一书札记',
        authors: ['列宁'],
        page_start: 447,
        page_end: 450,
        dates: [{ year: 1916 }],
      },
      {
        title: '读书札记',
        authors: ['列宁'],
        page_start: 451,
        page_end: 455,
        is_range_date: true,
        dates: [{ year: 1912 }, { year: 1916 }],
      },
      {
        title: '关于约翰·普连厄《马克思和黑格尔》的书评的札记',
        authors: ['列宁'],
        page_start: 456,
        page_end: 456,
        dates: [{ year: 1913 }],
      },
      {
        title: '关于拉·巴·培里《现代哲学倾向》的书评的札记',
        authors: ['列宁'],
        page_start: 457,
        page_end: 458,
        dates: [{ year: 1913, month: 4 }],
      },
      {
        title: '关于阿里奥塔《唯心主义对科学的反动》的书评的札记',
        authors: ['列宁'],
        page_start: 459,
        page_end: 460,
        dates: [{ year: 1913 }],
      },
      {
        title: '关于希法亭（在《金融资本》一书中）论及马赫的言论的札记',
        authors: ['列宁'],
        page_start: 461,
        page_end: 461,
        dates: [{ year: 1916, month: 6 }],
      },
      {
        title: '普列汉诺夫《马克思主义的基本问题》一书批注',
        authors: ['列宁'],
        page_start: 464,
        page_end: 468,
        dates: [{ year: 1908, month: 5 }],
      },
      {
        title: '莱伊《现代哲学》一书批注',
        authors: ['列宁'],
        page_start: 469,
        page_end: 543,
        dates: [{ year: 1909 }],
      },
      {
        title: '德波林〈辩证唯物主义》一书批注',
        authors: ['列宁'],
        page_start: 544,
        page_end: 552,
        dates: [{ year: 1909 }],
      },
      {
        title: '舒里雅齐柯夫《西欧哲学对资本主义的辩护》一书批注',
        authors: ['列宁'],
        page_start: 553,
        page_end: 571,
        dates: [{ year: 1908 }],
      },
      {
        title: '普列汉诺夫《尼·加·车尔尼雪夫斯基》一书批注',
        authors: ['列宁'],
        page_start: 572,
        page_end: 633,
        is_range_date: true,
        dates: [
          { year: 1909, month: 10 },
          { year: 1911, month: 4 },
        ],
      },
      { title: '注释', authors: [], page_start: 634, page_end: 659, dates: [] },
      {
        title: '列宁在《哲学笔记》中引用和提到的书报杂志索引',
        authors: [],
        page_start: 660,
        page_end: 680,
        dates: [],
      },
      {
        title: '人名索引',
        authors: [],
        page_start: 681,
        page_end: 700,
        dates: [],
      },
      {
        title: '名目索引',
        authors: [],
        page_start: 701,
        page_end: 717,
        dates: [],
      },
    ],
    ocr: { content_thresholds: [0.132, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives5/0aade93c-c356-46d2-9807-b567596b7e45.pdf',
};
