export default {
  entity: {
    id: '0b2f26ed-ad29-48e7-9c89-446932a97ab0',
    name: '中共党史教学参考资料 第27册 “文化大革命”参考资料 下册（1988年）',
    internal: true,
    official: true,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/0b2f26ed-ad29-48e7-9c89-446932a97ab0.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '一九七三年新年献词',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        dates: [{ year: 1973, month: 1, day: 1 }],
        page_start: 13,
        page_end: 15,
      },
      {
        title: '要学外国的长处',
        authors: ['周恩来'],
        dates: [{ year: 1973, month: 2, day: 26 }],
        page_start: 15,
        page_end: 15,
      },
      {
        title: '北京、上海、天津大批先进分子被吸收人党',
        authors: [],
        dates: [{ year: 1973, month: 6, day: 30 }],
        page_start: 16,
        page_end: 19,
      },
      {
        title: '一定要把“五·七”干校办好',
        authors: ['《人民日报》社论'],
        dates: [{ year: 1973, month: 7, day: 11 }],
        page_start: 19,
        page_end: 21,
      },
      {
        title: '进一步做好知识青年上山下乡的工作',
        authors: ['《人民日报》社论'],
        dates: [{ year: 1973, month: 8, day: 7 }],
        page_start: 21,
        page_end: 22,
      },
      {
        title: '《人民日报》转载《一份发人深省的答卷》的编者按语',
        authors: [],
        dates: [{ year: 1973, month: 8, day: 10 }],
        page_start: 23,
        page_end: 23,
      },
      {
        title: '《辽宁日报》发表《一份发人深省的答卷》的编者按语',
        authors: [],
        dates: [{ year: 1973, month: 7, day: 19 }],
        page_start: 23,
        page_end: 23,
      },
      {
        title: '张铁生信原件',
        authors: ['张铁生'],
        dates: [{ year: 1973, month: 6, day: 30 }],
        page_start: 24,
        page_end: 24,
      },
      {
        title: '一个反革命的政治骗局——“四人帮”炮制《答卷》作者这个假典型的调查',
        authors: ['《辽宁日报》记者', '《人民日报》记者'],
        dates: [{ year: 1976, month: 11, day: 30 }],
        page_start: 25,
        page_end: 27,
      },
      {
        title: '北京大学教育革命深人发展',
        authors: [],
        dates: [{ year: 1973, month: 8, day: 20 }],
        page_start: 27,
        page_end: 29,
      },
      {
        title: '中共中央批准《关于林彪反党集团反革命罪行的审查报告》的决议',
        authors: [],
        dates: [{ year: 1973, month: 8, day: 20 }],
        page_start: 29,
        page_end: 29,
      },
      {
        title: '关于林彪反党集团反革命罪行的审查报告',
        authors: ['中央专案组'],
        dates: [{ year: 1973, month: 7, day: 10 }],
        page_start: 29,
        page_end: 31,
      },
      {
        title: '中共中央作出《关于恢复李雪峰同志党籍的决定》',
        authors: [],
        dates: [],
        page_start: 32,
        page_end: 32,
      },
      {
        title: '要记取“左”倾危害的教训',
        authors: [],
        dates: [],
        page_start: 32,
        page_end: 32,
      },
      {
        title: '在中国共产党第十次全国代表大会上的报告',
        authors: ['周恩来'],
        dates: [{ year: 1973, month: 8, day: 24 }],
        page_start: 33,
        page_end: 40,
      },
      {
        title: '关于修改党章的报告',
        authors: ['王洪文'],
        dates: [{ year: 1973, month: 8, day: 24 }],
        page_start: 40,
        page_end: 43,
      },
      {
        title: '中国共产党章程',
        authors: [],
        dates: [{ year: 1973, month: 8, day: 28 }],
        page_start: 43,
        page_end: 46,
      },
      {
        title: '中国共产党第十次全国代表大会新闻公报',
        authors: [],
        dates: [{ year: 1973, month: 8, day: 29 }],
        page_start: 46,
        page_end: 48,
      },
      {
        title: '中国共产党第十届中央委员会第一次全体会议新闻公报',
        authors: [],
        dates: [{ year: 1973, month: 8, day: 30 }],
        page_start: 48,
        page_end: 49,
      },
      {
        title: '隔家和儒家的反动思想',
        authors: ['北京大学大批判组', '清华大学大批判组'],
        dates: [{ year: 1973, month: 9, day: 4 }],
        page_start: 49,
        page_end: 53,
      },
      {
        title: '“焚书坑儒”辩',
        authors: ['施丁'],
        dates: [{ year: 1973, month: 9, day: 28 }],
        page_start: 53,
        page_end: 56,
      },
      {
        title: '论尊儒反法',
        authors: ['石仓'],
        dates: [{ year: 1973, month: 10, day: 1 }],
        page_start: 56,
        page_end: 64,
      },
      {
        title: '右倾机会主义和孔子思想',
        authors: ['动云戈'],
        dates: [{ year: 1973, month: 11, day: 1 }],
        page_start: 64,
        page_end: 68,
      },
      {
        title: '一个小学生的来信和日记摘抄',
        authors: [],
        dates: [{ year: 1973, month: 12, day: 28 }],
        page_start: 68,
        page_end: 71,
      },
      {
        title: '揭穿一个政治骗局——《一个小学生的来信和日记摘抄》真相',
        authors: ['《人民日报》记者'],
        dates: [{ year: 1978, month: 5, day: 21 }],
        page_start: 71,
        page_end: 74,
      },
      {
        title: '一九七四年元旦献词',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        dates: [{ year: 1974, month: 1, day: 1 }],
        page_start: 75,
        page_end: 77,
      },
      {
        title: '清华大学党委作出关于“反右倾回潮运动”问题的决议',
        authors: [],
        dates: [],
        page_start: 77,
        page_end: 78,
      },
      {
        title: '既要讲批评又要讲谅解——空军某部航修厂党委搞好革命团结的体会',
        authors: ['《解放军报》通讯员'],
        dates: [{ year: 1974, month: 1, day: 17 }],
        page_start: 78,
        page_end: 79,
      },
      {
        title: '这样介绍“体会”对吗？——对《既要讲批评又要讲谅解》一文的意见',
        authors: ['牛乾一', '胡兴培', '罗志成', '王夙山'],
        dates: [{ year: 1974, month: 2, day: 15 }],
        page_start: 79,
        page_end: 81,
      },
      {
        title: '“四人帮”勒令《解放军报》变相停刊事件真相',
        authors: ['《解放军报》记者'],
        dates: [{ year: 1976, month: 12, day: 19 }],
        page_start: 81,
        page_end: 84,
      },
      {
        title: '中共中央关于转发《林彪与孔孟之道》（材料之一）的通知',
        authors: [],
        dates: [{ year: 1974, month: 1, day: 18 }],
        page_start: 84,
        page_end: 84,
      },
      {
        title: '林彪与孔孟之道（材料之一）',
        authors: ['北京大学', '清华大学'],
        dates: [{ year: 1973, month: 12, day: null }],
        page_start: 85,
        page_end: 102,
        ocr: { vsplit: 0.4 },
      },
      {
        title:
          '江青、姚文元、迟群、谢静宜在中央直属机关和国家机关批林批孔动员大会上的讲话',
        authors: ['江青', '姚文元', '迟群', '谢静宜'],
        dates: [{ year: 1974, month: 1, day: 25 }],
        page_start: 102,
        page_end: 121,
      },
      {
        title: '玩火者必自焚——“四人帮”军乱军的反革命“放火烧荒”事件始末',
        authors: ['《解放军报》记者'],
        dates: [{ year: 1976, month: 12, day: 14 }],
        page_start: 109,
        page_end: 125,
      },
      {
        title: '林彪与孔孟之道',
        authors: ['北京大学大批判组', '清华大学大批判组'],
        dates: [{ year: 1974, month: 2, day: 1 }],
        page_start: 126,
        page_end: 131,
      },
      {
        title: '广泛深入开展批林批孔的斗争',
        authors: ['《红旗》杂志短评'],
        dates: [{ year: 1974, month: 2, day: 1 }],
        page_start: 131,
        page_end: 133,
      },
      {
        title: '继续革命反对复辟——评林彪效法孔老二“克己复礼”',
        authors: ['《文汇报》评论员'],
        dates: [{ year: 1974, month: 2, day: 10 }],
        page_start: 133,
        page_end: 135,
      },
      {
        title: '中共中央关于“走后门”问题的通知',
        authors: [],
        dates: [{ year: 1974, month: 2, day: 20 }],
        page_start: 135,
        page_end: 136,
      },
      {
        title: '批“克已复礼”——林彪妄图复辟资本主义的反动纲领',
        authors: ['《人民日报》社论'],
        dates: [{ year: 1974, month: 2, day: 20 }],
        page_start: 136,
        page_end: 137,
      },
      {
        title: '评晋剧《三上桃峰》',
        authors: ['初澜'],
        dates: [{ year: 1974, month: 2, day: 28 }],
        page_start: 137,
        page_end: 141,
      },
      {
        title: '再批“克已复礼”',
        authors: ['《人民日报》社论'],
        dates: [{ year: 1974, month: 3, day: 15 }],
        page_start: 142,
        page_end: 143,
      },
      {
        title: '孔丘其人',
        authors: ['北京大学大批判组', '清华大学大批判组'],
        dates: [{ year: 1974, month: 4, day: 1 }],
        page_start: 143,
        page_end: 146,
      },
      {
        title: '中共中央关于批林批孔运动几个问题的通知',
        authors: [],
        dates: [{ year: 1974, month: 4, day: 10 }],
        page_start: 147,
        page_end: 147,
      },
      {
        title: '在联大第六届特别会议上的发言',
        authors: ['邓小平'],
        dates: [{ year: 1974, month: 4, day: 10 }],
        page_start: 147,
        page_end: 152,
      },
      {
        title: '中共中央关于批林批孔运动几个政策问题的通知',
        authors: [],
        dates: [{ year: 1974, month: 5, day: 18 }],
        page_start: 152,
        page_end: 153,
      },
      {
        title: '江青在“天津市儒法斗争史报告会”上的讲话',
        authors: ['江青'],
        dates: [{ year: 1974, month: 6, day: 19 }],
        page_start: 153,
        page_end: 160,
      },
      {
        title: '“四人帮”在批林批孔中是怎样搞篡党夺权阴谋的',
        authors: ['郑攀理', '李文'],
        dates: [{ year: 1977, month: 1, day: 30 }],
        page_start: 1,
        page_end: 1,
      },
      {
        title: '“四人帮”尊法丑剧的幕前幕后',
        authors: ['《人民教育》编辑部', '《历史研究》编辑部'],
        dates: [{ year: 1978 }],
        page_start: 163,
        page_end: 174,
      },
      {
        title: '为哪条教育路线唱赞歌？——评湘剧《园丁之歌》',
        authors: ['初澜'],
        dates: [{ year: 1974, month: 8, day: 4 }],
        page_start: 174,
        page_end: 177,
      },
      {
        title:
          '中共中央转发军事科学院编的《批判林彪资产阶级军事路线的若干问题》的通知',
        authors: [],
        dates: [{ year: 1974, month: 8, day: 5 }],
        page_start: 177,
        page_end: 177,
      },
      {
        title: '中共中央关于为贺龙同志恢复名誉的通知',
        authors: [],
        dates: [{ year: 1974, month: 9, day: 29 }],
        page_start: 177,
        page_end: 178,
      },
      {
        title: '中央专案审查小组关于为贺龙同志恢复名誉问题的报告',
        authors: ['中央专案审查小组'],
        dates: [{ year: 1974, month: 9, day: 13 }],
        page_start: 178,
        page_end: 180,
      },
      {
        title: '元帅之死——贺龙同志被林、江反革命集团迫害致死前后',
        authors: ['胡思升'],
        dates: [{ year: 1980, month: 12, day: 13 }],
        page_start: 180,
        page_end: 183,
      },
      {
        title: '贺龙被害内幕——“文化大革命”期间林彪、江青一伙迫害贺龙元帅记实',
        authors: ['杨金路', '江海洋'],
        dates: [{ year: 1986 }],
        page_start: 183,
        page_end: 201,
      },
      {
        title: '中共中央关于准备在最近期间召开第四届全国人民代表大会的通知',
        authors: [],
        dates: [{ year: 1974, month: 10, day: 11 }],
        page_start: 202,
        page_end: 202,
      },
      {
        title: '长沙诬告前后——特别法庭第一审判庭侧记之一',
        authors: ['纪希展', '林钢', '鲁南'],
        dates: [],
        page_start: 203,
        page_end: 206,
      },
      {
        title: '一出反革命闹剧——“四人帮”炮制“风庆轮问题”的真相',
        authors: ['交通部大批判组'],
        dates: [{ year: 1977, month: 1, day: 17 }],
        page_start: 206,
        page_end: 1,
      },
      {
        title: '中共中央转发军事科学院编的《批判林彪的“六个战术原则”》的通知',
        authors: [],
        dates: [{ year: 1974, month: 12, day: 19 }],
        page_start: 209,
        page_end: 210,
      },
      {
        title: '一九七五年新年献词',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        dates: [{ year: 1975, month: 1, day: 1 }],
        page_start: 210,
        page_end: 212,
      },
      {
        title: '中共中央关于邓小平同志任职的通知',
        authors: [],
        dates: [{ year: 1975, month: 1, day: 5 }],
        page_start: 212,
        page_end: 212,
      },
      {
        title: '政府工作报告',
        authors: ['周思来'],
        dates: [{ year: 1975, month: 1, day: 13 }],
        page_start: 212,
        page_end: 216,
      },
      {
        title: '关于修改宪法的报告',
        authors: ['张春桥'],
        dates: [{ year: 1975, month: 1, day: 13 }],
        page_start: 216,
        page_end: 218,
      },
      {
        title: '中共中央关于禁止抢夺武器问题的通知',
        authors: [],
        dates: [{ year: 1975, month: 1, day: 17 }],
        page_start: 219,
        page_end: 219,
      },
      {
        title: '中国共产党第十届中央委员会第二次全体会议公报',
        authors: [],
        dates: [{ year: 1975, month: 1, day: 17 }],
        page_start: 219,
        page_end: 219,
      },
      {
        title: '中华人民共和国第四届全国人民代表大会第一次会议新闻公报',
        authors: [],
        dates: [{ year: 1975, month: 1, day: 17 }],
        page_start: 220,
        page_end: 221,
      },
      {
        title: '中华人民共和国全国人民代表大会公告',
        authors: [],
        dates: [{ year: 1975, month: 1, day: 17 }],
        page_start: 221,
        page_end: 222,
      },
      {
        title: '中华人民共和国全国人民代表大会公告',
        authors: [],
        dates: [{ year: 1975, month: 1, day: 17 }],
        page_start: 222,
        page_end: 223,
      },
      {
        title: '中华人民共和国宪法',
        authors: [],
        dates: [{ year: 1975, month: 1, day: 17 }],
        page_start: 223,
        page_end: 228,
      },
      {
        title:
          '中华人民共和国第四届全国人民代表大会第一次会议关于政府工作报告的决议',
        authors: [],
        dates: [{ year: 1975, month: 1, day: 17 }],
        page_start: 228,
        page_end: 228,
      },
      {
        title: '中华人民共和国全国人民代表大会公告',
        authors: [],
        dates: [{ year: 1975, month: 1, day: 19 }],
        page_start: 228,
        page_end: 229,
      },
      {
        title:
          '四届人大常委会举行第一次会议任命江华为最高人民法院院长任命姬鹏飞为四届人大常委会秘书长',
        authors: [],
        dates: [{ year: 1975, month: 1, day: 20 }],
        page_start: 229,
        page_end: 229,
      },
      {
        title: '中共中央关于取消军委办公会议，成立中央军委常委的通知',
        authors: [],
        dates: [{ year: 1975, month: 2, day: 5 }],
        page_start: 230,
        page_end: 230,
      },
      {
        title: '学好无产阶级专政的理论',
        authors: ['《人民日报》社论'],
        dates: [{ year: 1975, month: 2, day: 9 }],
        page_start: 230,
        page_end: 231,
      },
      {
        title: '中共中央批转一九七五年国民经济计划的通知',
        authors: [],
        dates: [{ year: 1975, month: 2, day: 10 }],
        page_start: 232,
        page_end: 232,
      },
      {
        title: '中共中央关于学习毛主席关于理论问题的重要指示的通知',
        authors: [],
        dates: [{ year: 1975, month: 2, day: 18 }],
        page_start: 232,
        page_end: 233,
      },
      {
        title: '马克思恩格斯列宁论无产阶级专政',
        authors: [],
        dates: [{ year: 1975, month: 2, day: 22 }],
        page_start: 233,
        page_end: 243,
      },
      {
        title: '张春桥在全军各大单位政治部主任座谈会上的讲话记录稿',
        authors: ['张春桥'],
        dates: [{ year: 1975, month: 3, day: 1 }],
        page_start: 243,
        page_end: 246,
      },
      {
        title: '“四人帮”上演反“经验主义”丑剧的前前后后',
        authors: ['新华社记者述评'],
        dates: [{ year: 1977, month: 3, day: 2 }],
        page_start: 247,
        page_end: 1,
      },
      {
        title: '论林彪反党集团的社会基础',
        authors: ['姚文元'],
        dates: [{ year: 1975, month: 3, day: 1 }],
        page_start: 250,
        page_end: 255,
      },
      {
        title:
          '“四人帮”同林彪一样都是党夺权的阴谋家野心家——姚文元的反党文章《论林彪反党集团的社会基础》和“四人帮”的反革命活动',
        authors: [],
        dates: [{ year: 1976, month: 12, day: 4 }],
        page_start: 255,
        page_end: 260,
      },
      {
        title: '中共中央关于加强铁路工作的决定',
        authors: [],
        dates: [{ year: 1975, month: 3, day: 5 }],
        page_start: 260,
        page_end: 261,
      },
      {
        title: '论对资产阶级的全面专政',
        authors: ['张春桥'],
        dates: [{ year: 1975, month: 4, day: 1 }],
        page_start: 261,
        page_end: 267,
      },
      {
        title:
          '无产阶级专政和社会主义民主——批判张春桥《论对资产阶级的全面专政》',
        authors: ['《红旗》杂志特约评论员'],
        dates: [{ year: 1978 }],
        page_start: 267,
        page_end: 274,
      },
      {
        title: '迟群传达江青一九七五年四月四日的电话“指示”',
        authors: [],
        dates: [],
        page_start: 274,
        page_end: 275,
      },
      {
        title:
          '毛泽东对新华社《关于报导学习无产阶级专政理论问题的请示报告》的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1975, month: 4, day: 23 }],
        page_start: 275,
        page_end: 275,
      },
      {
        title: '毛泽东在中央军委关于贺诚任职请示报告上的批语',
        authors: ['毛泽东'],
        dates: [{ year: 1975, month: 5, day: 17 }],
        page_start: 275,
        page_end: 275,
      },
      {
        title: '中共中央关于努力完成今年钢铁生产计划的指示',
        authors: [],
        dates: [{ year: 1975, month: 6, day: 4 }],
        page_start: 276,
        page_end: 277,
      },
      {
        title: '中共冶金工业部核心小组关于迅速把钢铁工业搞上去的报告',
        authors: ['中共冶金工业部核心小组'],
        dates: [{ year: 1975, month: 5, day: 22 }],
        page_start: 277,
        page_end: 280,
      },
      {
        title: '邓小平在中央军委扩大会议上的讲话',
        authors: ['邓小平'],
        dates: [{ year: 1975, month: 7, day: 14 }],
        page_start: 280,
        page_end: 283,
      },
      {
        title: '叶剑英在中央军委扩大会议上的总结讲话',
        authors: ['叶剑英'],
        dates: [{ year: 1975, month: 7, day: 15 }],
        page_start: 284,
        page_end: 286,
      },
      {
        title: '丹心向党功炳千秋',
        authors: ['杨成武'],
        dates: [{ year: 1986, month: 11, day: 5 }],
        page_start: 286,
        page_end: 289,
      },
      {
        title: '中共中央转发国务院《关于今年上半年工业生产情况的报告》',
        authors: [],
        dates: [{ year: 1975, month: 7, day: 17 }],
        page_start: 290,
        page_end: 290,
      },
      {
        title: '关于今年上半年工业生产情况的报告',
        authors: ['国务院'],
        dates: [{ year: 1975, month: 7, day: 12 }],
        page_start: 290,
        page_end: 1,
      },
      {
        title: '毛泽东对电影《创业》的作者张天民来信的批语',
        authors: ['毛泽东'],
        dates: [{ year: 1975, month: 7, day: 25 }],
        page_start: 292,
        page_end: 292,
      },
      {
        title: '全国铁路一九七五年上半年货运量创历史同期最高水平',
        authors: ['新华社记者述评'],
        dates: [{ year: 1975, month: 7, day: 29 }],
        page_start: 292,
        page_end: 294,
      },
      {
        title: '毛泽东关于《水浒》的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1975, month: 8, day: 14 }],
        page_start: 294,
        page_end: 295,
      },
      {
        title: '重视对《水浒》的评论',
        authors: ['《红旗》杂志短评'],
        dates: [{ year: 1975, month: 8, day: 28 }],
        page_start: 295,
        page_end: 296,
      },
      {
        title: '评《水浒》',
        authors: ['竺方明'],
        dates: [{ year: 1975, month: 8, day: 31 }],
        page_start: 296,
        page_end: 301,
      },
      {
        title: '江青在接见大寨大队干部和社员时的讲话记录稿',
        authors: ['江青'],
        dates: [{ year: 1975, month: 9, day: 12 }],
        page_start: 301,
        page_end: 308,
      },
      {
        title: '“评《水浒》运动”到底是怎么一回事？',
        authors: ['人民文学出版社古典文学编辑室', '《人民日报》文艺部'],
        dates: [{ year: 1978, month: 8, day: 11 }],
        page_start: 308,
        page_end: 313,
      },
      {
        title: '全国农业学大寨会议在昔阳隆重开幕',
        authors: [],
        dates: [{ year: 1975, month: 9, day: 15 }],
        page_start: 313,
        page_end: 315,
      },
      {
        title: '中共中央关于大力发展养猪业的通知',
        authors: [],
        dates: [{ year: 1975, month: 9, day: 16 }],
        page_start: 316,
        page_end: 316,
      },
      {
        title: '纪念长征胜利四十周年',
        authors: ['《人民日报》编辑部', '《解放军报》编辑部'],
        dates: [{ year: 1975, month: 10, day: 19 }],
        page_start: 316,
        page_end: 317,
      },
      {
        title: '普及大寨县',
        authors: ['《人民日报》社论'],
        dates: [{ year: 1975, month: 10, day: 21 }],
        page_start: 318,
        page_end: 319,
      },
      {
        title: '结合评论《水浒》深人学习理论',
        authors: ['池恒'],
        dates: [{ year: 1975, month: 11, day: 1 }],
        page_start: 319,
        page_end: 321,
      },
      {
        title: '中共中央关于转发《打招呼的讲话要点》的通知',
        authors: [],
        dates: [{ year: 1975, month: 11, day: 26 }],
        page_start: 321,
        page_end: 321,
      },
      {
        title: '打招呼的讲话要点',
        authors: [],
        dates: [],
        page_start: 322,
        page_end: 322,
      },
      {
        title: '刘冰等给毛主席写信符合党章内容属实清华大学党委公开纠正这一错案',
        authors: [],
        dates: [{ year: 1978, month: 11, day: 23 }],
        page_start: 322,
        page_end: 323,
      },
      {
        title: '教育革命的方向不容篡改',
        authors: ['北京大学大批判组', '清华大学大批判组'],
        dates: [{ year: 1975, month: 12, day: 1 }],
        page_start: 323,
        page_end: 329,
      },
      {
        title:
          '一株反党乱校的大毒草——批判北京大学、清华大学大批判组教育部大批判组的《教育革命的方向不容篡改》',
        authors: [],
        dates: [{ year: 1977, month: 10, day: 21 }],
        page_start: 329,
        page_end: 333,
      },
      {
        title: '反修防修的伟大革命',
        authors: ['梁效'],
        dates: [{ year: 1975, month: 12, day: 9 }],
        page_start: 333,
        page_end: 336,
      },
      {
        title: '路线正确破浪前进——喜看朝阳农学院教育革命的大好形势',
        authors: ['《人民日报》记者述评'],
        dates: [{ year: 1975, month: 12, day: 13 }],
        page_start: 336,
        page_end: 339,
      },
      {
        title: '世上无难事只要肯登攀',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        dates: [{ year: 1976, month: 1, day: 1 }],
        page_start: 340,
        page_end: 342,
      },
      {
        title: '评论《水浒》的现实意义',
        authors: ['尹铭'],
        dates: [{ year: 1976, month: 1, day: 1 }],
        page_start: 342,
        page_end: 344,
      },
      {
        title: '张铁生的新“答卷”——对教育界某刊物上奇谈怪论的批判',
        authors: ['《辽宁青年》杂志记者', '新华社记者'],
        dates: [{ year: 1976, month: 1, day: 6 }],
        page_start: 344,
        page_end: 346,
      },
      {
        title:
          '北大校园风雷动——反击右倾翻案风的教育革命大辩论，提高北京大学师生阶级斗争和路线斗争觉悟',
        authors: [],
        dates: [{ year: 1976, month: 1, day: 7 }],
        page_start: 346,
        page_end: 347,
      },
      {
        title: '中共中央、人大常委会、国务院让告周恩来同志进世',
        authors: [],
        dates: [{ year: 1976, month: 1, day: 8 }],
        page_start: 347,
        page_end: 348,
      },
      {
        title: '在最后的日子里——记病重住院期间的周恩来同志',
        authors: ['高文谦'],
        dates: [{ year: 1986, month: 1, day: 8 }],
        page_start: 348,
        page_end: 353,
      },
      {
        title: '批判极左思潮所做出的不懈努力——读《周恩来选集》下卷',
        authors: ['文谦'],
        dates: [{ year: 1984, month: 12, day: 18 }],
        page_start: 353,
        page_end: 356,
      },
      {
        title: '周恩来同志治丧委员会名单',
        authors: [],
        dates: [{ year: 1976, month: 1, day: 8 }],
        page_start: 356,
        page_end: 356,
      },
      {
        title: '中共中央、国务院通知隆重追悼周恩来同志',
        authors: [],
        dates: [{ year: 1976, month: 1, day: 9 }],
        page_start: 356,
        page_end: 356,
      },
      {
        title: '周恩来同志治丧委员会公告',
        authors: [],
        dates: [{ year: 1976, month: 1, day: 9 }],
        page_start: 357,
        page_end: 357,
      },
      {
        title: '党和国家领导人以及首都群众代表向周恩来同志的遗体告别',
        authors: [],
        dates: [{ year: 1976, month: 1, day: 11 }],
        page_start: 357,
        page_end: 358,
      },
      {
        title: '首都人民举行隆重吊唁仪式沉痛悼念周恩来同志',
        authors: [],
        dates: [{ year: 1976, month: 1, day: 14 }],
        page_start: 358,
        page_end: 360,
      },
      {
        title: '大辩论带来大变化——清华大学教育革命和各项工作出现新面貌',
        authors: ['新华社记者', '《人民日报》记者'],
        dates: [{ year: 1976, month: 1, day: 14 }],
        page_start: 361,
        page_end: 362,
      },
      {
        title:
          '磨不灭的光辉砍不断的怀念——新华社记者对姚文元破坏悼念周总理的宣传报道的控拆',
        authors: ['新华社记者'],
        dates: [{ year: 1977, month: 1, day: 6 }],
        page_start: 362,
        page_end: 365,
      },
      {
        title: '党和国家领导人以及首都各界群众隆重举行周恩来同志追悼大会',
        authors: [],
        dates: [{ year: 1976, month: 1, day: 15 }],
        page_start: 366,
        page_end: 370,
      },
      {
        title: '邓小平副主席在周恩来同志追掉大会上致障词',
        authors: ['邓小平'],
        dates: [{ year: 1976, month: 1, day: 15 }],
        page_start: 370,
        page_end: 372,
      },
      {
        title: '中共中央通知',
        authors: [],
        dates: [{ year: 1976, month: 2, day: 2 }],
        page_start: 373,
        page_end: 373,
      },
      {
        title: '一九七六年二月三日有感',
        authors: ['张春桥'],
        dates: [{ year: 1976, month: 2, day: 3 }],
        page_start: 373,
        page_end: 373,
      },
      {
        title:
          '无产阶级文化大革命的继续和深入——喜看清华大学教育革命大辩论破浪前进',
        authors: [],
        dates: [{ year: 1976, month: 2, day: 6 }],
        page_start: 373,
        page_end: 375,
      },
      {
        title: '孔丘之忧',
        authors: ['高路'],
        dates: [{ year: 1976, month: 2, day: 13 }],
        page_start: 375,
        page_end: 375,
      },
      {
        title: '要继续批孔',
        authors: ['幸成'],
        dates: [{ year: 1976, month: 2, day: 13 }],
        page_start: 376,
        page_end: 377,
      },
      {
        title: '再论孔丘其人',
        authors: ['北京大学大批判组', '清华大学大批判组'],
        dates: [{ year: 1976, month: 2, day: 24 }],
        page_start: 377,
        page_end: 380,
      },
      {
        title: '评“三项指示为纲”',
        authors: ['梁效', '任明'],
        dates: [{ year: 1976, month: 2, day: 29 }],
        page_start: 381,
        page_end: 382,
      },
      {
        title: '从资产阶级民主派到走资派',
        authors: [],
        dates: [{ year: 1976, month: 3, day: 1 }],
        page_start: 1,
        page_end: 1,
      },
      {
        title: '江青在打招呼会议期间擅自召集的十二省、区会议上的讲话记录稿',
        authors: ['江青'],
        dates: [{ year: 1976, month: 3, day: 2 }],
        page_start: 386,
        page_end: 396,
      },
      {
        title:
          '中共中央关于转发华国锋在中央召集的各省、市、自治区和各大军区同志会议上讲话的通知',
        authors: [],
        dates: [{ year: 1976, month: 3, day: 3 }],
        page_start: 397,
        page_end: 397,
      },
      {
        title: '华国锋同志的讲话',
        authors: ['华国锋'],
        dates: [{ year: 1976, month: 2, day: 25 }],
        page_start: 397,
        page_end: 398,
      },
      {
        title: '《文汇报》删去了新华社关于向雷锋学习报道中的周恩来的题词',
        authors: [],
        dates: [{ year: 1976, month: 3, day: 5 }],
        page_start: 398,
        page_end: 399,
      },
      {
        title: '走资派还在走我们就要同他斗',
        authors: [],
        dates: [{ year: 1976, month: 3, day: 25 }],
        page_start: 399,
        page_end: 400,
      },
      {
        title:
          '光明与黑暗的一场大搏斗——追记万众声讨“四人帮”制造的《文汇报》“三·五”、“三·二五”反革命事件',
        authors: ['《文汇报》记者'],
        dates: [{ year: 1978, month: 11, day: 18 }],
        page_start: 400,
        page_end: 404,
      },
      {
        title: '“克已复礼”再批判',
        authors: ['梁效'],
        dates: [{ year: 1976, month: 3, day: 6 }],
        page_start: 404,
        page_end: 408,
      },
      {
        title: '翻案不得人心',
        authors: ['《人民日报》社论'],
        dates: [{ year: 1976, month: 3, day: 10 }],
        page_start: 408,
        page_end: 409,
      },
      {
        title: '中共中央关于在反击右倾翻案风中各地禁止来京上访的通知',
        authors: [],
        dates: [{ year: 1976, month: 3, day: 24 }],
        page_start: 410,
        page_end: 410,
      },
      {
        title: '一个复辟资本主义的总纲——《论全党全国各项工作的总纲》部析',
        authors: ['程越'],
        dates: [{ year: 1976, month: 4, day: 1 }],
        page_start: 410,
        page_end: 414,
      },
      {
        title: '批判洋奴哲学',
        authors: ['方海'],
        dates: [{ year: 1976, month: 4, day: 1 }],
        page_start: 414,
        page_end: 416,
      },
      {
        title: '“四人帮”是地地道道的洋奴',
        authors: ['中共国家计委核心小组'],
        dates: [],
        page_start: 416,
        page_end: 417,
      },
      {
        title: '江青崇洋媚外里通外国的一出丑剧',
        authors: ['邵兵'],
        dates: [{ year: 1977, month: 1, day: 16 }],
        page_start: 417,
        page_end: 420,
      },
      {
        title: '满纸洋奴腔一部伪造史——评江青在广州对外国“作家”的一次谈话',
        authors: ['广州部队大批判组'],
        dates: [{ year: 1977, month: 3, day: 26 }],
        page_start: 420,
        page_end: 1,
      },
      {
        title: '《汇报提纲》出笼的前前后后',
        authors: ['康立', '延风'],
        dates: [{ year: 1976, month: 4, day: null }],
        page_start: 424,
        page_end: 428,
      },
      {
        title: '中共中央关于南京大字报问题的电话通知',
        authors: [],
        dates: [{ year: 1976, month: 4, day: 1 }],
        page_start: 429,
        page_end: 429,
      },
      {
        title: '吴德在天安门广场广播讲话',
        authors: ['吴德'],
        dates: [{ year: 1976, month: 4, day: 5 }],
        page_start: 429,
        page_end: 429,
      },
      {
        title: '中共中央关于华国锋同志任中共中央第一副主席、国务院总理的决议',
        authors: [],
        dates: [{ year: 1976, month: 4, day: 7 }],
        page_start: 430,
        page_end: 430,
      },
      {
        title: '中共中央关于撤销邓小平党内外一切职务的决议',
        authors: [],
        dates: [{ year: 1976, month: 4, day: 7 }],
        page_start: 430,
        page_end: 430,
      },
      {
        title: '天安门广场的反革命政治事件',
        authors: ['《人民日报》工农兵通讯员', '《人民日报》记者'],
        dates: [{ year: 1976, month: 4, day: 8 }],
        page_start: 430,
        page_end: 432,
      },
      {
        title: '天安门事件真相——把“四人帮”利用《人民日报》颠倒的历史再颠倒过来',
        authors: ['《人民日报》记者'],
        dates: [{ year: 1978, month: 11, day: 21 }],
        page_start: 432,
        page_end: 446,
      },
      {
        title: '揭露“四人帮”及其心腹炮制天安门事件报道的阴谋',
        authors: ['《新闻战线》记者'],
        dates: [{ year: 1978 }],
        page_start: 446,
        page_end: 452,
      },
      {
        title: '因参加天安门事件被捕的人没有一个反革命分子',
        authors: ['《解放军报》记者'],
        dates: [{ year: 1978, month: 11, day: 18 }],
        page_start: 452,
        page_end: 453,
      },
      {
        title: '四五运动日志',
        authors: [],
        dates: [],
        page_start: 453,
        page_end: 461,
      },
      {
        title: '伟大的胜利',
        authors: ['《人民日报》社论'],
        dates: [{ year: 1976, month: 4, day: 10 }],
        page_start: 461,
        page_end: 462,
      },
      {
        title: '天安门广场事件说明了什么？',
        authors: ['《人民日报》社论'],
        dates: [{ year: 1976, month: 4, day: 18 }],
        page_start: 462,
        page_end: 464,
      },
      {
        title: '邓小平与天安门广场反革命事件',
        authors: ['梁效'],
        dates: [{ year: 1976, month: 4, day: 28 }],
        page_start: 464,
        page_end: 466,
      },
      {
        title: '社会主义大集好——辽宁省彰武县哈尔套公社改造农村集市的调查',
        authors: ['新华社记者'],
        dates: [{ year: 1976, month: 5, day: 9 }],
        page_start: 466,
        page_end: 468,
      },
      {
        title:
          '哈尔套经验出笼的前前后后——“四人帮”在辽宁那个死党炮制“哈尔套经验”真相之一',
        authors: [
          '中共阜新市委调查组',
          '《阜新日报》记者',
          '阜新人民广播电台记者',
          '《辽宁日报》记者',
        ],
        dates: [{ year: 1977, month: 1, day: 21 }],
        page_start: 468,
        page_end: 470,
      },
      {
        title:
          '文化大革命水放光芒——纪念中共中央一九六六年五月十六日《通知》十周年',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        dates: [{ year: 1976, month: 5, day: 16 }],
        page_start: 470,
        page_end: 472,
      },
      {
        title:
          '迟群、谢静宜在清华大学机械系学员和干部学习一九七六年五月十六日两报一刊社论座谈会上的讲话',
        authors: ['迟群、谢静宜'],
        dates: [{ year: 1976, month: 5, day: 16 }],
        page_start: 472,
        page_end: 475,
      },
      {
        title:
          '一个加快复辟资本主义的《条例》——批判邓小平授意炮制的《关于加快工业发展的若干问题》',
        authors: ['吕达'],
        dates: [{ year: 1976, month: 5, day: 31 }],
        page_start: 475,
        page_end: 477,
      },
      {
        title:
          '人民解放军永远是无产阶级专政的坚强柱石——批判邓小平在军队一次会议上的讲话',
        authors: ['斌音'],
        dates: [{ year: 1976, month: 6, day: 4 }],
        page_start: 477,
        page_end: 480,
      },
      {
        title: '军事战线一场大是大非的斗争',
        authors: ['《解放军报》编辑部'],
        dates: [{ year: 1978, month: 1, day: 30 }],
        page_start: 481,
        page_end: 483,
      },
      {
        title: '十年来围绕军权问题同林彪、“四人帮”的激烈斗争',
        authors: ['军事科学院批判组'],
        dates: [{ year: 1978, month: 4, day: 3 }],
        page_start: 484,
        page_end: 488,
      },
      {
        title: '中共中央、人大常委会、国务院计告朱德同志逝世',
        authors: [],
        dates: [{ year: 1976, month: 7, day: 6 }],
        page_start: 488,
        page_end: 489,
      },
      {
        title: '朱德同志治丧委员会名单',
        authors: [],
        dates: [{ year: 1976, month: 7, day: 6 }],
        page_start: 489,
        page_end: 489,
      },
      {
        title: '朱德同志治丧委员会公告',
        authors: [],
        dates: [{ year: 1976, month: 7, day: 6 }],
        page_start: 489,
        page_end: 490,
      },
      {
        title: '首都隆重举行朱德同志追悼大会',
        authors: [],
        dates: [{ year: 1976, month: 7, day: 11 }],
        page_start: 490,
        page_end: 492,
      },
      {
        title: '华国锋第一副主席在朱德同志追悼大会上致惊词',
        authors: [],
        dates: [{ year: 1976, month: 7, day: 11 }],
        page_start: 493,
        page_end: 494,
      },
      {
        title: '最后的十年——康克清谈朱德同志',
        authors: ['康克清'],
        dates: [{ year: 1986, month: 11, day: 29 }],
        page_start: 494,
        page_end: 497,
      },
      {
        title: '河北省唐山、丰南一带发生强烈地震',
        authors: [],
        dates: [{ year: 1976, month: 7, day: 28 }],
        page_start: 497,
        page_end: 498,
      },
      {
        title: '中共中央向灾区人民发出慰问电',
        authors: [],
        dates: [{ year: 1976, month: 7, day: 28 }],
        page_start: 498,
        page_end: 498,
      },
      {
        title: '《评〈关于加快工业发展的若干问题〉》的前言',
        authors: ['北京大学大批判组', '清华大学大批判组'],
        dates: [{ year: 1976, month: 7, day: null }],
        page_start: 498,
        page_end: 499,
      },
      {
        title: '关于加快工业发展的若干问题',
        authors: [],
        dates: [{ year: 1975, month: 9, day: 2 }],
        page_start: 499,
        page_end: 510,
      },
      {
        title: '一场党夺权的反革命丑剧——评“四人帮”对《二十条》的“批判”',
        authors: ['国家计委大批判组'],
        dates: [{ year: 1977, month: 7, day: 16 }],
        page_start: 510,
        page_end: 519,
      },
      {
        title: '《评〈论全党全国各项工作的总纲〉》的前言',
        authors: ['北京大学大批判组', '清华大学大批判组'],
        dates: [{ year: 1976, month: 7, day: null }],
        page_start: 519,
        page_end: 519,
      },
      {
        title: '论全党全国各项工作的总纲',
        authors: [],
        dates: [{ year: 1975, month: 10, day: 7 }],
        page_start: 519,
        page_end: 530,
      },
      {
        title: '打着反复辟的旗号摘复辟——批判“四人帮”对《论总纲》的“批判”',
        authors: ['向群'],
        dates: [{ year: 1977, month: 7, day: 7 }],
        page_start: 530,
        page_end: 539,
      },
      {
        title: '《评〈关于科技工作的几个问题〉》的前言',
        authors: ['北京大学大批判组', '清华大学大批判组'],
        dates: [{ year: 1976, month: 7, day: null }],
        page_start: 539,
        page_end: 540,
      },
      {
        title: '关于科技工作的几个问题（汇报提纲讨论第一稿）',
        authors: [],
        dates: [{ year: 1975, month: 8, day: 11 }],
        page_start: 540,
        page_end: 543,
      },
      {
        title: '要知松高洁待到雪化时——推翻“四人帮”对《汇报提纲》的诬陷',
        authors: ['中国科学院理论组'],
        dates: [{ year: 1977, month: 6, day: 30 }],
        page_start: 543,
        page_end: 548,
      },
      {
        title:
          '以华总理为总团长的中央悬问团到达地震灾区转达毛主席、党中央的亲切关怀和慰问',
        authors: [],
        dates: [{ year: 1976, month: 8, day: 4 }],
        page_start: 549,
        page_end: 549,
      },
      {
        title:
          '“四人帮“破坏抗震救灾十恶不赦——唐山、丰南地震灾区人民怒斥王张江姚反党集团阴谋篡党夺权，不顾人民死活的滔天罪行',
        authors: ['新华社记者'],
        dates: [{ year: 1976, month: 11, day: 12 }],
        page_start: 549,
        page_end: 551,
      },
      {
        title:
          '中国共产党中央委员会、中华人民共和国全国人民代表大会常务委员会、中华人民共和国国务院、中国共产党中央军事委员会告全党全军全国各族人民书',
        authors: [],
        dates: [{ year: 1976, month: 9, day: 9 }],
        page_start: 551,
        page_end: 553,
      },
      {
        title:
          '中国共产党中央委员会、中华人民共和国全国人民代表大会常务委员会、中华人民共和国国务院、中国共产党中央军事委员会公告',
        authors: [],
        dates: [{ year: 1976, month: 9, day: 9 }],
        page_start: 553,
        page_end: 554,
      },
      {
        title: '毛泽东主席治丧委员会名单',
        authors: [],
        dates: [{ year: 1976, month: 9, day: 9 }],
        page_start: 554,
        page_end: 555,
      },
      {
        title: '张铁生、刘继业的反动言论',
        authors: [],
        dates: [{ year: 1976, month: 9, day: 9 }],
        page_start: 556,
        page_end: 560,
      },
      {
        title: '毛主席永远活在我们心中',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        dates: [{ year: 1976, month: 9, day: 16 }],
        page_start: 560,
        page_end: 562,
      },
      {
        title:
          '首都百万群众怀着极其沉痛和无限崇敬的心情隆重举行伟大的领袖和导师毛泽东主席追悼大会',
        authors: [],
        dates: [{ year: 1976, month: 9, day: 18 }],
        page_start: 562,
        page_end: 566,
      },
      {
        title:
          '在伟大的领袖和导师毛泽东主席追悼大会上中国共产党中央委员会第一副主席、国务院总理华国锋同志致悼词',
        authors: [],
        dates: [{ year: 1976, month: 9, day: 18 }],
        page_start: 566,
        page_end: 568,
      },
      {
        title: '江青在清华大学的讲话',
        authors: ['江青'],
        dates: [{ year: 1976, month: 10, day: 1 }],
        page_start: 569,
        page_end: 569,
      },
      {
        title: '王洪文在平谷县的讲话',
        authors: ['王洪文'],
        dates: [{ year: 1976, month: 10, day: 3 }],
        page_start: 569,
        page_end: 569,
      },
      {
        title: '永远按毛主席的既定方针办',
        authors: ['梁效'],
        dates: [{ year: 1976, month: 10, day: 4 }],
        page_start: 570,
        page_end: 573,
      },
      {
        title: '关于王张江姚反党集团操纵奥论工具，宣扬“按既定方针办”的一些情况',
        authors: [],
        dates: [],
        page_start: 573,
        page_end: 577,
      },
      {
        title: '灭亡前的猖狂一跳——揭穿“四人帮”伪造“临终嘱咐”的大阴谋',
        authors: ['《人民日报》编辑部'],
        dates: [{ year: 1976, month: 12, day: 17 }],
        page_start: 578,
        page_end: 584,
      },
      {
        title:
          '“四人帮“的一支反革命别动队——揭批原北京大学、清华大学“大批判组”的罪行',
        authors: ['新华社通讯员', '新华社记者'],
        dates: [{ year: 1977, month: 7, day: 13 }],
        page_start: 584,
        page_end: 588,
      },
      {
        title:
          '为“四人帮”篡党夺权鸣锣开道的急先锋——揭露“两校大批判组”的反革命面目',
        authors: [],
        dates: [{ year: 1976, month: 12, day: 18 }],
        page_start: 588,
        page_end: 590,
      },
      {
        title: '“四人帮”党夺权的急先锋——清算原上海市委写作组的反革命罪行',
        authors: ['中涛声'],
        dates: [{ year: 1977, month: 10, day: 27 }],
        page_start: 590,
        page_end: 595,
      },
      {
        title:
          '自掘攻基自造墓砖——揭批“四人帮”通过帮刊《学习与批判》制造反革命舆论的罪行',
        authors: ['新华社通讯员', '新华社记者'],
        dates: [{ year: 1977, month: 3, day: 17 }],
        page_start: 596,
        page_end: 598,
      },
      {
        title: '中共中央通知',
        authors: [],
        dates: [{ year: 1976, month: 10, day: 7 }],
        page_start: 598,
        page_end: 598,
      },
      {
        title:
          '中共中央关于华国锋同志任中国共产党中央委员会主席、中国共产党中央军事委员会主席的决议',
        authors: [],
        dates: [{ year: 1976, month: 10, day: 7 }],
        page_start: 599,
        page_end: 599,
      },
      {
        title:
          '中国共产党中央委员会、中华人民共和国全国人民代表大会常务委员会中华人民共和国国务院、中国共产党中央军事委员会关于建立伟大的领袖和导师毛泽东主席纪念堂的决定',
        authors: [],
        dates: [{ year: 1976, month: 10, day: 8 }],
        page_start: 599,
        page_end: 599,
      },
      {
        title: '中共中央关于出版《毛泽东选集》和筹备出版《毛泽东全集》的决定',
        authors: [],
        dates: [{ year: 1976, month: 10, day: 8 }],
        page_start: 599,
        page_end: 600,
      },
      {
        title: '亿万人民的共同心愿',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        dates: [{ year: 1976, month: 10, day: 10 }],
        page_start: 600,
        page_end: 601,
      },
      {
        title: '中共中央关于王洪文、张春桥、江青、姚文元反党集团事件的通知',
        authors: [],
        dates: [{ year: 1976, month: 10, day: 18 }],
        page_start: 601,
        page_end: 604,
      },
      {
        title: '向反党算权的阴谋家、野心家猛烈开火',
        authors: ['《文汇报》编辑部'],
        dates: [{ year: 1976, month: 10, day: 20 }],
        page_start: 605,
        page_end: 606,
      },
      {
        title: '上海人民喷怒声讨和揭发批判反党算权的走资派的反革命罪行',
        authors: [],
        dates: [{ year: 1976, month: 10, day: 20 }],
        page_start: 606,
        page_end: 607,
      },
      {
        title: '北京、上海广大军民连日举行声势浩大的庆祝游行',
        authors: [],
        dates: [
          { year: 1976, month: 10, day: 21 },
          { year: 1976, month: 10, day: 22 },
        ],
        page_start: 607,
        page_end: 614,
      },
      {
        title: '全国各省、自治区军民连日举行庆祝集会和游行',
        authors: [],
        dates: [{ year: 1976, month: 10, day: 23 }],
        page_start: 614,
        page_end: 617,
      },
      {
        title: '首都百万军民隆重举行庆祝太会',
        authors: [],
        dates: [{ year: 1976, month: 10, day: 24 }],
        page_start: 617,
        page_end: 621,
      },
      {
        title: '吴德在首都庆祝大会上的讲话',
        authors: ['吴德'],
        dates: [{ year: 1976, month: 10, day: 24 }],
        page_start: 621,
        page_end: 622,
      },
      {
        title: '伟大的历史性胜利',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        dates: [{ year: 1976, month: 10, day: 25 }],
        page_start: 623,
        page_end: 625,
      },
      {
        title:
          '上海军民坚决拥护党中央决定，苏振华、倪志福、彭冲三同志主持上海市的工作撤销张春桥、姚文元、王洪文在上海的党内外一切职务',
        authors: [],
        dates: [{ year: 1976, month: 10, day: 29 }],
        page_start: 625,
        page_end: 626,
      },
      {
        title:
          '“四人帮”在上海大量选拔培植亲信阴谋篡夺中央和国务院各部委的领导权',
        authors: ['新华社记者组'],
        dates: [],
        page_start: 627,
        page_end: 629,
      },
      {
        title: '民心不可欺——“四人帮”策动上海武装叛乱始末',
        authors: ['曹章', '徐绍昌', '邵观光', '张维新'],
        dates: [{ year: 1980, month: 12, day: 13 }],
        page_start: 629,
        page_end: 636,
      },
      {
        title:
          '从“文攻武卫”到“第二武装”的彻底破产——深入揭批“四人帮”破坏民兵建设的反革命罪行',
        authors: ['南京部队动员部', '南京部队群工部'],
        dates: [{ year: 1978, month: 2, day: 19 }],
        page_start: 636,
        page_end: 641,
      },
      {
        title: '十年经营顷刻瓦解——揭露“四人帮”在上海搞“第二武装”的前期后后',
        authors: ['上海警备区民兵工作理论组'],
        dates: [{ year: 1977 }],
        page_start: 641,
        page_end: 648,
      },
    ],
    ocr: { content_thresholds: [0, 0.11, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/0b2f26ed-ad29-48e7-9c89-446932a97ab0.pdf',
};
