export default {
  entity: {
    id: '0b885c01-a812-4192-b4d2-217bae67bf27',
    name: '红旗一九六九年第八期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/0b885c01-a812-4192-b4d2-217bae67bf27.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '人民军队所向无敌──纪念中国人民解放军诞生四十二周年',
        authors: [
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
          '《人民日报》编辑部',
        ],
        page_start: 8,
        page_end: 12,
        dates: [{ year: 1969, month: 8, day: 1 }],
      },
      {
        title: '永远突出无产阶级政治',
        authors: ['邵海清'],
        page_start: 13,
        page_end: 16,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '毛主席的建军路线是指引我们胜利前进的航标',
        authors: ['人民解放军海军某部航标队党支部'],
        page_start: 16,
        page_end: 19,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '用毛泽东思想武装起来的人是最大的战斗力',
        authors: ['冯全民'],
        page_start: 20,
        page_end: 22,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '我们贫下中农最热爱人民解放军',
        authors: ['姜泰元'],
        page_start: 22,
        page_end: 24,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title:
          '政权建设中的一个新问题——支左人员如何正确处理同新的领导班子的关系',
        authors: ['八三四一部队驻南口机车车辆机械厂毛泽东思想宣传队'],
        page_start: 25,
        page_end: 30,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '宗派主义是无产阶级党性的大敌',
        authors: ['洪流'],
        page_start: 31,
        page_end: 34,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '工人革命群众组织必须接受党的领导',
        authors: ['秦连才'],
        page_start: 35,
        page_end: 38,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '一个一个单位地搞好斗、批、改',
        authors: ['栗新'],
        page_start: 39,
        page_end: 42,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '学会使用唯物辩证法——向同志们介绍一组工人学哲学的文章（短评）',
        authors: ['《红旗》杂志编辑部'],
        page_start: 43,
        page_end: 44,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '创先进与“保”先进',
        authors: ['郑尚友'],
        page_start: 44,
        page_end: 46,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '学会全面地看问题',
        authors: ['洪跃工'],
        page_start: 47,
        page_end: 49,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '掌握辩证法 解决“老大难”',
        authors: ['齐学彪'],
        page_start: 47,
        page_end: 49,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '掌握辩证法 解决“老大难”',
        authors: ['齐学彪'],
        page_start: 49,
        page_end: 51,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '印染工艺改革的启示',
        authors: ['申辉年'],
        page_start: 52,
        page_end: 53,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '东风是怎样吹进门窗来的？',
        authors: ['上海国棉十七厂四纺工场工人学哲学小组'],
        page_start: 52,
        page_end: 53,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '东风是怎样吹进门窗来的？',
        authors: ['上海国棉十七厂四纺工场工人学哲学小组'],
        page_start: 54,
        page_end: 56,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '储粮储草 备战备荒——吉林伊通县柴家岗子生产队的调查报告',
        authors: [
          '四平专区革命委员会、伊通县革命委员会、伊通县人民武装部联合调查组',
        ],
        page_start: 57,
        page_end: 61,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '干部解放出来怎么办？——河北邯郸国棉三厂的调查报告',
        authors: [
          '邯郸地区革命委员会、邯郸市革命委员会、人民解放军邯郸驻军联合调查组',
        ],
        page_start: 62,
        page_end: 67,
        dates: [{ year: 1969, month: 8 }],
      },
      {
        title: '从炮制“共产主义基督教”看苏修叛徒的堕落',
        authors: ['于奋'],
        page_start: 68,
        page_end: 73,
        dates: [{ year: 1969, month: 8 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/0b885c01-a812-4192-b4d2-217bae67bf27.pdf',
};
