export default {
  entity: {
    id: '0cf7536a-2c1b-40be-89a1-8caf332a2acc',
    name: '红旗一九五九年第七期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/0cf7536a-2c1b-40be-89a1-8caf332a2acc.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '帝国主义是阿拉伯民族解放的死敌',
        authors: ['于兆力'],
        page_start: 3,
        page_end: 10,
        dates: [{ year: 1959, month: 4 }],
      },
      {
        title: '对于美国经济危机的几点看法',
        authors: ['孟用潜'],
        page_start: 11,
        page_end: 20,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 4 }],
      },
      {
        title: '按劳分配和等价交换',
        authors: ['方元'],
        page_start: 21,
        page_end: 22,
        dates: [{ year: 1959, month: 4 }],
      },
      {
        title: '人民公社的积累要适当',
        authors: ['洪行'],
        page_start: 23,
        page_end: 24,
        dates: [{ year: 1959, month: 3 }],
      },
      {
        title: '一九五八年上海工业战线上的技术革命运动',
        authors: ['马天水'],
        page_start: 25,
        page_end: 35,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 4 }],
      },
      {
        title: '农业中学的第一年',
        authors: ['欧阳惠林'],
        page_start: 36,
        page_end: 40,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 4 }],
      },
      {
        title: '关于领导农业生产的问题（通讯）',
        authors: ['周金'],
        page_start: 41,
        page_end: 47,
        dates: [{ year: 1959, month: 4 }],
      },
      {
        title: '多快好省地发展森林后备资源',
        authors: ['张子良'],
        page_start: 48,
        page_end: 49,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 4 }],
      },
      {
        title: '“哲学史”第一卷',
        authors: ['王子野'],
        page_start: 50,
        page_end: 51,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 4 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/0cf7536a-2c1b-40be-89a1-8caf332a2acc.pdf',
};
