export default {
  entity: {
    id: '0d948a84-85f8-4e30-b43d-9148bae6609d',
    name: '红旗一九七二年第十二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/0d948a84-85f8-4e30-b43d-9148bae6609d.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '做工作要敢于负责',
        authors: ['严平'],
        page_start: 8,
        page_end: 11,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '扶植和发展革命的新生事物',
        authors: ['高戈'],
        page_start: 12,
        page_end: 15,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '要用积极的态度去解决间题',
        authors: ['薛岑'],
        page_start: 16,
        page_end: 19,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '小评论一组（六篇）',
        authors: [
          '江苏高淳县丹湖公社评论组',
          '上海新华电器模具厂党支部',
          '程平',
          '湖南岳阳县南正街综合商店评论组',
          '江卓成',
          '吉林九台县鸡鸣山公社评论组',
        ],
        page_start: 20,
        page_end: 28,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '坚持计划用粮、节约用粮',
        authors: ['洪桥'],
        page_start: 29,
        page_end: 31,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '加强农业科学研究',
        authors: ['任为农'],
        page_start: 32,
        page_end: 36,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '学习辩证法 改造低产田',
        authors: ['湖北安陆县崔兴公社崔沟大队党支部'],
        page_start: 37,
        page_end: 40,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '努力实现机械化—―徐州铁路分局车辆段的调查报告',
        authors: ['江苏徐州市革命委员会报道组'],
        page_start: 41,
        page_end: 44,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '介绍一个清洁工人办的化工厂',
        authors: ['河北秦皇岛市革命委员会调查组'],
        page_start: 45,
        page_end: 47,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title:
          '春秋战国时期思想领域内两条路线的斗争——从儒法论争看春秋战国时期的社会变革',
        authors: ['杨荣国'],
        page_start: 48,
        page_end: 57,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '毛主席的革命文艺路线给了我新的艺术生命',
        authors: ['李炳淑'],
        page_start: 58,
        page_end: 62,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '全心全意为社员群众防病治病',
        authors: ['孙卫东'],
        page_start: 63,
        page_end: 65,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '我们是怎样巩固合作医疗的？',
        authors: ['陕西延安县南泥湾公社马坊大队医疗站'],
        page_start: 66,
        page_end: 68,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '坚持农民业余教育二十年',
        authors: ['中国共产党蕲春县孙冲公社委员会'],
        page_start: 69,
        page_end: 72,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '课文两篇',
        authors: [],
        page_start: 72,
        page_end: 72,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '在实践斗争中增长才干——学习辩证唯物论的认识论的一点体会',
        authors: ['吴桂贤'],
        page_start: 73,
        page_end: 78,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '要永远保持普通劳动者的本色——学习《法兰西内战》的一点体会',
        authors: ['尉凤英'],
        page_start: 79,
        page_end: 81,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
      {
        title: '红旗杂志一九七二年第一期到第十二期总目录',
        authors: ['《红旗》杂志编辑部'],
        page_start: 82,
        page_end: 89,
        dates: [{ year: 1972, month: 12, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/0d948a84-85f8-4e30-b43d-9148bae6609d.pdf',
};
