export default {
  entity: {
    id: '0daa87bc-e961-49ba-84a3-516e1d66526a',
    name: '红旗一九七二年第八期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/0daa87bc-e961-49ba-84a3-516e1d66526a.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '发扬光荣传统──纪念中国人民解放军创建四十五周年',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        page_start: 7,
        page_end: 8,
        dates: [{ year: 1972, month: 8, day: 1 }],
      },
      {
        title: '掌握社会主义时期阶级斗争的规律',
        authors: ['纪平'],
        page_start: 9,
        page_end: 13,
        dates: [{ year: 1972, month: 8, day: 1 }],
      },
      {
        title: '毛主席战略思想的伟大胜利——学习《关于辽沈战役的作战方针》',
        authors: ['沈钧'],
        page_start: 14,
        page_end: 18,
        dates: [{ year: 1972, month: 8, day: 1 }],
      },
      {
        title: '在批修整风中坚持认真看书学习',
        authors: ['齐学思'],
        page_start: 19,
        page_end: 22,
        dates: [{ year: 1972, month: 8, day: 1 }],
      },
      {
        title: '从认识史看先验论的破产',
        authors: ['唐晓文'],
        page_start: 23,
        page_end: 29,
        dates: [{ year: 1972, month: 8, day: 1 }],
      },
      {
        title: '把看书学习和路线教育结合起来',
        authors: ['中国人民解放军北京部队某部四连党支部'],
        page_start: 30,
        page_end: 33,
        dates: [{ year: 1972, month: 8, day: 1 }],
      },
      {
        title: '让党的基本路线在连队生根',
        authors: ['中国人民解放军武汉部队某团党委会'],
        page_start: 34,
        page_end: 37,
        dates: [{ year: 1972, month: 8, day: 1 }],
      },
      {
        title: '把革命大批判长期坚持下去',
        authors: ['天津市第四棉纺织厂工人评论组'],
        page_start: 38,
        page_end: 42,
        dates: [{ year: 1972, month: 8, day: 1 }],
      },
      {
        title: '认真改进文风',
        authors: ['齐永红'],
        page_start: 43,
        page_end: 45,
        dates: [{ year: 1972, month: 8, day: 1 }],
      },
      {
        title: '请读两篇好而短的调查报告',
        authors: ['商业部'],
        page_start: 46,
        page_end: 49,
        dates: [{ year: 1972, month: 7, day: 24 }],
      },
      {
        title: '“瘸腿队”的帽子是怎样甩掉的？——北京顺义县井上大队的调查报告',
        authors: ['中国共产党北京市委员会调查组'],
        page_start: 50,
        page_end: 52,
        dates: [{ year: 1972, month: 8, day: 1 }],
      },
      {
        title: '一个积极支援农业的供销社',
        authors: ['山西神池县革命委员会调查组'],
        page_start: 53,
        page_end: 55,
        dates: [{ year: 1972, month: 8, day: 1 }],
      },
      {
        title: '进一步办好轻工业',
        authors: ['钟青'],
        page_start: 56,
        page_end: 60,
        dates: [{ year: 1972, month: 8, day: 1 }],
      },
      {
        title: '以粮为纲 全面发展——江苏海安县的调查报告',
        authors: ['农林部调查组'],
        page_start: 61,
        page_end: 65,
        dates: [{ year: 1972, month: 8, day: 1 }],
      },
      {
        title: '关于要重视对青少年的思想教育工作的讨论（五篇）',
        authors: [
          '济南市革命委员会几名青年工作者',
          '长沙市南区十七名小学教师',
          '邓湘雄',
          '鲁志德',
          '洛阳轴承厂工具分厂第五团支部',
        ],
        page_start: 66,
        page_end: 73,
        dates: [{ year: 1972, month: 8, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/0daa87bc-e961-49ba-84a3-516e1d66526a.pdf',
};
