export default {
  entity: {
    id: '0e3ac1d5-ec74-4fd2-8da9-5d4322f87271',
    name: '为毛主席而战——文革重庆大武斗实录（三联书店2010年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '何蜀著，三联书店2010年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/0e3ac1d5-ec74-4fd2-8da9-5d4322f87271.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '序：是文化的革命还是武斗？',
        authors: ['徐友渔'],
        page_start: 20,
        page_end: 22,
        dates: [{ year: 2010, month: 8 }],
      },
      {
        title: '序',
        authors: ['启之'],
        page_start: 23,
        page_end: 28,
        dates: [{ year: 2008, month: 7, day: 6 }],
      },
      {
        title: '引子',
        authors: ['何蜀'],
        page_start: 30,
        page_end: 31,
        dates: [{ year: 2010, month: 8 }],
      },
      {
        title: '第一章 北京吹来动乱风',
        authors: ['何蜀'],
        page_start: 32,
        page_end: 81,
        dates: [{ year: 2010, month: 8 }],
      },
      {
        title: '第二章 造反之火燃向全社会',
        authors: ['何蜀'],
        page_start: 82,
        page_end: 112,
        dates: [{ year: 2010, month: 8 }],
      },
      {
        title: '第三章 首开大规模武斗先例',
        authors: ['何蜀'],
        page_start: 114,
        page_end: 136,
        dates: [{ year: 2010, month: 8 }],
      },
      {
        title: '第四章 两大派分道扬镳',
        authors: ['何蜀'],
        page_start: 138,
        page_end: 161,
        dates: [{ year: 2010, month: 8 }],
      },
      {
        title: '第五章 都是“复辟逆流”',
        authors: ['何蜀'],
        page_start: 162,
        page_end: 197,
        dates: [{ year: 2010, month: 8 }],
      },
      {
        title: '第六章 武斗在制止中升级',
        authors: ['何蜀'],
        page_start: 198,
        page_end: 217,
        dates: [{ year: 2010, month: 8 }],
      },
      {
        title: '第七章 “无产阶级专政”下的“全面内战”',
        authors: ['何蜀'],
        page_start: 218,
        page_end: 265,
        dates: [{ year: 2010, month: 8 }],
      },
      {
        title: '第八章 从停火交枪到解散组织',
        authors: ['何蜀'],
        page_start: 266,
        page_end: 301,
        dates: [{ year: 2010, month: 8 }],
      },
      {
        title: '第九章 重庆大武斗面面观',
        authors: ['何蜀'],
        page_start: 302,
        page_end: 377,
        dates: [{ year: 2010, month: 8 }],
      },
      {
        title: '尾声 无言的墓群',
        authors: ['何蜀'],
        page_start: 378,
        page_end: 386,
        dates: [{ year: 2010, month: 8 }],
      },
      {
        title: '后记',
        authors: ['何蜀'],
        page_start: 387,
        page_end: 388,
        dates: [{ year: 2010, month: 8 }],
      },
    ],
    ocr: { content_thresholds: [0.108, 0.078, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/0e3ac1d5-ec74-4fd2-8da9-5d4322f87271.pdf',
};
