export default {
  entity: {
    id: '10bdf796-7520-4dcb-b5f9-270e1d98ce7f',
    name: '红旗一九六三年第十三、十四期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/10bdf796-7520-4dcb-b5f9-270e1d98ce7f.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '干部参加集体生产劳动，对于社会主义制度是带根本性的一件大事',
        authors: ['《红旗》杂志编辑部'],
        page_start: 5,
        page_end: 17,
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
      {
        title: '一个团结勤奋向上的集体',
        authors: ['李成章', '华福'],
        page_start: 18,
        page_end: 22,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
      {
        title: '老贫农的本色',
        authors: ['李廷凡', '钱进'],
        page_start: 22,
        page_end: 25,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
      {
        title: '“劳动带头干，工作是模范”',
        authors: ['申元则', '连治水'],
        page_start: 26,
        page_end: 29,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
      {
        title: '身份是社员，劳动是本分',
        authors: ['孙汝纯', '毕可友'],
        page_start: 30,
        page_end: 32,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
      {
        title: '始终保持着劳动人民的本色',
        authors: ['郑际雄'],
        page_start: 33,
        page_end: 37,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
      {
        title: '社员的好榜样，青年的带路人',
        authors: ['莫占林'],
        page_start: 38,
        page_end: 42,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
      {
        title: '他们为什么能一贯参加劳动？',
        authors: ['万里云', '潘用庭'],
        page_start: 42,
        page_end: 44,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
      {
        title: '四望山下',
        authors: ['碧野'],
        page_start: 45,
        page_end: 49,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
      {
        title: '参加生产，领导生产',
        authors: ['王继生', '杜加星', '项绍棠'],
        page_start: 50,
        page_end: 54,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
      {
        title: '他是庄稼人',
        authors: ['周维敷', '任洁民'],
        page_start: 55,
        page_end: 60,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
      {
        title: '十三年手不离锄',
        authors: ['张健', '任山'],
        page_start: 60,
        page_end: 62,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
      {
        title: '昔阳县四级干部参加生产劳动的伟大范例',
        authors: ['中共晋中地委农村工作部'],
        page_start: 63,
        page_end: 68,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
      {
        title:
          '把干部参加劳动的制度永远坚持下去——鞍山地区组织干部参加集体生产劳动的经验',
        authors: ['中共鞍山市委员会'],
        page_start: 69,
        page_end: 73,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
      {
        title: '地委书记余锡渠同志',
        authors: ['伊晓'],
        page_start: 74,
        page_end: 76,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1963, month: 7, day: 10 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/10bdf796-7520-4dcb-b5f9-270e1d98ce7f.pdf',
};
