export default {
  entity: {
    id: '13107599-e880-434a-8398-8094a15b50f7',
    name: '红旗一九六五年第七期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/13107599-e880-434a-8398-8094a15b50f7.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title:
          '把反对赫鲁晓夫修正主义的斗争进行到底——纪念《关于国际共产主义运动总路线的建议》发表两周年',
        authors: ['人民日报编辑部', '红旗杂志编辑部'],
        page_start: 3,
        page_end: 10,
        dates: [{ year: 1965 }],
      },
      {
        title: '从第二十八届世界比赛看完过乒乓球队的成长',
        authors: ['荣高棠'],
        page_start: 11,
        page_end: 22,
        dates: [{ year: 1965 }],
      },
      {
        title: '敢于胜利，才能胜利',
        authors: ['林慧卿', '郑敏之', '梁丽珍', '李郝男'],
        page_start: 23,
        page_end: 25,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '一比三',
        authors: ['撞则栋'],
        page_start: 26,
        page_end: 27,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '听一听 想一想',
        authors: ['徐寅生'],
        page_start: 27,
        page_end: 29,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '一张决赛名单',
        authors: ['容国团', '孙梅英'],
        page_start: 29,
        page_end: 30,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '战争胜败的决定因素是人不是物',
        authors: ['施东向'],
        page_start: 31,
        page_end: 42,
        dates: [{ year: 1965 }],
      },
    ],
    ocr: { content_thresholds: [0.07, 0.165, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/13107599-e880-434a-8398-8094a15b50f7.pdf',
};
