export default {
  entity: {
    id: '1537a4aa-be75-4eec-ad71-da04af72cd10',
    name: '红旗一九七二年第二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/1537a4aa-be75-4eec-ad71-da04af72cd10.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '必须继续巩固无产阶级专政——学习《论人民民主专政》的一点体会',
        authors: ['中国共产党广西壮族自治区委员会写作小组'],
        page_start: 7,
        page_end: 12,
        dates: [{ year: 1972, month: 2, day: 1 }],
      },
      {
        title: '读几本哲学史',
        authors: ['唐晓文'],
        page_start: 13,
        page_end: 17,
        dates: [{ year: 1972, month: 2, day: 1 }],
      },
      {
        title: '坚持党的理论和实践相结合的原则',
        authors: ['中国共产党四川省委员会写作小组'],
        page_start: 18,
        page_end: 24,
        dates: [{ year: 1972, month: 2, day: 1 }],
      },
      {
        title: '海港',
        authors: ['上海京剧团《海港》剧组'],
        page_start: 25,
        page_end: 51,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.47,
          content_thresholds: [0, 0.15, 0, 0.2],
        },
        dates: [{ year: 1972, month: 1 }],
      },
      {
        title: '无产阶级专政下继续革命的光辉典型——赞方海珍形象的塑造',
        authors: ['闻军'],
        page_start: 52,
        page_end: 56,
        dates: [{ year: 1972, month: 2, day: 1 }],
      },
      {
        title: '要经常注意节约',
        authors: ['阳高照'],
        page_start: 57,
        page_end: 61,
        dates: [{ year: 1972, month: 2, day: 1 }],
      },
      {
        title: '男女同工要同酬——评农村分配问题上的一种错误倾向',
        authors: ['金继祖', '洪松'],
        page_start: 62,
        page_end: 65,
        dates: [{ year: 1972, month: 2, day: 1 }],
      },
      {
        title: '提倡“认真”一字——反对一种所谓走“捷径”的坏学风',
        authors: [
          '上海机床厂、红色线厂、上海无线电二十六厂、上海重型机器厂几位工人',
        ],
        page_start: 66,
        page_end: 69,
        dates: [{ year: 1972, month: 2, day: 1 }],
      },
      {
        title: '勤俭办社绘新图',
        authors: ['江苏常熟县何市公社人民大队党支部'],
        page_start: 70,
        page_end: 75,
        dates: [{ year: 1972, month: 2, day: 1 }],
      },
      {
        title: '坚持正确路线 赢得建设高速度——北京石油化工总厂的调查报告',
        authors: ['中国共产党北京市委员会调查组'],
        page_start: 76,
        page_end: 82,
        dates: [{ year: 1972, month: 2, day: 1 }],
      },
      {
        title: '多快好省地发展钢铁生产',
        authors: ['中国共产党鞍山市委员会'],
        page_start: 83,
        page_end: 89,
        dates: [{ year: 1972, month: 2, day: 1 }],
      },
      {
        title: '甘当人民群众的小学生',
        authors: ['中国人民解放军济南部队某部“遵纪爱民模范连”'],
        page_start: 90,
        page_end: 93,
        dates: [{ year: 1972, month: 2, day: 1 }],
      },
      {
        title: '自觉做好拥军优属工作',
        authors: ['宁夏石嘴山市大武口公社大武口大队党支部'],
        page_start: 94,
        page_end: 97,
        dates: [{ year: 1972, month: 2, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/1537a4aa-be75-4eec-ad71-da04af72cd10.pdf',
};
