export default {
  entity: {
    id: '1585d290-4048-4cec-aef9-5517bf49cf29',
    name: '红旗一九六四年第二十一、二十二期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/1585d290-4048-4cec-aef9-5517bf49cf29.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '赫鲁晓夫是怎样下台的',
        authors: ['红旗杂志编辑部'],
        page_start: 3,
        page_end: 10,
        dates: [{ year: 1964 }],
      },
      {
        title: '阿尔巴尼亚在社会主义大道上前进——庆祝阿尔巴尼亚解放二十周年',
        authors: ['许建国'],
        page_start: 11,
        page_end: 14,
        dates: [{ year: 1964 }],
      },
      {
        title: '主观唯心主义的大杂烩——评冯定同志的《平凡的真理》',
        authors: ['陆锋'],
        page_start: 15,
        page_end: 26,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '过渡时期没有阶级斗争吗？',
        authors: ['冼光位'],
        page_start: 27,
        page_end: 31,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '敌我矛盾不容调和',
        authors: ['俞建平'],
        page_start: 31,
        page_end: 34,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '英雄事迹从哪里来？',
        authors: ['李小林'],
        page_start: 35,
        page_end: 37,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '驳“和平转变”论',
        authors: ['陈瑞苗'],
        page_start: 37,
        page_end: 39,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '西方基督教神学是怎样为美帝国主义服务的',
        authors: ['杨真'],
        page_start: 40,
        page_end: 46,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
    ],
    ocr: { content_thresholds: [0.07, 0.165, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/1585d290-4048-4cec-aef9-5517bf49cf29.pdf',
};
