export default {
  entity: {
    id: '17fb52b8-0111-4af5-80ed-d9665739385d',
    name: '红旗一九七〇年第十一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/17fb52b8-0111-4af5-80ed-d9665739385d.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '在庆祝中华人民共和国成立二十一周年大会上的讲话',
        alias: '在庆祝中华人民共和国成立二十一周年大会上林彪副主席的讲话',
        authors: ['林彪'],
        page_start: 8,
        page_end: 11,
        dates: [{ year: 1970, month: 10, day: 1 }],
      },
      {
        title: '继续革命 乘胜前进——庆祝中华人民共和国成立二十一周年',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        page_start: 10,
        page_end: 13,
        dates: [{ year: 1970, month: 11, day: 1 }],
      },
      {
        title: '中共中央致电朝鲜劳动党中央最热烈祝贺朝鲜劳动党诞生二十五周年',
        authors: ['中共中央'],
        page_start: 14,
        page_end: 15,
        dates: [{ year: 1970, month: 10, day: 9 }],
      },
      {
        title: '领导干部要带头学好',
        authors: ['《红旗》杂志编辑部'],
        page_start: 16,
        page_end: 18,
        dates: [{ year: 1970, month: 11, day: 1 }],
      },
      {
        title: '加强无产阶级党性',
        authors: ['红垒'],
        page_start: 19,
        page_end: 22,
        dates: [{ year: 1970, month: 11, day: 1 }],
      },
      {
        title: '在克服主观主义中前进',
        authors: ['黄祖示'],
        page_start: 23,
        page_end: 27,
        dates: [{ year: 1970, month: 11, day: 1 }],
      },
      {
        title: '要自觉地改造世界观',
        authors: ['戴裕民'],
        page_start: 28,
        page_end: 30,
        dates: [{ year: 1970, month: 11, day: 1 }],
      },
      {
        title: '靠唯物辩证法做好工作——下乡半年的体会',
        authors: ['朱培屏'],
        page_start: 31,
        page_end: 33,
        dates: [{ year: 1970, month: 11, day: 1 }],
      },
      {
        title: '天津市革命委员会关于认真学习毛主席哲学著作的决定',
        authors: ['天津市革命委员会'],
        page_start: 34,
        page_end: 35,
        dates: [{ year: 1970, month: 10, day: 2 }],
      },
      {
        title: '毛泽东思想指引我们多快好省地修建铁路',
        authors: ['中国人民解放军铁道兵写作小组'],
        page_start: 36,
        page_end: 44,
        dates: [{ year: 1970, month: 11, day: 1 }],
      },
      {
        title: '运用毛主席的哲学思想发展科学技术',
        authors: ['李四光'],
        page_start: 45,
        page_end: 50,
        dates: [{ year: 1970, month: 11, day: 1 }],
      },
      {
        title: '要经常分析阶级斗争形势——湖南双峰县青树坪公社的调查报告',
        authors: ['湖南邵阳地区革委会调查组'],
        page_start: 51,
        page_end: 55,
        dates: [{ year: 1970, month: 11, day: 1 }],
      },
      {
        title: '农业学大寨 苗岭换新装',
        authors: ['陈作荣'],
        page_start: 56,
        page_end: 57,
        dates: [{ year: 1970, month: 11, day: 1 }],
      },
      {
        title: '永远与工农群众相结合',
        authors: ['朱思端'],
        page_start: 58,
        page_end: 60,
        dates: [{ year: 1970, month: 11, day: 1 }],
      },
      {
        title: '在阶级斗争风浪中加强连队革命化战斗化',
        authors: ['中国人民解放军某部“红色尖兵连”党支部'],
        page_start: 61,
        page_end: 64,
        dates: [{ year: 1970, month: 11, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/17fb52b8-0111-4af5-80ed-d9665739385d.pdf',
};
