export default {
  entity: {
    id: '18306d01-a029-4a85-b4f7-fd892be983ec',
    name: '文革通讯第9期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '浙江工农兵美术大学毛泽东主义红卫兵战斗队、毛泽东主义红卫兵',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives15/main/18306d01-a029-4a85-b4f7-fd892be983ec.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '周总理讲话',
        authors: ['周恩来'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967 }],
      },
      {
        title: '江青同志讲话',
        authors: ['江青'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967 }],
      },
      {
        title: '中央首长谈个毛造反派内部团结',
        authors: ['陈伯达', '江青', '谢富治', '戚本禹'],
        page_start: 1,
        page_end: 2,
        dates: [{ year: 1967 }],
      },
      {
        title: '陈伯达、康生、江青同志审查一九六六年国庆影片谈话纪要',
        authors: ['陈伯达', '康生', '江青'],
        page_start: 2,
        page_end: 2,
        dates: [{ year: 1967 }],
      },
      {
        title: '张春桥同志谈关于红卫兵',
        authors: ['张春桥'],
        page_start: 2,
        page_end: 2,
        dates: [{ year: 1967 }],
      },
      {
        title: '戚本禹同志讲话——接见红代会核心组时的讲话',
        authors: ['戚本禹'],
        page_start: 2,
        page_end: 3,
        dates: [{ year: 1967 }],
      },
      {
        title: '姚文元同志三月二十日在黄浦区革命委员会成立大会上的讲话',
        authors: ['姚文元'],
        page_start: 3,
        page_end: 5,
        dates: [{ year: 1967, month: 3, day: 20 }],
      },
      {
        title: '聂元梓同志在三月十一日整风串联会上的讲话',
        authors: ['聂元梓'],
        page_start: 5,
        page_end: 5,
        dates: [{ year: 1967, month: 3, day: 21 }],
      },
      {
        title: '北京动态',
        authors: ['《文革通讯》编辑部'],
        page_start: 5,
        page_end: 6,
        dates: [{ year: 1967, month: 4, day: 14 }],
      },
      {
        title: '祖国各地',
        authors: ['《文革通讯》编辑部'],
        page_start: 6,
        page_end: 6,
        dates: [{ year: 1967, month: 4, day: 14 }],
      },
      {
        title: '上海动态',
        authors: ['《文革通讯》编辑部'],
        page_start: 6,
        page_end: 7,
        dates: [{ year: 1967, month: 4, day: 14 }],
      },
      {
        title: '必须痛击这股逆流',
        authors: ['《文革通讯》编辑部'],
        page_start: 7,
        page_end: 7,
        dates: [{ year: 1967, month: 4, day: 14 }],
      },
      {
        title: '谭震林十大罪状',
        authors: ['《文革通讯》编辑部'],
        page_start: 8,
        page_end: 8,
        dates: [{ year: 1967, month: 4, day: 14 }],
      },
      {
        title: '谭震林论“共产主义”',
        authors: ['《文革通讯》编辑部'],
        page_start: 8,
        page_end: 8,
        dates: [{ year: 1967, month: 4, day: 14 }],
      },
      {
        title: '阿尔巴尼亚人民热爱毛主席',
        authors: ['《文革通讯》编辑部'],
        page_start: 8,
        page_end: 8,
        dates: [{ year: 1967, month: 4, day: 14 }],
      },
    ],
    ocr: undefined,
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives15/18306d01-a029-4a85-b4f7-fd892be983ec.pdf',
};
