export default {
  entity: {
    id: '19f2d86e-00ec-43f4-9fb3-99553989096c',
    name: '文革通讯第19期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '浙江工农兵美术大学毛泽东主义红卫兵战斗队、毛泽东主义红卫兵',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives15/main/19f2d86e-00ec-43f4-9fb3-99553989096c.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '毛主席五次批判《清宫秘史》',
        authors: ['毛泽东'],
        page_start: 1,
        page_end: 1,
        is_range_date: true,
        dates: [
          { year: 1950, month: 3 },
          { year: 1965, month: 12, day: 21 },
        ],
      },
      {
        title: '毛主席对北京市革命委员会的最新指示',
        authors: ['毛泽东'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967, month: 4 }],
      },
      {
        title: '林副主席在中央工作会议上的讲话',
        authors: ['林彪'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967 }],
      },
      {
        title: '中央文革小组对当前形势的几点最新指示',
        authors: ['江青', '姚文元'],
        page_start: 1,
        page_end: 2,
        dates: [
          { year: 1967, month: 4, day: 16 },
          { year: 1967, month: 4, day: 17 },
        ],
      },
      {
        title: '戚本禹同志谈青年要保持早节',
        authors: ['戚本禹'],
        page_start: 2,
        page_end: 2,
        dates: [{ year: 1967 }],
      },
      {
        title: '关锋同志关于批刘少奇的要点',
        authors: ['关锋'],
        page_start: 2,
        page_end: 2,
        dates: [{ year: 1967 }],
      },
      {
        title: '张春桥同志谈中学复课及红卫兵问题',
        authors: ['张春桥'],
        page_start: 2,
        page_end: 3,
        dates: [{ year: 1967 }],
      },
      {
        title: '北京消息',
        authors: ['《文革通讯》编辑部'],
        page_start: 3,
        page_end: 3,
        dates: [{ year: 1967, month: 4, day: 30 }],
      },
      {
        title: '刘少奇之女谈刘、王',
        authors: ['《文革通讯》编辑部'],
        page_start: 3,
        page_end: 3,
        dates: [{ year: 1967, month: 4, day: 30 }],
      },
      {
        title: '刘邓在重庆',
        authors: ['《文革通讯》编辑部'],
        page_start: 3,
        page_end: 4,
        dates: [{ year: 1967, month: 4, day: 30 }],
      },
      {
        title: '上海动态',
        authors: ['《文革通讯》编辑部'],
        page_start: 4,
        page_end: 4,
        dates: [{ year: 1967, month: 4, day: 30 }],
      },
      {
        title: '国际动态',
        authors: ['《文革通讯》编辑部'],
        page_start: 4,
        page_end: 4,
        dates: [{ year: 1967, month: 4, day: 30 }],
      },
    ],
    ocr: undefined,
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives15/19f2d86e-00ec-43f4-9fb3-99553989096c.pdf',
};
