export default {
  entity: {
    id: '1b858c5b-e5a4-4042-9eb8-8b1d89c9afee',
    name: '张春桥：1949及其后（中文大学出版社2017年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '郑重著，中文大学出版社2017年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/1b858c5b-e5a4-4042-9eb8-8b1d89c9afee.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '自序',
        authors: ['郑重'],
        page_start: 3,
        page_end: 5,
        dates: [{ year: 2016, month: 7 }],
      },
      {
        title: '第一章 重返大上海',
        authors: ['郑重'],
        page_start: 5,
        page_end: 17,
        dates: [{ year: 2017 }],
      },
      {
        title: '第二章 执掌《解放日报》',
        authors: ['郑重'],
        page_start: 19,
        page_end: 33,
        dates: [{ year: 2017 }],
      },
      {
        title: '第三章 走进毛泽东',
        authors: ['郑重'],
        page_start: 35,
        page_end: 57,
        dates: [{ year: 2017 }],
      },
      {
        title: '第四章 特殊历史时期的序幕',
        authors: ['郑重'],
        page_start: 59,
        page_end: 76,
        dates: [{ year: 2017 }],
      },
      {
        title: '第五章 批判《海瑞罢官》',
        authors: ['郑重'],
        page_start: 77,
        page_end: 96,
        dates: [{ year: 2017 }],
      },
      {
        title: '第六章 毛泽东棋盘上的一粒棋子',
        authors: ['郑重'],
        page_start: 97,
        page_end: 116,
        dates: [{ year: 2017 }],
      },
      {
        title: '第七章 安亭事件',
        authors: ['郑重'],
        page_start: 118,
        page_end: 135,
        dates: [{ year: 2017 }],
      },
      {
        title: '第八章 市委心脏爆炸：写作班造反',
        authors: ['郑重'],
        page_start: 135,
        page_end: 152,
        dates: [{ year: 2017 }],
      },
      {
        title: '第九章 实践毛泽东夺权理论（上）：一月革命',
        authors: ['郑重'],
        page_start: 154,
        page_end: 176,
        dates: [{ year: 2017 }],
      },
      {
        title: '第十章 实践毛泽东夺权理论（下）：短命的上海人民公社',
        authors: ['郑重'],
        page_start: 177,
        page_end: 196,
        dates: [{ year: 2017 }],
      },
      {
        title: '第十一章 夺权以后',
        authors: ['郑重'],
        page_start: 196,
        page_end: 213,
        dates: [{ year: 2017 }],
      },
      {
        title: '第十二章 大批判：思想领域的夺权',
        authors: ['郑重'],
        page_start: 214,
        page_end: 232,
        dates: [{ year: 2017 }],
      },
      {
        title: '第十三章 “四·一二炮打”和秋后算账',
        authors: ['郑重'],
        page_start: 233,
        page_end: 252,
        dates: [{ year: 2017 }],
      },
      {
        title: '第十四章 九大前后',
        authors: ['郑重'],
        page_start: 253,
        page_end: 269,
        dates: [{ year: 2017 }],
      },
      {
        title: '第十五章 难识庐山真面目',
        authors: ['郑重'],
        page_start: 269,
        page_end: 285,
        dates: [{ year: 2017 }],
      },
      {
        title: '第十六章 对垒周恩来',
        authors: ['郑重'],
        page_start: 285,
        page_end: 301,
        dates: [{ year: 2017 }],
      },
    ],
    ocr: {
      auto_vsplit: false,
      vsplit: 0.5,
      content_thresholds: [0, 0.072, 0, 0],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/1b858c5b-e5a4-4042-9eb8-8b1d89c9afee.pdf',
};
