export default {
  entity: {
    id: '1e5a161d-09f5-418d-97ff-97021869890b',
    name: '红旗一九六二年第十二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/1e5a161d-09f5-418d-97ff-97021869890b.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '关于党的干部政策的几个问题——学习毛泽东同志有关著作的体会',
        authors: ['赵汉'],
        page_start: 3,
        page_end: 15,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1962, month: 6, day: 16 }],
      },
      {
        title: '自然资源的利用和保护',
        authors: ['甘子玉'],
        page_start: 16,
        page_end: 19,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 6, day: 16 }],
      },
      {
        title: '关于选择研究题目',
        authors: ['严中乎'],
        page_start: 20,
        page_end: 29,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 6, day: 16 }],
      },
      {
        title: '农村人民公社应该加强经济核算观点',
        authors: ['陈因'],
        page_start: 30,
        page_end: 33,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 6, day: 16 }],
      },
      {
        title: '说鞭策',
        authors: ['吴介民'],
        page_start: 34,
        page_end: 35,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 6, day: 16 }],
      },
      {
        title: '美法交恶：西方外交史万花筒上的一个新镜头',
        authors: ['张振亚'],
        page_start: 36,
        page_end: 39,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 6, day: 16 }],
      },
      {
        title: '丑恶的“形象”',
        authors: ['胡思升'],
        page_start: 40,
        page_end: 41,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 6, day: 16 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/1e5a161d-09f5-418d-97ff-97021869890b.pdf',
};
