export default {
  entity: {
    id: '204378d0-bbc1-47c2-b6d2-0cf47d728d58',
    name: '红旗一九七六年第八期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/204378d0-bbc1-47c2-b6d2-0cf47d728d58.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中共中央给地震灾区人民的慰问电',
        authors: ['中共中央'],
        page_start: 8,
        page_end: 8,
        dates: [{ year: 1976, month: 7, day: 28 }],
      },
      {
        title: '进一步发展社会主义新生事物',
        authors: ['程越'],
        page_start: 11,
        page_end: 15,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '无产阶级是革命的乐观主义者',
        authors: ['毕盛'],
        page_start: 16,
        page_end: 20,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '在批邓斗争中加强团结',
        authors: ['青岩'],
        page_start: 21,
        page_end: 23,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '工人参加企业管理好',
        authors: ['北京市北郊木材厂党委会'],
        page_start: 24,
        page_end: 28,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '集体养猪 大有可为——安徽利辛县小叶园生产队的调查',
        authors: ['中共安徽省委、中共利辛县委联合调查组'],
        page_start: 29,
        page_end: 31,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '坚持继续革命逐步缩小差别——吉林永吉县阿拉底大队的调查',
        authors: ['中共吉林省委、吉林市委、永吉县委调查组'],
        page_start: 32,
        page_end: 36,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '做限制资产阶级法权的促进派',
        authors: ['王连生'],
        page_start: 37,
        page_end: 40,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '一个在科技界复辟资本主义的纲领——评《科学院工作汇报提纲》',
        authors: ['中国科学院大批判组'],
        page_start: 41,
        page_end: 47,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '精神可以变成物质——批判邓小平反对工人参加上层建筑领域革命的谬论',
        authors: ['大连红旗造船厂党委会'],
        page_start: 48,
        page_end: 53,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '篡改马克思主义的一个标本',
        authors: ['方海'],
        page_start: 54,
        page_end: 56,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '邓小平为什么替“老戏”招魂?',
        authors: ['江天'],
        page_start: 57,
        page_end: 60,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '永远坚持毛主席的建军路线——批判邓小平在军队建设上的修正主义谬论',
        authors: ['沈屏'],
        page_start: 61,
        page_end: 66,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '在三同中密切官兵关系',
        authors: ['中国人民解放军北京部队“济南第一团”党委会'],
        page_start: 67,
        page_end: 69,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '以阶级斗争为纲做好战备工作',
        authors: ['中国人民解放军沈阳部队某部红一连党支部'],
        page_start: 70,
        page_end: 73,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '加强工人民兵的建设',
        authors: ['上海沪东造船厂党委会'],
        page_start: 74,
        page_end: 77,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '对生命认识的两种世界观斗争',
        authors: ['胡雨涛'],
        page_start: 78,
        page_end: 86,
        dates: [{ year: 1976, month: 8 }],
      },
      {
        title: '莫斯科版的“升官图”——评奇文《怎样成为部长》',
        authors: ['桑娄东'],
        page_start: 87,
        page_end: 89,
        dates: [{ year: 1976, month: 8 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/204378d0-bbc1-47c2-b6d2-0cf47d728d58.pdf',
};
