export default {
  entity: {
    id: '224de5af-a8f4-43a4-8181-3dbf11f1b42f',
    name: '红旗一九六七年第十期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/224de5af-a8f4-43a4-8181-3dbf11f1b42f.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '关于正确处理人民内部矛盾的问题',
        authors: ['毛泽东'],
        page_start: 4,
        page_end: 33,
        dates: [{ year: 1957, month: 2, day: 27 }],
      },
      {
        title:
          '无产阶级专政下进行革命的理论武器——纪念《关于正确处理人民内部矛盾的问题》发表十周年',
        authors: [],
        page_start: 34,
        page_end: 41,
        dates: [{ year: 1967 }],
      },
      {
        title: '伟大的战略措施',
        authors: ['红旗杂志', '人民日报'],
        page_start: 42,
        page_end: 45,
        dates: [{ year: 1967 }],
      },
      {
        title: '活学活用毛主席著作正确处理人民内部矛盾',
        authors: ['中国人民解放军北京部队空军直属队毛泽东思想宣传队'],
        page_start: 46,
        page_end: 50,
        dates: [{ year: 1967 }],
        ocr: { vsplit: 0.35 },
      },
      {
        title: '严格区分两类不同性质的矛盾正确对待受蒙蔽的群众',
        authors: ['中国人民解放军空军政治部文工团革命委员会'],
        page_start: 51,
        page_end: 54,
        dates: [{ year: 1967 }],
        ocr: { vsplit: 0.35 },
      },
      {
        title: '永远忠于毛主席的无产阶级革命路线',
        authors: ['李水清', '陈继德'],
        page_start: 55,
        page_end: 61,
        dates: [{ year: 1967 }],
      },
      {
        title: '正确认识和运用无产阶级专政下的大民主',
        authors: ['洪晓斌'],
        page_start: 62,
        page_end: 64,
        dates: [{ year: 1967 }],
        ocr: { vsplit: 0.35 },
      },
      {
        title: '防止资产阶级思想侵蚀',
        authors: ['《红旗》杂志编辑部'],
        page_start: 65,
        page_end: 66,
        dates: [{ year: 1967 }],
      },
      {
        title: '山东省革命委员会关于认真转变作风若干规定',
        authors: ['山东省革命委员会'],
        page_start: 67,
        page_end: 67,
        dates: [{ year: 1967, month: 6, day: 7 }],
      },
      {
        title: '念念不忘斗争大方向——三论无产阶级革命派怎样掌好权用好权',
        authors: ['文汇报'],
        page_start: 68,
        page_end: 70,
        dates: [{ year: 1967, month: 6, day: 11 }],
      },
      {
        title: '把大批判和本单位斗批改结合起来',
        authors: ['上海爱民糖果厂工人革命造反队'],
        page_start: 71,
        page_end: 75,
        dates: [{ year: 1967 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/224de5af-a8f4-43a4-8181-3dbf11f1b42f.pdf',
};
