export default {
  entity: {
    id: '234331e5-1061-47d5-bd8d-8ff71a70f57f',
    name: '文革通讯第27期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '浙江工农兵美术大学毛泽东主义红卫兵战斗队、毛泽东主义红卫兵',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives15/main/234331e5-1061-47d5-bd8d-8ff71a70f57f.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '毛主席五月二日和王力同志的对话',
        authors: ['毛泽东', '王力'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967, month: 5, day: 2 }],
      },
      {
        title: '五月四日谢富治同志传达毛主席指示',
        authors: ['毛泽东', '谢富治'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967, month: 5, day: 4 }],
      },
      {
        title: '王力同志传达毛主席指示',
        authors: ['王力'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967, month: 5 }],
      },
      {
        title: '最最热烈欢呼毛主席光辉著作《讲话》发表二十五周年',
        authors: ['《文革通讯》编辑部'],
        page_start: 1,
        page_end: 2,
        dates: [{ year: 1967, month: 5, day: 15 }],
      },
      {
        title: '中央文革最近对斗争彭小蒙问题作的批示',
        authors: ['江青', '陈伯达', '康生'],
        page_start: 2,
        page_end: 2,
        dates: [{ year: 1967, month: 4, day: 20 }],
      },
      {
        title: '周总理，春桥同志在谈李雪峰问题时的一段讲话',
        authors: ['周恩来', '张春桥'],
        page_start: 2,
        page_end: 2,
        dates: [{ year: 1967 }],
      },
      {
        title: '关于天津市夺权形势答读者问',
        authors: ['天津大学“八·一三”红卫兵报编辑部'],
        page_start: 2,
        page_end: 2,
        dates: [{ year: 1967 }],
      },
      {
        title:
          '五月四日戚本禹同志对艾琳同志谈《在延安文艺座谈会上的讲话》的宣传',
        authors: ['戚本禹'],
        page_start: 3,
        page_end: 3,
        dates: [{ year: 1967, month: 5, day: 4 }],
      },
      {
        title: '首都消息',
        authors: ['《文革通讯》编辑部'],
        page_start: 3,
        page_end: 4,
        dates: [{ year: 1967, month: 5, day: 15 }],
      },
      {
        title: '党内最大的走资本主义道路的当权派对留苏学生所放的毒必须肃清',
        authors: ['《文革通讯》编辑部'],
        page_start: 4,
        page_end: 4,
        dates: [{ year: 1967, month: 5, day: 15 }],
      },
      {
        title: '刘少奇罪行点滴',
        authors: ['《文革通讯》编辑部'],
        page_start: 4,
        page_end: 4,
        dates: [{ year: 1967, month: 5, day: 15 }],
      },
      {
        title: '陈昌奉等及各地先进人物都拿起笔作刀枪，向刘、邓猛烈开火',
        authors: ['《文革通讯》编辑部'],
        page_start: 4,
        page_end: 4,
        dates: [{ year: 1967, month: 5, day: 15 }],
      },
      {
        title: '王光美妖婆剥削世家',
        authors: ['《文革通讯》编辑部'],
        page_start: 5,
        page_end: 5,
        dates: [{ year: 1967, month: 5, day: 15 }],
      },
      {
        title: '邓小平丑史',
        authors: ['《文革通讯》编辑部'],
        page_start: 5,
        page_end: 6,
        dates: [{ year: 1967, month: 5, day: 15 }],
      },
      {
        title: '祖国各地',
        authors: ['《文革通讯》编辑部'],
        page_start: 6,
        page_end: 8,
        dates: [{ year: 1967, month: 5, day: 15 }],
      },
      {
        title: '国际动态',
        authors: ['《文革通讯》编辑部'],
        page_start: 8,
        page_end: 8,
        dates: [{ year: 1967, month: 5, day: 15 }],
      },
    ],
    ocr: undefined,
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives15/234331e5-1061-47d5-bd8d-8ff71a70f57f.pdf',
};
