export default {
  entity: {
    id: '285ab922-3283-4e23-9a9f-6c09b4f89f4c',
    name: '红旗一九七三年第六期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/285ab922-3283-4e23-9a9f-6c09b4f89f4c.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '从总结经验中学习',
        authors: ['云岚'],
        page_start: 8,
        page_end: 13,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
      {
        title: '加强干部队伍的建设',
        authors: ['俞彤'],
        page_start: 14,
        page_end: 18,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
      {
        title: '掌握政策是领导机关的一项基本任务',
        authors: ['青岩'],
        page_start: 19,
        page_end: 22,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
      {
        title: '自觉地改造主观世界',
        authors: ['纪平'],
        page_start: 23,
        page_end: 27,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
      {
        title: '组织社会调查推动深入批修',
        authors: ['中国人民解放军北京部队某部防化连党支部'],
        page_start: 28,
        page_end: 35,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
      {
        title: '团结胜利的保证',
        authors: ['南郁'],
        page_start: 36,
        page_end: 38,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
      {
        title:
          '沿着为工农兵服务的方向继续前进——学习《在延安文艺座谈会上的讲话》',
        authors: ['戚文德'],
        page_start: 39,
        page_end: 43,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
      {
        title: '大有希望的小将',
        authors: ['任读'],
        page_start: 44,
        page_end: 47,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
      {
        title: '小评论一组（五篇）',
        authors: [
          '薛立仑',
          '湖北安陆县夹河公社顾李大队评论组',
          '南宁市环境卫生工作队工人评论组',
          '川沙县严桥公社革命委员会评论组',
          '江苏大丰县利国小煤矿机电队',
        ],
        page_start: 48,
        page_end: 56,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
      {
        title: '学大寨首先要学路线',
        authors: ['湖南常宁县白沙公社福坪大队党支部'],
        page_start: 57,
        page_end: 60,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
      {
        title: '路线和政策教育促进了农业的发展',
        authors: ['江苏如皋县革命委员会调查组'],
        page_start: 61,
        page_end: 64,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
      {
        title: '用辩证唯物论指导农田水利建设',
        authors: ['中国共产党衡水县委员会'],
        page_start: 65,
        page_end: 68,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
      {
        title: '立足农村生产搞好购销工作——长安县商业部门的调查报告',
        authors: ['陕西西安市革命委员会、长安县革命委员会联合调查组'],
        page_start: 69,
        page_end: 73,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
      {
        title: '在实践中寻找治虫的规律',
        authors: ['罗河山'],
        page_start: 74,
        page_end: 77,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
      {
        title:
          '艰苦奋斗 勤俭办学——内蒙古五原县民族公社复丰大队民办小学的调查报告',
        authors: ['中国共产党内蒙古自治区委员会调查组'],
        page_start: 78,
        page_end: 81,
        dates: [{ year: 1973, month: 6, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/285ab922-3283-4e23-9a9f-6c09b4f89f4c.pdf',
};
