export default {
  entity: {
    id: '2b2ad923-b246-40c1-9a00-a0d85a2a8788',
    name: '红旗一九六二年第十九期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/2b2ad923-b246-40c1-9a00-a0d85a2a8788.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中国共产党第八届中央委员会第十次全体会议的公报',
        authors: ['中国共产党中央委员会'],
        page_start: 3,
        page_end: 7,
        dates: [{ year: 1962, month: 10, day: 1 }],
      },
      {
        title: '新兴的人民力量是无敌的——庆祝伟大的中华人民共和国成立十三周年',
        authors: ['《红旗》杂志编辑部'],
        page_start: 8,
        page_end: 13,
        dates: [{ year: 1962, month: 10, day: 1 }],
      },
      {
        title: '衷心喜悦话史学',
        authors: ['陈垣'],
        page_start: 14,
        page_end: 15,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1962, month: 10, day: 1 }],
      },
      {
        title: '科学技术支援农业的光辉前景',
        authors: ['钱学森'],
        page_start: 17,
        page_end: 19,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1962, month: 10, day: 1 }],
      },
      {
        title: '喜看祖国的科学蓬勃发展',
        authors: ['竺可桢'],
        page_start: 19,
        page_end: 21,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1962, month: 10, day: 1 }],
      },
      {
        title: '欣欣向荣',
        authors: ['华罗庚'],
        page_start: 22,
        page_end: 23,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1962, month: 10, day: 1 }],
      },
      {
        title: '万寿无疆',
        authors: ['老舍'],
        page_start: 24,
        page_end: 26,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1962, month: 10, day: 1 }],
      },
      {
        title: '地方戏和年景',
        authors: ['赵树理'],
        page_start: 26,
        page_end: 28,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1962, month: 10, day: 1 }],
      },
      {
        title: '李大贵观礼',
        authors: ['周立波'],
        page_start: 29,
        page_end: 33,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1962, month: 10, day: 1 }],
      },
      {
        title: '集体研究和个人研究',
        authors: ['邢贲思'],
        page_start: 34,
        page_end: 38,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1962, month: 10, day: 1 }],
      },
      {
        title: '马克思主义论无产阶级的自我教育和自我改造',
        authors: ['范若愚'],
        page_start: 39,
        page_end: 43,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1962, month: 10, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/2b2ad923-b246-40c1-9a00-a0d85a2a8788.pdf',
};
