export default {
  entity: {
    id: '2c1e7af3-1eb3-4fdc-88be-78b70dffb524',
    name: '红旗一九七五年第七期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/2c1e7af3-1eb3-4fdc-88be-78b70dffb524.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '提倡调查研究',
        authors: ['池恒'],
        page_start: 6,
        page_end: 8,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '巩固和发展上山下乡的成果',
        authors: ['齐坚'],
        page_start: 9,
        page_end: 12,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '做好思想教育工作',
        authors: ['梁华'],
        page_start: 13,
        page_end: 14,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '为青年出版更多更好的自学读物——评《青年自学丛书》',
        authors: ['翟青'],
        page_start: 15,
        page_end: 19,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '充分发挥党组织的先锋队作用',
        authors: ['柏杉'],
        page_start: 20,
        page_end: 22,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '加强党的思想建设和组织建设',
        authors: ['向晖'],
        page_start: 23,
        page_end: 27,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '抓好农村党员的思想教育',
        authors: ['安徽利辛县柳西大队党支部'],
        page_start: 28,
        page_end: 31,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '做名副其实的共产党员',
        authors: ['李增锡'],
        page_start: 32,
        page_end: 34,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '正确认识我国的商品制度',
        authors: ['郑凯'],
        page_start: 35,
        page_end: 39,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '努力使主观符合客观——我们是怎样逐步做好天气预报的？',
        authors: ['贵州水城气象站'],
        page_start: 40,
        page_end: 45,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '论钱干活的思想要不得',
        authors: ['李小四'],
        page_start: 46,
        page_end: 48,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '搞协作非得靠“人情”吗？',
        authors: ['上海无线电十三厂工人理论小组'],
        page_start: 48,
        page_end: 49,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '从一根红头绳谈起',
        authors: ['淮南市李郢孜百货商店党支部'],
        page_start: 50,
        page_end: 51,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '学理论 促生产——天津市电子仪器厂的调查报告',
        authors: ['第四机械工业部、天津市第二机械局调查组'],
        page_start: 52,
        page_end: 55,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '法家路线和黄老思想——读帛书《经法》',
        authors: ['康立', '卫今'],
        page_start: 56,
        page_end: 65,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '照毛主席的思想办农业',
        authors: ['葛静'],
        page_start: 66,
        page_end: 70,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '搞好钢铁生产的根本问题在路线',
        authors: ['章迪'],
        page_start: 71,
        page_end: 74,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '注意发展轻工业',
        authors: ['钟成'],
        page_start: 75,
        page_end: 78,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '为革命做好商品供应工作',
        authors: ['北京市西单菜市场党支部'],
        page_start: 79,
        page_end: 81,
        dates: [{ year: 1975, month: 7 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/2c1e7af3-1eb3-4fdc-88be-78b70dffb524.pdf',
};
