export default {
  entity: {
    id: '2ce1c58d-24f9-4cbb-b9c1-7430b717d8a5',
    name: '红旗一九六六年第十三期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/2ce1c58d-24f9-4cbb-b9c1-7430b717d8a5.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '在中华人民共和国成立十七周年庆祝大会上的讲话',
        authors: ['林彪'],
        page_start: 4,
        page_end: 5,
        dates: [{ year: 1966, month: 10, day: 1 }],
      },
      {
        title: '在毛泽东思想的大路上前进（一九六六年第十三期社论）',
        alias: '在毛泽东思想的大路上前进',
        authors: ['《红旗》杂志编辑部'],
        page_start: 6,
        page_end: 8,
        dates: [{ year: 1966, month: 10, day: 3 }],
      },
      {
        title: '夺取革命和生产的更大胜利',
        authors: ['王进喜'],
        page_start: 9,
        page_end: 13,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1966 }],
      },
      {
        title: '在毛泽东思想的光辉照耀下飞跃前进',
        authors: ['蔡祖泉'],
        page_start: 13,
        page_end: 14,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1966 }],
      },
      {
        title: '思想革命带动生产革命',
        authors: ['吕玉兰'],
        page_start: 15,
        page_end: 17,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1966 }],
      },
      {
        title: '毛主席，您是我们心中的红太阳',
        authors: ['罗昌秀'],
        page_start: 17,
        page_end: 18,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1966 }],
      },
      {
        title: '人民战士永远忠于毛主席',
        authors: ['卢燕财'],
        page_start: 19,
        page_end: 21,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1966 }],
      },
      {
        title: '新北大在高歌猛进',
        authors: ['长缨'],
        page_start: 20,
        page_end: 22,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1966 }],
      },
      {
        title: '把连队建设成毛泽东思想的好学校',
        authors: ['陈金元'],
        page_start: 23,
        page_end: 33,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1966 }],
      },
      {
        title:
          '用毛泽东思想武装农民的头脑——山西省昔阳县大寨大队政治思想工作的基本经验',
        authors: ['陈永贵'],
        page_start: 34,
        page_end: 42,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1966 }],
      },
      {
        title: '为人民管好油井',
        authors: ['胡法莲'],
        page_start: 43,
        page_end: 47,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1966 }],
      },
      {
        title: '把毕生的力量贡献给革命事业',
        authors: ['姚建纲'],
        page_start: 47,
        page_end: 52,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1966 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.17, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/2ce1c58d-24f9-4cbb-b9c1-7430b717d8a5.pdf',
};
