export default {
  entity: {
    id: '356e2bad-8081-41ca-9f6e-bdc965755b3e',
    name: '红旗一九六四年第十期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/356e2bad-8081-41ca-9f6e-bdc965755b3e.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '南斯拉夫全民所有制经济的蜕化',
        authors: ['施东向'],
        page_start: 3,
        page_end: 21,
        dates: [{ year: 1964 }],
      },
      {
        title: '论人的因素第一',
        authors: ['红旗杂志评论员'],
        page_start: 22,
        page_end: 28,
        dates: [{ year: 1964 }],
      },
      {
        title: '我军指战员怎样学习毛泽东著作',
        authors: ['肖华'],
        page_start: 29,
        page_end: 36,
        dates: [{ year: 1964 }],
      },
      {
        title: '学习理论的目的全在应用',
        authors: ['王承放'],
        page_start: 37,
        page_end: 39,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '挤和钻',
        authors: ['苏思本'],
        page_start: 38,
        page_end: 40,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title:
          '更广泛、更深入地开展“比学赶帮”运动——华东地区在工业战线上开展“比学赶帮”运动的几点体会',
        authors: ['韩哲一'],
        page_start: 41,
        page_end: 48,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '关于实践标准问题讨论的情况',
        authors: ['红旗杂志评论员'],
        page_start: 49,
        page_end: 51,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '实践是检验真理的唯一的客观标准——与何祚庥同志商榷',
        authors: ['杜雷', '吴俊光'],
        page_start: 52,
        page_end: 57,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '再谈自然科学研究中的实践标准问题——答杜雷、吴俊光、陶德麟等同志',
        authors: ['何祚庥'],
        page_start: 57,
        page_end: 67,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
    ],
    ocr: { content_thresholds: [0.07, 0.165, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/356e2bad-8081-41ca-9f6e-bdc965755b3e.pdf',
};
