export default {
  entity: {
    id: '35fcf895-4895-4e9c-b2be-89d0ff5aabf3',
    name: '红旗一九五八年第十二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/35fcf895-4895-4e9c-b2be-89d0ff5aabf3.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '驳工业战线上群众路线的怀疑派',
        authors: ['《人民日报》编辑部'],
        page_start: 3,
        page_end: 9,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958 }],
      },
      {
        title: '长春汽车厂为争取年产十五万辆汽车而奋斗',
        authors: ['饶斌'],
        page_start: 9,
        page_end: 14,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958 }],
      },
      {
        title: '在大型企业中贯彻群众路线的一面红旗',
        authors: ['刘志兰', '房昭文'],
        page_start: 14,
        page_end: 17,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958 }],
      },
      {
        title: '插红旗，拔白旗',
        authors: ['中共湖南省委会'],
        page_start: 18,
        ocr: { vsplit: 0.35 },
        page_end: 21,
        dates: [{ year: 1958 }],
      },
      {
        title:
          '从是否“已经到了共产主义”说起——有关农村的社会主义和共产主义教育运动的两点意见',
        authors: ['许立群'],
        page_start: 22,
        page_end: 26,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958 }],
      },
      {
        title: '发扬共产主义的劳动精神',
        authors: ['王立'],
        page_start: 27,
        page_end: 30,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958 }],
      },
      {
        title: '抓住时代的精神',
        authors: ['关锋'],
        page_start: 31,
        page_end: 32,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958 }],
      },
      {
        title: '是少种多收好，还是广种薄收好——石楼县建立基本农田的胜利',
        authors: ['中共石楼县委会'],
        page_start: 33,
        ocr: { vsplit: 0.35 },
        page_end: 36,
        dates: [{ year: 1958 }],
      },
      {
        title: '开展大面积的高额丰产运动',
        authors: ['阎达开'],
        page_start: 37,
        ocr: { vsplit: 0.35 },
        page_end: 39,
        dates: [{ year: 1958 }],
      },
      {
        title:
          '一个办得很象样子的公共食堂——山西省五寨县火箭人民公社东寨生产队公共食堂的简要介绍',
        authors: ['范若愚'],
        page_start: 40,
        ocr: { vsplit: 0.35 },
        page_end: 43,
        dates: [{ year: 1958 }],
      },
    ],
    ocr: {
      auto_vsplit: false,
      vsplit: 0,
      content_thresholds: [0, 0.185, 0, 0.1],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/35fcf895-4895-4e9c-b2be-89d0ff5aabf3.pdf',
};
