export default {
  entity: {
    id: '36113ef7-6801-471c-b40f-17338077deac',
    name: '毛泽东选集第一卷（人民出版社1991年版）',
    internal: true,
    official: true,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/36113ef7-6801-471c-b40f-17338077deac.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '第二版说明',
        authors: ['中共中央文献编辑委员会'],
        page_start: 5,
        page_end: 6,
        dates: [{ year: 1991, month: 2 }],
      },
      {
        title: '本书出版的说明',
        authors: ['中共中央毛泽东选集出版委员会'],
        page_start: 7,
        page_end: 8,
        dates: [{ year: 1951, month: 8, day: 25 }],
      },
      {
        title: '中国社会各阶级的分析',
        authors: ['毛泽东'],
        page_start: 16,
        page_end: 24,
        dates: [{ year: 1925, month: 12, day: 1 }],
      },
      {
        title: '湖南农民运动考察报告',
        authors: ['毛泽东'],
        page_start: 16,
        page_end: 24,
        dates: [{ year: 1927, month: 3 }],
      },
      {
        title: '湖南农民运动考察报告',
        authors: ['毛泽东'],
        page_start: 25,
        page_end: 57,
        dates: [{ year: 1927, month: 3 }],
      },
      {
        title: '中国的红色政权为什么能够存在？',
        authors: ['毛泽东'],
        page_start: 60,
        page_end: 69,
        dates: [{ year: 1928, month: 10, day: 5 }],
      },
      {
        title: '井冈山的斗争',
        authors: ['毛泽东'],
        page_start: 70,
        page_end: 97,
        dates: [{ year: 1928, month: 11, day: 25 }],
      },
      {
        title: '关于纠正党内的错误思想',
        authors: ['毛泽东'],
        page_start: 98,
        page_end: 109,
        dates: [{ year: 1929, month: 11 }],
      },
      {
        title: '星星之火，可以燎原',
        authors: ['毛泽东'],
        page_start: 110,
        page_end: 121,
        dates: [{ year: 1930, month: 1, day: 5 }],
      },
      {
        title: '反对本本主义',
        authors: ['毛泽东'],
        page_start: 122,
        page_end: 131,
        dates: [{ year: 1930, month: 5 }],
      },
      {
        title: '必须注意经济工作',
        authors: ['毛泽东'],
        page_start: 132,
        page_end: 139,
        dates: [{ year: 1933, month: 8, day: 12 }],
      },
      {
        title: '怎样分析农村阶级',
        authors: ['毛泽东'],
        page_start: 140,
        page_end: 142,
        dates: [{ year: 1933, month: 10 }],
      },
      {
        title: '我们的经济政策',
        authors: ['毛泽东'],
        page_start: 143,
        page_end: 148,
        dates: [{ year: 1934, month: 1 }],
      },
      {
        title: '关心群众生活，注意工作方法',
        authors: ['毛泽东'],
        page_start: 149,
        page_end: 154,
        dates: [{ year: 1934, month: 1, day: 27 }],
      },
      {
        title: '论反对日本帝国主义的策略',
        authors: ['毛泽东'],
        page_start: 155,
        page_end: 182,
        dates: [{ year: 1935, month: 12, day: 27 }],
      },
      {
        title: '中国革命战争的战略问题',
        authors: ['毛泽东'],
        page_start: 183,
        page_end: 257,
        dates: [{ year: 1936, month: 12 }],
      },
      {
        title: '关于蒋介石声明的声明',
        authors: ['毛泽东'],
        page_start: 228,
        page_end: 264,
        dates: [{ year: 1936, month: 12, day: 28 }],
      },
      {
        title: '中国共产党在抗日时期的任务',
        authors: ['毛泽东'],
        page_start: 265,
        page_end: 283,
        dates: [{ year: 1937, month: 5, day: 3 }],
      },
      {
        title: '为争取千百万群众进入抗日民族统一战线而斗争',
        authors: ['毛泽东'],
        page_start: 284,
        page_end: 294,
        dates: [{ year: 1937, month: 5, day: 8 }],
      },
      {
        title: '实践论',
        authors: ['毛泽东'],
        page_start: 295,
        page_end: 311,
        dates: [{ year: 1937, month: 7 }],
      },
      {
        title: '矛盾论',
        authors: ['毛泽东'],
        page_start: 312,
        page_end: 353,
        dates: [{ year: 1937, month: 8 }],
      },
    ],
    ocr: { content_thresholds: [0.126, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/36113ef7-6801-471c-b40f-17338077deac.pdf',
};
