export default {
  entity: {
    id: '36b5e385-285a-4fbc-8942-a78e1a52df93',
    name: '红旗一九五八年第三期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/36b5e385-285a-4fbc-8942-a78e1a52df93.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '浪漫主义和现实主义',
        authors: ['郭沫若'],
        page_start: 3,
        page_end: 10,
        ocr: { vsplit: 0.371 },
        dates: [{ year: 1958, month: 6, day: 20 }],
      },
      {
        title: '全新的社会，全新的人',
        authors: ['陈伯达'],
        page_start: 11,
        page_end: 13,
        dates: [{ year: 1958 }],
      },
      {
        title: '旭光一社用土办法办小小工厂',
        authors: ['中共鄂城县委会'],
        page_start: 13,
        page_end: 16,
        dates: [{ year: 1958 }],
        ocr: { vsplit: 0.35 },
      },
      {
        title: '旭光一社市怎样领导和管理小小工厂的',
        authors: ['中共鄂城县委会'],
        page_start: 17,
        page_end: 19,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958, month: 5, day: 25 }],
      },
      {
        title: '打破办工业的神秘观点',
        authors: ['薄一波'],
        page_start: 20,
        ocr_exceptions: {
          '20': { content_thresholds: [0, 0.168, 0.137, 0.1] },
        },
        page_end: 23,
        dates: [{ year: 1958 }],
      },
      {
        title: '草木之争',
        authors: ['宋乃德'],
        page_start: 24,
        page_end: 27,
        dates: [{ year: 1958 }],
      },
      {
        title: '发展地方工业的“四带”措施',
        authors: [],
        page_start: 26,
        page_end: 27,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958 }],
      },
      {
        title: '养捕之争',
        authors: ['高文华'],
        page_start: 28,
        page_end: 31,
        dates: [{ year: 1958 }],
      },
      {
        title: '六个人的小工厂大搞技术革新',
        authors: [],
        page_start: 30,
        ocr: { vsplit: 0.35 },
        page_end: 31,
        dates: [{ year: 1958 }],
      },
      {
        title: '从实际出发，还是从主观出发？',
        authors: ['孔桑'],
        page_start: 32,
        page_end: 34,
        dates: [{ year: 1958 }],
      },
      {
        title: '现场会议',
        authors: ['中共湖北省委会'],
        page_start: 35,
        page_end: 38,
        dates: [{ year: 1958, month: 5, day: 30 }],
      },
      {
        title: '检查评比',
        authors: ['万良才'],
        page_start: 39,
        page_end: 42,
        dates: [{ year: 1958, month: 6, day: 7 }],
      },
      {
        title: '以创造精神办街道工业',
        authors: [],
        page_start: 42,
        ocr: { vsplit: 0.35 },
        page_end: 43,
        dates: [{ year: 1958 }],
      },
    ],
    ocr: {
      auto_vsplit: false,
      vsplit: 0,
      content_thresholds: [0, 0.18, 0, 0.1],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/36b5e385-285a-4fbc-8942-a78e1a52df93.pdf',
};
