export default {
  entity: {
    id: '377f88dc-5ac4-413e-8c77-4f6dbc3e8da6',
    name: '毛泽东著作选读（甲种本）（人民出版社1965年版）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '毛泽东，人民出版社1965年版',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/377f88dc-5ac4-413e-8c77-4f6dbc3e8da6.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '出版说明',
        authors: ['毛泽东著作编辑选读委员会'],
        page_start: 3,
        page_end: 3,
        dates: [{ year: 1965, month: 3 }],
      },
      {
        title: '中国社会各阶级的分析',
        authors: ['毛泽东'],
        page_start: 10,
        page_end: 17,
        dates: [{ year: 1926, month: 3 }],
      },
      {
        title: '湖南农民运动考察报告',
        authors: ['毛泽东'],
        page_start: 18,
        page_end: 28,
        dates: [{ year: 1927, month: 3 }],
      },
      {
        title: '反对本本主义',
        authors: ['毛泽东'],
        page_start: 29,
        page_end: 37,
        dates: [{ year: 1930, month: 5 }],
      },
      {
        title: '关心群众生活，注意工作方法',
        authors: ['毛泽东'],
        page_start: 38,
        page_end: 43,
        dates: [{ year: 1934, month: 1, day: 27 }],
      },
      {
        title: '重要的问题在善于学习',
        authors: ['毛泽东'],
        page_start: 44,
        page_end: 48,
        dates: [{ year: 1936, month: 12 }],
      },
      {
        title: '实践论',
        authors: ['毛泽东'],
        page_start: 49,
        page_end: 64,
        dates: [{ year: 1937, month: 7 }],
      },
      {
        title: '矛盾论',
        authors: ['毛泽东'],
        page_start: 65,
        page_end: 103,
        dates: [{ year: 1937, month: 8 }],
      },
      {
        title: '反对自由主义',
        authors: ['毛泽东'],
        page_start: 104,
        page_end: 123,
        dates: [{ year: 1937, month: 9, day: 7 }],
      },
      {
        title: '被敌人反对是好事而不是坏事',
        authors: ['毛泽东'],
        page_start: 124,
        page_end: 125,
        dates: [{ year: 1939, month: 5, day: 26 }],
      },
      {
        title: '《共产党人》发刊词',
        authors: ['毛泽东'],
        page_start: 126,
        page_end: 138,
        dates: [{ year: 1939, month: 10, day: 4 }],
      },
      {
        title: '纪念白求恩',
        authors: ['毛泽东'],
        page_start: 139,
        page_end: 140,
        dates: [{ year: 1939, month: 12, day: 21 }],
      },
      {
        title: '目前抗日统一战线中的策略问题',
        authors: ['毛泽东'],
        page_start: 141,
        page_end: 152,
        dates: [{ year: 1940, month: 3, day: 11 }],
      },
      {
        title: '改造我们的学习',
        authors: ['毛泽东'],
        page_start: 153,
        page_end: 160,
        dates: [{ year: 1941, month: 5 }],
      },
      {
        title: '整顿党的作风',
        authors: ['毛泽东'],
        page_start: 161,
        page_end: 177,
        dates: [{ year: 1942, month: 2, day: 1 }],
      },
      {
        title: '反对党八股',
        authors: ['毛泽东'],
        page_start: 178,
        page_end: 193,
        dates: [{ year: 1942, month: 2, day: 8 }],
      },
      {
        title: '在延安文艺座谈会上的讲话',
        authors: ['毛泽东'],
        page_start: 194,
        page_end: 223,
        dates: [{ year: 1942, month: 5 }],
      },
      {
        title: '关于领导方法的若干问题',
        authors: ['毛泽东'],
        page_start: 224,
        page_end: 229,
        dates: [{ year: 1943, month: 6, day: 1 }],
      },
      {
        title: '组织起来',
        authors: ['毛泽东'],
        page_start: 230,
        page_end: 238,
        dates: [{ year: 1943, month: 11, day: 29 }],
      },
      {
        title: '放下包袱，开动机器',
        authors: ['毛泽东'],
        page_start: 239,
        page_end: 241,
        dates: [{ year: 1944, month: 4, day: 12 }],
      },
      {
        title: '为人民服务',
        authors: ['毛泽东'],
        page_start: 242,
        page_end: 243,
        dates: [{ year: 1944, month: 9, day: 8 }],
      },
      {
        title: '全党团结起来，为实现党的任务而斗争',
        authors: ['毛泽东'],
        page_start: 244,
        page_end: 249,
        dates: [{ year: 1945, month: 4, day: 24 }],
      },
      {
        title: '愚公移山',
        authors: ['毛泽东'],
        page_start: 250,
        page_end: 253,
        dates: [{ year: 1945, month: 6, day: 11 }],
      },
      {
        title: '抗日战争胜利后的时局和我们的方针',
        authors: ['毛泽东'],
        page_start: 254,
        page_end: 266,
        dates: [{ year: 1945, month: 8, day: 13 }],
      },
      {
        title: '关于目前国际形势的几点估计',
        authors: ['毛泽东'],
        page_start: 267,
        page_end: 268,
        dates: [{ year: 1946, month: 4 }],
      },
      {
        title: '和美国记者安娜·路易斯·斯特朗的谈话',
        authors: ['毛泽东'],
        page_start: 269,
        page_end: 273,
        dates: [{ year: 1946, month: 8 }],
      },
      {
        title: '党内反对错误倾向问题',
        authors: ['毛泽东'],
        page_start: 274,
        page_end: 275,
        dates: [{ year: 1948, month: 1, day: 18 }],
      },
      {
        title: '对晋绥日报编辑人员的谈话',
        authors: ['毛泽东'],
        page_start: 276,
        page_end: 280,
        dates: [{ year: 1948, month: 4, day: 2 }],
      },
      {
        title: '关于健全党委制',
        authors: ['毛泽东'],
        page_start: 281,
        page_end: 282,
        dates: [{ year: 1948, month: 9, day: 20 }],
      },
      {
        title: '继续保持艰苦奋斗的作风',
        authors: ['毛泽东'],
        page_start: 283,
        page_end: 284,
        dates: [{ year: 1949, month: 3, day: 5 }],
      },
      {
        title: '党委会的工作方法',
        authors: ['毛泽东'],
        page_start: 285,
        page_end: 289,
        dates: [{ year: 1949, month: 3, day: 13 }],
      },
      {
        title: '论人民民主专政纪念中国共产党二十八周年',
        alias: '论人民民主专政 纪念中国共产党二十八周年',
        authors: ['毛泽东'],
        page_start: 290,
        page_end: 303,
        dates: [{ year: 1949, month: 6, day: 30 }],
      },
      {
        title: '关于农业合作化问题',
        authors: ['毛泽东'],
        page_start: 304,
        page_end: 327,
        dates: [{ year: 1955, month: 7, day: 31 }],
      },
      {
        title: '《中国农村的社会主义高潮》按语选',
        authors: ['毛泽东'],
        page_start: 328,
        page_end: 335,
        dates: [
          { year: 1955, month: 9 },
          { year: 1955, month: 12 },
        ],
      },
      {
        title: '关于正确处理人民内部矛盾的问题',
        authors: ['毛泽东'],
        page_start: 336,
        page_end: 373,
        dates: [{ year: 1957, month: 2, day: 27 }],
      },
      {
        title: '在中国共产党全国宣传工作会议上的讲话',
        authors: ['毛泽东'],
        page_start: 374,
        page_end: 389,
        dates: [{ year: 1957, month: 3, day: 12 }],
      },
      {
        title: '介绍一个合作社',
        authors: ['毛泽东'],
        page_start: 390,
        page_end: 391,
        dates: [{ year: 1958, month: 4, day: 15 }],
      },
      {
        title: '人的正确思想是从那里来的？',
        authors: ['毛泽东'],
        page_start: 392,
        page_end: 393,
        dates: [{ year: 1963, month: 5 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.12, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/377f88dc-5ac4-413e-8c77-4f6dbc3e8da6.pdf',
};
