export default {
  entity: {
    id: '39332105-8098-4d2b-b85d-1f30059627f1',
    name: '自然辩证法一九七五年第一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《自然辩证法》编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/39332105-8098-4d2b-b85d-1f30059627f1.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title:
          '土壤肥力是能够不断提高的——从上海市郊区土壤肥力调查看“土壤肥力递减论”的破产',
        authors: ['上海市农业科学院'],
        page_start: 6,
        page_end: 15,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '评大脑生理学中的唯心论倾向',
        authors: ['单世谊'],
        page_start: 16,
        page_end: 27,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '薛定谔的“捷径”通向何处？——评《生命是什么》一书',
        authors: ['单世谊'],
        page_start: 28,
        page_end: 36,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '喜看沃土育新苗',
        authors: ['宋志清'],
        page_start: 47,
        page_end: 50,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '利用变异规律培育水稻良种',
        authors: ['上海市跃进农场七连'],
        page_start: 51,
        page_end: 54,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '喝令盐碱荒滩献粮棉',
        authors: ['上海市前哨农场五·七战斗连'],
        page_start: 55,
        page_end: 58,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '我们也种出了丰产棉',
        authors: ['上海市新海农场二连六班'],
        page_start: 59,
        page_end: 63,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '新型喷雾器的诞生',
        authors: ['上海市红星农场七连超低量喷雾器试制小组'],
        page_start: 64,
        page_end: 66,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '猪棚里面有学问',
        authors: ['上海市东风农场第六饲养场'],
        page_start: 67,
        page_end: 69,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '大田接种“五四〇六”菌肥的体会',
        authors: ['李镇桐'],
        page_start: 70,
        page_end: 73,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '努力赢得种田的自由',
        authors: ['上海市金山县金卫公社八二大队党支部'],
        page_start: 74,
        page_end: 81,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '多快好省研制井岗霉素',
        authors: ['上海市农药研究所'],
        page_start: 82,
        page_end: 87,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '土地少也能多种经营',
        authors: ['上海市宝山县吴淞公社张建浜大队'],
        page_start: 88,
        page_end: 91,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '低产鱼塘是怎样实现高产的',
        authors: ['上海市南汇县水产养殖场'],
        page_start: 92,
        page_end: 98,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '河蟹为什么又多起来了',
        authors: ['上海市水产研究所'],
        page_start: 99,
        page_end: 103,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '动物园里有哲学',
        authors: ['上海西郊公园革委会'],
        page_start: 104,
        page_end: 109,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title:
          '毛主席的军事思想指挥我们战斗——一位严重挤压伤病员是怎样抢救过来的？',
        authors: ['上海第一医学院中山医院'],
        page_start: 110,
        page_end: 117,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '坚持走理论联系实际的路',
        authors: ['陈念贻'],
        page_start: 118,
        page_end: 123,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '燃素说的兴衰',
        authors: ['金若水'],
        page_start: 124,
        page_end: 147,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '《齐民要术》选注',
        authors: ['刘民壮'],
        page_start: 148,
        page_end: 162,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '《齐民要术》选注',
        authors: ['刘民壮'],
        page_start: 148,
        page_end: 162,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '海克尔论变异和遗传的矛盾',
        authors: ['海克尔'],
        page_start: 163,
        page_end: 173,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '沙漠归来',
        authors: ['殷虹'],
        page_start: 174,
        page_end: 185,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '北宋时期的著名科学家——沈括',
        authors: ['史毅'],
        page_start: 186,
        page_end: 196,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '意识经验论两篇',
        authors: ['艾克尔斯'],
        page_start: 197,
        page_end: 208,
        dates: [{ year: 1975, month: 3 }],
      },
      {
        title: '从两棵棉花到亩产皮棉238斤',
        authors: ['上海赴安徽知识青年慰问团'],
        page_start: 209,
        page_end: 209,
        dates: [{ year: 1975, month: 3 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.12, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/39332105-8098-4d2b-b85d-1f30059627f1.pdf',
};
