export default {
  entity: {
    id: '39f5c300-d854-414d-a93f-a0cfd049f55b',
    name: '列宁选集 第三卷（1972年）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '列宁，人民出版社',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives5/main/39f5c300-d854-414d-a93f-a0cfd049f55b.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '远方来信（摘录）',
        authors: ['列宁'],
        page_start: 13,
        page_end: 24,
        dates: [{ year: 1917, month: 3, day: 7 }],
      },
      {
        title: '论无产阶级在这次革命中的任务',
        authors: ['列宁'],
        page_start: 25,
        page_end: 30,
        dates: [{ year: 1917, month: 4, day: 7 }],
      },
      {
        title: '论两个政权',
        authors: ['列宁'],
        page_start: 31,
        page_end: 34,
        dates: [{ year: 1917, month: 4, day: 9 }],
      },
      {
        title: '论策略书',
        authors: ['列宁'],
        page_start: 35,
        page_end: 47,
        is_range_date: true,
        dates: [
          { year: 1917, month: 4, day: 8 },
          { year: 1917, month: 4, day: 13 },
        ],
      },
      {
        title: '无产阶级在我国革命中的任务（无产阶级政党的行动纲领草案）',
        authors: ['列宁'],
        page_start: 48,
        page_end: 81,
        dates: [{ year: 1917, month: 4, day: 10 }],
      },
      {
        title: '战争与革命（1917年5月14日（27日）的演讲）',
        authors: ['列宁'],
        page_start: 82,
        page_end: 104,
        dates: [{ year: 1917, month: 5, day: 14 }],
      },
      {
        title: '全俄农民第一次代表大会关于土地问题的决议草案',
        authors: ['列宁'],
        page_start: 105,
        page_end: 106,
        dates: [{ year: 1917, month: 5, day: 17 }],
      },
      {
        title:
          '关于对临时政府的态度的演说（1917年6月4日 （17日）在全俄工兵代表苏维埃第一次代表大会上）',
        authors: ['列宁'],
        page_start: 107,
        page_end: 118,
        dates: [{ year: 1917, month: 6, day: 4 }],
      },
      {
        title: '论口号',
        authors: ['列宁'],
        page_start: 119,
        page_end: 126,
        dates: [{ year: 1917, month: 7 }],
      },
      {
        title: '革命的教训',
        authors: ['列宁'],
        page_start: 127,
        page_end: 141,
        dates: [
          { year: 1917, month: 7 },
          { year: 1917, month: 9, day: 6 },
        ],
      },
      {
        title: '大难临头，出路何在？',
        authors: ['列宁'],
        page_start: 142,
        page_end: 182,
        is_range_date: true,
        dates: [
          { year: 1917, month: 9, day: 10 },
          { year: 1917, month: 9, day: 14 },
        ],
      },
      {
        title: '国家与革命（马克思主义关于国家的学说与无产阶级在革命中的任务）',
        authors: ['列宁'],
        page_start: 183,
        page_end: 288,
        is_range_date: true,
        dates: [
          { year: 1917, month: 8 },
          { year: 1917, month: 9 },
        ],
      },
      {
        title: '马克思主义和起义（给俄国社会民主工党中央委员会的信）',
        authors: ['列宁'],
        page_start: 289,
        page_end: 295,
        is_range_date: true,
        dates: [
          { year: 1917, month: 9, day: 13 },
          { year: 1917, month: 9, day: 14 },
        ],
      },
      {
        title: '革命的任务',
        authors: ['列宁'],
        page_start: 296,
        page_end: 305,
        dates: [
          { year: 1917, month: 10, day: 9 },
          { year: 1917, month: 10, day: 10 },
        ],
      },
      {
        title: '布尔什维克能保持国家政权吗？',
        authors: ['列宁'],
        page_start: 306,
        page_end: 353,
        is_range_date: true,
        dates: [
          { year: 1917, month: 9 },
          { year: 1917, month: 10, day: 1 },
        ],
      },
      {
        title: '局外人的意见',
        authors: ['列宁'],
        page_start: 354,
        page_end: 356,
        dates: [{ year: 1917, month: 10, day: 8 }],
      },
      {
        title: '俄国社会民主工党中央委员会关于武装起义的决议',
        authors: ['列宁'],
        page_start: 357,
        page_end: 357,
        dates: [{ year: 1917, month: 10, day: 10 }],
      },
      {
        title: '给布尔什维克党党员的信',
        authors: ['列宁'],
        page_start: 358,
        page_end: 361,
        dates: [{ year: 1917, month: 10, day: 18 }],
      },
      {
        title: '给中央委员的信',
        authors: ['列宁'],
        page_start: 362,
        page_end: 363,
        dates: [{ year: 1917, month: 10, day: 24 }],
      },
      {
        title:
          '全俄工兵代表苏维埃第二次代表大会（摘录）（1917年10月25—26日（11月7—8日））',
        authors: ['列宁'],
        page_start: 364,
        page_end: 378,
        dates: [{ year: 1917, month: 10, day: 28 }],
      },
      {
        title: '工人监督条例草案',
        authors: ['列宁'],
        page_start: 379,
        page_end: 380,
        is_range_date: true,
        dates: [
          { year: 1917, month: 10, day: 26 },
          { year: 1917, month: 10, day: 31 },
        ],
      },
      {
        title:
          '俄国社会民主工党（布尔什维克）中央委员会宣言（告全体党员及俄国一切劳动阶级书）',
        authors: ['列宁'],
        page_start: 381,
        page_end: 385,
        is_range_date: true,
        dates: [
          { year: 1917, month: 11, day: 5 },
          { year: 1917, month: 11, day: 6 },
        ],
      },
      {
        title: '工人同被剥削劳动农民的联盟（给《真理报》编辑部的信）',
        authors: ['列宁'],
        page_start: 386,
        page_end: 388,
        dates: [{ year: 1917, month: 11, day: 18 }],
      },
      {
        title: '关于立宪会议的提纲',
        authors: ['列宁'],
        page_start: 389,
        page_end: 393,
        dates: [{ year: 1917, month: 12, day: 12 }],
      },
      {
        title:
          '在全俄中央执行委员会会议上关于银行国有化问题的发言（1917年12月14日（27日））',
        authors: ['列宁'],
        page_start: 394,
        page_end: 396,
        dates: [{ year: 1917, month: 12, day: 16 }],
      },
      {
        title: '关于实行银行国有化及其必要措施的法令草案',
        authors: ['列宁'],
        page_start: 397,
        page_end: 399,
        dates: [{ year: 1917, month: 12 }],
      },
      {
        title: '被旧事物的破灭吓坏了的和为新事物而斗争的',
        authors: ['列宁'],
        page_start: 400,
        page_end: 403,
        is_range_date: true,
        dates: [
          { year: 1917, month: 12, day: 25 },
          { year: 1917, month: 12, day: 28 },
        ],
      },
      {
        title: '怎样组织竞赛？',
        authors: ['列宁'],
        page_start: 404,
        page_end: 413,
        is_range_date: true,
        dates: [
          { year: 1917, month: 12, day: 25 },
          { year: 1917, month: 12, day: 28 },
        ],
      },
      {
        title: '关于消费公社的法令草案',
        authors: ['列宁'],
        page_start: 414,
        page_end: 415,
        is_range_date: true,
        dates: [
          { year: 1917, month: 12, day: 25 },
          { year: 1917, month: 12, day: 28 },
        ],
      },
      {
        title: '被剥削劳动人民权利宣言',
        authors: ['列宁'],
        page_start: 416,
        page_end: 418,
        dates: [{ year: 1918, month: 1 }],
      },
      {
        title: '解散立宪会议的法令草案',
        authors: ['列宁'],
        page_start: 419,
        page_end: 420,
        dates: [{ year: 1918, month: 1, day: 6 }],
      },
      {
        title: '谈谈不幸的和约问题的历史',
        authors: ['列宁'],
        page_start: 421,
        page_end: 429,
        dates: [{ year: 1918, month: 2, day: 24 }],
      },
      {
        title:
          '关于人民委员会工作的报告（1918年1月11日（24日）在全俄工兵农代表苏维埃第三次代表大会上）',
        authors: ['列宁'],
        page_start: 430,
        page_end: 447,
        dates: [{ year: 1918, month: 1, day: 11 }],
      },
      {
        title: '社会主义祖国在危急中！',
        authors: ['列宁'],
        page_start: 448,
        page_end: 449,
        dates: [{ year: 1918, month: 2, day: 21 }],
      },
      {
        title: '奇谈与怪论',
        authors: ['列宁'],
        page_start: 450,
        page_end: 457,
        dates: [
          { year: 1918, month: 2, day: 28 },
          { year: 1918, month: 3, day: 1 },
        ],
      },
      {
        title: '严重的教训与严重的责任',
        authors: ['列宁'],
        page_start: 458,
        page_end: 463,
        dates: [{ year: 1918, month: 3, day: 5 }],
      },
      {
        title:
          '关于战争与和平的报告（1918年3月7日在俄共（布）第七次代表大会上）',
        authors: ['列宁'],
        page_start: 464,
        page_end: 486,
        dates: [{ year: 1918, month: 3, day: 7 }],
      },
      {
        title:
          '关于修改党纲和更改党的名称的报告（1918年3月8日晚上在俄共（布）第七次代表大会上）',
        authors: ['列宁'],
        page_start: 487,
        page_end: 499,
        dates: [{ year: 1918, month: 3, day: 8 }],
      },
      {
        title: '当前的主要任务',
        authors: ['列宁'],
        page_start: 500,
        page_end: 504,
        dates: [{ year: 1918, month: 3, day: 11 }],
      },
      {
        title: '苏维埃政权的当前任务',
        authors: ['列宁'],
        page_start: 505,
        page_end: 541,
        is_range_date: true,
        dates: [
          { year: 1918, month: 3 },
          { year: 1918, month: 4 },
        ],
      },
      {
        title: '论“左派”幼稚性和小资产阶级性',
        authors: ['列宁'],
        page_start: 542,
        page_end: 571,
        dates: [{ year: 1918, month: 5, day: 5 }],
      },
      {
        title: '论饥荒（给彼得格勒工人的信）',
        authors: ['列宁'],
        page_start: 572,
        page_end: 579,
        dates: [{ year: 1918, month: 5, day: 22 }],
      },
      {
        title: '在国民经济委员会第一次代表大会上的演说（1918年5月26日）',
        authors: ['列宁'],
        page_start: 580,
        page_end: 587,
        dates: [{ year: 1918, month: 5, day: 26 }],
      },
      {
        title: '预言',
        authors: ['列宁'],
        page_start: 588,
        page_end: 593,
        dates: [{ year: 1918, month: 6, day: 29 }],
      },
      {
        title: '工人同志们！大家都来进行最后的决战！',
        authors: ['列宁'],
        page_start: 594,
        page_end: 597,
        dates: [{ year: 1918, month: 8 }],
      },
      {
        title: '给美国工人的信',
        authors: ['列宁'],
        page_start: 598,
        page_end: 611,
        dates: [{ year: 1918, month: 8, day: 20 }],
      },
      {
        title: '论我们报纸的性质',
        authors: ['列宁'],
        page_start: 612,
        page_end: 614,
        dates: [{ year: 1918, month: 9, day: 20 }],
      },
      {
        title: '在马克思恩格斯纪念碑揭幕典礼上的讲话',
        authors: ['列宁'],
        page_start: 615,
        page_end: 616,
        dates: [{ year: 1918, month: 11, day: 7 }],
      },
      {
        title: '在全俄肃反委员会工作人员游艺大会上的演说',
        authors: ['列宁'],
        page_start: 617,
        page_end: 618,
        dates: [{ year: 1918, month: 11, day: 7 }],
      },
      {
        title: '皮梯利姆·索罗金的宝贵自供',
        authors: ['列宁'],
        page_start: 619,
        page_end: 627,
        dates: [{ year: 1918, month: 11, day: 20 }],
      },
      {
        title: '无产阶级革命和叛徒考茨基',
        authors: ['列宁'],
        page_start: 628,
        page_end: 721,
        is_range_date: true,
        dates: [
          { year: 1918, month: 10 },
          { year: 1918, month: 11 },
        ],
      },
      {
        title: '论“民主”和专政',
        authors: ['列宁'],
        page_start: 722,
        page_end: 726,
        dates: [{ year: 1918, month: 12, day: 23 }],
      },
      {
        title: '共产国际第一次代表大会（1919年3月2—6日）',
        authors: ['列宁'],
        page_start: 727,
        page_end: 746,
        is_range_date: true,
        dates: [
          { year: 1919, month: 3, day: 2 },
          { year: 1919, month: 3, day: 6 },
        ],
      },
      {
        title: '俄共（布）党纲草案',
        authors: ['列宁'],
        page_start: 747,
        page_end: 783,
        dates: [{ year: 1919 }],
      },
      {
        title: '关于党纲的报告（1919年3月19日在俄共（布）第八次代表大会上）',
        authors: ['列宁'],
        page_start: 784,
        page_end: 803,
        dates: [{ year: 1919, month: 3, day: 19 }],
      },
      {
        title:
          '关于农村工作的报告（1919年3月23日在俄共（布）第八次代表大会上）',
        authors: ['列宁'],
        page_start: 804,
        page_end: 819,
        dates: [{ year: 1919, month: 3, day: 23 }],
      },
      {
        title: '第三国际及其在历史上的地位',
        authors: ['列宁'],
        page_start: 820,
        page_end: 827,
        dates: [{ year: 1919, month: 4, day: 15 }],
      },
      {
        title: '致全俄社会教育第一次代表大会的贺词（1919年5月6日）',
        authors: ['列宁'],
        page_start: 828,
        page_end: 831,
        dates: [{ year: 1919, month: 5, day: 6 }],
      },
      {
        title:
          '关于用自由平等口号欺骗人民（1919年5月19日在全俄社会教育第一次代表大会上的报告）',
        authors: ['列宁'],
        page_start: 832,
        page_end: 867,
        dates: [{ year: 1919, month: 5, day: 19 }],
      },
      {
        title: '向匈牙利工人致敬',
        authors: ['列宁'],
        page_start: 868,
        page_end: 872,
        dates: [{ year: 1919, month: 5, day: 27 }],
      },
      {
        title: '注释',
        authors: ['中共中央马克思恩格斯列宁斯大林著作编辑局'],
        page_start: 873,
        page_end: 933,
        dates: [{ year: 1972, month: 10 }],
      },
      {
        title: '人名索引',
        authors: ['中共中央马克思恩格斯列宁斯大林著作编辑局'],
        page_start: 934,
        page_end: 945,
        dates: [{ year: 1972, month: 10 }],
      },
    ],
    ocr: { content_thresholds: [0.12, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives5/39f5c300-d854-414d-a93f-a0cfd049f55b.pdf',
};
