export default {
  entity: {
    id: '3a8b5436-9c88-4294-bcbe-ba9feddf9d55',
    name: '红旗一九五九年第五期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/3a8b5436-9c88-4294-bcbe-ba9feddf9d55.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '当前基本建设工作中的几个重大问题',
        authors: ['陈云'],
        page_start: 3,
        page_end: 18,
        dates: [{ year: 1959, month: 3 }],
      },
      {
        title: '高速度发展畜牧业',
        authors: ['乌兰夫'],
        page_start: 19,
        page_end: 26,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 3 }],
      },
      {
        title: '广泛地进行“全国一盘棋”的教育',
        authors: ['陶鲁笳'],
        page_start: 27,
        page_end: 31,
        dates: [{ year: 1959, month: 3 }],
      },
      {
        title: '向科学的高峰继续前进',
        authors: ['任会'],
        page_start: 32,
        page_end: 33,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 3 }],
      },
      {
        title: '朝鲜的社会主义建设',
        authors: ['乔晓光'],
        page_start: 34,
        page_end: 39,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 3 }],
      },
      {
        title: '无神论的一次巨大胜利——勐海县格朗和区爱尼族大破鬼神迷信的斗争',
        authors: ['吴玉才'],
        page_start: 40,
        page_end: 44,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 2 }],
      },
      {
        title: '珠江岸边',
        authors: ['陈残云'],
        page_start: 45,
        page_end: 46,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 2 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/3a8b5436-9c88-4294-bcbe-ba9feddf9d55.pdf',
};
