export default {
  entity: {
    id: '3b695585-3549-471c-963e-28c1173ed2b7',
    name: '红旗一九六一年第三、四期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/3b695585-3549-471c-963e-28c1173ed2b7.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中国共产党第八届中央委员会第九次全体会议公报',
        authors: [],
        page_start: 3,
        page_end: 5,
        is_ranged_date: true,
        dates: [
          { year: 1961, month: 1, day: 14 },
          { year: 1961, month: 1, day: 18 },
        ],
      },
      {
        title: '中国共产党八届九中全会关于各国共产党和工人党代表会议的决议',
        authors: [],
        page_start: 6,
        page_end: 8,
        dates: [{ year: 1961, month: 1, day: 18 }],
      },
      {
        title: '大兴调查研究之风 一切从实际出发——纪念《农村调查》出版二十周年',
        authors: ['《红旗》杂志编辑部'],
        page_start: 9,
        page_end: 14,
        dates: [{ year: 1961, month: 2 }],
      },
      {
        title: '《不怕鬼的故事》序',
        authors: ['何其芳'],
        page_start: 15,
        page_end: 20,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 2 }],
      },
      {
        title: '争取我国工业生产建设的新胜利',
        authors: ['薄一波'],
        page_start: 21,
        page_end: 27,
        dates: [{ year: 1961, month: 2 }],
      },
      {
        title: '鼓足干劲，力争丰收',
        authors: ['廖鲁言'],
        page_start: 28,
        page_end: 34,
        dates: [{ year: 1961, month: 2 }],
      },
      {
        title: '一个从铁业生产合作社发展起来的农具修造厂',
        authors: ['陶石'],
        page_start: 35,
        page_end: 39,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 2 }],
      },
      {
        title: '关于旧中国的国家垄断资本主义',
        authors: ['许涤新'],
        page_start: 40,
        page_end: 48,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 2 }],
      },
      {
        title: '发展修理服务业是组织人民经济生活的一个重要内容',
        authors: ['陈扬'],
        page_start: 49,
        page_end: 52,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 2 }],
      },
      {
        title: '京西煤矿生产持续跃进的经验',
        authors: ['王政'],
        page_start: 53,
        page_end: 59,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 2 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/3b695585-3549-471c-963e-28c1173ed2b7.pdf',
};
