export default {
  entity: {
    id: '4146ed54-5d56-4072-acf6-ab8675a35c5b',
    name: '无产阶级文化大革命概述简论（第三篇）（水陆洲2012年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '水陆洲编',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/4146ed54-5d56-4072-acf6-ab8675a35c5b.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '《无产阶级文化大革命概述简论》第三篇概述',
        authors: ['水陆洲'],
        page_start: 5,
        page_end: 72,
        dates: [{ year: 2012, month: 8, day: 17 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第一节 九大以后的新形势新任务',
        authors: ['水陆洲'],
        page_start: 73,
        page_end: 86,
        dates: [{ year: 2011, month: 12, day: 21 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第二节 解决一些省的遗留问题',
        authors: ['水陆洲'],
        page_start: 87,
        page_end: 122,
        dates: [{ year: 2011, month: 12, day: 20 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第三节 清理阶级队伍',
        authors: ['水陆洲'],
        page_start: 123,
        page_end: 148,
        dates: [{ year: 2011, month: 12, day: 27 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第四节 打击反革命破坏活动',
        authors: ['水陆洲'],
        page_start: 149,
        page_end: 159,
        dates: [{ year: 2011, month: 12, day: 27 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第五节 继续清查五·一六',
        authors: ['水陆洲'],
        page_start: 160,
        page_end: 193,
        dates: [{ year: 2011, month: 12, day: 28 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第六节 整党建党',
        authors: ['水陆洲'],
        page_start: 194,
        page_end: 202,
        dates: [{ year: 2011, month: 12, day: 28 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第七节 毕业生分配、上山下乡',
        authors: ['水陆洲'],
        page_start: 203,
        page_end: 216,
        dates: [{ year: 2011, month: 12, day: 29 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第八节 教育卫生文化等领域的革命',
        authors: ['水陆洲'],
        page_start: 217,
        page_end: 240,
        dates: [{ year: 2011, month: 12, day: 29 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第九节 改革旧的规章制度',
        authors: ['水陆洲'],
        page_start: 241,
        page_end: 256,
        dates: [{ year: 2011, month: 12, day: 30 }],
      },
      {
        title: '第二章 九届二中全会上的斗争 第一节 一九七〇年的新形势新任务',
        authors: ['水陆洲'],
        page_start: 257,
        page_end: 284,
        dates: [{ year: 2011, month: 12, day: 31 }],
      },
      {
        title: '第二章 九届二中全会上的斗争 第二节 林彪集团逐渐形成',
        authors: ['水陆洲'],
        page_start: 285,
        page_end: 303,
        dates: [{ year: 2011, month: 3, day: 6 }],
      },
      {
        title: '第二章 九届二中全会上的斗争 第三节 围绕修改宪法的斗争',
        authors: ['水陆洲'],
        page_start: 304,
        page_end: 321,
        dates: [{ year: 2011, month: 12, day: 31 }],
      },
      {
        title: '第二章 九届二中全会上的斗争 第四节 林彪搞突袭 毛泽东反潮流',
        authors: ['水陆洲'],
        page_start: 322,
        page_end: 365,
        dates: [{ year: 2011, month: 12, day: 31 }],
      },
      {
        title: '第三章 开展批陈整风 第一节 一九七一年的新形势新任务',
        authors: ['水陆洲'],
        page_start: 366,
        page_end: 382,
        dates: [{ year: 2012, month: 1, day: 1 }],
      },
      {
        title: '第三章 开展批陈整风 第二节 几员大将的检讨 吴法宪叶群的检讨',
        authors: ['水陆洲'],
        page_start: 383,
        page_end: 396,
        dates: [{ year: 2012, month: 1, day: 1 }],
      },
      {
        title: '第三章 开展批陈整风 第三节 陈伯达反党问题',
        authors: ['水陆洲'],
        page_start: 397,
        page_end: 409,
        dates: [{ year: 2012, month: 3, day: 8 }],
      },
      {
        title: '第三章 开展批陈整风 第四节 召开华北会议',
        authors: ['水陆洲'],
        page_start: 410,
        page_end: 429,
        dates: [{ year: 2012, month: 3, day: 8 }],
      },
      {
        title: '第三章 开展批陈整风 第五节 召开中央批陈整风汇报会议',
        authors: ['水陆洲'],
        page_start: 430,
        page_end: 448,
        dates: [{ year: 2012, month: 3, day: 8 }],
      },
      {
        title: '第四章 林彪集团的反革命政变活动 第一节 制定反革命计划',
        authors: ['水陆洲'],
        page_start: 449,
        page_end: 463,
        dates: [{ year: 2012, month: 4, day: 4 }],
      },
      {
        title: '第四章 林彪集团的反革命政变活动 第二节 实施反革命政变',
        authors: ['水陆洲'],
        page_start: 464,
        page_end: 483,
        dates: [{ year: 2012, month: 4, day: 3 }],
      },
      {
        title: '第五章 毛泽东外地巡视 第一节 毛泽东巡视武昌',
        authors: ['水陆洲'],
        page_start: 484,
        page_end: 495,
        dates: [{ year: 2011, month: 4, day: 24 }],
      },
      {
        title: '第五章 毛泽东外地巡视 第二节 毛泽东巡视长沙',
        authors: ['水陆洲'],
        page_start: 496,
        page_end: 515,
        dates: [{ year: 2012, month: 4 }],
      },
      {
        title: '第五章 毛泽东外地巡视 第三节 毛泽东巡视南昌',
        authors: ['水陆洲'],
        page_start: 516,
        page_end: 521,
        dates: [{ year: 2012, month: 5, day: 2 }],
      },
      {
        title: '第五章 毛泽东外地巡视 第四节 毛泽东巡视杭州',
        authors: ['水陆洲'],
        page_start: 522,
        page_end: 530,
        dates: [{ year: 2012, month: 5, day: 3 }],
      },
      {
        title: '第五章 毛泽东外地巡视 第五节 毛泽东巡视上海',
        authors: ['水陆洲'],
        page_start: 531,
        page_end: 535,
        dates: [{ year: 2012, month: 4, day: 25 }],
      },
      {
        title: '第五章 毛泽东外地巡视 第六节 毛泽东回到北京',
        authors: ['水陆洲'],
        page_start: 536,
        page_end: 539,
        dates: [{ year: 2012, month: 4, day: 25 }],
      },
      {
        title: '第六章 林彪集团的覆灭 第一节 林彪等人叛逃',
        authors: ['水陆洲'],
        page_start: 540,
        page_end: 553,
        dates: [{ year: 2012, month: 4, day: 26 }],
      },
      {
        title: '第六章 林彪集团的覆灭 第二节 揭批林彪集团罪行',
        authors: ['水陆洲'],
        page_start: 554,
        page_end: 568,
        dates: [{ year: 2012, month: 4, day: 27 }],
      },
      {
        title: '第七章 开展外交新局面 第一节 毛泽东决定开展中美谈判',
        authors: ['水陆洲'],
        page_start: 569,
        page_end: 586,
        dates: [{ year: 2012, month: 4, day: 28 }],
      },
      {
        title:
          '第七章 开展外交新局面 第二节 基辛格访华 中国恢复在联合国的合法席位',
        authors: ['水陆洲'],
        page_start: 587,
        page_end: 597,
        dates: [{ year: 2012, month: 4, day: 28 }],
      },
      {
        title: '第七章 开展外交新局面 第三节 尼克松访华',
        authors: ['水陆洲'],
        page_start: 598,
        page_end: 608,
        dates: [{ year: 2012, month: 4, day: 28 }],
      },
      {
        title: '第七章 开展外交新局面 第四节 中日恢复邦交',
        authors: ['水陆洲'],
        page_start: 609,
        page_end: 625,
        dates: [{ year: 2011, month: 3, day: 11 }],
      },
      {
        title: '第八章 批林整风 第一节 一九七二年的新形势新任务',
        authors: ['水陆洲'],
        page_start: 626,
        page_end: 636,
        dates: [{ year: 2012, month: 5, day: 4 }],
      },
      {
        title: '第八章 批林整风 第二节 开展批林整风',
        authors: ['水陆洲'],
        page_start: 637,
        page_end: 702,
        dates: [{ year: 2012, month: 5, day: 4 }],
      },
      {
        title: '第八章 批林整风 第三节 批判极左思潮问题',
        authors: ['水陆洲'],
        page_start: 703,
        page_end: 711,
        dates: [{ year: 2011, month: 5, day: 4 }],
      },
      {
        title: '第八章 批林整风 第四节 江青接受美国学者采访',
        authors: ['水陆洲'],
        page_start: 712,
        page_end: 715,
        dates: [{ year: 2012, month: 3, day: 10 }],
      },
      {
        title: '第九章 召开十大 第一节 一九七三年的新形势新任务',
        authors: ['水陆洲'],
        page_start: 716,
        page_end: 722,
        dates: [{ year: 2011, month: 5, day: 22 }],
      },
      {
        title: '第九章 召开十大 第二节 继续批林整风',
        authors: ['水陆洲'],
        page_start: 723,
        page_end: 736,
        dates: [{ year: 2012, month: 5, day: 4 }],
      },
      {
        title: '第九章 召开十大 第三节 邓小平复出',
        authors: ['水陆洲'],
        page_start: 737,
        page_end: 746,
        dates: [{ year: 2012, month: 5, day: 4 }],
      },
      {
        title: '第九章 召开十大 第四节 继续搞好文艺革命',
        authors: ['水陆洲'],
        page_start: 747,
        page_end: 759,
        dates: [{ year: 2012, month: 5, day: 4 }],
      },
      {
        title: '第九章 召开十大 第五节 批判教育领域的复辟回潮',
        authors: ['水陆洲'],
        page_start: 760,
        page_end: 767,
        dates: [{ year: 2012, month: 5, day: 4 }],
      },
      {
        title: '第九章 召开十大 第六节 中共第十次代表大会召开',
        authors: ['水陆洲'],
        page_start: 768,
        page_end: 783,
        dates: [{ year: 2012, month: 5, day: 4 }],
      },
      {
        title: '第九章 召开十大 第七节 毛泽东批评外交工作',
        authors: ['水陆洲'],
        page_start: 784,
        page_end: 797,
        dates: [{ year: 2012, month: 5, day: 5 }],
      },
      {
        title: '第九章 召开十大 第八节 评法批儒',
        authors: ['水陆洲'],
        page_start: 798,
        page_end: 801,
        dates: [{ year: 2010, month: 1, day: 4 }],
      },
      {
        title: '第九章 召开十大 第九节 八大军区司令员对调',
        authors: ['水陆洲'],
        page_start: 802,
        page_end: 808,
        dates: [{ year: 2010, month: 1, day: 18 }],
      },
      {
        title: '第十章 批林批孔 第一节 新阶段新任务',
        authors: ['水陆洲'],
        page_start: 809,
        page_end: 825,
        dates: [{ year: 2010, month: 1, day: 25 }],
      },
      {
        title: '第十章 批林批孔 第二节 发动批林批孔',
        authors: ['水陆洲'],
        page_start: 826,
        page_end: 858,
        dates: [{ year: 2010, month: 2, day: 1 }],
      },
      {
        title: '第十章 批林批孔 第三节 各地区的批林批孔运动',
        authors: ['水陆洲'],
        page_start: 859,
        page_end: 905,
        dates: [{ year: 2010, month: 2, day: 8 }],
      },
      {
        title: '第十章 批林批孔 第四节 批判各领域的复辟回潮',
        authors: ['水陆洲'],
        page_start: 906,
        page_end: 929,
        dates: [{ year: 2012, month: 5, day: 13 }],
      },
      {
        title: '第十章 批林批孔 第六节 筹备四届人大',
        authors: ['水陆洲'],
        page_start: 930,
        page_end: 950,
        dates: [{ year: 2010, month: 3, day: 1 }],
      },
      {
        title: '第十章 批林批孔 第七节 毛泽东论三个世界',
        authors: ['水陆洲'],
        page_start: 951,
        page_end: 956,
        dates: [{ year: 2010, month: 3, day: 8 }],
      },
    ],
    ocr: {
      standard_paragraph_merge_strategy_threshold: 0.186,
      differential_paragraph_merge_strategy_threshold: 0,
      content_thresholds: [0.054, 0, 0, 0],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/4146ed54-5d56-4072-acf6-ab8675a35c5b.pdf',
};
