export default {
  entity: {
    id: '43e8cc4f-8fd2-4791-a106-8c331d315332',
    name: '红旗一九五八年第七期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/43e8cc4f-8fd2-4791-a106-8c331d315332.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '教育必须与生产劳动相结合',
        authors: ['陆定一'],
        page_start: 3,
        page_end: 14,
        dates: [{ year: 1958 }],
      },
      {
        title: '迎接人民公社化的高潮',
        authors: ['《红旗》杂志编辑部'],
        page_start: 15,
        page_end: 17,
        dates: [{ year: 1958 }],
      },
      {
        title: '嵖岈山卫星人民公社试行简章（草稿）',
        authors: [],
        page_start: 18,
        page_end: 24,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958, month: 8, day: 7 }],
      },
      {
        title: '河南信阳来信',
        authors: ['李友九'],
        page_start: 24,
        page_end: 25,
        dates: [{ year: 1958, month: 8, day: 8 }],
      },
      {
        title: '家务劳动的集体化、社会化',
        authors: ['胡绳'],
        page_start: 26,
        page_end: 32,
        dates: [{ year: 1958 }],
      },
      {
        title: '“巧姑娘”运动',
        authors: ['南彩英'],
        page_start: 32,
        page_end: 34,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958, month: 7, day: 17 }],
      },
      {
        title: '阜阳县实现了沼气化',
        authors: ['中共阜阳县委会'],
        page_start: 35,
        page_end: 37,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958 }],
      },
      {
        title: '贫瘠土地也能丰产',
        authors: ['中共应城县委会'],
        page_start: 38,
        ocr: { vsplit: 0.35 },
        page_end: 40,
        dates: [{ year: 1958 }],
      },
      {
        title: '纸老虎在研究“投降学”',
        authors: ['夏衍'],
        page_start: 41,
        page_end: 43,
        dates: [{ year: 1958 }],
      },
    ],
    ocr: {
      auto_vsplit: false,
      vsplit: 0,
      content_thresholds: [0, 0.185, 0, 0.1],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/43e8cc4f-8fd2-4791-a106-8c331d315332.pdf',
};
