export default {
  entity: {
    id: '440c8819-7c1b-4eaa-981b-2579bd8e1a1a',
    name: '非常与正常——上海“文革”时期的社会生活（下）（上海辞书出版社2011年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '金大陆著，上海辞书出版社2011年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/440c8819-7c1b-4eaa-981b-2579bd8e1a1a.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '第十章 上海“文革”时期的蔬菜生产和供应',
        authors: ['金大陆'],
        page_start: 8,
        page_end: 59,
        tags: [{ name: '上海辞书出版社', type: 'issuer' }],
        dates: [{ year: 2011, month: 4 }],
      },
      {
        title: '第十一章 上海“文革”时期的粮油供应——兼论“国家管理”的“在位”',
        authors: ['金大陆'],
        page_start: 60,
        page_end: 128,
        tags: [{ name: '上海辞书出版社', type: 'issuer' }],
        dates: [{ year: 2011, month: 4 }],
      },
      {
        title:
          '第十二章 关于“票证时代”的集体记忆——以上海“文革”时期的猪肉供应为个案',
        authors: ['金大陆'],
        page_start: 129,
        page_end: 163,
        tags: [{ name: '上海辞书出版社', type: 'issuer' }],
        dates: [{ year: 2011, month: 4 }],
      },
      {
        title: '第十三章 上海“文革”时期的水产品生产和供应',
        authors: ['金大陆'],
        page_start: 164,
        page_end: 182,
        tags: [{ name: '上海辞书出版社', type: 'issuer' }],
        dates: [{ year: 2011, month: 4 }],
      },
      {
        title: '第十四章 像章“问题”',
        authors: ['金大陆'],
        page_start: 183,
        page_end: 204,
        tags: [{ name: '上海辞书出版社', type: 'issuer' }],
        dates: [{ year: 2011, month: 4 }],
      },
      {
        title: '第十五章 上海的几尊毛泽东塑像',
        authors: ['金大陆'],
        page_start: 205,
        page_end: 235,
        tags: [{ name: '上海辞书出版社', type: 'issuer' }],
        dates: [{ year: 2011, month: 4 }],
      },
      {
        title: '第十六章 上海“文革”运动中的“群众报刊”',
        authors: ['金大陆'],
        page_start: 236,
        page_end: 302,
        tags: [{ name: '上海辞书出版社', type: 'issuer' }],
        dates: [{ year: 2011, month: 4 }],
      },
      {
        title: '第十七章 上海“文革”运动中的“宣传品”',
        authors: ['金大陆'],
        page_start: 303,
        page_end: 363,
        tags: [{ name: '上海辞书出版社', type: 'issuer' }],
        dates: [{ year: 2011, month: 4 }],
      },
      {
        title: '第十八章 “深挖洞”——以上海1969年至1978年的人防工程为中心',
        authors: ['金大陆'],
        page_start: 364,
        page_end: 406,
        tags: [{ name: '上海辞书出版社', type: 'issuer' }],
        dates: [{ year: 2011, month: 4 }],
      },
      {
        title: '第十九章 “野营拉练”——以上海1970年至1974年的“野营拉练”为例',
        authors: ['金大陆'],
        page_start: 407,
        page_end: 435,
        tags: [{ name: '上海辞书出版社', type: 'issuer' }],
        dates: [{ year: 2011, month: 4 }],
      },
      {
        title: '第二十章 题旨和结论',
        authors: ['金大陆'],
        page_start: 436,
        page_end: 456,
        tags: [{ name: '上海辞书出版社', type: 'issuer' }],
        dates: [{ year: 2011, month: 4 }],
      },
      {
        title:
          '后记 心心念念——写在《非常与正常——上海“文革”时期的社会生活》交稿后',
        authors: ['金大陆'],
        page_start: 457,
        page_end: 466,
        tags: [{ name: '上海辞书出版社', type: 'issuer' }],
        dates: [{ year: 2011, month: 4 }],
      },
    ],
    ocr: { content_thresholds: [0.1, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/440c8819-7c1b-4eaa-981b-2579bd8e1a1a.pdf',
};
