export default {
  entity: {
    id: '44c9a51f-5aa1-4379-b770-b774e95856c1',
    name: '四清运动实录（浙江人民出版社2005年）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '郭德宏、林小波，浙江人民出版社2005年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/44c9a51f-5aa1-4379-b770-b774e95856c1.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '第一章 起源',
        authors: ['郭德宏', '林小波'],
        page_start: 5,
        page_end: 33,
        dates: [{ year: 2005, month: 1 }],
      },
      {
        title: '第二章 发动和试点',
        authors: ['郭德宏', '林小波'],
        page_start: 34,
        page_end: 83,
        dates: [{ year: 2005, month: 1 }],
      },
      {
        title: '第三章 铺开',
        authors: ['郭德宏', '林小波'],
        page_start: 84,
        page_end: 120,
        dates: [{ year: 2005, month: 1 }],
      },
      {
        title: '第四章 高潮：政策制定',
        authors: ['郭德宏', '林小波'],
        page_start: 121,
        page_end: 159,
        dates: [{ year: 2005, month: 1 }],
      },
      {
        title: '第五章 高潮：夺权样板',
        authors: ['郭德宏', '林小波'],
        page_start: 160,
        page_end: 207,
        dates: [{ year: 2005, month: 1 }],
      },
      {
        title: '第六章 高潮：大兵团作战',
        authors: ['郭德宏', '林小波'],
        page_start: 208,
        page_end: 256,
        dates: [{ year: 2005, month: 1 }],
      },
      {
        title: '第七章 转折',
        authors: ['郭德宏', '林小波'],
        page_start: 257,
        page_end: 327,
        dates: [{ year: 2005, month: 1 }],
      },
      {
        title: '第八章 尾声',
        authors: ['郭德宏', '林小波'],
        page_start: 328,
        page_end: 353,
        dates: [{ year: 2005, month: 1 }],
      },
      {
        title: '附录一 四清运动大事记',
        authors: ['郭德宏', '林小波'],
        page_start: 354,
        page_end: 394,
        dates: [{ year: 2005, month: 1 }],
      },
      {
        title: '附录二 参考书目',
        authors: ['郭德宏', '林小波'],
        page_start: 395,
        page_end: 400,
        dates: [{ year: 2005, month: 1 }],
      },
    ],
    ocr: { content_thresholds: [0.137, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/44c9a51f-5aa1-4379-b770-b774e95856c1.pdf',
};
