export default {
  entity: {
    id: '45f85d41-2767-49bc-87e9-ba331b429fce',
    name: '毛泽东思想万岁（1961年-1968年）',
    internal: true,
    official: false,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/45f85d41-2767-49bc-87e9-ba331b429fce.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '在中央工作会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1961, month: 1, day: 13 }],
        page_start: 14,
        page_end: 16,
      },
      {
        title: '在八届九中全会上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1961, month: 1, day: 18 }],
        page_start: 17,
        page_end: 19,
      },
      {
        title: '《反对本本主义》说明',
        authors: ['毛泽东'],
        dates: [{ year: 1961, month: 3, day: 11 }],
        page_start: 19,
        page_end: 20,
      },
      {
        title:
          '《中央关于认真进行调查研究工作问题给各中央局、省、市、区党委一封信》',
        authors: ['毛泽东'],
        dates: [{ year: 1961, month: 3, day: 27 }],
        page_start: 20,
        page_end: 20,
      },
      {
        title: '在广州会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1961, month: 3, day: null }],
        page_start: 20,
        page_end: 20,
      },
      {
        title: '在接见亚洲、非洲外宾时的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1961, month: 4, day: 28 }],
        page_start: 21,
        page_end: 21,
      },
      {
        title: '在接见古巴文化代表团时的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1961, month: 4, day: 19 }],
        page_start: 21,
        page_end: 21,
      },
      {
        title: '调查成灾一例',
        authors: ['毛泽东'],
        dates: [{ year: 1961, month: 5, day: 30 }],
        page_start: 21,
        page_end: 21,
      },
      {
        title: '在北京会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1961, month: 6, day: 12 }],
        page_start: 22,
        page_end: 23,
      },
      {
        title: '给江西共产主义劳动大学的一封信',
        authors: ['毛泽东'],
        dates: [{ year: 1961, month: 7, day: 30 }],
        page_start: 23,
        page_end: 23,
      },
      {
        title: '对《各地贯彻执行六十条的情况和问题》的批语',
        authors: ['毛泽东'],
        dates: [{ year: 1961, month: 9, day: 6 }],
        page_start: 24,
        page_end: 24,
      },
      {
        title: '给政治局常委及有关同志的信',
        authors: ['毛泽东'],
        dates: [{ year: 1961, month: 9, day: 29 }],
        page_start: 24,
        page_end: 24,
      },
      {
        title: '在接见日本朋友时的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1961, month: 10, day: 7 }],
        page_start: 25,
        page_end: 25,
      },
      {
        title: '关于科学研究十四条的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1962, month: 1, day: null }],
        page_start: 26,
        page_end: 26,
      },
      {
        title: '给郭沫若回信中的几句话',
        authors: ['毛泽东'],
        dates: [{ year: 1962, month: 1, day: null }],
        page_start: 26,
        page_end: 26,
      },
      {
        title: '在扩大的中央工作会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1962, month: 1, day: 31 }],
        page_start: 26,
        page_end: 38,
      },
      {
        title: '接见几内亚政府经济代表团和妇女代表团的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1962, month: 5, day: 3 }],
        page_start: 38,
        page_end: 42,
      },
      {
        title: '在北戴河中央工作会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1962, month: 8, day: 6 }],
        page_start: 42,
        page_end: 43,
      },
      {
        title: '在北戴河中央工作会议中心小组会上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1962, month: 8, day: 9 }],
        page_start: 44,
        page_end: 46,
      },
      {
        title: '对中共中央组织部的批评',
        authors: ['毛泽东'],
        dates: [{ year: 1962, month: 8, day: 12 }],
        page_start: 47,
        page_end: 47,
      },
      {
        title: '在八届十中全会上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1962, month: 9, day: 24 }],
        page_start: 47,
        page_end: 50,
      },
      {
        title: '在八届十中全会上对工业支援农业的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1962, month: 7, day: 24 }],
        page_start: 50,
        page_end: 51,
      },
      {
        title: '关于电台的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1962, month: 10, day: 1 }],
        page_start: 51,
        page_end: 51,
      },
      {
        title: '批评新华社',
        authors: ['毛泽东'],
        dates: [{ year: 1962 }],
        page_start: 51,
        page_end: 51,
      },
      {
        title: '听取中印边境自卫反击战汇报时的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 2, day: null }],
        page_start: 52,
        page_end: 52,
      },
      {
        title: '同苏修大使契尔沃年科的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 2, day: 23 }],
        page_start: 1,
        page_end: 52,
      },
      {
        title:
          '接见阿尔巴尼亚新闻工作者代表团、劳动青年联盟代表团、工会工作代表团和档案工作者代表团的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 5, day: 4 }],
        page_start: 52,
        page_end: 54,
      },
      {
        title: '对四个文件的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 5, day: 8 }],
        page_start: 55,
        page_end: 55,
      },
      {
        title: '对东北和河南两件报告的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 5, day: 8 }],
        page_start: 55,
        page_end: 55,
      },
      {
        title: '在关于四清运动中央工作会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 5, day: null }],
        page_start: 55,
        page_end: 57,
      },
      {
        title: '关于《山西省昔阳县干部参加劳动已形成社会风尚》一文的批语',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 5, day: null }],
        page_start: 57,
        page_end: 58,
      },
      {
        title: '对《浙江省七个关于干部参加劳动的好材料》的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 5, day: 9 }],
        page_start: 58,
        page_end: 59,
      },
      {
        title: '关于农村社会主义教育等问题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 5, day: null }],
        page_start: 59,
        page_end: 64,
      },
      {
        title: '在杭州会议上的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 5, day: null }],
        page_start: 64,
        page_end: 67,
      },
      {
        title: '批示×××在农村蹲点至少五个月',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 6, day: 3 }],
        page_start: 67,
        page_end: 67,
      },
      {
        title: '接见古巴文化、工会、青年代表的谈活',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 7, day: 26 }],
        page_start: 68,
        page_end: 71,
      },
      {
        title: '八连颂',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 8, day: 1 }],
        page_start: 71,
        page_end: 71,
      },
      {
        title:
          '呼吁世界人民联合起来反对美国帝国主义的种族歧视、支持美国黑人反对种族歧视的斗争为声明',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 8, day: 8 }],
        page_start: 72,
        page_end: 73,
      },
      {
        title: '反对美国——吴庭艳集团侵略和居杀越南南方人民的声明',
        authors: ['毛泽东'],
        dates: [{ year: 1962, month: 8, day: 29 }],
        page_start: 73,
        page_end: 74,
      },
      {
        title: '电唁杜波依斯博士浙世',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 8, day: 29 }],
        page_start: 74,
        page_end: 74,
      },
      {
        title: '在中央工作会议上对文学艺术的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 9, day: null }],
        page_start: 74,
        page_end: 74,
      },
      {
        title: '就贺霍查同志五十五岁生日的电报',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 10, day: 15 }],
        page_start: 75,
        page_end: 75,
      },
      {
        title: '接见阿尔巴尼亚总检察长等的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 11, day: 15 }],
        page_start: 75,
        page_end: 78,
      },
      {
        title: '给林彪、荣臻等同志的信',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 11, day: 16 }],
        page_start: 78,
        page_end: 79,
      },
      {
        title:
          '接见古巴诗人、作家和艺术家联合会文学部主任比达、罗德里格斯夫妇的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 11, day: null }],
        page_start: 79,
        page_end: 82,
      },
      {
        title: '对柯庆施同志有关上海曲艺革命化改革总结报告的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1963, day: 12 }],
        page_start: 83,
        page_end: 83,
      },
      {
        title: '关于加强相互学习克服故步自封、骄傲自满的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 12, day: 13 }],
        page_start: 83,
        page_end: 84,
      },
      {
        title: '谦虚——戒骄',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 12, day: 13 }],
        page_start: 84,
        page_end: 88,
      },
      {
        title: '发给林彪同志的信',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 12, day: 14 }],
        page_start: 88,
        page_end: 88,
      },
      {
        title: '论反对官僚主义',
        authors: ['毛泽东'],
        dates: [{ year: 1963 }],
        page_start: 89,
        page_end: 90,
      },
      {
        title: '在聂荣臻同志汇报时的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1963, month: 12, day: null }],
        page_start: 90,
        page_end: 91,
      },
      {
        title: '在中南海元旦联欢会上的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 1, day: 1 }],
        page_start: 92,
        page_end: 92,
      },
      {
        title: '同×××谈人民日报要学习解放军',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 1, day: 8 }],
        page_start: 92,
        page_end: 92,
      },
      {
        title: '慰问恩克鲁玛总统的信',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 1, day: 9 }],
        page_start: 92,
        page_end: 93,
      },
      {
        title:
          '就巴拉马人民反对美帝国主义的爱国斗争对《人民日报》记者发表的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 1, day: 12 }],
        page_start: 93,
        page_end: 93,
      },
      {
        title: '谈报纸革命化问题',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 1, day: null }],
        page_start: 94,
        page_end: 94,
      },
      {
        title: '就最近日本人民反对美帝国主义的爱国正义斗争发表谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, day: 27 }],
        page_start: 94,
        page_end: 95,
      },
      {
        title: '接见阿尔及和亚民族解放阵线代表和法律工作者代表团的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 1, day: 28 }],
        page_start: 95,
        page_end: 99,
      },
      {
        title: '几段插话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 1, day: null }],
        page_start: 99,
        page_end: 101,
      },
      {
        title: '对《人民日报加强学术文章的报告》的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 2, day: 3 }],
        page_start: 101,
        page_end: 101,
      },
      {
        title: '对《中央关于传达石油工业部关于大庆石油会战情况通知》的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 2, day: 5 }],
        page_start: 101,
        page_end: 101,
      },
      {
        title: '接见新西兰共产党总书记威尔科克斯夫妇时的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 2, day: 9 }],
        page_start: 102,
        page_end: 103,
      },
      {
        title: '关于出版三十本马、恩、列、斯著作的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 2, day: 13 }],
        page_start: 104,
        page_end: 104,
      },
      {
        title: '春节谈话记要',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 2, day: 13 }],
        page_start: 104,
        page_end: 109,
      },
      {
        title: '送给李纳的四句话',
        authors: ['毛泽东'],
        dates: [],
        page_start: 109,
        page_end: 109,
      },
      {
        title: '与毛远新同志的谈话记要',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 2, day: null }],
        page_start: 109,
        page_end: 109,
      },
      {
        title: '关于胡藏芸案件的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 2, day: null }],
        page_start: 110,
        page_end: 110,
      },
      {
        title: '关于学校课程和讲授、考试方法问题的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 3, day: 10 }],
        page_start: 110,
        page_end: 110,
      },
      {
        title: '人民日报要搞理论工作',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 3, day: 22 }],
        page_start: 110,
        page_end: 111,
      },
      {
        title: '对新华社的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1964 }],
        page_start: 111,
        page_end: 111,
      },
      {
        title: '给华罗庚的信',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 3, day: 18 }],
        page_start: 111,
        page_end: 111,
      },
      {
        title: '给高×的信',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 3, day: 18 }],
        page_start: 111,
        page_end: 111,
      },
      {
        title: '在邯郸四清工作座谈会上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 3, day: 28 }],
        page_start: 112,
        page_end: 112,
      },
      {
        title: '在一次汇报时的插话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 3, day: null }],
        page_start: 113,
        page_end: 116,
      },
      {
        title: '接见阿尔及利亚文化代表团时的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 4, day: 15 }],
        page_start: 116,
        page_end: 122,
      },
      {
        title: '对人民日报理论工作的批评',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 4, day: null }],
        page_start: 122,
        page_end: 122,
      },
      {
        title: '关于胡藏芸案件的指示和批示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 4, day: null }],
        page_start: 122,
        page_end: 122,
      },
      {
        title: '在谢富治同志汇报劳改工作时的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 4, day: 28 }],
        page_start: 123,
        page_end: 123,
      },
      {
        title: '对共青团九大的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1964 }],
        page_start: 124,
        page_end: 124,
      },
      {
        title: '在计委领导小组汇报第三个五年计划时的一些插话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 5, day: 11 }],
        page_start: 124,
        page_end: 124,
      },
      {
        title: '接见阿尔巴尼亚妇女代表团和电影工作者的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 5, day: 15 }],
        page_start: 125,
        page_end: 128,
      },
      {
        title: '在四个付总理汇报时的插话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 5, day: null }],
        page_start: 128,
        page_end: 128,
      },
      {
        title: '关于第二个五年计划在中央工作会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 6, day: 6 }],
        page_start: 128,
        page_end: 130,
      },
      {
        title: '和×××的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 6, day: 8 }],
        page_start: 130,
        page_end: 131,
      },
      {
        title: '和×××的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 6, day: 16 }],
        page_start: 131,
        page_end: 131,
      },
      {
        title: '关于军事工作落实与培养革命接班人的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 6, day: 16 }],
        page_start: 132,
        page_end: 133,
      },
      {
        title: '对人民日报文艺宣传的批评',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 6, day: null }],
        page_start: 134,
        page_end: 134,
      },
      {
        title: '接见桑给巴尔专家米·姆·阿里夫妇的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 6, day: 18 }],
        page_start: 134,
        page_end: 140,
      },
      {
        title: '接见智利新闻工作者代表团的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 6, day: 23 }],
        page_start: 141,
        page_end: 145,
      },
      {
        title: '接见外宾关于保健工作的一段谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 6, day: 24 }],
        page_start: 146,
        page_end: 146,
      },
      {
        title: '和王海蓉同志的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 6, day: 24 }],
        page_start: 146,
        page_end: 149,
      },
      {
        title: '对全国文联和所属各协会整风的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 6, day: 27 }],
        page_start: 149,
        page_end: 149,
      },
      {
        title: '畅游十三陵水库时对青年的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 6, day: null }],
        page_start: 149,
        page_end: 150,
      },
      {
        title: '在小型会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1964 }],
        page_start: 150,
        page_end: 150,
      },
      {
        title: '在中央工作会议小型会议上的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1964 }],
        page_start: 150,
        page_end: 150,
      },
      {
        title: '关于部队开展游泳活动的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 7, day: 2 }],
        page_start: 150,
        page_end: 150,
      },
      {
        title: '对一渡河支部提拔新生力量报导的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 7, day: 4 }],
        page_start: 151,
        page_end: 151,
      },
      {
        title: '接见日本社会党人士佐佐木更三、黑田寿男、细迫兼光等的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 7, day: 10 }],
        page_start: 151,
        page_end: 157,
      },
      {
        title: '无产阶级专政的历史教训',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 7, day: 14 }],
        page_start: 157,
        page_end: 159,
      },
      {
        title: '对王东兴同志报告的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 7, day: null }],
        page_start: 159,
        page_end: 160,
      },
      {
        title: '观看北京京剧一团演出的革命现代京剧《沙家滨》后的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 7, day: null }],
        page_start: 160,
        page_end: 160,
      },
      {
        title: '关于部队学习游泳的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 8, day: 6 }],
        page_start: 160,
        page_end: 160,
      },
      {
        title: '对卫生部党组关于高级干部保健工作报告的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 8, day: null }],
        page_start: 160,
        page_end: 160,
      },
      {
        title:
          '对《中央宣传部关于公开放映和批判〈北国江南〉、〈早春2月〉的请示报告》的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 8, day: null }],
        page_start: 160,
        page_end: 160,
      },
      {
        title: '关于哲学问题的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 8, day: 18 }],
        page_start: 161,
        page_end: 167,
      },
      {
        title: '同李雪案等同志的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 8, day: 20 }],
        page_start: 167,
        page_end: 167,
      },
      {
        title: '接见出席第十届禁止原子弹氢弹世界大会后访华外宾的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 8, day: 22 }],
        page_start: 168,
        page_end: 171,
      },
      {
        title: '关于坂田文章的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 8, day: 24 }],
        page_start: 171,
        page_end: 174,
      },
      {
        title: '同毛远新同志的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 8, day: null }],
        page_start: 174,
        page_end: 176,
      },
      {
        title: '接见非洲和拉丁美洲青年学生代表团时的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 8, day: 25 }],
        page_start: 177,
        page_end: 182,
      },
      {
        title: '接见尼泊尔教育代表团时的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 8, day: 29 }],
        page_start: 182,
        page_end: 187,
      },
      {
        title: '关于团结方法的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 8, day: null }],
        page_start: 187,
        page_end: 188,
      },
      {
        title: '在×××反修报告会上的插话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 9, day: 4 }],
        page_start: 188,
        page_end: 189,
      },
      {
        title: '接见老挝爱国战线党文工团团长、副团长和主要成员时的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 9, day: 4 }],
        page_start: 189,
        page_end: 193,
      },
      {
        title: '接见法国技术展览会负责人及法国驻华大使的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 9, day: 10 }],
        page_start: 194,
        page_end: 194,
      },
      {
        title: '与计划领导小组的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 9, day: 12 }],
        page_start: 194,
        page_end: 194,
      },
      {
        title: '接见阿尔及利亚政府经济代表团时的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 9, day: 20 }],
        page_start: 194,
        page_end: 199,
      },
      {
        title: '对《中央音乐学院的意见》的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 9, day: 27 }],
        page_start: 199,
        page_end: 199,
      },
      {
        title: '观看革命现代芭蕾舞剧《红色娘子军》后的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 10, day: 8 }],
        page_start: 199,
        page_end: 199,
      },
      {
        title: '接见西南非妇女代表团的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 10, day: null }],
        page_start: 199,
        page_end: 200,
      },
      {
        title: '会见古巴党政代表团的谈记录',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 10, day: 16 }],
        page_start: 200,
        page_end: 200,
      },
      {
        title: '关于总结经验的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 12, day: null }],
        page_start: 200,
        page_end: 200,
      },
      {
        title: '对《关于×××、×××、××x问题》的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 12, day: 12 }],
        page_start: 200,
        page_end: 200,
      },
      {
        title: '在中央工作会议上的插话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 12, day: 15 }],
        page_start: 201,
        page_end: 201,
      },
      {
        title: '对高扬文同志的蹲点报告的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 12, day: 19 }],
        page_start: 202,
        page_end: 202,
      },
      {
        title: '在中央工作座谈会上关于四清问题的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 12, day: 20 }],
        page_start: 202,
        page_end: 211,
      },
      {
        title: '人民日报现在有看头了',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 12, day: 20 }],
        page_start: 211,
        page_end: 211,
      },
      {
        title: '在中央工作会议上的插话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 12, day: 27 }],
        page_start: 212,
        page_end: 212,
      },
      {
        title: '在中央工作会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 12, day: 28 }],
        page_start: 212,
        page_end: 214,
      },
      {
        title: '同江西省委同志谈记录',
        authors: ['毛泽东'],
        dates: [{ year: 1964 }],
        page_start: 214,
        page_end: 214,
      },
      {
        title: '中国的大跃进',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 12, day: null }],
        page_start: 215,
        page_end: 215,
      },
      {
        title: '社会主义社会阶级斗争并没有熄灭',
        authors: ['毛泽东'],
        dates: [{ year: 1964 }],
        page_start: 215,
        page_end: 215,
      },
      {
        title: '同参加“亚非文学交流座谈会”的亚非作家的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1964, month: 12, day: 25 }],
        page_start: 216,
        page_end: 217,
      },
      {
        title: '关于划分阶级问题的指示',
        authors: ['毛泽东'],
        dates: [],
        page_start: 217,
        page_end: 217,
      },
      {
        title: '关于依靠贫下中农的问题',
        authors: ['毛泽东'],
        dates: [],
        page_start: 218,
        page_end: 1,
      },
      {
        title: '《前十条》和《六十条》为什么能调动人的力量',
        authors: ['毛泽东'],
        dates: [{ year: 1964 }],
        page_start: 218,
        page_end: 218,
      },
      {
        title: '跨点问题',
        authors: ['毛泽东'],
        dates: [{ year: 1964 }],
        page_start: 219,
        page_end: 219,
      },
      {
        title: '论实事求是',
        authors: ['毛泽东'],
        dates: [],
        page_start: 219,
        page_end: 219,
      },
      {
        title: '小资产阶级的通病',
        authors: ['毛泽东'],
        dates: [],
        page_start: 220,
        page_end: 221,
      },
      {
        title: '《关于学习解放军加强政治工作的指示》的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1964 }],
        page_start: 221,
        page_end: 221,
      },
      {
        title: '关于四清运动的一次讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 1, day: 3 }],
        page_start: 222,
        page_end: 225,
      },
      {
        title: '和美国记者斯诺的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 1, day: 9 }],
        page_start: 225,
        page_end: 238,
      },
      {
        title: '对徐××同志《关于如何打乒乓球》一文的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 1, day: 12 }],
        page_start: 239,
        page_end: 239,
      },
      {
        title: '中央《关于学习周恩来同志政府工作报告的通知》',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 1, day: 14 }],
        page_start: 239,
        page_end: 239,
      },
      {
        title: '接见苏班德里约的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 1, day: 27 }],
        page_start: 239,
        page_end: 240,
      },
      {
        title: '对《陈×××同志跨点报告》的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 1, day: 29 }],
        page_start: 240,
        page_end: 240,
      },
      {
        title: '听取谷牧、余秋里汇报计划工作时的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 1, day: null }],
        page_start: 240,
        page_end: 241,
      },
      {
        title: '听取××汇报工业交通会议情况时的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 2, day: 11 }],
        page_start: 241,
        page_end: 241,
      },
      {
        title: '听取×x同志汇报会上的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 2, day: 21 }],
        page_start: 241,
        page_end: 241,
      },
      {
        title:
          '接见海军干部工作会议、《解放军报》绵辑记者会议和第三批战士演出队时的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 2, day: 22 }],
        page_start: 241,
        page_end: 241,
      },
      {
        title: '正面教员与反面教员',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 2, day: null }],
        page_start: 242,
        page_end: 242,
      },
      {
        title: '接见巴勒斯坦解放组织代表团时的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 3, day: null }],
        page_start: 242,
        page_end: 242,
      },
      {
        title: '接见中南局第九次全体会议同志时的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 4, day: 21 }],
        page_start: 243,
        page_end: 243,
      },
      {
        title: '关于劳改工作的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 4, day: null }],
        page_start: 243,
        page_end: 243,
      },
      {
        title: '对卫生工作的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 6, day: 26 }],
        page_start: 243,
        page_end: 244,
      },
      {
        title: '对北京师范学院调查材料的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 7, day: 3 }],
        page_start: 244,
        page_end: 244,
      },
      {
        title: '对军队文工团到农村、工厂去锻炼的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 7, day: 15 }],
        page_start: 244,
        page_end: 244,
      },
      {
        title: '关于模特儿问题的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 7, day: 18 }],
        page_start: 244,
        page_end: 245,
      },
      {
        title: '给章士钊的信',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 7, day: 18 }],
        page_start: 245,
        page_end: 245,
      },
      {
        title: '对医务人员的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 7, day: 19 }],
        page_start: 245,
        page_end: 246,
      },
      {
        title: '在全国工交系统四清工作座谈会上的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 7, day: 20 }],
        page_start: 246,
        page_end: 246,
      },
      {
        title: '给华罗庚的信',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 7, day: 21 }],
        page_start: 246,
        page_end: 246,
      },
      {
        title: '接见李宗仁先生及其夫人的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 7, day: 27 }],
        page_start: 246,
        page_end: 247,
      },
      {
        title: '在线××、张×汇报卫生工作时的插话',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 8, day: 2 }],
        page_start: 247,
        page_end: 249,
      },
      {
        title: '接见法国务部长马尔罗时的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 8, day: 3 }],
        page_start: 249,
        page_end: 252,
      },
      {
        title: '接见几内亚教育代表团、总检察长时的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 8, day: 8 }],
        page_start: 253,
        page_end: 255,
      },
      {
        title: '关于民族工作的一次指示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 9, day: null }],
        page_start: 255,
        page_end: 255,
      },
      {
        title: '同黑非洲留法学生联合代表团的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 9, day: 14 }],
        page_start: 255,
        page_end: 255,
      },
      {
        title: '接见阿尔巴尼亚内务部代表团时谈劳改工作',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 9, day: 18 }],
        page_start: 255,
        page_end: 256,
      },
      {
        title: '关于大学文科改政革的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 10, day: null }],
        page_start: 256,
        page_end: 256,
      },
      {
        title: '路过济南在火车上听取汇报时的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 11, day: null }],
        page_start: 256,
        page_end: 256,
      },
      {
        title: '在听取×××同志汇报时的插话',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 11, day: null }],
        page_start: 257,
        page_end: 257,
      },
      {
        title: '批判罗瑞卿',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 12, day: 2 }],
        page_start: 257,
        page_end: 257,
      },
      {
        title: '反对折衷主义',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 12, day: 2 }],
        page_start: 257,
        page_end: 259,
      },
      {
        title: '在杭州会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 12, day: 21 }],
        page_start: 259,
        page_end: 262,
      },
      {
        title: '在杭州与陈伯达、艾思奇同志的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 12, day: 21 }],
        page_start: 262,
        page_end: 262,
      },
      {
        title: '对林彪同志一封来信的批语',
        authors: ['毛泽东'],
        dates: [{ year: 1965, month: 12, day: 2 }],
        page_start: 262,
        page_end: 262,
      },
      {
        title: '对机要保密工作的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1965 }],
        page_start: 263,
        page_end: 263,
      },
      {
        title: '关于礼宾工作的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1965 }],
        page_start: 263,
        page_end: 264,
      },
      {
        title: '关于《海瑞罢官》',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 2, day: 8 }],
        page_start: 265,
        page_end: 265,
      },
      {
        title: '同毛远新同志的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 2, day: 18 }],
        page_start: 265,
        page_end: 265,
      },
      {
        title: '关于农业机械化问题与备战备荒为人民的指示信',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 2, day: 19 }],
        page_start: 266,
        page_end: 266,
      },
      {
        title: '关于农业机械化问题与备战备荒为人民的指示信',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 3, day: 12 }],
        page_start: 266,
        page_end: 267,
      },
      {
        title:
          '在修改《林彪同志委托江青同志召开的部队文艺工作座谈会纪要》时所加的话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 3, day: null }],
        page_start: 267,
        page_end: 267,
      },
      {
        title: '看了“人工喉”、“断手再植”、“止血粉”将文章后对医务工作者的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 3, day: 12 }],
        page_start: 267,
        page_end: 267,
      },
      {
        title: '在政治局扩大会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 3, day: 20 }],
        page_start: 268,
        page_end: 270,
      },
      {
        title: '在中央政治局常委扩大会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 3, day: null }],
        page_start: 270,
        page_end: 271,
      },
      {
        title: '与康生等同志谈话纪要',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 3, day: null }],
        page_start: 271,
        page_end: 271,
      },
      {
        title: '在政治局扩大会议期间的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 4, day: 16 }],
        page_start: 271,
        page_end: 271,
      },
      {
        title: '在中央政治局常委扩大会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 4, day: 22 }],
        page_start: 271,
        page_end: 271,
      },
      {
        title: '批判彭真',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 4, day: null }],
        page_start: 272,
        page_end: 272,
      },
      {
        title: '给林彪同志的信',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 5, day: 7 }],
        page_start: 272,
        page_end: 273,
      },
      {
        title: '为中共中央“五·一六”通知所加的几段',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 5, day: 16 }],
        page_start: 273,
        page_end: 274,
      },
      {
        title: '关于发表全国第一张马列主义大字报的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 6, day: 1 }],
        page_start: 274,
        page_end: 274,
      },
      {
        title: '在接见日本、古巴、巴西和阿根廷朋友时的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 7, day: 10 }],
        page_start: 274,
        page_end: 274,
      },
      {
        title: '关于北大“六·一八”事件',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 7, day: null }],
        page_start: 275,
        page_end: 275,
      },
      {
        title: '畅游长江时对青年的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 7, day: 17 }],
        page_start: 275,
        page_end: 275,
      },
      {
        title: '重要讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 7, day: 21 }],
        page_start: 275,
        page_end: 276,
      },
      {
        title: '在会见大区书记和中央文革小组成员的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 7, day: 22 }],
        page_start: 276,
        page_end: 277,
      },
      {
        title: '对中央首长的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 7, day: null }],
        page_start: 277,
        page_end: 278,
      },
      {
        title: '对共青团中央的批评',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 7, day: null }],
        page_start: 278,
        page_end: 278,
      },
      {
        title: '关于打人问题',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 8, day: 1 }],
        page_start: 278,
        page_end: 278,
      },
      {
        title: '给清华附中红卫兵小将的一封信',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 8, day: 1 }],
        page_start: 279,
        page_end: 279,
      },
      {
        title: '在中央常委扩大会议上的插话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 8, day: 4 }],
        page_start: 279,
        page_end: 280,
      },
      {
        title: '炮打司令部——我的一张大字报',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 8, day: 5 }],
        page_start: 280,
        page_end: 280,
      },
      {
        title: '在修改《欢呼北大的一张大字报》一文时加的一段',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 8, day: 5 }],
        page_start: 280,
        page_end: 280,
      },
      {
        title: '在中共中央群众接待站传讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 8, day: 10 }],
        page_start: 280,
        page_end: 280,
      },
      {
        title: '对杨寅田大字报的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 8, day: null }],
        page_start: 280,
        page_end: 280,
      },
      {
        title: '在八届十一中全会闭幕式上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 8, day: 12 }],
        page_start: 281,
        page_end: 281,
      },
      {
        title: '在第一次接见红卫兵大会上与林彪同志的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 8, day: 18 }],
        page_start: 281,
        page_end: 281,
      },
      {
        title: '在天安门城楼上与北大附中×××谈话纪要',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 8, day: 18 }],
        page_start: 281,
        page_end: 282,
      },
      {
        title: '在中央工作会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 8, day: 23 }],
        page_start: 282,
        page_end: 282,
      },
      {
        title: '关于北航《红旗战斗队》在国防科委坚持斗争问题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 8, day: null }],
        page_start: 282,
        page_end: 282,
      },
      {
        title: '关于工作组',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 8, day: null }],
        page_start: 282,
        page_end: 282,
      },
      {
        title: '对四位外国专家的大字报的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 8, day: 29 }],
        page_start: 283,
        page_end: 283,
      },
      {
        title: '对《关于长沙、青岛、西安等地情况报告》的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 9, day: 7 }],
        page_start: 283,
        page_end: 283,
      },
      {
        title: '对署名“奥地利《红旗》派的同志”来信：批示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 9, day: 9 }],
        page_start: 283,
        page_end: 283,
      },
      {
        title: '“奥地利《红旗》派的同志”的来信(1966年8月30日)',
        authors: ['毛泽东'],
        dates: [],
        page_start: 284,
        page_end: 284,
      },
      {
        title: '关于中央文革',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 9, day: null }],
        page_start: 284,
        page_end: 284,
      },
      {
        title: '就左派队伍问题与张春桥、姚文元同志的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 10, day: 1 }],
        page_start: 284,
        page_end: 284,
      },
      {
        title: '接见在京部队时的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 10, day: 13 }],
        page_start: 285,
        page_end: 285,
      },
      {
        title: '关于组织外地来京革命师生进行政治军事训练的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 10, day: null }],
        page_start: 285,
        page_end: 285,
      },
      {
        title: '对陈伯达同志《两个月来运动的总结》的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 10, day: 14 }],
        page_start: 285,
        page_end: 285,
      },
      {
        title: '在中央政治局汇报会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 10, day: 24 }],
        page_start: 285,
        page_end: 287,
      },
      {
        title: '在中央工作会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 10, day: 25 }],
        page_start: 287,
        page_end: 288,
      },
      {
        title: '在中央工作会议期间与各大区同志的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 10, day: null }],
        page_start: 289,
        page_end: 289,
      },
      {
        title: '致阿尔巴尼亚劳动党第五次代表大会的贺电',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 10, day: 25 }],
        page_start: 289,
        page_end: 290,
      },
      {
        title: '在中央政治局工作汇报会汉上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 10, day: null }],
        page_start: 290,
        page_end: 290,
      },
      {
        title: '在聂荣臻同志去指挥发射导弹时的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 10, day: 27 }],
        page_start: 290,
        page_end: 290,
      },
      {
        title: '在第七次接见红卫兵大会上与中央负责同志的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 11, day: 10 }],
        page_start: 291,
        page_end: 291,
      },
      {
        title: '要支持群众的革命串连',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 11, day: null }],
        page_start: 291,
        page_end: 291,
      },
      {
        title: '祝贺阿尔巴尼亚解放二十二周年的电报',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 11, day: 28 }],
        page_start: 291,
        page_end: 292,
      },
      {
        title: '在文化大革命中学会大民主',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 12, day: null }],
        page_start: 292,
        page_end: 292,
      },
      {
        title: '关于复员转业军人参加文化大革命问题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 12, day: null }],
        page_start: 292,
        page_end: 292,
      },
      {
        title: '关于军政训练的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 12, day: null }],
        page_start: 292,
        page_end: 292,
      },
      {
        title: '在中央常委扩大会上的四点指示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 12, day: null }],
        page_start: 292,
        page_end: 293,
      },
      {
        title: '讨论“工矿十条”时的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 12, day: null }],
        page_start: 293,
        page_end: 293,
      },
      {
        title: '赞扬参加接待红卫兵和革命师生的解放军指战员的工作',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 12, day: null }],
        page_start: 293,
        page_end: 293,
      },
      {
        title: '给周总理的亲笔信',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 12, day: 27 }],
        page_start: 293,
        page_end: 293,
      },
      {
        title: '对《林彪同志给浙江省军区的指示》的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1966, month: 12, day: 29 }],
        page_start: 294,
        page_end: 294,
      },
      {
        title: '林彪同志给浙江省军区的指示',
        authors: ['毛泽东'],
        dates: [],
        page_start: 294,
        page_end: 294,
      },
      {
        title: '和林彪同志的一段谈话',
        authors: ['毛泽东'],
        dates: [],
        page_start: 294,
        page_end: 294,
      },
      {
        title: '关于一九六七年文化大革命的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 1, day: 1 }],
        page_start: 295,
        page_end: 295,
      },
      {
        title: '关于陶铸问题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 1, day: null }],
        page_start: 295,
        page_end: 295,
      },
      {
        title: '对中央文革小组的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 1, day: 9 }],
        page_start: 295,
        page_end: 296,
      },
      {
        title: '与外宾谈如何看大字报',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 1, day: null }],
        page_start: 296,
        page_end: 296,
      },
      {
        title: '关于接管的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 1, day: null }],
        page_start: 296,
        page_end: 296,
      },
      {
        title: '谈机关文化大革命的重要性',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 1, day: 9 }],
        page_start: 297,
        page_end: 297,
      },
      {
        title: '关于军队支持左派的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 1, day: 21 }],
        page_start: 297,
        page_end: 297,
      },
      {
        title: '谈无产阶级文化大革命新阶段',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 1, day: 23 }],
        page_start: 297,
        page_end: 297,
      },
      {
        title: '在军委扩大会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, day: 27 }],
        page_start: 298,
        page_end: 298,
      },
      {
        title: '关于军队文化大革命的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 1, day: null }],
        page_start: 298,
        page_end: 298,
      },
      {
        title: '关于外国朋友参加文化大革命的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 1, day: 28 }],
        page_start: 298,
        page_end: 298,
      },
      {
        title: '与周总理谈夺权问题',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 1, day: null }],
        page_start: 299,
        page_end: 299,
      },
      {
        title: '关于夺权问题',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 1, day: null }],
        page_start: 299,
        page_end: 299,
      },
      {
        title:
          '为《红旗》杂志1967年第三期社论《论无产阶级革命派的夺权斗争》所加的一段',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 1, day: null }],
        page_start: 300,
        page_end: 300,
      },
      {
        title: '对广播系统夺权的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 1, day: 23 }],
        page_start: 300,
        page_end: 300,
      },
      {
        title: '谈文明斗争',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 2, day: 3 }],
        page_start: 300,
        page_end: 300,
      },
      {
        title: '和卡博、巴卢库同志的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 2, day: 3 }],
        page_start: 301,
        page_end: 302,
      },
      {
        title: '关于西安问题的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 2, day: 4 }],
        page_start: 303,
        page_end: 303,
      },
      {
        title: '接见张春桥、姚文元同志对上海文化大革命的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 2, day: null }],
        page_start: 303,
        page_end: 305,
      },
      {
        title: '关于宗派主义问题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 2, day: null }],
        page_start: 305,
        page_end: 305,
      },
      {
        title: '给中国人民解放军北京卫成区2月18日写的两个报告的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 2, day: 19 }],
        page_start: 306,
        page_end: 306,
      },
      {
        title: '要理头工作，善于思考',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 2, day: 306 }],
        page_start: 1,
        page_end: 306,
      },
      {
        title: '为中央《给全国农村人民公社贫下中农和各级干部的信》加的一段',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 2, day: 20 }],
        page_start: 306,
        page_end: 306,
      },
      {
        title: '对北京两所中学军训材料的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 2, day: null }],
        page_start: 307,
        page_end: 307,
      },
      {
        title: '对《郑州日报》问题的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 2, day: null }],
        page_start: 307,
        page_end: 307,
      },
      {
        title: '在《论革命的“三结合”》一文中所写的两段',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 3, day: null }],
        page_start: 307,
        page_end: 308,
      },
      {
        title: '关于军队要协同地方管工业约指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 3, day: 3 }],
        page_start: 308,
        page_end: 308,
      },
      {
        title: '两条路线斗争的基本问题',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 3, day: null }],
        page_start: 308,
        page_end: 308,
      },
      {
        title: '对铁道兵党委一个报告（渡口驻军支左经验）的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 3, day: 7 }],
        page_start: 308,
        page_end: 308,
      },
      {
        title:
          '对《天津延安中学以教学班为基础实现全校大联合和整顿巩固发展红卫兵的体会》一文件的批语',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 3, day: 7 }],
        page_start: 308,
        page_end: 309,
      },
      {
        title: '在胜利中不要冲昏头脑',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 3, day: null }],
        page_start: 309,
        page_end: 309,
      },
      {
        title: '关于《毛泽东选集》注释等问题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967 }, { year: 8, month: 8, day: null }],
        page_start: 309,
        page_end: 309,
      },
      {
        title: '对中共中央印发薄一波、刘澜涛、杨献珍等人自首叛变材料的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 3, day: 16 }],
        page_start: 309,
        page_end: 310,
      },
      {
        title: '对林彪同志3月20日报告的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 3, day: 20 }],
        page_start: 310,
        page_end: 310,
      },
      {
        title: '对齐齐哈尔铁路局机务段报告的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 3, day: 20 }],
        page_start: 310,
        page_end: 310,
      },
      {
        title: '对报纸工作的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 3, day: null }],
        page_start: 310,
        page_end: 310,
      },
      {
        title: '关于党组织的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 3, day: null }],
        page_start: 311,
        page_end: 311,
      },
      {
        title:
          '对《红旗》杂志调查员报告《“打击一大片，保护一小摄”是资产阶级反动路线一个组成部分》文的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 3, day: 29 }],
        page_start: 311,
        page_end: 311,
      },
      {
        title: '关于大批制的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 3, day: null }],
        page_start: 311,
        page_end: 311,
      },
      {
        title: '关于宜宾问题的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 4, day: null }],
        page_start: 311,
        page_end: 311,
      },
      {
        title: '对《爱国主义还是卖国主义？》一文所加的一段',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 4, day: null }],
        page_start: 312,
        page_end: 312,
      },
      {
        title: '关于部队支左的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 4, day: null }],
        page_start: 312,
        page_end: 312,
      },
      {
        title: '关于四川文化大革命的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 4, day: null }],
        page_start: 312,
        page_end: 312,
      },
      {
        title: '关于批判黑《修养》',
        authors: ['毛泽东'],
        dates: [{ year: 1967 }, { year: 4, month: 4, day: null }],
        page_start: 313,
        page_end: 313,
      },
      {
        title: '不能放弃对党内最大走资本主义道路当权派的斗争',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 4, day: null }],
        page_start: 313,
        page_end: 314,
      },
      {
        title: '关于《触詟说赵太后》',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 4, day: null }],
        page_start: 314,
        page_end: 314,
      },
      {
        title: '《触詟说赵太后》',
        authors: ['毛泽东'],
        dates: [],
        page_start: 314,
        page_end: 314,
      },
      {
        title: '与×同志的一段对话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 4, day: null }],
        page_start: 315,
        page_end: 315,
      },
      {
        title: '关于军管问题',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 4, day: null }],
        page_start: 315,
        page_end: 315,
      },
      {
        title: '关于革命派的大联合',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 4, day: null }],
        page_start: 315,
        page_end: 315,
      },
      {
        title: '接见谢富治同志时的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 4, day: 19 }],
        page_start: 315,
        page_end: 315,
      },
      {
        title: '无政府主义是对机会主义的惩罚',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 4, day: null }],
        page_start: 315,
        page_end: 315,
      },
      {
        title: '关于陕西驻军虚心听取群众意见改进工作报告的批示和批注',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 4, day: 23 }],
        page_start: 316,
        page_end: 316,
      },
      {
        title: '陕西驻军负责同志虚心听取群众意见、改进工作',
        authors: ['毛泽东'],
        dates: [],
        page_start: 316,
        page_end: 316,
      },
      {
        title: '关于四川问题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 4, day: 23 }],
        page_start: 317,
        page_end: 317,
      },
      {
        title: '在中央常委、中央文革小组和政治局会议上的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1967 }, { year: 5, month: 5, day: null }],
        page_start: 317,
        page_end: 318,
      },
      {
        title: '“五一”节对阿尔巴尼亚贵宾的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: 1 }],
        page_start: 318,
        page_end: 318,
      },
      {
        title: '“五一”节对中央首长的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: 1 }],
        page_start: 318,
        page_end: 318,
      },
      {
        title: '“五一”节和张×的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: 1 }],
        page_start: 319,
        page_end: 319,
      },
      {
        title: '对棉粮工作的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: 1 }],
        page_start: 319,
        page_end: 319,
      },
      {
        title: '关于大批制问题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: 2 }],
        page_start: 319,
        page_end: 320,
      },
      {
        title: '关于军队整训的指示——给林彪同志的信',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: 7 }],
        page_start: 320,
        page_end: 320,
      },
      {
        title: '对广州、湖南军区报告的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1967 }],
        page_start: 320,
        page_end: 321,
      },
      {
        title:
          '对《红旗》杂志、《人民日报》两编辑部一九六七年五月八日文章《〈修养〉的要害是背叛无产阶级专政》一文所加的两段',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: 7 }],
        page_start: 321,
        page_end: 321,
      },
      {
        title: '要破除资产阶级法权思想',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: null }],
        page_start: 321,
        page_end: 321,
      },
      {
        title: '对北京市革命委员会的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: null }],
        page_start: 322,
        page_end: 322,
      },
      {
        title: '千革命要有阶级感情',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: null }],
        page_start: 322,
        page_end: 322,
      },
      {
        title: '对上海市革命造反派的号召',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: null }],
        page_start: 322,
        page_end: 322,
      },
      {
        title: '对上海市革命委会的号召',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: null }],
        page_start: 322,
        page_end: 323,
      },
      {
        title: '关于国际形势的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: null }],
        page_start: 323,
        page_end: 323,
      },
      {
        title: '关于处理军民关系的几点指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: null }],
        page_start: 323,
        page_end: 323,
      },
      {
        title: '在《伟大的历史文件》一文中所写的一段',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: 18 }],
        page_start: 324,
        page_end: 324,
      },
      {
        title: '接见阿尔巴尼亚军事代表团时的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 5, day: null }],
        page_start: 324,
        page_end: 326,
      },
      {
        title: '在文化革命中立新功',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 6, day: null }],
        page_start: 327,
        page_end: 327,
      },
      {
        title: '关于夏收的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 6, day: 3 }],
        page_start: 327,
        page_end: 327,
      },
      {
        title: '关于中央各部运动的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 6, day: null }],
        page_start: 327,
        page_end: 327,
      },
      {
        title: '中国革命的伟大世界意义',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 6, day: null }],
        page_start: 327,
        page_end: 327,
      },
      {
        title: '关于干部问题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 6, day: null }],
        page_start: 328,
        page_end: 328,
      },
      {
        title: '有了错误就改',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 6, day: null }],
        page_start: 328,
        page_end: 328,
      },
      {
        title: '关于叛徒问题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 6, day: null }],
        page_start: 328,
        page_end: 328,
      },
      {
        title: '关于对外宣传的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 6, day: 18 }],
        page_start: 328,
        page_end: 328,
      },
      {
        title: '对中央警卫团支左部队的三点指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 6, day: 26 }],
        page_start: 329,
        page_end: 329,
      },
      {
        title: '对赞比亚总统的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 6, day: null }],
        page_start: 329,
        page_end: 329,
      },
      {
        title: '修改中国红卫兵代表团去阿尔巴尼亚的发言稿',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 6, day: null }],
        page_start: 329,
        page_end: 330,
      },
      {
        title: '对姚文元同志访问阿尔巴尼亚的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 6, day: null }],
        page_start: 330,
        page_end: 330,
      },
      {
        title: '关于绝食静坐的问题',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 6, day: 29 }],
        page_start: 330,
        page_end: 330,
      },
      {
        title: '看了西安师院造反派两张大字报和给中央文革的信后的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 6, day: null }],
        page_start: 330,
        page_end: 330,
      },
      {
        title: '关于缅甸问题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 7, day: 1 }],
        page_start: 330,
        page_end: 330,
      },
      {
        title: '关于建造主席塑象问题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 7, day: 5 }],
        page_start: 330,
        page_end: 330,
      },
      {
        title: '对军队同志的教导',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 7, day: null }],
        page_start: 331,
        page_end: 331,
      },
      {
        title: '在听了××××会议汇报后的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 7, day: 7 }],
        page_start: 331,
        page_end: 332,
      },
      {
        title: '关于“农村包围城市”的口号',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 7, day: null }],
        page_start: 332,
        page_end: 332,
      },
      {
        title: '关于不要“开快车”的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 7, day: 13 }],
        page_start: 332,
        page_end: 332,
      },
      {
        title: '接见军队领导干部时的讲话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 7, day: 13 }],
        page_start: 332,
        page_end: 332,
      },
      {
        title: '关于湖南军区的龙书金',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 7, day: null }],
        page_start: 333,
        page_end: 333,
      },
      {
        title: '关于教育革命的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 7, day: null }],
        page_start: 333,
        page_end: 333,
      },
      {
        title: '《中央对武汉军区的复电》',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 7, day: 25 }],
        page_start: 333,
        page_end: 334,
      },
      {
        title: '对武汉事件的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 7, day: null }],
        page_start: 334,
        page_end: 334,
      },
      {
        title: '关于“八一”建军节的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 7, day: null }],
        page_start: 334,
        page_end: 334,
      },
      {
        title: '为一九六七年七月三十日《人民日报》社论加的一句话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 7, day: null }],
        page_start: 334,
        page_end: 334,
      },
      {
        title: '关于大联合的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 8, day: null }],
        page_start: 335,
        page_end: 335,
      },
      {
        title: '关于大串连的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 8, day: null }],
        page_start: 335,
        page_end: 335,
      },
      {
        title: '对《红旗》杂志1967年第十二期社论的批语',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 8, day: null }],
        page_start: 335,
        page_end: 335,
      },
      {
        title: '对天津、河北问题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 8, day: null }],
        page_start: 335,
        page_end: 335,
      },
      {
        title: '无产阶级专政下革命的主要对象',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 8, day: null }],
        page_start: 336,
        page_end: 336,
      },
      {
        title: '关于武斗的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 8, day: null }],
        page_start: 336,
        page_end: 336,
      },
      {
        title:
          '对《中共中央、国务院、中央军委、中央文革小组给煤炭工业战线职工的一封信》的批示和修改',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 8, day: 16 }],
        page_start: 336,
        page_end: 336,
      },
      {
        title: '关于军队支左问题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 8, day: null }],
        page_start: 337,
        page_end: 337,
      },
      {
        title: '要从政治上、思想上、理论上把走资派打倒',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 8, day: null }],
        page_start: 337,
        page_end: 337,
      },
      {
        title: '8·27指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 8, day: 27 }],
        page_start: 337,
        page_end: 338,
      },
      {
        title: '对公安工作的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 8, day: null }],
        page_start: 338,
        page_end: 338,
      },
      {
        title: '关于陈毅的几点指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 8, day: 11 }],
        page_start: 338,
        page_end: 338,
      },
      {
        title: '对姚文元志《还陶铸的两本书》一文的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 9, day: null }],
        page_start: 338,
        page_end: 338,
      },
      {
        title: '对新闻工作的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 9, day: null }],
        page_start: 338,
        page_end: 338,
      },
      {
        title: '对庆祝国庆的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 9, day: null }],
        page_start: 339,
        page_end: 339,
      },
      {
        title: '中共中央通知',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 10, day: 7 }],
        page_start: 339,
        page_end: 339,
      },
      {
        title: '毛主席视察华北、中南和华东地区时的重要指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967 }],
        page_start: 339,
        page_end: 341,
      },
      {
        title: '毛主席视察华北、中南和华东地区时谈的主要精神的传达',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 9, day: null }],
        page_start: 341,
        page_end: 352,
      },
      {
        title: '对林彪同志一九六七年国庆讲话的评语',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 10, day: null }],
        page_start: 352,
        page_end: 352,
      },
      {
        title: '造反派要听周总理的话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 10, day: null }],
        page_start: 352,
        page_end: 352,
      },
      {
        title: '关于机关革命化的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 10, day: null }],
        page_start: 353,
        page_end: 353,
      },
      {
        title: '接见刚果（布）总理努马扎莱的谈话',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 10, day: 3 }],
        page_start: 353,
        page_end: 353,
      },
      {
        title: '关于按系统实现革命的大联合的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 10, day: 17 }],
        page_start: 354,
        page_end: 354,
      },
      {
        title: '对海军学习毛主席著作积极分子代表大会代表的谈活',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 11, day: 19 }],
        page_start: 354,
        page_end: 354,
      },
      {
        title: '进行教育革命要依靠无产阶级革命派',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 10, day: 25 }],
        page_start: 354,
        page_end: 354,
      },
      {
        title: '对《解放军报》1967年11月9日社论《抓好形势教育》的重要修改',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 11, day: null }],
        page_start: 354,
        page_end: 355,
      },
      {
        title: '关于党组织的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 11, day: null }],
        page_start: 355,
        page_end: 355,
      },
      {
        title: '关于正确对待犯过错误的老造反派的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 11, day: null }],
        page_start: 355,
        page_end: 355,
      },
      {
        title: '给林彪、周恩来、中央及文革的信',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 12, day: 17 }],
        page_start: 355,
        page_end: 356,
      },
      {
        title: '对姚文元同志一封信的批示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 12, day: null }],
        page_start: 356,
        page_end: 356,
      },
      {
        title: '祝贺越南南方民族解放阵线成立七周年给阮友寿主席的贺电',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 12, day: 19 }],
        page_start: 356,
        page_end: 357,
      },
      {
        title: '关于举办学习班的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1967, month: 2, day: null }],
        page_start: 357,
        page_end: 357,
      },
      {
        title: '对广东同题的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1968, month: 2, day: null }],
        page_start: 358,
        page_end: 358,
      },
      {
        title: '关于革命委员会等的指示',
        authors: ['毛泽东'],
        dates: [{ year: 1968, month: 2, day: null }],
        page_start: 358,
        page_end: 358,
      },
      {
        title: '无产阶级文化大革命是共产党和国民党长期斗争的继续',
        authors: ['毛泽东'],
        dates: [{ year: 1968, month: 3, day: null }],
        page_start: 358,
        page_end: 358,
      },
      {
        title: '革命委员会的三条基本经验',
        authors: ['毛泽东'],
        dates: [{ year: 1968, month: 3, day: 30 }],
        page_start: 359,
        page_end: 359,
      },
      {
        title: '支持美国黑人抗暴斗争的声明',
        authors: ['毛泽东'],
        dates: [{ year: 1968, month: 4, day: 16 }],
        page_start: 359,
        page_end: 360,
      },
      {
        title: '对派性要进行阶级分析',
        authors: ['毛泽东'],
        dates: [
          { year: 1968, month: 4, day: null },
          { year: 5, month: 5, day: null },
        ],
        page_start: 360,
        page_end: 360,
      },
    ],
    ocr: undefined,
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/45f85d41-2767-49bc-87e9-ba331b429fce.pdf',
};
