export default {
  entity: {
    id: '47db5441-00d4-4901-ab0f-99d36ae4555b',
    name: '无产阶级文化大革命资料汇编（第四篇）（水陆洲2012年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '水陆洲编',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/47db5441-00d4-4901-ab0f-99d36ae4555b.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '第一章 学习无产阶级专政的理论 第一节 学理论 抓路线 促生产',
        authors: ['水陆洲'],
        page_start: 4,
        page_end: 28,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title:
          '第一章 学习无产阶级专政的理论 第二节 学习毛主席关于理论问题的重要指示',
        authors: ['水陆洲'],
        page_start: 29,
        page_end: 100,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第一章 学习无产阶级专政的理论 第三节 召开四届人大',
        authors: ['水陆洲'],
        page_start: 101,
        page_end: 125,
        dates: [{ year: 2012, month: 6, day: 12 }],
      },
      {
        title:
          '第一章 学习无产阶级专政的理论 第四节 毛泽东关于批修正主义的指示',
        authors: ['水陆洲'],
        page_start: 126,
        page_end: 139,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第一章 学习无产阶级专政的理论 第五节《红都女皇》事件',
        authors: ['水陆洲'],
        page_start: 140,
        page_end: 144,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第一章 学习无产阶级专政的理论 第六节 评水浒',
        authors: ['水陆洲'],
        page_start: 145,
        page_end: 185,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第一章 学习无产阶级专政的理论 第七节 落实文艺政策',
        authors: ['水陆洲'],
        page_start: 186,
        page_end: 205,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第一章 学习无产阶级专政的理论 第八节 农业学大寨',
        authors: ['水陆洲'],
        page_start: 206,
        page_end: 236,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第一章 学习无产阶级专政的理论 第九节 落实各类人员政策',
        authors: ['水陆洲'],
        page_start: 237,
        page_end: 256,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第一节 以三项指示为纲',
        authors: ['水陆洲'],
        page_start: 257,
        page_end: 271,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第二节 整顿工业交通',
        authors: ['水陆洲'],
        page_start: 272,
        page_end: 293,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第三节 整顿教育',
        authors: ['水陆洲'],
        page_start: 294,
        page_end: 342,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第四节 整顿中国科学院',
        authors: ['水陆洲'],
        page_start: 343,
        page_end: 432,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第五节 整顿军队',
        authors: ['水陆洲'],
        page_start: 433,
        page_end: 467,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第六节 整顿国防科委系统',
        authors: ['水陆洲'],
        page_start: 468,
        page_end: 527,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第七节 整顿党组织',
        authors: ['水陆洲'],
        page_start: 528,
        page_end: 536,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第八节 各省的整顿',
        authors: ['水陆洲'],
        page_start: 537,
        page_end: 557,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第九节 反击右倾翻案风',
        authors: ['水陆洲'],
        page_start: 558,
        page_end: 618,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第三章 反击右倾翻案风 第一节 一九七六年的形势和任务',
        authors: ['水陆洲'],
        page_start: 619,
        page_end: 660,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第三章 反击右倾翻案风 第二节 继续反击右倾翻案风',
        authors: ['水陆洲'],
        page_start: 661,
        page_end: 852,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第三章 反击右倾翻案风 第三节 周恩来朱德逝世',
        authors: ['水陆洲'],
        page_start: 853,
        page_end: 884,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第三章 反击右倾翻案风 第四节 天安门事件',
        authors: ['水陆洲'],
        page_start: 885,
        page_end: 960,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第四章 毛泽东主席逝世 第一节 毛泽东的政治遗言',
        authors: ['水陆洲'],
        page_start: 961,
        page_end: 967,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第四章 毛泽东主席逝世 第二节 各级党和政府的吊唁活动',
        authors: ['水陆洲'],
        page_start: 968,
        page_end: 1077,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第四章 毛泽东主席逝世 第三节 全国人民吊唁毛泽东主席逝世',
        authors: ['水陆洲'],
        page_start: 1078,
        page_end: 1412,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第四章 毛泽东主席逝世 第四节 各国对毛泽东逝世的吊唁',
        authors: ['水陆洲'],
        page_start: 1413,
        page_end: 1747,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
    ],
    ocr: {
      standard_paragraph_merge_strategy_threshold: 0.186,
      differential_paragraph_merge_strategy_threshold: 0,
      content_thresholds: [0.054, 0, 0, 0],
      extract_text_from_pdf: true,
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/47db5441-00d4-4901-ab0f-99d36ae4555b.pdf',
};
