export default {
  entity: {
    id: '4828e228-4e46-4374-a1b1-b2cb71877e82',
    name: '红旗一九六九年第十期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/4828e228-4e46-4374-a1b1-b2cb71877e82.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '为进一步巩固无产阶级专政而斗争──庆祝中华人民共和国成立二十周年',
        authors: [
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
          '《人民日报》编辑部',
        ],
        page_start: 8,
        page_end: 11,
        dates: [{ year: 1969, month: 10, day: 1 }],
      },
      {
        title: '庆祝中华人民共和国成立二十周年口号',
        authors: ['《红旗》杂志编辑部'],
        page_start: 12,
        page_end: 13,
        dates: [{ year: 1969, month: 10 }],
      },
      {
        title: '光芒万丈的灯塔——学习《关于正确处理人民内部矛盾的问题》',
        authors: ['辽宁省革命委员会写作小组'],
        page_start: 14,
        page_end: 24,
        dates: [{ year: 1969, month: 10 }],
      },
      {
        title: '中国社会主义工业化的道路',
        authors: ['北京市革命委员会写作小组'],
        page_start: 25,
        page_end: 34,
        dates: [{ year: 1969, month: 10 }],
      },
      {
        title: '紧跟毛主席 一步一层天',
        authors: ['李全寿'],
        page_start: 35,
        page_end: 39,
        dates: [{ year: 1969, month: 10 }],
      },
      {
        title: '学习革命样板戏 保卫革命样板戏',
        authors: ['哲平'],
        page_start: 40,
        page_end: 43,
        dates: [{ year: 1969, month: 10 }],
      },
      {
        title: '用唯物辩证法认识矛盾和解决矛盾',
        authors: ['人民解放军武汉部队某部七连党支部'],
        page_start: 44,
        page_end: 50,
        dates: [{ year: 1969, month: 10 }],
      },
      {
        title: '毛泽东思想在社会主义建设中的伟大胜利',
        authors: ['天津市革命委员会写作小组'],
        page_start: 51,
        page_end: 59,
        dates: [{ year: 1969, month: 10 }],
      },
      {
        title: '工人阶级的革命志气',
        authors: ['王超柱'],
        page_start: 60,
        page_end: 62,
        dates: [{ year: 1969, month: 10 }],
      },
      {
        title: '独立自主、自力更生方针的光辉成果',
        authors: ['魏峻烈'],
        page_start: 63,
        page_end: 65,
        dates: [{ year: 1969, month: 10 }],
      },
      {
        title: '在合作化的基础上实现机械化',
        authors: ['程金阶'],
        page_start: 66,
        page_end: 68,
        dates: [{ year: 1969, month: 10 }],
      },
      {
        title: '毛主席人民战争思想的无比威力',
        authors: ['简海金'],
        page_start: 69,
        page_end: 71,
        dates: [{ year: 1969, month: 10 }],
      },
      {
        title: '毛泽东思想的光辉照亮了西藏高原',
        authors: ['央宗'],
        page_start: 72,
        page_end: 75,
        dates: [{ year: 1969, month: 10 }],
      },
      {
        title: '靠毛泽东思想攀登科学技术新高峰',
        authors: ['朱光亚'],
        page_start: 76,
        page_end: 78,
        dates: [{ year: 1969, month: 10 }],
      },
      {
        title: '农村妇女是巨大的革命力量',
        authors: ['黑龙江省革命委员会、兰西县革命委员会调查组'],
        page_start: 79,
        page_end: 81,
        dates: [{ year: 1969, month: 10 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/4828e228-4e46-4374-a1b1-b2cb71877e82.pdf',
};
