export default {
  entity: {
    id: '49c0e64a-0dd4-4b15-94de-22f754f1c0c0',
    name: '大逆转：中国的私有化 1979-1989',
    internal: false,
    official: false,
    type: 'pdf',
    author: '韩丁',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/49c0e64a-0dd4-4b15-94de-22f754f1c0c0.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '前言',
        authors: ['威廉·韩丁'],
        page_start: 3,
        page_end: 4,
        dates: [{ year: 1990 }],
      },
      {
        title: '简介：中国的农村改革',
        authors: ['威廉·韩丁'],
        page_start: 5,
        page_end: 12,
        dates: [{ year: 1990 }],
      },
      {
        title: '中国的一个小城镇：1978年的张庄',
        authors: ['威廉·韩丁'],
        page_start: 13,
        page_end: 18,
        dates: [{ year: 1990 }],
      },
      {
        title: '凤阳之行 1983',
        authors: ['威廉·韩丁'],
        page_start: 19,
        page_end: 29,
        dates: [{ year: 1990 }],
      },
      {
        title: '大刀阔斧的改革，农村的变化 1984',
        authors: ['威廉·韩丁'],
        page_start: 30,
        page_end: 34,
        dates: [{ year: 1990 }],
      },
      {
        title: '草原现状',
        authors: ['威廉·韩丁'],
        page_start: 35,
        page_end: 39,
        dates: [{ year: 1990 }],
      },
      {
        title: '解读改革：1986年农村的变化',
        authors: ['威廉·韩丁'],
        page_start: 40,
        page_end: 46,
        dates: [{ year: 1990 }],
      },
      {
        title: '改革所绕过的：农业机械化 1986',
        authors: ['威廉·韩丁'],
        page_start: 47,
        page_end: 52,
        dates: [{ year: 1990 }],
      },
      {
        title: '重访大寨：1987年',
        authors: ['威廉·韩丁'],
        page_start: 53,
        page_end: 59,
        dates: [{ year: 1990 }],
      },
      {
        title: '毛泽东农村政策再思',
        authors: ['威廉·韩丁'],
        page_start: 60,
        page_end: 68,
        dates: [{ year: 1990 }],
      },
      {
        title: '为什么不走资本主义的道路？',
        authors: ['威廉·韩丁'],
        page_start: 69,
        page_end: 73,
        dates: [{ year: 1990 }],
      },
      {
        title: '天安门屠杀：1989年的6月',
        authors: ['威廉·韩丁'],
        page_start: 74,
        page_end: 80,
        dates: [{ year: 1990 }],
      },
    ],
    ocr: {
      content_thresholds: [0, 0.046, 0, 0],
      standard_paragraph_merge_strategy_threshold: 0.085,
      differential_paragraph_merge_strategy_threshold: 0,
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/49c0e64a-0dd4-4b15-94de-22f754f1c0c0.pdf',
};
