export default {
  entity: {
    id: '52ef824d-b21d-414c-8a28-d6d69976f705',
    name: '红旗一九五九年第一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/52ef824d-b21d-414c-8a28-d6d69976f705.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '有历史意义的纲领性文件',
        authors: ['《红旗》杂志编辑部'],
        page_start: 3,
        page_end: 7,
        dates: [{ year: 1959, month: 1, day: 1 }],
      },
      {
        title: '一九五九年工业战线的任务',
        authors: ['薄一波'],
        page_start: 8,
        page_end: 12,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 1, day: 1 }],
      },
      {
        title: '一九五九年农业战线的任务',
        authors: ['廖鲁言'],
        page_start: 13,
        page_end: 20,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 1, day: 1 }],
      },
      {
        title: '思想必须适合于客观规律性',
        authors: ['范若愚'],
        page_start: 21,
        page_end: 24,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 1, day: 1 }],
      },
      {
        title: '从工人诗歌看诗歌的民族形式问题',
        authors: ['张光年'],
        page_start: 25,
        page_end: 31,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 1, day: 1 }],
      },
      {
        title: '丰富多采',
        authors: ['郭小川'],
        page_start: 32,
        page_end: 33,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 1, day: 1 }],
      },
      {
        title: '一个小型钢铁联合企业的诞生',
        authors: ['阎明润'],
        page_start: 34,
        page_end: 36,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 1, day: 1 }],
      },
      {
        title: '农民怎样议论按劳分配',
        authors: ['王录'],
        page_start: 36,
        page_end: 38,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 1, day: 1 }],
      },
      {
        title: '劳动和休息',
        authors: ['树则'],
        page_start: 38,
        page_end: 39,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 1, day: 1 }],
      },
      {
        title: '照妖镜下显原形——铁托集团在台湾问题上的立场说明了什么？',
        authors: ['李亚'],
        page_start: 40,
        page_end: 43,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 1, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/52ef824d-b21d-414c-8a28-d6d69976f705.pdf',
};
