export default {
  entity: {
    id: '56345858-52d1-473e-b5bd-436fd87f20a4',
    name: '自然辩证法一九七三年第一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '恩格斯，人民出版社1971年版',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/56345858-52d1-473e-b5bd-436fd87f20a4.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '天体的来龙去脉',
        authors: ['余衡泰'],
        page_start: 8,
        page_end: 66,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '宇宙是无限和有限的统一',
        authors: ['卞思祖'],
        page_start: 67,
        page_end: 86,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '3°K微波辐射的发现说明了什么？——兼评“大爆炸宇宙学”',
        authors: ['李柯'],
        page_start: 87,
        page_end: 103,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '天文学从社会实践中来',
        authors: ['余珊'],
        page_start: 104,
        page_end: 111,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '报风和乘风',
        authors: ['吴玉远'],
        page_start: 112,
        page_end: 118,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '地下顶管',
        authors: ['上海市政工程公司革命委员会', '龚朴', '章智明', '沈逸珍'],
        page_start: 119,
        page_end: 124,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '苏州河上巧运水泥管',
        authors: ['上海港驳船运输公司拖轮队', '唐天林'],
        page_start: 125,
        page_end: 129,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '看鱼下网',
        authors: ['张文振', '张文彩'],
        page_start: 130,
        page_end: 132,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '水上也能种花生',
        authors: ['上海川沙县药师四队科学实验小组', '佟林清', '张燕'],
        page_start: 133,
        page_end: 135,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '论证等级式宇宙学',
        authors: ['G·德·伏古勒', '傅季重', '周煦良', '徐孝通'],
        page_start: 136,
        page_end: 154,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '《天问》《天对》选注',
        authors: [
          '王运熙',
          '李庆甲',
          '徐鹏',
          '顾易生',
          '章培恒',
          '谭其骧',
          '杨宽',
          '蒋天枢',
        ],
        page_start: 155,
        page_end: 177,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '论无限、宇宙和世界（节译）',
        authors: ['布鲁诺', '傅力', '王福山'],
        page_start: 178,
        page_end: 192,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '关于地壳结构的一种新理论——板块构造假说',
        authors: ['朱新轩', '王慧中', '郭蓄民', '许世远'],
        page_start: 193,
        page_end: 204,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '天文学中的一些新发现',
        authors: ['李中元'],
        page_start: 205,
        page_end: 213,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '到自然界中去找辩证法——科教片《无限风光在险峰》观后',
        authors: ['朱锋'],
        page_start: 214,
        page_end: 218,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '小辞典',
        authors: ['《自然辩证法》编辑部'],
        page_start: 219,
        page_end: 223,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '编者的话',
        authors: ['《自然辩证法》编辑部'],
        page_start: 223,
        page_end: 225,
        dates: [{ year: 1973, month: 6 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.08, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/56345858-52d1-473e-b5bd-436fd87f20a4.pdf',
};
