export default {
  entity: {
    id: '56358efd-4f03-45ce-865c-69807faa5f28',
    name: '红旗一九六五年第九期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/56358efd-4f03-45ce-865c-69807faa5f28.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '抗日游击战争的战略问题',
        authors: ['毛泽东'],
        page_start: 3,
        page_end: 22,
        dates: [{ year: 1938, month: 5 }],
      },
      {
        title: '从近代物理学的发展看唯心主义和形而上学的破产',
        authors: ['朱洪元'],
        page_start: 23,
        page_end: 27,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '在不断揭露和解决矛盾中前进',
        authors: ['高崇寿'],
        page_start: 27,
        page_end: 29,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '对于用唯物辩证法指导分子结构理论研究的一些看法',
        authors: ['徐光宪'],
        page_start: 30,
        page_end: 33,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '关于物质的无限可分性',
        authors: ['龚育之'],
        page_start: 33,
        page_end: 38,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '唯物辩证法是探索自然界的理论武器',
        authors: ['艾思奇'],
        page_start: 38,
        page_end: 43,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '德波林学派的一些批判者变成了德波林学派的继承者',
        authors: ['李哲'],
        page_start: 44,
        page_end: 49,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '飞夺泸定桥',
        authors: ['杨成武'],
        page_start: 50,
        page_end: 56,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '大石塔村的变革',
        authors: ['徐雅'],
        page_start: 57,
        page_end: 59,
        dates: [{ year: 1947 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
    ],
    ocr: { content_thresholds: [0.07, 0.165, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/56358efd-4f03-45ce-865c-69807faa5f28.pdf',
};
