export default {
  entity: {
    id: '56c4afc1-0f03-4f92-b376-2e72682a26ae',
    name: '红旗一九七二年第十一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/56c4afc1-0f03-4f92-b376-2e72682a26ae.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中华人民共和国政府声明',
        authors: [],
        page_start: 6,
        page_end: 6,
        dates: [{ year: 1972, month: 10, day: 30 }],
      },
      {
        title: '加强党的一元化领导',
        authors: ['钟实'],
        page_start: 7,
        page_end: 12,
        dates: [{ year: 1972, month: 11, day: 1 }],
      },
      {
        title: '谦虚谨慎 乘胜前进',
        authors: ['辛源'],
        page_start: 13,
        page_end: 15,
        dates: [{ year: 1972, month: 11, day: 1 }],
      },
      {
        title: '要从思想上弄清楚路线是非',
        authors: ['云岚'],
        page_start: 16,
        page_end: 19,
        dates: [{ year: 1972, month: 11, day: 1 }],
      },
      {
        title: '关键在于提高马列主义理论水平——谈批修整风如何深入下去',
        authors: ['《解放日报》评论员'],
        page_start: 20,
        page_end: 21,
        dates: [{ year: 1972, month: 10, day: 23 }],
      },
      {
        title: '认真总结正反两方面的经验',
        authors: ['庄宁'],
        page_start: 22,
        page_end: 25,
        dates: [{ year: 1972, month: 11, day: 1 }],
      },
      {
        title: '领导工作要坚持群众路线',
        authors: ['中国共产党个旧市委员会'],
        page_start: 26,
        page_end: 28,
        dates: [{ year: 1972, month: 11, day: 1 }],
      },
      {
        title: '奇袭白虎团',
        authors: ['山东省京剧团《奇袭白虎团》剧组'],
        page_start: 29,
        page_end: 57,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.47,
          content_thresholds: [0, 0.15, 0, 0.2],
        },
        dates: [{ year: 1972, month: 9 }],
      },
      {
        title: '中朝人民战斗友谊的壮丽颂歌——评革命现代京剧《奇袭白虎团》',
        authors: ['路戈'],
        page_start: 58,
        page_end: 61,
        dates: [{ year: 1972, month: 11, day: 1 }],
      },
      {
        title: '节约一切可能节约的人力',
        authors: ['唐山机车车辆工厂工人评论组'],
        page_start: 62,
        page_end: 65,
        dates: [{ year: 1972, month: 11, day: 1 }],
      },
      {
        title: '坚持储粮 备战备荒——广西全州县紫岭大队红星生产队的调查报告',
        authors: ['中国共产党全州县委员会调查组'],
        page_start: 66,
        page_end: 67,
        dates: [{ year: 1972, month: 11, day: 1 }],
      },
      {
        title: '做好后进队的转化工作',
        authors: ['中国共产党应城县委员会'],
        page_start: 68,
        page_end: 70,
        dates: [{ year: 1972, month: 11, day: 1 }],
      },
      {
        title: '了解一些民族解放运动的历史——四谈读一点世界史',
        authors: ['史军'],
        page_start: 71,
        page_end: 76,
        dates: [{ year: 1972, month: 11, day: 1 }],
      },
      {
        title: '学一点地理',
        authors: ['华志海'],
        page_start: 77,
        page_end: 81,
        dates: [{ year: 1972, month: 11, day: 1 }],
      },
      {
        title: '对于一个提法的建议',
        authors: ['肖学军'],
        page_start: 81,
        page_end: 81,
        dates: [{ year: 1972, month: 11, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/56c4afc1-0f03-4f92-b376-2e72682a26ae.pdf',
};
