export default {
  entity: {
    id: '5a741aaa-fac2-4066-a503-6ebfd0ae1ae1',
    name: '文革通讯（第12期）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '浙江工农兵美术大学毛泽东主义红卫兵战斗队、毛泽东主义红卫兵',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives15/main/5a741aaa-fac2-4066-a503-6ebfd0ae1ae1.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '林彪同志谈文化革命的十大成绩',
        authors: ['林彪'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967 }],
      },
      {
        title: '江青同志讲话',
        authors: ['江青'],
        page_start: 1,
        page_end: 2,
        dates: [{ year: 1967 }],
      },
      {
        title: '张春桥同志讲话',
        authors: ['张春桥'],
        page_start: 2,
        page_end: 3,
        dates: [
          { year: 1967, month: 3, day: 12 },
          { year: 1967, month: 3, day: 11 },
        ],
      },
      {
        title: '戚本禹同志讲话',
        authors: ['戚本禹'],
        page_start: 3,
        page_end: 4,
        dates: [{ year: 1967, month: 3, day: 2 }],
      },
      {
        title: '世界五大洲革命青年支持红卫兵',
        authors: ['《文革通讯》编辑部'],
        page_start: 4,
        page_end: 4,
        dates: [{ year: 1967, month: 4, day: 22 }],
      },
      {
        title: '祖国各地',
        authors: ['《文革通讯》编辑部'],
        page_start: 4,
        page_end: 5,
        dates: [{ year: 1967, month: 4, day: 22 }],
      },
      {
        title: '刘少奇二十年罪行录',
        authors: ['《文革通讯》编辑部'],
        page_start: 5,
        page_end: 6,
        dates: [{ year: 1967, month: 4, day: 22 }],
      },
      {
        title: '刘少奇剥削阶级本性难移——刘少奇家乡调查记',
        authors: ['《文革通讯》编辑部'],
        page_start: 6,
        page_end: 7,
        dates: [{ year: 1967, month: 4, day: 22 }],
      },
      {
        title: '《论共产党员的修养》再次出版的背景',
        authors: ['《文革通讯》编辑部'],
        page_start: 7,
        page_end: 8,
        dates: [{ year: 1967, month: 4, day: 22 }],
      },
    ],
    ocr: undefined,
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives15/5a741aaa-fac2-4066-a503-6ebfd0ae1ae1.pdf',
};
