export default {
  entity: {
    id: '5a912e06-accb-4194-bc40-bd0948860cc7',
    name: '红旗一九七六年第二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/5a912e06-accb-4194-bc40-bd0948860cc7.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '回击科技界的右倾翻案风',
        authors: ['北京大学', '清华大学大批判组'],
        page_start: 6,
        page_end: 14,
        dates: [{ year: 1, month: 2 }],
      },
      {
        title: '在斗争中学习无产阶级专政理论',
        authors: ['程越'],
        page_start: 15,
        page_end: 19,
        dates: [{ year: 1965, month: 2 }],
      },
      {
        title: '折中主义就是修正主义',
        authors: ['纪平'],
        page_start: 20,
        page_end: 23,
        dates: [{ year: 1965, month: 2 }],
      },
      {
        title: '孔孟之道与投降主义——从《宣和遗事》看《水浒》的创作思想',
        authors: ['史众'],
        page_start: 24,
        page_end: 29,
        dates: [{ year: 1965, month: 2 }],
      },
      {
        title: '不许为修正主义教育路线翻案',
        authors: ['辽宁大学大批判组'],
        page_start: 30,
        page_end: 34,
        dates: [{ year: 1965, month: 2 }],
      },
      {
        title: '“反对形而上学”是假 否定教育革命是真',
        authors: ['武汉大学大批判组'],
        page_start: 35,
        page_end: 39,
        dates: [{ year: 1965, month: 2 }],
      },
      {
        title: '深入批判“学而优则仕”的谬论',
        authors: ['广西师范学院中文系理论组'],
        page_start: 40,
        page_end: 42,
        dates: [{ year: 1965, month: 2 }],
      },
      {
        title: '开展教育革命大辩论的一些体会',
        authors: ['广西南宁市第二中学觉支部'],
        page_start: 43,
        page_end: 46,
        dates: [{ year: 1965, month: 2 }],
      },
      {
        title: '历史是人民群众创造的',
        authors: ['江虹'],
        page_start: 47,
        page_end: 51,
        dates: [{ year: 1965, month: 2 }],
      },
      {
        title: '开门办科研好',
        authors: ['中国科学院大连化学物理研究所党委会'],
        page_start: 52,
        page_end: 56,
        dates: [{ year: 1965, month: 2 }],
      },
      {
        title: '积极开展群众性的农业科学实验',
        authors: ['中国共产党华容县委员会'],
        page_start: 57,
        page_end: 61,
        dates: [{ year: 1965, month: 2 }],
      },
      {
        title: '全心全意地依靠工人阶级',
        authors: ['兰州化学工业公司党委会'],
        page_start: 62,
        page_end: 66,
        dates: [{ year: 1965, month: 2 }],
      },
      {
        title: '让教育革命的钟声响彻四方——略论彩色故事片《决裂》的主题思想',
        authors: ['方锷'],
        page_start: 67,
        page_end: 73,
        dates: [{ year: 1965, month: 2 }],
      },
      {
        title: '奔腾向前的社会主义洪流——评长篇小说《千重浪》',
        authors: ['马联玉'],
        page_start: 74,
        page_end: 78,
        dates: [{ year: 1965, month: 2 }],
      },
      {
        title: '大拖拉机和小面包',
        authors: ['景池'],
        page_start: 79,
        page_end: 81,
        dates: [{ year: 1965, month: 2 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/5a912e06-accb-4194-bc40-bd0948860cc7.pdf',
};
