export default {
  entity: {
    id: '5d4cbf36-0f89-435a-8f64-80a9168e8109',
    name: '红旗一九七一年第七、八期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/5d4cbf36-0f89-435a-8f64-80a9168e8109.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '纪念中国共产党五十周年',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        page_start: 8,
        page_end: 28,
        dates: [{ year: 1971, month: 7, day: 1 }],
      },
      {
        title: '坚持马克思主义的领导方法——学习《关于领导方法的若干问题》',
        authors: ['中国共产党云南省委员会写作小组'],
        page_start: 29,
        page_end: 36,
        dates: [{ year: 1971, month: 7, day: 1 }],
      },
      {
        title: '进一步加强党委会的建设——学习《党委会的工作方法》',
        authors: ['中国共产党广东省委员会写作小组'],
        page_start: 37,
        page_end: 42,
        dates: [{ year: 1971, month: 7, day: 1 }],
      },
      {
        title:
          '坚持生产关系和生产力的辩证统一论——学习《关于正确处理人民内部矛盾的问题》的一点体会',
        authors: ['权忠'],
        page_start: 43,
        page_end: 50,
        dates: [{ year: 1971, month: 7, day: 1 }],
      },
      {
        title: '牢记党内两条路线斗争的历史经验——学习《学习和时局》',
        authors: ['中国共产党青海省委员会写作小组'],
        page_start: 51,
        page_end: 55,
        dates: [{ year: 1971, month: 7, day: 1 }],
      },
      {
        title: '永远拿起批评和自我批评的武器',
        authors: ['江苏海门县大新公社中兴大队党支部'],
        page_start: 56,
        page_end: 61,
        dates: [{ year: 1971, month: 7, day: 1 }],
      },
      {
        title: '发扬党的密切联系群众的优良作风',
        authors: ['辽宁宽甸县永甸公社军民大队党支部'],
        page_start: 62,
        page_end: 65,
        dates: [{ year: 1971, month: 7, day: 1 }],
      },
      {
        title: '加强党的政策教育',
        authors: ['中国共产党长春客车厂委员会'],
        page_start: 66,
        page_end: 70,
        dates: [{ year: 1971, month: 7, day: 1 }],
      },
      {
        title: '认真读书，坚持坚定正确的政治方向',
        authors: ['中国共产党北京化工三厂委员会'],
        page_start: 71,
        page_end: 76,
        dates: [{ year: 1971, month: 7, day: 1 }],
      },
      {
        title: '在革命大批判中加强党的思想建设',
        authors: ['中国共产党天津自行车厂委员会'],
        page_start: 77,
        page_end: 80,
        dates: [{ year: 1971, month: 7, day: 1 }],
      },
      {
        title: '艰苦奋斗永不忘 延安精神代代传',
        authors: ['陕西延安城区枣园公社杨家岭大队党支部'],
        page_start: 81,
        page_end: 84,
        dates: [{ year: 1971, month: 7, day: 1 }],
      },
      {
        title: '认真实行民主集中制',
        authors: ['中国人民解放军成都部队某团党委会'],
        page_start: 85,
        page_end: 89,
        dates: [{ year: 1971, month: 7, day: 1 }],
      },
      {
        title: '在三大革命运动第一线造就无产阶级干部队伍',
        authors: ['中国共产党江西省委员会写作小组'],
        page_start: 90,
        page_end: 97,
        dates: [{ year: 1971, month: 7, day: 1 }],
      },
      {
        title: '一个密切联系群众的党委会——湖南龙山县洛塔公社党委会的调查报告',
        authors: ['中国共产党湖南省委员会调查组'],
        page_start: 98,
        page_end: 105,
        dates: [{ year: 1971, month: 7, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/5d4cbf36-0f89-435a-8f64-80a9168e8109.pdf',
};
