export default {
  entity: {
    id: '5f27c701-5f3c-43f4-9a8d-368bf21a01aa',
    name: '红旗一九七三年第十二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/5f27c701-5f3c-43f4-9a8d-368bf21a01aa.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '巩固无产阶级专政的纲领——学习《论人民民主专政》',
        authors: ['俞彤'],
        page_start: 8,
        page_end: 14,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
      {
        title: '巩固无产阶级专政的一项战略措施',
        authors: ['云岚'],
        page_start: 15,
        page_end: 20,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
      {
        title: '积极培养妇女干部',
        authors: ['夏平'],
        page_start: 21,
        page_end: 25,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
      {
        title: '反潮流是马列主义的一个原则',
        authors: ['方岩梁'],
        page_start: 26,
        page_end: 29,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
      {
        title: '“倒过来”的哲学和复辟资本主义——批判林彪的资产阶级唯心论',
        authors: ['辛风'],
        page_start: 30,
        page_end: 35,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
      {
        title: '继续搞好农村的卫生革命',
        authors: ['金卫'],
        page_start: 36,
        page_end: 41,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
      {
        title: '把无产阶级教育革命进行到底',
        authors: ['钟实'],
        page_start: 42,
        page_end: 45,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
      {
        title: '开展群众性的革命故事活动',
        authors: ['上海市金山县文化馆'],
        page_start: 46,
        page_end: 49,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
      {
        title: '把批孔和批林结合起来',
        authors: ['天津市电磁线厂工人评论组'],
        page_start: 50,
        page_end: 51,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
      {
        title: '孔子是“全民教育家”吗？',
        authors: ['唐晓文'],
        page_start: 52,
        page_end: 59,
        dates: [{ year: 1973, month: 9, day: 27 }],
      },
      {
        title: '林彪为什么咒骂秦始皇？',
        authors: ['陈阳凤', '李子林', '梅倩'],
        page_start: 60,
        page_end: 65,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
      {
        title: '加速山区的农业建设',
        authors: ['巴山'],
        page_start: 66,
        page_end: 70,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
      {
        title: '发展工业 支援农业',
        authors: ['黎峰'],
        page_start: 71,
        page_end: 75,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
      {
        title: '保护环境 发展生产',
        authors: ['湘晖'],
        page_start: 76,
        page_end: 79,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
      {
        title: '从进化论看唯物论和唯心论的斗争',
        authors: ['陈燕生'],
        page_start: 80,
        page_end: 89,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
      {
        title: '红旗杂志一九七三年第一期到第十二期总目录',
        authors: ['《红旗》杂志编辑部'],
        page_start: 90,
        page_end: 97,
        dates: [{ year: 1973, month: 12, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/5f27c701-5f3c-43f4-9a8d-368bf21a01aa.pdf',
};
