export default {
  entity: {
    id: '61cd9fc8-4f3e-4426-9e07-827440d94115',
    name: '红旗一九七三年第八期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/61cd9fc8-4f3e-4426-9e07-827440d94115.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '重视上层建筑领域的革命',
        authors: ['黎坚'],
        page_start: 6,
        page_end: 11,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title: '改革大学招生制度的深远意义',
        authors: ['朱研'],
        page_start: 12,
        page_end: 16,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title: '在革命斗争中坚持看书学习',
        authors: ['田志松'],
        page_start: 17,
        page_end: 20,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title: '把“五·七”干校办得更好',
        authors: ['钟文'],
        page_start: 21,
        page_end: 24,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title: '共产党员要永做无产阶级先进分子',
        authors: ['薛仑'],
        page_start: 25,
        page_end: 28,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title: '工厂也要注意培养理论队伍',
        authors: ['中国共产党武汉冶金建筑机械修造厂委员会'],
        page_start: 29,
        page_end: 33,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title: '我们是怎样办农村图书室的？',
        authors: ['中国共产党醴陵县委员会'],
        page_start: 34,
        page_end: 36,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title: '农业科学研究要面向农村',
        authors: ['中国共产党上海市农业科学院委员会'],
        page_start: 37,
        page_end: 40,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title:
          '具有历史意义的战略转变——学习《抗日游击战争的战略问题》的一点体会',
        authors: ['纪博涛'],
        page_start: 41,
        page_end: 45,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title: '认真学习毛主席的十大军事原则',
        authors: ['中国人民解放军昆明部队某团党委会'],
        page_start: 46,
        page_end: 50,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title: '英明的战略部署——学习《关于平津战役的作战方针》',
        authors: ['洪城'],
        page_start: 51,
        page_end: 55,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title: '党委要抓大事',
        authors: ['纪平'],
        page_start: 56,
        page_end: 59,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title: '注意保护森林资源',
        authors: ['华林茂'],
        page_start: 60,
        page_end: 64,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title: '更正',
        authors: ['中共保定地委、中共博野县委调查组'],
        page_start: 64,
        page_end: 64,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title: '搞好农村商业的斗、批、改',
        authors: ['河北东光县燕台购销服务处党支部'],
        page_start: 65,
        page_end: 68,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
      {
        title: '工人群众有无限的创造力——鞍铜第一初轧厂提高开坯能力的调查',
        authors: ['鞍山市革命委员会调查组'],
        page_start: 69,
        page_end: 73,
        dates: [{ year: 1973, month: 8, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/61cd9fc8-4f3e-4426-9e07-827440d94115.pdf',
};
