export default {
  entity: {
    id: '62c6dac1-786b-4b09-ac44-7808f29b007c',
    name: '资本主义是怎样在苏联复辟的（上海人民出版社1975年版）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '革命联盟，上海人民出版社1975年版',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/62c6dac1-786b-4b09-ac44-7808f29b007c.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '译者的话',
        authors: ['上海外国语学院'],
        page_start: 9,
        page_end: 9,
        dates: [{ year: 1975 }],
      },
      {
        title: '前言',
        authors: ['革命联盟'],
        page_start: 13,
        page_end: 18,
        dates: [{ year: 1974, month: 10 }],
      },
      {
        title: '第一章 几个理论问题',
        authors: ['革命联盟'],
        page_start: 19,
        page_end: 38,
        dates: [{ year: 1974, month: 10 }],
      },
      {
        title: '第二章 资本主义复辟的根源和赫鲁晓夫的上台',
        authors: ['革命联盟'],
        page_start: 39,
        page_end: 77,
        dates: [{ year: 1974, month: 10 }],
      },
      {
        title:
          '第三章 勃列日涅夫和柯西金统治下的苏联经济——资本主义生产关系的全面复辟',
        authors: ['革命联盟'],
        page_start: 78,
        page_end: 167,
        dates: [{ year: 1974, month: 10 }],
      },
      {
        title: '第四章 苏联社会帝国主义在全世界',
        authors: ['革命联盟'],
        page_start: 168,
        page_end: 231,
        dates: [{ year: 1974, month: 10 }],
      },
      {
        title: '第五章 苏联社会帝国主义统治下的日常生活',
        authors: ['革命联盟'],
        page_start: 232,
        page_end: 292,
        dates: [{ year: 1974, month: 10 }],
      },
      {
        title: '第六章 苏联人民的回击',
        authors: ['革命联盟'],
        page_start: 293,
        page_end: 326,
        dates: [{ year: 1974, month: 10 }],
      },
      {
        title: '第七章 文化革命和社会主义阶段中的阶级斗争',
        authors: ['革命联盟'],
        page_start: 327,
        page_end: 355,
        dates: [{ year: 1974, month: 10 }],
      },
      {
        title: '第八章 结论——社会帝国主义在苏联出现的意义',
        authors: ['革命联盟'],
        page_start: 356,
        page_end: 370,
        dates: [{ year: 1974, month: 10 }],
      },
      {
        title: '革命联盟简介',
        authors: ['革命联盟'],
        page_start: 371,
        page_end: 372,
        dates: [{ year: 1974, month: 10 }],
      },
      {
        title: '革命联盟简介',
        authors: ['革命联盟'],
        page_start: 371,
        page_end: 372,
        dates: [{ year: 1974, month: 10 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.09, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/62c6dac1-786b-4b09-ac44-7808f29b007c.pdf',
};
