export default {
  entity: {
    id: '65b91eb9-585f-4834-9613-dd9e4d4824a9',
    name: '红旗一九六七年第六期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/65b91eb9-585f-4834-9613-dd9e4d4824a9.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '《修养》的要害是背叛无产阶级专政',
        authors: ['《人民日报》编辑部', '《红旗》杂志编辑部'],
        page_start: 4,
        page_end: 10,
        dates: [{ year: 1967, month: 5, day: 8 }],
      },
      {
        title: '给毛主席的致敬信',
        authors: ['北京市革命委员会'],
        page_start: 11,
        page_end: 13,
        dates: [{ year: 1967, month: 4, day: 20 }],
      },
      {
        title: '周恩来在北京市革命委员会成立大会上的讲话',
        authors: [],
        page_start: 14,
        page_end: 16,
        dates: [{ year: 1967, month: 4, day: 20 }],
      },
      {
        title: '江青在北京市革命委员会成立大会上的讲话',
        authors: ['江青'],
        page_start: 17,
        page_end: 19,
        dates: [{ year: 1967, month: 4, day: 20 }],
      },
      {
        title: '谢富治在北京市革命委员会成立大会上的讲话',
        authors: ['谢富治'],
        page_start: 20,
        page_end: 25,
        dates: [{ year: 1967, month: 4, day: 20 }],
      },
      {
        title:
          '谈京剧革命——一九六四年七月在京剧现代戏观摩演出人员的座谈会上的讲话',
        authors: ['江青'],
        page_start: 26,
        page_end: 28,
        dates: [{ year: 1964, month: 7 }],
      },
      {
        title: '欢呼京剧革命的伟大胜利',
        authors: ['《红旗》杂志编辑部'],
        page_start: 29,
        page_end: 30,
        dates: [{ year: 1967, month: 5, day: 8 }],
      },
      {
        title: '热烈响应拥军爱民的号召',
        authors: ['《红旗》杂志编辑部'],
        page_start: 31,
        page_end: 32,
        dates: [{ year: 1967 }],
      },
      {
        title: '坚定地同无产阶级革命派站在一起',
        authors: ['潘复生'],
        page_start: 33,
        page_end: 37,
        dates: [{ year: 1967, month: 5, day: 8 }],
      },
      {
        title: '发扬人民军队的光荣传统在无产阶级文化大革命中立新功',
        authors: ['李再含'],
        page_start: 38,
        page_end: 40,
        dates: [{ year: 1967, month: 5, day: 13 }],
      },
      {
        title: '用毛泽东思想支援工业',
        authors: ['解放军某部支援大同煤矿毛泽东思想宣传队'],
        page_start: 41,
        page_end: 45,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1967 }],
      },
      {
        title:
          '毛泽东思想是办好新《文汇报》的灵魂──上海《文汇报》新生后办报的几点经验',
        authors: ['《红旗》杂志编辑部'],
        page_start: 46,
        page_end: 50,
        dates: [{ year: 1967, month: 5, day: 8 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/65b91eb9-585f-4834-9613-dd9e4d4824a9.pdf',
};
