export default {
  entity: {
    id: '66c2cc98-f9a7-4ab6-8281-ac69a7c6b5e8',
    name: '中国的文化大革命与工业组织（中国文化传播出版社2009年8月版）',
    internal: true,
    official: true,
    type: 'pdf',
    author: '夏尔·贝特兰，中国文化传播出版社2009年8月版',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/66c2cc98-f9a7-4ab6-8281-ac69a7c6b5e8.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '作者简介',
        authors: [],
        page_start: 4,
        page_end: 7,
        dates: [{ year: 2009, month: 8 }],
      },
      {
        title: '中文版序',
        authors: ['中国工人研究网'],
        page_start: 8,
        page_end: 15,
        dates: [{ year: 2009, month: 8 }],
      },
      {
        title: '前言',
        authors: ['夏尔·贝特兰'],
        page_start: 18,
        page_end: 20,
        dates: [{ year: 1973, month: 1 }],
      },
      {
        title: '一、针织总厂',
        authors: ['夏尔·贝特兰'],
        page_start: 21,
        page_end: 38,
        dates: [{ year: 1973, month: 1 }],
      },
      {
        title: '二、工业计划',
        authors: ['夏尔·贝特兰'],
        page_start: 38,
        page_end: 51,
        dates: [{ year: 1973, month: 1 }],
      },
      {
        title: '三、苏联劳动分工模式的变革',
        authors: ['夏尔·贝特兰'],
        page_start: 51,
        page_end: 64,
        dates: [{ year: 1973, month: 1 }],
      },
      {
        title: '四、生产关系的革命',
        authors: ['夏尔·贝特兰'],
        page_start: 64,
        page_end: 71,
        dates: [{ year: 1973, month: 1 }],
      },
      {
        title: '后记',
        authors: ['夏尔·贝特兰'],
        page_start: 72,
        page_end: 88,
        dates: [{ year: 1973, month: 1 }],
      },
      {
        title: '附录：《大跃退》节选',
        authors: ['夏尔·贝特兰'],
        page_start: 89,
        page_end: 129,
        dates: [{ year: 1978 }],
      },
    ],
    ocr: {
      standard_paragraph_merge_strategy_threshold: 0.122,
      differential_paragraph_merge_strategy_threshold: 0,
      content_thresholds: [0, 0.072, 0, 0],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/66c2cc98-f9a7-4ab6-8281-ac69a7c6b5e8.pdf',
};
