export default {
  entity: {
    id: '678bf2d4-62a5-482a-ae4b-122bdc1a038c',
    name: '红旗一九六七年第五期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/678bf2d4-62a5-482a-ae4b-122bdc1a038c.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中共中央给全国厂矿企业革命职工、革命干部的信',
        authors: [],
        page_start: 4,
        page_end: 5,
        dates: [{ year: 1967, month: 3, day: 18 }],
      },
      {
        title: '论革命的“三结合”',
        authors: ['《红旗》杂志编辑部'],
        page_start: 6,
        page_end: 9,
        dates: [{ year: 1967 }],
      },
      {
        title: '爱国主义还是卖国主义？评反动影片《清宫秘史》',
        authors: ['戚本禹'],
        page_start: 10,
        page_end: 24,
        dates: [{ year: 1967, month: 3, day: 30 }],
      },
      {
        title: '在干部问题上的资产阶级反动路线必须批判',
        authors: ['《红旗》杂志评论员'],
        page_start: 25,
        page_end: 26,
        dates: [{ year: 1967, month: 3, day: 30 }],
      },
      {
        title:
          '“打击一大片，保护一小撮”是资产阶级反动路线的一个组成部分（一九六六年六、七两月清华大学工作组在干部问题上执行资产阶级反动路线的情况调查）',
        authors: ['《红旗》杂志编辑部调查员'],
        page_start: 27,
        page_end: 31,
        dates: [{ year: 1967, month: 3, day: 30 }],
      },
      {
        title: '放手发动群众，粉碎反革命复辟阴谋',
        authors: ['王效禹'],
        page_start: 32,
        page_end: 34,
        dates: [{ year: 1967, month: 3, day: 30 }],
      },
      {
        title: '跟着毛主席革命到底',
        authors: ['潘复生'],
        page_start: 35,
        page_end: 39,
        dates: [{ year: 1967, month: 3, day: 21 }],
      },
      {
        title: '我们是怎样支持无产阶级革命派的',
        authors: ['梁辑卿', '杜方平', '吴大胜'],
        page_start: 40,
        page_end: 44,
        dates: [{ year: 1967, month: 3 }],
      },
      {
        title: '迎着阶级斗争的大风浪奋勇前进',
        authors: ['林杰'],
        page_start: 45,
        page_end: 48,
        dates: [{ year: 1967, month: 3 }],
      },
      {
        title: '大寨在毛泽东思想的光辉照耀下前进',
        authors: ['陈永贵'],
        page_start: 49,
        page_end: 52,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1967, month: 3 }],
      },
      {
        title: '坚决执行毛主席的干部政策',
        authors: ['黑龙江省依兰县红色造反者'],
        page_start: 53,
        page_end: 57,
        dates: [{ year: 1967 }],
      },
      {
        title: '把革命放在首位',
        authors: ['《红旗》杂志编辑部'],
        page_start: 58,
        page_end: 59,
        dates: [{ year: 1967 }],
      },
      {
        title: '哈尔滨铁路局夺权后运输形势大好',
        authors: [],
        page_start: 59,
        page_end: 61,
        dates: [{ year: 1967 }],
      },
      {
        title:
          '革命统帅生产——山西省军区某部协同太原第一热电厂无产阶级革命派管理工业的基本经验',
        authors: [
          '中国人民解放军山西省军区支援工业工作队',
          '太原第一热电厂革命委员会',
        ],
        page_start: 62,
        page_end: 66,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1967 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/678bf2d4-62a5-482a-ae4b-122bdc1a038c.pdf',
};
