export default {
  entity: {
    id: '6ae9dce1-6f81-4f06-8635-06842e1b9675',
    name: '中华人民共和国史 第六卷 砸烂旧世界——文化大革命的动乱与浩劫（1966-1968）（中文大学2008年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '卜伟华著，中文大学2008年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/6ae9dce1-6f81-4f06-8635-06842e1b9675.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '总序：世纪视野下的中华人民共和国史',
        authors: ['金观涛'],
        page_start: 5,
        page_end: 7,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2007, month: 12 }],
      },
      {
        title: '序言：历史的教训不能忘记',
        authors: ['王年一'],
        page_start: 8,
        page_end: 11,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2005, month: 2, day: 10 }],
      },
      {
        title: '第一章 导火索',
        authors: ['卜伟华'],
        page_start: 21,
        page_end: 92,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第二章 发动',
        authors: ['卜伟华'],
        page_start: 93,
        page_end: 203,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第三章 再发动',
        authors: ['卜伟华'],
        page_start: 205,
        page_end: 289,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第四章 新口号',
        authors: ['卜伟华'],
        page_start: 291,
        page_end: 371,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第五章 夺权',
        authors: ['卜伟华'],
        page_start: 373,
        page_end: 486,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第六章 大批判',
        authors: ['卜伟华'],
        page_start: 487,
        page_end: 543,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第七章 天下大乱',
        authors: ['卜伟华'],
        page_start: 544,
        page_end: 625,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第八章 理还乱',
        authors: ['卜伟华'],
        page_start: 626,
        page_end: 670,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第九章 波澜再起',
        authors: ['卜伟华'],
        page_start: 671,
        page_end: 742,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第十章 “全国一片红”',
        authors: ['卜伟华'],
        page_start: 743,
        page_end: 807,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '后记',
        authors: ['卜伟华'],
        page_start: 808,
        page_end: 818,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2004, month: 12, day: 31 }],
      },
      {
        title: '大事记',
        authors: ['卜伟华'],
        page_start: 819,
        page_end: 823,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '参考文献',
        authors: ['卜伟华'],
        page_start: 824,
        page_end: 840,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '索引',
        authors: ['卜伟华'],
        page_start: 841,
        page_end: 848,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
    ],
    ocr: { content_thresholds: [0.09, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/6ae9dce1-6f81-4f06-8635-06842e1b9675.pdf',
};
