export default {
  entity: {
    id: '6b120776-ef1f-405c-950d-3f361b18fef0',
    name: '关于国际共产主义运动总路线的论战（人民出版社1965年版）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '人民出版社1965年版',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/6b120776-ef1f-405c-950d-3f361b18fef0.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title:
          '关于国际共产主义运动总路线的建议——中国共产党中央委员会对苏联共产党中央委员会一九六三年三月三十日来信的复信',
        authors: ['中国共产党中央委员会'],
        page_start: 8,
        page_end: 57,
        dates: [{ year: 1963, month: 6, day: 14 }],
      },
      {
        title: '苏共领导同我们分歧的由来和发展——评苏共中央的公开信',
        authors: ['《人民日报》编辑部', '《红旗》杂志编辑部'],
        page_start: 58,
        page_end: 102,
        dates: [{ year: 1963, month: 9, day: 6 }],
      },
      {
        title: '关于和平过渡问题的意见提纲',
        authors: [],
        page_start: 103,
        page_end: 106,
        dates: [{ year: 1957, month: 11, day: 10 }],
      },
      {
        title: '中国共产党代表团在布加勒斯特兄弟党会谈上的声明',
        authors: [],
        page_start: 107,
        page_end: 110,
        dates: [{ year: 1960, month: 6, day: 26 }],
      },
      {
        title:
          '中共中央对苏共中央通知书的答复信中关于解决分歧、达到团结的五项建议',
        authors: ['中共中央'],
        page_start: 111,
        page_end: 112,
        dates: [{ year: 1960, month: 9, day: 10 }],
      },
      {
        title: '关于斯大林问题——二评苏共中央的公开信',
        authors: ['《人民日报》编辑部', '《红旗》杂志编辑部'],
        page_start: 114,
        page_end: 136,
        dates: [{ year: 1963, month: 9, day: 13 }],
      },
      {
        title: '南斯拉夫是社会主义国家吗？——三评苏共中央的公开信',
        authors: ['《人民日报》编辑部', '《红旗》杂志编辑部'],
        page_start: 138,
        page_end: 180,
        dates: [{ year: 1963, month: 9, day: 26 }],
      },
      {
        title: '新殖民主义的辩护士——四评苏共中央的公开信',
        authors: ['《人民日报》编辑部', '《红旗》杂志编辑部'],
        page_start: 182,
        page_end: 213,
        dates: [{ year: 1963, month: 10, day: 22 }],
      },
      {
        title: '在战争与和平问题上的两条路线——五评苏共中央的公开信',
        authors: ['《人民日报》编辑部', '《红旗》杂志编辑部'],
        page_start: 214,
        page_end: 248,
        dates: [{ year: 1963, month: 11, day: 19 }],
      },
      {
        title: '两种根本对立的和平共处政策——六评苏共中央的公开信',
        authors: ['《人民日报》编辑部', '《红旗》杂志编辑部'],
        page_start: 250,
        page_end: 289,
        dates: [{ year: 1963, month: 12, day: 12 }],
      },
      {
        title: '苏共领导是当代最大的分裂主义者——七评苏共中央的公开信',
        authors: ['《人民日报》编辑部', '《红旗》杂志编辑部'],
        page_start: 290,
        page_end: 341,
        dates: [{ year: 1964, month: 2, day: 4 }],
      },
      {
        title: '无产阶级革命和赫鲁晓夫修正主义——八评苏共中央的公开信',
        authors: ['《人民日报》编辑部', '《红旗》杂志编辑部'],
        page_start: 342,
        page_end: 391,
        dates: [{ year: 1964, month: 3, day: 31 }],
      },
      {
        title:
          '关于赫鲁晓夫的假共产主义及其在世界历史上的教训——九评苏共中央的公开信',
        authors: ['《人民日报》编辑部', '《红旗》杂志编辑部'],
        page_start: 392,
        page_end: 450,
        dates: [{ year: 1964, month: 7, day: 14 }],
      },
      {
        title: '赫鲁晓夫是怎样下台的',
        authors: ['《红旗》杂志编辑部'],
        page_start: 452,
        page_end: 462,
        dates: [{ year: 1964, month: 11, day: 21 }],
      },
      {
        title: '苏共中央给中共中央的信',
        authors: ['苏联共产党中央委员会'],
        page_start: 466,
        page_end: 493,
        dates: [{ year: 1963, month: 3, day: 30 }],
      },
      {
        title: '苏联共产党中央委员会给苏联各级党组织和全体共产党员的公开信',
        authors: ['苏联共产党中央委员会'],
        page_start: 494,
        page_end: 551,
        dates: [{ year: 1963, month: 7, day: 14 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.077, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/6b120776-ef1f-405c-950d-3f361b18fef0.pdf',
};
