export default {
  entity: {
    id: '6b348e26-051b-407a-9f84-1278001518b5',
    name: '红旗一九六九年第一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/6b348e26-051b-407a-9f84-1278001518b5.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '用毛泽东思想统帅一切',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        page_start: 8,
        page_end: 14,
        dates: [{ year: 1969, month: 1, day: 1 }],
      },
      {
        title: '我国成功地进行了一次新的氢弹爆炸',
        authors: [],
        page_start: 15,
        page_end: 17,
        dates: [{ year: 1968, month: 12, day: 28 }],
      },
      {
        title: '用实际行动迎接“九大”的召开',
        authors: ['王秀珍'],
        page_start: 18,
        page_end: 21,
        dates: [{ year: 1969 }],
      },
      {
        title: '沿着毛主席的革命路线胜利前进',
        authors: ['洪华'],
        page_start: 21,
        page_end: 23,
        dates: [{ year: 1969 }],
      },
      {
        title: '毛主席自力更生的光辉思想给我们无穷的力量',
        authors: ['郭凤莲'],
        page_start: 24,
        page_end: 26,
        dates: [{ year: 1969 }],
      },
      {
        title: '热情做好下乡知识青年再教育的工作',
        authors: ['林英兵', '任卫东'],
        page_start: 27,
        page_end: 29,
        dates: [{ year: 1969 }],
      },
      {
        title: '同工人结合一辈子',
        authors: ['潘玉铭'],
        page_start: 30,
        page_end: 32,
        dates: [{ year: 1969 }],
      },
      {
        title: '一个受工农兵欢迎的新型商店',
        authors: [
          '天津市汉沽区革委会',
          '天津市汉沽区商业革委会',
          '天津汉沽驻军支左联络站',
        ],
        page_start: 33,
        page_end: 37,
        dates: [{ year: 1969 }],
      },
      {
        title: '广东省、曲江县、群星大队坚持合作医疗制度十一年的情况调查',
        authors: ['广东省革委会', '韶关专区革委会', '曲江县革委会'],
        page_start: 38,
        page_end: 45,
        dates: [{ year: 1969 }],
      },
      {
        title:
          '一支能工能农的农村水电技术队伍是怎样成长的——贵州省乌当区东风公社的调查报告',
        authors: ['东风公社革委会', '乌当区革委会', '新贵州报'],
        page_start: 46,
        page_end: 50,
        dates: [{ year: 1969 }],
      },
      {
        title: '英雄的鲜血与叛徒的恐惧',
        authors: ['苏联“为在苏联重建马克思列宁主义政党而斗争的战士委员会”'],
        page_start: 51,
        page_end: 57,
        dates: [{ year: 1969 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/6b348e26-051b-407a-9f84-1278001518b5.pdf',
};
