export default {
  entity: {
    id: '6b469ced-4f61-48c9-9d0b-550abebe4102',
    name: '简明世界史（现代部分）（北京大学历史系1975年版）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '北京大学历史系1974年版',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/6b469ced-4f61-48c9-9d0b-550abebe4102.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '编者说明',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 3,
        page_end: 4,
        dates: [{ year: 1974, month: 8 }],
      },
      {
        title: '现代部分引言',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 11,
        page_end: 13,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '第一章 伟大的俄国十月社会主义革命开辟了人类历史的新纪元',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 15,
        page_end: 41,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '第二章 十月革命后资本主义国家革命运动的高涨',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 42,
        page_end: 74,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '第三章 十月革命后殖民地半殖民地民族解放运动的高涨',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 75,
        page_end: 110,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '第四章 帝国主义的凡尔赛——华盛顿体系 二十年代的国际关系',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 111,
        page_end: 129,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '第五章 苏联社会主义革命和建设的伟大胜利',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 130,
        page_end: 154,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '第六章 资本主义世界的经济危机 各国人民的反法西斯斗争',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 155,
        page_end: 181,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '第七章 三十年代殖民地、半殖民地民族解放运动的发展',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 182,
        page_end: 207,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '第八章 三十年代的国际关系 帝国主义准备世界大战',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 208,
        page_end: 225,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '第九章 第二次世界大战 世界人民反法西斯战争的伟大胜利',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 226,
        page_end: 254,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '大事年表',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 255,
        page_end: 260,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '人名中外文对照表',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 261,
        page_end: 268,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '地名及其他名词中外文对照表',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 269,
        page_end: 278,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '插图',
        authors: ['北京大学历史系简明世界史编写组'],
        page_start: 279,
        page_end: 302,
        dates: [{ year: 1975, month: 10 }],
      },
    ],
    ocr: { content_thresholds: [0.13, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/6b469ced-4f61-48c9-9d0b-550abebe4102.pdf',
};
