export default {
  entity: {
    id: '6e1a1549-f575-4474-a325-6b226c809319',
    name: '红旗一九五九年第十一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/6e1a1549-f575-4474-a325-6b226c809319.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '一切经过试验',
        authors: ['许辛学'],
        page_start: 3,
        page_end: 5,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
      {
        title: '必须优质高产',
        authors: ['许辛学'],
        page_start: 6,
        page_end: 7,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
      {
        title: '认真地多读些书',
        authors: ['施东向'],
        page_start: 8,
        page_end: 10,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
      {
        title: '流动资金、信贷资金及其管理问题',
        authors: ['段云'],
        page_start: 11,
        page_end: 18,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
      {
        title: '关于按劳分配的几个问题',
        authors: ['何均'],
        page_start: 19,
        page_end: 26,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
      {
        title: '价值规律和社会主义制度下价格决定的规律性',
        authors: ['于光远'],
        page_start: 27,
        page_end: 37,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
      {
        title: '历史教学的古与今',
        authors: ['白寿彝'],
        page_start: 38,
        page_end: 46,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
      {
        title: '在“人民资本主义”幌子的背后',
        authors: ['杨重光'],
        page_start: 47,
        page_end: 51,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/6e1a1549-f575-4474-a325-6b226c809319.pdf',
};
