export default {
  entity: {
    id: '71ca7556-6829-4972-a48e-277e38c6dc02',
    name: '超凡领袖的挫败——文化大革命在武汉（中文大学出版社2009年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '王绍光著，王红绩译，中文大学出版社2009年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/71ca7556-6829-4972-a48e-277e38c6dc02.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '自序',
        authors: ['王绍光'],
        page_start: 4,
        page_end: 7,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.5,
          content_thresholds: [0.09, 0, 0, 0],
        },
        dates: [{ year: 2008, month: 10, day: 12 }],
      },
      {
        title: '英文原著序言',
        authors: ['王绍光'],
        page_start: 8,
        page_end: 9,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.5,
          content_thresholds: [0.09, 0, 0, 0],
        },
        dates: [{ year: 2009 }],
      },
      {
        title: '翻译说明',
        authors: ['王红绩'],
        page_start: 9,
        page_end: 9,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.5,
          content_thresholds: [0.09, 0, 0, 0],
        },
        dates: [{ year: 2009 }],
      },
      {
        title: '第一章 诸论',
        authors: ['王绍光'],
        page_start: 10,
        page_end: 30,
        dates: [{ year: 2009 }],
      },
      {
        title: '第二章 分歧的根源，1949—1966年',
        authors: ['王绍光'],
        page_start: 32,
        page_end: 60,
        dates: [{ year: 2009 }],
      },
      {
        title: '第三章 旧游戏与新牺牲者，1966年6—7月',
        authors: ['王绍光'],
        page_start: 62,
        page_end: 75,
        dates: [{ year: 2009 }],
      },
      {
        title: '第四章 新游戏与新玩家，1966年8—12月',
        authors: ['王绍光'],
        page_start: 76,
        page_end: 98,
        dates: [{ year: 2009 }],
      },
      {
        title: '第五章 派性剖析',
        authors: ['王绍光'],
        page_start: 100,
        page_end: 114,
        dates: [{ year: 2009 }],
      },
      {
        title: '第六章 保守派与造反派之间的冲突，1967年1-4月',
        authors: ['王绍光'],
        page_start: 116,
        page_end: 133,
        dates: [{ year: 2009 }],
      },
      {
        title: '第七章 保守派与造反派之间的冲突，1967年5-7月',
        authors: ['王绍光'],
        page_start: 134,
        page_end: 158,
        dates: [{ year: 2009 }],
      },
      {
        title: '第八章 造反派之间的冲突，1967年8-12月',
        authors: ['王绍光'],
        page_start: 160,
        page_end: 176,
        dates: [{ year: 2009 }],
      },
      {
        title: '第九章 造反派之间的冲突，1968年',
        authors: ['王绍光'],
        page_start: 178,
        page_end: 199,
        dates: [{ year: 2009 }],
      },
      {
        title: '第十章 1969-1973年间的派别斗争',
        authors: ['王绍光'],
        page_start: 200,
        page_end: 215,
        dates: [{ year: 2009 }],
      },
      {
        title: '第十一章 1974-1976年间的派别斗争',
        authors: ['王绍光'],
        page_start: 216,
        page_end: 249,
        dates: [{ year: 2009 }],
      },
      {
        title: '第十二章 超凡领袖的挫败',
        authors: ['王绍光'],
        page_start: 250,
        page_end: 264,
        dates: [{ year: 2009 }],
      },
      {
        title: '附录 受访者情况',
        authors: ['王绍光'],
        page_start: 265,
        page_end: 268,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.5,
          content_thresholds: [0.09, 0, 0, 0],
        },
        dates: [{ year: 2009 }],
      },
      {
        title: '注释',
        authors: ['王绍光'],
        page_start: 268,
        page_end: 287,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.5,
          content_thresholds: [0.09, 0, 0, 0],
        },
        dates: [{ year: 2009 }],
      },
      {
        title: '参考书目',
        authors: ['王绍光'],
        page_start: 287,
        page_end: 293,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.5,
          content_thresholds: [0.09, 0, 0, 0],
        },
        dates: [{ year: 2009 }],
      },
    ],
    ocr: { content_thresholds: [0.09, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/71ca7556-6829-4972-a48e-277e38c6dc02.pdf',
};
