export default {
  entity: {
    id: '73c3138d-e033-4176-89fb-545a5ab0b781',
    name: '红旗一九六五年第十二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/73c3138d-e033-4176-89fb-545a5ab0b781.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '驳苏共新领导的所谓“联合行动”',
        authors: ['人民日报编辑部', '红旗杂志编辑部'],
        page_start: 3,
        page_end: 19,
        dates: [{ year: 1965 }],
      },
      {
        title: '活学活用毛泽东思想——王杰同志日记选',
        authors: ['王杰'],
        page_start: 20,
        page_end: 30,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '为共产主义事业献出一切——读王杰同志的日记',
        authors: ['关锋'],
        page_start: 31,
        page_end: 35,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '工农兵业余创作队伍在成长',
        authors: ['荀常'],
        page_start: 36,
        page_end: 37,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '农民欢迎革命小戏',
        authors: ['文文宣'],
        page_start: 37,
        page_end: 38,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '充足理由律在形式逻辑中的地位和作用',
        authors: ['邵友勋'],
        page_start: 39,
        page_end: 42,
        dates: [{ year: 1965 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '大庆通信——从职工家属闹革命的一些平凡事说起',
        authors: ['孙维世'],
        page_start: 43,
        page_end: 51,
        dates: [{ year: 1965, month: 10 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
    ],
    ocr: { content_thresholds: [0.07, 0.165, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/73c3138d-e033-4176-89fb-545a5ab0b781.pdf',
};
