export default {
  entity: {
    id: '755b194a-3e40-4ebf-831a-2d1f656ee30e',
    name: '学习与批判一九七三年第三期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《学习与批判》编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/755b194a-3e40-4ebf-831a-2d1f656ee30e.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '正确认识路线斗争的长期性——学习《矛盾论》的一点体会',
        authors: ['方海'],
        page_start: 5,
        page_end: 8,
        dates: [{ year: 1973 }],
      },
      {
        title: '认清无产阶级的历史使命',
        authors: ['复旦大学国际政治系'],
        page_start: 9,
        page_end: 11,
        dates: [{ year: 1973 }],
      },
      {
        title: '从发展不平衡看帝国主义的战争本质',
        authors: ['金士靖'],
        page_start: 12,
        page_end: 16,
        dates: [{ year: 1973 }],
      },
      {
        title: '资产阶级与儒法论争',
        authors: ['《中国近代史丛书》编写组'],
        page_start: 17,
        page_end: 25,
        dates: [{ year: 1973 }],
      },
      {
        title: '《天演论》和中国近代反孔思潮',
        authors: ['金冲及'],
        page_start: 26,
        page_end: 31,
        dates: [{ year: 1973 }],
      },
      {
        title: '从反儒尊法到尊孔读经——试论章太炎思想的演变过程',
        authors: ['沈濮'],
        page_start: 31,
        page_end: 36,
        dates: [{ year: 1973 }],
      },
      {
        title: '尊孔与卖国之间——从鲁迅对胡适的一场斗争谈起',
        authors: ['秋雨'],
        page_start: 37,
        page_end: 39,
        dates: [{ year: 1973 }],
      },
      {
        title: '解决矛盾要靠正确的路线',
        authors: ['巩学庆'],
        page_start: 40,
        page_end: 41,
        dates: [{ year: 1973 }],
      },
      {
        title: '做完善社会主义生产关系的促进派',
        alias: '上海部分财政专管员座谈会',
        authors: ['许元冲', '胡逸民', '吴煜延', '韩忠琛', '钱力行'],
        page_start: 42,
        page_end: 45,
        dates: [{ year: 1973 }],
        ocr: { vsplit: 0.4 },
      },
      {
        title: '集中兵力打好歼灭战',
        authors: ['上海闵行“一二五”工程指挥组'],
        page_start: 46,
        page_end: 49,
        dates: [{ year: 1973 }],
      },
      {
        title: '美国“能源危机”是怎么回事？',
        authors: [],
        page_start: 55,
        page_end: 56,
        dates: [{ year: 1973 }],
      },
      {
        title: '前进的步伐——短篇小说集《碧水长流》序',
        authors: ['方泽生'],
        page_start: 57,
        page_end: 59,
        dates: [{ year: 1973 }],
      },
      {
        title: '阳光和土壤',
        authors: ['段瑞夏', '林正义'],
        page_start: 60,
        page_end: 63,
        dates: [{ year: 1973 }],
      },
      {
        title: '儿童文艺创作漫谈——彩色美术影片《小号手》、《东海小哨兵》观后',
        authors: ['边善基', '陆寿钧'],
        page_start: 64,
        page_end: 67,
        dates: [{ year: 1973 }],
      },
      {
        title: '评晴雯的反抗性格——《红楼梦》人物批判之一',
        authors: ['任犊'],
        page_start: 68,
        page_end: 70,
        dates: [{ year: 1973 }],
      },
      {
        title: '试论雅各宾派的历史作用',
        authors: ['上海师范大学《世界近代史》编写组'],
        page_start: 71,
        page_end: 76,
        dates: [{ year: 1973 }],
      },
      {
        title: '希特勒的声东击西政策',
        authors: ['童澈'],
        page_start: 77,
        page_end: 79,
        dates: [{ year: 1973 }],
      },
      {
        title: '在阿登纳笔下',
        authors: ['史坚斌'],
        page_start: 80,
        page_end: 81,
        dates: [{ year: 1973 }],
      },
      {
        title: '要取得共同的语言',
        authors: ['吕广杰'],
        page_start: 82,
        page_end: 83,
        dates: [{ year: 1973 }],
      },
      {
        title: '虚心向群众学习',
        authors: ['黄秀文'],
        page_start: 83,
        page_end: 85,
        dates: [{ year: 1973 }],
      },
      {
        title: '在反复实践中提高认识增长才干',
        authors: ['周麟昌'],
        page_start: 85,
        page_end: 86,
        dates: [{ year: 1973 }],
      },
      {
        title: '结合社会调查学习马克思主义哲学',
        authors: ['复旦大学哲学系'],
        page_start: 87,
        page_end: 91,
        dates: [{ year: 1973 }],
      },
      {
        title: '邹容传',
        authors: ['陈今'],
        page_start: 92,
        page_end: 98,
        dates: [{ year: 1973 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.08, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/755b194a-3e40-4ebf-831a-2d1f656ee30e.pdf',
};
