export default {
  entity: {
    id: '76ebed03-69e5-40a7-8e01-d40221462fd1',
    name: '中华人民共和国建国史研究 2（江西人民出版社2009年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '杨奎松著，江西人民出版社2009年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/76ebed03-69e5-40a7-8e01-d40221462fd1.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '前言',
        authors: ['杨奎松'],
        page_start: 8,
        page_end: 14,
        dates: [{ year: 2009, month: 6, day: 25 }],
      },
      {
        title: '第一章 美苏冷战与中国革命',
        authors: ['杨奎松'],
        page_start: 15,
        page_end: 54,
        dates: [{ year: 2009, month: 9 }],
      },
      {
        title: '第二章 美领馆事件与新中国对美政策的确立',
        authors: ['杨奎松'],
        page_start: 55,
        page_end: 84,
        dates: [{ year: 2009, month: 9 }],
      },
      {
        title: '第三章 中苏结盟与中苏两党的民族主义碰撞',
        authors: ['杨奎松'],
        page_start: 85,
        page_end: 100,
        dates: [{ year: 2009, month: 9 }],
      },
      {
        title: '第四章 中国出兵朝鲜的因与果',
        authors: ['杨奎松'],
        page_start: 101,
        page_end: 150,
        dates: [{ year: 2009, month: 9 }],
      },
      {
        title: '第五章 新中国对援越抗法战争的策略演变',
        authors: ['杨奎松'],
        page_start: 151,
        page_end: 180,
        dates: [{ year: 2009, month: 9 }],
      },
      {
        title: '第六章 两次台海危机的由来及其幕后',
        authors: ['杨奎松'],
        page_start: 180,
        page_end: 222,
        dates: [{ year: 2009, month: 9 }],
      },
      {
        title: '第七章 1960年代中国对外政策转向的历史考察',
        authors: ['杨奎松'],
        page_start: 223,
        page_end: 272,
        dates: [{ year: 2009, month: 9 }],
      },
      {
        title: '第八章 中苏边界冲突与中国对美缓和',
        authors: ['杨奎松'],
        page_start: 272,
        page_end: 302,
        dates: [{ year: 2009, month: 9 }],
      },
      {
        title: '第九章 中美和解过程中的中方变奏',
        authors: ['杨奎松'],
        page_start: 303,
        page_end: 326,
        dates: [{ year: 2009, month: 9 }],
      },
      {
        title: '参考文献及资料要目',
        authors: ['杨奎松'],
        page_start: 327,
        page_end: 334,
        dates: [{ year: 2009, month: 9 }],
      },
      {
        title: '图片来源',
        authors: ['杨奎松'],
        page_start: 335,
        page_end: 335,
        dates: [{ year: 2009, month: 9 }],
      },
    ],
    ocr: { content_thresholds: [0.096, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/76ebed03-69e5-40a7-8e01-d40221462fd1.pdf',
};
