export default {
  entity: {
    id: '79da64b8-3433-4da6-9e03-61863d278909',
    name: '毛泽东选集第三卷（人民出版社1991年版）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/79da64b8-3433-4da6-9e03-61863d278909.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '《农村调查》的序言和跋',
        authors: ['毛泽东'],
        page_start: 7,
        page_end: 12,
        dates: [
          { year: 1941, month: 3 },
          { year: 1941, month: 4 },
        ],
      },
      {
        title: '改造我们的学习',
        authors: ['毛泽东'],
        page_start: 13,
        page_end: 21,
        dates: [{ year: 1941, month: 5, day: 19 }],
      },
      {
        title: '揭破远东慕尼黑的阴谋',
        authors: ['毛泽东'],
        page_start: 22,
        page_end: 23,
        dates: [{ year: 1941, month: 5, day: 25 }],
      },
      {
        title: '关于反法西斯的国际统一战线',
        authors: ['毛泽东'],
        page_start: 24,
        page_end: 24,
        dates: [{ year: 1941, month: 6, day: 23 }],
      },
      {
        title: '在陕甘宁边区参议会的演说',
        authors: ['毛泽东'],
        page_start: 25,
        page_end: 28,
        dates: [{ year: 1941, month: 11, day: 6 }],
      },
      {
        title: '整顿党的作风',
        authors: ['毛泽东'],
        page_start: 29,
        page_end: 47,
        dates: [{ year: 1942, month: 2, day: 1 }],
      },
      {
        title: '反对党八股',
        authors: ['毛泽东'],
        page_start: 48,
        page_end: 64,
        dates: [{ year: 1942, month: 2, day: 8 }],
      },
      {
        title: '在延安文艺座谈会上的讲话',
        authors: ['毛泽东'],
        page_start: 65,
        page_end: 97,
        dates: [{ year: 1942, month: 5 }],
      },
      {
        title: '一个极其重要的政策',
        authors: ['毛泽东'],
        page_start: 98,
        page_end: 101,
        dates: [{ year: 1942, month: 9, day: 7 }],
      },
      {
        title: '第二次世界大战的转折点',
        authors: ['毛泽东'],
        page_start: 102,
        page_end: 107,
        dates: [{ year: 1942, month: 10, day: 12 }],
      },
      {
        title: '祝十月革命二十五周年',
        authors: ['毛泽东'],
        page_start: 108,
        page_end: 108,
        dates: [{ year: 1942, month: 11, day: 6 }],
      },
      {
        title: '抗日时期的经济问题和财政问题',
        authors: ['毛泽东'],
        page_start: 109,
        page_end: 114,
        dates: [{ year: 1942, month: 12 }],
      },
      {
        title: '关于领导方法的若干问题',
        authors: ['毛泽东'],
        page_start: 115,
        page_end: 120,
        dates: [{ year: 1943, month: 6, day: 1 }],
      },
      {
        title: '质问国民党',
        authors: ['毛泽东'],
        page_start: 121,
        page_end: 127,
        dates: [{ year: 1943, month: 7, day: 12 }],
      },
      {
        title: '开展根据地的减租、生产和拥政爱民运动',
        authors: ['毛泽东'],
        page_start: 128,
        page_end: 131,
        dates: [{ year: 1943, month: 10, day: 1 }],
      },
      {
        title: '评国民党十一中全会和三届二次国民参政会',
        authors: ['毛泽东'],
        page_start: 132,
        page_end: 145,
        dates: [{ year: 1943, month: 10, day: 5 }],
      },
      {
        title: '组织起来',
        authors: ['毛泽东'],
        page_start: 146,
        page_end: 154,
        dates: [{ year: 1943, month: 11, day: 29 }],
      },
      {
        title: '学习和时局',
        authors: ['毛泽东'],
        page_start: 155,
        page_end: 169,
        dates: [{ year: 1944, month: 4, day: 12 }],
      },
      {
        title: '附录：关于若干历史问题的决议',
        authors: ['中共中央'],
        page_start: 170,
        page_end: 221,
        dates: [{ year: 1945, month: 2, day: 20 }],
      },
      {
        title: '为人民服务',
        authors: ['毛泽东'],
        page_start: 222,
        page_end: 224,
        dates: [{ year: 1944, month: 9, day: 8 }],
      },
      {
        title: '评蒋介石在双十节的演说',
        authors: ['毛泽东'],
        page_start: 225,
        page_end: 228,
        dates: [{ year: 1944, month: 10, day: 11 }],
      },
      {
        title: '文化工作中的统一战线',
        authors: ['毛泽东'],
        page_start: 229,
        page_end: 231,
        dates: [{ year: 1944, month: 10, day: 30 }],
      },
      {
        title: '必须学会做经济工作',
        authors: ['毛泽东'],
        page_start: 232,
        page_end: 238,
        dates: [{ year: 1945, month: 1, day: 10 }],
      },
      {
        title: '游击区也能够进行生产',
        authors: ['毛泽东'],
        page_start: 239,
        page_end: 242,
        dates: [{ year: 1945, month: 1, day: 31 }],
      },
      {
        title: '两个中国之命运',
        authors: ['毛泽东'],
        page_start: 243,
        page_end: 246,
        dates: [{ year: 1945, month: 4, day: 23 }],
      },
      {
        title: '论联合政府',
        authors: ['毛泽东'],
        page_start: 247,
        page_end: 318,
        dates: [{ year: 1945, month: 4, day: 24 }],
      },
      {
        title: '愚公移山',
        authors: ['毛泽东'],
        page_start: 319,
        page_end: 322,
        dates: [{ year: 1945, month: 6, day: 11 }],
      },
      {
        title: '论军队生产自给，兼论整风和生产两大运动的重要性',
        authors: ['毛泽东'],
        page_start: 323,
        page_end: 327,
        dates: [{ year: 1945, month: 4, day: 27 }],
      },
      {
        title: '赫尔利和蒋介石的双簧已经破产',
        authors: ['毛泽东'],
        page_start: 328,
        page_end: 331,
        dates: [{ year: 1945, month: 7, day: 10 }],
      },
      {
        title: '评赫尔利政策的危险',
        authors: ['毛泽东'],
        page_start: 332,
        page_end: 334,
        dates: [{ year: 1945, month: 7, day: 12 }],
      },
      {
        title: '给福斯特同志的电报',
        authors: ['毛泽东'],
        page_start: 335,
        page_end: 336,
        dates: [{ year: 1945, month: 7, day: 29 }],
      },
      {
        title: '对日寇的最后一战',
        authors: ['毛泽东'],
        page_start: 337,
        page_end: 338,
        dates: [{ year: 1945, month: 8, day: 9 }],
      },
    ],
    ocr: { content_thresholds: [0.14, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/79da64b8-3433-4da6-9e03-61863d278909.pdf',
};
