export default {
  entity: {
    id: '7c8d92c8-ff3c-4ef9-9190-81b4c2aced20',
    name: '红旗一九七六年第五期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/7c8d92c8-ff3c-4ef9-9190-81b4c2aced20.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中共中央关于华国锋同志任中共中央第一副主席、国务院总理的决议',
        authors: [],
        page_start: 8,
        page_end: 8,
        dates: [{ year: 1976, month: 4, day: 7 }],
      },
      {
        title: '中共中央关于撤销邓小平党内外一切职务的决议',
        authors: [],
        page_start: 9,
        page_end: 9,
        dates: [{ year: 1976, month: 4, day: 7 }],
      },
      {
        title: '天安门广场的反革命政治事件',
        authors: ['《人民日报》工农兵通讯员', '《人民日报》记者'],
        page_start: 10,
        page_end: 12,
        dates: [{ year: 1976, month: 4, day: 8 }],
      },
      {
        title: '吴德在天安门广场的广播讲话',
        alias: '吴德同志在天安门广场广播讲话',
        authors: ['吴德'],
        page_start: 10,
        page_end: 12,
        dates: [{ year: 1976, month: 4, day: 5 }],
      },
      {
        title: '吴德在天安门广场的广播讲话',
        alias: '吴德同志在天安门广场广播讲话',
        authors: ['吴德'],
        page_start: 13,
        page_end: 13,
        dates: [{ year: 1976, month: 4, day: 5 }],
      },
      {
        title: '无产阶级专政的伟大胜利',
        authors: ['池恒'],
        page_start: 14,
        page_end: 18,
        dates: [{ year: 1976, month: 5 }],
      },
      {
        title: '为巩固无产阶级专政而战斗',
        authors: ['首都工人民兵总指挥部'],
        page_start: 19,
        page_end: 23,
        dates: [{ year: 1976, month: 5 }],
      },
      {
        title: '用革命舆论粉碎反革命舆论',
        authors: ['梁效'],
        page_start: 24,
        page_end: 29,
        dates: [{ year: 1976, month: 4, day: 23 }],
      },
      {
        title: '邓小平是天安门广场事件的罪魁祸首',
        authors: ['洪广思'],
        page_start: 30,
        page_end: 33,
        dates: [{ year: 1976, month: 4, day: 23 }],
      },
      {
        title: '阶级敌人是虚弱和孤立的',
        authors: ['魏峡安'],
        page_start: 34,
        page_end: 37,
        dates: [{ year: 1976, month: 5 }],
      },
      {
        title: '邓小平全面背叛马克思主义',
        authors: ['黎章'],
        page_start: 38,
        page_end: 47,
        dates: [{ year: 1976, month: 5 }],
      },
      {
        title: '批判工交战线的修正主义谬论',
        authors: ['钟实'],
        page_start: 48,
        page_end: 55,
        dates: [{ year: 1976, month: 5 }],
      },
      {
        title: '邓小平在体育战线鼓吹什么？',
        authors: ['云力'],
        page_start: 56,
        page_end: 59,
        dates: [{ year: 1976, month: 5 }],
      },
      {
        title:
          '攻击文化大革命就是妄图复辟——批判“运动一来往往伤害老工人和有经验的干部”的反动谬论',
        authors: ['秦焰'],
        page_start: 60,
        page_end: 64,
        dates: [{ year: 1976, month: 5 }],
      },
      {
        title: '“记性”与“本性”',
        authors: ['河北正定县三角村大队贫下中农评论组'],
        page_start: 65,
        page_end: 66,
        dates: [{ year: 1976, month: 5 }],
      },
      {
        title: '“相对依靠”是什么意思？',
        authors: ['济南机车上厂工人评论组'],
        page_start: 67,
        page_end: 68,
        dates: [{ year: 1976, month: 5 }],
      },
      {
        title: '紧紧抓住阶级斗争这个纲',
        authors: ['大寨大队党支部'],
        page_start: 69,
        page_end: 74,
        dates: [{ year: 1976, month: 5 }],
      },
      {
        title: '阶级斗争从来没有熄灭',
        authors: ['吴全清'],
        page_start: 75,
        page_end: 78,
        dates: [{ year: 1976, month: 5 }],
      },
      {
        title: '誓做无产阶级专政的坚强柱石',
        authors: ['北京卫戍区某部六连党支部'],
        page_start: 79,
        page_end: 82,
        dates: [{ year: 1976, month: 5 }],
      },
      {
        title: '毛泽东思想指引我们顶风前进',
        authors: ['小靳庄大队党支部'],
        page_start: 83,
        page_end: 86,
        dates: [{ year: 1976, month: 5 }],
      },
      {
        title: '天安门广场事件说明了什么？',
        authors: ['《人民日报》编辑部'],
        page_start: 87,
        page_end: 89,
        dates: [{ year: 1976, month: 4, day: 18 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/7c8d92c8-ff3c-4ef9-9190-81b4c2aced20.pdf',
};
