export default {
  entity: {
    id: '7ce7d057-df9f-488a-a346-e51aad2051b4',
    name: '红旗一九六四年第二十期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/7ce7d057-df9f-488a-a346-e51aad2051b4.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '我国第一颗原子弹爆炸成功',
        authors: ['新华社'],
        page_start: 3,
        page_end: 3,
        dates: [{ year: 1964, month: 10, day: 16 }],
      },
      {
        title: '中华人民共和国政府声明',
        authors: ['中华人民共和国政府'],
        page_start: 4,
        page_end: 6,
        dates: [{ year: 1964 }],
      },
      {
        title: '中共中央和国务院热烈祝贺首次核试验的巨大胜利',
        authors: ['中共中央', '国务院'],
        page_start: 7,
        page_end: 7,
        dates: [{ year: 1964, month: 10, day: 16 }],
      },
      {
        title:
          '周恩来总理致电世界各国政府首脑——转达我国真服关于召开世界各国首脑会议讨论全面禁止和彻底销毁核武器的建议',
        authors: ['周恩来'],
        page_start: 8,
        page_end: 9,
        dates: [{ year: 1964, month: 10, day: 17 }],
      },
      {
        title: '发扬无产阶级的革命坚持性',
        authors: ['宋任穷'],
        page_start: 10,
        page_end: 14,
        dates: [{ year: 1964 }],
      },
      {
        title:
          '文艺理论阵地上的革命精神和反动精神的斗争——驳周谷城的时代精神“汇合论”',
        authors: ['文文宣'],
        page_start: 15,
        page_end: 24,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '怎样看待妇女问题',
        authors: ['万木春'],
        page_start: 25,
        page_end: 29,
        dates: [{ year: 1964 }],
      },
      {
        title: '一丝不苟',
        authors: ['苏星'],
        page_start: 30,
        page_end: 32,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '论小事和大事',
        authors: ['徐道河'],
        page_start: 32,
        page_end: 33,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '革命责任心和责任制相结合',
        authors: ['李智威'],
        page_start: 34,
        page_end: 35,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '站住脚跟，永不褪色',
        authors: ['原冰'],
        page_start: 36,
        page_end: 39,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
    ],
    ocr: { content_thresholds: [0.07, 0.165, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/7ce7d057-df9f-488a-a346-e51aad2051b4.pdf',
};
