export default {
  entity: {
    id: '7fe1037f-7030-4adc-9f83-2a3d56974670',
    name: '“文革”时期群众组织研究（当代中国出版社2004年）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '叶青著，当代中国出版社2004年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/7fe1037f-7030-4adc-9f83-2a3d56974670.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '序',
        authors: ['汪征鲁'],
        page_start: 5,
        page_end: 11,
        dates: [{ year: 2004, month: 3 }],
      },
      {
        title: '绪论',
        authors: ['叶青'],
        page_start: 12,
        page_end: 26,
        dates: [{ year: 2004, month: 3 }],
      },
      {
        title: '第一章 中国共产党与群众运动、群众组织',
        authors: ['叶青'],
        page_start: 27,
        page_end: 43,
        dates: [{ year: 2004, month: 3 }],
      },
      {
        title: '第二章 福建群众组织的产生',
        authors: ['叶青'],
        page_start: 44,
        page_end: 77,
        dates: [{ year: 2004, month: 3 }],
      },
      {
        title: '第三章 福建群众严重对立的出现与群众组织的发展',
        authors: ['叶青'],
        page_start: 78,
        page_end: 113,
        dates: [{ year: 2004, month: 3 }],
      },
      {
        title: '第四章 红卫兵“大串连”与福建群众组织的进一步发展',
        authors: ['叶青'],
        page_start: 114,
        page_end: 130,
        dates: [{ year: 2004, month: 3 }],
      },
      {
        title:
          '第五章 福建省“八·二九”革命造反总司令部——“一月风暴”夺权行动中福建群众组织的短暂联合',
        authors: ['叶青'],
        page_start: 131,
        page_end: 149,
        dates: [{ year: 2004, month: 3 }],
      },
      {
        title: '第六章 “文革”的深入与群众组织“拥军”与“反军”对立',
        authors: ['叶青'],
        page_start: 150,
        page_end: 198,
        dates: [{ year: 2004, month: 3 }],
      },
      {
        title: '第七章 “文化大革命”的新形势与福建群众组织演变的加速',
        authors: ['叶青'],
        page_start: 199,
        page_end: 260,
        dates: [{ year: 2004, month: 3 }],
      },
      {
        title: '第八章 “革命大联合”前后群众组织重新整合',
        authors: ['叶青'],
        page_start: 261,
        page_end: 281,
        dates: [{ year: 2004, month: 3 }],
      },
      {
        title: '第九章 “福建省革委会”的产生与群众组织的消亡',
        authors: ['叶青'],
        page_start: 282,
        page_end: 292,
        dates: [{ year: 2004, month: 3 }],
      },
      {
        title: '第十章 “文革”时期福建群众组织特征及对立演变的分析',
        authors: ['叶青'],
        page_start: 293,
        page_end: 307,
        dates: [{ year: 2004, month: 3 }],
      },
      {
        title: '结语 “文化大革命”群众组织研究的若干思考',
        authors: ['叶青'],
        page_start: 308,
        page_end: 310,
        dates: [{ year: 2004, month: 3 }],
      },
      {
        title: '参考文献 312',
        authors: ['叶青'],
        page_start: 311,
        page_end: 326,
        dates: [{ year: 2004, month: 3 }],
      },
      {
        title: '附录：大、中专院校红卫兵组织 328',
        authors: ['叶青'],
        page_start: 327,
        page_end: 384,
        dates: [{ year: 2004, month: 3 }],
      },
    ],
    ocr: {
      standard_paragraph_merge_strategy_threshold: 0.171,
      differential_paragraph_merge_strategy_threshold: 0,
      content_thresholds: [0, 0, 0, 0],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/7fe1037f-7030-4adc-9f83-2a3d56974670.pdf',
};
