export default {
  entity: {
    id: '81a443cc-c92d-4df4-a996-3e07628a29e7',
    name: '红旗一九七一年第一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/81a443cc-c92d-4df4-a996-3e07628a29e7.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '沿着毛主席革命路线胜利前进',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        page_start: 8,
        page_end: 12,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title: '狠抓两条路线斗争教育',
        authors: ['中国共产党北京新华印刷厂委员会'],
        page_start: 13,
        page_end: 16,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title: '大赛的道路宽又广',
        authors: ['山东曲阜县夏家村大队党支部'],
        page_start: 17,
        page_end: 22,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title: '紧跟毛主席 航行千万里',
        authors: ['中国人民解放军海军北海舰队某部八十二号护卫艇党支部'],
        page_start: 23,
        page_end: 27,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title: '毛主席的革命路线是翻身奴隶的生命线',
        authors: ['吉牛布哈'],
        page_start: 28,
        page_end: 32,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title:
          '在斗争中提高路线觉悟——始终抓往两个阶级、两条道路、两条路线斗争这个纲',
        authors: ['姚文绪'],
        page_start: 33,
        page_end: 37,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title: '正确对待群众',
        authors: ['方敏'],
        page_start: 37,
        page_end: 40,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title: '进一步加强党的民主集中制',
        authors: ['中国共产党湖南省委员会写作小组'],
        page_start: 41,
        page_end: 45,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title: '继续认真搞好斗、批、改',
        authors: ['江汉文'],
        page_start: 46,
        page_end: 50,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title: '学好辩证唯物论的认识论',
        authors: ['金海'],
        page_start: 51,
        page_end: 53,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title: '认识和掌握阶级斗争的规律性',
        authors: ['尹中奇'],
        page_start: 54,
        page_end: 59,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title: '从实践中掌握地下油水运动规律',
        authors: ['大庆油田采油中二队工人学哲学小纽'],
        page_start: 60,
        page_end: 63,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title: '革命实践必须执行革命路线',
        authors: ['王恩文'],
        page_start: 64,
        page_end: 69,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title: '掌握行车规律 保证安全正点',
        authors: ['田维荣'],
        page_start: 70,
        page_end: 73,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title: '运用辩证法落实农业“八字宪法”',
        authors: ['刘应祥'],
        page_start: 73,
        page_end: 76,
        dates: [{ year: 1971, month: 1, day: 1 }],
      },
      {
        title: '波兰人民的革命风暴',
        authors: ['《人民日报》评论员'],
        page_start: 77,
        page_end: 78,
        dates: [{ year: 1970, month: 12, day: 22 }],
      },
      {
        title:
          '坦克的履带镇压不了波兰人民的愤怒和仇恨——阿尔巴尼亚《人民之声报》发表文章盛赞波兰人民反抗波修集团的英勇斗争',
        authors: ['新华社'],
        page_start: 79,
        page_end: 81,
        dates: [{ year: 1970, month: 12, day: 20 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/81a443cc-c92d-4df4-a996-3e07628a29e7.pdf',
};
