export default {
  entity: {
    id: '88f520b7-44ae-43c9-aa69-f423675e6271',
    name: '红旗一九六〇年第十四期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/88f520b7-44ae-43c9-aa69-f423675e6271.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '广泛开展支援农业的群众运动',
        authors: ['江渭清'],
        page_start: 3,
        page_end: 10,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 7 }],
      },
      {
        title: '论群众性的经济核算',
        authors: ['曾直'],
        page_start: 11,
        page_end: 18,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 7 }],
      },
      {
        title: '人人核算 个个理财',
        authors: ['中共成都量具刀具厂委员会'],
        page_start: 19,
        page_end: 23,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 7 }],
      },
      {
        title: '工业基地也能够做到蔬菜自给',
        authors: ['黄达'],
        page_start: 24,
        page_end: 28,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 7 }],
      },
      {
        title: '不断前进的天津光复道商店',
        authors: ['马秀中'],
        page_start: 29,
        page_end: 36,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 7 }],
      },
      {
        title: '深入实际 深入群众',
        authors: ['林一舟'],
        page_start: 37,
        page_end: 38,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 7 }],
      },
      {
        title: '水乡探胜',
        authors: ['陈残云'],
        page_start: 39,
        page_end: 43,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 7 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/88f520b7-44ae-43c9-aa69-f423675e6271.pdf',
};
