export default {
  entity: {
    id: '89b23e69-8611-4fde-a2db-202a777e70bb',
    name: '武汉“七二〇”事件实录（中国文化传播出版社2017年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '徐海亮，中国文化传播出版社2017年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/89b23e69-8611-4fde-a2db-202a777e70bb.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '《武汉“七二〇”事件实录》增订版说明',
        authors: ['徐海亮'],
        page_start: 51,
        page_end: 54,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '武汉“文革”的口碑历史',
        authors: ['王海光'],
        page_start: 55,
        page_end: 63,
        dates: [{ year: 2010, month: 9, day: 3 }],
      },
      {
        title: '《东海风云录》书稿自序',
        authors: ['徐海亮'],
        page_start: 64,
        page_end: 71,
        dates: [{ year: 2008, month: 2 }],
      },
      {
        title: '写在前面',
        authors: ['徐海亮'],
        page_start: 76,
        page_end: 71,
        dates: [{ year: 2010, month: 2 }],
      },
      {
        title: '7月13日前夕',
        authors: ['徐海亮'],
        page_start: 81,
        page_end: 87,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月14日',
        authors: ['徐海亮'],
        page_start: 88,
        page_end: 93,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月15日',
        authors: ['徐海亮'],
        page_start: 94,
        page_end: 100,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月16日',
        authors: ['徐海亮'],
        page_start: 94,
        page_end: 106,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月17日',
        authors: ['徐海亮'],
        page_start: 107,
        page_end: 115,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月18日',
        authors: ['徐海亮'],
        page_start: 116,
        page_end: 133,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月19日',
        authors: ['徐海亮'],
        page_start: 134,
        page_end: 154,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月20日（一）',
        authors: ['徐海亮'],
        page_start: 155,
        page_end: 189,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月20日（二）',
        authors: ['徐海亮'],
        page_start: 190,
        page_end: 219,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月21日',
        authors: ['徐海亮'],
        page_start: 220,
        page_end: 241,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月22日',
        authors: ['徐海亮'],
        page_start: 242,
        page_end: 254,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月23日',
        authors: ['徐海亮'],
        page_start: 255,
        page_end: 265,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月24日',
        authors: ['徐海亮'],
        page_start: 266,
        page_end: 276,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月25日',
        authors: ['徐海亮'],
        page_start: 277,
        page_end: 287,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月26日',
        authors: ['徐海亮'],
        page_start: 288,
        page_end: 295,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月27日',
        authors: ['徐海亮'],
        page_start: 296,
        page_end: 307,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月28日',
        authors: ['徐海亮'],
        page_start: 308,
        page_end: 323,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '7月29日',
        authors: ['徐海亮'],
        page_start: 324,
        page_end: 327,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '1967年1月1日至7月12日大事记',
        authors: ['徐海亮'],
        page_start: 328,
        page_end: 379,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '周恩来处理武汉“七二〇事件”（上）',
        authors: ['徐海亮'],
        page_start: 380,
        page_end: 411,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '周恩来处理武汉“七二〇事件”（下）',
        authors: ['徐海亮'],
        page_start: 412,
        page_end: 451,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '1967年“武汉事件”及其在文革进程中的位置',
        authors: ['徐海亮'],
        page_start: 452,
        page_end: 511,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '关于武汉地区当前局势的声明（二八声明）',
        authors: ['《长江日报》'],
        page_start: 512,
        page_end: 518,
        dates: [{ year: 1967, month: 2, day: 8 }],
      },
      {
        title: '中国人民解放军武汉部队严正声明（二一八声明）',
        authors: ['中国人民解放军武汉部队'],
        page_start: 519,
        page_end: 521,
        dates: [{ year: 1967, month: 2, day: 18 }],
      },
      {
        title: '中国人民解放军武汉部队通告（三二一通告）',
        authors: ['中国人民解放军武汉部队'],
        page_start: 521,
        page_end: 527,
        dates: [{ year: 1967, month: 3, day: 21 }],
      },
      {
        title:
          '中共中央对河南省军区党委《关于支左工作中所犯错误的检查报告》的批示（附《检查报告》）',
        authors: ['中国人民解放军武汉部队'],
        page_start: 528,
        page_end: 533,
        dates: [{ year: 1967, month: 7, day: 10 }],
      },
      {
        title: '中共中央对《中国人民解放军武汉军区公告》的复电（附《公告》）',
        authors: ['中国人民解放军武汉部队'],
        page_start: 533,
        page_end: 539,
        dates: [{ year: 1967, month: 7, day: 26 }],
      },
      {
        title: '1967年11月30日陈再道的口头检查',
        authors: ['陈再道'],
        page_start: 540,
        page_end: 569,
        dates: [{ year: 1967, month: 11, day: 30 }],
      },
      {
        title: '1967年12月3日陈再道的书面检查',
        authors: ['陈再道'],
        page_start: 569,
        page_end: 570,
        dates: [{ year: 1967, month: 12, day: 3 }],
      },
      {
        title: '1967年12月1日钟汉华的口头检查（摘录）',
        authors: ['钟汉华'],
        page_start: 571,
        page_end: 574,
        dates: [{ year: 1967, month: 12, day: 1 }],
      },
      {
        title: '武汉军区、湖北省军区独立师领导人简介',
        authors: ['徐海亮'],
        page_start: 574,
        page_end: 578,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '“武汉事件”相关群众组织简介',
        authors: ['徐海亮'],
        page_start: 578,
        page_end: 581,
        dates: [{ year: 2017, month: 4 }],
      },
      {
        title: '“百万雄师”总站常委概况一览表',
        authors: ['徐海亮'],
        page_start: 581,
        page_end: 582,
        dates: [{ year: 2017, month: 4 }],
      },
    ],
    ocr: {
      standard_paragraph_merge_strategy_threshold: 0.174,
      differential_paragraph_merge_strategy_threshold: 0,
      content_thresholds: [0.114, 0.072, 0, 0],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/89b23e69-8611-4fde-a2db-202a777e70bb.pdf',
};
