export default {
  entity: {
    id: '8a91a197-8c2a-4e8b-9e8a-bbe97afc4f51',
    name: '红旗一九七五年第八期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/8a91a197-8c2a-4e8b-9e8a-bbe97afc4f51.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '搞好农村的社会主义革命——纪念《关于农业合作化问题》发表二十周年',
        authors: ['齐彦'],
        page_start: 6,
        page_end: 11,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '学一点政治经济学',
        authors: ['吴畅'],
        page_start: 12,
        page_end: 14,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '评林彪的卖国哲学',
        authors: ['梁效'],
        page_start: 15,
        page_end: 20,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '进一步加强党的团结',
        authors: ['青岩'],
        page_start: 21,
        page_end: 24,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '理论联系实际 推动学习深入',
        authors: ['池恒'],
        page_start: 25,
        page_end: 27,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '坚持社会主义道路 限制资产阶级法权',
        authors: ['北京平谷县许家务大队党支部'],
        page_start: 28,
        page_end: 31,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '运用理论调查研究农村现状',
        authors: ['江振华'],
        page_start: 32,
        page_end: 35,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '分工虽不同都是主人翁',
        authors: ['上海第五钢铁厂第一车间理论小组'],
        page_start: 36,
        page_end: 37,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '正确处理干部和群众的关系',
        authors: ['中国共产党昆仑机械厂委员会'],
        page_start: 38,
        page_end: 40,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '为建设农村贡献我们的力量',
        authors: ['刘克清', '李解忠', '李典庆', '李维友', '李国坚', '肖坤书'],
        page_start: 41,
        page_end: 43,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '沿着毛主席的无产阶级建军路线前进',
        authors: ['柯史'],
        page_start: 44,
        page_end: 51,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '密切官兵关系的有效措施',
        authors: ['中国人民解放军空军航空兵某师党委会'],
        page_start: 52,
        page_end: 54,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '自觉地经常地向人民群众学习',
        authors: ['中国人民解放军海军某部“洛阳”舰党支部'],
        page_start: 55,
        page_end: 58,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '保持旺盛的革命斗志',
        authors: ['靳志柏'],
        page_start: 59,
        page_end: 61,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '破除外因论 自觉拒腐蚀',
        authors: ['江景宏'],
        page_start: 62,
        page_end: 64,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '领导要敢于负责',
        authors: ['袁青'],
        page_start: 65,
        page_end: 67,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '实践是农业科学发展的源泉',
        authors: ['金枫'],
        page_start: 68,
        page_end: 78,
        dates: [{ year: 1975, month: 8 }],
      },
      {
        title: '苏修鼓吹“三不”主义的目的何在？',
        authors: ['秦景池'],
        page_start: 79,
        page_end: 81,
        dates: [{ year: 1975, month: 8 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/8a91a197-8c2a-4e8b-9e8a-bbe97afc4f51.pdf',
};
