export default {
  entity: {
    id: '8b7404da-fea1-4bd3-ba12-1d7eee5594fc',
    name: '文革通讯第14期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '浙江工农兵美术大学毛泽东主义红卫兵战斗队、毛泽东主义红卫兵',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives15/main/8b7404da-fea1-4bd3-ba12-1d7eee5594fc.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '毛主席说：“好！”',
        authors: ['毛主席'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967, month: 4, day: 26 }],
      },
      {
        title: '好消息',
        authors: ['《文革通讯》编辑部'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967, month: 4, day: 26 }],
      },
      {
        title: '中央首长讲话',
        authors: ['周恩来', '陈伯达', '康生', '江青', '姚文元'],
        page_start: 1,
        page_end: 2,
        dates: [{ year: 1967, month: 4, day: 3 }],
      },
      {
        title: '张春桥、姚文元等同志关于报纸宣传问题的意见',
        authors: ['张春桥', '姚文元'],
        page_start: 2,
        page_end: 3,
        dates: [{ year: 1967, month: 4, day: 12 }],
      },
      {
        title: '北京消息',
        authors: ['《文革通讯》编辑部'],
        page_start: 3,
        page_end: 5,
        dates: [{ year: 1967, month: 4, day: 26 }],
      },
      {
        title: '中央部委动态',
        authors: ['《文革通讯》编辑部'],
        page_start: 5,
        page_end: 6,
        dates: [{ year: 1967, month: 4, day: 26 }],
      },
      {
        title: '坚决击退反革命逆流',
        authors: ['《文革通讯》编辑部'],
        page_start: 6,
        page_end: 6,
        dates: [{ year: 1967, month: 4, day: 26 }],
      },
      {
        title: '把刘少奇的《论共产党员的修养》批倒批臭',
        authors: ['《文革通讯》编辑部'],
        page_start: 7,
        page_end: 7,
        dates: [{ year: 1967, month: 4, day: 26 }],
      },
      {
        title: '打倒刘、邓的新反扑',
        authors: ['《文革通讯》编辑部'],
        page_start: 7,
        page_end: 7,
        dates: [{ year: 1967, month: 4, day: 26 }],
      },
      {
        title: '祖国各地',
        authors: ['《文革通讯》编辑部'],
        page_start: 7,
        page_end: 8,
        dates: [{ year: 1967, month: 4, day: 26 }],
      },
    ],
    ocr: undefined,
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives15/8b7404da-fea1-4bd3-ba12-1d7eee5594fc.pdf',
};
