export default {
  entity: {
    id: '8cd7746c-9698-46ea-be1c-c179aeaad92d',
    name: '无产阶级文化大革命概述简论（第四篇）（水陆洲2012年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '水陆洲编',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/8cd7746c-9698-46ea-be1c-c179aeaad92d.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '无产阶级文化大革命概述简论第四篇 概述',
        authors: ['水陆洲'],
        page_start: 4,
        page_end: 77,
        dates: [{ year: 2012, month: 8, day: 19 }],
      },
      {
        title: '第一章 学习无产阶级专政的理论 第一节 学理论 抓路线 促生产',
        authors: ['水陆洲'],
        page_start: 78,
        page_end: 85,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title:
          '第一章 学习无产阶级专政的理论 第二节 学习毛主席关于理论问题的重要指示',
        authors: ['水陆洲'],
        page_start: 86,
        page_end: 105,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第一章 学习无产阶级专政的理论 第三节 召开四届人大',
        authors: ['水陆洲'],
        page_start: 106,
        page_end: 115,
        dates: [{ year: 2012, month: 6, day: 12 }],
      },
      {
        title:
          '第一章 学习无产阶级专政的理论 第四节 毛泽东关于批修正主义的指示',
        authors: ['水陆洲'],
        page_start: 116,
        page_end: 140,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第一章 学习无产阶级专政的理论 第五节《红都女皇》事件',
        authors: ['水陆洲'],
        page_start: 141,
        page_end: 145,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第一章 学习无产阶级专政的理论 第六节 评水浒',
        authors: ['水陆洲'],
        page_start: 146,
        page_end: 157,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第一章 学习无产阶级专政的理论 第七节 落实文艺政策',
        authors: ['水陆洲'],
        page_start: 158,
        page_end: 163,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第一章 学习无产阶级专政的理论 第八节 农业学大寨',
        authors: ['水陆洲'],
        page_start: 164,
        page_end: 172,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第一章 学习无产阶级专政的理论 第九节 落实各类人员政策',
        authors: ['水陆洲'],
        page_start: 173,
        page_end: 176,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第一节 以三项指示为纲',
        authors: ['水陆洲'],
        page_start: 177,
        page_end: 185,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第二节 整顿工业交通',
        authors: ['水陆洲'],
        page_start: 186,
        page_end: 193,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第三节 整顿教育',
        authors: ['水陆洲'],
        page_start: 194,
        page_end: 207,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第四节 整顿中国科学院',
        authors: ['水陆洲'],
        page_start: 208,
        page_end: 218,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第五节 整顿军队',
        authors: ['水陆洲'],
        page_start: 219,
        page_end: 227,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第六节 整顿国防科委系统',
        authors: ['水陆洲'],
        page_start: 228,
        page_end: 262,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第七节 整顿党组织',
        authors: ['水陆洲'],
        page_start: 263,
        page_end: 267,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第八节 各省的整顿',
        authors: ['水陆洲'],
        page_start: 268,
        page_end: 277,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第二章 邓小平的全面整顿 第九节 反击右倾翻案风',
        authors: ['水陆洲'],
        page_start: 278,
        page_end: 304,
        dates: [{ year: 2012, month: 3, day: 12 }],
      },
      {
        title: '第三章 反击右倾翻案风 第一节 一九七六年的形势和任务',
        authors: ['水陆洲'],
        page_start: 305,
        page_end: 315,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第三章 反击右倾翻案风 第二节 继续反击右倾翻案风',
        authors: ['水陆洲'],
        page_start: 316,
        page_end: 354,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第三章 反击右倾翻案风 第三节 周恩来朱德逝世',
        authors: ['水陆洲'],
        page_start: 355,
        page_end: 365,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第三章 反击右倾翻案风 第四节 天安门事件',
        authors: ['水陆洲'],
        page_start: 366,
        page_end: 403,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第四章 毛泽东主席逝世 第一节 毛泽东的政治遗言',
        authors: ['水陆洲'],
        page_start: 404,
        page_end: 406,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第四章 毛泽东主席逝世 第二节 各级党和政府的吊唁活动',
        authors: ['水陆洲'],
        page_start: 407,
        page_end: 420,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第四章 毛泽东主席逝世 第三节 全国人民吊唁毛泽东主席逝世',
        authors: ['水陆洲'],
        page_start: 421,
        page_end: 440,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第四章 毛泽东主席逝世 第四节 各国对毛泽东逝世的吊唁（上）',
        authors: ['水陆洲'],
        page_start: 441,
        page_end: 517,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
      {
        title: '第四章第四节 各国对毛泽东逝世的吊唁（下）',
        authors: ['水陆洲'],
        page_start: 518,
        page_end: 609,
        dates: [{ year: 2012, month: 3, day: 14 }],
      },
    ],
    ocr: {
      standard_paragraph_merge_strategy_threshold: 0.186,
      differential_paragraph_merge_strategy_threshold: 0,
      content_thresholds: [0.054, 0, 0, 0],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/8cd7746c-9698-46ea-be1c-c179aeaad92d.pdf',
};
