export default {
  entity: {
    id: '8d6663d1-3539-4513-9851-4c91a374a489',
    name: '红旗一九七三年第一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/8d6663d1-3539-4513-9851-4c91a374a489.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '新年献词（一九七三年元旦社论）',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        page_start: 8,
        page_end: 11,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '坚持实事求是和群众路线的方法',
        authors: ['甘戈', '庄宁'],
        page_start: 12,
        page_end: 17,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '全心全意地为人民服务',
        authors: ['钟实'],
        page_start: 18,
        page_end: 21,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '千万不要忘记阶级和阶级斗争',
        authors: ['辛永铭'],
        page_start: 22,
        page_end: 25,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '要全面地看问题',
        authors: ['南郁'],
        page_start: 26,
        page_end: 30,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title:
          '用唯物辩证法观察路线斗争——学习《路德维希·费尔巴哈和德国古典哲学的终结》的一点体会',
        authors: ['方兴'],
        page_start: 31,
        page_end: 35,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '永远走与工农相结合的道路',
        authors: ['胡守正'],
        page_start: 36,
        page_end: 39,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '艰苦奋斗 勤俭办社',
        authors: ['湖北沔阳县榨湾大队党支部'],
        page_start: 40,
        page_end: 43,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '掌握治碱规律 夺取粮棉丰收',
        authors: ['中国共产党新乡县洪门公社委员会'],
        page_start: 44,
        page_end: 49,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '队有储备 户有余粮——山西广灵县翟町大队的调查报告',
        authors: ['中国共产党雁北地区委员会、中国共产党广灵县委员会调查组'],
        page_start: 50,
        page_end: 52,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '实事求是地领导农业生产',
        authors: ['中国共产党榆树县委员会'],
        page_start: 53,
        page_end: 56,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '自力更生办水电——广东梅县办小水电的调查报告',
        authors: ['梅县地区革命委员会调查组'],
        page_start: 57,
        page_end: 59,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '永远发扬艰苦朴素的优良作风',
        authors: ['中国人民解放军南京部队某部高炮三连党支部'],
        page_start: 60,
        page_end: 63,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '在斗争中培养工人干部',
        authors: ['任菁'],
        page_start: 64,
        page_end: 66,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '要深人细致地做思想工作',
        authors: ['金瓯'],
        page_start: 67,
        page_end: 71,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '握紧的拳头有力量',
        authors: ['河南林县元家庄大队党支部'],
        page_start: 72,
        page_end: 73,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
      {
        title: '微积分的理论是怎么来的？',
        authors: ['舒立'],
        page_start: 74,
        page_end: 81,
        dates: [{ year: 1973, month: 1, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/8d6663d1-3539-4513-9851-4c91a374a489.pdf',
};
