export default {
  entity: {
    id: '8dbb9464-25e0-409a-8cd5-f10da05e64f2',
    name: '红旗一九六〇年第四期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/8dbb9464-25e0-409a-8cd5-f10da05e64f2.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '反对美国变日本为战争策源地',
        authors: ['《红旗》杂志评论员'],
        page_start: 3,
        page_end: 5,
        dates: [{ year: 1960, month: 2 }],
      },
      {
        title: '加速农业的技术改造',
        authors: ['陈正人'],
        page_start: 6,
        page_end: 12,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 2 }],
      },
      {
        title: '上海农村的一亩地一头猪运动',
        authors: ['陈丕显'],
        page_start: 13,
        page_end: 18,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 2 }],
      },
      {
        title: '我国水产事业高速度发展的道路',
        authors: ['高文华'],
        page_start: 19,
        page_end: 24,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 2 }],
      },
      {
        title: '发动群众，不断解决生产中的关键问题',
        authors: ['王树成'],
        page_start: 25,
        page_end: 29,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 2 }],
      },
      {
        title: '从奴隶制度飞跃到社会主义——凉山彝族的昨天和今天',
        authors: ['刘万邦'],
        page_start: 30,
        page_end: 38,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 2 }],
      },
      {
        title: '思维和存在没有同一性吗？——和世诚同志商榷',
        authors: ['王若水'],
        page_start: 39,
        page_end: 48,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 2 }],
      },
      {
        title: '正确的判断和坚强的决心',
        authors: ['谢克东', '苏群'],
        page_start: 49,
        page_end: 51,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 2 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/8dbb9464-25e0-409a-8cd5-f10da05e64f2.pdf',
};
