export default {
  entity: {
    id: '8e6be60c-f1a8-4eb9-9d55-43449ad516cc',
    name: '红旗一九七三年第二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/8e6be60c-f1a8-4eb9-9d55-43449ad516cc.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '毛泽东等祝贺《越南问题的巴黎协定》正式签订的电报',
        alias:
          '热烈祝贺关于越南问题的巴黎协定正式签订——毛主席董代主席朱委员长周总理致电孙德胜主席黎笋第一书记长征主席范文同总理和阮友寿主席黄晋发主席',
        authors: ['毛泽东'],
        page_start: 6,
        page_end: 7,
        dates: [{ year: 1973, month: 1, day: 29 }],
      },
      {
        title: '党的建设必须密切联系党的政治路线——学习《<共产党人>发刊词》',
        authors: ['俞彤'],
        page_start: 8,
        page_end: 13,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '要统筹兼顾——学习《关于正确处理人民内部矛盾的问题》',
        authors: ['云岚'],
        page_start: 14,
        page_end: 18,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '“灵魂深处爆发革命”是黑《修养》的翻版',
        authors: ['天津铁路分局天津站工人评论组'],
        page_start: 19,
        page_end: 22,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '坚持辩证唯物论和党性的统一',
        authors: ['宜江'],
        page_start: 23,
        page_end: 25,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '解决思想间题不能“雷厉风行”',
        authors: ['中国人民解放军北京卫戍区某部一连党支部'],
        page_start: 26,
        page_end: 28,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '把认识路线搞正确',
        authors: ['吕玉兰'],
        page_start: 29,
        page_end: 31,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '谈谈科学种田',
        authors: ['陈永贵'],
        page_start: 32,
        page_end: 41,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '用总路线的精神办钢铁工业——上海市多快好省发展钢铁生产的调查报告',
        authors: ['冶金工业部调查组'],
        page_start: 42,
        page_end: 47,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '根据工农兵的需要办商店',
        authors: ['北京市东直门外副食品商店党支部'],
        page_start: 48,
        page_end: 51,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '为社会主义建设多作贡献',
        authors: ['大连机床厂革命委员会'],
        page_start: 52,
        page_end: 55,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '抓好粮食生产和多种经营',
        authors: ['陆严'],
        page_start: 56,
        page_end: 60,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '做好青年的思想工作',
        authors: ['共青团上海第三钢铁厂委员会'],
        page_start: 61,
        page_end: 66,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '破旧俗 立新风',
        authors: ['中国共产党启东县惠和公社委员会'],
        page_start: 67,
        page_end: 70,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '拍出更多更好的新闻纪录影片',
        authors: ['方亮'],
        page_start: 71,
        page_end: 74,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '一切从人民的利益出发',
        authors: ['中国人民解放军沈阳部队某团党委会'],
        page_start: 75,
        page_end: 78,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
      {
        title: '草原军民 心心相连',
        authors: ['苏荣扎布'],
        page_start: 79,
        page_end: 81,
        dates: [{ year: 1973, month: 2, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/8e6be60c-f1a8-4eb9-9d55-43449ad516cc.pdf',
};
