export default {
  entity: {
    id: '8fa126fb-a252-4e6e-94a6-1f316cadd98c',
    name: '红旗一九五九年第十期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/8fa126fb-a252-4e6e-94a6-1f316cadd98c.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '包产一定要落实',
        authors: ['林一舟'],
        page_start: 3,
        page_end: 4,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 5 }],
      },
      {
        title: '农业生产措施要同群众商量决定',
        authors: ['洪禹'],
        page_start: 5,
        page_end: 8,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 5 }],
      },
      {
        title: '社会主义制度下的商品生产和价值规律',
        authors: ['薛暮桥'],
        page_start: 9,
        page_end: 22,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 5 }],
      },
      {
        title: '目前历史教学中的几个问题',
        authors: ['翦伯赞'],
        page_start: 23,
        page_end: 33,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 5 }],
      },
      {
        title: '为了追求真理',
        authors: ['施东向'],
        page_start: 34,
        page_end: 35,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 5 }],
      },
      {
        title: '关于水电和火电问题的讨论',
        authors: ['李锐'],
        page_start: 36,
        page_end: 46,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 5 }],
      },
      {
        title: '自动化在帝国主义国家里',
        authors: ['杨重光'],
        page_start: 47,
        page_end: 51,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 5 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/8fa126fb-a252-4e6e-94a6-1f316cadd98c.pdf',
};
