export default {
  entity: {
    id: '92e950b6-a53e-4537-87b0-040dd8c11b17',
    name: '自然辩证法一九七六年第一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《自然辩证法》编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/92e950b6-a53e-4537-87b0-040dd8c11b17.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title:
          '沿着毛主席的革命路线奋勇前进——复旦大学、上海师范大学理科教师座谈会纪要',
        authors: ['《自然辩证法》编辑部'],
        page_start: 5,
        page_end: 13,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '开门办科研的道路越走越宽广',
        authors: ['中国科学院上海有机化学研究所革委会'],
        page_start: 14,
        page_end: 22,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '数学理论研究的宽广道路',
        authors: ['苏步青'],
        page_start: 23,
        page_end: 31,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '毛主席哲学思想指导我们发展新光源',
        authors: ['蔡祖泉'],
        page_start: 32,
        page_end: 37,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '华莱士是怎样堕入唯灵论的——学习《自然辩证法》札记',
        authors: ['潘名山'],
        page_start: 38,
        page_end: 46,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '人类的继往开来（续）',
        authors: ['李炳文', '胡波'],
        page_start: 47,
        page_end: 66,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '论用动物血清鉴定人类血型',
        authors: ['薛勤'],
        page_start: 67,
        page_end: 73,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '人体和癌肿',
        authors: ['何仲熹', '钟学哲'],
        page_start: 74,
        page_end: 93,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '对肿瘤的几点认识',
        authors: ['陈世全', '陈世齐'],
        page_start: 94,
        page_end: 99,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '略论免疫学中的几对矛盾',
        authors: ['魏升'],
        page_start: 100,
        page_end: 110,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '把扶正和祛邪有机结合起来',
        authors: ['张弛'],
        page_start: 111,
        page_end: 114,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '中医扶正疗法的作用',
        authors: ['刘嘉湘'],
        page_start: 115,
        page_end: 118,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '治疗癌症应立足于祛邪',
        authors: ['上海曙光医院内科肿瘤组'],
        page_start: 119,
        page_end: 122,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '在战胜晚期绒癌的征途上',
        authors: ['蔡树模'],
        page_start: 123,
        page_end: 133,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '梅山铁矿的发现及在找矿理论上的意义',
        authors: ['江苏省冶金地质勘探公司八〇七队', '梅山工程指挥部铁矿地质组'],
        page_start: 134,
        page_end: 148,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '焦炉是怎样改烧高炉煤气的',
        authors: ['梅山工程指挥部焦化厂'],
        page_start: 149,
        page_end: 153,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '“石烟多似洛阳尘”——石油的发现，开采和利用',
        authors: ['史戈'],
        page_start: 154,
        page_end: 165,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '纸的发明和造纸技术的传播',
        authors: ['秦功'],
        page_start: 16,
        page_end: 177,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '关于惯性、质量和运动——学习恩格斯《自然辩证法》札记',
        authors: ['关洪'],
        page_start: 178,
        page_end: 195,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '人体有没有抵御肿瘤的能力？',
        authors: ['C·F·麦克汉', '彼得·亚力山大'],
        page_start: 196,
        page_end: 208,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '赖尔和他的《地质学原理》',
        authors: ['史毅'],
        page_start: 209,
        page_end: 224,
        dates: [{ year: 1976, month: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.145, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/92e950b6-a53e-4537-87b0-040dd8c11b17.pdf',
};
