export default {
  entity: {
    id: '9396d223-50a3-44f6-990b-88dbf5b0aec8',
    name: '红旗一九六七年第四期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/9396d223-50a3-44f6-990b-88dbf5b0aec8.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中共中央给全国农村人民公社贫下中农和各级干部的信',
        authors: [],
        page_start: 4,
        page_end: 5,
        dates: [{ year: 1967, month: 2, day: 20 }],
      },
      {
        title: '必须正确地对待干部',
        authors: ['《红旗》杂志编辑部'],
        page_start: 6,
        page_end: 12,
        dates: [{ year: 1967, month: 2, day: 23 }],
      },
      {
        title: '黑龙江省红色造反者夺权斗争的基本经验',
        authors: ['黑龙江省红色造反者'],
        page_start: 13,
        page_end: 15,
        dates: [{ year: 1967, month: 2, day: 9 }],
      },
      {
        title: '坚决捍卫“三结合”的正确方针',
        authors: ['《人民日报》编辑部'],
        page_start: 16,
        page_end: 17,
        dates: [{ year: 1967, month: 2, day: 17 }],
      },
      {
        title: '革命的“三结合”是夺权斗争胜利的保证',
        authors: ['《人民日报》编辑部'],
        page_start: 17,
        page_end: 19,
        dates: [{ year: 1967, month: 3, day: 2 }],
      },
      {
        title: '彻底粉碎反革命逆流',
        authors: ['《解放军报》编辑部'],
        page_start: 19,
        page_end: 20,
        dates: [{ year: 1967, month: 2, day: 18 }],
      },
      {
        title: '当前文化大革命的形势和任务',
        authors: ['上海市革命委员会'],
        page_start: 21,
        page_end: 26,
        dates: [{ year: 1967, month: 2, day: 23 }],
      },
      {
        title: '革命不分先后',
        authors: ['《文汇报》编辑部'],
        page_start: 27,
        page_end: 29,
        dates: [{ year: 1967, month: 2, day: 18 }],
      },
      {
        title: '坚定不移地支持无产阶级革命派的夺权斗争',
        authors: ['张日清'],
        page_start: 30,
        page_end: 34,
        dates: [{ year: 1967 }],
      },
      {
        title: '推荐两篇好文章',
        authors: ['《红旗》杂志编辑部'],
        page_start: 35,
        page_end: 36,
        dates: [{ year: 1967 }],
      },
      {
        title: '我们鲁迅兵团向何处去？',
        authors: ['上海体育战线革命造反司令部鲁迅兵团东方红战斗队'],
        page_start: 37,
        page_end: 44,
        dates: [{ year: 1967 }],
      },
      {
        title: '为“东方红”小将的一张大字报叫好',
        authors: ['上海《体育战报》评论员'],
        page_start: 44,
        page_end: 45,
        dates: [{ year: 1967 }],
      },
      {
        title: '我们是怎样争取和团结群众大多数的',
        authors: ['北京邮票厂革命造反总部'],
        page_start: 46,
        page_end: 49,
        dates: [{ year: 1967 }],
      },
      {
        title: '保卫四清运动的伟大成果',
        authors: ['《红旗》杂志评论员'],
        page_start: 50,
        page_end: 51,
        dates: [{ year: 1967, month: 3, day: 1 }],
      },
      {
        title: '响应毛主席、党中央的号召，掀起春耕生产的高潮',
        authors: ['《红旗》杂志评论员'],
        page_start: 52,
        page_end: 53,
        dates: [{ year: 1967, month: 3, day: 1 }],
      },
      {
        title: '在支持无产阶级革命派夺权斗争中活学活用毛主席著作',
        authors: ['王泽俊'],
        page_start: 54,
        page_end: 56,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1967 }],
      },
      {
        title: '坚决站在无产阶级革命派一边',
        authors: ['王坤'],
        page_start: 57,
        page_end: 58,
        ocr: { auto_vsplit: false, vsplit: 0.41 },
        dates: [{ year: 1967 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/9396d223-50a3-44f6-990b-88dbf5b0aec8.pdf',
};
