export default {
  entity: {
    id: '95bc051a-bd92-48c0-ae43-478814fda629',
    name: '红旗一九七四年第十二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/95bc051a-bd92-48c0-ae43-478814fda629.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '发展社会主义的新生事物',
        authors: ['池恒'],
        page_start: 6,
        page_end: 10,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '继续抓好学习和批判',
        authors: ['吕真'],
        page_start: 11,
        page_end: 14,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '加强革命团结 争取更大胜利',
        authors: ['郑实'],
        page_start: 15,
        page_end: 17,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '集中优势兵力 各个歼灭敌人',
        authors: ['昆骏'],
        page_start: 18,
        page_end: 22,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '儒家是杀人如麻的刽子手',
        authors: ['吴畅'],
        page_start: 23,
        page_end: 28,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '春秋战国时期儒法两条军事路线的斗争',
        authors: ['魏理'],
        page_start: 29,
        page_end: 35,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '论法家与“清官”的根本区别',
        authors: ['天津铁路分局天津站工人理论小组'],
        page_start: 36,
        page_end: 40,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '正义战争必然胜利——批判《盐铁论》中儒家的军事投降主义',
        authors: ['中国人民解放军海军三八九舰理论小组'],
        page_start: 41,
        page_end: 45,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '在银幕上为无产阶级争光——影片《闪闪的红星》的一些创作体会',
        authors: ['八一电影制片厂《闪闪的红星》创作组、摄制组'],
        page_start: 46,
        page_end: 54,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '小厂也能造出四百吨大平板车',
        authors: ['河北沧州市交通局四〇〇小组'],
        page_start: 55,
        page_end: 59,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '在两条道路斗争中发挥战斗堡垒作用',
        authors: ['天津市宝坻县小新庄大队党支部'],
        page_start: 60,
        page_end: 64,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '干部参加集体生产劳动好得很',
        authors: ['中国共产党辉县委员会'],
        page_start: 65,
        page_end: 69,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '争取社会主义农业的更大发展',
        authors: ['赵丰年'],
        page_start: 70,
        page_end: 74,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '总结抗旱经验 促进农业发展',
        authors: ['贺建农'],
        page_start: 75,
        page_end: 80,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '学大寨就要抓路线',
        authors: ['宁江'],
        page_start: 81,
        page_end: 86,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '对人体认识的两种世界观斗争',
        authors: ['金卫'],
        page_start: 87,
        page_end: 97,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
      {
        title: '红旗杂志一九七四年第一期到第十二期总目录',
        authors: ['《红旗》杂志编辑部'],
        page_start: 98,
        page_end: 105,
        dates: [{ year: 1974, month: 11, day: 25 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/95bc051a-bd92-48c0-ae43-478814fda629.pdf',
};
