export default {
  entity: {
    id: '970f7790-c4bd-44c3-a102-7ca01a63cea3',
    name: '红旗一九七一年第二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/970f7790-c4bd-44c3-a102-7ca01a63cea3.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '认真读书，努力改造世界观',
        authors: ['《红旗》杂志编辑部'],
        page_start: 8,
        page_end: 10,
        dates: [{ year: 1971, month: 2, day: 1 }],
      },
      {
        title: '加强新闻报道队伍的思想建设',
        authors: ['江虹'],
        page_start: 11,
        page_end: 14,
        dates: [{ year: 1971, month: 2, day: 1 }],
      },
      {
        title: '把移风易俗的斗争进行到底',
        authors: ['鲁政'],
        page_start: 15,
        page_end: 17,
        dates: [{ year: 1971, month: 2, day: 1 }],
      },
      {
        title: '谦虚谨慎 继续革命',
        authors: ['中国人民解放军济南部队某师党委会'],
        page_start: 18,
        page_end: 22,
        dates: [{ year: 1971, month: 2, day: 1 }],
      },
      {
        title: '认真总结经验 克服骄傲自满',
        authors: ['安徼省安庆地区革命委员会'],
        page_start: 23,
        page_end: 26,
        dates: [{ year: 1971, month: 2, day: 1 }],
      },
      {
        title: '加强传统教育 提高路线觉悟',
        authors: ['中国人民解放军武汉部队某部红军团党委会'],
        page_start: 27,
        page_end: 31,
        dates: [{ year: 1971, month: 2, day: 1 }],
      },
      {
        title: '发扬革命传统 争取更大光荣',
        authors: ['陕西省延安地区革命委员会'],
        page_start: 32,
        page_end: 35,
        dates: [{ year: 1971, month: 2, day: 1 }],
      },
      {
        title: '活学活用毛主席哲学思想提高两条路线斗争觉悟',
        authors: ['华子泉'],
        page_start: 36,
        page_end: 41,
        dates: [{ year: 1971, month: 2, day: 1 }],
      },
      {
        title: '深入开展工业战线的增产节约运动',
        authors: ['国家计委写作小组'],
        page_start: 42,
        page_end: 50,
        dates: [{ year: 1971, month: 2, day: 1 }],
      },
      {
        title: '培养工人阶级的技术队伍',
        authors: ['张梅华'],
        page_start: 51,
        page_end: 55,
        dates: [{ year: 1971, month: 2, day: 1 }],
      },
      {
        title:
          '执行“发展经济，保障供给”的伟大方针——中国人民银行辽宁抚顺市分行建新服务班的调查报告',
        authors: ['财政部、抚顺市革委会、抚顺军分区联合调查组'],
        page_start: 56,
        page_end: 61,
        dates: [{ year: 1971, month: 2, day: 1 }],
      },
      {
        title: '为普及合成纤维生产而奋斗——广东茂名市化工二厂的调查报告',
        authors: ['茂名市革命委员会调查组'],
        page_start: 62,
        page_end: 65,
        dates: [{ year: 1971, month: 2, day: 1 }],
      },
      {
        title: '我们是怎样加强妇女工作领导的',
        authors: ['韩文'],
        page_start: 66,
        page_end: 68,
        dates: [{ year: 1971, month: 2, day: 1 }],
      },
      {
        title: '革命妇女意志坚——广西环江县同进大队的调查报告',
        authors: ['河池专区革委会、环江县革委会联合调查组'],
        page_start: 69,
        page_end: 74,
        dates: [{ year: 1971, month: 2, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/970f7790-c4bd-44c3-a102-7ca01a63cea3.pdf',
};
