export default {
  entity: {
    id: '9a0b73c4-38fe-45d6-8c7b-5448b0ea54f2',
    name: '红旗一九七〇年第四期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/9a0b73c4-38fe-45d6-8c7b-5448b0ea54f2.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title:
          '进一步加强无产阶级专政——学习毛主席关于无产阶级专政下继续革命的学说，纪念“九大”一周年',
        authors: ['黑龙江省革命委员会写作小组'],
        page_start: 8,
        page_end: 19,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title: '打倒洋奴哲学',
        authors: ['赵先平'],
        page_start: 20,
        page_end: 24,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title: '注意综合利用',
        authors: ['于宏'],
        page_start: 23,
        page_end: 29,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title: '无产阶级教育革命大有奔头——驳“当教师没奔头”论',
        authors: ['浙江省革命委员会写作小组'],
        page_start: 30,
        page_end: 33,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title:
          '为巩固无产阶级专政储备更多的粮草——江苏灌云县吴南生产队的调查报告',
        authors: [
          '灌云县革命委员会、灌云县人民武装部、《新华日报》记者联合调查',
        ],
        page_start: 34,
        page_end: 38,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title:
          '一个小厂是怎样年产五百辆汽车的？——江西井冈山汽车制造厂的调查报告',
        authors: ['江西省革命委员会调查组'],
        page_start: 39,
        page_end: 44,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title:
          '鼓吹资产阶级文艺就是复辟资本主义——驳周扬吹捧资产阶级“文艺复兴”“启蒙运动”“批判现实主义”的反动理论',
        authors: ['上海革命大批判写作小组'],
        page_start: 45,
        page_end: 54,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title: '让哲学变为群众手里的尖锐武器',
        authors: ['《红旗》杂志编辑部'],
        page_start: 55,
        page_end: 56,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title: '只有破得深 才能立得牢',
        authors: ['姜乾位'],
        page_start: 56,
        page_end: 57,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title: '养成分析的习惯',
        authors: ['戴香妹'],
        page_start: 57,
        page_end: 58,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title: '我是怎样学习“一分为二”观点的',
        authors: ['冯照成'],
        page_start: 59,
        page_end: 60,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title: '决定的因素是人',
        authors: ['长春市玻璃总厂工人学哲学小组'],
        page_start: 61,
        page_end: 64,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title: '打破洋框框',
        authors: ['天津化工厂三车间工人学哲学小组'],
        page_start: 64,
        page_end: 66,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title: '安全行车的辩证法',
        authors: ['薛向东'],
        page_start: 67,
        page_end: 70,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title: '有一劳永逸这种事吗？',
        authors: ['江苏泰县河横大队通讯组'],
        page_start: 71,
        page_end: 71,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
      {
        title: '为传播毛泽东思想做好发行工作',
        authors: ['河南孟津县革命委员会'],
        page_start: 72,
        page_end: 73,
        dates: [{ year: 1970, month: 4, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/9a0b73c4-38fe-45d6-8c7b-5448b0ea54f2.pdf',
};
