export default {
  entity: {
    id: '9aa5709d-3c92-4bff-b061-bf06b6a7def3',
    name: '无产阶级文化大革命资料汇编（第五篇）（水陆洲2012年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '水陆洲编',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/9aa5709d-3c92-4bff-b061-bf06b6a7def3.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '第一章 十月政变 第一节 元老派的预谋',
        authors: ['水陆洲'],
        page_start: 5,
        page_end: 42,
        dates: [{ year: 2012, month: 3, day: 15 }],
      },
      {
        title: '第一章 十月政变 第二节 新贵派的阴谋',
        authors: ['水陆洲'],
        page_start: 43,
        page_end: 75,
        dates: [{ year: 2012, month: 3, day: 15 }],
      },
      {
        title: '第一章 十月政变 第三节 江青等人的活动',
        authors: ['水陆洲'],
        page_start: 76,
        page_end: 119,
        dates: [{ year: 2012, month: 3, day: 15 }],
      },
      {
        title: '第一章 十月政变 第四节 逮捕江张姚王毛',
        authors: ['水陆洲'],
        page_start: 120,
        page_end: 164,
        dates: [{ year: 2012, month: 3, day: 15 }],
      },
      {
        title: '第一章 十月政变 第五节 通过四项决定',
        authors: ['水陆洲'],
        page_start: 165,
        page_end: 182,
        dates: [{ year: 2012, month: 3, day: 15 }],
      },
      {
        title: '第一章 十月政变 第六节 稳定局势',
        authors: ['水陆洲'],
        page_start: 183,
        page_end: 191,
        dates: [{ year: 2012, month: 3, day: 15 }],
      },
      {
        title: '第一章 十月政变 第七节 揭批的三大战役',
        authors: ['水陆洲'],
        page_start: 192,
        page_end: 483,
        dates: [{ year: 2012, month: 3, day: 15 }],
      },
      {
        title: '第一章 十月政变 第八节 清理帮派体系骨干分子',
        authors: ['水陆洲'],
        page_start: 484,
        page_end: 591,
        dates: [{ year: 2012, month: 3, day: 15 }],
      },
      {
        title: '第二章 召开十一大 第一节 邓小平复出',
        authors: ['水陆洲'],
        page_start: 592,
        page_end: 609,
        dates: [{ year: 2012, month: 3, day: 16 }],
      },
      {
        title: '第二章 召开十一大 第二节 举行十届三中全会',
        authors: ['水陆洲'],
        page_start: 610,
        page_end: 629,
        dates: [{ year: 2012, month: 3, day: 16 }],
      },
      {
        title: '第二章 召开十一大 第三节 宣布文革结束',
        authors: ['水陆洲'],
        page_start: 630,
        page_end: 705,
        dates: [{ year: 2012, month: 3, day: 16 }],
      },
      {
        title: '第二章 召开十一大 第四节 批判两个凡是',
        authors: ['水陆洲'],
        page_start: 706,
        page_end: 772,
        dates: [{ year: 2012, month: 3, day: 16 }],
      },
      {
        title: '第二章 召开十一大 第五节 清查帮派体系',
        authors: ['水陆洲'],
        page_start: 773,
        page_end: 867,
        dates: [{ year: 2012, month: 3, day: 16 }],
      },
      {
        title: '第三章 十一届三中全会 第一节 举行中央工作会议',
        authors: ['水陆洲'],
        page_start: 868,
        page_end: 893,
        dates: [{ year: 2012, month: 3, day: 16 }],
      },
      {
        title: '第三章 十一届三中全会 第二节 大规模的平反翻案',
        authors: ['水陆洲'],
        page_start: 894,
        page_end: 994,
        dates: [{ year: 2012, month: 3, day: 16 }],
      },
      {
        title: '第三章 十一届三中全会 第三节 召开理论务虚会',
        authors: ['水陆洲'],
        page_start: 995,
        page_end: 1056,
        dates: [{ year: 2012, month: 3, day: 16 }],
      },
      {
        title: '第四章 十一届四、五中全会 第一节 七九年国庆讲话',
        authors: ['水陆洲'],
        page_start: 1057,
        page_end: 1063,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第四章 十一届四、五中全会 第二节 为刘少奇平反',
        authors: ['水陆洲'],
        page_start: 1064,
        page_end: 1160,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第四章 十一届四、五中全会 第三节 审判江青',
        authors: ['水陆洲'],
        page_start: 1161,
        page_end: 1215,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第四章 十一届四、五中全会 第四节 华的五个干将被辞职',
        authors: ['水陆洲'],
        page_start: 1216,
        page_end: 1234,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第五章 十一届六中全会 第一节 历史问题决议',
        authors: ['水陆洲'],
        page_start: 1236,
        page_end: 1328,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第五章 十一届六中全会 第二节 华国锋下台',
        authors: ['水陆洲'],
        page_start: 1329,
        page_end: 1333,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第五章 十一届六中全会 第三节 邓小平继续批毛',
        authors: ['水陆洲'],
        page_start: 1334,
        page_end: 1334,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第五章 十一届六中全会 第四节 审判各地区的“帮派骨干分子”',
        authors: ['水陆洲'],
        page_start: 1335,
        page_end: 1408,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第六章 星星之火可以燎原 第一节 河南省',
        authors: ['水陆洲'],
        page_start: 1409,
        page_end: 1507,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第六章 星星之火可以燎原 第二节 湖北省',
        authors: ['水陆洲'],
        page_start: 1508,
        page_end: 1581,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第六章 星星之火可以燎原 第三节 云南省',
        authors: ['水陆洲'],
        page_start: 1582,
        page_end: 1648,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第六章 星星之火可以燎原 第四节 四川省',
        authors: ['水陆洲'],
        page_start: 1649,
        page_end: 1716,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第六章 星星之火可以燎原 第五节 重庆市',
        authors: ['水陆洲'],
        page_start: 1718,
        page_end: 1752,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第六章 星星之火可以燎原 第六节 山东省',
        authors: ['水陆洲'],
        page_start: 1753,
        page_end: 1757,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第六章 星星之火可以燎原 第七节 浙江省',
        authors: ['水陆洲'],
        page_start: 1758,
        page_end: 1782,
        dates: [{ year: 2012, month: 3, day: 18 }],
      },
      {
        title: '第六章 星星之火可以燎原 第八节 黑龙江省',
        authors: ['水陆洲'],
        page_start: 1783,
        page_end: 1808,
        dates: [{ year: 2012, month: 3, day: 19 }],
      },
      {
        title: '第六章 星星之火可以燎原 第九节 河北省',
        authors: ['水陆洲'],
        page_start: 1809,
        page_end: 1814,
        dates: [{ year: 2012, month: 3, day: 19 }],
      },
      {
        title: '第六章 星星之火可以燎原 第十节 安徽省',
        authors: ['水陆洲'],
        page_start: 1815,
        page_end: 1833,
        dates: [{ year: 2012, month: 3, day: 19 }],
      },
      {
        title: '第六章 星星之火可以燎原 第十一节 湖南省',
        authors: ['水陆洲'],
        page_start: 1834,
        page_end: 1851,
        dates: [{ year: 2012, month: 8, day: 3 }],
      },
      {
        title: '第六章 星星之火可以燎原 第十二节 江西省',
        authors: ['水陆洲'],
        page_start: 1852,
        page_end: 1862,
        dates: [{ year: 2012, month: 8, day: 3 }],
      },
    ],
    ocr: {
      standard_paragraph_merge_strategy_threshold: 0.186,
      differential_paragraph_merge_strategy_threshold: 0,
      content_thresholds: [0.054, 0, 0, 0],
      extract_text_from_pdf: true,
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/9aa5709d-3c92-4bff-b061-bf06b6a7def3.pdf',
};
