export default {
  entity: {
    id: '9d8ab39d-f0c7-4aa8-b22a-d254b2134654',
    name: '文革通讯第22期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '浙江工农兵美术大学毛泽东主义红卫兵战斗队、毛泽东主义红卫兵',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives15/main/9d8ab39d-f0c7-4aa8-b22a-d254b2134654.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '毛主席的最新指示',
        authors: ['毛泽东'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967, month: 4, day: 23 }],
      },
      {
        title: '毛主席四月十九日下午四点接见谢富治副总理',
        authors: ['毛泽东'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967, month: 4, day: 19 }],
      },
      {
        title: '陈伯达同志四月二十七日讲话',
        authors: ['陈伯达'],
        page_start: 1,
        page_end: 2,
        dates: [{ year: 1967, month: 4, day: 27 }],
      },
      {
        title:
          '四月十八日十七时，陈伯达同志给在人民大会堂开会的谢富治副总理及一些院校负责人的电话记录',
        authors: ['陈伯达'],
        page_start: 2,
        page_end: 2,
        dates: [{ year: 1967, month: 4, day: 18 }],
      },
      {
        title: '周总理谈刘、邓问题',
        authors: ['周恩来'],
        page_start: 2,
        page_end: 3,
        dates: [{ year: 1967, month: 4, day: 6 }],
      },
      {
        title:
          '周总理、中央文革同志22日接见中学部分联动分子江青同志宣布全部释放被捕的130多名联动分子',
        authors: ['周恩来', '江青', '陈伯达'],
        page_start: 3,
        page_end: 3,
        dates: [{ year: 1967, month: 4, day: 22 }],
      },
      {
        title: '重要声明',
        authors: ['清华大学井冈山兵团动态组'],
        page_start: 3,
        page_end: 3,
        dates: [{ year: 1967, month: 4 }],
      },
      {
        title: '就清华附中联动被释放分子的传单问题访中央文革接待站',
        authors: ['杨华成'],
        page_start: 4,
        page_end: 4,
        dates: [{ year: 1967, month: 4, day: 26 }],
      },
      {
        title: '北京简讯',
        authors: ['《文革通讯》编辑部'],
        page_start: 4,
        page_end: 5,
        dates: [{ year: 1967, month: 5, day: 7 }],
      },
      {
        title: '访《铁道游击队》第四任政委看刘少奇丑态',
        authors: ['《文革通讯》编辑部'],
        page_start: 5,
        page_end: 5,
        dates: [{ year: 1967, month: 5, day: 7 }],
      },
      {
        title: '祖国各地',
        authors: ['《文革通讯》编辑部'],
        page_start: 5,
        page_end: 8,
        dates: [{ year: 1967, month: 5, day: 7 }],
      },
    ],
    ocr: undefined,
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives15/9d8ab39d-f0c7-4aa8-b22a-d254b2134654.pdf',
};
