export default {
  entity: {
    id: '9fa38e5d-eb38-4ac9-b90d-16bd96c80a70',
    name: '文化大革命的起源-浩劫的来临 1961-1966年（新世纪出版社2012年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '马若德著，新世纪出版社2012年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/9fa38e5d-eb38-4ac9-b90d-16bd96c80a70.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '全译版前言',
        authors: ['新世纪出版社'],
        page_start: 17,
        page_end: 18,
        dates: [{ year: 2012, month: 10, day: 1 }],
      },
      {
        title: '前言',
        authors: ['马若德'],
        page_start: 19,
        page_end: 22,
        dates: [{ year: 1995 }],
      },
      {
        title: '导言',
        authors: ['马若德'],
        page_start: 23,
        page_end: 30,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第一编 灾荒第三年 第一章 中共中央第九次全体会议',
        authors: ['马若德'],
        page_start: 32,
        page_end: 43,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第一编 灾荒第三年 第二章 紧急措施',
        authors: ['马若德'],
        page_start: 44,
        page_end: 59,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第一编 灾荒第三年 第三章 农村工作的新路线',
        authors: ['马若德'],
        page_start: 60,
        page_end: 90,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第一编 灾荒第三年 第四章 计划迭出',
        authors: ['马若德'],
        page_start: 91,
        page_end: 108,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第一编 灾荒第三年 第五章 红与专',
        authors: ['马若德'],
        page_start: 109,
        page_end: 138,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第一编 灾荒第三年 第六章 中国的孤立',
        authors: ['马若德'],
        page_start: 139,
        page_end: 152,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第二编 虚假的黎明 第七章 七千人干部大会',
        authors: ['马若德'],
        page_start: 154,
        page_end: 198,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第二编 虚假的黎明 第八章 经济困难',
        authors: ['马若德'],
        page_start: 199,
        page_end: 221,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第二编 虚假的黎明 第九章 关于集体化的争论',
        authors: ['马若德'],
        page_start: 222,
        page_end: 242,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第二编 虚假的黎明 第十章 恢复统一战线',
        authors: ['马若德'],
        page_start: 243,
        page_end: 256,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第二编 虚假的黎明 第十一章 三家村奇案',
        authors: ['马若德'],
        page_start: 257,
        page_end: 265,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第三编 阶级斗争 第十二章 毛改变了信号',
        authors: ['马若德'],
        page_start: 267,
        page_end: 299,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第三编 阶级斗争 第十三章 喜马拉雅山战役，加勒比海危机',
        authors: ['马若德'],
        page_start: 300,
        page_end: 325,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第三编 阶级斗争 第十四章 毛负全责',
        authors: ['马若德'],
        page_start: 326,
        page_end: 334,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第三编 阶级斗争 第十五章 社会主义教育运动',
        authors: ['马若德'],
        page_start: 335,
        page_end: 347,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第三编 阶级斗争 第十六章 中苏决裂与越南战争',
        authors: ['马若德'],
        page_start: 348,
        page_end: 375,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第四编 延安圆桌会议的终结 第十七章 女战士',
        authors: ['马若德'],
        page_start: 377,
        page_end: 392,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第四编 延安圆桌会议的终结 第十八章 从灰色名人到红色领导人',
        authors: ['马若德'],
        page_start: 393,
        page_end: 421,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第四编 延安圆桌会议的终结 第十九章 毛以退为进',
        authors: ['马若德'],
        page_start: 422,
        page_end: 450,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '第四编 延安圆桌会议的终结 第二十章 浩劫来临',
        authors: ['马若德'],
        page_start: 451,
        page_end: 455,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '结论',
        authors: ['马若德'],
        page_start: 456,
        page_end: 464,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '注释',
        authors: ['马若德'],
        page_start: 465,
        page_end: 592,
        dates: [{ year: 2012, month: 10 }],
      },
      {
        title: '书目',
        authors: ['马若德'],
        page_start: 593,
        page_end: 622,
        dates: [{ year: 2012, month: 10 }],
      },
    ],
    ocr: { content_thresholds: [0.072, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/9fa38e5d-eb38-4ac9-b90d-16bd96c80a70.pdf',
};
