export default {
  entity: {
    id: 'a202d6ff-1b2f-424a-827f-ef68f5e3ffd1',
    name: '国际共产主义运动简史（1848-1917）（上海人民出版社1976年版）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '上海人民出版社1976年版',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/a202d6ff-1b2f-424a-827f-ef68f5e3ffd1.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '《青年自学丛书》编辑说明',
        authors: ['上海师范大学政治教育系', '《国际共产主义运动简史》编写组'],
        page_start: 7,
        page_end: 7,
        dates: [{ year: 1976, month: 4 }],
      },
      {
        title: '一 马克思主义的诞生和国际共产主义运动的兴起',
        authors: ['上海师范大学政治教育系', '《国际共产主义运动简史》编写组'],
        page_start: 11,
        page_end: 39,
        dates: [{ year: 1976, month: 4 }],
      },
      {
        title: '二 1848年欧洲革命风暴和马克思主义的发展',
        authors: ['上海师范大学政治教育系', '《国际共产主义运动简史》编写组'],
        page_start: 40,
        page_end: 60,
        dates: [{ year: 1976, month: 4 }],
      },
      {
        title: '三 第一国际期间马克思、恩格斯反对机会主义的斗争',
        authors: ['上海师范大学政治教育系', '《国际共产主义运动简史》编写组'],
        page_start: 61,
        page_end: 84,
        dates: [{ year: 1976, month: 4 }],
      },
      {
        title: '四 无产阶级专政的第一次伟大尝试——巴黎公社',
        authors: ['上海师范大学政治教育系', '《国际共产主义运动简史》编写组'],
        page_start: 85,
        page_end: 103,
        dates: [{ year: 1976, month: 4 }],
      },
      {
        title: '五 马克思、恩格斯在欧美各国建党问题上同机会主义路线的斗争',
        authors: ['上海师范大学政治教育系', '《国际共产主义运动简史》编写组'],
        page_start: 104,
        page_end: 130,
        dates: [{ year: 1976, month: 4 }],
      },
      {
        title: '六 恩格斯为坚持和捍卫马克思主义革命路线而斗争',
        authors: ['上海师范大学政治教育系', '《国际共产主义运动简史》编写组'],
        page_start: 131,
        page_end: 151,
        dates: [{ year: 1976, month: 4 }],
      },
      {
        title: '七 列宁主义的诞生',
        authors: ['上海师范大学政治教育系', '《国际共产主义运动简史》编写组'],
        page_start: 152,
        page_end: 172,
        dates: [{ year: 1976, month: 4 }],
      },
      {
        title: '八 列宁为建立新型马克思主义政党而斗争',
        authors: ['上海师范大学政治教育系', '《国际共产主义运动简史》编写组'],
        page_start: 173,
        page_end: 192,
        dates: [{ year: 1976, month: 4 }],
      },
      {
        title: '九 列宁在俄国1905年革命期间和革命低潮时期反对机会主义的斗争',
        authors: ['上海师范大学政治教育系', '《国际共产主义运动简史》编写组'],
        page_start: 193,
        page_end: 217,
        dates: [{ year: 1976, month: 4 }],
      },
      {
        title: '十 在民族殖民地问题上列宁反对修正主义的斗争',
        authors: ['上海师范大学政治教育系', '《国际共产主义运动简史》编写组'],
        page_start: 218,
        page_end: 231,
        dates: [{ year: 1976, month: 4 }],
      },
      {
        title: '十一 在对待帝国主义战争问题上列宁反对第二国际修正主义的斗争',
        authors: ['上海师范大学政治教育系', '《国际共产主义运动简史》编写组'],
        page_start: 232,
        page_end: 253,
        dates: [{ year: 1976, month: 4 }],
      },
      {
        title: '十二 十月社会主义革命开辟了人类历史的新纪元',
        authors: ['上海师范大学政治教育系', '《国际共产主义运动简史》编写组'],
        page_start: 254,
        page_end: 294,
        dates: [{ year: 1976, month: 4 }],
      },
      {
        title: '后记',
        authors: ['上海师范大学政治教育系', '《国际共产主义运动简史》编写组'],
        page_start: 254,
        page_end: 294,
        dates: [{ year: 1975, month: 12 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.122, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/a202d6ff-1b2f-424a-827f-ef68f5e3ffd1.pdf',
};
