export default {
  entity: {
    id: 'a67c3add-0af2-4a56-b8e9-e48cf9246ce2',
    name: '无产阶级文化大革命资料汇编（第三篇）（上）（水陆洲2012年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '水陆洲编',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/a67c3add-0af2-4a56-b8e9-e48cf9246ce2.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '第一章 认真搞好斗、批、改 第一节 九大以后的新形势新任务',
        authors: ['水陆洲'],
        page_start: 4,
        page_end: 73,
        dates: [{ year: 2011, month: 12, day: 21 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第二节 解决一些省的遗留问题',
        authors: ['水陆洲'],
        page_start: 74,
        page_end: 242,
        dates: [{ year: 2011, month: 12, day: 20 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第三节 清理阶级队伍',
        authors: ['水陆洲'],
        page_start: 243,
        page_end: 296,
        dates: [{ year: 2011, month: 12, day: 27 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第四节 打击反革命破坏活动',
        authors: ['水陆洲'],
        page_start: 297,
        page_end: 380,
        dates: [{ year: 2011, month: 12, day: 27 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第五节 继续清查五·一六',
        authors: ['水陆洲'],
        page_start: 381,
        page_end: 609,
        dates: [{ year: 2011, month: 12, day: 28 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第六节 整党建党',
        authors: ['水陆洲'],
        page_start: 610,
        page_end: 672,
        dates: [{ year: 2011, month: 12, day: 28 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第七节 毕业生分配、上山下乡',
        authors: ['水陆洲'],
        page_start: 673,
        page_end: 742,
        dates: [{ year: 2011, month: 12, day: 29 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第八节 教育卫生文化等领域的革命',
        authors: ['水陆洲'],
        page_start: 743,
        page_end: 832,
        dates: [{ year: 2011, month: 12, day: 29 }],
      },
      {
        title: '第一章 认真搞好斗、批、改 第九节 改革旧的规章制度',
        authors: ['水陆洲'],
        page_start: 833,
        page_end: 940,
        dates: [{ year: 2011, month: 12, day: 30 }],
      },
      {
        title: '第二章 九届二中全会上的斗争 第一节 一九七〇年的新形势新任务',
        authors: ['水陆洲'],
        page_start: 941,
        page_end: 1036,
        dates: [{ year: 2011, month: 12, day: 31 }],
      },
      {
        title: '第二章 九届二中全会上的斗争 第二节 林彪集团逐渐形成',
        authors: ['水陆洲'],
        page_start: 1037,
        page_end: 1102,
        dates: [{ year: 2011, month: 3, day: 6 }],
      },
      {
        title: '第二章 九届二中全会上的斗争 第三节 围绕修改宪法的斗争',
        authors: ['水陆洲'],
        page_start: 1103,
        page_end: 1154,
        dates: [{ year: 2011, month: 12, day: 31 }],
      },
      {
        title: '第二章 九届二中全会上的斗争 第四节 林彪搞突袭 毛泽东反潮流',
        authors: ['水陆洲'],
        page_start: 1155,
        page_end: 1292,
        dates: [{ year: 2011, month: 12, day: 31 }],
      },
      {
        title: '第三章 开展批陈整风 第一节 一九七一年的新形势新任务',
        authors: ['水陆洲'],
        page_start: 1293,
        page_end: 1353,
        dates: [{ year: 2012, month: 1, day: 1 }],
      },
      {
        title: '第三章 开展批陈整风 第二节 几员大将的检讨 吴法宪叶群的检讨',
        authors: ['水陆洲'],
        page_start: 1354,
        page_end: 1370,
        dates: [{ year: 2012, month: 1, day: 1 }],
      },
      {
        title: '第三章 开展批陈整风 第三节 陈伯达反党问题',
        authors: ['水陆洲'],
        page_start: 1371,
        page_end: 1409,
        dates: [{ year: 2012, month: 3, day: 8 }],
      },
      {
        title: '第三章 开展批陈整风 第四节 召开华北会议',
        authors: ['水陆洲'],
        page_start: 1410,
        page_end: 1426,
        dates: [{ year: 2012, month: 3, day: 8 }],
      },
      {
        title: '第三章 开展批陈整风 第五节 召开中央批陈整风汇报会议',
        authors: ['水陆洲'],
        page_start: 1427,
        page_end: 1464,
        dates: [{ year: 2012, month: 3, day: 8 }],
      },
      {
        title: '第四章 林彪集团的反革命政变活动 第一节 制定反革命计划',
        authors: ['水陆洲'],
        page_start: 1465,
        page_end: 1480,
        dates: [{ year: 2012, month: 4, day: 4 }],
      },
      {
        title: '第四章 林彪集团的反革命政变活动 第二节 实施反革命政变',
        authors: ['水陆洲'],
        page_start: 1481,
        page_end: 1488,
        dates: [{ year: 2012, month: 4, day: 3 }],
      },
      {
        title: '第五章 毛泽东外地巡视 第一节 毛泽东巡视武昌',
        authors: ['水陆洲'],
        page_start: 1489,
        page_end: 1500,
        dates: [{ year: 2011, month: 4, day: 24 }],
      },
      {
        title: '第五章 毛泽东外地巡视 第二节 毛泽东巡视长沙',
        authors: ['水陆洲'],
        page_start: 1501,
        page_end: 1533,
        dates: [{ year: 2012, month: 4 }],
      },
      {
        title: '第五章 毛泽东外地巡视 第三节 毛泽东巡视南昌',
        authors: ['水陆洲'],
        page_start: 1534,
        page_end: 1539,
        dates: [{ year: 2012, month: 5, day: 2 }],
      },
      {
        title: '第五章 毛泽东外地巡视 第四节 毛泽东巡视杭州',
        authors: ['水陆洲'],
        page_start: 1540,
        page_end: 1550,
        dates: [{ year: 2012, month: 5, day: 3 }],
      },
      {
        title: '第五章 毛泽东外地巡视 第五节 毛泽东巡视上海',
        authors: ['水陆洲'],
        page_start: 1551,
        page_end: 1557,
        dates: [{ year: 2012, month: 4, day: 25 }],
      },
      {
        title: '第五章 毛泽东外地巡视 第六节 毛泽东回到北京',
        authors: ['水陆洲'],
        page_start: 1558,
        page_end: 1569,
        dates: [{ year: 2012, month: 4, day: 25 }],
      },
    ],
    ocr: {
      standard_paragraph_merge_strategy_threshold: 0.186,
      differential_paragraph_merge_strategy_threshold: 0,
      content_thresholds: [0.054, 0, 0, 0],
      extract_text_from_pdf: true,
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/a67c3add-0af2-4a56-b8e9-e48cf9246ce2.pdf',
};
