export default {
  entity: {
    id: 'a69ffe78-9ac4-44e6-8f28-5d885b1bba29',
    name: '红旗一九七〇年第五期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/a69ffe78-9ac4-44e6-8f28-5d885b1bba29.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '列宁主义，还是社会帝国主义？──纪念伟大列宁诞生一百周年',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        page_start: 8,
        page_end: 24,
        dates: [{ year: 1970, month: 4, day: 22 }],
      },
      {
        title: '我国第一颗人造地球卫星发射成功',
        authors: ['新华社'],
        page_start: 25,
        page_end: 25,
        dates: [{ year: 1970, month: 4, day: 25 }],
      },
      {
        title: '红灯记',
        authors: ['中国京剧团'],
        page_start: 26,
        page_end: 49,
        dates: [{ year: 1970, month: 5, day: 1 }],
      },
      {
        title: '为塑造无产阶级的英雄典型而斗争——塑造李玉和英雄形象的体会',
        authors: ['中国京剧团《红灯记》剧组'],
        page_start: 50,
        page_end: 59,
        dates: [{ year: 1970, month: 5, day: 1 }],
      },
      {
        title: '革命大批判的强大思想武器——学习《在延安文艺座谈会上的讲话》',
        authors: ['天津市革命委员会写作小组'],
        page_start: 60,
        page_end: 65,
        dates: [{ year: 1970, month: 5, day: 1 }],
      },
      {
        title: '人民战争的壮丽颂歌——评钢琴协奏曲《黄河》',
        authors: ['丁学雷'],
        page_start: 66,
        page_end: 73,
        dates: [{ year: 1970, month: 5, day: 1 }],
      },
      {
        title: '从“老三篇”中学习毛主席的哲学思想',
        authors: ['李长茂'],
        page_start: 74,
        page_end: 76,
        dates: [{ year: 1970, month: 5, day: 1 }],
      },
      {
        title: '把千里草原建设成祖国的钢铁长城',
        authors: ['宝日勒岱'],
        page_start: 77,
        page_end: 79,
        dates: [{ year: 1970, month: 5, day: 1 }],
      },
      {
        title: '紧跟毛主席奋斗终生',
        authors: ['周建人'],
        page_start: 79,
        page_end: 82,
        dates: [{ year: 1970, month: 5, day: 1 }],
      },
      {
        title: '毛泽东思想指引我们妇女永远向前',
        authors: ['杨桂芳'],
        page_start: 83,
        page_end: 86,
        dates: [{ year: 1970, month: 5, day: 1 }],
      },
      {
        title: '无产阶级文化大革命是发展生产的伟大动力',
        authors: ['张正桃'],
        page_start: 86,
        page_end: 88,
        dates: [{ year: 1970, month: 5, day: 1 }],
      },
      {
        title: '艰苦奋斗 继续革命',
        authors: ['“南京路上好八连”党支部'],
        page_start: 89,
        page_end: 91,
        dates: [{ year: 1970, month: 5, day: 1 }],
      },
      {
        title: '革命历史歌曲（五首）',
        authors: [],
        page_start: 92,
        page_end: 97,
        dates: [{ year: 1970, month: 5, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/a69ffe78-9ac4-44e6-8f28-5d885b1bba29.pdf',
};
