export default {
  entity: {
    id: 'a6c01981-a674-416b-ab3b-2fc3f84c1058',
    name: '十年非梦——黄金海回忆录（2013年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '黄金海，2013年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/a6c01981-a674-416b-ab3b-2fc3f84c1058.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '《十年非梦》编辑说明',
        authors: ['《十年非梦》编辑组'],
        page_start: 7,
        page_end: 8,
        dates: [{ year: 2013 }],
      },
      {
        title: '秉笔直言 黄金十年——代序',
        authors: ['黄肇敏'],
        page_start: 9,
        page_end: 9,
        dates: [{ year: 2020, month: 7, day: 13 }],
      },
      {
        title: '前言',
        authors: ['黄金海'],
        page_start: 15,
        page_end: 22,
        dates: [{ year: 2013 }],
      },
      {
        title: '第一章 苦尽甘来两重天 党的恩情可比山',
        authors: ['黄金海'],
        page_start: 23,
        page_end: 32,
        dates: [{ year: 2013 }],
      },
      {
        title: '第二章 文革风暴平地起 欲置度外不由己',
        authors: ['黄金海'],
        page_start: 33,
        page_end: 43,
        dates: [{ year: 2013 }],
      },
      {
        title: '第三章 红卫兵大串联 上海工运风云起',
        authors: ['黄金海'],
        page_start: 44,
        page_end: 61,
        dates: [{ year: 2013 }],
      },
      {
        title: '第四章 “安亭事件”缘何起 上海市委耍心计',
        authors: ['黄金海'],
        page_start: 62,
        page_end: 82,
        dates: [{ year: 2013 }],
      },
      {
        title: '第五章 精心制造大分裂 酿成上海大事件',
        authors: ['黄金海'],
        page_start: 83,
        page_end: 95,
        dates: [{ year: 2013 }],
      },
      {
        title: '第六章 经济主义妖风起 上海经济告危急',
        authors: ['黄金海'],
        page_start: 96,
        page_end: 123,
        dates: [{ year: 2013 }],
      },
      {
        title: '第七章 “一月风暴”上海起，偶然存于必然里',
        authors: ['黄金海'],
        page_start: 124,
        page_end: 143,
        dates: [{ year: 2013 }],
      },
      {
        title: '第八章 夺权虽获大胜利 流血斗争更残酷',
        authors: ['黄金海'],
        page_start: 144,
        page_end: 164,
        dates: [{ year: 2013 }],
      },
      {
        title: '第九章 一月夺权遭阻击 “二次大乱”终平息',
        authors: ['黄金海'],
        page_start: 165,
        page_end: 198,
        dates: [{ year: 2013 }],
      },
      {
        title: '第十章 工人阶级驻上层 分管财贸履薄冰',
        authors: ['黄金海'],
        page_start: 199,
        page_end: 244,
        dates: [{ year: 2013 }],
      },
      {
        title: '第十一章 “武装叛乱”势需要 判断有误是实情',
        authors: ['黄金海'],
        page_start: 245,
        page_end: 261,
        dates: [{ year: 2013 }],
      },
      {
        title: '第十二章 身陷囹圄十五载 褒贬自会有春秋',
        authors: ['黄金海'],
        page_start: 262,
        page_end: 344,
        dates: [{ year: 2013 }],
      },
    ],
    ocr: { content_thresholds: [0.078, 0.078, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/a6c01981-a674-416b-ab3b-2fc3f84c1058.pdf',
};
