export default {
  entity: {
    id: 'a7a7ea71-b8fd-46ae-9018-f51b25238381',
    name: '红色工程师的崛起：清华大学与中国技术官僚阶级的起源（中文大学出版社2017年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '安舟著，中文大学出版社2017年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/a7a7ea71-b8fd-46ae-9018-f51b25238381.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中文版序',
        authors: ['安舟'],
        page_start: 15,
        page_end: 16,
        dates: [{ year: 2016, month: 1 }],
      },
      {
        title: '序',
        authors: ['安舟'],
        page_start: 17,
        page_end: 21,
        dates: [{ year: 2008, month: 4 }],
      },
      {
        title: '导言',
        authors: ['安舟'],
        page_start: 25,
        page_end: 39,
        dates: [{ year: 2017 }],
      },
      {
        title: '第一部 建设社会主义（1949-1966） 第一章 阶级权力的政治基础',
        authors: ['安舟'],
        page_start: 43,
        page_end: 67,
        dates: [{ year: 2017 }],
      },
      {
        title: '第一部 建设社会主义（1949-1966） 第二章 阶级权力的文化基础',
        authors: ['安舟'],
        page_start: 69,
        page_end: 86,
        dates: [{ year: 2017 }],
      },
      {
        title: '第一部 建设社会主义（1949-1966） 第三章 红色工程师的摇篮',
        authors: ['安舟'],
        page_start: 87,
        page_end: 108,
        dates: [{ year: 2017 }],
      },
      {
        title: '第二部 文化大革命（1966-1968） 第四章 政治权力对拼文化权力',
        authors: ['安舟'],
        page_start: 111,
        page_end: 128,
        dates: [{ year: 2017 }],
      },
      {
        title:
          '第二部 文化大革命（1966-1968） 第五章 团结起来，保卫政治权力及文化权力',
        authors: ['安舟'],
        page_start: 129,
        page_end: 154,
        dates: [{ year: 2017 }],
      },
      {
        title: '第三部 把文化大革命制度化（1968-1976） 第六章 监督红色工程师',
        authors: ['安舟'],
        page_start: 157,
        page_end: 182,
        dates: [{ year: 2017 }],
      },
      {
        title:
          '第三部 把文化大革命制度化（1968-1976） 第七章 消除脑力劳动与体力劳动的差别',
        authors: ['安舟'],
        page_start: 183,
        page_end: 209,
        dates: [{ year: 2017 }],
      },
      {
        title: '第三部 把文化大革命制度化（1968-1976） 第八章 工农兵学员',
        authors: ['安舟'],
        page_start: 211,
        page_end: 233,
        dates: [{ year: 2017 }],
      },
      {
        title: '第四部 新时代（1976-现在） 第九章 重建政治资本及文化资本的基础',
        authors: ['安舟'],
        page_start: 237,
        page_end: 255,
        dates: [{ year: 2017 }],
      },
      {
        title: '第四部 新时代（1976-现在） 第十章 红色工程师们的胜利',
        authors: ['安舟'],
        page_start: 257,
        page_end: 271,
        dates: [{ year: 2017 }],
      },
      {
        title: '第四部 新时代（1976-现在） 第十一章 技术专家治国与资本主义',
        authors: ['安舟'],
        page_start: 273,
        page_end: 285,
        dates: [{ year: 2017 }],
      },
      {
        title: '结论',
        authors: ['安舟'],
        page_start: 289,
        page_end: 305,
        dates: [{ year: 2017 }],
      },
      {
        title: '参考资料',
        authors: ['安舟'],
        page_start: 307,
        page_end: 317,
        dates: [{ year: 2017 }],
      },
      {
        title: '参考文献',
        authors: ['安舟'],
        page_start: 319,
        page_end: 343,
        dates: [{ year: 2017 }],
      },
    ],
    ocr: { content_thresholds: [0.076, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/a7a7ea71-b8fd-46ae-9018-f51b25238381.pdf',
};
