export default {
  entity: {
    id: 'a9839e34-3274-4f8b-a806-82479ee20823',
    name: '红旗一九七二年第四期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/a9839e34-3274-4f8b-a806-82479ee20823.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '要提倡顾全大局',
        authors: ['钟实'],
        page_start: 8,
        page_end: 12,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '正确理解和处理政治与业务的关系',
        authors: ['路阳'],
        page_start: 13,
        page_end: 18,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '读一点世界史',
        authors: ['史军'],
        page_start: 19,
        page_end: 24,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '使社会主义的服务性工作越做越好',
        authors: ['金枫'],
        page_start: 25,
        page_end: 29,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '以路线为纲搞好企业管理——大连钢厂如何搞好企业管理的调查报告',
        authors: ['旅大市革命委员会调查组'],
        page_start: 30,
        page_end: 35,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '把党的政策交给群众',
        authors: ['河北肥乡县河头堡公社西河头堡大队党支部'],
        page_start: 36,
        page_end: 39,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '发扬军民一致的光荣传统',
        authors: ['中国人民解放军兰州部队某部“英雄八连”'],
        page_start: 40,
        page_end: 43,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '红色娘子军',
        authors: ['中国京剧团'],
        page_start: 44,
        page_end: 70,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.47,
          content_thresholds: [0, 0.15, 0, 0.2],
        },
        dates: [{ year: 1972, month: 1 }],
      },
      {
        title: '移植创作中的优秀成果——评革命现代京剧《红色娘子军》',
        authors: ['宋鸿华'],
        page_start: 71,
        page_end: 74,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '我们的头脑是一个加工厂——从大型磨床的设计制透看先验论的破产',
        authors: ['王德法'],
        page_start: 75,
        page_end: 78,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '聪明来自实践',
        authors: ['王波'],
        page_start: 79,
        page_end: 82,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '正确认识思想和物质的关系',
        authors: ['天津第一炼钢厂平炉车间'],
        page_start: 83,
        page_end: 86,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '怎样看待群众中新流行的简化字？',
        authors: ['郭沫若'],
        page_start: 87,
        page_end: 88,
        dates: [{ year: 1972, month: 3, day: 23 }],
      },
      {
        title: '教育青年应注意的问题',
        authors: ['贺德富', '卢金才', '陈国柱', '季秀林'],
        page_start: 89,
        page_end: 90,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '正确理解和处理政治与业务的关系',
        authors: ['路阳'],
        page_start: 13,
        page_end: 18,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '积极引导青工认真看书学习',
        authors: ['缪梅娣'],
        page_start: 91,
        page_end: 93,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '应该重视下乡知识青年的文化学习',
        authors: ['长春市郊区五名下乡知识青年'],
        page_start: 94,
        page_end: 94,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '教育青年服从革命需要',
        authors: ['李祥林'],
        page_start: 95,
        page_end: 96,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
      {
        title: '要加强对干部子女的思想教育',
        authors: ['长春市第十一中学十名教师'],
        page_start: 96,
        page_end: 97,
        dates: [{ year: 1972, month: 4, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/a9839e34-3274-4f8b-a806-82479ee20823.pdf',
};
