export default {
  entity: {
    id: 'aebb881b-bed6-48db-855c-e3b8ef36cc28',
    name: '红旗一九六四年第十六期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/aebb881b-bed6-48db-855c-e3b8ef36cc28.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title:
          '中共高层的中央委员会对于苏联共产党中央委员会七月三十日来信的复信',
        authors: ['中国共产党中央委员会'],
        page_start: 3,
        page_end: 5,
        dates: [{ year: 1964, month: 8, day: 30 }],
      },
      {
        title: '苏共中央一九六四年七月三十日给中共中央的信',
        authors: ['苏联共产党中央委员会'],
        page_start: 6,
        page_end: 8,
        dates: [{ year: 1964, month: 7, day: 30 }],
      },
      {
        title: '哲学战线上的信论战——关于杨献珍同志的“合二而一”论的讨论报道',
        authors: ['红旗杂志报道员'],
        page_start: 9,
        page_end: 13,
        dates: [{ year: 1964 }],
      },
      {
        title: '放手发动群众，正确地领导农业的技术改革',
        authors: ['王任重'],
        page_start: 14,
        page_end: 22,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '留有余地是一个积极的方针',
        authors: ['李成瑞'],
        page_start: 23,
        page_end: 28,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '好中求多、多中求快、好中求省',
        authors: ['许辛学'],
        page_start: 28,
        page_end: 30,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '美帝国主义是亚洲、非洲和拉丁美洲石油资源的最大掠夺者',
        authors: ['施经综'],
        page_start: 31,
        page_end: 41,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '佛教思想和中国哲学思想——读《汉——唐中国佛教思想论集》',
        authors: ['孔繁'],
        page_start: 42,
        page_end: 45,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
      {
        title: '坚持革命方向——京剧现代戏观摩演出大会演出节目观后',
        authors: ['王朝闻'],
        page_start: 46,
        page_end: 55,
        dates: [{ year: 1964 }],
        ocr: { auto_vsplit: false, vsplit: 0.385 },
      },
    ],
    ocr: { content_thresholds: [0.07, 0.165, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/aebb881b-bed6-48db-855c-e3b8ef36cc28.pdf',
};
