export default {
  entity: {
    id: 'aed46e0c-566f-4904-9197-3e2c860ef9c0',
    name: '内蒙古挖肃灾难实录（南蒙古人权信息中心2011年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '巴彦泰著，南蒙古人权信息中心整理',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/aed46e0c-566f-4904-9197-3e2c860ef9c0.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '前言',
        authors: ['巴彦泰'],
        page_start: 4,
        page_end: 7,
        dates: [{ year: 2011 }],
      },
      {
        title: '第一编 内蒙古“文化大革命”中的“挖肃”运动',
        authors: ['巴彦泰'],
        page_start: 8,
        page_end: 41,
        dates: [{ year: 2011 }],
      },
      {
        title: '第二编 中央《五·二二指示》挖“内人党”停下来，平反、放人',
        authors: ['巴彦泰'],
        page_start: 42,
        page_end: 51,
        dates: [{ year: 2011 }],
      },
      {
        title: '第三编 “挖肃”所造成的民族灾难',
        authors: ['巴彦泰'],
        page_start: 52,
        page_end: 91,
        dates: [{ year: 2011 }],
      },
      {
        title: '第四编 广大干部群众反“挖肃”反迫害，要求平反昭雪的斗争',
        authors: ['巴彦泰'],
        page_start: 92,
        page_end: 116,
        dates: [{ year: 2011 }],
      },
      {
        title: '第五编 彻底平反“新内人党”冤假错案',
        authors: ['巴彦泰'],
        page_start: 117,
        page_end: 128,
        dates: [{ year: 2011 }],
      },
      {
        title: '第六编 对滕海清“挖肃”罪行的声讨',
        authors: ['巴彦泰'],
        page_start: 129,
        page_end: 143,
        dates: [{ year: 2011 }],
      },
      {
        title: '第七编 对滕海清发动的这场“挖肃”运动的思考',
        authors: ['巴彦泰'],
        page_start: 144,
        page_end: 219,
        dates: [{ year: 2011 }],
      },
    ],
    ocr: {
      standard_paragraph_merge_strategy_threshold: 0.171,
      differential_paragraph_merge_strategy_threshold: 0,
      content_thresholds: [0, 0, 0, 0],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/aed46e0c-566f-4904-9197-3e2c860ef9c0.pdf',
};
