export default {
  entity: {
    id: 'aee1f9e8-a37b-4f7a-8a7c-bcea461eb5fc',
    name: '红旗一九七五年第二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/aee1f9e8-a37b-4f7a-8a7c-bcea461eb5fc.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中国共产党第十届中央委员会第二次会议公报',
        alias: '中国共产党第十届中央委员会第二次全体会议公报',
        authors: [],
        page_start: 8,
        page_end: 8,
        dates: [{ year: 1975, month: 1, day: 17 }],
      },
      {
        title: '中华人民共和国全国人民代表大会公告',
        authors: [],
        page_start: 9,
        page_end: 17,
        dates: [{ year: 1975, month: 1, day: 17 }],
      },
      {
        title: '张春桥在第四届全国人民代表大会关于修改宪法的报告',
        alias: '关于修改宪法的报告',
        authors: ['张春桥'],
        page_start: 18,
        page_end: 22,
        dates: [{ year: 1975, month: 1, day: 13 }],
      },
      {
        title: '政府工作报告',
        authors: ['周恩来'],
        page_start: 23,
        page_end: 30,
        dates: [{ year: 1975, month: 1, day: 13 }],
      },
      {
        title:
          '中华人民共和国第四届全国人民代表大会第一次会议关于政府工作报告的决议',
        authors: [],
        page_start: 30,
        page_end: 30,
        dates: [{ year: 1975, month: 1, day: 17 }],
      },
      {
        title: '中华人民共和国第四届全国人民代表大会第一次会议新闻公报',
        authors: [],
        page_start: 31,
        page_end: 34,
        dates: [{ year: 1975, month: 1, day: 17 }],
      },
      {
        title:
          '中华人民共和国第四届全国人民代表大会第一次会议主席团和秘书长名单',
        authors: [],
        page_start: 34,
        page_end: 35,
        dates: [{ year: 1975, month: 1, day: 13 }],
      },
      {
        title: '中华人民共和国全国人民代表大会公告',
        authors: [],
        page_start: 36,
        page_end: 37,
        dates: [{ year: 1975, month: 1, day: 17 }],
      },
      {
        title: '中华人民共和国全国人民代表大会公告',
        authors: [],
        page_start: 37,
        page_end: 38,
        dates: [{ year: 1975, month: 1, day: 17 }],
      },
      {
        title: '认真学习无产阶级专政的理论',
        authors: ['池恒'],
        page_start: 39,
        page_end: 44,
        dates: [{ year: 1975, month: 2 }],
      },
      {
        title: '无产阶级专政的历史任务——学习《伟大的创举》',
        authors: ['周斯'],
        page_start: 45,
        page_end: 51,
        dates: [{ year: 1975, month: 2 }],
      },
      {
        title: '坚持无产阶级对资产阶级的专政',
        authors: ['路阳'],
        page_start: 52,
        page_end: 58,
        dates: [{ year: 1975, month: 2 }],
      },
      {
        title: '切实执行民主集中制',
        authors: ['向晖'],
        page_start: 59,
        page_end: 64,
        dates: [{ year: 1975, month: 2 }],
      },
      {
        title: '彻底地为人民的利益工作——学习《为人民服务》',
        authors: ['中国共产党平谷县委员会'],
        page_start: 65,
        page_end: 68,
        dates: [{ year: 1975, month: 2 }],
      },
      {
        title: '加强社会主义教育',
        authors: ['庄立'],
        page_start: 69,
        page_end: 74,
        dates: [{ year: 1975, month: 2 }],
      },
      {
        title: '论刘禹锡的政治诗',
        authors: ['闻军'],
        page_start: 75,
        page_end: 84,
        dates: [{ year: 1975, month: 2 }],
      },
      {
        title: '战争问题中的唯心论和机械论——批判林彪的“六个战术原则”',
        authors: ['柯术'],
        page_start: 85,
        page_end: 91,
        dates: [{ year: 1975, month: 2 }],
      },
      {
        title: '增强革命团结 发展大好形势',
        authors: ['呼和浩特铁路局党委会'],
        page_start: 92,
        page_end: 95,
        dates: [{ year: 1975, month: 2 }],
      },
      {
        title: '进一步加强民族团结',
        authors: ['阿衣木汗', '沙马力汗'],
        page_start: 96,
        page_end: 98,
        dates: [{ year: 1975, month: 2 }],
      },
      {
        title: '当前资本主义世界的经济危机',
        authors: ['靳南'],
        page_start: 99,
        page_end: 105,
        dates: [{ year: 1975, month: 2 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/aee1f9e8-a37b-4f7a-8a7c-bcea461eb5fc.pdf',
};
