export default {
  entity: {
    id: 'af5c1a90-1874-4bc5-abe1-8b49a9583f81',
    name: '红旗一九五九年第二十四期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/af5c1a90-1874-4bc5-abe1-8b49a9583f81.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '进一步加强人民公社党组织的领导作用',
        authors: ['安子文'],
        page_start: 3,
        page_end: 10,
        dates: [{ year: 1959, month: 12 }],
      },
      {
        title: '党的团结和纪律',
        authors: ['王从吾'],
        page_start: 11,
        page_end: 17,
        dates: [{ year: 1959, month: 12 }],
      },
      {
        title: '文艺工作者的世界观问题',
        authors: ['闻师润'],
        page_start: 18,
        page_end: 22,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 12 }],
      },
      {
        title: '保持工业生产在高速度发展中均衡地上升',
        authors: ['许辛学'],
        page_start: 23,
        page_end: 25,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 12 }],
      },
      {
        title: '克服薄弱环节，实现工业生产的全面跃进',
        authors: ['孙洪志'],
        page_start: 25,
        page_end: 30,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 12 }],
      },
      {
        title: '发挥人民公社威力，加速发展林业',
        authors: ['惠中权'],
        page_start: 31,
        page_end: 36,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 12 }],
      },
      {
        title: '数学和生产实践',
        authors: ['关肇直'],
        page_start: 37,
        page_end: 42,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 12 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/af5c1a90-1874-4bc5-abe1-8b49a9583f81.pdf',
};
