export default {
  entity: {
    id: 'affe9b6d-35b6-4327-a9dd-592e9e4c6320',
    name: '文革通讯第16、17期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '浙江工农兵美术大学毛泽东主义红卫兵战斗队、毛泽东主义红卫兵',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives15/main/affe9b6d-35b6-4327-a9dd-592e9e4c6320.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '周总理、中央文革小组对农林口无产阶级文化大革命的最新指示',
        authors: ['江青', '陈伯达', '周恩来'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967 }],
      },
      {
        title: '周总理关于安徽问题的电话指示',
        authors: ['周恩来'],
        page_start: 1,
        page_end: 2,
        dates: [{ year: 1967, month: 4, day: 12 }],
      },
      {
        title: '江青同志讲话（要点）',
        authors: ['江青'],
        page_start: 2,
        page_end: 3,
        dates: [{ year: 1967, month: 4, day: 16 }],
      },
      {
        title: '康生同志讲话（要点）',
        authors: ['康生'],
        page_start: 3,
        page_end: 3,
        dates: [{ year: 1967, month: 4, day: 16 }],
      },
      {
        title: '陈伯达同志讲话（要点）',
        authors: ['陈伯达'],
        page_start: 3,
        page_end: 4,
        dates: [
          { year: 1967, month: 4, day: 16 },
          { year: 1967, month: 4, day: 13 },
        ],
      },
      {
        title: '周总理三月二十八日接见计委口时的讲话',
        authors: ['周恩来'],
        page_start: 4,
        page_end: 4,
        dates: [{ year: 1967, month: 3, day: 28 }],
      },
      {
        title:
          '陈伯达、戚本禹等中央负责同志在三月二十七日下午四时在北大外文楼和同学们的讲话大致内容',
        authors: ['戚本禹', '陈伯达'],
        page_start: 4,
        page_end: 5,
        dates: [{ year: 1967, month: 3, day: 28 }],
      },
      {
        title: '周总理、江青等同志谈刘邓',
        authors: ['周恩来', '江青', '陈伯达'],
        page_start: 5,
        page_end: 5,
        dates: [{ year: 1967, month: 4, day: 4 }],
      },
      {
        title: '中央首长谈刘记黑《修养》',
        authors: ['周恩来', '张春桥', '戚本禹', '姚文元', '《红旗》杂志评论员'],
        page_start: 5,
        page_end: 6,
        dates: [
          { year: 1967, month: 2, day: 26 },
          { year: 1967, month: 2, day: 17 },
          { year: 1967, month: 2, day: 25 },
          { year: 1967, month: 2, day: 18 },
          { year: 1967, month: 1, day: 27 },
          { year: 1967, month: 2, day: 29 },
        ],
      },
      {
        title: '《人民日报》关于批判刘邓的意见',
        authors: ['《人民日报》编辑部'],
        page_start: 6,
        page_end: 6,
        dates: [{ year: 1967 }],
      },
      {
        title: '师大一附中刘平平揭发刘少奇、王光美大字报摘录',
        authors: ['刘平平'],
        page_start: 6,
        page_end: 7,
        dates: [{ year: 1967 }],
      },
      {
        title: '炮打陈毅，解放外事口',
        authors: ['《文革通讯》编辑部'],
        page_start: 7,
        page_end: 9,
        dates: [{ year: 1967, month: 4, day: 28 }],
      },
      {
        title: '刘少奇和王光美出国经过新疆的片段',
        authors: ['《文革通讯》编辑部'],
        page_start: 9,
        page_end: 9,
        dates: [{ year: 1967, month: 4, day: 28 }],
      },
      {
        title: '邓小平的丑史',
        authors: ['《文革通讯》编辑部'],
        page_start: 9,
        page_end: 10,
        dates: [{ year: 1967, month: 4, day: 28 }],
      },
      {
        title: '北京通讯',
        authors: ['《文革通讯》编辑部'],
        page_start: 10,
        page_end: 13,
        dates: [{ year: 1967, month: 4, day: 28 }],
      },
      {
        title: '王光美为“桃源经验”翻案决没有好下场',
        authors: ['《文革通讯》编辑部'],
        page_start: 13,
        page_end: 13,
        dates: [{ year: 1967, month: 4, day: 28 }],
      },
      {
        title: '徐景贤同志四月十二日讲话摘要',
        authors: ['徐景贤'],
        page_start: 13,
        page_end: 14,
        dates: [{ year: 1967, month: 4, day: 12 }],
      },
      {
        title: '徐景贤同志谈电影《清宫秘史》',
        authors: ['徐景贤'],
        page_start: 14,
        page_end: 14,
        dates: [{ year: 1967 }],
      },
      {
        title: '反动的“永华影业公司”的一些情况介绍',
        authors: ['上海红旗电影制片厂《红旗战报》编辑部'],
        page_start: 14,
        page_end: 15,
        dates: [{ year: 1967 }],
      },
      {
        title: '祖国各地',
        authors: ['《文革通讯》编辑部'],
        page_start: 15,
        page_end: 16,
        dates: [{ year: 1967, month: 4, day: 28 }],
      },
    ],
    ocr: undefined,
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives15/affe9b6d-35b6-4327-a9dd-592e9e4c6320.pdf',
};
