export default {
  entity: {
    id: 'b092f486-a733-4d2f-82d9-318d98144572',
    name: '红旗一九五九年第二十一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/b092f486-a733-4d2f-82d9-318d98144572.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '关于工业战线的群众运动',
        authors: ['柯庆施'],
        page_start: 3,
        page_end: 11,
        dates: [{ year: 1959, month: 11 }],
      },
      {
        title:
          '观大局，看主流，辨风向，调动积极因素——从一个环节看党的总路线在工业战线上的伟大胜利',
        authors: ['余秋里'],
        page_start: 12,
        page_end: 16,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 11 }],
      },
      {
        title: '十月革命是世界人民胜利的旗帜',
        authors: ['《红旗》杂志编辑部'],
        page_start: 17,
        page_end: 19,
        dates: [{ year: 1959, month: 11 }],
      },
      {
        title: '列宁的伟大遗产——迎“列宁全集”中译本的出版',
        authors: ['姜椿芳'],
        page_start: 19,
        page_end: 21,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 11 }],
      },
      {
        title: '右倾机会主义就是企图为资本主义复辟开辟道路',
        authors: ['《红旗》杂志评论员'],
        page_start: 22,
        page_end: 24,
        dates: [{ year: 1959, month: 11 }],
      },
      {
        title: '党的教育方针在高等学校的胜利',
        authors: ['赵守一'],
        page_start: 25,
        page_end: 31,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 11 }],
      },
      {
        title: '多快好省地进行建设的一个范例',
        authors: ['赵鹏飞', '李晨'],
        page_start: 32,
        page_end: 39,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 11 }],
      },
      {
        title: '用实际行动保卫党的总路线',
        authors: ['张德生'],
        page_start: 40,
        page_end: 41,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 11 }],
      },
      {
        title: '坚持不断革命，坚持高速度',
        authors: ['江华'],
        page_start: 41,
        page_end: 44,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 11 }],
      },
      {
        title: '英雄与懦夫的分界线',
        authors: ['张仲良'],
        page_start: 44,
        page_end: 46,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 11 }],
      },
      {
        title: '在伟大胜利的基础上继续跃进',
        authors: ['欧阳钦'],
        page_start: 46,
        page_end: 48,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 11 }],
      },
      {
        title: '保卫和贯彻执行党的总路线',
        authors: ['杨尚奎'],
        page_start: 48,
        page_end: 51,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 11 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/b092f486-a733-4d2f-82d9-318d98144572.pdf',
};
