export default {
  entity: {
    id: 'b43aeded-1fb5-4ec8-812f-742210966d88',
    name: '红旗一九七四年第三期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/b43aeded-1fb5-4ec8-812f-742210966d88.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '认真学 深入批',
        authors: ['《红旗》杂志编辑部'],
        page_start: 6,
        page_end: 8,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
      {
        title: '批“克己复礼”──林彪妄图复辟资本主义的反动纲领',
        authors: ['《人民日报》编辑部'],
        page_start: 9,
        page_end: 10,
        dates: [{ year: 1974, month: 2, day: 20 }],
      },
      {
        title: '孔子和林彪都是政治骗子',
        authors: ['康立'],
        page_start: 11,
        page_end: 17,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
      {
        title: '秦统一六国起决定作用的是什么？',
        authors: ['李时'],
        page_start: 18,
        page_end: 24,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
      {
        title: '批林批孔是反修防修的伟大斗争',
        authors: ['燕枫'],
        page_start: 25,
        page_end: 29,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
      {
        title: '揭穿“己所不欲，勿施于人”的反动实质',
        authors: ['郭企元', '黄士耀'],
        page_start: 30,
        page_end: 32,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
      {
        title: '从“天马”的下场看天命论的破产',
        authors: ['乌云格日勒'],
        page_start: 33,
        page_end: 35,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
      {
        title: '污蔑劳动人民就是反对革命',
        authors: ['天津铁路分局天津站六号门工人评论组'],
        page_start: 36,
        page_end: 39,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
      {
        title: '我们革命妇女最恨孔孟之道',
        authors: ['大寨大队铁姑娘队'],
        page_start: 40,
        page_end: 42,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
      {
        title: '放手发动群众 掌握政策界限',
        authors: ['中国共产党上海第五钢铁厂委员会'],
        page_start: 43,
        page_end: 47,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
      {
        title: '联系路线斗争实际批林批孔',
        authors: ['河北安平县南王庄大队党支部'],
        page_start: 48,
        page_end: 50,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
      {
        title: '反修斗争的强大思想武器——学习《帝国主义是资本主义的最高阶段》',
        authors: ['辛风'],
        page_start: 51,
        page_end: 57,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
      {
        title: '到底是谁家的“工具”？——评安东尼奥尼的“申辩”',
        authors: ['华言'],
        page_start: 58,
        page_end: 62,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
      {
        title: '评晋剧《三上桃峰》',
        authors: ['初澜'],
        page_start: 63,
        page_end: 68,
        dates: [{ year: 1974, month: 2, day: 28 }],
      },
      {
        title: '从农业出发办好地方工业',
        authors: ['庄宁'],
        page_start: 69,
        page_end: 74,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
      {
        title: '让工农兵英雄形象牢固地占领故事片阵地',
        authors: ['江天'],
        page_start: 75,
        page_end: 79,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
      {
        title: '人类对地球的认识和改造',
        authors: ['李之棣'],
        page_start: 80,
        page_end: 89,
        dates: [{ year: 1974, month: 3, day: 3 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/b43aeded-1fb5-4ec8-812f-742210966d88.pdf',
};
