export default {
  entity: {
    id: 'b4f9521d-5d20-4269-9a9d-546fa046f0e8',
    name: '红旗一九六〇年第二十、二十一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/b4f9521d-5d20-4269-9a9d-546fa046f0e8.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中国人民革命胜利经验的基本总结——为“毛泽东选集”第四卷的出版而作',
        authors: ['《红旗》杂志编辑部'],
        page_start: 3,
        page_end: 15,
        dates: [{ year: 1960, month: 11 }],
      },
      {
        title: '伟大十月革命的道路的全人类解放的共同道路',
        authors: ['《红旗》杂志编辑部'],
        page_start: 16,
        page_end: 19,
        dates: [{ year: 1960, month: 11 }],
      },
      {
        title: '辩证法是革命的代数学——谈“毛泽东选集”第四卷',
        authors: ['邓力群', '吴江'],
        page_start: 20,
        page_end: 37,
        dates: [{ year: 1960, month: 11 }],
      },
      {
        title: '依靠群众，合理分配商品——重庆市合理分配商品的经验',
        authors: ['郑延石'],
        page_start: 38,
        page_end: 45,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 11 }],
      },
      {
        title: '广泛运用运筹学为社会主义建设服务',
        authors: ['刘季平'],
        page_start: 46,
        page_end: 51,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 11 }],
      },
      {
        title: '搞好生活，促进生产',
        authors: ['王桂冀'],
        page_start: 52,
        page_end: 55,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 11 }],
      },
      {
        title: '砀山县的田间科学研究活动',
        authors: ['刘钦鉴'],
        page_start: 56,
        page_end: 59,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 11 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/b4f9521d-5d20-4269-9a9d-546fa046f0e8.pdf',
};
