export default {
  entity: {
    id: 'b5f53339-13bb-4750-b15c-7d8b5f4def41',
    name: '红旗一九七〇年第九期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/b5f53339-13bb-4750-b15c-7d8b5f4def41.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '提高警惕保卫祖国──纪念中国人民解放军诞生四十三周年',
        alias: '提高警惕 保卫祖国──纪念中国人民解放军诞生四十三周年',
        authors: [
          '《红旗》杂志编辑部',
          '《人民日报》编辑部',
          '《解放军报》编辑部',
        ],
        page_start: 8,
        page_end: 10,
        dates: [{ year: 1970, month: 8, day: 1 }],
      },
      {
        title: '发扬爱国主义和国际主义的革命精神',
        authors: ['特级英雄黄继光生前所在连党支部'],
        page_start: 11,
        page_end: 13,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
      {
        title: '建设边疆 保卫祖国',
        authors: ['岩帅'],
        page_start: 14,
        page_end: 17,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
      {
        title: '政治思想领导永远是第一位的领导',
        authors: ['中国人民解放军沈阳部队某团党委会'],
        page_start: 18,
        page_end: 21,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
      {
        title: '共产党员应成为政治思想工作的模范',
        authors: ['白川'],
        page_start: 22,
        page_end: 24,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
      {
        title: '在改造世界观上狠下功夫',
        authors: ['中国人民解放军北京部队炮兵某师党委会'],
        page_start: 25,
        page_end: 28,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
      {
        title: '一支社会主义工业建设的开路先锋——江西九〇九地质队的调查报告',
        authors: ['江西省革委会、地质局联合调查组'],
        page_start: 29,
        page_end: 36,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
      {
        title: '一支土生土长的农业技术队伍——浙江淳安县的调查报告',
        authors: ['浙江省革命委员会调查组'],
        page_start: 37,
        page_end: 42,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
      {
        title:
          '在“鞍钢宪法”的光辉旗帜下不断前进——辽宁本溪钢铁公司钢厂的调查报告',
        authors: ['本溪市革命委员会、本溪钢铁公司革命委员会调查组'],
        page_start: 43,
        page_end: 47,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
      {
        title: '办好“小化纤”——上海小型化学纤维工业发展情况的调查',
        authors: ['上海市革命委员会调查组'],
        page_start: 48,
        page_end: 52,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
      {
        title: '办好小煤窑——广东阳春县的调查报告',
        authors: ['广东省革命委员会调查组'],
        page_start: 53,
        page_end: 55,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
      {
        title: '自力更生，坚持为农业服务——河南郾城县机械厂的调查报告',
        authors: ['郾城县革命委员会、郾城县人民武装部调查组'],
        page_start: 56,
        page_end: 59,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
      {
        title: '自力更生 开源节流——在解决原材料问题上的两种思想斗争',
        authors: ['成渝'],
        page_start: 60,
        page_end: 63,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
      {
        title: '深入开展群众性的大批判——安徽马鞍山市关于大批判战斗队的调查报告',
        authors: ['安徽省革命委员会调查组'],
        page_start: 64,
        page_end: 68,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
      {
        title: '用战备观点发展农村医疗卫生事业——湖南衡阳县上峰公社的调查报告',
        authors: ['衡阳县革委会、人武部、新华社记者联合调查组'],
        page_start: 69,
        page_end: 72,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
      {
        title: '从思想教育入手，整好建好团支部——陕西宝鸡县红旗大队的调查报告',
        authors: [
          '陕西省革命委员会、宝鸡地区革命委员会、宝鸡县革命委员会调查组',
        ],
        page_start: 73,
        page_end: 77,
        dates: [{ year: 1970, month: 9, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/b5f53339-13bb-4750-b15c-7d8b5f4def41.pdf',
};
