export default {
  entity: {
    id: 'b74a9165-6148-4a68-8c0b-01c2c2939c6b',
    name: '中华人民共和国史 第二卷 向社会主义过渡——中国经济与社会的转型（1953-1955）（中文大学2009年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '林蕴晖著，中文大学2009年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/b74a9165-6148-4a68-8c0b-01c2c2939c6b.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '总序：世纪视野下的中华人民共和国史',
        authors: ['金观涛'],
        page_start: 4,
        page_end: 6,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2007, month: 12 }],
      },
      {
        title: '导言',
        authors: ['林蕴晖'],
        page_start: 16,
        page_end: 34,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009 }],
      },
      {
        title: '第一章 向社会主义过渡的总路线',
        authors: ['林蕴晖'],
        page_start: 36,
        page_end: 88,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009 }],
      },
      {
        title: '第二章 粮食统购统销和对私有制改造的全面启动',
        authors: ['林蕴晖'],
        page_start: 90,
        page_end: 158,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009 }],
      },
      {
        title: '第三章 农业合作化“高潮”和单一公有制的建立',
        authors: ['林蕴晖'],
        page_start: 160,
        page_end: 251,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009 }],
      },
      {
        title: '第四章 贯彻总路线的思想动员',
        authors: ['林蕴晖'],
        page_start: 252,
        page_end: 287,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009 }],
      },
      {
        title: '第五章 高岗、饶漱石事件',
        authors: ['林蕴晖'],
        page_start: 288,
        page_end: 380,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009 }],
      },
      {
        title: '第六章 工业化建设的起步',
        authors: ['林蕴晖'],
        page_start: 382,
        page_end: 451,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009 }],
      },
      {
        title: '第七章 国家政治制度的确立',
        authors: ['林蕴晖'],
        page_start: 452,
        page_end: 490,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009 }],
      },
      {
        title: '第八章 由思想批判到肃反运动',
        authors: ['林蕴晖'],
        page_start: 492,
        page_end: 579,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009 }],
      },
      {
        title: '第九章 国防现代化的开端',
        authors: ['林蕴晖'],
        page_start: 580,
        page_end: 605,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009 }],
      },
      {
        title: '第十章 寻求和平共处',
        authors: ['林蕴晖'],
        page_start: 606,
        page_end: 684,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009 }],
      },
      {
        title: '后记',
        authors: ['林蕴晖'],
        page_start: 686,
        page_end: 686,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009, month: 2, day: 28 }],
      },
      {
        title: '大事记',
        authors: ['林蕴晖'],
        page_start: 688,
        page_end: 703,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009 }],
      },
      {
        title: '参考文献',
        authors: ['林蕴晖'],
        page_start: 704,
        page_end: 715,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009 }],
      },
      {
        title: '索引',
        authors: ['林蕴晖'],
        page_start: 716,
        page_end: 731,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2009 }],
      },
    ],
    ocr: { content_thresholds: [0.106, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/b74a9165-6148-4a68-8c0b-01c2c2939c6b.pdf',
};
