export default {
  entity: {
    id: 'b89504e4-9d2e-47cc-9b76-9285491859a3',
    name: '红旗一九六八年第五期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/b89504e4-9d2e-47cc-9b76-9285491859a3.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '认真学习两条路线斗争的历史',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        page_start: 8,
        page_end: 15,
        dates: [{ year: 1968 }],
      },
      {
        title: '在中国共产党第七届中央委员会第二次全体会议上的报告',
        authors: ['毛泽东'],
        page_start: 16,
        page_end: 30,
        dates: [{ year: 1949, month: 3, day: 5 }],
      },
      {
        title: '中国共产党第八届扩大的第十二次中央委员会全会公报',
        authors: [],
        page_start: 31,
        page_end: 36,
        dates: [{ year: 1968, month: 10, day: 31 }],
      },
      {
        title: '彻底埋葬“阶级斗争熄灭论”',
        authors: ['焦兆海'],
        page_start: 37,
        page_end: 38,
        dates: [{ year: 1968 }],
      },
      {
        title: '批臭复辟资本主义的“驯服工具论”',
        authors: ['张富贵'],
        page_start: 39,
        page_end: 41,
        dates: [{ year: 1968 }],
      },
      {
        title: '揭穿“党内和平论”的反动实质',
        authors: ['王炳贤', '吕福庭', '魏先德'],
        page_start: 41,
        page_end: 43,
        dates: [{ year: 1968 }],
      },
      {
        title: '“土专家”和农业教育革命——江苏省靖江县的调查报告',
        authors: ['靖江县革命委员会', '靖江县大兴公社革命委员会'],
        page_start: 44,
        page_end: 49,
        dates: [{ year: 1968 }],
      },
      {
        title: '一所贫下中农掌权的民办小学——从松树小学的成长看农村办学的方向',
        authors: ['辽宁省革命委员会', '解放军某部'],
        page_start: 50,
        page_end: 55,
        dates: [{ year: 1968 }],
      },
      {
        title: '“看不惯”与“看得惯”',
        authors: ['赵国华'],
        page_start: 56,
        page_end: 58,
        dates: [{ year: 1968 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/b89504e4-9d2e-47cc-9b76-9285491859a3.pdf',
};
