export default {
  entity: {
    id: 'bb9075c6-20db-4a3a-8689-0797ba380c08',
    name: '中华人民共和国史 第四卷 乌托邦运动——从大跃进到大饥荒（1958-1961）（中文大学2008年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '林蕴晖著，中文大学2008年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/bb9075c6-20db-4a3a-8689-0797ba380c08.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '总序：世纪视野下的中华人民共和国史',
        authors: ['金观涛'],
        page_start: 5,
        page_end: 7,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2007, month: 12 }],
      },
      {
        title: '导言',
        authors: ['林蕴晖'],
        page_start: 18,
        page_end: 23,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第一章 多快好省总路线出台',
        authors: ['林蕴晖'],
        page_start: 24,
        page_end: 123,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第二章 大跃进和人民公社的兴起',
        authors: ['林蕴晖'],
        page_start: 124,
        page_end: 185,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第三章 大炼钢铁和人民公社化运动',
        authors: ['林蕴晖'],
        page_start: 186,
        page_end: 278,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第四章 炮击金门与第二次台海危机',
        authors: ['林蕴晖'],
        page_start: 279,
        page_end: 331,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第五章 西藏平叛与西藏的社会改革',
        authors: ['林蕴晖'],
        page_start: 333,
        page_end: 373,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第六章 毛泽东“压缩空气”及其底线',
        authors: ['林蕴晖'],
        page_start: 374,
        page_end: 464,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第七章 庐山会议发生的重大转折',
        authors: ['林蕴晖'],
        page_start: 466,
        page_end: 535,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第八章 坚持“跃进”经济跌入谷底',
        authors: ['林蕴晖'],
        page_start: 536,
        page_end: 639,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第九章 制定政策挽救农村危局',
        authors: ['林蕴晖'],
        page_start: 640,
        page_end: 727,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '第十章 实行全面调整重建社会秩序',
        authors: ['林蕴晖'],
        page_start: 728,
        page_end: 798,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '大事记',
        authors: ['林蕴晖'],
        page_start: 800,
        page_end: 813,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '参考文献',
        authors: ['林蕴晖'],
        page_start: 814,
        page_end: 824,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
      {
        title: '索引',
        authors: ['林蕴晖'],
        page_start: 825,
        page_end: 841,
        tags: [{ name: '中文大学出版社', type: 'issuer' }],
        dates: [{ year: 2008 }],
      },
    ],
    ocr: { content_thresholds: [0.08, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/bb9075c6-20db-4a3a-8689-0797ba380c08.pdf',
};
