export default {
  entity: {
    id: 'bcc6ea43-92e3-426e-85db-a7b1941c7252',
    name: '红旗一九七三年第五期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/bcc6ea43-92e3-426e-85db-a7b1941c7252.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '批修整风是一次深刻的社会主义教育',
        authors: ['庄宁'],
        page_start: 8,
        page_end: 12,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title:
          '思想必须适应客观情况的发展——学习《中国农村的社会主义高潮》序言和按语',
        authors: ['冀岩'],
        page_start: 13,
        page_end: 17,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title: '拒腐蚀，永不沾',
        authors: ['田志松'],
        page_start: 18,
        page_end: 20,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title: '历史的经验值得注意——谈读一点中国近代史',
        authors: ['施斌'],
        page_start: 21,
        page_end: 29,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title: '发展农业的根本问题在路线',
        authors: ['安群'],
        page_start: 30,
        page_end: 35,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title: '转炉炉龄是怎样提高的？',
        authors: ['中国共产党首都钢铁公司炼钢厂委员会'],
        page_start: 36,
        page_end: 41,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title: '基本建设要集中力量打歼灭战',
        authors: ['郭建伟'],
        page_start: 42,
        page_end: 46,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title: '进一步做好出版工作',
        authors: ['郑磊'],
        page_start: 47,
        page_end: 51,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title: '我们工人要努力学习革命理论',
        authors: ['张福恒'],
        page_start: 52,
        page_end: 55,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title: '努力提高革命责任感',
        authors: ['张洪池'],
        page_start: 56,
        page_end: 60,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title: '做批判修正主义的火车头',
        authors: ['郭映福'],
        page_start: 61,
        page_end: 63,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title: '全世界无产者团结战斗的光辉诗篇——读《鲍狄埃诗选》',
        authors: ['司钟'],
        page_start: 64,
        page_end: 67,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title: '进一步发挥工人阶级的主力军作用',
        authors: ['《人民日报》编辑部'],
        page_start: 68,
        page_end: 70,
        dates: [{ year: 1973, month: 4, day: 24 }],
      },
      {
        title: '青年要站在革命队伍的前头——学习《青年运动的方向》的一点体会',
        authors: ['谭闻'],
        page_start: 71,
        page_end: 74,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title: '学习鲁迅 培养青年',
        authors: ['周建人'],
        page_start: 75,
        page_end: 79,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title: '我深深爱上了边疆的一草一木',
        authors: ['朱克家'],
        page_start: 80,
        page_end: 84,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
      {
        title: '全心全意同工农相结合',
        authors: ['颜景堂'],
        page_start: 85,
        page_end: 89,
        dates: [{ year: 1973, month: 5, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/bcc6ea43-92e3-426e-85db-a7b1941c7252.pdf',
};
