export default {
  entity: {
    id: 'bce97cc3-b541-4836-b5b2-a7d95b8a1598',
    name: '上海“文化大革命”史话（送审稿）（二）（1992.8）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '上海“文革”史料整理编纂小组，1992年8月',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/bce97cc3-b541-4836-b5b2-a7d95b8a1598.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '十三、两次“炮打”张春桥事件',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 2,
        page_end: 22,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '十四、造反派的内讧和大规模武斗',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 23,
        page_end: 34,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '十五、“改朝换代”的叫嚣和迫害干部的主要手段',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 35,
        page_end: 53,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '十六、一桩重大的政治阴谋——诬陷迫害陈丕显、曹荻秋',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 53,
        page_end: 65,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '十七、打击、摧残各级干部和社会知名人士',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 66,
        page_end: 84,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '十八、炮制集团性冤假错案',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 84,
        page_end: 96,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '十九、砸烂公、检、法',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 96,
        page_end: 107,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '二十、“游雪涛小组”',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 107,
        page_end: 114,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '二十一、“上体司”治安组',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 115,
        page_end: 121,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '二十二、“清档”与“防扩散”',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 122,
        page_end: 130,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '二十三、“一打三反”和清查“五·一六”运动',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 130,
        page_end: 139,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '二十四、从“文攻武卫”到市民兵指挥部',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 139,
        page_end: 154,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '二十五、“工总司”帮体系及其在“四人帮”篡党夺权中的作用',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 154,
        page_end: 167,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '二十六、江青、张春桥等利用召开“九大”进行的阴谋活动',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 167,
        page_end: 177,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '二十七、“文革”中的整党建党和市第四次党代表大会',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 177,
        page_end: 186,
        dates: [{ year: 1992, month: 8 }],
      },
    ],
    ocr: { auto_vsplit: true, vsplit: 0.5 },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/bce97cc3-b541-4836-b5b2-a7d95b8a1598.pdf',
};
