export default {
  entity: {
    id: 'be134e97-861f-44c0-87a6-a320e946b07d',
    name: '上海“文化大革命”史话（送审稿）（三）（1992.8）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '上海“文革”史料整理编纂小组，1992年8月',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/be134e97-861f-44c0-87a6-a320e946b07d.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '二十八、“九·一三事件”后江青集团对林彪在上海党羽的所谓清查工作',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 2,
        page_end: 9,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '二十九、江青集团从上海抽调帮派骨干去中央领导机构的猖狂活动',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 9,
        page_end: 19,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '三十、“批林批孔”中的第二次夺权',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 20,
        page_end: 37,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '三十一、“四人帮”驱策马、徐、王阴谋搞乱上海警备区和南京军区',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 37,
        page_end: 49,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '三十二、马、徐、王等组织策划“炮轰”国务院的几个突出事件',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 50,
        page_end: 64,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '三十三、“四人帮”在上海的党羽搞的“批邓、反击右倾翻案风”',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 65,
        page_end: 85,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '三十四、张、姚直接控制的“上海市委写作组”',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 85,
        page_end: 125,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '三十五、扑不灭的抗争烈火——上海人民与“四人帮”作斗争的几则事例',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 125,
        page_end: 139,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '三十六、武装叛乱的策动和破产',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 140,
        page_end: 174,
        dates: [{ year: 1992, month: 8 }],
      },
      {
        title: '后记',
        authors: ['上海“文革”史料整理编纂小组'],
        page_start: 175,
        page_end: 181,
        dates: [{ year: 1992, month: 8 }],
      },
    ],
    ocr: { auto_vsplit: true, vsplit: 0.5 },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/be134e97-861f-44c0-87a6-a320e946b07d.pdf',
};
