export default {
  entity: {
    id: 'becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa',
    name: '毛远新紧跟“四人帮”大反经验主义的部分罪行材料',
    internal: true,
    official: true,
    type: 'img',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/1.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/2.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/3.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/4.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/5.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/6.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/7.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/8.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/9.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/10.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/11.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/12.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/13.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/14.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa/15.png',
  },
  parser_option: {
    page_limits: [],
    ext: 'png',
    articles: [
      {
        title: '一、毛远新紧跟“四人帮”大反经验主义的罪行',
        authors: ['毛远新'],
        page_start: 2,
        page_end: 3,
        ocr_exceptions: { '2': { content_thresholds: [0, 0, 0.5, 0] } },
        dates: [
          { year: 1975, month: 3, day: 5 },
          { year: 1975, month: 3, day: 31 },
          { year: 1975, month: 4, day: 3 },
          { year: 1975, month: 4, day: 10 },
          { year: 1975, month: 4, day: 15 },
          { year: 1975, month: 4, day: 22 },
          { year: 1975, month: 4, day: 23 },
          { year: 1975, month: 4, day: 24 },
          { year: 1975, month: 4, day: 25 },
          { year: 1975, month: 11, day: 26 },
        ],
      },
      {
        title: '二、毛远新大反经验主义的言论（摘编）',
        authors: ['毛远新'],
        page_start: 3,
        page_end: 9,
        ocr_exceptions: { '9': { content_thresholds: [0, 0, 0, 0.5] } },
        dates: [
          { year: 1975, month: 3, day: 5 },
          { year: 1975, month: 3, day: 31 },
          { year: 1975, month: 4, day: 3 },
          { year: 1975, month: 4, day: 10 },
          { year: 1975, month: 4, day: 15 },
          { year: 1975, month: 4, day: 25 },
          { year: 1975, month: 7, day: 16 },
          { year: 1975, month: 7, day: 17 },
          { year: 1975, month: 11, day: 26 },
        ],
      },
      {
        title: '三、毛远新亲自修改的一份未发出的省委文件（大样）',
        authors: ['毛远新', '中共辽宁省委', '辽宁省革命委员会宣传组'],
        page_start: 9,
        page_end: 13,
        ocr_exceptions: {
          '9': { content_thresholds: [0, 0, 0.5, 0] },
          '13': { content_thresholds: [0, 0, 0, 0.5] },
        },
        dates: [
          { year: 1975, month: 4, day: 15 },
          { year: 1975, month: 4, day: 18 },
        ],
      },
      {
        title: '四、毛远新授意发表的第二次理论讨论会的消息报道',
        authors: ['辽宁日报', '中共辽宁省委', '辽宁省革命委员会宣传组'],
        page_start: 13,
        page_end: 15,
        ocr_exceptions: { '13': { content_thresholds: [0, 0, 0.5, 0] } },
        dates: [{ year: 1975, month: 4, day: 22 }],
      },
    ],
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives1/becd9f73-f6d4-4f1a-88ac-2fb3b1dfbffa',
};
