export default {
  entity: {
    id: 'bfe38dad-00f4-4779-9991-fa6a70bf11f1',
    name: '红旗一九七六年第一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/bfe38dad-00f4-4779-9991-fa6a70bf11f1.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '水调歌头·重上井冈山',
        authors: ['毛泽东'],
        page_start: 6,
        page_end: 6,
        ocr: {
          standard_paragraph_merge_strategy_threshold: 0.45,
          differential_paragraph_merge_strategy_threshold: 0,
          content_thresholds: [0, 0.16, 0, 0.2],
        },
        dates: [{ year: 1965, month: 5 }],
      },
      {
        title: '念奴娇·鸟儿问答',
        authors: ['毛泽东'],
        page_start: 6,
        page_end: 6,
        ocr: {
          standard_paragraph_merge_strategy_threshold: 0.45,
          differential_paragraph_merge_strategy_threshold: 0,
          content_thresholds: [0, 0.16, 0, 0.2],
        },
        dates: [{ year: 1965 }],
      },
      {
        title: '世上无难事只要肯登攀（一九七六年元旦社论）',
        alias: '世上无难事 只要肯登攀',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        page_start: 8,
        page_end: 11,
        dates: [{ year: 1976, month: 1, day: 1 }],
      },
      {
        title: '抓紧阶级斗争这个纲',
        authors: ['池恒'],
        page_start: 12,
        page_end: 17,
        dates: [{ year: 1976, month: 1, day: 1 }],
      },
      {
        title: '坚持党的基本路线——学习《关于正确处理人民内部矛盾的问题》',
        authors: ['程越'],
        page_start: 18,
        page_end: 24,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '注意老、中、青结合',
        authors: ['潘锋'],
        page_start: 25,
        page_end: 28,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '评论《水浒》的现实意义',
        authors: ['尹铭'],
        page_start: 29,
        page_end: 31,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '无产阶级专政与文化大革命',
        authors: ['钟实'],
        page_start: 32,
        page_end: 36,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '正确对待无产阶级文化大革命',
        authors: ['高明山'],
        page_start: 37,
        page_end: 40,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '大是大非问题一定要辩论清楚',
        authors: ['中国共产党朝阳农学院委员会'],
        page_start: 41,
        page_end: 46,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '教育革命“拖四个现代化的后腿”吗？',
        authors: ['复旦大学大批判组'],
        page_start: 47,
        page_end: 51,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '驳“今不如昔”论',
        authors: ['余凡'],
        page_start: 52,
        page_end: 55,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '教育革命好得很',
        authors: ['王春兰'],
        page_start: 56,
        page_end: 59,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '喜看工农兵学员茁壮成长',
        authors: ['段学复', '黄昆'],
        page_start: 60,
        page_end: 64,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '我们是怎样开展教育革命大辩论的',
        authors: ['清华大学建筑工程系党委会'],
        page_start: 65,
        page_end: 68,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '鼓舞我们战斗的宏伟诗篇——学习毛主席词二首',
        authors: ['袁水拍'],
        page_start: 69,
        page_end: 73,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title:
          '深入进行农村两条道路的斗争——纪念《中国农村的社会主义高潮》序言和按语发表二十周年',
        authors: ['向晖'],
        page_start: 74,
        page_end: 79,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '群众是真正的英雄——沙市工业为什么文化大革命以来增长三倍？',
        authors: ['湖北省革命委员会调查组'],
        page_start: 80,
        page_end: 83,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '在继续革命的道路上胜利前进',
        authors: ['山东莒南县厉家赛大队党总支'],
        page_start: 84,
        page_end: 87,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '抓路线教育 促战备工作',
        authors: ['中国人民解放军南京部队某部“硬骨头六连”党支部'],
        page_start: 88,
        page_end: 91,
        dates: [{ year: 1976, month: 1 }],
      },
      {
        title: '一部歌颂文化大革命的好影片——评《春苗》',
        authors: ['初澜'],
        page_start: 92,
        page_end: 97,
        dates: [{ year: 1976, month: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.16, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/bfe38dad-00f4-4779-9991-fa6a70bf11f1.pdf',
};
