export default {
  entity: {
    id: 'c0ae4e3a-f292-4359-9e09-2a859511e159',
    name: '红旗一九七三年第九期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/c0ae4e3a-f292-4359-9e09-2a859511e159.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '在中国共产党第十次全国代表大会上的报告',
        authors: ['周恩来'],
        page_start: 8,
        page_end: 20,
        dates: [{ year: 1973, month: 8, day: 24 }],
      },
      {
        title: '王洪文在中共十大上关于修改党章的报告',
        authors: ['王洪文'],
        page_start: 21,
        page_end: 26,
        dates: [{ year: 1973, month: 8, day: 24 }],
      },
      {
        title: '中国共产党章程',
        authors: [],
        page_start: 27,
        page_end: 31,
        dates: [{ year: 1973, month: 8, day: 28 }],
      },
      {
        title: '中国共产党第十次全国代表大会新闻公报',
        authors: [],
        page_start: 32,
        page_end: 38,
        dates: [{ year: 1973, month: 8, day: 29 }],
      },
      {
        title: '中国共产党第十届中央委员会第一次全体会议新闻公报',
        authors: [],
        page_start: 39,
        page_end: 39,
        dates: [{ year: 1973, month: 8, day: 30 }],
      },
      {
        title:
          '帝国主义是无产阶级社会革命的前夜——学习《帝国主义是资本主义的最高阶段》',
        authors: ['常谦'],
        page_start: 40,
        page_end: 46,
        dates: [{ year: 1973, month: 9, day: 3 }],
      },
      {
        title: '充分发挥无产阶级先锋队的领导作用',
        authors: ['安群'],
        page_start: 47,
        page_end: 51,
        dates: [{ year: 1973, month: 9, day: 3 }],
      },
      {
        title: '一条重要的历史经验',
        authors: ['田志松'],
        page_start: 52,
        page_end: 56,
        dates: [{ year: 1973, month: 9, day: 3 }],
      },
      {
        title: '善于从本质上发现群众的积极性——学习《介绍-一个合作社》',
        authors: ['俞彤'],
        page_start: 57,
        page_end: 61,
        dates: [{ year: 1973, month: 9, day: 3 }],
      },
      {
        title: '林彪是无产阶级专政的可耻叛徒',
        authors: ['甘戈'],
        page_start: 62,
        page_end: 66,
        dates: [{ year: 1973, month: 9, day: 3 }],
      },
      {
        title: '要团结，不要分裂——批判林彪分裂党的罪行',
        authors: ['北京怀柔县大蒲池沟大队党支部'],
        page_start: 67,
        page_end: 71,
        dates: [{ year: 1973, month: 9, day: 3 }],
      },
      {
        title: '努力实现工人阶级的历史任务——批判林彪破坏工人运动的罪行',
        authors: ['天津市建筑工程局工人批判组'],
        page_start: 72,
        page_end: 77,
        dates: [{ year: 1973, month: 9, day: 3 }],
      },
      {
        title: '深入批林整风，加快牧区建设步伐',
        authors: ['宝日勒岱'],
        page_start: 78,
        page_end: 81,
        dates: [{ year: 1973, month: 9, day: 3 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/c0ae4e3a-f292-4359-9e09-2a859511e159.pdf',
};
