export default {
  entity: {
    id: 'c21f8808-2334-4e60-a047-27a52e8adbce',
    name: '夏邦银、朱洪霞、胡厚民等人的言论节录',
    internal: false,
    official: true,
    type: 'img',
    author: '中共武汉市委材料组',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/1.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/2.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/3.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/4.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/5.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/6.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/7.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/8.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/9.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/10.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/11.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/12.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/13.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/14.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/15.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/16.png,https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives1/main/c21f8808-2334-4e60-a047-27a52e8adbce/17.png',
  },
  parser_option: {
    page_limits: [],
    ext: 'png',
    articles: [
      {
        title: '前言',
        authors: ['中共武汉市委材料组'],
        page_start: 2,
        page_end: 3,
        ocr_exceptions: { '3': { content_thresholds: [0, 0.08, 0, 0.5] } },
        dates: [{ year: 1976, month: 12 }],
      },
      {
        title: '给伟大领袖毛主席的一封信',
        authors: ['夏邦银', '朱洪霞', '胡厚民'],
        page_start: 4,
        page_end: 5,
        ocr_exceptions: {
          '4': { content_thresholds: [0, 0.08, 0.5, 0] },
          '5': { content_thresholds: [0, 0.08, 0, 0.5] },
        },
        dates: [{ year: 1976, month: 2, day: 23 }],
      },
      {
        title: '口号报',
        authors: ['夏邦银', '朱洪霞', '胡厚民'],
        page_start: 5,
        page_end: 5,
        ocr_exceptions: { '5': { content_thresholds: [0, 0.08, 0.5, 0] } },
        dates: [{ year: 1976, month: 2 }],
      },
      {
        title: '跟上形势端正态度积极领导——致省、市委主要负责同志的一封公开信',
        authors: ['夏邦银', '朱洪霞', '胡厚民'],
        page_start: 6,
        page_end: 6,
        dates: [{ year: 1976, month: 3, day: 1 }],
      },
      {
        title: '朱洪霞在武重俱乐部集会上的讲话（节录）',
        authors: ['朱洪霞', '戴行江'],
        page_start: 7,
        page_end: 7,
        ocr_exceptions: { '7': { content_thresholds: [0, 0.08, 0, 0.5] } },
        dates: [{ year: 1976, month: 3, day: 8 }],
      },
      {
        title: '朱洪霞在武重俱乐部集会上的讲话（节录）',
        authors: ['朱洪霞'],
        page_start: 7,
        page_end: 7,
        ocr_exceptions: { '7': { content_thresholds: [0, 0.08, 0.5, 0] } },
        dates: [{ year: 1976, month: 3, day: 14 }],
      },
      {
        title: '朱洪霞在市房地局礼堂集会上的讲话（节录）',
        authors: ['朱洪霞'],
        page_start: 7,
        page_end: 8,
        ocr_exceptions: {
          '7': { content_thresholds: [0, 0.08, 0.5, 0] },
          '8': { content_thresholds: [0, 0.08, 0, 0.5] },
        },
        dates: [{ year: 1976, month: 3, day: 15 }],
      },
      {
        title: '朱洪霞在市房地局礼堂集会上的讲话（节录）',
        authors: ['朱洪霞', '胡厚民', '聂年生'],
        page_start: 8,
        page_end: 9,
        ocr_exceptions: { '9': { content_thresholds: [0, 0.08, 0, 0.5] } },
        dates: [{ year: 1976, month: 3, day: 15 }],
      },
      {
        title: '吴正斌在武胜路集会上的讲话（节录）',
        authors: ['吴正斌'],
        page_start: 9,
        page_end: 9,
        ocr_exceptions: { '9': { content_thresholds: [0, 0.08, 0, 0.5] } },
        dates: [{ year: 1976, month: 3, day: 21 }],
      },
      {
        title: '朱洪霞等人在市建工局礼堂集会上的讲话（节录）',
        authors: ['胡厚民', '朱洪霞', '顾建棠', '吴焱金'],
        page_start: 9,
        page_end: 11,
        ocr_exceptions: { '9': { content_thresholds: [0, 0.08, 0.5, 0] } },
        dates: [{ year: 1976, month: 3, day: 25 }],
      },
      {
        title: '胡厚民、朱洪霞等人在市政三公司集会上的讲话（节录）',
        authors: ['胡厚民', '朱洪霞'],
        page_start: 11,
        page_end: 12,
        ocr_exceptions: { '11': { content_thresholds: [0, 0.08, 0.5, 0] } },
        dates: [{ year: 1976, month: 3, day: 31 }],
      },
      {
        title: '胡厚民等人在市建工局礼堂集会上的讲话（节录）',
        authors: ['胡厚民', '吴焱金'],
        page_start: 12,
        page_end: 13,
        ocr_exceptions: {
          '12': { content_thresholds: [0, 0.08, 0.5, 0] },
          '13': { content_thresholds: [0, 0.08, 0, 0.5] },
        },
        dates: [{ year: 1976, month: 4, day: 1 }],
      },
      {
        title: '朱洪霞、胡厚民等人在武胜路街头集会上的讲话（节录）',
        authors: ['胡厚民', '朱洪霞'],
        page_start: 13,
        page_end: 14,
        ocr_exceptions: { '14': { content_thresholds: [0, 0.08, 0, 0.5] } },
        dates: [{ year: 1976, month: 4, day: 4 }],
      },
      {
        title: '朱洪霞、胡厚民在市建工局礼堂集会上的讲话（节录）',
        authors: ['胡厚民', '朱洪霞'],
        page_start: 14,
        page_end: 14,
        dates: [{ year: 1976, month: 4, day: 12 }],
      },
      {
        title: '朱洪霞、胡厚民在江汉工人文化宫集会上的讲话（节录）',
        authors: ['胡厚民', '朱洪霞'],
        page_start: 14,
        page_end: 15,
        ocr_exceptions: { '14': { content_thresholds: [0, 0.08, 0.5, 0] } },
        dates: [{ year: 1976, month: 4, day: 13 }],
      },
      {
        title: '顾建棠等人在市建工局礼堂集会上的讲话（节录）',
        authors: ['顾建棠'],
        page_start: 15,
        page_end: 15,
        ocr_exceptions: { '15': { content_thresholds: [0, 0.08, 0.5, 0] } },
        dates: [{ year: 1976, month: 4, day: 15 }],
      },
      {
        title: '朱洪霞在国棉六厂子弟小学集会上的讲话（节录）',
        authors: ['朱洪霞'],
        page_start: 15,
        page_end: 16,
        ocr_exceptions: { '15': { content_thresholds: [0, 0.08, 0.5, 0] } },
        dates: [{ year: 1976, month: 4, day: 28 }],
      },
      {
        title: '夏邦银、胡厚民等人在长航集会上的讲话（节录）',
        authors: ['夏邦银', '胡厚民'],
        page_start: 16,
        page_end: 16,
        ocr_exceptions: { '16': { content_thresholds: [0, 0.08, 0, 0.5] } },
        dates: [{ year: 1976, month: 5, day: 8 }],
      },
      {
        title: '朱洪霞在江岸区环卫所集会上的讲话（节录）',
        authors: ['朱洪霞'],
        page_start: 16,
        page_end: 16,
        dates: [{ year: 1976, month: 5, day: 22 }],
      },
      {
        title: '夏邦银、胡厚民讲话（节录）',
        authors: ['夏邦银', '胡厚民'],
        page_start: 16,
        page_end: 17,
        ocr_exceptions: {
          '16': { content_thresholds: [0, 0.08, 0.5, 0] },
          '17': { content_thresholds: [0, 0.08, 0, 0.5] },
        },
        dates: [{ year: 1976, month: 7, day: 9 }],
      },
      {
        title: '潘洪斌在市房地局礼堂集会上的讲话（节录）',
        authors: ['潘洪斌'],
        page_start: 17,
        page_end: 17,
        ocr_exceptions: { '17': { content_thresholds: [0, 0.08, 0, 0.5] } },
        dates: [{ year: 1976, month: 7, day: 13 }],
      },
      {
        title: '彭勋、顾建棠在国棉六厂集会上的讲话（节录）',
        authors: ['彭勋', '顾建棠'],
        page_start: 17,
        page_end: 17,
        dates: [{ year: 1976, month: 7, day: 14 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.08, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives1/c21f8808-2334-4e60-a047-27a52e8adbce',
};
