export default {
  entity: {
    id: 'c2789a7d-95d2-4f51-a1fb-dcd44509509c',
    name: '红旗一九七〇年第六期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/c2789a7d-95d2-4f51-a1fb-dcd44509509c.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '全世界人民团结起来，打败美国侵略者及其一切走狗',
        authors: ['毛泽东'],
        page_start: 6,
        page_end: 7,
        dates: [{ year: 1970, month: 5, day: 20 }],
      },
      {
        title: '改造世界观──纪念《在延安文艺座谈会上的讲话》发表二十八周年',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        page_start: 8,
        page_end: 10,
        dates: [{ year: 1970, month: 5, day: 23 }],
      },
      {
        title: '沙家浜',
        authors: ['北京京剧团'],
        page_start: 11,
        page_end: 42,
        dates: [{ year: 1970, month: 5 }],
      },
      {
        title: '《在延安文艺座谈会上的讲话》照耀着《沙家浜》的成长',
        authors: ['北京京剧团《沙家浜》剧组'],
        page_start: 43,
        page_end: 52,
        dates: [{ year: 1970, month: 6, day: 1 }],
      },
      {
        title:
          '演革命戏 做革命人──纪念毛主席的光辉著作《在延安文艺座谈会上的讲话》发表二十八周年',
        authors: ['上海京剧团《智取威虎山》剧组'],
        page_start: 53,
        page_end: 57,
        dates: [{ year: 1970, month: 6, day: 1 }],
      },
      {
        title: '文艺革命的指路明灯——学习《在延安文艺座谈会上的讲话》的体会',
        authors: ['迈新'],
        page_start: 58,
        page_end: 62,
        dates: [{ year: 1970, month: 6, day: 1 }],
      },
      {
        title:
          '永远沿着为工农兵服务的方向前进——学习《在延安文艺座谈会上的讲话》',
        authors: ['广西壮族自治区革命委员会写作小组'],
        page_start: 63,
        page_end: 69,
        dates: [{ year: 1970, month: 6, day: 1 }],
      },
      {
        title: '毛主席领导的红军是英雄汉——批判反共历史剧《石达开的末路》',
        authors: ['钟岸'],
        page_start: 70,
        page_end: 80,
        dates: [{ year: 1970, month: 6, day: 1 }],
      },
      {
        title: '工业必须大力支援农业——驳“支农吃亏论”',
        authors: ['齐永红'],
        page_start: 81,
        page_end: 84,
        dates: [{ year: 1970, month: 6, day: 1 }],
      },
      {
        title: '多快好省地发展地方工业',
        authors: ['黑龙江省革命委员会写作小组'],
        page_start: 85,
        page_end: 91,
        dates: [{ year: 1970, month: 6, day: 1 }],
      },
      {
        title: '思想革命带动技术革新——北京维尼纶厂的调查报告',
        authors: ['北京市革命委员会、纺织工业部联合调查组'],
        page_start: 92,
        page_end: 97,
        dates: [{ year: 1970, month: 6, day: 1 }],
      },
      {
        title: '中国人民伟大的革命志气万岁——庆祝我国第一颗人造地球卫星发射成功',
        authors: ['红宇'],
        page_start: 98,
        page_end: 101,
        dates: [{ year: 1970, month: 6, day: 1 }],
      },
      {
        title:
          '一个全心全意为农业生产服务的修配社——吉林德惠县胶车修配社的调查报告',
        authors: ['长春市革命委员会、德惠县革命委员会调查组'],
        page_start: 102,
        page_end: 105,
        dates: [{ year: 1970, month: 6, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/c2789a7d-95d2-4f51-a1fb-dcd44509509c.pdf',
};
