export default {
  entity: {
    id: 'c492f936-cda3-4709-a9ef-459edeacd192',
    name: '红旗一九七五年第四期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/c492f936-cda3-4709-a9ef-459edeacd192.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '论对资产阶级的全面专政',
        authors: ['张春桥'],
        page_start: 6,
        page_end: 15,
        dates: [{ year: 1975, month: 4, day: 1 }],
      },
      {
        title: '从理论与实践的结合上学好弄通',
        authors: ['《红旗》杂志编辑部'],
        page_start: 16,
        page_end: 19,
        dates: [{ year: 1975, month: 4 }],
      },
      {
        title: '回顾“三反”“五反”运动',
        authors: ['翟青'],
        page_start: 20,
        page_end: 23,
        dates: [{ year: 1975, month: 4 }],
      },
      {
        title: '巩固和发展社会主义制度——学习《无产阶级专政时代的经济和政治》',
        authors: ['燕枫'],
        page_start: 26,
        page_end: 32,
        dates: [{ year: 1975, month: 4 }],
      },
      {
        title:
          '限制资产阶级法权的思想武器——学习《在中国共产党第七届中央委员会第二次全体会议上的报告》',
        authors: ['纪岩'],
        page_start: 33,
        page_end: 39,
        dates: [{ year: 1975, month: 4 }],
      },
      {
        title: '调动一切积极因素',
        authors: ['高洛'],
        page_start: 40,
        page_end: 43,
        dates: [{ year: 1975, month: 4 }],
      },
      {
        title: '战胜资产阶级的思想反抗',
        authors: ['庄宁'],
        page_start: 44,
        page_end: 48,
        dates: [{ year: 1975, month: 4 }],
      },
      {
        title: '批资本主义 干社会主义——山东鱼台县相里大队的调查报告',
        authors: ['中国共产党鱼台县委员会调查组'],
        page_start: 49,
        page_end: 52,
        dates: [{ year: 1975, month: 4 }],
      },
      {
        title: '回到农村 继续革命',
        authors: ['北京部队某部八连全体复员战士'],
        page_start: 53,
        page_end: 56,
        dates: [{ year: 1975, month: 4 }],
      },
      {
        title: '开门整风 团结多数',
        authors: ['河北魏县陈庄大队党支部'],
        page_start: 57,
        page_end: 60,
        dates: [{ year: 1975, month: 4 }],
      },
      {
        title: '在反腐蚀的斗争中前进——北京市崇文门第二旅馆的调查报告',
        authors: ['中国共产党北京市委宣传组调查组'],
        page_start: 61,
        page_end: 64,
        dates: [{ year: 1975, month: 4 }],
      },
      {
        title: '认真办好自然科学研究刊物',
        authors: ['柯文'],
        page_start: 65,
        page_end: 69,
        dates: [{ year: 1975, month: 4 }],
      },
      {
        title: '商品交换中两种思想的斗争——从湖南花鼓戏《送货路上》谈起',
        authors: ['胡容'],
        page_start: 70,
        page_end: 74,
        dates: [{ year: 1975, month: 4 }],
      },
      {
        title: '宁夏六个国营农场的变化说明了什么？',
        authors: ['农林部农垦局调查组'],
        page_start: 75,
        page_end: 79,
        dates: [{ year: 1975, month: 4 }],
      },
      {
        title: '坚持正确路线 搞好铁路运输',
        authors: ['吉林铁路局党委会'],
        page_start: 80,
        page_end: 84,
        dates: [{ year: 1975, month: 4 }],
      },
      {
        title: '自力更生是个路线问题',
        authors: ['黎新'],
        page_start: 85,
        page_end: 89,
        dates: [{ year: 1975, month: 4 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/c492f936-cda3-4709-a9ef-459edeacd192.pdf',
};
