export default {
  entity: {
    id: 'c5198093-426b-4c32-9e10-15d0246c3669',
    name: '红旗一九五九年第十九期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/c5198093-426b-4c32-9e10-15d0246c3669.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '马克思列宁主义在中国的胜利',
        authors: ['刘少奇'],
        page_start: 3,
        page_end: 17,
        dates: [{ year: 1959, month: 9, day: 14 }],
      },
      {
        title: '高举党的总路线和毛泽东军事思想的红旗阔步前进',
        authors: ['林彪'],
        page_start: 18,
        page_end: 27,
        dates: [{ year: 1959, month: 10 }],
      },
      {
        title: '中国人民大团结和世界人民大团结',
        authors: ['邓小平'],
        page_start: 28,
        page_end: 34,
        dates: [{ year: 1959, month: 10 }],
      },
      {
        title: '论我国社会主义建设的大跃进',
        authors: ['李富春'],
        page_start: 35,
        page_end: 44,
        dates: [{ year: 1959, month: 10 }],
      },
      {
        title: '不断发展我国各民族的大团结',
        authors: ['乌兰夫'],
        page_start: 45,
        page_end: 52,
        dates: [{ year: 1959, month: 10 }],
      },
      {
        title: '共产党员应当是马克思列宁主义者，不应当是党的同路人',
        authors: ['康生'],
        page_start: 53,
        page_end: 57,
        dates: [{ year: 1959, month: 10 }],
      },
      {
        title: '中国人民胜利的国际意义',
        authors: ['王稼祥'],
        page_start: 58,
        page_end: 62,
        dates: [{ year: 1959, month: 10 }],
      },
      {
        title: '歌颂人民公社——为庆祝人民公社一周年而作',
        authors: ['陶铸'],
        page_start: 63,
        page_end: 71,
        dates: [{ year: 1959, month: 10 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/c5198093-426b-4c32-9e10-15d0246c3669.pdf',
};
