export default {
  entity: {
    id: 'c6c28483-1ccb-4a97-a15b-4b286b86221d',
    name: '红旗一九六〇年第六期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/c6c28483-1ccb-4a97-a15b-4b286b86221d.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '关于实现我国农业机械化的若干问题',
        authors: ['谭震林'],
        page_start: 3,
        page_end: 10,
        dates: [{ year: 1960, month: 3 }],
      },
      {
        title: '开展伟大的人民卫生工作',
        authors: ['徐运北'],
        page_start: 11,
        page_end: 17,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 3 }],
      },
      {
        title: '卫生红旗城市——广东佛山',
        authors: ['江林'],
        page_start: 18,
        page_end: 24,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 3 }],
      },
      {
        title: '投资包干是基本建设管理制度的一项革命',
        authors: ['夏耘'],
        page_start: 25,
        page_end: 30,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 3 }],
      },
      {
        title: '大跃进大的县、社工业',
        authors: ['王雨洛'],
        page_start: 31,
        page_end: 37,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 3 }],
      },
      {
        title: '生物学研究工作和生产实践相结合的道路',
        authors: ['过兴先'],
        page_start: 38,
        page_end: 43,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 3 }],
      },
      {
        title: '胜利一定属于伟大的非洲人民',
        authors: ['冯华'],
        page_start: 44,
        page_end: 47,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 3 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/c6c28483-1ccb-4a97-a15b-4b286b86221d.pdf',
};
