export default {
  entity: {
    id: 'c832c789-e157-42ee-8588-1d1580411eeb',
    name: '样板戏——文化革命及其最新形式（人间出版社2021年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '张晴艳著，人间出版社2021年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/c832c789-e157-42ee-8588-1d1580411eeb.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '序',
        authors: ['汪晖'],
        page_start: 13,
        page_end: 17,
        tags: [{ name: '人间出版社', type: 'issuer' }],
        dates: [{ year: 2020, month: 6, day: 21 }],
      },
      {
        title: '自序',
        authors: ['张晴艳'],
        page_start: 19,
        page_end: 20,
        tags: [{ name: '人间出版社', type: 'issuer' }],
        dates: [{ year: 2020, month: 6, day: 9 }],
      },
      {
        title: '导论',
        authors: ['张晴艳'],
        page_start: 21,
        page_end: 65,
        tags: [{ name: '人间出版社', type: 'issuer' }],
        dates: [{ year: 2021, month: 1 }],
      },
      {
        title: '第一章 漫长的文化革命及其过渡形式',
        authors: ['张晴艳'],
        page_start: 67,
        page_end: 116,
        tags: [{ name: '人间出版社', type: 'issuer' }],
        dates: [{ year: 2021, month: 1 }],
      },
      {
        title: '第二章 文化革命及其“样板”的诞生',
        authors: ['张晴艳'],
        page_start: 117,
        page_end: 245,
        tags: [{ name: '人间出版社', type: 'issuer' }],
        dates: [{ year: 2021, month: 1 }],
      },
      {
        title: '第三章 从文化革命到文化大革命',
        authors: ['张晴艳'],
        page_start: 247,
        page_end: 338,
        tags: [{ name: '人间出版社', type: 'issuer' }],
        dates: [{ year: 2021, month: 1 }],
      },
      {
        title: '结论',
        authors: ['张晴艳'],
        page_start: 339,
        page_end: 343,
        tags: [{ name: '人间出版社', type: 'issuer' }],
        dates: [{ year: 2021, month: 1 }],
      },
      {
        title: '附录一 “逼真”之假定性',
        authors: ['张晴艳'],
        page_start: 345,
        page_end: 378,
        tags: [{ name: '人间出版社', type: 'issuer' }],
        dates: [{ year: 2021, month: 1 }],
      },
      {
        title: '附录二 南北、花雅——样板团的转变',
        authors: ['张晴艳'],
        page_start: 379,
        page_end: 412,
        tags: [{ name: '人间出版社', type: 'issuer' }],
        dates: [{ year: 2021, month: 1 }],
      },
      {
        title: '参考书目',
        authors: ['张晴艳'],
        page_start: 413,
        page_end: 456,
        tags: [{ name: '人间出版社', type: 'issuer' }],
        dates: [{ year: 2021, month: 1 }],
      },
    ],
    ocr: { content_thresholds: [0.09, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/c832c789-e157-42ee-8588-1d1580411eeb.pdf',
};
