export default {
  entity: {
    id: 'c9a48a35-60c6-421f-ab1e-0eda9eadd092',
    name: '红旗一九七五年第十二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/c9a48a35-60c6-421f-ab1e-0eda9eadd092.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '教育革命的方向不容篡改',
        authors: ['北京大学', '清华大学大批判组'],
        page_start: 8,
        page_end: 15,
        dates: [{ year: 1975, month: 12, day: 1 }],
      },
      {
        title: '革命是历史的火车头',
        authors: ['齐永红'],
        page_start: 16,
        page_end: 20,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '热情支持社会主义的新生事物',
        authors: ['俞彤'],
        page_start: 21,
        page_end: 24,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '惩前毖后 治病救人',
        authors: ['齐彦'],
        page_start: 25,
        page_end: 27,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '坚持青年同工农结合的正确路线——学习《青年运动的方向》',
        authors: ['石凌'],
        page_start: 28,
        page_end: 33,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '永远坚持毛主席的教育方针',
        authors: ['叶新'],
        page_start: 34,
        page_end: 38,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '牢记党的基本路线',
        authors: ['上海市第二中学党支部'],
        page_start: 39,
        page_end: 42,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '开门办学 越办越好',
        authors: ['北京市第十三中学党支部'],
        page_start: 43,
        page_end: 46,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '略论方腊',
        authors: ['史文'],
        page_start: 47,
        page_end: 53,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '从宋江看修正主义的反动本质',
        authors: ['袁青'],
        page_start: 54,
        page_end: 56,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '发动群众评论《水浒》',
        authors: ['甘肃庆阳县八里庙大队党支部'],
        page_start: 57,
        page_end: 60,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '普及大寨县要抓好基本路线教育',
        authors: ['严群'],
        page_start: 61,
        page_end: 64,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '丰收了也要注意节约',
        authors: ['江景宏'],
        page_start: 65,
        page_end: 67,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '比什么？',
        authors: ['山东泰安县后省庄大队贫下中农评论组'],
        page_start: 68,
        page_end: 69,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '条件是不可改变的吗？',
        authors: ['上海金山县枫围公社新华大队理论小组'],
        page_start: 69,
        page_end: 71,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '修修配配 大有可为',
        authors: ['广西灵山县农机修造厂工人评论组'],
        page_start: 71,
        page_end: 72,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '搞好农田基本建设依靠什么？——陕西榆林地区的调查报告',
        authors: ['中国共产党陕西省委员会调查组'],
        page_start: 73,
        page_end: 77,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '加强领导班子的思想建设',
        authors: ['邯邢冶金矿山管理局党委会'],
        page_start: 78,
        page_end: 81,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '红旗杂志一九七五年第一期到第十二期总目录',
        authors: ['《红旗》杂志编辑部'],
        page_start: 82,
        page_end: 89,
        dates: [{ year: 1975, month: 12 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/c9a48a35-60c6-421f-ab1e-0eda9eadd092.pdf',
};
