export default {
  entity: {
    id: 'ca05f2d9-6729-4738-83c3-10ee950ea8c2',
    name: '国际共产主义运动中两条路线斗争简史（北京人民出版社1976年版）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '北京人民出版社1976年版',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/ca05f2d9-6729-4738-83c3-10ee950ea8c2.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '前言',
        authors: ['北京大学国际政治系'],
        page_start: 11,
        page_end: 14,
        dates: [{ year: 1976, month: 7 }],
      },
      {
        title: '一、马克思主义同蒲鲁东主义的斗争',
        authors: ['北京大学国际政治系'],
        page_start: 15,
        page_end: 53,
        dates: [{ year: 1976, month: 7 }],
      },
      {
        title: '二、马克思主义同巴枯宁主义的斗争',
        authors: ['北京大学国际政治系'],
        page_start: 54,
        page_end: 95,
        dates: [{ year: 1976, month: 7 }],
      },
      {
        title: '三、马克思主义同拉萨尔主义的斗争',
        authors: ['北京大学国际政治系'],
        page_start: 96,
        page_end: 130,
        dates: [{ year: 1976, month: 7 }],
      },
      {
        title: '四、马克思列宁主义同伯恩施坦主义的斗争',
        authors: ['北京大学国际政治系'],
        page_start: 131,
        page_end: 164,
        dates: [{ year: 1976, month: 7 }],
      },
      {
        title: '五、马克思列宁主义同考茨基主义的斗争',
        authors: ['北京大学国际政治系'],
        page_start: 165,
        page_end: 204,
        dates: [{ year: 1976, month: 7 }],
      },
      {
        title: '六、马克思列宁主义同托洛茨基主义的斗争',
        authors: ['北京大学国际政治系'],
        page_start: 205,
        page_end: 245,
        dates: [{ year: 1976, month: 7 }],
      },
      {
        title: '七、马克思列宁主义同布哈林主义的斗争',
        authors: ['北京大学国际政治系'],
        page_start: 247,
        page_end: 279,
        dates: [{ year: 1976, month: 7 }],
      },
      {
        title: '结束语',
        authors: ['北京大学国际政治系'],
        page_start: 280,
        page_end: 280,
        dates: [{ year: 1976, month: 7 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.116, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/ca05f2d9-6729-4738-83c3-10ee950ea8c2.pdf',
};
