export default {
  entity: {
    id: 'ca1b4083-cfe9-4328-b68c-a48ad2d32230',
    name: '自然辩证法一九七五年第四期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《自然辩证法》编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/ca1b4083-cfe9-4328-b68c-a48ad2d32230.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '人类的继往开来（续）',
        authors: ['李炳文', '胡波'],
        page_start: 6,
        page_end: 38,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '“红移”现象说明了什么？——再评“大爆炸宇宙学”',
        authors: ['李柯'],
        page_start: 39,
        page_end: 57,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '河外天体红移是可以认识的',
        authors: ['方励之', '程福臻', '张家铝', '尤峻汉', '周又元', '褚耀泉'],
        page_start: 58,
        page_end: 74,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '宣夜说的形成和发展——中国古代的宇宙无限论',
        authors: ['席泽宗'],
        page_start: 75,
        page_end: 90,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title:
          '论叶绿体在光反应中的作用——关于光合作用催化电子理论与“双光说”的分析',
        authors: ['范义积'],
        page_start: 91,
        page_end: 99,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '试谈光合作用研究的意义',
        authors: ['曾健刚'],
        page_start: 100,
        page_end: 107,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '光能利用与作物高产',
        authors: ['于沪宁'],
        page_start: 108,
        page_end: 112,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '对光合作用认识的发展',
        authors: ['殷宏章'],
        page_start: 113,
        page_end: 120,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '正在前进，继续前进！——农业机械化调查札记',
        authors: ['上海县革命委员会调查组'],
        page_start: 121,
        page_end: 127,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '机械化促进了农副两旺——薛家厍生产队的调查',
        authors: ['莘农文'],
        page_start: 128,
        page_end: 132,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '浦江淤泥化良田',
        authors: ['苏俊功'],
        page_start: 133,
        page_end: 137,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '苹果保鲜',
        authors: ['山东潍坊市蔬菜果品公司果品仓库商品养护研究小组'],
        page_start: 138,
        page_end: 143,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '吊装新歌',
        authors: ['上海市工业设备安装公司'],
        page_start: 144,
        page_end: 149,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '翠蓝工艺描新图',
        authors: ['上海染料化工一厂'],
        page_start: 150,
        page_end: 154,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '宋应星《论气》选注',
        authors: ['裴震'],
        page_start: 155,
        page_end: 159,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '河外星云的距离和视向速度之间的关系',
        authors: ['埃德温·哈勃'],
        page_start: 160,
        page_end: 167,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title:
          '星系天文学中的观测佯谬——某些河外天体的证据，与通常关于红移、年龄和起源的假设相矛盾',
        authors: ['霍尔顿·阿尔普'],
        page_start: 168,
        page_end: 186,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '形象生动的街头学校——科学技术画廊漫步',
        authors: ['余淮'],
        page_start: 187,
        page_end: 191,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '竹林深处的“活化石”——彩色科教片《熊猫》观后',
        authors: ['史戈'],
        page_start: 192,
        page_end: 198,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title:
          '需要进一步开展对遗传学问题的研究和讨论——本刊举行遗传学问题座谈会纪要',
        authors: ['《自然辩证法》编辑部'],
        page_start: 199,
        page_end: 201,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '小辞典',
        authors: ['《自然辩证法》编辑部'],
        page_start: 202,
        page_end: 203,
        dates: [{ year: 1975, month: 12 }],
      },
      {
        title: '本刊1973年第1期至1975年第4期（总1期至总10期）目录',
        authors: ['《自然辩证法》编辑部'],
        page_start: 204,
        page_end: 208,
        dates: [{ year: 1975, month: 12 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.1, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/ca1b4083-cfe9-4328-b68c-a48ad2d32230.pdf',
};
