export default {
  entity: {
    id: 'caa115dc-f284-4ba4-942a-937e5101e23a',
    name: '红旗一九六一年第二十期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/caa115dc-f284-4ba4-942a-937e5101e23a.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '进一步健全工业企业的责任制',
        authors: ['许辛学'],
        page_start: 3,
        page_end: 7,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 10 }],
      },
      {
        title: '其实是前进得更快了——学习土地改革的几点体会',
        authors: ['杜敬'],
        page_start: 8,
        page_end: 16,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 10 }],
      },
      {
        title: '学会“弹钢琴”的工作方法',
        authors: ['周景芳'],
        page_start: 17,
        page_end: 22,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 10 }],
      },
      {
        title: '更好地发挥农村基层党组织的领导核心作用',
        authors: ['许邦仪'],
        page_start: 23,
        page_end: 27,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 10 }],
      },
      {
        title: '缄默掩盖不住阴谋',
        authors: ['袁先禄'],
        page_start: 28,
        page_end: 31,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 10 }],
      },
      {
        title: '虚弱的回升',
        authors: ['有林'],
        page_start: 31,
        page_end: 34,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 10 }],
      },
      {
        title: '教学小品',
        authors: ['敢峰'],
        page_start: 35,
        page_end: 37,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 10 }],
      },
      {
        title: '雪浪花',
        authors: ['杨朔'],
        page_start: 38,
        page_end: 40,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 10 }],
      },
      {
        title: '白云深处',
        authors: ['周洁夫'],
        page_start: 40,
        page_end: 43,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 10 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/caa115dc-f284-4ba4-942a-937e5101e23a.pdf',
};
