export default {
  entity: {
    id: 'cbcf9973-3766-4593-97b8-f5913c56c2c5',
    name: '七十年征程——江渭清回忆录（江苏人民出版社1996年）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '江渭清著，江苏人民出版社1996年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/cbcf9973-3766-4593-97b8-f5913c56c2c5.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '附图',
        authors: ['江渭清'],
        page_start: 4,
        page_end: 19,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '代序',
        authors: ['张震'],
        page_start: 20,
        page_end: 23,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第一章 北伐洪流',
        authors: ['江渭清'],
        page_start: 32,
        page_end: 47,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第二章 投身革命',
        authors: ['江渭清'],
        page_start: 48,
        page_end: 58,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第三章 平江地区的战斗',
        authors: ['江渭清'],
        page_start: 59,
        page_end: 68,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第四章 转战湘赣负重伤',
        authors: ['江渭清'],
        page_start: 69,
        page_end: 78,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第五章 湘鄂赣边的三年',
        authors: ['江渭清'],
        page_start: 79,
        page_end: 105,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第六章 迎接抗日高潮到来',
        authors: ['江渭清'],
        page_start: 106,
        page_end: 118,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第七章 东进抗日',
        authors: ['江渭清'],
        page_start: 119,
        page_end: 135,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第八章 皖南事变前后',
        authors: ['江渭清'],
        page_start: 136,
        page_end: 152,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第九章 二到苏南',
        authors: ['江渭清'],
        page_start: 153,
        page_end: 189,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第十章 三到苏南',
        authors: ['江渭清'],
        page_start: 190,
        page_end: 260,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第十一章 南下苏浙皖边区',
        authors: ['江渭清'],
        page_start: 261,
        page_end: 282,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第十二章 投入解放战争',
        authors: ['江渭清'],
        page_start: 283,
        page_end: 303,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第十三章 北上山东',
        authors: ['江渭清'],
        page_start: 304,
        page_end: 326,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第十四章 从豫东打到江南',
        authors: ['江渭清'],
        page_start: 327,
        page_end: 348,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第一章 南京解放头三年',
        authors: ['江渭清'],
        page_start: 352,
        page_end: 391,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第二章 江苏建省与“三大改造”',
        authors: ['江渭清'],
        page_start: 392,
        page_end: 422,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第三章 整风和反右派斗争',
        authors: ['江渭清'],
        page_start: 423,
        page_end: 447,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第四章 “大跃进”年代（上）',
        authors: ['江渭清'],
        page_start: 448,
        page_end: 466,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第五章 “大跃进”年代（下）',
        authors: ['江渭清'],
        page_start: 467,
        page_end: 492,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第六章 开展“四清”运动（上）',
        authors: ['江渭清'],
        page_start: 493,
        page_end: 509,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第七章 开展“四清”运动（下）',
        authors: ['江渭清'],
        page_start: 510,
        page_end: 536,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第八章 “文化大革命”的狂潮恶浪',
        authors: ['江渭清'],
        page_start: 537,
        page_end: 581,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第九章 在江西的日子里',
        authors: ['江渭清'],
        page_start: 582,
        page_end: 615,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '第十章 晚晴荣享清平乐',
        authors: ['江渭清'],
        page_start: 616,
        page_end: 628,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 10 }],
      },
      {
        title: '后记',
        authors: ['江渭清'],
        page_start: 629,
        page_end: 630,
        tags: [{ name: '江苏人民出版社', type: 'issuer' }],
        dates: [{ year: 1996, month: 7 }],
      },
    ],
    ocr: { content_thresholds: [0.11, 0.066, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/cbcf9973-3766-4593-97b8-f5913c56c2c5.pdf',
};
