export default {
  entity: {
    id: 'cd9cc4a7-d563-443d-be4d-54c6faa92af0',
    name: '红旗一九六一年第十四期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/cd9cc4a7-d563-443d-be4d-54c6faa92af0.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '坚持“从群众中来，到群众中去”的领导方法',
        authors: ['杜敬', '张先畴'],
        page_start: 4,
        page_end: 11,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 7 }],
      },
      {
        title: '发展日用小商品生产，增加市场供应',
        authors: ['季龙'],
        page_start: 12,
        page_end: 17,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 7 }],
      },
      {
        title: '听书漫笔',
        authors: ['王朝闻'],
        page_start: 18,
        page_end: 25,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 7 }],
      },
      {
        title: '论发展过程中的部分质变',
        authors: ['吴江'],
        page_start: 26,
        page_end: 35,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 7 }],
      },
      {
        title: '美国种族关系上的“良好记录”',
        authors: ['卢之超'],
        page_start: 36,
        page_end: 38,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 7 }],
      },
      {
        title: '形式逻辑研究什么？怎样研究？',
        authors: ['吴家国'],
        page_start: 39,
        page_end: 45,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 7 }],
      },
      {
        title: '关于形式逻辑对象和作用问题的讨论',
        authors: ['《红旗》杂志编辑部'],
        page_start: 46,
        page_end: 48,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1961, month: 7 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/cd9cc4a7-d563-443d-be4d-54c6faa92af0.pdf',
};
