export default {
  entity: {
    id: 'ce229b2d-a595-4dc7-982c-43250c13e4b9',
    name: '张春桥：1949及其后（2）（中文大学出版社2017年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '郑重著，中文大学出版社2017年',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/ce229b2d-a595-4dc7-982c-43250c13e4b9.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '第十七章 管好自家的后院',
        authors: ['郑重'],
        page_start: 1,
        page_end: 26,
        dates: [{ year: 2017 }],
      },
      {
        title: '第十八章 最大的野心：写一部《毛泽东传》',
        authors: ['郑重'],
        page_start: 26,
        page_end: 40,
        dates: [{ year: 2017 }],
      },
      {
        title: '第十九章 毛泽东战略调整：批评“四人帮”、支持邓小平',
        authors: ['郑重'],
        page_start: 40,
        page_end: 56,
        dates: [{ year: 2017 }],
      },
      {
        title: '第二十章 邓小平下课及四五运动',
        authors: ['郑重'],
        page_start: 57,
        page_end: 73,
        dates: [{ year: 2017 }],
      },
      {
        title: '第二十一章 一九七六年十月事件',
        authors: ['郑重'],
        page_start: 74,
        page_end: 91,
        dates: [{ year: 2017 }],
      },
      {
        title: '第二十二章 现在还不是说话的时候',
        authors: ['郑重'],
        page_start: 92,
        page_end: 109,
        dates: [{ year: 2017 }],
      },
      {
        title: '代跋 海燕与太阳——张春桥心路轨迹试探',
        authors: ['郑重'],
        page_start: 110,
        page_end: 146,
        dates: [{ year: 2017 }],
      },
    ],
    ocr: {
      auto_vsplit: false,
      vsplit: 0.5,
      content_thresholds: [0, 0.072, 0, 0],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/ce229b2d-a595-4dc7-982c-43250c13e4b9.pdf',
};
