export default {
  entity: {
    id: 'cec31371-d421-4324-9dcd-6605e48283ed',
    name: '毛泽东选集第二卷（人民出版社1991年版）',
    internal: true,
    official: true,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/cec31371-d421-4324-9dcd-6605e48283ed.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '反对日本进攻的方针、办法和前途',
        authors: ['毛泽东'],
        page_start: 11,
        page_end: 19,
        dates: [{ year: 1937, month: 7, day: 23 }],
      },
      {
        title: '为动员一切力量争取抗战胜利而斗争',
        authors: ['毛泽东'],
        page_start: 20,
        page_end: 26,
        dates: [{ year: 1937, month: 8, day: 25 }],
      },
      {
        title: '反对自由主义',
        authors: ['毛泽东'],
        page_start: 27,
        page_end: 29,
        dates: [{ year: 1937, month: 9, day: 7 }],
      },
      {
        title: '国共合作成立后的迫切任务',
        authors: ['毛泽东'],
        page_start: 30,
        page_end: 40,
        dates: [{ year: 1937, month: 9, day: 29 }],
      },
      {
        title: '和英国记者贝特兰的谈话',
        authors: ['毛泽东'],
        page_start: 41,
        page_end: 54,
        dates: [{ year: 1937, month: 10, day: 25 }],
      },
      {
        title: '上海太原失陷以后抗日战争的形势和任务',
        authors: ['毛泽东'],
        page_start: 55,
        page_end: 68,
        dates: [{ year: 1937, month: 11, day: 12 }],
      },
      {
        title: '陕甘宁边区政府、第八路军后方留守处布告',
        authors: ['毛泽东'],
        page_start: 69,
        page_end: 71,
        dates: [{ year: 1938, month: 5, day: 15 }],
      },
      {
        title: '抗日游击战争的战略问题',
        authors: ['毛泽东'],
        page_start: 72,
        page_end: 106,
        dates: [{ year: 1938, month: 5 }],
      },
      {
        title: '论持久战',
        authors: ['毛泽东'],
        page_start: 107,
        page_end: 186,
        dates: [{ year: 1938, month: 5 }],
      },
      {
        title: '中国共产党在民族战争中的地位',
        authors: ['毛泽东'],
        page_start: 187,
        page_end: 204,
        dates: [{ year: 1938, month: 10, day: 14 }],
      },
      {
        title: '统一战线中的独立自主问题',
        authors: ['毛泽东'],
        page_start: 205,
        page_end: 208,
        dates: [{ year: 1938, month: 11, day: 5 }],
      },
      {
        title: '五四运动',
        authors: ['毛泽东'],
        page_start: 226,
        page_end: 228,
        dates: [{ year: 1939, month: 5, day: 1 }],
      },
      {
        title: '青年运动的方向',
        authors: ['毛泽东'],
        page_start: 229,
        page_end: 237,
        dates: [{ year: 1939, month: 5, day: 4 }],
      },
      {
        title: '反对投降活动',
        authors: ['毛泽东'],
        page_start: 238,
        page_end: 242,
        dates: [{ year: 1939, month: 6, day: 30 }],
      },
      {
        title: '必须制裁反动派',
        authors: ['毛泽东'],
        page_start: 243,
        page_end: 247,
        dates: [{ year: 1939, month: 8, day: 1 }],
      },
      {
        title: '关于国际新形势对新华日报记者的谈话',
        authors: ['毛泽东'],
        page_start: 248,
        page_end: 254,
        dates: [{ year: 1939, month: 9, day: 1 }],
      },
      {
        title: '和中央社、扫荡报、新民报三记者的谈话',
        authors: ['毛泽东'],
        page_start: 255,
        page_end: 260,
        dates: [{ year: 1939, month: 9, day: 16 }],
      },
      {
        title: '苏联利益和人类利益的一致',
        authors: ['毛泽东'],
        page_start: 261,
        page_end: 269,
        dates: [{ year: 1939, month: 9, day: 28 }],
      },
      {
        title: '《共产党人》发刊词',
        authors: ['毛泽东'],
        page_start: 270,
        page_end: 282,
        dates: [{ year: 1939, month: 10, day: 4 }],
      },
      {
        title: '目前形势和党的任务',
        authors: ['毛泽东'],
        page_start: 283,
        page_end: 285,
        dates: [{ year: 1939, month: 10, day: 10 }],
      },
      {
        title: '大量吸收知识分子',
        authors: ['毛泽东'],
        page_start: 286,
        page_end: 288,
        dates: [{ year: 1939, month: 12, day: 1 }],
      },
      {
        title: '中国革命和中国共产党',
        authors: ['毛泽东'],
        page_start: 289,
        page_end: 324,
        dates: [{ year: 1939, month: 12 }],
      },
      {
        title: '斯大林是中国人民的朋友',
        authors: ['毛泽东'],
        page_start: 325,
        page_end: 326,
        dates: [{ year: 1939, month: 12, day: 20 }],
      },
      {
        title: '纪念白求恩',
        authors: ['毛泽东'],
        page_start: 327,
        page_end: 329,
        dates: [{ year: 1939, month: 12, day: 21 }],
      },
      {
        title: '新民主主义论',
        authors: ['毛泽东'],
        page_start: 330,
        page_end: 379,
        dates: [{ year: 1940, month: 1 }],
      },
      {
        title: '克服投降危险，力争时局好转',
        authors: ['毛泽东'],
        page_start: 380,
        page_end: 382,
        dates: [{ year: 1940, month: 1, day: 28 }],
      },
      {
        title: '团结一切抗日力量，反对反共顽固派',
        authors: ['毛泽东'],
        page_start: 383,
        page_end: 388,
        dates: [{ year: 1940, month: 2, day: 1 }],
      },
      {
        title: '向国民党的十点要求',
        authors: ['毛泽东'],
        page_start: 389,
        page_end: 394,
        dates: [{ year: 1940, month: 2, day: 1 }],
      },
      {
        title: '《中国工人》发刊词',
        authors: ['毛泽东'],
        page_start: 395,
        page_end: 396,
        dates: [{ year: 1940, month: 2, day: 7 }],
      },
      {
        title: '必须强调团结和进步',
        authors: ['毛泽东'],
        page_start: 397,
        page_end: 398,
        dates: [{ year: 1940, month: 2, day: 7 }],
      },
      {
        title: '新民主主义的宪政',
        authors: ['毛泽东'],
        page_start: 399,
        page_end: 408,
        dates: [{ year: 1940, month: 2, day: 20 }],
      },
      {
        title: '抗日根据地的政权问题',
        authors: ['毛泽东'],
        page_start: 409,
        page_end: 411,
        dates: [{ year: 1940, month: 3, day: 6 }],
      },
      {
        title: '目前抗日统一战线中的策略问题',
        authors: ['毛泽东'],
        page_start: 412,
        page_end: 420,
        dates: [{ year: 1940, month: 3, day: 11 }],
      },
      {
        title: '放手发展抗日力量，抵抗反共顽固派的进攻',
        authors: ['毛泽东'],
        page_start: 421,
        page_end: 426,
        dates: [{ year: 1940, month: 5, day: 4 }],
      },
      {
        title: '团结到底',
        authors: ['毛泽东'],
        page_start: 427,
        page_end: 429,
        dates: [{ year: 1940, month: 7, day: 5 }],
      },
      {
        title: '论政策',
        authors: ['毛泽东'],
        page_start: 430,
        page_end: 438,
        dates: [{ year: 1940, month: 12, day: 25 }],
      },
      {
        title: '为皖南事变发表的命令和谈话',
        authors: ['毛泽东'],
        page_start: 439,
        page_end: 445,
        dates: [{ year: 1941, month: 1, day: 20 }],
      },
      {
        title: '打退第二次反共高潮后的时局',
        authors: ['毛泽东'],
        page_start: 446,
        page_end: 448,
        dates: [{ year: 1941, month: 3, day: 18 }],
      },
      {
        title: '关于打退第二次反共高潮的总结',
        authors: ['毛泽东'],
        page_start: 449,
        page_end: 454,
        dates: [{ year: 1941, month: 5, day: 8 }],
      },
    ],
    ocr: { content_thresholds: [0.14, 0, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/cec31371-d421-4324-9dcd-6605e48283ed.pdf',
};
