export default {
  entity: {
    id: 'cff9c9f0-4422-4826-b46f-877ac6effadc',
    name: '红旗一九七四年第八期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/cff9c9f0-4422-4826-b46f-877ac6effadc.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '认真看书学习 掌握理论武器',
        authors: ['池恒'],
        page_start: 8,
        page_end: 10,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '做革命团结的促进派',
        authors: ['齐新'],
        page_start: 11,
        page_end: 15,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '儒法斗争是“狗咬狗”吗？',
        authors: ['翟平'],
        page_start: 16,
        page_end: 18,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '论秦汉之际的阶级斗争',
        authors: ['罗思鼎'],
        page_start: 19,
        page_end: 29,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '儒法斗争与我国古代科学技术的发展',
        authors: ['李群'],
        page_start: 30,
        page_end: 35,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '尊孔读经与崇洋卖国',
        authors: ['陈今'],
        page_start: 36,
        page_end: 42,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '论王充的反儒斗争',
        authors: ['钟达'],
        page_start: 43,
        page_end: 48,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '韬晦之计和林彪的复辟阴谋',
        authors: ['师平'],
        page_start: 49,
        page_end: 51,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '深入批判林彪的“六个战术原则”',
        authors: ['沈思'],
        page_start: 52,
        page_end: 59,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '批判林彪资产阶级军事路线的一些体会',
        authors: ['中国人民解放军北京部队某部八连党支部'],
        page_start: 60,
        page_end: 63,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '批林批孔 促进战备',
        authors: ['中国人民解放军沈阳部队某部六连党支部'],
        page_start: 64,
        page_end: 67,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '提高警惕 保卫祖国',
        authors: ['中国人民解放军广州部队某部四连党支部'],
        page_start: 68,
        page_end: 72,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '发扬官兵一致的革命传统',
        authors: ['中国人民解放军兰州部队某部红一连党支部'],
        page_start: 73,
        page_end: 76,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '用毛主席哲学思想指导找油找气',
        authors: ['中国共产党大港油田委员会'],
        page_start: 77,
        page_end: 84,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '嘉定县安亭公社新泾大队1974—1980年农业发展规划（修订草案）',
        authors: ['嘉定县安亭公社新泾大队'],
        page_start: 85,
        page_end: 89,
        dates: [
          { year: 1973, month: 9 },
          { year: 1974, month: 6 },
        ],
      },
      {
        title: '学大寨 讲路线——湖北随县环城公社八一大队的调查报告',
        authors: ['中国共产党随县委员会宣传部调查组'],
        page_start: 90,
        page_end: 93,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
      {
        title: '路线搞对头 生产争上游——柳州铁路分局桂林北站的调查报告',
        authors: ['柳州铁路局党委会、柳州铁路分局党委会联合调查组'],
        page_start: 94,
        page_end: 97,
        dates: [{ year: 1974, month: 8, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/cff9c9f0-4422-4826-b46f-877ac6effadc.pdf',
};
