export default {
  entity: {
    id: 'd2bf3c0d-7ad9-484c-b2a5-6b2a2def3b33',
    name: '红旗一九七五年第十期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/d2bf3c0d-7ad9-484c-b2a5-6b2a2def3b33.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '认真总结农业学大寨的经验',
        authors: ['谭枫'],
        page_start: 8,
        page_end: 13,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '积极办好中小工业',
        authors: ['江虹'],
        page_start: 14,
        page_end: 18,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '做好后进队的转化工作',
        authors: ['中国共产党昔阳县委员会'],
        page_start: 19,
        page_end: 22,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title:
          '在毛主席革命路线指引下胜利前进——庆祝新疆维吾尔自治区成立二十周年',
        authors: ['赛福鼎'],
        page_start: 23,
        page_end: 29,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '大有希望的新生事物——江苏无锡县发展社队工业的调查报告',
        authors: ['江苏省革命委员会调查组'],
        page_start: 30,
        page_end: 33,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '建设理论队伍 推动群众学习',
        authors: ['天津市染料厂党委会'],
        page_start: 34,
        page_end: 37,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '发挥技术人员的积极作用——上海沪东造船厂的调查报告',
        authors: ['上海市第一机电工业局调查组'],
        page_start: 38,
        page_end: 41,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '评投降派宋江',
        authors: ['安群'],
        page_start: 42,
        page_end: 48,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '评金圣叹腰斩《水浒》——兼驳胡适吹捧金批本《水浒》的谬论',
        authors: ['闻钟'],
        page_start: 49,
        page_end: 54,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '《水浒》与宋代的阶级斗争',
        authors: ['杨荣国'],
        page_start: 55,
        page_end: 58,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '宣扬投降是对农民革命的歪曲',
        authors: ['山东梁山县后集大队《水浒》评论组'],
        page_start: 59,
        page_end: 62,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '《水浒》为何屏晁盖于一百〇八人之外？',
        authors: ['陈大康'],
        page_start: 62,
        page_end: 63,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '加强领导班子的建设',
        authors: ['石平'],
        page_start: 64,
        page_end: 67,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '发展安定团结的大好形势',
        authors: ['巴山'],
        page_start: 68,
        page_end: 70,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '用什么标准要求学生？',
        authors: ['上海市本溪中学党支部'],
        page_start: 71,
        page_end: 73,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '同位素年代学与人类对自然发展史的认识',
        authors: ['周新华', '朱炳泉'],
        page_start: 74,
        page_end: 83,
        dates: [{ year: 1975, month: 10 }],
      },
      {
        title: '苏修争霸世界的经济根源',
        authors: ['梁效'],
        page_start: 84,
        page_end: 89,
        dates: [{ year: 1975, month: 10 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/d2bf3c0d-7ad9-484c-b2a5-6b2a2def3b33.pdf',
};
