export default {
  entity: {
    id: 'd5f30e52-7a97-4451-bb78-b5b6d2169364',
    name: '红旗一九五九年第十五期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/d5f30e52-7a97-4451-bb78-b5b6d2169364.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '认识客观规律的客观性质',
        authors: ['许涤新'],
        page_start: 3,
        page_end: 9,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 8 }],
      },
      {
        title: '参加国家建设是人民解放军的光荣任务',
        authors: ['肖华'],
        page_start: 10,
        page_end: 16,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 8 }],
      },
      {
        title: '苏联人民为争取提前完成七年计划而奋斗',
        authors: ['刘晓'],
        page_start: 17,
        page_end: 24,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 8 }],
      },
      {
        title: '工业企业的专业分工和综合经营',
        authors: ['张有萱'],
        page_start: 25,
        page_end: 30,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 8 }],
      },
      {
        title: '农村中的工具改革',
        authors: ['李燕民'],
        page_start: 30,
        page_end: 35,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 8 }],
      },
      {
        title: '独立思考和服从真理',
        authors: ['施东向'],
        page_start: 36,
        page_end: 37,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 8 }],
      },
      {
        title: '“政治经济学教科书”（修订第三版）',
        authors: ['李云'],
        page_start: 38,
        page_end: 43,
        dates: [{ year: 1959, month: 8 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/d5f30e52-7a97-4451-bb78-b5b6d2169364.pdf',
};
