export default {
  entity: {
    id: 'd6e8f47c-70e7-4432-937f-d6c702420d10',
    name: '红旗一九六九年第六、七期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/d6e8f47c-70e7-4432-937f-d6c702420d10.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中国共产党万岁──纪念中国共产党诞生四十八周年',
        authors: [
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
          '《人民日报》编辑部',
        ],
        page_start: 8,
        page_end: 12,
        dates: [{ year: 1969, month: 7, day: 1 }],
      },
      {
        title: '高举“九大”的团结旗帜，争取更大的胜利',
        authors: [
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
          '《人民日报》编辑部',
        ],
        page_start: 13,
        page_end: 17,
        dates: [{ year: 1969, month: 6, day: 9 }],
      },
      {
        title: '加强团结，粉碎帝、修、反的阴谋',
        authors: ['肉孜吐尔迪', '孜牙'],
        page_start: 18,
        page_end: 20,
        dates: [{ year: 1969, month: 7 }],
      },
      {
        title: '一不怕苦，二不怕死 继续革命，彻底革命',
        authors: ['刘如亮'],
        page_start: 21,
        page_end: 23,
        dates: [{ year: 1969, month: 7 }],
      },
      {
        title: '毛泽东思想是工人阶级团结的基础',
        authors: ['葛信钧'],
        page_start: 24,
        page_end: 26,
        dates: [{ year: 1969, month: 7 }],
      },
      {
        title: '“越是艰险越向前”——驳“文化工作危险论”',
        authors: ['劲松'],
        page_start: 27,
        page_end: 30,
        dates: [{ year: 1969, month: 7 }],
      },
      {
        title: '革命青年工人的责任',
        authors: ['徐继先'],
        page_start: 31,
        page_end: 34,
        dates: [{ year: 1969, month: 7 }],
      },
      {
        title:
          '做过细的思想教育工作——如何帮助犯错误的干部回到毛主席的革命路线上来',
        authors: ['红涛'],
        page_start: 35,
        page_end: 38,
        dates: [{ year: 1969, month: 7 }],
      },
      {
        title: '评斯坦尼斯拉夫斯基“体系”',
        authors: ['上海革命大批判写作小组'],
        page_start: 39,
        page_end: 49,
        dates: [{ year: 1969, month: 7 }],
      },
      {
        title: '孔家店的幽灵与现实的阶级斗争',
        authors: ['史反修'],
        page_start: 50,
        page_end: 57,
        dates: [{ year: 1969, month: 6, day: 13 }],
      },
      {
        title: '政治统帅经济 革命统帅生产',
        authors: ['葛政'],
        page_start: 58,
        page_end: 62,
        dates: [{ year: 1969, month: 7 }],
      },
      {
        title: '三股绳紧紧拧成一股绳——黑龙江省双鸭山市的调查报告',
        authors: ['《黑龙江日报》记者'],
        page_start: 63,
        page_end: 70,
        dates: [{ year: 1969, month: 7 }],
      },
      {
        title: '一个朝气蓬勃的党支部——北京木城涧煤矿二段党支部的调查报告',
        authors: [
          '中国共产党北京木城涧煤矿委员会驻矿解放军毛泽东思想宣传队',
          '北京市革命委员会调查组',
        ],
        page_start: 71,
        page_end: 75,
        dates: [{ year: 1969, month: 6, day: 25 }],
      },
      {
        title: '改革不合理的规章制度是一场革命——北京市北郊木材厂的调查报告',
        authors: ['北京市革命委员会调查组'],
        page_start: 76,
        page_end: 81,
        dates: [{ year: 1969, month: 7 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/d6e8f47c-70e7-4432-937f-d6c702420d10.pdf',
};
