export default {
  entity: {
    id: 'da59c86f-1b55-41ef-b159-f2beb5d0ab7b',
    name: '党的基础知识（上海人民出版社1974年版）',
    internal: false,
    official: true,
    type: 'pdf',
    author: '上海人民出版社1974年版',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/da59c86f-1b55-41ef-b159-f2beb5d0ab7b.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '一 党的性质',
        authors: ['《党的基础知识》编写组'],
        page_start: 7,
        page_end: 15,
        dates: [{ year: 1974 }],
      },
      {
        title: '二 党的指导思想',
        authors: ['《党的基础知识》编写组'],
        page_start: 16,
        page_end: 26,
        dates: [{ year: 1974 }],
      },
      {
        title: '三 党的基本纲领和最终目的',
        authors: ['《党的基础知识》编写组'],
        page_start: 27,
        page_end: 35,
        dates: [{ year: 1974 }],
      },
      {
        title: '四 党的基本路线',
        authors: ['《党的基础知识》编写组'],
        page_start: 36,
        page_end: 46,
        dates: [{ year: 1974 }],
      },
      {
        title: '五 党的“三要三不要”原则',
        authors: ['《党的基础知识》编写组'],
        page_start: 47,
        page_end: 59,
        dates: [{ year: 1974 }],
      },
      {
        title: '六 党的一元化领导',
        authors: ['《党的基础知识》编写组'],
        page_start: 60,
        page_end: 72,
        dates: [{ year: 1974 }],
      },
      {
        title: '七 党的民主集中制',
        authors: ['《党的基础知识》编写组'],
        page_start: 73,
        page_end: 81,
        dates: [{ year: 1974 }],
      },
      {
        title: '八 党的纪律',
        authors: ['《党的基础知识》编写组'],
        page_start: 82,
        page_end: 89,
        dates: [{ year: 1974 }],
      },
      {
        title: '九 党的三大作风',
        authors: ['《党的基础知识》编写组'],
        page_start: 90,
        page_end: 103,
        dates: [{ year: 1974 }],
      },
      {
        title: '十 培养无产阶级革命事业接班人',
        authors: ['《党的基础知识》编写组'],
        page_start: 104,
        page_end: 111,
        dates: [{ year: 1974 }],
      },
      {
        title: '十一 党的基层组织的任务',
        authors: ['《党的基础知识》编写组'],
        page_start: 112,
        page_end: 121,
        dates: [{ year: 1974 }],
      },
      {
        title: '十二 党员的先锋模范作用',
        authors: ['《党的基础知识》编写组'],
        page_start: 122,
        page_end: 128,
        dates: [{ year: 1974 }],
      },
      {
        title: '十三 入党条件和入党手续',
        authors: ['《党的基础知识》编写组'],
        page_start: 129,
        page_end: 138,
        dates: [{ year: 1974 }],
      },
      {
        title: '十四 坚持无产阶级国际主义',
        authors: ['《党的基础知识》编写组'],
        page_start: 139,
        page_end: 147,
        dates: [{ year: 1974 }],
      },
      {
        title: '后记',
        authors: ['《党的基础知识》编写组'],
        page_start: 148,
        page_end: 148,
        dates: [{ year: 1973, month: 11 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.079, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/da59c86f-1b55-41ef-b159-f2beb5d0ab7b.pdf',
};
