export default {
  entity: {
    id: 'db482458-6a2e-435d-93dd-14f362e497ea',
    name: '文革通讯第18期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '浙江工农兵美术大学毛泽东主义红卫兵战斗队、毛泽东主义红卫兵',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives15/main/db482458-6a2e-435d-93dd-14f362e497ea.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title:
          '徐景贤同志四月十三日在上海市第六女中传达毛主席对上海第六女中联合的批语',
        authors: ['徐景贤'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967, month: 4, day: 13 }],
      },
      {
        title: '中共中央、国务院、中央军委、中央文化革命小组关于青海问题的决定',
        authors: ['中共中央', '国务院', '中央军委', '中央文化革命小组'],
        page_start: 1,
        page_end: 2,
        dates: [{ year: 1967, month: 3, day: 24 }],
      },
      {
        title: '周总理接见经委、计委、建委各派代表讲话摘要',
        authors: ['周恩来'],
        page_start: 2,
        page_end: 3,
        dates: [{ year: 1967 }],
      },
      {
        title: '关锋同志谈陈毅、徐向前问题',
        authors: ['关锋'],
        page_start: 3,
        page_end: 3,
        dates: [{ year: 1967 }],
      },
      {
        title: '“陈毅论陈毅”十则',
        authors: ['《文革通讯》编辑部'],
        page_start: 3,
        page_end: 4,
        dates: [{ year: 1967, month: 4, day: 29 }],
      },
      {
        title: '叶剑英十则',
        authors: ['《文革通讯》编辑部'],
        page_start: 4,
        page_end: 5,
        dates: [{ year: 1967, month: 4, day: 29 }],
      },
      {
        title: '杨成武同志揭刘、邓',
        authors: ['杨成武'],
        page_start: 5,
        page_end: 5,
        dates: [{ year: 1967 }],
      },
      {
        title: '一仆二主——从冯友兰看刘少奇',
        authors: ['《文革通讯》编辑部'],
        page_start: 5,
        page_end: 6,
        dates: [{ year: 1967, month: 4, day: 29 }],
      },
      {
        title: '刘某三哭',
        authors: ['《文革通讯》编辑部'],
        page_start: 6,
        page_end: 6,
        dates: [{ year: 1967, month: 4, day: 29 }],
      },
      {
        title: '祖国各地',
        authors: ['《文革通讯》编辑部'],
        page_start: 6,
        page_end: 8,
        dates: [{ year: 1967, month: 4, day: 29 }],
      },
    ],
    ocr: undefined,
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives15/db482458-6a2e-435d-93dd-14f362e497ea.pdf',
};
