export default {
  entity: {
    id: 'dfdd6b56-5f4e-42e1-af94-ae2ab38cc0b4',
    name: '毛泽东思想万岁（1913-1943卷）（1968年武汉版）',
    internal: true,
    official: false,
    type: 'pdf',
    author: '1968年武汉',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/dfdd6b56-5f4e-42e1-af94-ae2ab38cc0b4.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '第一师范讲堂录',
        authors: ['毛泽东'],
        page_start: 10,
        page_end: 10,
        dates: [{ year: 1913, month: 11, day: 1 }],
      },
      {
        title: '读《明耻篇》后题词',
        authors: ['毛泽东'],
        page_start: 10,
        page_end: 10,
        dates: [{ year: 1915 }],
      },
      {
        title: '《新青年》第七卷第一号',
        authors: ['毛泽东'],
        page_start: 10,
        page_end: 10,
        dates: [{ year: 1917 }],
      },
      {
        title: '工人夜校招生广告',
        authors: ['毛泽东'],
        page_start: 11,
        page_end: 11,
        dates: [],
      },
      {
        title: '夜学日记',
        authors: ['毛泽东'],
        page_start: 11,
        page_end: 11,
        dates: [{ year: 1917, month: 11, day: 14 }],
      },
      {
        title: '新民学会的方针',
        authors: ['毛泽东'],
        page_start: 11,
        page_end: 12,
        dates: [{ year: 1918, month: 4 }],
      },
      {
        title: '在上海送别第一批去法国勤工俭学同学时讲话',
        authors: ['毛泽东'],
        page_start: 12,
        page_end: 12,
        dates: [{ year: 1919 }],
      },
      {
        title: '湘江评论',
        authors: ['毛泽东'],
        page_start: 12,
        page_end: 19,
        dates: [{ year: 1919, month: 7, day: 14 }],
      },
      {
        title: '湘江评论第二号',
        authors: ['毛泽东'],
        page_start: 19,
        page_end: 24,
        dates: [{ year: 1919, month: 7, day: 21 }],
      },
      {
        title: '湘江评论增刊第一号',
        authors: ['毛泽东'],
        page_start: 24,
        page_end: 27,
        dates: [{ year: 1919, month: 7, day: 21 }],
      },
      {
        title: '湘江评论第三号',
        authors: ['毛泽东'],
        page_start: 28,
        page_end: 29,
        dates: [{ year: 1919, month: 7, day: 28 }],
      },
      {
        title: '民众的大联合（一）',
        authors: ['毛泽东'],
        page_start: 29,
        page_end: 30,
        dates: [{ year: 1919, month: 7, day: 21 }],
      },
      {
        title: '民众的大联合（二）',
        authors: ['毛泽东'],
        page_start: 31,
        page_end: 33,
        dates: [{ year: 1919, month: 7, day: 28 }],
      },
      {
        title: '民众的大联合（三）',
        authors: ['毛泽东'],
        page_start: 33,
        page_end: 35,
        dates: [{ year: 1919, month: 8, day: 4 }],
      },
      {
        title: '问题研究会章程',
        authors: ['毛泽东'],
        page_start: 35,
        page_end: 38,
        dates: [{ year: 1919, month: 10, day: 23 }],
      },
      {
        title: '学生之工作',
        authors: ['毛泽东'],
        page_start: 39,
        page_end: 41,
        dates: [{ year: 1919, month: 12, day: 28 }],
      },
      {
        title: '新民学会会员通信集第一集',
        authors: ['毛泽东'],
        page_start: 42,
        page_end: 46,
        dates: [],
      },
      {
        title: '新民学会会员通信集第二集',
        authors: ['毛泽东'],
        page_start: 46,
        page_end: 52,
        dates: [],
      },
      {
        title: '新民学会会员通信集第三集',
        authors: ['毛泽东'],
        page_start: 52,
        page_end: 57,
        dates: [],
      },
      {
        title: '非自杀（节录）',
        authors: ['毛泽东'],
        page_start: 57,
        page_end: 57,
        dates: [{ year: 1919, month: 11, day: 1 }],
      },
      {
        title: '驱逐张敬尧文电',
        authors: ['毛泽东'],
        page_start: 58,
        page_end: 58,
        dates: [{ year: 1920, month: 1 }],
      },
      {
        title: '发起“文化书社”缘起（摘要）',
        authors: ['毛泽东'],
        page_start: 58,
        page_end: 58,
        dates: [{ year: 1920, month: 7, day: 31 }],
      },
      {
        title: '“湖南自治运动”应该发起了',
        authors: ['毛泽东'],
        page_start: 60,
        page_end: 60,
        dates: [{ year: 1920, month: 9, day: 26 }],
      },
      {
        title: '湖南受中国之累以历史及现状证明之',
        authors: ['毛泽东'],
        page_start: 60,
        page_end: 61,
        dates: [{ year: 1920, month: 9, day: 12 }],
      },
      {
        title: '湘人为贪吏卖矿呈总统府、国务院及外、财、农商三部文',
        authors: ['毛泽东'],
        page_start: 61,
        page_end: 62,
        dates: [{ year: 1920, month: 12, day: 27 }],
      },
      {
        title: '致湖南省警察厅长的公开信（摘录）',
        authors: ['毛泽东'],
        page_start: 62,
        page_end: 63,
        dates: [{ year: 1920, month: 12 }],
      },
      {
        title: '文化书社第二期社务报告（摘录）',
        authors: ['毛泽东'],
        page_start: 63,
        page_end: 65,
        dates: [{ year: 1921, month: 4 }],
      },
      {
        title: '怎样去做才有真正的劳工团体出现？',
        authors: ['毛泽东'],
        page_start: 65,
        page_end: 66,
        dates: [{ year: 1920, month: 12 }],
      },
      {
        title: '新民学会一次讨论记载――提出无产阶级革命和无产阶级专政的主张',
        authors: ['毛泽东'],
        page_start: 67,
        page_end: 67,
        dates: [{ year: 1921, month: 1 }],
      },
      {
        title: '给杨怀中先生的信（摘录）',
        authors: ['毛泽东'],
        page_start: 67,
        page_end: 67,
        dates: [],
      },
      {
        title: '湖南自修大学创立宣言',
        authors: ['毛泽东'],
        page_start: 68,
        page_end: 69,
        dates: [{ year: 1921, month: 8 }],
      },
      {
        title: '告中国农民书',
        authors: ['毛泽东'],
        page_start: 69,
        page_end: 70,
        dates: [{ year: 1921 }],
      },
      {
        title: '上工宣言',
        authors: ['毛泽东'],
        page_start: 70,
        page_end: 70,
        dates: [],
      },
      {
        title: '长沙铅印活版工会致“大公报”记者盾（李抱一）书',
        authors: ['毛泽东'],
        page_start: 70,
        page_end: 71,
        dates: [{ year: 1922, month: 12, day: 14 }],
      },
      {
        title: '《省宪法》与赵恒惕',
        authors: ['毛泽东'],
        page_start: 71,
        page_end: 72,
        dates: [],
      },
      {
        title: '纸烟税',
        authors: ['毛泽东'],
        page_start: 72,
        page_end: 72,
        dates: [],
      },
      {
        title: '纸烟税',
        authors: ['毛泽东'],
        page_start: 72,
        page_end: 72,
        dates: [],
      },
      {
        title: '英国人与梁如浩',
        authors: ['毛泽东'],
        page_start: 73,
        page_end: 74,
        dates: [],
      },
      {
        title: '湖南自修大学组织大纲',
        authors: ['毛泽东'],
        page_start: 74,
        page_end: 77,
        dates: [{ year: 1923, month: 4, day: 10 }],
      },
      {
        title: '湖南自修大学入学须知',
        authors: ['毛泽东'],
        page_start: 77,
        page_end: 78,
        dates: [],
      },
      {
        title: '外力、军阀与革命',
        authors: ['毛泽东'],
        page_start: 78,
        page_end: 79,
        dates: [{ year: 1923, month: 4, day: 10 }],
      },
      {
        title: '《新时代》发刊词',
        authors: ['毛泽东'],
        page_start: 79,
        page_end: 80,
        dates: [{ year: 1923 }],
      },
      {
        title: '少年中国学会改组委员会调查表',
        authors: ['毛泽东'],
        page_start: 79,
        page_end: 80,
        dates: [{ year: 1921, month: 11, day: 21 }],
      },
      {
        title: '广东省党部代表大会会场日刊发刊词',
        authors: ['毛泽东'],
        page_start: 80,
        page_end: 81,
        dates: [{ year: 1925, month: 10, day: 25 }],
      },
      {
        title: '在国民党第二次全国代表大会上的发言',
        authors: ['毛泽东'],
        page_start: 81,
        page_end: 82,
        dates: [{ year: 1925 }],
      },
      {
        title: '填写《少年中国学会改组委员会调查表》',
        authors: ['毛泽东'],
        page_start: 82,
        page_end: 82,
        dates: [{ year: 1925, month: 11, day: 21 }],
      },
      {
        title: '中国国民党反奉战争宣传大纲',
        authors: ['毛泽东'],
        page_start: 82,
        page_end: 85,
        dates: [{ year: 1925, month: 11, day: 27 }],
      },
      {
        title: '政治周报',
        authors: ['毛泽东'],
        page_start: 85,
        page_end: 86,
        dates: [{ year: 1925, month: 12, day: 5 }],
      },
      {
        title: '反攻（一）',
        authors: ['毛泽东'],
        page_start: 86,
        page_end: 88,
        dates: [{ year: 1925, month: 12, day: 5 }],
      },
      {
        title: '反攻（二）',
        authors: ['毛泽东'],
        page_start: 88,
        page_end: 89,
        dates: [{ year: 1925, month: 12, day: 13 }],
      },
      {
        title: '中国国民党选派学生赴莫斯科孙文大学',
        authors: ['毛泽东'],
        page_start: 90,
        page_end: 91,
        dates: [{ year: 1925, month: 12, day: 13 }],
      },
      {
        title: '反攻（三）',
        authors: ['毛泽东'],
        page_start: 92,
        page_end: 93,
        dates: [{ year: 1925, month: 12, day: 20 }],
      },
      {
        title: '宣传报告',
        authors: ['毛泽东'],
        page_start: 93,
        page_end: 98,
        dates: [{ year: 1926, month: 4, day: 10 }],
      },
      {
        title: '中国农民中各阶级的分析及其对于革命的态度',
        authors: ['毛泽东'],
        page_start: 98,
        page_end: 100,
        dates: [{ year: 1926, month: 1, day: 1 }],
      },
      {
        title: '中国社会各阶级的分析',
        authors: ['毛泽东'],
        page_start: 101,
        page_end: 105,
        dates: [{ year: 1926 }],
      },
      {
        title: '国民党右派分离的原因及其对于革命前途的影响',
        authors: ['毛泽东'],
        page_start: 105,
        page_end: 108,
        dates: [{ year: 1926, month: 1 }],
      },
      {
        title: '上海民国日报反动的原因及国民党中央对该报的处置',
        authors: ['毛泽东'],
        page_start: 108,
        page_end: 109,
        dates: [{ year: 1925, month: 12, day: 20 }],
      },
      {
        title: '江浙农民的痛苦及其反抗运动',
        authors: ['毛泽东'],
        page_start: 109,
        page_end: 111,
        dates: [],
      },
      {
        title: '在湖南省第一次农工代表大会的讲话',
        authors: ['毛泽东'],
        page_start: 109,
        page_end: 111,
        dates: [{ year: 1926, month: 12, day: 20 }],
      },
      {
        title: '在湖南省第一次农工代表大会的讲话',
        authors: ['毛泽东'],
        page_start: 111,
        page_end: 112,
        dates: [{ year: 1926, month: 12, day: 20 }],
      },
      {
        title: '视察湖南农民运动给中央的报告',
        authors: ['毛泽东'],
        page_start: 112,
        page_end: 113,
        dates: [{ year: 1927, month: 2, day: 16 }],
      },
      {
        title: '湘赣边界各县党第二次代表大会决议案',
        authors: ['毛泽东'],
        page_start: 113,
        page_end: 118,
        dates: [{ year: 1928, month: 10, day: 25 }],
      },
      {
        title: '红军第四军六次代表大会决议案（摘录）',
        authors: ['毛泽东'],
        page_start: 118,
        page_end: 118,
        dates: [{ year: 1928, month: 12 }],
      },
      {
        title: '红军第四军司令、政治部布告',
        authors: ['毛泽东'],
        page_start: 118,
        page_end: 118,
        dates: [{ year: 1929, month: 6 }],
      },
      {
        title: '中国革命军事委员会总政治部第四号通令',
        authors: ['毛泽东'],
        page_start: 119,
        page_end: 122,
        dates: [{ year: 1931, month: 3, day: 20 }],
      },
      {
        title: '命令',
        authors: ['毛泽东'],
        page_start: 122,
        page_end: 122,
        dates: [{ year: 1933, month: 8, day: 8 }],
      },
      {
        title: '反围攻时给红军的动员令',
        authors: ['毛泽东'],
        page_start: 122,
        page_end: 122,
        dates: [],
      },
      {
        title: '红军第四军司令部布告',
        authors: ['毛泽东'],
        page_start: 123,
        page_end: 123,
        dates: [{ year: 1929 }],
      },
      {
        title: '中国共产党红军第四军第九次代表大会决议案',
        authors: ['毛泽东'],
        page_start: 123,
        page_end: 136,
        dates: [{ year: 1929 }],
      },
      {
        title: '总前委代表毛泽东给江西省行委的一封信',
        authors: ['毛泽东'],
        page_start: 137,
        page_end: 137,
        dates: [{ year: 1930, month: 11, day: 24 }],
      },
      {
        title: '查田运动是广大区域内的中心重大任务',
        authors: ['毛泽东'],
        page_start: 138,
        page_end: 139,
        dates: [{ year: 1933 }],
      },
      {
        title: '在八县查田运动大会上的报告',
        authors: ['毛泽东'],
        page_start: 139,
        page_end: 142,
        dates: [{ year: 1933, month: 6, day: 14 }],
      },
      {
        title: '关于查田运动的初步总结',
        authors: ['毛泽东'],
        page_start: 142,
        page_end: 149,
        dates: [{ year: 1933 }],
      },
      {
        title: '乡苏维埃怎样工作',
        authors: ['毛泽东'],
        page_start: 149,
        page_end: 153,
        dates: [{ year: 1933 }],
      },
      {
        title:
          '中华苏维埃共和国中央执行委员会与人民委员会对第二次全国苏维埃代表大会的报告',
        authors: ['毛泽东'],
        page_start: 153,
        page_end: 156,
        dates: [{ year: 1934, month: 1, day: 3 }],
      },
      {
        title: '中国工农红军北上抗日宣言',
        authors: ['毛泽东'],
        page_start: 156,
        page_end: 158,
        dates: [{ year: 1934 }],
      },
      {
        title: '关于日本声明书谈话',
        authors: ['毛泽东'],
        page_start: 158,
        page_end: 159,
        dates: [{ year: 1934 }],
      },
      {
        title: '中央关于反对敌人五次“围剿”的总结决议',
        authors: ['毛泽东'],
        page_start: 159,
        page_end: 162,
        dates: [{ year: 1935, month: 1, day: 8 }],
      },
      {
        title: '中华苏维埃共和国中央执行委员会命令',
        authors: ['毛泽东'],
        page_start: 162,
        page_end: 163,
        dates: [{ year: 1935, month: 12, day: 15 }],
      },
      {
        title: '中共关于目前政治形势与党的任务的决议',
        authors: ['毛泽东'],
        page_start: 163,
        page_end: 169,
        dates: [{ year: 1935, month: 12, day: 25 }],
      },
      {
        title: '给林彪同志的一封信',
        authors: ['毛泽东'],
        page_start: 169,
        page_end: 169,
        dates: [{ year: 1936, month: 12, day: 26 }],
      },
      {
        title: '致蔡元培信',
        authors: ['毛泽东'],
        page_start: 169,
        page_end: 170,
        dates: [{ year: 1936, month: 9, day: 26 }],
      },
      {
        title: '给张学良的一封信',
        authors: ['毛泽东'],
        page_start: 170,
        page_end: 171,
        dates: [{ year: 1936, month: 10, day: 5 }],
      },
      {
        title: '关于停战抗日的谈话',
        authors: ['毛泽东'],
        page_start: 171,
        page_end: 171,
        dates: [{ year: 1936, month: 10, day: 15 }],
      },
      {
        title: '中国共产党中央委员会为鲁迅逝世发出的电报',
        authors: ['毛泽东'],
        page_start: 171,
        page_end: 172,
        dates: [{ year: 1936, month: 10, day: 20 }],
      },
      {
        title: '致蒋介石书',
        authors: ['毛泽东'],
        page_start: 172,
        page_end: 173,
        dates: [{ year: 1936, month: 12, day: 1 }],
      },
      {
        title: '给徐特立同志的一封信',
        authors: ['毛泽东'],
        page_start: 173,
        page_end: 173,
        dates: [{ year: 1937, month: 1, day: 3 }],
      },
      {
        title: '与北方青年的谈话',
        authors: ['毛泽东'],
        page_start: 173,
        page_end: 174,
        dates: [{ year: 1937 }],
      },
      {
        title: '在西北青年救国会上的讲演',
        authors: ['毛泽东'],
        page_start: 174,
        page_end: 175,
        dates: [{ year: 1937 }],
      },
      {
        title: '命令',
        authors: ['毛泽东'],
        page_start: 175,
        page_end: 175,
        dates: [{ year: 1937, month: 7, day: 14 }],
      },
      {
        title: '辩证法唯物论讲授提纲',
        authors: ['毛泽东'],
        page_start: 176,
        page_end: 193,
        dates: [{ year: 1937, month: 8, day: 9 }],
      },
      {
        title: '关于独立自主山地游击战原则的指示',
        authors: ['毛泽东'],
        page_start: 193,
        page_end: 194,
        dates: [{ year: 1937, month: 9, day: 21 }],
      },
      {
        title: '关于整个华北工作应以游击战争为唯一方向的指示',
        authors: ['毛泽东'],
        page_start: 194,
        page_end: 194,
        dates: [{ year: 1937, month: 9, day: 25 }],
      },
      {
        title: '《农村调查》序言（一）',
        authors: ['毛泽东'],
        page_start: 194,
        page_end: 194,
        dates: [{ year: 1937, month: 10, day: 6 }],
      },
      {
        title: '在鲁迅逝世周年纪念大会上的演说',
        authors: ['毛泽东'],
        page_start: 195,
        page_end: 196,
        dates: [{ year: 1937, month: 10, day: 19 }],
      },
      {
        title: '基础战术',
        authors: ['毛泽东'],
        page_start: 196,
        page_end: 222,
        dates: [],
      },
      {
        title: '在抗大校舍落成大会上的训词',
        authors: ['毛泽东'],
        page_start: 222,
        page_end: 223,
        dates: [{ year: 1937, month: 10, day: 24 }],
      },
      {
        title: '“和美国记者贝特兰的谈话”补充',
        authors: ['毛泽东'],
        page_start: 223,
        page_end: 223,
        dates: [{ year: 1937, month: 10, day: 25 }],
      },
      {
        title: '给抗大九队同志的信',
        authors: ['毛泽东'],
        page_start: 223,
        page_end: 223,
        dates: [{ year: 1937, month: 12, day: 25 }],
      },
      {
        title: '加强政治教育与体育活动给项英同志的一封信',
        authors: ['毛泽东'],
        page_start: 224,
        page_end: 224,
        dates: [{ year: 1938 }],
      },
      {
        title: '与延安新中华报记者谈话',
        authors: ['毛泽东'],
        page_start: 224,
        page_end: 231,
        dates: [{ year: 1938, month: 2 }],
      },
      {
        title: '与合众社记者的谈话',
        authors: ['毛泽东'],
        page_start: 232,
        page_end: 234,
        dates: [{ year: 1938, month: 2 }],
      },
      {
        title: '中国共产党抗日救国十大纲领',
        authors: ['毛泽东'],
        page_start: 234,
        page_end: 235,
        dates: [],
      },
      {
        title: '在纪念孙中山逝世十三周年及追悼抗敌阵亡将士大会上的演说词',
        authors: ['毛泽东'],
        page_start: 236,
        page_end: 237,
        dates: [{ year: 1938, month: 3, day: 12 }],
      },
      {
        title: '对新四军进行游击战的指示',
        authors: ['毛泽东'],
        page_start: 238,
        page_end: 238,
        dates: [{ year: 1938, month: 5, day: 4 }],
      },
      {
        title: '与世界学联代表团柯乐满先生雅德先生傅路德先生雷克难先生之谈话',
        authors: ['毛泽东'],
        page_start: 238,
        page_end: 241,
        dates: [{ year: 1938, month: 7, day: 2 }],
      },
      {
        title: '论新阶段（节选）',
        authors: ['毛泽东'],
        page_start: 241,
        page_end: 242,
        dates: [{ year: 1938, month: 11 }],
      },
      {
        title: '八路军军政杂志发刊词',
        authors: ['毛泽东'],
        page_start: 242,
        page_end: 243,
        dates: [{ year: 1939, month: 1, day: 2 }],
      },
      {
        title: '《论持久战》英译本序言',
        authors: ['毛泽东'],
        page_start: 244,
        page_end: 244,
        dates: [{ year: 1939, month: 1, day: 20 }],
      },
      {
        title: '中国军队应当学习苏联红军',
        authors: ['毛泽东'],
        page_start: 244,
        page_end: 245,
        dates: [{ year: 1939, month: 2, day: 23 }],
      },
      {
        title: '在延安庆祝“五一”国际劳动节的讲话',
        authors: ['毛泽东'],
        page_start: 245,
        page_end: 248,
        dates: [{ year: 1939, month: 5, day: 1 }],
      },
      {
        title: '抗大三周年纪念',
        authors: ['毛泽东'],
        page_start: 248,
        page_end: 248,
        dates: [{ year: 1939, month: 5, day: 26 }],
      },
      {
        title: '在抗大成立三周年纪念大会上的讲话（摘录）',
        authors: ['毛泽东'],
        page_start: 249,
        page_end: 249,
        dates: [{ year: 1939, month: 6, day: 1 }],
      },
      {
        title: '中英两国人民站在一条战线上',
        authors: ['毛泽东'],
        page_start: 249,
        page_end: 250,
        dates: [{ year: 1939, month: 6, day: 1 }],
      },
      {
        title: '在延安模范青年给奖大会上的讲话（摘录）',
        authors: ['毛泽东'],
        page_start: 250,
        page_end: 250,
        dates: [{ year: 1939, month: 6, day: 6 }],
      },
      {
        title: '当前时局的最大危机',
        authors: ['毛泽东'],
        page_start: 250,
        page_end: 252,
        dates: [{ year: 1939, month: 6, day: 30 }],
      },
      {
        title: '反投降提纲',
        authors: ['毛泽东'],
        page_start: 252,
        page_end: 271,
        dates: [{ year: 1939, month: 6, day: 10 }],
      },
      {
        title: '在延安女子大学开学典礼上的讲话',
        authors: ['毛泽东'],
        page_start: 271,
        page_end: 271,
        dates: [{ year: 1939, month: 7, day: 25 }],
      },
      {
        title: '中央军委关于整理抗大问题的指示（节选）',
        authors: ['毛泽东'],
        page_start: 271,
        page_end: 272,
        dates: [{ year: 1939, month: 7, day: 25 }],
      },
      {
        title: '在陕甘宁边区学联第一次代表大会上的讲话',
        authors: ['毛泽东'],
        page_start: 272,
        page_end: 272,
        dates: [{ year: 1939, month: 8, day: 13 }],
      },
      {
        title: '第二次帝国主义战争讲演提纲',
        authors: ['毛泽东'],
        page_start: 272,
        page_end: 278,
        dates: [{ year: 1939, month: 9, day: 14 }],
      },
      {
        title: '研究沦陷区',
        authors: ['毛泽东'],
        page_start: 278,
        page_end: 279,
        dates: [{ year: 1939, month: 10, day: 1 }],
      },
      {
        title: '在延安各界庆祝斯大林六十寿辰大会上的讲话',
        authors: ['毛泽东'],
        page_start: 279,
        page_end: 281,
        dates: [{ year: 1939, month: 12, day: 21 }],
      },
      {
        title: '在延安纪念“一二·九”四周年大会上的讲话（节录）',
        authors: ['毛泽东'],
        page_start: 281,
        page_end: 281,
        dates: [{ year: 1939, month: 12, day: 9 }],
      },
      {
        title: '在中共中央举行的庆祝吴玉章同志六十寿辰大会上的祝词',
        authors: ['毛泽东'],
        page_start: 282,
        page_end: 282,
        dates: [{ year: 1940, month: 1, day: 15 }],
      },
      {
        title: '在陕甘宁边区第二届农工展览会开幕典礼上的讲话',
        authors: ['毛泽东'],
        page_start: 282,
        page_end: 283,
        dates: [{ year: 1940, month: 1, day: 16 }],
      },
      {
        title: '强调团结与进步',
        authors: ['毛泽东'],
        page_start: 283,
        page_end: 283,
        dates: [{ year: 1940, month: 2, day: 7 }],
      },
      {
        title: '相持阶段中的形势与任务',
        authors: ['毛泽东'],
        page_start: 284,
        page_end: 285,
        dates: [{ year: 1940, month: 2 }],
      },
      {
        title: '在陕甘宁边区自然科学研究会成立大会上的讲话',
        authors: ['毛泽东'],
        page_start: 285,
        page_end: 286,
        dates: [{ year: 1940, month: 3, day: 15 }],
      },
      {
        title: '在延安新哲学会第一届年会上的讲话',
        authors: ['毛泽东'],
        page_start: 286,
        page_end: 286,
        dates: [{ year: 1940, month: 6, day: 21 }],
      },
      {
        title: '在边区中央局经济自给动员大会上的讲话',
        authors: ['毛泽东'],
        page_start: 286,
        page_end: 286,
        dates: [{ year: 1940, month: 12, day: 3 }],
      },
      {
        title: '谨防扒手（社论）',
        authors: ['毛泽东'],
        page_start: 286,
        page_end: 287,
        dates: [{ year: 1941, month: 5, day: 23 }],
      },
      {
        title: '谣言与烟幕（社论）',
        authors: ['毛泽东'],
        page_start: 287,
        page_end: 289,
        dates: [{ year: 1941, month: 5, day: 28 }],
      },
      {
        title: '在陕甘宁边区第三届参议会上的讲话（摘录）',
        authors: ['毛泽东'],
        page_start: 289,
        page_end: 289,
        dates: [{ year: 1941, month: 7, day: 1 }],
      },
      {
        title: '关于增强党性的决定',
        authors: ['毛泽东'],
        page_start: 289,
        page_end: 291,
        dates: [{ year: 1941, month: 7, day: 1 }],
      },
      {
        title: '中央关于调查研究的决定',
        authors: ['毛泽东'],
        page_start: 291,
        page_end: 291,
        dates: [{ year: 1941, month: 8, day: 1 }],
      },
      {
        title: '“曾忠才长征记”一文按语',
        authors: ['毛泽东'],
        page_start: 292,
        page_end: 292,
        dates: [{ year: 1941, month: 8, day: 26 }],
      },
      {
        title: '“文化课本”序',
        authors: ['毛泽东'],
        page_start: 292,
        page_end: 292,
        dates: [{ year: 1941 }],
      },
      {
        title: '在东方各民族反法西斯大会上的讲话',
        authors: ['毛泽东'],
        page_start: 292,
        page_end: 293,
        dates: [{ year: 1941, month: 10, day: 30 }],
      },
      {
        title: '赠给王观澜同志的一段话——就战胜疾病问题',
        authors: ['毛泽东'],
        page_start: 294,
        page_end: 294,
        dates: [{ year: 1941, month: 12, day: 16 }],
      },
      {
        title: '庆祝苏军二十四周年',
        authors: ['毛泽东'],
        page_start: 294,
        page_end: 294,
        dates: [{ year: 1942, month: 2, day: 18 }],
      },
      {
        title: '在《解放日报》改版座谈会上的讲话',
        authors: ['毛泽东'],
        page_start: 295,
        page_end: 295,
        dates: [{ year: 1942, month: 4, day: 2 }],
      },
      {
        title: '“整顿学风、党风、文风”的补充',
        authors: ['毛泽东'],
        page_start: 295,
        page_end: 296,
        dates: [{ year: 1942, month: 2, day: 1 }],
      },
      {
        title: '“反对党八股”的补充',
        authors: ['毛泽东'],
        page_start: 296,
        page_end: 297,
        dates: [{ year: 1942, month: 2, day: 8 }],
      },
      {
        title: '给在华日本共产主义同盟的一封信',
        authors: ['毛泽东'],
        page_start: 297,
        page_end: 297,
        dates: [{ year: 1942, month: 6, day: 25 }],
      },
      {
        title: '关于统一抗日根据地党的领导及调整各组织间关系的决定',
        authors: ['毛泽东'],
        page_start: 297,
        page_end: 301,
        dates: [{ year: 1942, month: 9, day: 1 }],
      },
      {
        title: '历史教训',
        authors: ['毛泽东'],
        page_start: 301,
        page_end: 303,
        dates: [{ year: 1942, month: 10, day: 14 }],
      },
      {
        title: '关于中共更加布尔什维克化十二条',
        authors: ['毛泽东'],
        page_start: 303,
        page_end: 312,
        dates: [{ year: 1942, month: 11, day: 23 }],
      },
      {
        title: '电贺苏联红军第二十五周年',
        authors: ['毛泽东'],
        page_start: 313,
        page_end: 313,
        dates: [{ year: 1943, month: 2, day: 22 }],
      },
      {
        title: '毛泽东关于共产国际解散问题',
        authors: ['毛泽东'],
        page_start: 313,
        page_end: 315,
        dates: [{ year: 1943, month: 5, day: 26 }],
      },
      {
        title: '中央关于对待原四方面军干部态度问题的指示',
        authors: ['毛泽东'],
        page_start: 315,
        page_end: 316,
        dates: [{ year: 1943, month: 6, day: 8 }],
      },
      {
        title: '关于批评彭德怀一九四三年四月“关于民主教育谈话”的一封信',
        authors: ['毛泽东'],
        page_start: 316,
        page_end: 317,
        dates: [{ year: 1943, month: 6, day: 6 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.072, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/dfdd6b56-5f4e-42e1-af94-ae2ab38cc0b4.pdf',
};
