export default {
  entity: {
    id: 'e02758ee-2c6d-4162-8d80-a6a1fc8a2d01',
    name: '红旗一九六〇年第一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/e02758ee-2c6d-4162-8d80-a6a1fc8a2d01.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '迎接一九六〇年的新跃进',
        authors: ['李富春'],
        page_start: 3,
        page_end: 10,
        dates: [{ year: 1960, month: 1 }],
      },
      {
        title: '财政金融工作中的几个问题',
        authors: ['李先念'],
        page_start: 11,
        page_end: 15,
        dates: [{ year: 1960, month: 1 }],
      },
      {
        title: '人民公社的巩固和发展',
        authors: ['吴芝圃'],
        page_start: 16,
        page_end: 23,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 1 }],
      },
      {
        title: '论“一条龙”运输大协作',
        authors: ['余光生', '孙大光'],
        page_start: 24,
        page_end: 28,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 1 }],
      },
      {
        title: '城市街道居民工作的跃进',
        authors: ['管大同'],
        page_start: 29,
        page_end: 34,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 1 }],
      },
      {
        title: '争取和平斗争的大好形势',
        authors: ['于兆力'],
        page_start: 35,
        page_end: 41,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 1 }],
      },
      {
        title: '人民公社改变了草原的面貌',
        authors: ['中共内蒙古自治区委员会巴彦宝利格人民公社调查小组'],
        page_start: 42,
        page_end: 47,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/e02758ee-2c6d-4162-8d80-a6a1fc8a2d01.pdf',
};
