export default {
  entity: {
    id: 'e32ebac4-bba7-4fe1-b8c8-197ebee18dcb',
    name: '红旗一九七〇年第十期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/e32ebac4-bba7-4fe1-b8c8-197ebee18dcb.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中国共产党第九届中央委员第二次会议公报',
        alias: '中国共产党第九届中央委员会第二次全体会议公报',
        authors: [],
        page_start: 8,
        page_end: 11,
        dates: [{ year: 1970, month: 9, day: 6 }],
      },
      {
        title: '认真学习毛主席的哲学著作',
        authors: ['《红旗》杂志编辑部'],
        page_start: 12,
        page_end: 14,
        dates: [{ year: 1970, month: 10, day: 1 }],
      },
      {
        title: '充分认识阶级斗争的长期性、复杂性、曲折性',
        authors: ['刘亚彬'],
        page_start: 14,
        page_end: 17,
        dates: [{ year: 1970, month: 10, day: 1 }],
      },
      {
        title: '在斗争中学，在斗争中用',
        authors: ['耿长锁'],
        page_start: 17,
        page_end: 19,
        dates: [{ year: 1970, month: 10, day: 1 }],
      },
      {
        title: '用一分为二的观点做好知识青年的再教育',
        authors: ['陕西安塞县肖官驿大队革命委员会'],
        page_start: 20,
        page_end: 22,
        dates: [{ year: 1970, month: 10, day: 1 }],
      },
      {
        title: '要便思想合乎客观外界的规律性',
        authors: ['广西百色电机厂铸铝班工人学哲学小组'],
        page_start: 22,
        page_end: 24,
        dates: [{ year: 1970, month: 10, day: 1 }],
      },
      {
        title: '在“合理”上下功夫',
        authors: ['甘肃玉门市白杨河四队科学实验小组'],
        page_start: 25,
        page_end: 27,
        dates: [{ year: 1970, month: 10, day: 1 }],
      },
      {
        title: '掌握水上航运的主动权',
        authors: ['江苏常熟县轮船营业处四三七拖轮小组'],
        page_start: 27,
        page_end: 30,
        dates: [{ year: 1970, month: 10, day: 1 }],
      },
      {
        title: '大厂要向先进小厂学习',
        authors: ['景恭文'],
        page_start: 31,
        page_end: 34,
        dates: [{ year: 1970, month: 10, day: 1 }],
      },
      {
        title: '大家都来关心高校招生',
        authors: ['李志华'],
        page_start: 35,
        page_end: 37,
        dates: [{ year: 1970, month: 10, day: 1 }],
      },
      {
        title: '全面规划，加强领导——评发展县、社、队工业中的几个认识问题',
        authors: ['龙文'],
        page_start: 38,
        page_end: 40,
        dates: [{ year: 1970, month: 10, day: 1 }],
      },
      {
        title: '彻底批判刘少奇的资产阶级唯心论和形而上学',
        authors: ['北京市革命大批判写作小组'],
        page_start: 41,
        page_end: 49,
        dates: [{ year: 1970, month: 10, day: 1 }],
      },
      {
        title: '“国防文学”就是卖国文学——揭穿周扬“国防文学”的反动本质',
        authors: ['清华大学革命大批判写作小组'],
        page_start: 50,
        page_end: 58,
        dates: [{ year: 1970, month: 10, day: 1 }],
      },
      {
        title:
          '阶级斗争存在一天，革命大批判就要坚持一天——上海高压容器厂持久开展革命大批判的八个“怎么办？”',
        authors: ['上海市革命委员会调查组'],
        page_start: 59,
        page_end: 65,
        dates: [{ year: 1970, month: 10, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/e32ebac4-bba7-4fe1-b8c8-197ebee18dcb.pdf',
};
