export default {
  entity: {
    id: 'e54c9ef3-79c8-4a5a-95b4-835064b934c1',
    name: '印度一些革命派的重要文件、文章汇编（中共中央对外联络部1970年5月）',
    internal: true,
    official: true,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/e54c9ef3-79c8-4a5a-95b4-835064b934c1.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '印共革命派安得拉邦协调委员会的决议',
        authors: [],
        page_start: 6,
        page_end: 10,
        dates: [{ year: 1969, month: 2 }],
      },
      {
        title: '安得拉邦革命共产党委员会当前纲领',
        authors: [],
        page_start: 11,
        page_end: 32,
        dates: [{ year: 1969, month: 4 }],
      },
      {
        title: '关于安得拉邦武装斗争的声明',
        authors: [],
        page_start: 33,
        page_end: 36,
        dates: [{ year: 1969, month: 7 }],
      },
      {
        title: '关于斯里卡库兰县吉里江人武装斗争的报告',
        authors: [],
        page_start: 37,
        page_end: 74,
        dates: [{ year: 1969, month: 4 }],
      },
      {
        title: '给中国共产党第九次全国代表大会主席团的贺信',
        authors: [],
        page_start: 75,
        page_end: 84,
        dates: [{ year: 1969, month: 4 }],
      },
      {
        title: '关于与共产党革命派全印协调委员会的分歧',
        authors: ['共产党革命派马哈拉斯特拉邦委员会'],
        page_start: 86,
        page_end: 96,
        dates: [{ year: 1969, month: 6 }],
      },
      {
        title: '建立革命的共产党',
        authors: ['西孟加拉邦帕里玛尔·达斯·古普塔派'],
        page_start: 97,
        page_end: 113,
        dates: [{ year: 1969, month: 5 }],
      },
      {
        title: '新民主的斗争和“新共和”',
        authors: ['西孟加拉邦阿希特·森派'],
        page_start: 114,
        page_end: 117,
        dates: [{ year: 1969, month: 12 }],
      },
      {
        title: '在新民主主义革命中开展群众斗争和建立群众组织是必不可少的',
        authors: ['西孟加拉邦阿希特·森派'],
        page_start: 118,
        page_end: 123,
        dates: [{ year: 1969, month: 12 }],
      },
      {
        title: '剥开所谓“革命领导”的假面具',
        authors: ['西孟加拉邦阿希特·森派'],
        page_start: 124,
        page_end: 130,
        dates: [{ year: 1970, month: 2 }],
      },
      {
        title: '印度革命的前途（供讨论）',
        authors: ['西孟加拉邦《南国》派'],
        page_start: 132,
        page_end: 166,
        dates: [{ year: 1969, month: 5 }],
      },
      {
        title: '关于印度革命的战略问题（供讨论）',
        authors: ['西孟加拉邦《南国》派'],
        page_start: 167,
        page_end: 180,
        dates: [{ year: 1969, month: 5 }],
      },
      {
        title: '依靠毛泽东思想开展批评与自我批评',
        authors: ['琴都·鲍雅尔'],
        page_start: 181,
        page_end: 199,
        dates: [{ year: 1969, month: 5 }],
      },
      {
        title: '特利切里——普尔帕利的一年',
        authors: ['昆尼卡尔·纳拉扬纳'],
        page_start: 202,
        page_end: 207,
        dates: [{ year: 1969, month: 11 }],
      },
      {
        title: '立即向党内处于领导地位的修正主义作斗争',
        authors: ['昆尼卡尔·纳拉扬纳'],
        page_start: 208,
        page_end: 217,
        dates: [{ year: 1969, month: 12 }],
      },
      {
        title: '毛泽东思想的光辉照耀着喀拉拉邦',
        authors: ['昆尼卡尔·纳拉扬纳'],
        page_start: 218,
        page_end: 223,
        dates: [{ year: 1969, month: 12, day: 14 }],
      },
      {
        title: '编后',
        authors: [],
        page_start: 224,
        page_end: 225,
        dates: [{ year: 1970, month: 4 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.102, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/e54c9ef3-79c8-4a5a-95b4-835064b934c1.pdf',
};
