export default {
  entity: {
    id: 'e569e6be-702a-4fc4-9010-95bb6bab08fb',
    name: '红旗一九七五年第九期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/e569e6be-702a-4fc4-9010-95bb6bab08fb.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '重视对《水浒》的评论',
        authors: ['《红旗》杂志评论员'],
        page_start: 9,
        page_end: 10,
        dates: [{ year: 1975, month: 8, day: 28 }],
      },
      {
        title: '使人民都知道投降派——学习鲁迅对《水浒》的论述',
        authors: ['方岩粱'],
        page_start: 11,
        page_end: 15,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '一部宣扬投降主义的反面教材——评《水浒》',
        authors: ['北京大学、清华大学大批判组'],
        page_start: 16,
        page_end: 20,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '评《水浒》的投降主义路线',
        authors: ['钟谷'],
        page_start: 21,
        page_end: 28,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '叛徒的颂歌',
        authors: ['赵安亭'],
        page_start: 29,
        page_end: 35,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '加强体育队伍的思想建设',
        authors: ['郭育'],
        page_start: 36,
        page_end: 38,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '进一步抓好农村卫生工作',
        authors: ['韦革'],
        page_start: 39,
        page_end: 41,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '共产党员要增强党的观念',
        authors: ['闵雪'],
        page_start: 42,
        page_end: 45,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '坚持精兵简政',
        authors: ['兰文'],
        page_start: 46,
        page_end: 49,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '掌握对立统一的辩证观点',
        authors: ['燕枫'],
        page_start: 50,
        page_end: 53,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '无产阶级专政和资产阶级法权——学习《国家与革命》第五章',
        authors: ['钟实'],
        page_start: 54,
        page_end: 58,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '总结经验 促进学习',
        authors: ['李扬'],
        page_start: 59,
        page_end: 60,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '工人阶级也要不断学习和改造',
        authors: ['洪滨'],
        page_start: 61,
        page_end: 65,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '深入学习理论必须端正学风',
        authors: ['中国共产党盘锦地区委员会'],
        page_start: 66,
        page_end: 69,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '翻身农奴在社会主义道路上前进——庆祝西藏自治区成立十周年',
        authors: ['朱锋'],
        page_start: 70,
        page_end: 76,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '依靠群众赢得了高速度',
        authors: ['上海石油化工总厂筹建指挥部'],
        page_start: 77,
        page_end: 80,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '努力把基本建设搞得更好',
        authors: ['姚尚'],
        page_start: 81,
        page_end: 85,
        dates: [{ year: 1975, month: 9 }],
      },
      {
        title: '在抗灾斗争中锻炼得更坚强',
        authors: ['山东诸城县新河崖大队党支部'],
        page_start: 86,
        page_end: 89,
        dates: [{ year: 1975, month: 9 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/e569e6be-702a-4fc4-9010-95bb6bab08fb.pdf',
};
