export default {
  entity: {
    id: 'ea1b0606-049b-45a0-b5d2-716c8c6bda80',
    name: '红旗一九五九年第十二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/ea1b0606-049b-45a0-b5d2-716c8c6bda80.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '领导农业生产中的几个问题——安徽省农业生产的经验',
        authors: ['曾希圣'],
        page_start: 3,
        page_end: 10,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
      {
        title: '自然科学的发展与生产的关系',
        authors: ['龚育之'],
        page_start: 11,
        page_end: 19,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
      {
        title: '指标要切合实际',
        authors: ['许辛学'],
        page_start: 20,
        page_end: 22,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
      {
        title: '关于写文章',
        authors: ['施东向'],
        page_start: 23,
        page_end: 24,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
      {
        title: '治水工作的辩证观点',
        authors: ['李凡夫'],
        page_start: 25,
        page_end: 31,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
      {
        title: '进一步加强和巩固工农联盟',
        authors: ['邓拓'],
        page_start: 32,
        page_end: 39,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
      {
        title: '关于全民所有制内部商品价值形式问题',
        authors: ['胡钧'],
        page_start: 40,
        page_end: 51,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 6 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/ea1b0606-049b-45a0-b5d2-716c8c6bda80.pdf',
};
