export default {
  entity: {
    id: 'ec12c1b1-08d4-4189-8696-9b01631a7043',
    name: '文革通讯第10期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '浙江工农兵美术大学毛泽东主义红卫兵战斗队、毛泽东主义红卫兵',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives15/main/ec12c1b1-08d4-4189-8696-9b01631a7043.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '毛主席的最新批示',
        authors: ['毛泽东'],
        page_start: 1,
        page_end: 2,
        dates: [
          { year: 1967, month: 3, day: 7 },
          { year: 1967, month: 4, day: 6 },
        ],
      },
      {
        title: '中央首长讲话',
        authors: ['周恩来'],
        page_start: 2,
        page_end: 2,
        dates: [{ year: 1967, month: 4, day: 17 }],
      },
      {
        title: '张春桥同志的一些新指示',
        authors: ['张春桥'],
        page_start: 2,
        page_end: 3,
        dates: [{ year: 1967 }],
      },
      {
        title: '坚决打倒刘邓资产阶级反动路线的忠实走卒——谭震林',
        authors: ['《文革通讯》编辑部'],
        page_start: 3,
        page_end: 5,
        dates: [{ year: 1967, month: 4, day: 15 }],
      },
      {
        title: '北京简讯',
        authors: ['《文革通讯》编辑部'],
        page_start: 5,
        page_end: 6,
        dates: [{ year: 1967, month: 4, day: 15 }],
      },
      {
        title: '击退资产阶级反革命复辟逆流',
        authors: ['《文革通讯》编辑部'],
        page_start: 6,
        page_end: 6,
        dates: [{ year: 1967, month: 4, day: 15 }],
      },
      {
        title: '聂元梓同志讲话摘要',
        authors: ['聂元梓'],
        page_start: 6,
        page_end: 7,
        dates: [{ year: 1967, month: 3, day: 18 }],
      },
      {
        title: '批谭动态',
        authors: ['《文革通讯》编辑部'],
        page_start: 7,
        page_end: 7,
        dates: [{ year: 1967, month: 4, day: 15 }],
      },
      {
        title: '祖国各地',
        authors: ['《文革通讯》编辑部'],
        page_start: 7,
        page_end: 8,
        dates: [{ year: 1967, month: 4, day: 15 }],
      },
    ],
    ocr: undefined,
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives15/ec12c1b1-08d4-4189-8696-9b01631a7043.pdf',
};
