export default {
  entity: {
    id: 'ec8fd1ff-a1c1-4a67-8c30-d40e168f0fe4',
    name: '红旗一九五八年第八期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/ec8fd1ff-a1c1-4a67-8c30-d40e168f0fe4.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '美国侵略者自己套上了绞索',
        authors: ['《红旗》杂志编辑部'],
        page_start: 3,
        page_end: 6,
        dates: [{ year: 1958 }],
      },
      {
        title: '由农业生产合作社到人民公社',
        authors: ['吴芝圃'],
        page_start: 7,
        ocr: { vsplit: 0.35 },
        page_end: 13,
        dates: [{ year: 1958 }],
      },
      {
        title: '中共河北省委关于建立人民公社到指示',
        authors: [],
        page_start: 14,
        page_end: 19,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958, month: 8, day: 29 }],
      },
      {
        title: '党的教育方针促进了高等学校的革命',
        authors: ['蒋南翔'],
        page_start: 20,
        ocr: { vsplit: 0.35 },
        page_end: 25,
        dates: [{ year: 1958 }],
      },
      {
        title: '半工半读十教育和生产劳动相结合的最好形式',
        authors: ['梁寒冰'],
        page_start: 26,
        page_end: 29,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958 }],
      },
      {
        title: '山西机床厂办起了红专大学',
        authors: ['药远保'],
        page_start: 30,
        page_end: 32,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958 }],
      },
      {
        title: '文教战线上的大跃进',
        authors: ['赵守一'],
        page_start: 33,
        page_end: 39,
        ocr: { vsplit: 0.35 },
        dates: [{ year: 1958 }],
      },
      {
        title: '农村小医院',
        authors: ['中共应城县委会'],
        page_start: 39,
        ocr: { vsplit: 0.2 },
        page_end: 40,
        dates: [{ year: 1958 }],
      },
      {
        title: '热烈的竞争，亲密的协作',
        authors: ['李柏'],
        page_start: 41,
        ocr: { vsplit: 0.35 },
        page_end: 43,
        dates: [{ year: 1958 }],
      },
    ],
    ocr: {
      auto_vsplit: false,
      vsplit: 0,
      content_thresholds: [0, 0.185, 0, 0.1],
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/ec8fd1ff-a1c1-4a67-8c30-d40e168f0fe4.pdf',
};
