export default {
  entity: {
    id: 'ee53371f-2d83-41a4-91f7-8e5c116a3ef0',
    name: '红旗一九五九年第十七期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/ee53371f-2d83-41a4-91f7-8e5c116a3ef0.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中国共产党第八届中央委员会第八次全体会议公报',
        authors: [],
        page_start: 3,
        page_end: 5,
        dates: [{ year: 1959, month: 9 }],
      },
      {
        title: '中国共产党八届八中全会关于开展增产节约运动的决议',
        authors: [],
        page_start: 6,
        page_end: 10,
        dates: [{ year: 1959, month: 8, day: 16 }],
      },
      {
        title: '伟大的号召',
        authors: ['《红旗》杂志编辑部'],
        page_start: 11,
        page_end: 15,
        dates: [{ year: 1959, month: 9 }],
      },
      {
        title: '马克思主义者应当如何对待革命的群众运动',
        authors: ['《红旗》杂志编辑部'],
        page_start: 16,
        page_end: 27,
        dates: [{ year: 1959, month: 9 }],
      },
      {
        title: '人民公社的好处说不完',
        authors: ['王国藩'],
        page_start: 28,
        page_end: 32,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 9 }],
      },
      {
        title: '人民公社办运输',
        authors: ['张邦英'],
        page_start: 32,
        page_end: 37,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 9 }],
      },
      {
        title: '南水北调的宏伟理想',
        authors: ['王化云'],
        page_start: 38,
        page_end: 46,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 9 }],
      },
      {
        title: '岸信介把日本推向绝路',
        authors: ['陈新'],
        page_start: 47,
        page_end: 51,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 9 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/ee53371f-2d83-41a4-91f7-8e5c116a3ef0.pdf',
};
