export default {
  entity: {
    id: 'ee969489-4b64-4d6d-b461-741fd7f8cd33',
    name: '红旗一九五九年第八期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/ee969489-4b64-4d6d-b461-741fd7f8cd33.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '高速度发展纺织工业',
        authors: ['钱之光'],
        page_start: 3,
        page_end: 13,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 4 }],
      },
      {
        title: '苏联争取共产主义劳动胜利的群众运动',
        authors: ['伊·昌格里'],
        page_start: 14,
        page_end: 20,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 4 }],
      },
      {
        title: '试谈局部和全局的辩证关系',
        authors: ['胡里'],
        page_start: 21,
        page_end: 23,
        dates: [{ year: 1959, month: 4 }],
      },
      {
        title: '中国人民解放军的民主传统',
        authors: ['唐平铸'],
        page_start: 24,
        page_end: 36,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 4 }],
      },
      {
        title: '谁是和平的真正拥护者？',
        authors: ['何扬'],
        page_start: 37,
        page_end: 42,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 4 }],
      },
      {
        title: '从麻城实习谈起——对教育与生产劳动相结合的体会',
        authors: ['何定杰'],
        page_start: 43,
        page_end: 45,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 4 }],
      },
      {
        title: '在高山运河工地上——引洮上山工程散记',
        authors: ['李季'],
        page_start: 46,
        page_end: 51,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1959, month: 4 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/ee969489-4b64-4d6d-b461-741fd7f8cd33.pdf',
};
