export default {
  entity: {
    id: 'eeca2962-79fc-4445-8b22-13ece0814c36',
    name: '无产阶级文化大革命资料汇编（第三篇）（下）（水陆洲2012年）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '水陆洲编',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/eeca2962-79fc-4445-8b22-13ece0814c36.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '第六章 林彪集团的覆灭 第一节 林彪等人叛逃',
        authors: ['水陆洲'],
        page_start: 4,
        page_end: 199,
        dates: [{ year: 2012, month: 4, day: 26 }],
      },
      {
        title: '第六章 林彪集团的覆灭 第二节 揭批林彪集团罪行',
        authors: ['水陆洲'],
        page_start: 200,
        page_end: 247,
        dates: [{ year: 2012, month: 4, day: 27 }],
      },
      {
        title: '第七章 开展外交新局面 第一节 毛泽东决定开展中美谈判',
        authors: ['水陆洲'],
        page_start: 248,
        page_end: 256,
        dates: [{ year: 2012, month: 4, day: 28 }],
      },
      {
        title:
          '第七章 开展外交新局面 第二节 基辛格访华 中国恢复在联合国的合法席位',
        authors: ['水陆洲'],
        page_start: 257,
        page_end: 273,
        dates: [{ year: 2012, month: 4, day: 28 }],
      },
      {
        title: '第七章 开展外交新局面 第三节 尼克松访华',
        authors: ['水陆洲'],
        page_start: 274,
        page_end: 288,
        dates: [{ year: 2012, month: 4, day: 28 }],
      },
      {
        title: '第七章 开展外交新局面 第四节 中日恢复邦交',
        authors: ['水陆洲'],
        page_start: 289,
        page_end: 311,
        dates: [{ year: 2011, month: 3, day: 11 }],
      },
      {
        title: '第八章 批林整风 第一节 一九七二年的新形势新任务',
        authors: ['水陆洲'],
        page_start: 312,
        page_end: 341,
        dates: [{ year: 2012, month: 5, day: 4 }],
      },
      {
        title: '第八章 批林整风 第二节 开展批林整风',
        authors: ['水陆洲'],
        page_start: 342,
        page_end: 616,
        dates: [{ year: 2012, month: 5, day: 4 }],
      },
      {
        title: '第八章 批林整风 第三节 批判极左思潮问题',
        authors: ['水陆洲'],
        page_start: 617,
        page_end: 656,
        dates: [{ year: 2011, month: 5, day: 4 }],
      },
      {
        title: '第八章 批林整风 第四节 江青接受美国学者采访',
        authors: ['水陆洲'],
        page_start: 657,
        page_end: 693,
        dates: [{ year: 2012, month: 3, day: 10 }],
      },
      {
        title: '第九章 召开十大 第一节 一九七三年的新形势新任务',
        authors: ['水陆洲'],
        page_start: 694,
        page_end: 716,
        dates: [{ year: 2011, month: 5, day: 22 }],
      },
      {
        title: '第九章 召开十大 第二节 继续批林整风',
        authors: ['水陆洲'],
        page_start: 717,
        page_end: 784,
        dates: [{ year: 2012, month: 5, day: 4 }],
      },
      {
        title: '第九章 召开十大 第三节 邓小平复出',
        authors: ['水陆洲'],
        page_start: 785,
        page_end: 799,
        dates: [{ year: 2012, month: 5, day: 4 }],
      },
      {
        title: '第九章 召开十大 第四节 继续搞好文艺革命',
        authors: ['水陆洲'],
        page_start: 800,
        page_end: 832,
        dates: [{ year: 2012, month: 5, day: 4 }],
      },
      {
        title: '第九章 召开十大 第五节 批判教育领域的复辟回潮',
        authors: ['水陆洲'],
        page_start: 833,
        page_end: 855,
        dates: [{ year: 2012, month: 5, day: 4 }],
      },
      {
        title: '第九章 召开十大 第六节 中共第十次代表大会召开',
        authors: ['水陆洲'],
        page_start: 856,
        page_end: 883,
        dates: [{ year: 2012, month: 5, day: 4 }],
      },
      {
        title: '第九章 召开十大 第七节 毛泽东批评外交工作',
        authors: ['水陆洲'],
        page_start: 884,
        page_end: 919,
        dates: [{ year: 2012, month: 5, day: 5 }],
      },
      {
        title: '第九章 召开十大 第八节 评法批儒',
        authors: ['水陆洲'],
        page_start: 920,
        page_end: 953,
        dates: [{ year: 2010, month: 1, day: 4 }],
      },
      {
        title: '第九章 召开十大 第九节 八大军区司令员对调',
        authors: ['水陆洲'],
        page_start: 954,
        page_end: 958,
        dates: [{ year: 2010, month: 1, day: 18 }],
      },
      {
        title: '第十章 批林批孔 第一节 新阶段新任务',
        authors: ['水陆洲'],
        page_start: 959,
        page_end: 1005,
        dates: [{ year: 2010, month: 1, day: 25 }],
      },
      {
        title: '第十章 批林批孔 第二节 发动批林批孔',
        authors: ['水陆洲'],
        page_start: 1006,
        page_end: 1240,
        dates: [{ year: 2010, month: 2, day: 1 }],
      },
      {
        title: '第十章 批林批孔 第三节 各地区的批林批孔运动',
        authors: ['水陆洲'],
        page_start: 1241,
        page_end: 1323,
        dates: [{ year: 2010, month: 2, day: 8 }],
      },
      {
        title: '第十章 批林批孔 第四节 批判各领域的复辟回潮',
        authors: ['水陆洲'],
        page_start: 1324,
        page_end: 1403,
        dates: [{ year: 2012, month: 5, day: 13 }],
      },
      {
        title: '第十章 批林批孔 第五节 各大军区负责人到北京检查文革中的错误',
        authors: ['水陆洲'],
        page_start: 1404,
        page_end: 1428,
        dates: [{ year: 2012, month: 6, day: 6 }],
      },
      {
        title: '第十章 批林批孔 第六节 筹备四届人大',
        authors: ['水陆洲'],
        page_start: 1429,
        page_end: 1462,
        dates: [{ year: 2010, month: 3, day: 1 }],
      },
      {
        title: '第十章 批林批孔 第七节 毛泽东论三个世界',
        authors: ['水陆洲'],
        page_start: 1463,
        page_end: 1477,
        dates: [{ year: 2010, month: 3, day: 8 }],
      },
    ],
    ocr: {
      standard_paragraph_merge_strategy_threshold: 0.186,
      differential_paragraph_merge_strategy_threshold: 0,
      content_thresholds: [0.054, 0, 0, 0],
      extract_text_from_pdf: true,
    },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/eeca2962-79fc-4445-8b22-13ece0814c36.pdf',
};
