export default {
  entity: {
    id: 'f39b62f2-6a46-4167-a44e-eeb8790499c4',
    name: '自然辩证法一九七四年第一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '恩格斯，人民出版社1971年版',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/f39b62f2-6a46-4167-a44e-eeb8790499c4.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '评环境污染',
        authors: ['袁任平'],
        page_start: 6,
        page_end: 11,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '联合治废展新图',
        authors: ['上海市治理三废领导小组调查组'],
        page_start: 12,
        page_end: 18,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '变废为宝无止境',
        authors: ['上海燎原化工厂革命委员会'],
        page_start: 19,
        page_end: 24,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '废气变银丝',
        authors: ['上海化纤九厂革命委员会'],
        page_start: 25,
        page_end: 29,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '认识垃圾 利用垃圾',
        authors: ['上海市废旧物资公司'],
        page_start: 30,
        page_end: 33,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '环境污染的由来和发展',
        authors: ['柯勤'],
        page_start: 34,
        page_end: 45,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '人类起源问题的一些新认识',
        authors: ['李炳文', '胡波'],
        page_start: 46,
        page_end: 58,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '自然科学和阶级斗争——读马克思恩格斯关于达尔文进化论的书信',
        authors: ['袁明'],
        page_start: 59,
        page_end: 66,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '针刺麻醉中的辩证法',
        authors: ['任康桐'],
        page_start: 67,
        page_end: 84,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '地球上最早的人——东非人类化石材料简介',
        authors: ['陈德珍'],
        page_start: 85,
        page_end: 95,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '黄牛和水牛也能杂交',
        authors: ['《动物与防治》'],
        page_start: 95,
        page_end: 95,
        dates: [{ year: 1973, month: 6 }],
      },
      {
        title: '生物生生不息',
        authors: ['胡雨涛'],
        page_start: 96,
        page_end: 127,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '全角膜白斑盲人重见光明',
        authors: ['上海铁路中心医院革命委员会'],
        page_start: 128,
        page_end: 135,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '治好严重腰腿痛的启示',
        authors: ['上海市静安区中心医院外科'],
        page_start: 136,
        page_end: 142,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '揭开“红眼病”病因之谜',
        authors: ['上海市“红眼病”病原研究协作组'],
        page_start: 143,
        page_end: 148,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '从焯菜到焯菜素',
        authors: ['上海药物研究所慢性气管炎研究组', '王之璋'],
        page_start: 149,
        page_end: 154,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '生物学是不是一门独特的科学？',
        authors: ['迈克尔·A·西蒙', '迈克尔·E·鲁斯', '陆帆', '赵寿元'],
        page_start: 155,
        page_end: 173,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '宇宙有没有“谜底”？——评海克尔的《宇宙之谜》',
        authors: ['朱锋'],
        page_start: 174,
        page_end: 183,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '达尔文和他的进化学说',
        authors: ['辛可'],
        page_start: 184,
        page_end: 195,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '关于星系爆发的时间（答读者问）',
        authors: ['《自然辩证法》编辑部'],
        page_start: 195,
        page_end: 195,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '岂止是“客套”！',
        authors: ['登高'],
        page_start: 196,
        page_end: 198,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '什么是病毒？（名词解释）',
        authors: ['《自然辩证法》编辑部'],
        page_start: 198,
        page_end: 198,
        dates: [{ year: 1974, month: 1 }],
      },
      {
        title: '小辞典',
        authors: ['《自然辩证法》编辑部'],
        page_start: 199,
        page_end: 203,
        dates: [{ year: 1974, month: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.12, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/f39b62f2-6a46-4167-a44e-eeb8790499c4.pdf',
};
