export default {
  entity: {
    id: 'f4a90e82-45a8-4f81-be07-8fbcf7d821c9',
    name: '红旗一九六〇年第二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/f4a90e82-45a8-4f81-be07-8fbcf7d821c9.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '无产阶级领导工业的基本方针',
        authors: ['宋任穷'],
        page_start: 3,
        page_end: 8,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 1 }],
      },
      {
        title: '学习毛泽东思想 充分发扬自觉的能动性',
        authors: ['江渭清'],
        page_start: 9,
        page_end: 18,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 1 }],
      },
      {
        title: '一九六〇年的农业战线',
        authors: ['刘瑞龙'],
        page_start: 19,
        page_end: 29,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 1 }],
      },
      {
        title: '六亿神州送瘟神',
        authors: ['魏文伯'],
        page_start: 30,
        page_end: 34,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 1 }],
      },
      {
        title: '关于干部参加体力劳动',
        authors: ['赵汉'],
        page_start: 35,
        page_end: 40,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 1 }],
      },
      {
        title: '老高炉的生产大跃进',
        authors: ['周介生'],
        page_start: 41,
        page_end: 43,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 1 }],
      },
      {
        title: '一个由土到洋的小型炼焦厂',
        authors: ['殷家夫'],
        page_start: 44,
        page_end: 47,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/f4a90e82-45a8-4f81-be07-8fbcf7d821c9.pdf',
};
