export default {
  entity: {
    id: 'f6691372-978b-4bac-bf5d-b5a79c83d6d9',
    name: '自然辩证法一九七五年第二期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《自然辩证法》编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/f6691372-978b-4bac-bf5d-b5a79c83d6d9.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '论运动的守恒和不守恒——兼评热力学第一定律和第二定律',
        authors: ['李柯'],
        page_start: 6,
        page_end: 25,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '论钢管矫直机棍形的改造',
        authors: ['陈惠波'],
        page_start: 26,
        page_end: 32,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '相对论批判',
        authors: [
          '罗嘉昌',
          '季梁',
          '徐湛',
          '沈乃徽',
          '张达华',
          '邵济群',
          '朱清时',
          '李云',
        ],
        page_start: 33,
        page_end: 62,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '地震的规律是可以认识的',
        authors: ['中国科学院上海天文台地震室'],
        page_start: 63,
        page_end: 72,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '地震与儒法论争',
        authors: ['翟海天'],
        page_start: 73,
        page_end: 79,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '国外关于地震成因的几种假说',
        authors: ['《自然辩证法》编辑部'],
        page_start: 80,
        page_end: 87,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '访“龙”记”——上海几家工厂改造老设备实现生产连续化、自动化见闻',
        authors: ['《自然辩证法》记者'],
        page_start: 88,
        page_end: 97,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '这个公社实现了插秧机械化——崇明县堡镇公社的调查',
        authors: ['崇明县革命委员会调查组'],
        page_start: 98,
        page_end: 102,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '向生产的深度和广度进军——记上海化工战线技术革新的几个片断',
        authors: ['《自然辩证法》记者'],
        page_start: 103,
        page_end: 111,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '大型电站转子是怎样攻下来的',
        authors: ['上海重型机器厂工人写作组'],
        page_start: 112,
        page_end: 117,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '发展异型钢管品种的辩证法',
        authors: ['上海异型钢管厂'],
        page_start: 118,
        page_end: 124,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '征服急性白血病的第一步',
        authors: ['上海市白血病防治研究协作组'],
        page_start: 125,
        page_end: 132,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '肝癌诊断的难与易',
        authors: ['上海第一医学院附属中山医院肝肿瘤组'],
        page_start: 133,
        page_end: 138,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '人类的继往开来',
        authors: ['李炳文', '胡波'],
        page_start: 139,
        page_end: 157,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '在三大革命实践中取得真知',
        authors: ['上海师范大学地理系河口海岸研究室'],
        page_start: 158,
        page_end: 175,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '走出实验室的小天地',
        authors: ['王蘅文'],
        page_start: 176,
        page_end: 180,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '农基课要与农业生产相结合',
        authors: ['川沙县六团中学'],
        page_start: 181,
        page_end: 185,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '在针刺医疗实践中上好卫生课',
        authors: ['奉贤县平安中学红卫兵针刺小组'],
        page_start: 185,
        page_end: 190,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '开门办学中的三堂课',
        authors: ['姜晶', '龚家敏'],
        page_start: 190,
        page_end: 195,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '数学课也要在生产实践中上',
        authors: ['蒋代炘'],
        page_start: 195,
        page_end: 197,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '不屈的战士布鲁诺',
        authors: ['晋盛'],
        page_start: 198,
        page_end: 208,
        dates: [{ year: 1975, month: 7 }],
      },
      {
        title: '小辞典',
        authors: ['《自然辩证法》编辑部'],
        page_start: 209,
        page_end: 209,
        dates: [{ year: 1975, month: 7 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.12, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/f6691372-978b-4bac-bf5d-b5a79c83d6d9.pdf',
};
