export default {
  entity: {
    id: 'f9048a02-0bc0-48c3-8d5e-3161f75935d5',
    name: '内蒙文革实录：“民族分裂”与“挖肃”运动（天行健出版社2010年6月）',
    internal: false,
    official: false,
    type: 'pdf',
    author: '启之著，天行健出版社2010年6月',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/f9048a02-0bc0-48c3-8d5e-3161f75935d5.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '序一：在我看过的同类材料中，此件是写得最好的',
        authors: ['沈迈克'],
        page_start: 9,
        page_end: 11,
        dates: [{ year: 2007, month: 8, day: 2 }],
      },
      {
        title: '序二：前事不忘，后事之师',
        authors: ['合蜀'],
        page_start: 12,
        page_end: 14,
        dates: [{ year: 2007, month: 10, day: 17 }],
      },
      {
        title: '序三：民族的不幸源于政治的不幸',
        authors: ['徐友渔'],
        page_start: 15,
        page_end: 17,
        dates: [{ year: 2007, month: 11, day: 2 }],
      },
      {
        title: '前言 千秋易过，文革罪恶难消',
        authors: ['启之'],
        page_start: 19,
        page_end: 26,
        dates: [{ year: 2010, month: 6 }],
      },
      {
        title: '第一章 背景',
        authors: ['启之'],
        page_start: 27,
        page_end: 104,
        dates: [{ year: 2010, month: 6 }],
      },
      {
        title: '第二章 发轫',
        authors: ['启之'],
        page_start: 105,
        page_end: 166,
        dates: [{ year: 2010, month: 6 }],
      },
      {
        title: '第三章 夺权',
        authors: ['启之'],
        page_start: 167,
        page_end: 216,
        dates: [{ year: 2010, month: 6 }],
      },
      {
        title: '第四章 挖肃（一）',
        authors: ['启之'],
        page_start: 217,
        page_end: 283,
        dates: [{ year: 2010, month: 6 }],
      },
      {
        title: '第五章 挖肃（二）',
        authors: ['启之'],
        page_start: 285,
        page_end: 323,
        dates: [{ year: 2010, month: 6 }],
      },
      {
        title: '第六章 挖肃（三）',
        authors: ['启之'],
        page_start: 325,
        page_end: 362,
        dates: [{ year: 2010, month: 6 }],
      },
      {
        title: '第七章 “成果”',
        authors: ['启之'],
        page_start: 363,
        page_end: 407,
        dates: [{ year: 2010, month: 6 }],
      },
      {
        title: '第八章 战乱',
        authors: ['启之'],
        page_start: 409,
        page_end: 442,
        dates: [{ year: 2010, month: 6 }],
      },
      {
        title: '第九章 残局',
        authors: ['启之'],
        page_start: 443,
        page_end: 478,
        dates: [{ year: 2010, month: 6 }],
      },
      {
        title: '第十章 善后',
        authors: ['启之'],
        page_start: 479,
        page_end: 528,
        dates: [{ year: 2010, month: 6 }],
      },
      {
        title: '第十一章 影响',
        authors: ['启之'],
        page_start: 529,
        page_end: 578,
        dates: [{ year: 2010, month: 6 }],
      },
      {
        title: '结语 走向民族和解',
        authors: ['启之'],
        page_start: 579,
        page_end: 582,
        dates: [{ year: 2010, month: 6 }],
      },
      {
        title: '后记',
        authors: ['启之'],
        page_start: 583,
        page_end: 588,
        dates: [{ year: 2010, month: 6 }],
      },
      {
        title: '参考文献',
        authors: ['启之'],
        page_start: 589,
        page_end: 593,
        dates: [{ year: 2010, month: 6 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.108, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/f9048a02-0bc0-48c3-8d5e-3161f75935d5.pdf',
};
