export default {
  entity: {
    id: 'fac85a52-b745-44f3-81bb-6eb727db7f4f',
    name: '红旗一九六〇年第十七期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/fac85a52-b745-44f3-81bb-6eb727db7f4f.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '全党全民动手，大办工业',
        authors: ['廖鲁言'],
        page_start: 3,
        page_end: 9,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 9 }],
      },
      {
        title: '让土壤科学成为农业持续跃进的战斗武器',
        authors: ['刘瑞龙'],
        page_start: 10,
        page_end: 16,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 9 }],
      },
      {
        title: '针锋相对的斗争——古巴人民坚持反对美帝国主义',
        authors: ['郭济洲'],
        page_start: 17,
        page_end: 22,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 9 }],
      },
      {
        title: '各级领导干部都要做农村调查研究工作',
        authors: ['肖述'],
        page_start: 23,
        page_end: 27,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 9 }],
      },
      {
        title: '高速度地发展建筑材料工业',
        authors: ['刘秀峰'],
        page_start: 28,
        page_end: 32,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 9 }],
      },
      {
        title: '包头钢铁公司的多种经营',
        authors: ['陈守中'],
        page_start: 33,
        page_end: 38,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 9 }],
      },
      {
        title: '社办工业必须更好地为农业生产服务',
        authors: ['贾启允'],
        page_start: 39,
        page_end: 43,
        ocr: {
          auto_vsplit: false,
          vsplit: 0.38,
          content_thresholds: [0, 0.17, 0, 0.2],
        },
        dates: [{ year: 1960, month: 9 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.017, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/fac85a52-b745-44f3-81bb-6eb727db7f4f.pdf',
};
