export default {
  entity: {
    id: 'fb700078-9800-41c3-ae09-395ea6fa4c10',
    name: '文革通讯第21期',
    internal: false,
    official: false,
    type: 'pdf',
    author: '浙江工农兵美术大学毛泽东主义红卫兵战斗队、毛泽东主义红卫兵',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives15/main/fb700078-9800-41c3-ae09-395ea6fa4c10.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '毛主席的最新指示',
        authors: ['毛泽东'],
        page_start: 1,
        page_end: 1,
        dates: [{ year: 1967, month: 5, day: 4 }],
      },
      {
        title: '周总理谈军管任务',
        authors: ['周恩来'],
        page_start: 1,
        page_end: 2,
        dates: [{ year: 1967 }],
      },
      {
        title: '重整红卫兵军威',
        authors: ['张春桥'],
        page_start: 2,
        page_end: 2,
        dates: [{ year: 1967, month: 3, day: 12 }],
      },
      {
        title: '戚本禹同志讲话摘要——怎样对待伟大的中国人民解放军',
        authors: ['戚本禹'],
        page_start: 2,
        page_end: 2,
        dates: [{ year: 1967 }],
      },
      {
        title: '王力同志说：《文汇报》“四·九”社论是掌握大方向的',
        authors: ['王力'],
        page_start: 2,
        page_end: 3,
        dates: [{ year: 1967, month: 4, day: 30 }],
      },
      {
        title:
          '打倒中国的赫鲁晓夫——刘少奇！——叶林、周赤萍揭刘少奇、王光美、李雪峯',
        authors: ['叶林', '周赤萍'],
        page_start: 3,
        page_end: 3,
        dates: [{ year: 1967, month: 4, day: 10 }],
      },
      {
        title: '打倒中国的赫鲁晓夫——刘少奇！——公安部副部长李震同志谈刘、邓',
        authors: ['李震'],
        page_start: 3,
        page_end: 3,
        dates: [{ year: 1967 }],
      },
      {
        title: '打倒中国的赫鲁晓夫——刘少奇！——斩断刘少奇伸向嘉定的魔爪',
        authors: ['《文革通讯》编辑部'],
        page_start: 4,
        page_end: 4,
        dates: [{ year: 1967, month: 5, day: 4 }],
      },
      {
        title: '王光美丑闻二三事',
        authors: ['王光美'],
        page_start: 4,
        page_end: 4,
        dates: [{ year: 1967, month: 5, day: 4 }],
      },
      {
        title: '刘少奇丑恶灵魂的又一次大暴露',
        authors: ['《文革通讯》编辑部'],
        page_start: 4,
        page_end: 5,
        dates: [{ year: 1967, month: 5, day: 4 }],
      },
      {
        title: '北京消息',
        authors: ['《文革通讯》编辑部'],
        page_start: 5,
        page_end: 6,
        dates: [{ year: 1967, month: 5, day: 4 }],
      },
      {
        title: '彻底捣毁刘氏叛徒集团',
        authors: ['王鹤峯'],
        page_start: 5,
        page_end: 5,
        dates: [{ year: 1966, month: 11, day: 29 }],
      },
      {
        title: '祖国各地',
        authors: ['《文革通讯》编辑部'],
        page_start: 6,
        page_end: 8,
        dates: [{ year: 1967, month: 5, day: 4 }],
      },
      {
        title: '国际动态',
        authors: ['《文革通讯》编辑部'],
        page_start: 8,
        page_end: 8,
        dates: [{ year: 1967, month: 5, day: 4 }],
      },
      {
        title: '启事',
        authors: ['《文革通讯》编辑部'],
        page_start: 8,
        page_end: 8,
        dates: [{ year: 1967, month: 5, day: 4 }],
      },
    ],
    ocr: undefined,
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives15/fb700078-9800-41c3-ae09-395ea6fa4c10.pdf',
};
