export default {
  entity: {
    id: 'fdadf13c-2dcd-4c2a-aef9-41d2da14cc33',
    name: '红旗一九七二年第一期',
    internal: false,
    official: true,
    type: 'pdf',
    author: '《红旗》杂志编辑部',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives2/main/fdadf13c-2dcd-4c2a-aef9-41d2da14cc33.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '团结起来，争取更大的胜利（一九七二年元旦社论）',
        authors: [
          '《人民日报》编辑部',
          '《红旗》杂志编辑部',
          '《解放军报》编辑部',
        ],
        page_start: 8,
        page_end: 13,
        dates: [{ year: 1972, month: 1, day: 1 }],
      },
      {
        title:
          '我们应当相信群众 我们应当相信党——重读《中国农村的社会主义高潮》的序言和按语',
        authors: ['安学江'],
        page_start: 14,
        page_end: 21,
        dates: [{ year: 1972, month: 1, day: 1 }],
      },
      {
        title: '批判修正主义的锐利武器——学习《哥达纲领批判》的一点体会',
        authors: ['中国共产党黑龙江省委员会写作小组'],
        page_start: 22,
        page_end: 28,
        dates: [{ year: 1972, month: 1, day: 1 }],
      },
      {
        title: '在实践中不断发展对于真理的认识——学习《反杜林论》的一点体会',
        authors: ['中国共产党马鞍山市委员会'],
        page_start: 29,
        page_end: 33,
        dates: [{ year: 1972, month: 1, day: 1 }],
      },
      {
        title: '发扬党的紧密联系群众的光荣传统',
        authors: ['中国共产党甘肃省委员会写作小组'],
        page_start: 34,
        page_end: 40,
        dates: [{ year: 1972, month: 1, day: 1 }],
      },
      {
        title: '进一步加强党的一元化领导',
        authors: ['齐永红'],
        page_start: 41,
        page_end: 46,
        dates: [{ year: 1972, month: 1, day: 1 }],
      },
      {
        title: '“龙江风格”万古常青——评革命现代京剧《龙江颂》',
        authors: ['丁学雷'],
        page_start: 47,
        page_end: 55,
        dates: [{ year: 1972, month: 1, day: 1 }],
      },
      {
        title: '开发矿业 建设矿山',
        authors: ['中国共产党本溪钢铁公司委员会'],
        page_start: 56,
        page_end: 63,
        dates: [{ year: 1972, month: 1, day: 1 }],
      },
      {
        title: '调动一切积极因素努力办好中小矿山',
        authors: ['江虹'],
        page_start: 64,
        page_end: 67,
        dates: [{ year: 1972, month: 1, day: 1 }],
      },
      {
        title: '认真实行农林牧三结合——河北迁安县的调查报告',
        authors: ['农林部调查组'],
        page_start: 68,
        page_end: 75,
        dates: [{ year: 1972, month: 1, day: 1 }],
      },
      {
        title: '抓革命，促生产，扎扎实实学大寨',
        authors: ['中国共产党新乡县委员会'],
        page_start: 76,
        page_end: 80,
        dates: [{ year: 1972, month: 1, day: 1 }],
      },
      {
        title: '坚决执行三大纪律八项注意',
        authors: ['中国人民解放军南京部队某部三连党支部'],
        page_start: 81,
        page_end: 84,
        dates: [{ year: 1972, month: 1, day: 1 }],
      },
      {
        title: '同工农相结合的道路越走越宽广',
        authors: ['杨慧锦'],
        page_start: 85,
        page_end: 89,
        dates: [{ year: 1972, month: 1, day: 1 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.15, 0, 0.2] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives2/fdadf13c-2dcd-4c2a-aef9-41d2da14cc33.pdf',
};
