export default {
  entity: {
    id: 'ff7c277a-e54a-4c0f-97f7-f1548d7728b1',
    name: '马克思主义哲学基本知识（政治理论课辅助教材）湖南省衡阳、邵阳地区卫生学校编',
    internal: false,
    official: true,
    type: 'pdf',
    author: '湖南省衡阳地区卫生学校、邵阳地区卫生学校编',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/ff7c277a-e54a-4c0f-97f7-f1548d7728b1.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '第一章 什么是马克思主义哲学',
        authors: ['湖南省衡阳地区卫生学校', '湖南省邵阳地区卫生学校'],
        page_start: 8,
        page_end: 18,
        dates: [{ year: 1976, month: 3 }],
      },
      {
        title: '第二章 物质和意识',
        authors: ['湖南省衡阳地区卫生学校', '湖南省邵阳地区卫生学校'],
        page_start: 19,
        page_end: 36,
        dates: [{ year: 1976, month: 3 }],
      },
      {
        title: '第三章 对立统一规律',
        authors: ['湖南省衡阳地区卫生学校', '湖南省邵阳地区卫生学校'],
        page_start: 37,
        page_end: 85,
        dates: [{ year: 1976, month: 3 }],
      },
      {
        title: '第四章 认识和实践',
        authors: ['湖南省衡阳地区卫生学校', '湖南省邵阳地区卫生学校'],
        page_start: 86,
        page_end: 117,
        dates: [{ year: 1976, month: 3 }],
      },
      {
        title: '第五章 社会基本矛盾',
        authors: ['湖南省衡阳地区卫生学校', '湖南省邵阳地区卫生学校'],
        page_start: 118,
        page_end: 139,
        dates: [{ year: 1976, month: 3 }],
      },
      {
        title: '第六章 阶级和阶级斗争',
        authors: ['湖南省衡阳地区卫生学校', '湖南省邵阳地区卫生学校'],
        page_start: 140,
        page_end: 162,
        dates: [{ year: 1976, month: 3 }],
      },
      {
        title: '第七章 国家与革命',
        authors: ['湖南省衡阳地区卫生学校', '湖南省邵阳地区卫生学校'],
        page_start: 163,
        page_end: 178,
        dates: [{ year: 1976, month: 3 }],
      },
      {
        title: '第八章 无产阶级专政下的继续革命',
        authors: ['湖南省衡阳地区卫生学校', '湖南省邵阳地区卫生学校'],
        page_start: 179,
        page_end: 202,
        dates: [{ year: 1976, month: 3 }],
      },
      {
        title: '第九章 人民群众是历史的创造者',
        authors: ['湖南省衡阳地区卫生学校', '湖南省邵阳地区卫生学校'],
        page_start: 203,
        page_end: 216,
        dates: [{ year: 1976, month: 3 }],
      },
    ],
    ocr: { content_thresholds: [0, 0.114, 0, 0] },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/ff7c277a-e54a-4c0f-97f7-f1548d7728b1.pdf',
};
