export default {
  entity: {
    id: 'ff92c783-256c-487a-abd2-8e59e9be6390',
    name: '文革期间毛泽东及中央领导讲话（补篇）（港中文藏书）',
    internal: true,
    official: false,
    type: 'pdf',
    author: '香港中文大学藏书',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives3/main/ff92c783-256c-487a-abd2-8e59e9be6390.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '毛泽东在杭州同胡志明的谈话（节录）',
        authors: ['毛泽东'],
        page_start: 3,
        page_end: 10,
        dates: [{ year: 1966, month: 6, day: 10 }],
      },
      {
        title: '毛泽东在中央常委扩大会议的讲话',
        authors: ['毛泽东'],
        page_start: 10,
        page_end: 11,
        dates: [{ year: 1966, month: 8, day: 4 }],
      },
      {
        title: '中共中央关于八届十一中全会选举结果的通知',
        authors: ['中共中央'],
        page_start: 12,
        page_end: 12,
        dates: [{ year: 1966, month: 8, day: 14 }],
      },
      {
        title: '毛泽东接见卡博、巴卢库时的谈话（节录）',
        authors: ['毛泽东'],
        page_start: 12,
        page_end: 17,
        dates: [{ year: 1967, month: 2, day: 3 }],
      },
      {
        title: '毛泽东关于“九大”和整党问题的谈话',
        authors: ['毛泽东'],
        page_start: 18,
        page_end: 20,
        dates: [{ year: 1967, month: 11, day: 5 }],
      },
      {
        title: '周恩来在中国共产党第八届扩大的十二中全会开幕会上的讲话（节录）',
        authors: ['周恩来'],
        page_start: 21,
        page_end: 22,
        dates: [{ year: 1968, month: 10, day: 13 }],
      },
      {
        title:
          '康生、江青、姚文元、谢富治在中国共产党第八届扩大的十二中全会小组会议上的插话（节录）',
        authors: ['康生', '江青', '姚文元', '谢富治'],
        page_start: 22,
        page_end: 26,
        dates: [{ year: 1968, month: 10, day: 17 }],
      },
      {
        title: '毛泽东在中国共产党第八届扩大的十二中全会闭幕会上的讲话（节录）',
        authors: ['毛泽东'],
        page_start: 26,
        page_end: 28,
        dates: [{ year: 1968, month: 10, day: 31 }],
      },
      {
        title: '周恩来、毛泽东在李广桥支部关于“徐向前最近表现情况”报告上的批语',
        authors: ['毛泽东', '周恩来'],
        page_start: 28,
        page_end: 28,
        dates: [
          { year: 1968, month: 12, day: 29 },
          { year: 1969, month: 1, day: 3 },
        ],
      },
      {
        title: '毛泽东在中央文革碰头会上的讲话',
        authors: ['毛泽东'],
        page_start: 29,
        page_end: 31,
        dates: [{ year: 1969, month: 3, day: 15 }],
      },
      {
        title: '毛泽东在中国共产党第九届中央委员会第一次全体会议上的讲话',
        authors: ['毛泽东'],
        page_start: 31,
        page_end: 35,
        dates: [{ year: 1969, month: 4, day: 28 }],
      },
      {
        title: '中共中央关于打击反革命破坏活动的指示',
        authors: ['中共中央'],
        page_start: 36,
        page_end: 37,
        dates: [{ year: 1970, month: 1, day: 31 }],
      },
      {
        title: '毛泽东对刘少奇、王光美专案组关于王光美处理意见的报告的批语',
        authors: ['中共中央'],
        page_start: 38,
        page_end: 38,
        dates: [{ year: 1970, month: 7 }],
      },
      {
        title: '林彪在中国共产党九届二中全会第一次全体会上的讲话（节录）',
        authors: ['林彪'],
        page_start: 38,
        page_end: 42,
        dates: [{ year: 1970, month: 8, day: 23 }],
      },
      {
        title: '中国共产党九届二中全会第六号简报（华北组第二号简报）',
        authors: [],
        page_start: 42,
        page_end: 43,
        dates: [{ year: 1970, month: 8, day: 24 }],
      },
      {
        title: '陈伯达在中国共产党九届二中全会华北组的发言',
        authors: ['陈伯达'],
        page_start: 44,
        page_end: 45,
        dates: [{ year: 1970, month: 8, day: 24 }],
      },
      {
        title: '汪东兴在中国共产党九届二中全会华北组的发言',
        authors: ['汪东兴'],
        page_start: 46,
        page_end: 47,
        dates: [{ year: 1970, month: 8, day: 24 }],
      },
      {
        title: '吴法宪在中国共产党九届二中全会西南组的发言（节录）',
        authors: ['汪东兴'],
        page_start: 47,
        page_end: 49,
        dates: [{ year: 1970, month: 8, day: 24 }],
      },
      {
        title: '中共中央关于成立中央组织宣传组的决定',
        authors: ['汪东兴'],
        page_start: 50,
        page_end: 50,
        dates: [{ year: 1970, month: 11, day: 6 }],
      },
      {
        title: '毛泽东关于批陈整风运动的一个批语',
        authors: ['毛泽东'],
        page_start: 51,
        page_end: 51,
        dates: [{ year: 1971, month: 2, day: 19 }],
      },
      {
        title: '毛泽东对《无产阶级专政胜利万岁》一稿的批语',
        authors: ['毛泽东'],
        page_start: 51,
        page_end: 51,
        dates: [{ year: 1971, month: 3, day: 15 }],
      },
      {
        title: '中央政治局关于中美会谈的报告',
        authors: ['中央政治局'],
        page_start: 52,
        page_end: 56,
        dates: [{ year: 1971, month: 5, day: 29 }],
      },
      {
        title: '周恩来总理给尼克松总统的口信',
        authors: ['周恩来'],
        page_start: 57,
        page_end: 57,
        dates: [{ year: 1971, month: 5, day: 29 }],
      },
      {
        title: '毛泽东接见参加成都地区座谈会的同志时的讲话（节录）',
        authors: ['毛泽东'],
        page_start: 58,
        page_end: 59,
        dates: [{ year: 1971, month: 5, day: 29 }],
      },
      {
        title: '周恩来在中央批林整风汇报会第一次全体会议上的讲话（节录）',
        authors: ['周恩来'],
        page_start: 60,
        page_end: 66,
        dates: [{ year: 1972, month: 5, day: 21 }],
      },
      {
        title: '毛泽东会见斯里兰卡总理班达拉奈克夫人时的谈话（节录）',
        authors: ['毛泽东'],
        page_start: 67,
        page_end: 67,
        dates: [{ year: 1972, month: 6, day: 28 }],
      },
      {
        title: '中联部、外交部关于召开外事会议的请示报告和周恩来的批语',
        authors: ['中联部', '外交部', '周恩来'],
        page_start: 68,
        page_end: 69,
        dates: [
          { year: 1972, month: 11, day: 28 },
          { year: 1972, month: 11, day: 30 },
        ],
      },
      {
        title: '毛泽东对柴沫妻子王若林的信的批语',
        authors: ['毛泽东'],
        page_start: 69,
        page_end: 69,
        dates: [{ year: 1972, month: 12, day: 25 }],
      },
      {
        title: '毛泽东关于废除法西斯式审查方式的批语',
        authors: ['毛泽东'],
        page_start: 70,
        page_end: 70,
        dates: [{ year: 1972, month: 12 }],
      },
      {
        title: '毛泽东会见基辛格时的谈话（节录）',
        authors: ['毛泽东'],
        page_start: 71,
        page_end: 73,
        dates: [{ year: 1972, month: 12 }],
      },
      {
        title: '周恩来在听取汇报经济工作《十条》时的谈话',
        authors: ['周恩来'],
        page_start: 74,
        page_end: 76,
        dates: [{ year: 1973, month: 2, day: 26 }],
      },
      {
        title: '毛泽东会见马里国家元首特拉奥雷时的谈话（节录）',
        authors: ['毛泽东'],
        page_start: 76,
        page_end: 76,
        dates: [{ year: 1973, month: 6, day: 22 }],
      },
      {
        title: '毛泽东同王洪文、张春桥的谈话纪要',
        authors: ['毛泽东'],
        page_start: 77,
        page_end: 80,
        dates: [{ year: 1973, month: 7, day: 4 }],
      },
      {
        title: '毛泽东会见刚果人民共和国总统恩古瓦比时的谈话（节录）',
        authors: ['毛泽东'],
        page_start: 80,
        page_end: 81,
        dates: [{ year: 1973, month: 7, day: 29 }],
      },
      {
        title: '毛泽东对江青诬陷周恩来的批评',
        authors: ['毛泽东'],
        page_start: 82,
        page_end: 82,
        dates: [{ year: 1973, month: 12, day: 9 }],
      },
      {
        title: '毛泽东关于大军区司令员对调等问题的谈话要点',
        authors: ['毛泽东'],
        page_start: 83,
        page_end: 88,
        dates: [{ year: 1973, month: 12 }],
      },
      {
        title: '毛泽东接见中央军委会议同志时的谈话（节录）',
        authors: ['毛泽东'],
        page_start: 89,
        page_end: 89,
        dates: [{ year: 1973, month: 12, day: 21 }],
      },
      {
        title: '毛泽东会见赞比亚总统卡翁达时的谈话（节录）',
        authors: ['毛泽东'],
        page_start: 90,
        page_end: 90,
        dates: [{ year: 1974, month: 2, day: 22 }],
      },
      {
        title: '毛泽东在中央政治局会议上批评江青的谈话',
        authors: ['毛泽东'],
        page_start: 91,
        page_end: 91,
        dates: [{ year: 1974, month: 7, day: 17 }],
      },
      {
        title: '毛泽东同邓小平在长沙的一次谈话（节录）',
        authors: ['毛泽东'],
        page_start: 92,
        page_end: 92,
        dates: [{ year: 1974, month: 11, day: 12 }],
      },
      {
        title: '周恩来在政治局常委会上传达的毛泽东谈话要点（节录）',
        authors: ['周恩来'],
        page_start: 92,
        page_end: 93,
        is_range_date: true,
        dates: [
          { year: 1974, month: 10 },
          { year: 1975, month: 3 },
        ],
      },
      {
        title: '周恩来关于国务院各副总理分工问题的请示报告',
        authors: ['周恩来'],
        page_start: 94,
        page_end: 94,
        dates: [{ year: 1975, month: 2, day: 2 }],
      },
      {
        title: '中共中央关于学习毛泽东对理论问题指示的通知',
        authors: ['中共中央'],
        page_start: 95,
        page_end: 96,
        dates: [{ year: 1975, month: 2, day: 18 }],
      },
      {
        title: '毛泽东同在京中央政治局委员的谈话',
        authors: ['毛泽东'],
        page_start: 96,
        page_end: 101,
        dates: [{ year: 1975, month: 5, day: 3 }],
      },
      {
        title:
          '周恩来就如何传达毛泽东四月二十三日批示等问题给中央政治局委员的信',
        authors: ['周恩来'],
        page_start: 101,
        page_end: 103,
        dates: [{ year: 1975, month: 5, day: 21 }],
      },
      {
        title: '中央政治局批评“四人帮”的两次会议记录',
        authors: ['中央政治局'],
        page_start: 104,
        page_end: 107,
        dates: [
          { year: 1975, month: 5, day: 27 },
          { year: 1975, month: 6, day: 3 },
        ],
      },
      {
        title: '毛泽东同邓小平关于批评“四人帮”的一次谈话（节录）',
        authors: ['毛泽东'],
        page_start: 108,
        page_end: 108,
        dates: [{ year: 1975, month: 6 }],
      },
      {
        title: '毛主席重要指示',
        authors: ['毛泽东'],
        page_start: 109,
        page_end: 115,
        is_range_date: true,
        dates: [
          { year: 1975, month: 10 },
          { year: 1976, month: 1 },
        ],
      },
      {
        title:
          '中共中央关于转发华国锋在中央召集的各省、市、自治区和各大军区同志会议上讲话的通知',
        authors: ['中共中央'],
        page_start: 115,
        page_end: 115,
        dates: [{ year: 1976, month: 3, day: 3 }],
      },
      {
        title: '华国锋同志的讲话',
        authors: ['华国锋'],
        page_start: 116,
        page_end: 117,
        dates: [{ year: 1976, month: 2, day: 25 }],
      },
      {
        title: '中央政治局四月一日会议情况',
        authors: ['中央政治局'],
        page_start: 117,
        page_end: 118,
        dates: [{ year: 1976, month: 4, day: 2 }],
      },
      {
        title: '中央政治局四月四日会议记录',
        authors: ['中央政治局'],
        page_start: 118,
        page_end: 121,
        dates: [{ year: 1976, month: 4, day: 4 }],
      },
      {
        title: '中央政治局四月五日会议记录',
        authors: ['中央政治局'],
        page_start: 122,
        page_end: 124,
        dates: [{ year: 1976, month: 4, day: 5 }],
      },
      {
        title:
          '毛泽东对毛远新关于四月六日中央政治局讨论天安门事件情况报告的批语',
        authors: ['毛泽东'],
        page_start: 124,
        page_end: 127,
        dates: [{ year: 1976, month: 4, day: 6 }],
      },
      {
        title: '毛泽东关于天安门事件性质问题所写的字迹',
        authors: ['毛泽东'],
        page_start: 127,
        page_end: 129,
        dates: [{ year: 1976, month: 4, day: 7 }],
      },
      {
        title:
          '中共中央关于华国锋任中国共产党中央委员会第一副主席、中华人民共和国国务院总理的决议',
        authors: ['中共中央'],
        page_start: 129,
        page_end: 129,
        dates: [{ year: 1976, month: 4, day: 7 }],
      },
      {
        title: '中共中央文件 中发〔1972〕3号',
        authors: ['中共中央'],
        page_start: 130,
        page_end: 130,
        dates: [{ year: 1972, month: 1, day: 13 }],
      },
      {
        title: '中共中央文件 中发〔1972〕16号',
        authors: ['中共中央'],
        page_start: 131,
        page_end: 131,
        dates: [{ year: 1972, month: 4, day: 25 }],
      },
      {
        title: '浙江来京开会同志关于继续深入开展反对林陈反党集团斗争的请示报告',
        authors: [],
        page_start: 132,
        page_end: 135,
        dates: [],
      },
      {
        title: '中共浙江省委文件 省委〔1972〕9号',
        authors: ['中共浙江省委'],
        page_start: 136,
        page_end: 147,
        dates: [{ year: 1972, month: 6, day: 28 }],
      },
      {
        title: '中共浙江省委文件 省委〔1972〕11号',
        authors: ['中共浙江省委'],
        page_start: 148,
        page_end: 149,
        dates: [{ year: 1972, month: 7, day: 2 }],
      },
    ],
    ocr: { auto_vsplit: false, vsplit: 0.5 },
    ocr_exceptions: {},
  },
  parser_id: 'automation',
  path: '/archives3/ff92c783-256c-487a-abd2-8e59e9be6390.pdf',
};
