export default {
  entity: {
    id: 'maoquanji40',
    name: '毛泽东全集第40卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives0/main/mao-quanji/maoquanji40.pdf',
  },
  parser_option: {
    ext: 'pdf',
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
    page_limits: [],
    articles: [
      {
        page_start: 23,
        page_end: 24,
        title: '视察天津时的谈话（汇集）',
        dates: [{ year: 1958, month: 8, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 34,
        page_end: 35,
        title: '毛泽东等祝贺朝鲜解放十三周年的电报',
        dates: [{ year: 1958, month: 8, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 36,
        page_end: 36,
        title: '控制学生数量、多搞技术学校',
        dates: [{ year: 1958, month: 8, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 38,
        page_end: 38,
        title: '祝贺印度尼西亚独立十三周年的电报',
        dates: [{ year: 1958, month: 8, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 39,
        page_end: 43,
        title: '对陆定一《教育必须与生产劳动相结合》一文的批语、按语和修改',
        dates: [{ year: 1958, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 44,
        page_end: 44,
        title: '大国小国应该平等相待',
        dates: [{ year: 1958, month: 8, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 45,
        page_end: 49,
        title: '在北戴河政治局扩大会议上的讲话（一）',
        dates: [{ year: 1958, month: 8, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 51,
        page_end: 52,
        title: '对《蚜山卫星人民公社试行简章（草案）》的批语和修改',
        dates: [{ year: 1958, month: 8, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 70,
        page_end: 70,
        title: '关于停止在深圳方面的演习准备打金门的批语',
        dates: [{ year: 1958, month: 8, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 71,
        page_end: 71,
        title: '关于索要《科学简讯》的批语',
        dates: [{ year: 1958, month: 8, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 72,
        page_end: 76,
        title: '在北戴河政治局扩大会议上的讲话（二）',
        dates: [{ year: 1958, month: 8, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 77,
        page_end: 77,
        title: '关于印发刘晓给中央电报的批语',
        dates: [{ year: 1958, month: 8, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 78,
        page_end: 83,
        title: '在北戴河政治局扩大会议上的讲话（三）',
        dates: [{ year: 1958, month: 8, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 84,
        page_end: 90,
        title: '在北戴河政治局扩大会议上的讲话（四）',
        dates: [{ year: 1958, month: 8, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 91,
        page_end: 91,
        title: '对开展农村工具改良运动的指示',
        dates: [{ year: 1958, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 92,
        page_end: 92,
        title: '对青海省委关于循化撒拉族自治县反革命武装叛乱事件的报告的批语',
        dates: [{ year: 1958, month: 8, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 93,
        page_end: 94,
        title: '毛泽东等祝贺罗马尼亚解放十四周年的电报',
        dates: [{ year: 1958, month: 8, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 95,
        page_end: 95,
        title: '对中央关于教育工作指示草案的批语',
        dates: [{ year: 1958, month: 8, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 96,
        page_end: 96,
        title: '对北戴河中央政治局扩大会议讨论的关于农业方面的文件的批语',
        dates: [{ year: 1958, month: 8, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 97,
        page_end: 104,
        title: '在北戴河政治局扩大会议上的讲话（五）',
        dates: [{ year: 1958, month: 8, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 105,
        page_end: 105,
        title: '在北戴河会议关于民兵问题的决定稿上加写的话',
        dates: [{ year: 1958, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 106,
        page_end: 107,
        title: '在中央关于在农村建立人民公社问题的决议稿上加写的话',
        dates: [{ year: 1958, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 108,
        page_end: 111,
        title: '关于主要矛盾问题',
        dates: [{ year: 1958, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 112,
        page_end: 114,
        title: '关于编印《中共中央政治局北戴河扩大会议文件汇集》的批语',
        dates: [{ year: 1958, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 115,
        page_end: 116,
        title: '毛泽东等祝贺越南民主共和国成立十三周年的电报',
        dates: [{ year: 1958, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 117,
        page_end: 119,
        title: '对北戴河会议工业类文件的意见',
        dates: [{ year: 1958, month: 9, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 120,
        page_end: 125,
        title: '和巴西记者马罗金、杜特列夫人的谈话',
        dates: [{ year: 1958, month: 9, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 126,
        page_end: 127,
        title: '在军委关于对台湾和沿海蒋占岛屿军事斗争的指示稿上的批语',
        dates: [{ year: 1958, month: 9, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 128,
        page_end: 148,
        title: '在第十五次最高国务会议上的讲话',
        dates: [
          { year: 1958, month: 9, day: 5 },
          { year: 1958, month: 9, day: 8 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 149,
        page_end: 150,
        title: '对全国办人民公社情况汇报的批语',
        dates: [{ year: 1958, month: 9, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 151,
        page_end: 153,
        title: '整台湾是整家法',
        dates: [{ year: 1958, month: 9, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 154,
        page_end: 155,
        title: '关于研究赫鲁晓夫给艾森豪威尔的信稿的批语',
        dates: [{ year: 1958, month: 9, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 156,
        page_end: 157,
        title: '在第十五次最高国务会议上讲话的新闻稿',
        dates: [{ year: 1958, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 158,
        page_end: 159,
        title: '毛泽东等祝贺朝鲜民主主义人民共和国成立十周年的电报',
        dates: [{ year: 1958, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 160,
        page_end: 161,
        title: '毛泽东等祝贺保加利亚人民共和国国庆的电报',
        dates: [{ year: 1958, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 162,
        page_end: 162,
        title: '关于台湾局势等问题复胡志明电',
        dates: [{ year: 1958, month: 9, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 164,
        page_end: 164,
        title: '给湘乡县东山学校的信',
        dates: [{ year: 1958, month: 9, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 166,
        page_end: 166,
        title: '给毛禹居的信',
        dates: [{ year: 1958, month: 9, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 169,
        page_end: 169,
        title: '视察武汉大学的指示',
        dates: [{ year: 1958, month: 9, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 179,
        page_end: 180,
        title: '关于金门炮击办法等问题的信',
        dates: [{ year: 1958, month: 9, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 181,
        page_end: 181,
        title: '视察武钢时的指示',
        dates: [{ year: 1958, month: 9, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 195,
        page_end: 195,
        title: '对人民日报、新华通讯社《动态》的批语',
        dates: [{ year: 1958, month: 9, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 200,
        page_end: 200,
        title: '给王任重的信',
        dates: [{ year: 1958, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 202,
        page_end: 202,
        title: '为二七烈士纪念碑题名',
        dates: [{ year: 1958, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 204,
        page_end: 204,
        title: '给曾希圣的信',
        dates: [{ year: 1958, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 226,
        page_end: 226,
        title: '在《钢铁生产紧急会报会商定事项的通知》上的批语',
        dates: [{ year: 1958, month: 9, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 239,
        page_end: 239,
        title: '外交斗争必须高屋建领势如破竹',
        dates: [{ year: 1958, month: 9, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 240,
        page_end: 240,
        title: '给曾希圣的信',
        dates: [{ year: 1958, month: 9, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 260,
        page_end: 260,
        title: '给江渭清的信',
        dates: [{ year: 1958, month: 9, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 262,
        page_end: 263,
        title: '关于承认阿尔及利亚临时政府等问题致周恩来电',
        dates: [{ year: 1958, month: 9, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 264,
        page_end: 264,
        title: '祝贺阿尔及利亚共和国临时政府成立的电报',
        dates: [{ year: 1958, month: 9, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 265,
        page_end: 265,
        title: '关于阅看陆定一《教育必须与生产劳动相结合》一文给江青的批语',
        dates: [{ year: 1958, month: 9, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 266,
        page_end: 269,
        title: '巡视大江南北后对新华社记者的谈话',
        dates: [{ year: 1958, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 271,
        page_end: 272,
        title: '关于游泳的几次指示',
        dates: [
          { year: 1958, month: 9 },
          { year: 1958, month: 1966, day: 7 },
        ],
        is_range_date: true,
        authors: ['毛泽东'],
      },
      {
        page_start: 275,
        page_end: 275,
        title: '关于报道钢铁生产情况的批语',
        dates: [{ year: 1958, month: 9, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 276,
        page_end: 276,
        title: '报纸一个时期要有一定的方向',
        dates: [{ year: 1958, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 277,
        page_end: 277,
        title: '为《锡林郭勒日报》题写报头',
        dates: [{ year: 1958, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 285,
        page_end: 288,
        title: '杜勒斯是世界上最好的反面教员',
        dates: [{ year: 1958, month: 10, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 289,
        page_end: 289,
        title: '对一封反映安徽省灵璧县灾情的来信的批语',
        dates: [{ year: 1958, month: 10, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 290,
        page_end: 290,
        title: '给袁水拍的信',
        dates: [{ year: 1958, month: 10, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 291,
        page_end: 292,
        title: '灵机应变主动在我',
        dates: [{ year: 1958, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 294,
        page_end: 295,
        title: '关于暂停炮击和发表《告台湾同胞书》给彭德怀、黄克诚的信',
        dates: [
          { year: 1958, month: 10, day: 5 },
          { year: 1958, month: 10, day: 6 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 296,
        page_end: 298,
        title: '中华人民共和国国防部告台湾同胞书',
        dates: [{ year: 1958, month: 10, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 299,
        page_end: 300,
        title: '毛泽东等祝贺德意志民主共和国国庆的电报',
        dates: [{ year: 1958, month: 10, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 301,
        page_end: 301,
        title: '祝贺几内亚共和国成立的电报',
        dates: [{ year: 1958, month: 10, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 302,
        page_end: 302,
        title: '给仇亦山的信',
        dates: [{ year: 1958, month: 10, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 304,
        page_end: 305,
        title: '对《人民日报》社论稿《且看他们怎样动作》的批语和修改',
        dates: [{ year: 1958, month: 10, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 306,
        page_end: 307,
        title: '关于转载《破除资产阶级的法权思想》一文给吴冷西的信',
        dates: [{ year: 1958, month: 10, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 308,
        page_end: 308,
        title: '关于苏共中央来信等问题给周恩来的电报',
        dates: [{ year: 1958, month: 10, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 309,
        page_end: 310,
        title: '对卫生部党组关于西医学中医离职学习班的总结报告的批语',
        dates: [{ year: 1958, month: 10, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 312,
        page_end: 313,
        title: '中华人民共和国国防部命令',
        dates: [{ year: 1958, month: 10, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 314,
        page_end: 317,
        title: '再告台湾同胞书稿',
        dates: [{ year: 1958, month: 10, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 318,
        page_end: 318,
        title: '关于找草书字帖给田家英的信',
        dates: [{ year: 1958, month: 10, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 319,
        page_end: 321,
        title: '关于到河南遂平调查人民公社问题给陈伯达的信',
        dates: [{ year: 1958, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 323,
        page_end: 324,
        title: '关于国防部恢复炮击命令的批语',
        dates: [{ year: 1958, month: 10, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 325,
        page_end: 325,
        title: '给周恩来的信',
        dates: [{ year: 1958, month: 10, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 326,
        page_end: 328,
        title: '中华人民共和国国防部再告台湾同胞书',
        dates: [{ year: 1958, month: 10, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 329,
        page_end: 330,
        title: '给周世钊的信',
        dates: [{ year: 1958, month: 10, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 331,
        page_end: 331,
        title: '在参观中国科学院时和钱学森的谈话',
        dates: [{ year: 1958, month: 10, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 335,
        page_end: 337,
        title: '对王鹤寿关于钢铁方面几个问题的报告的批语',
        dates: [{ year: 1958, month: 10, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 338,
        page_end: 339,
        title: '对湖南省委关于开展共产主义教育运动意见的批语',
        dates: [{ year: 1958, month: 10, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 340,
        page_end: 340,
        title: '金门单日打炮双日不打炮',
        dates: [{ year: 1958, month: 10, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 341,
        page_end: 343,
        title: '在石家庄地区的谈话',
        dates: [{ year: 1958, month: 10, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 344,
        page_end: 345,
        title:
          '关于转载《毛泽东同志论帝国主义和一切反动派都是纸老虎》的批语和对《人民日报》编者按的修改',
        dates: [{ year: 1958, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 346,
        page_end: 347,
        title: '对《谈谈削除资产阶级法权》一文的批注',
        dates: [{ year: 1958, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 348,
        page_end: 349,
        title: '对驻苏大使馆关于中苏北京会谈以来苏联各方面情况报告的批语',
        dates: [{ year: 1958, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 350,
        page_end: 351,
        title: '听取华北、东北九省农业协作会议的汇报后的指示',
        dates: [{ year: 1958, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 352,
        page_end: 357,
        title: '在邯郸地区的谈话',
        dates: [{ year: 1958, month: 11, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 358,
        page_end: 362,
        title: '在新乡地区和五个县委书记谈话纪要',
        dates: [{ year: 1958, month: 11, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 363,
        page_end: 363,
        title: '建议金门炮击大打一天给周恩来等的信',
        dates: [{ year: 1958, month: 11, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 364,
        page_end: 364,
        title: '为厦门前线写的广播稿',
        dates: [{ year: 1958, month: 11, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 365,
        page_end: 368,
        title: '在为八届六中全会作准备的郑州会议上的讲话（一）',
        dates: [{ year: 1958, month: 11, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 369,
        page_end: 369,
        title: '对轻工业部党组关于人民公社大办工业问题报告的批语',
        dates: [{ year: 1958, month: 11, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 370,
        page_end: 372,
        title: '对《山东范县提出一九六O年过渡到共产主义》一文的批语',
        dates: [{ year: 1958, month: 11, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 373,
        page_end: 376,
        title: '在为八届六中全会作准备的郑州会议上的讲话（二）',
        dates: [{ year: 1958, month: 11, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 377,
        page_end: 378,
        title: '毛泽东等祝贺苏联十月革命四十一周年的电报',
        dates: [{ year: 1958, month: 11, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 379,
        page_end: 381,
        title: '在为八届六中全会作准备的郑州会议上的讲话（三）',
        dates: [{ year: 1958, month: 11, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 382,
        page_end: 383,
        title: '对山西省太谷县红旗人民公社的情况与计划的批语',
        dates: [{ year: 1958, month: 11, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 384,
        page_end: 389,
        title:
          '对《十五年社会主义建设纲要四十条（一九五八九七二年）》初稿的批语和修改',
        dates: [{ year: 1958, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 390,
        page_end: 391,
        title: '关于读书的建议',
        dates: [{ year: 1958, month: 11, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 393,
        page_end: 399,
        title: '在为八届六中全会作准备的郑州会议上的讲话（四）',
        dates: [{ year: 1958, month: 11, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 400,
        page_end: 403,
        title: '在为八届六中全会作准备的郑州会议上的讲话（五）',
        dates: [{ year: 1958, month: 11, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 404,
        page_end: 414,
        title: '在为八届六中全会作准备的郑州会议上的讲话（六）',
        dates: [{ year: 1958, month: 11, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 415,
        page_end: 422,
        title: '对《郑州会议关于人民公社若干问题的决议》的修改和信件',
        dates: [
          { year: 1958, month: 11, day: 10 },
          { year: 1958, month: 11, day: 12 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 423,
        page_end: 425,
        title: '对中办机要室关于在徐水县劳动中所见所闻情况报告的批语',
        dates: [{ year: 1958, month: 11, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 432,
        page_end: 433,
        title: '关于建议在北京开会为武昌会议作准备等问题给刘少奇、邓小平的电报',
        dates: [{ year: 1958, month: 11, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 434,
        page_end: 435,
        title: '在轻工业部党组关于大力发展猪皮制革的报告上的批语',
        dates: [{ year: 1958, month: 11, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 436,
        page_end: 436,
        title: '祝贺也门王国国庆的电报',
        dates: [{ year: 1958, month: 11, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 437,
        page_end: 438,
        title: '关于工作、生活同时并重方针的批语',
        dates: [{ year: 1958, month: 11, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 439,
        page_end: 439,
        title: '对湖南省岳阳县筹办人民公学的批语',
        dates: [{ year: 1958, month: 11, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 440,
        page_end: 441,
        title: '关于印发《人民日报》社论《苏联走向共产主义的巨大步骤》的批语',
        dates: [{ year: 1958, month: 11, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 442,
        page_end: 443,
        title: '对《关于“一个县能否进入共产主义”的辩论》一文的批语',
        dates: [{ year: 1958, month: 11, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 444,
        page_end: 445,
        title: '对《长春汽车厂发动群众大闹技术革命的经验》一文的批语',
        dates: [{ year: 1958, month: 11, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 446,
        page_end: 446,
        title: '中共中央对卫生部党组关于组织西医离职学习中医班总结报告的批示',
        dates: [{ year: 1958, month: 11, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 447,
        page_end: 452,
        title: '对谭震林、廖鲁言关于农业生产和农村人民公社情况报告的批语和修改',
        dates: [{ year: 1958, month: 11, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 453,
        page_end: 455,
        title: '对化工部党组关于扭转化学工业发展的被动局面的报告的批语',
        dates: [{ year: 1958, month: 11, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 456,
        page_end: 457,
        title: '对国家建委党组关于当前基本建设工作中几个重大问题的报告的批语',
        dates: [{ year: 1958, month: 11, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 458,
        page_end: 458,
        title: '关于印发《苏联政治经济学教科书第三版的主要修改和补充》的批语',
        dates: [{ year: 1958, month: 11, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 459,
        page_end: 459,
        title: '对《安国的小麦千亩天下第一田》一文的批语',
        dates: [{ year: 1958, month: 11, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 460,
        page_end: 461,
        title: '在中央政治局武昌扩大会议上的讲话提纲',
        dates: [{ year: 1958, month: 11, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 462,
        page_end: 474,
        title: '在武昌会议上的讲话（一）',
        dates: [{ year: 1958, month: 11, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 475,
        page_end: 476,
        title: '记者头脑要冷静',
        dates: [{ year: 1958, month: 11, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 477,
        page_end: 479,
        title: '对湖北省委关于做好当前人民生活的几项工作的规定的批语',
        dates: [
          { year: 1958, month: 11, day: 21 },
          { year: 1958, month: 11, day: 27 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 480,
        page_end: 480,
        title: '给李富春的信',
        dates: [{ year: 1958, month: 11, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 484,
        page_end: 485,
        title: '对湖北省委关于人民公社实行工资制和供给制的指示稿的批语',
        dates: [
          { year: 1958, month: 11, day: 22 },
          { year: 1958, month: 12, day: 6 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 487,
        page_end: 488,
        title: '毛泽东等祝贺中朝经济及文化合作协定签订五周年的电报',
        dates: [{ year: 1958, month: 11, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 489,
        page_end: 498,
        title: '在武昌会议上的讲话（二）',
        dates: [{ year: 1958, month: 11, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 499,
        page_end: 501,
        title:
          '对《中共中央、国务院关于适应人民公社化的形势改进农村财政贸易管理体制决定》草案的批语和修改',
        dates: [{ year: 1958, month: 11, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 502,
        page_end: 510,
        title: '对《关于人民公社若干问题的决议》稿的批语和修改',
        dates: [
          { year: 1958, month: 11 },
          { year: 1958, month: 12 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 511,
        page_end: 513,
        title: '对《财经各部委党组讨论（苏联社会主义经济问题）》一文的批语',
        dates: [{ year: 1958, month: 11, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 514,
        page_end: 515,
        title: '对《宦乡论西方世界的破裂》的批语',
        dates: [{ year: 1958, month: 11, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 516,
        page_end: 517,
        title: '一个教训',
        dates: [{ year: 1958, month: 11, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 518,
        page_end: 518,
        title: '第十次接见朝鲜代表团时的讲话',
        dates: [{ year: 1958, month: 11, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 520,
        page_end: 521,
        title: '对《苏联学者关于共产主义建设理论问题的几个新提法》一文的批语',
        dates: [{ year: 1958, month: 11, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 522,
        page_end: 523,
        title: '民兵现在主要是对付帝国主义侵略',
        dates: [{ year: 1958, month: 11, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 524,
        page_end: 525,
        title: '对《美国政治气氛向好的方面发展》的批语',
        dates: [{ year: 1958, month: 11, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 526,
        page_end: 526,
        title: '关于中共八届六中全会议程给邓小平的信',
        dates: [{ year: 1958, month: 11, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 527,
        page_end: 528,
        title: '毛泽东等祝贺阿尔巴尼亚解放十四周年的电报',
        dates: [{ year: 1958, month: 11, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
    ],
  },
  parser_id: 'automation',
  path: '/archives0/mao-quanji/maoquanji40.pdf',
};
