export default {
  entity: {
    id: 'maoquanji27',
    name: '毛泽东全集第27卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives0/main/maoquanji27.pdf',
  },
  parser_option: {
    articles: [
      {
        page_start: 32,
        page_end: 33,
        title: '在中央团校第一期学员毕业典礼上的讲话',
        dates: [{ year: 1949, month: 7, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 34,
        page_end: 34,
        title: '在中华全国文学艺术工作者代表大会上的讲话',
        dates: [{ year: 1949, month: 7, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 35,
        page_end: 39,
        title: '为纪念“七七”抗日战争十二周年宣言',
        dates: [{ year: 1949, month: 7, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 40,
        page_end: 40,
        title: '致总前委并粟裕、张震、周骏鸣电',
        dates: [{ year: 1949, month: 7, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 41,
        page_end: 42,
        title: '九月或十月前闽粤赣边纵队须独力作战',
        dates: [{ year: 1949, month: 7, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 43,
        page_end: 45,
        title: '依靠群众办好铁路建设事业',
        dates: [{ year: 1949, month: 7, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 46,
        page_end: 47,
        title: '四野应以一部向长沙湘潭推进',
        dates: [{ year: 1949, month: 7, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 48,
        page_end: 48,
        title: '复左协中将军等电',
        dates: [{ year: 1949, month: 7, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 49,
        page_end: 49,
        title: '关于打胡战役的指示',
        dates: [{ year: 1949, month: 7, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 51,
        page_end: 51,
        title: '歼灭马步芳等部的部署',
        dates: [{ year: 1949, month: 7, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 52,
        page_end: 52,
        title: '为《中国人民解放军三年战绩》一书题词',
        dates: [{ year: 1949, month: 7, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 53,
        page_end: 57,
        title: '采取远距离包围迁回方法追歼白崇禧部',
        dates: [
          { year: 1949, month: 7, day: 16 },
          { year: 1949, month: 7, day: 17 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 59,
        page_end: 60,
        title: '军委关于对程潜的方针的指示',
        dates: [{ year: 1949, month: 7, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 62,
        page_end: 62,
        title: '致林彪、邓子恢、萧克电',
        dates: [{ year: 1949, month: 7, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 63,
        page_end: 63,
        title: '致彭德怀、张宗逊、赵寿山电',
        dates: [{ year: 1949, month: 7, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 64,
        page_end: 64,
        title: '中共中央关于同意武昌划归湖北省建制致华中局电',
        dates: [{ year: 1949, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 65,
        page_end: 66,
        title: '陈邓华两兵团进攻广东的部署',
        dates: [{ year: 1949, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 67,
        page_end: 67,
        title: '复古巴人民社会党总书记电',
        dates: [{ year: 1949, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 68,
        page_end: 68,
        title: '复华东局电',
        dates: [{ year: 1949, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 69,
        page_end: 69,
        title: '致周恩来电',
        dates: [{ year: 1949, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 70,
        page_end: 70,
        title: '关于李达去湖南工作问题给周恩来的批示',
        dates: [
          { year: 1949, month: 7, day: 21 },
          { year: 1949, month: 7, day: 26 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 71,
        page_end: 71,
        title: '致华东局、南京市委电',
        dates: [{ year: 1949, month: 7, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 72,
        page_end: 72,
        title: '致华中局、华南分局、西北局等电',
        dates: [{ year: 1949, month: 7, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 73,
        page_end: 74,
        title: '对举行平凉战役以及西进作战的意见',
        dates: [{ year: 1949, month: 7, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 75,
        page_end: 76,
        title: '陈邓华两兵团在湘赣粤的行动计划',
        dates: [{ year: 1949, month: 7, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 77,
        page_end: 77,
        title: '为纪念邹韬奋逝世五周年题词',
        dates: [{ year: 1949, month: 7, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 79,
        page_end: 80,
        title: '陈邓华等兵团进军地区和路线问题',
        dates: [{ year: 1949, month: 7, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 81,
        page_end: 81,
        title: '复刘少奇、高岗、王稼祥电',
        dates: [{ year: 1949, month: 7, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 82,
        page_end: 82,
        title: '复林彪、邓子恢、萧克、赵尔陆电',
        dates: [{ year: 1949, month: 7, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 83,
        page_end: 83,
        title: '关于转发方方、魏金水致中共中央军委电的批语',
        dates: [{ year: 1949, month: 7, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 84,
        page_end: 84,
        title: '为戏曲改进会发起人大会题词',
        dates: [{ year: 1949, month: 7, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 85,
        page_end: 85,
        title: '关于刘少奇可先回国参加新政协会议致刘少奇、王稼祥电',
        dates: [{ year: 1949, month: 7, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 87,
        page_end: 89,
        title: '我们是能够克服困难的',
        dates: [{ year: 1949, month: 7, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 91,
        page_end: 91,
        title: '人民解放军二十二年的历史经验',
        dates: [{ year: 1949, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 100,
        page_end: 102,
        title: '中央关于华南分局、华中局、西南局的干部配备及其管辖范围的指示',
        dates: [{ year: 1949, month: 8, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 103,
        page_end: 103,
        title: '为《河北日报》题写报头',
        dates: [{ year: 1949, month: 8, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 104,
        page_end: 104,
        title: '为《唐山劳动日报》题写报头',
        dates: [{ year: 1949, month: 8, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 105,
        page_end: 105,
        title: '复栗裕等电',
        dates: [{ year: 1949, month: 8, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 106,
        page_end: 106,
        title: '复林彪、邓子恢、萧克、赵尔陆电',
        dates: [{ year: 1949, month: 8, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 107,
        page_end: 107,
        title: '中共中央关于东北人民政府委员候选人问题致东北局电',
        dates: [{ year: 1949, month: 8, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 108,
        page_end: 108,
        title: '复刘少奇、王稼祥电',
        dates: [{ year: 1949, month: 8, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 109,
        page_end: 109,
        title: '复刘少奇、高岗、王稼祥电',
        dates: [{ year: 1949, month: 8, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 110,
        page_end: 110,
        title: '对华北人民革命大学第一期教育经验总结的批语',
        dates: [{ year: 1949, month: 8, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 111,
        page_end: 111,
        title: '复程潜电',
        dates: [{ year: 1949, month: 8, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 112,
        page_end: 112,
        title: '致林彪、邓子恢等电',
        dates: [{ year: 1949, month: 8, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 113,
        page_end: 113,
        title: '致华中局等电',
        dates: [{ year: 1949, month: 8, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 114,
        page_end: 115,
        title: '争取程潜等站在我们方面有极大的政治作用',
        dates: [{ year: 1949, month: 8, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 116,
        page_end: 116,
        title: '要十分注意保护并尊重班禅额尔德尼等',
        dates: [{ year: 1949, month: 8, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 117,
        page_end: 120,
        title: '兼取政治方式解决西北地区',
        dates: [{ year: 1949, month: 8, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 121,
        page_end: 121,
        title: '复刘少奇、王稼祥电',
        dates: [{ year: 1949, month: 8, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 122,
        page_end: 122,
        title: '复华东局电',
        dates: [{ year: 1949, month: 8, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 123,
        page_end: 123,
        title: '致方方等电',
        dates: [{ year: 1949, month: 8, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 124,
        page_end: 124,
        title: '同意以中间不动两头平的政策解决河南土地问题',
        dates: [{ year: 1949, month: 8, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 125,
        page_end: 125,
        title: '给杨开智的信',
        dates: [{ year: 1949, month: 8, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 126,
        page_end: 127,
        title: '关于工会工作的方针',
        dates: [{ year: 1949, month: 8, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 128,
        page_end: 128,
        title: '复周世钊电',
        dates: [{ year: 1949, month: 8, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 129,
        page_end: 129,
        title: '在北平各界代表会议上的讲话',
        dates: [{ year: 1949, month: 8, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 130,
        page_end: 130,
        title: '复陈明仁电',
        dates: [{ year: 1949, month: 8, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 132,
        page_end: 132,
        title: '为《铁军报》题写报头',
        dates: [{ year: 1949, month: 8, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 133,
        page_end: 133,
        title: '给胡乔木的信',
        dates: [{ year: 1949, month: 8, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 134,
        page_end: 134,
        title: '复华东局电',
        dates: [{ year: 1949, month: 8, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 135,
        page_end: 141,
        title: '丢掉幻想，准备斗争',
        dates: [{ year: 1949, month: 8, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 142,
        page_end: 142,
        title: '复程潜、陈明仁等电',
        dates: [{ year: 1949, month: 8, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 143,
        page_end: 143,
        title: '致陈云等电',
        dates: [{ year: 1949, month: 8, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 144,
        page_end: 150,
        title: '别了，司徒雷登',
        dates: [{ year: 1949, month: 8, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 151,
        page_end: 151,
        title: '致阿哈买提江电',
        dates: [{ year: 1949, month: 8, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 152,
        page_end: 152,
        title: '给江庸的信',
        dates: [{ year: 1949, month: 8, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 154,
        page_end: 154,
        title: '中央关于三万人口以上城市召开各界代表会议的规定',
        dates: [{ year: 1949, month: 8, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 155,
        page_end: 155,
        title: '复刘伯承、邓小平等电',
        dates: [{ year: 1949, month: 8, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 156,
        page_end: 156,
        title: '致东北局电',
        dates: [{ year: 1949, month: 8, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 157,
        page_end: 157,
        title: '复彭德怀等电',
        dates: [{ year: 1949, month: 8, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 158,
        page_end: 158,
        title: '关于解决绥远问题的指示',
        dates: [{ year: 1949, month: 8, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 160,
        page_end: 160,
        title: '贺美国共产党三十周年电',
        dates: [{ year: 1949, month: 8, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 161,
        page_end: 162,
        title: '须集中三个兵团全力于攻兰战役',
        dates: [{ year: 1949, month: 8, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 164,
        page_end: 165,
        title: '给黄炎培的两封信',
        dates: [
          { year: 1949, month: 8, day: 24 },
          { year: 1949, month: 8, day: 26 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 166,
        page_end: 166,
        title: '给胡乔木的信',
        dates: [{ year: 1949, month: 8, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 167,
        page_end: 167,
        title: '复东北局电',
        dates: [{ year: 1949, month: 8, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 168,
        page_end: 168,
        title: '复王首道等电',
        dates: [{ year: 1949, month: 8, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 169,
        page_end: 169,
        title: '不论新区、老区均须召开县的各界代表会议',
        dates: [{ year: 1949, month: 8, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 171,
        page_end: 172,
        title: '对攻打兰州的几点意见',
        dates: [{ year: 1949, month: 8, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 173,
        page_end: 174,
        title: '三万以上人口的城市和各县均应召开各界人民代表会议',
        dates: [{ year: 1949, month: 8, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 175,
        page_end: 175,
        title: '关于转发北平工作情况报告给彭真的信',
        dates: [{ year: 1949, month: 8, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 177,
        page_end: 177,
        title: '中共中央关于转发北平工作情况报告致东北局等电',
        dates: [{ year: 1949, month: 8, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 179,
        page_end: 179,
        title: '复彭德怀电',
        dates: [{ year: 1949, month: 8, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 180,
        page_end: 180,
        title: '致傅作义电',
        dates: [{ year: 1949, month: 8, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 181,
        page_end: 181,
        title: '在新政协筹备会第四次常务委员会会议上的讲话',
        dates: [{ year: 1949, month: 8, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 182,
        page_end: 186,
        title: '为什么要讨论白皮书？',
        dates: [{ year: 1949, month: 8, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 189,
        page_end: 189,
        title: '给吴玉章的信',
        dates: [{ year: 1949, month: 8, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 190,
        page_end: 190,
        title: '致华中局电',
        dates: [{ year: 1949, month: 8, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 191,
        page_end: 191,
        title: '致各中央局、分局电',
        dates: [{ year: 1949, month: 8, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 192,
        page_end: 195,
        title: '“友谊”，还是侵略？',
        dates: [{ year: 1949, month: 8, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 196,
        page_end: 196,
        title: '先占张掖武威再占青海宁夏',
        dates: [{ year: 1949, month: 8, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 197,
        page_end: 197,
        title: '关于欢迎出席新政协会议致程潜电',
        dates: [{ year: 1949, month: 8, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 199,
        page_end: 199,
        title: '为《人民日报》题写报头',
        dates: [{ year: 1949, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 200,
        page_end: 201,
        title: '迫使白崇禧退入广西以利我军歼灭之',
        dates: [{ year: 1949, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 202,
        page_end: 202,
        title: '为冯玉祥将军逝世一周年纪念题词',
        dates: [{ year: 1949, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 203,
        page_end: 203,
        title: '致彭德怀、张宗逊电',
        dates: [{ year: 1949, month: 9, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 204,
        page_end: 205,
        title: '必须维持上海，统筹全局',
        dates: [{ year: 1949, month: 9, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 206,
        page_end: 206,
        title: '复彭德怀电',
        dates: [{ year: 1949, month: 9, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 207,
        page_end: 209,
        title: '在《中国人民政治协商会议共同纲领》起草过程中的批语',
        dates: [{ year: 1949, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 210,
        page_end: 211,
        title: '关于各地召开各界代表会议的指示',
        dates: [{ year: 1949, month: 9, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 212,
        page_end: 212,
        title: '给周恩来、聂荣臻的信',
        dates: [{ year: 1949, month: 9, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 213,
        page_end: 213,
        title: '致陈明仁电',
        dates: [{ year: 1949, month: 9, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 214,
        page_end: 214,
        title: '在审校《共同纲领》草案时改写的三段话',
        dates: [{ year: 1949, month: 9, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 215,
        page_end: 216,
        title: '开好县的各界代表会议',
        dates: [{ year: 1949, month: 9, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 217,
        page_end: 218,
        title: '对赣州会议及进军华南的指示',
        dates: [{ year: 1949, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 219,
        page_end: 219,
        title: '叶剑英将军奉命赴两广工作聂荣臻将军继任北平市长',
        dates: [{ year: 1949, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 220,
        page_end: 221,
        title: '中共中央致电祝贺各线我军连续奏捷',
        dates: [{ year: 1949, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 223,
        page_end: 224,
        title: '歼灭白崇禧部的部署',
        dates: [{ year: 1949, month: 9, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 225,
        page_end: 225,
        title: '复邓力群等电',
        dates: [{ year: 1949, month: 9, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 226,
        page_end: 226,
        title: '复邓力群电',
        dates: [{ year: 1949, month: 9, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 227,
        page_end: 227,
        title: '和张治中的谈话',
        dates: [{ year: 1949, month: 9, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 228,
        page_end: 228,
        title: '复彭德怀电',
        dates: [{ year: 1949, month: 9, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 229,
        page_end: 229,
        title: '祝波立特连任英共总书记二十周年的贺电',
        dates: [{ year: 1949, month: 9, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 230,
        page_end: 230,
        title: '为《中国儿童》创刊号题词',
        dates: [{ year: 1949, month: 9, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 232,
        page_end: 232,
        title: '给向振熙的信',
        dates: [{ year: 1949, month: 9, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 233,
        page_end: 233,
        title: '对西南各敌均取先包围再回打方针',
        dates: [{ year: 1949, month: 9, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 234,
        page_end: 234,
        title: '致华中局、华南分局、西北局及邓小平电',
        dates: [{ year: 1949, month: 9, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 235,
        page_end: 235,
        title: '复饶漱石电',
        dates: [{ year: 1949, month: 9, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 236,
        page_end: 236,
        title: '复叶剑英、陈赓电',
        dates: [{ year: 1949, month: 9, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 237,
        page_end: 237,
        title: '致王首道电',
        dates: [{ year: 1949, month: 9, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 238,
        page_end: 238,
        title: '复谭戒甫电',
        dates: [{ year: 1949, month: 9, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 239,
        page_end: 239,
        title: '给周北峰的信',
        dates: [{ year: 1949, month: 9, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 240,
        page_end: 240,
        title: '祝的里雅斯特自由区共产党召开二次大会的贺电',
        dates: [{ year: 1949, month: 9, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 241,
        page_end: 241,
        title: '祝加香八十寿辰的贺电',
        dates: [{ year: 1949, month: 9, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 242,
        page_end: 246,
        title: '迅速召开各界人民代表会议',
        dates: [{ year: 1949, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 247,
        page_end: 254,
        title: '唯心历史观的破产',
        dates: [{ year: 1949, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 264,
        page_end: 264,
        title: '复邓力群等电',
        dates: [{ year: 1949, month: 9, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 265,
        page_end: 265,
        title: '致彭德怀、张宗逊电',
        dates: [{ year: 1949, month: 9, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 266,
        page_end: 266,
        title: '复傅作义电',
        dates: [{ year: 1949, month: 9, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 267,
        page_end: 267,
        title: '复邓力群等电',
        dates: [{ year: 1949, month: 9, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 268,
        page_end: 268,
        title: '用打拉两种办法迅速解决宁夏问题',
        dates: [{ year: 1949, month: 9, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 269,
        page_end: 269,
        title: '毛主席、朱总司令回答董其武等起义通电',
        dates: [{ year: 1949, month: 9, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 271,
        page_end: 272,
        title: '聂荣臻将军、薄一波政委电贺绥远和平解放',
        dates: [{ year: 1949, month: 9, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 274,
        page_end: 275,
        title: '中共中央关于留用旧人员问题给各中央局的指示',
        dates: [{ year: 1949, month: 9, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 276,
        page_end: 279,
        title: '中国人民站起来了',
        dates: [{ year: 1949, month: 9, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 295,
        page_end: 296,
        title: '给张治中的信',
        dates: [{ year: 1949, month: 9, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 298,
        page_end: 298,
        title: '给沈雁冰的信',
        dates: [{ year: 1949, month: 9, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 299,
        page_end: 299,
        title: '为《人民文学》创刊号题词',
        dates: [{ year: 1949, month: 9, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 301,
        page_end: 301,
        title: '复彭德怀电',
        dates: [{ year: 1949, month: 9, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 302,
        page_end: 302,
        title: '复鲍尔汉电',
        dates: [{ year: 1949, month: 9, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 303,
        page_end: 303,
        title: '毛泽东在讨论国旗国徽国歌国都和纪年问题时的发言',
        dates: [{ year: 1949, month: 9, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 304,
        page_end: 305,
        title: '解决新疆问题的关键是我党和维族紧密合作',
        dates: [{ year: 1949, month: 9, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 306,
        page_end: 306,
        title: '关于组织部分政协代表发言给周恩来的信',
        dates: [{ year: 1949, month: 9, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 307,
        page_end: 308,
        title: '中共中央关于庆祝新政协召开和人民政府成立的指示',
        dates: [{ year: 1949, month: 9, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 311,
        page_end: 311,
        title: '毛主席和朱总司令复电陶峙岳鲍尔汉',
        dates: [{ year: 1949, month: 9, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 313,
        page_end: 313,
        title: '叶剑英将军奉命南下两广工作，聂荣臻将军继任北平市长',
        dates: [{ year: 1949, month: 9, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 315,
        page_end: 315,
        title: '为《新华月报》创刊号题词',
        dates: [{ year: 1949, month: 9, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 317,
        page_end: 317,
        title: '为《新华月报》题写报头',
        dates: [{ year: 1949, month: 9, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 318,
        page_end: 318,
        title: '为《新建设》杂志创刊题词',
        dates: [{ year: 1949, month: 9, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 320,
        page_end: 322,
        title: '中国人民大团结万岁',
        dates: [{ year: 1949, month: 9, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 327,
        page_end: 327,
        title: '人民英雄永垂不朽',
        dates: [{ year: 1949, month: 9, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 330,
        page_end: 330,
        title: '为《新华日报》第一次题写报头',
        dates: [{ year: 1949, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 331,
        page_end: 331,
        title: '为《黑龙江日报》题写报头',
        dates: [{ year: 1949, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 333,
        page_end: 333,
        title: '为《新建设》题名',
        dates: [{ year: 1949, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 334,
        page_end: 335,
        title: '中华人民共和国中央人民政府公告',
        dates: [{ year: 1949, month: 10, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 368,
        page_end: 368,
        title: '给侨胞的题词',
        dates: [{ year: 1949, month: 10, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 370,
        page_end: 370,
        title: '关于中苏建交的新闻稿',
        dates: [{ year: 1949, month: 10, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 371,
        page_end: 373,
        title: '对程潜陈明仁所提要求和建议的处置意见',
        dates: [{ year: 1949, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 374,
        page_end: 374,
        title: '关于安排程潜、陈明仁、李明灏看望王耀武、杜聿明、黄维等的电报',
        dates: [{ year: 1949, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 375,
        page_end: 375,
        title: '在马叙伦请假信上的批语',
        dates: [{ year: 1949, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 376,
        page_end: 376,
        title: '给黄炎培的信',
        dates: [{ year: 1949, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 377,
        page_end: 378,
        title: '答谢福斯特、但尼斯祝贺中华人民共和国成立的电报',
        dates: [{ year: 1949, month: 10, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 379,
        page_end: 379,
        title: '同意第四野战军五个军靠拢作战的部署',
        dates: [{ year: 1949, month: 10, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 380,
        page_end: 380,
        title: '中央关于吸收党外人士参加广州军管会等机构的电报',
        dates: [{ year: 1949, month: 10, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 381,
        page_end: 383,
        title: '转发浙江省委工作报告的批语',
        dates: [{ year: 1949, month: 10, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 384,
        page_end: 384,
        title: '关于杨开智等工作安排问题的电报',
        dates: [{ year: 1949, month: 10, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 385,
        page_end: 385,
        title: '给谭政、陶铸的信',
        dates: [{ year: 1949, month: 10, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 386,
        page_end: 386,
        title: '同意聚歼白崇禧主力的作战计划',
        dates: [{ year: 1949, month: 10, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 387,
        page_end: 387,
        title: '毛泽东、朱德致“长治”号舰全体起义人员电',
        dates: [{ year: 1949, month: 10, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 388,
        page_end: 389,
        title: '对新疆赵锡光、鲍尔汉、马良骏等祝贺中央人民政府成立的复电',
        dates: [
          { year: 1949, month: 10, day: 10 },
          { year: 1949, month: 10, day: 21 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 390,
        page_end: 390,
        title: '十八兵团由贺龙统率入川',
        dates: [{ year: 1949, month: 10, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 391,
        page_end: 392,
        title: '十五兵团暂不进攻广州',
        dates: [{ year: 1949, month: 10, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 393,
        page_end: 393,
        title: '关于同意约鲍尔汉至酒泉商谈的电报',
        dates: [{ year: 1949, month: 10, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 394,
        page_end: 394,
        title: '为《山西日报》题写报头',
        dates: [{ year: 1949, month: 10, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 395,
        page_end: 396,
        title: '慎重考虑围歼白崇禧部计划力求做到确有把握',
        dates: [{ year: 1949, month: 10, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 397,
        page_end: 398,
        title: '相机占领广州和围歼白崇禧部',
        dates: [{ year: 1949, month: 10, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 401,
        page_end: 401,
        title: '关于草拟华东军政委员会名单给陈毅的信',
        dates: [{ year: 1949, month: 10, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 402,
        page_end: 403,
        title: '民族军应改名为人民解放军',
        dates: [{ year: 1949, month: 10, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 404,
        page_end: 406,
        title: '转发松江县召开各界人民代表会议经验的电报',
        dates: [{ year: 1949, month: 10, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 407,
        page_end: 408,
        title: '第一野战军第二野战军在西北西南地区的作战部署',
        dates: [{ year: 1949, month: 10, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 410,
        page_end: 410,
        title: '务不使粤敌逃入广西',
        dates: [{ year: 1949, month: 10, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 411,
        page_end: 411,
        title: '在表扬歼灭白崇禧主力的部队的电报上的批语',
        dates: [{ year: 1949, month: 10, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 412,
        page_end: 412,
        title: '给冯友兰的信',
        dates: [{ year: 1949, month: 10, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 414,
        page_end: 414,
        title: '给上海市纸业革新促进会的题词',
        dates: [{ year: 1949, month: 10, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 415,
        page_end: 415,
        title: '为《南方日报》题写报头',
        dates: [{ year: 1949, month: 10, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 417,
        page_end: 417,
        title: '为了解罗章龙的情况致湖南省委电',
        dates: [{ year: 1949, month: 10, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 418,
        page_end: 418,
        title: '中央关于发表广州军管会和市政府就职布告的电报',
        dates: [{ year: 1949, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 419,
        page_end: 419,
        title: '中央关于新疆三区代表和彭德怀会谈问题的电报',
        dates: [{ year: 1949, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 420,
        page_end: 420,
        title: '同意分步骤在新疆进行军事工作',
        dates: [{ year: 1949, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 421,
        page_end: 421,
        title: '为《中苏友好》杂志创刊号题词',
        dates: [{ year: 1949, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 423,
        page_end: 423,
        title: '给张仲实的信',
        dates: [{ year: 1949, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 424,
        page_end: 424,
        title: '致卫立煌电',
        dates: [{ year: 1949, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 425,
        page_end: 425,
        title: '给周世钊的信',
        dates: [{ year: 1949, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 427,
        page_end: 427,
        title: '接受苏联驻华大使罗申呈递国书时的答词',
        dates: [{ year: 1949, month: 10, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 430,
        page_end: 430,
        title: '祝贺德意志民主共和国成立的电报',
        dates: [{ year: 1949, month: 10, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 431,
        page_end: 431,
        title: '四兵团应乘胜追击占领高要德庆等县',
        dates: [{ year: 1949, month: 10, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 432,
        page_end: 433,
        title: '解放西南地区的作战方针',
        dates: [{ year: 1949, month: 10, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 434,
        page_end: 434,
        title: '关于高凌云师与陕北伊盟部队合编的电报',
        dates: [{ year: 1949, month: 10, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 435,
        page_end: 435,
        title: '中央关于物色民主分子参加广西工作的电报',
        dates: [{ year: 1949, month: 10, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 436,
        page_end: 436,
        title: '给斯大林的信',
        dates: [{ year: 1949, month: 10, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 437,
        page_end: 441,
        title: '在人民革命军事委员会第一次会议上的讲话',
        dates: [{ year: 1949, month: 10, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 444,
        page_end: 444,
        title: '对艾斯海提·伊斯哈科夫祝贺新疆和全国解放的复电',
        dates: [{ year: 1949, month: 10, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 445,
        page_end: 445,
        title: '关于写解放军进入新疆的短评给胡乔木的信',
        dates: [{ year: 1949, month: 10, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 446,
        page_end: 447,
        title: '为阿哈买提江等五人不幸遇难写的碑文和电',
        dates: [
          { year: 1949, month: 10 },
          { year: 1949, month: 11 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 448,
        page_end: 448,
        title: '在赛福鼎入党申请书上的批语',
        dates: [{ year: 1949, month: 10, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 450,
        page_end: 451,
        title: '中央关于新疆问题致彭德怀电',
        dates: [{ year: 1949, month: 10, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 452,
        page_end: 452,
        title: '祝贺“海辽”号轮起义致方枕流等电',
        dates: [{ year: 1949, month: 10, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 453,
        page_end: 453,
        title: '在一则新闻稿上的批语',
        dates: [{ year: 1949, month: 10, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 454,
        page_end: 461,
        title: '和绥远负责人的谈话',
        dates: [{ year: 1949, month: 10, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 462,
        page_end: 462,
        title: '中央关于召开西北局会议的电报',
        dates: [{ year: 1949, month: 10, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 463,
        page_end: 463,
        title: '军委关于同意解除十兵团出击潮汕任务的电报',
        dates: [{ year: 1949, month: 10, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 464,
        page_end: 464,
        title: '中央关于湖南临时省政府改组问题的电报',
        dates: [{ year: 1949, month: 10, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 465,
        page_end: 466,
        title: '转发人民解放军入疆综合报告',
        dates: [{ year: 1949, month: 10, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 467,
        page_end: 467,
        title: '永远保持艰苦奋斗的作风',
        dates: [{ year: 1949, month: 10, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 469,
        page_end: 469,
        title: '复霍查同志电',
        dates: [{ year: 1949, month: 10, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 470,
        page_end: 470,
        title: '复拉比·蒲哈利电',
        dates: [{ year: 1949, month: 10, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 471,
        page_end: 471,
        title: '关于撤销迪化伪监委行署的电报',
        dates: [{ year: 1949, month: 10, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 472,
        page_end: 473,
        title: '关于请苏联帮助防治鼠疫致斯大林电',
        dates: [
          { year: 1949, month: 10, day: 28 },
          { year: 1949, month: 10, day: 30 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 474,
        page_end: 475,
        title: '严重注意攻击金门岛失利的教训',
        dates: [{ year: 1949, month: 10, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 476,
        page_end: 476,
        title: '关于董其武部改编问题给薄一波的信',
        dates: [{ year: 1949, month: 10, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 477,
        page_end: 478,
        title: '转发薄一波关于华北各城市各界代表会议报告的批语',
        dates: [{ year: 1949, month: 10, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 479,
        page_end: 481,
        title: '关于兵力部署的几点意见',
        dates: [{ year: 1949, month: 10, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 482,
        page_end: 483,
        title: '关于华中成立军政委员会问题致林彪等电',
        dates: [{ year: 1949, month: 10, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 484,
        page_end: 484,
        title: '为《新民主主义在中国的胜利》一书写的序言',
        dates: [{ year: 1949, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 485,
        page_end: 485,
        title: '为《河南日报》题写报头',
        dates: [{ year: 1949, month: 11, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 487,
        page_end: 487,
        title: '对空军关于航校校址问题报告的批语',
        dates: [{ year: 1949, month: 11, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 488,
        page_end: 489,
        title: '中央对浙江省委关于农村政策问题报告的批语和复电',
        dates: [{ year: 1949, month: 11, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 490,
        page_end: 490,
        title: '中共中央批转西北局关于长安县各界代表会议经验的指示',
        dates: [{ year: 1949, month: 11, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 491,
        page_end: 492,
        title: '中央关于对旧人员处理问题的电报',
        dates: [{ year: 1949, month: 11, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 493,
        page_end: 493,
        title: '军委关于同意定海作战方案致粟裕等电',
        dates: [{ year: 1949, month: 11, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 494,
        page_end: 494,
        title: '关于改造和补充陈明仁部致林彪电',
        dates: [{ year: 1949, month: 11, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 495,
        page_end: 495,
        title: '关于收集和研究上海税收办法的批语',
        dates: [{ year: 1949, month: 11, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 496,
        page_end: 496,
        title: '为国立戏剧学院题名',
        dates: [{ year: 1949, month: 11, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 498,
        page_end: 498,
        title: '中央关于上报新疆等省政府名单致彭德怀电',
        dates: [{ year: 1949, month: 11, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 499,
        page_end: 499,
        title: '中央关于建立华东军政委员会的电报',
        dates: [{ year: 1949, month: 11, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 500,
        page_end: 501,
        title: '对聂荣臻关于卫生部问题报告的批语',
        dates: [{ year: 1949, month: 11, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 502,
        page_end: 502,
        title: '对关于空军司令部名称和关防尺寸刊发问题的批语',
        dates: [{ year: 1949, month: 11, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 503,
        page_end: 504,
        title: '中央关于成立川西北军政委员会的电报',
        dates: [{ year: 1949, month: 11, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 505,
        page_end: 505,
        title: '邓华兵团可以分出一个师协同梁广纵队肃清南路敌军',
        dates: [{ year: 1949, month: 11, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 506,
        page_end: 506,
        title: '中央关于毛泽东去莫斯科时间致王稼祥电',
        dates: [{ year: 1949, month: 11, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 507,
        page_end: 507,
        title: '中央关于征询政协党外代表对华东政权机关意见的电报',
        dates: [{ year: 1949, month: 11, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 508,
        page_end: 508,
        title: '向董其武部调派的政工干部必须加以训练',
        dates: [{ year: 1949, month: 11, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 509,
        page_end: 509,
        title: '关于安排西蒙诺夫到广西前线参观的电报',
        dates: [{ year: 1949, month: 11, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 510,
        page_end: 510,
        title: '致斯大林电',
        dates: [{ year: 1949, month: 11, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 511,
        page_end: 511,
        title: '祝贺中国、中央两航空公司全体员工起义的电报',
        dates: [{ year: 1949, month: 11, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 512,
        page_end: 512,
        title: '须重视对定海作战的各项问题',
        dates: [{ year: 1949, month: 11, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 513,
        page_end: 514,
        title: '大批培养少数民族干部',
        dates: [{ year: 1949, month: 11, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 515,
        page_end: 515,
        title: '给毛远翔的信',
        dates: [{ year: 1949, month: 11, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 516,
        page_end: 516,
        title: '对创办三所军医大学报告的批语',
        dates: [{ year: 1949, month: 11, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 517,
        page_end: 517,
        title: '给毛煦生的信',
        dates: [{ year: 1949, month: 11, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 519,
        page_end: 519,
        title: '给毛泽青的信',
        dates: [{ year: 1949, month: 11, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 520,
        page_end: 520,
        title: '欢迎仇鳌来京的电报',
        dates: [{ year: 1949, month: 11, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 521,
        page_end: 521,
        title: '给李介侯的信',
        dates: [{ year: 1949, month: 11, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 522,
        page_end: 522,
        title: '给张四维的信',
        dates: [{ year: 1949, month: 11, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 523,
        page_end: 524,
        title: '中央转发贵州新区工作策略问题电报的批语',
        dates: [{ year: 1949, month: 11, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 525,
        page_end: 525,
        title: '致宣布脱离国民党当局的前资源委员会驻港员工电',
        dates: [{ year: 1949, month: 11, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 526,
        page_end: 526,
        title: '答谢兰那地夫祝贺中华人民共和国成立的电报',
        dates: [{ year: 1949, month: 11, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 527,
        page_end: 527,
        title: '复电感谢伊朗共产党',
        dates: [{ year: 1949, month: 11, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 528,
        page_end: 528,
        title: '关于同意工作方针致彭德怀电',
        dates: [{ year: 1949, month: 11, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 529,
        page_end: 529,
        title: '为《南侨日报》创刊三周年题词',
        dates: [{ year: 1949, month: 11, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 531,
        page_end: 531,
        title: '关于任弼时治病问题致斯大林电',
        dates: [{ year: 1949, month: 11, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 532,
        page_end: 532,
        title: '军委关于张治中去兰州致彭德怀电',
        dates: [{ year: 1949, month: 11, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 533,
        page_end: 534,
        title: '中央关于要华中局对处理旧人员提出意见的电报',
        dates: [{ year: 1949, month: 11, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 535,
        page_end: 536,
        title: '关于解决西藏问题的意见',
        dates: [{ year: 1949, month: 11, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 537,
        page_end: 537,
        title: '致班禅额尔德尼电',
        dates: [{ year: 1949, month: 11, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
    ],
    page_limits: [],
    ext: 'pdf',
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives0/maoquanji27.pdf',
};
