export default {
  entity: {
    id: 'maoquanji14',
    name: '毛泽东全集第14卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives8/main/maoquanji14.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '对于过去参政会工作和目前时局的意见',
        authors: ['毛泽东'],
        page_start: 29,
        page_end: 37,
        dates: [{ year: 1939, month: 9, day: 8 }],
        is_range_date: false,
      },
      {
        title: '同意抗大第一分校迁往山东',
        authors: ['毛泽东'],
        page_start: 38,
        page_end: 38,
        dates: [{ year: 1939, month: 9, day: 9 }],
        is_range_date: false,
      },
      {
        title: '在欢迎全国感劳总会北路感劳团晚会上的讲话',
        authors: ['毛泽东'],
        page_start: 39,
        page_end: 41,
        dates: [{ year: 1939, month: 9, day: 10 }],
        is_range_date: false,
      },
      {
        title: '共产党参政员捐款援助香港反汗工友',
        authors: ['毛泽东'],
        page_start: 42,
        page_end: 42,
        dates: [{ year: 1939, month: 9, day: 12 }],
        is_range_date: false,
      },
      {
        title: '论第二次帝国主义战争',
        authors: ['毛泽东'],
        page_start: 43,
        page_end: 58,
        dates: [{ year: 1939, month: 9, day: 14 }],
        is_range_date: false,
      },
      {
        title: '和中央社、扫荡报、新民报”记者的谈话',
        authors: ['毛泽东'],
        page_start: 59,
        page_end: 63,
        dates: [{ year: 1939, month: 9, day: 16 }],
        is_range_date: false,
      },
      {
        title: '结成坚固的统一战线，打败日本帝国主义',
        authors: ['毛泽东'],
        page_start: 64,
        page_end: 69,
        dates: [{ year: 1939, month: 9, day: 18 }],
        is_range_date: false,
      },
      {
        title: '和美国记者斯诺的谈话',
        authors: ['毛泽东'],
        page_start: 70,
        page_end: 88,
        dates: [{ year: 1939, month: 9, day: 24 }],
        is_range_date: false,
      },
      {
        title: '在陕甘宁边区机关、学校、部队秋收动员大会上的讲话',
        authors: ['毛泽东'],
        page_start: 89,
        page_end: 89,
        dates: [{ year: 1939, month: 9, day: 25 }],
        is_range_date: false,
      },
      {
        title: '苏联利益和人类利益的一致',
        authors: ['毛泽东'],
        page_start: 90,
        page_end: 98,
        dates: [{ year: 1939, month: 9, day: 28 }],
        is_range_date: false,
      },
      {
        title: '复陕西省政府主席蒋鼎文电',
        authors: ['毛泽东'],
        page_start: 99,
        page_end: 99,
        dates: [{ year: 1939, month: 9, day: 29 }],
        is_range_date: false,
      },
      {
        title: '在欢迎中外朋友晚会上的致辞',
        authors: ['毛泽东'],
        page_start: 100,
        page_end: 101,
        dates: [{ year: 1939, month: 9 }],
        is_range_date: false,
      },
      {
        title: '为杨十三题写抚联',
        authors: ['毛泽东'],
        page_start: 102,
        page_end: 102,
        dates: [{ year: 1939, month: 9 }],
        is_range_date: false,
      },
      {
        title: '在抗大四期毕业典礼上的讲话',
        authors: ['毛泽东'],
        page_start: 103,
        page_end: 103,
        dates: [{ year: 1939, month: 9 }],
        is_range_date: false,
      },
      {
        title: '为韩忠良题词',
        authors: ['毛泽东'],
        page_start: 104,
        page_end: 105,
        dates: [{ year: 1939, month: 9 }],
        is_range_date: false,
      },
      {
        title: '为八路军三五九旅题词',
        authors: ['毛泽东'],
        page_start: 106,
        page_end: 106,
        dates: [{ year: 1939, month: 9 }],
        is_range_date: false,
      },
      {
        title: '研究浴陷区',
        authors: ['毛泽东'],
        page_start: 107,
        page_end: 110,
        dates: [{ year: 1939, month: 10, day: 1 }],
        is_range_date: false,
      },
      {
        title: '《共产党人》发刊词',
        authors: ['毛泽东'],
        page_start: 111,
        page_end: 123,
        dates: [{ year: 1939, month: 10, day: 4 }],
        is_range_date: false,
      },
      {
        title: '为安吴青训班二周年纪念的题词',
        authors: ['毛泽东'],
        page_start: 124,
        page_end: 124,
        dates: [{ year: 1939, month: 10, day: 5 }],
        is_range_date: false,
      },
      {
        title: '给吕超"的信',
        authors: ['毛泽东'],
        page_start: 125,
        page_end: 126,
        dates: [{ year: 1939, month: 10, day: 7 }],
        is_range_date: false,
      },
      {
        title: '自前形势和党的任务',
        authors: ['毛泽东'],
        page_start: 127,
        page_end: 129,
        dates: [{ year: 1939, month: 10, day: 10 }],
        is_range_date: false,
      },
      {
        title: '复朱德、彭德怀等电',
        authors: ['毛泽东'],
        page_start: 130,
        page_end: 130,
        dates: [{ year: 1939, month: 10, day: 17 }],
        is_range_date: false,
      },
      {
        title: '为《共产党人》杂志题名',
        authors: ['毛泽东'],
        page_start: 131,
        page_end: 134,
        dates: [{ year: 1939, month: 10, day: 20 }],
        is_range_date: false,
      },
      {
        title: '群众工作是克服投降危险的决定性条件',
        authors: ['毛泽东'],
        page_start: 135,
        page_end: 135,
        dates: [{ year: 1939, month: 11, day: 1 }],
        is_range_date: false,
      },
      {
        title: '复陈毅电',
        authors: ['毛泽东'],
        page_start: 136,
        page_end: 136,
        dates: [{ year: 1939, month: 11, day: 1 }],
        is_range_date: false,
      },
      {
        title: '给林中鹤"的信',
        authors: ['毛泽东'],
        page_start: 137,
        page_end: 137,
        dates: [{ year: 1939, month: 11, day: 5 }],
        is_range_date: false,
      },
      {
        title: '给周扬的信',
        authors: ['毛泽东'],
        page_start: 138,
        page_end: 139,
        dates: [{ year: 1939, month: 11, day: 7 }],
        is_range_date: false,
      },
      {
        title: '在中共陕甘宁边区第二次代表大会上的讲话',
        authors: ['毛泽东'],
        page_start: 140,
        page_end: 141,
        dates: [{ year: 1939, month: 11, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致八路军总部、新四军军部等电',
        authors: ['毛泽东'],
        page_start: 142,
        page_end: 143,
        dates: [{ year: 1939, month: 11, day: 24 }],
        is_range_date: false,
      },
      {
        title: '为刘咖“题词',
        authors: ['毛泽东'],
        page_start: 144,
        page_end: 145,
        dates: [{ year: 1939, month: 11 }],
        is_range_date: false,
      },
      {
        title: '给马相伯家属的暗电',
        authors: ['毛泽东'],
        page_start: 146,
        page_end: 146,
        dates: [{ year: 1939, month: 11 }],
        is_range_date: false,
      },
      {
        title: '大量吸收知识分子',
        authors: ['毛泽东'],
        page_start: 147,
        page_end: 149,
        dates: [{ year: 1939, month: 12, day: 1 }],
        is_range_date: false,
      },
      {
        title: '为白求恩题写换联·',
        authors: ['毛泽东'],
        page_start: 150,
        page_end: 150,
        dates: [{ year: 1939, month: 12, day: 1 }],
        is_range_date: false,
      },
      {
        title: '为白求恩题写换词叫',
        authors: ['毛泽东'],
        page_start: 151,
        page_end: 151,
        dates: [{ year: 1939, month: 12, day: 1 }],
        is_range_date: false,
      },
      {
        title: '致郭洪涛等电',
        authors: ['毛泽东'],
        page_start: 152,
        page_end: 152,
        dates: [{ year: 1939, month: 12, day: 4 }],
        is_range_date: false,
      },
      {
        title: '为《挑晓报》题词则',
        authors: ['毛泽东'],
        page_start: 153,
        page_end: 154,
        dates: [{ year: 1939, month: 12, day: 5 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 155,
        page_end: 155,
        dates: [{ year: 1939, month: 12, day: 5 }],
        is_range_date: false,
      },
      {
        title: '普西南新旧军冲突和我们的方针0',
        authors: ['毛泽东'],
        page_start: 156,
        page_end: 157,
        dates: [{ year: 1939, month: 12, day: 6 }],
        is_range_date: false,
      },
      {
        title: '对山东军事工作的意见',
        authors: ['毛泽东'],
        page_start: 158,
        page_end: 159,
        dates: [{ year: 1939, month: 12, day: 6 }],
        is_range_date: false,
      },
      {
        title: '致贺龙、关向应、李井泉等电',
        authors: ['毛泽东'],
        page_start: 160,
        page_end: 160,
        dates: [{ year: 1939, month: 12, day: 9 }],
        is_range_date: false,
      },
      {
        title: '致八路军总部等电',
        authors: ['毛泽东'],
        page_start: 161,
        page_end: 161,
        dates: [{ year: 1939, month: 12, day: 9 }],
        is_range_date: false,
      },
      {
        title: '为延安世界语协会展览会题词',
        authors: ['毛泽东'],
        page_start: 162,
        page_end: 163,
        dates: [{ year: 1939, month: 12, day: 9 }],
        is_range_date: false,
      },
      {
        title: '一二·九运动的伟大意义',
        authors: ['毛泽东'],
        page_start: 164,
        page_end: 171,
        dates: [{ year: 1939, month: 12, day: 9 }],
        is_range_date: false,
      },
      {
        title: '在延安青年纪念一二·九运动四周年大会上的讲话',
        authors: ['毛泽东'],
        page_start: 172,
        page_end: 173,
        dates: [{ year: 1939, month: 12, day: 9 }],
        is_range_date: false,
      },
      {
        title: '关于普西南事件与我们方针的补充指示',
        authors: ['毛泽东'],
        page_start: 174,
        page_end: 176,
        dates: [{ year: 1939, month: 12, day: 9 }],
        is_range_date: false,
      },
      {
        title: '加强普西北作战的指挥',
        authors: ['毛泽东'],
        page_start: 177,
        page_end: 177,
        dates: [{ year: 1939, month: 12, day: 9 }],
        is_range_date: false,
      },
      {
        title: '复中共普西北区委书记赵林等电',
        authors: ['毛泽东'],
        page_start: 178,
        page_end: 178,
        dates: [{ year: 1939, month: 12, day: 12 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 179,
        page_end: 179,
        dates: [{ year: 1939, month: 12, day: 13 }],
        is_range_date: false,
      },
      {
        title: '中国革命和中国共产党',
        authors: ['毛泽东'],
        page_start: 180,
        page_end: 216,
        dates: [{ year: 1939, month: 12, day: 15 }],
        is_range_date: false,
      },
      {
        title: '斯大林是中国人民的朋友',
        authors: ['毛泽东'],
        page_start: 217,
        page_end: 218,
        dates: [{ year: 1939, month: 12, day: 20 }],
        is_range_date: false,
      },
      {
        title: '在延安各界庆祝斯大林六十寿辰大会上的讲话',
        authors: ['毛泽东'],
        page_start: 219,
        page_end: 221,
        dates: [{ year: 1939, month: 12, day: 21 }],
        is_range_date: false,
      },
      {
        title: '纪念白求恩',
        authors: ['毛泽东'],
        page_start: 222,
        page_end: 227,
        dates: [{ year: 1939, month: 12, day: 21 }],
        is_range_date: false,
      },
      {
        title: '在欢迎民族英雄马占山将军晚会上的讲话',
        authors: ['毛泽东'],
        page_start: 228,
        page_end: 228,
        dates: [{ year: 1939, month: 12, day: 22 }],
        is_range_date: false,
      },
      {
        title: '致朱德、彭德怀等电',
        authors: ['毛泽东'],
        page_start: 229,
        page_end: 229,
        dates: [{ year: 1939, month: 12, day: 23 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀等电',
        authors: ['毛泽东'],
        page_start: 230,
        page_end: 230,
        dates: [{ year: 1939, month: 12, day: 23 }],
        is_range_date: false,
      },
      {
        title: '致朱德、彭德怀电',
        authors: ['毛泽东'],
        page_start: 231,
        page_end: 231,
        dates: [{ year: 1939, month: 12, day: 23 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 232,
        page_end: 232,
        dates: [{ year: 1939, month: 12, day: 23 }],
        is_range_date: false,
      },
      {
        title: '致中共普西北区委等电',
        authors: ['毛泽东'],
        page_start: 233,
        page_end: 233,
        dates: [{ year: 1939, month: 12, day: 23 }],
        is_range_date: false,
      },
      {
        title: '致朱德、杨尚昆并彭德怀电',
        authors: ['毛泽东'],
        page_start: 234,
        page_end: 234,
        dates: [{ year: 1939, month: 12, day: 26 }],
        is_range_date: false,
      },
      {
        title: '聚床某战区司令长官部造谣',
        authors: ['毛泽东'],
        page_start: 235,
        page_end: 235,
        dates: [{ year: 1939, month: 12, day: 27 }],
        is_range_date: false,
      },
      {
        title: '做好巩固决死队的工作',
        authors: ['毛泽东'],
        page_start: 236,
        page_end: 236,
        dates: [{ year: 1939, month: 12, day: 28 }],
        is_range_date: false,
      },
      {
        title: '致朱德、彭德怀、杨尚昆、左权电',
        authors: ['毛泽东'],
        page_start: 237,
        page_end: 237,
        dates: [{ year: 1939, month: 12, day: 28 }],
        is_range_date: false,
      },
      {
        title: '致贺龙、关向应等电',
        authors: ['毛泽东'],
        page_start: 238,
        page_end: 238,
        dates: [{ year: 1939, month: 12, day: 30 }],
        is_range_date: false,
      },
      {
        title: '普西目前形势及我军事部署叫',
        authors: ['毛泽东'],
        page_start: 239,
        page_end: 240,
        dates: [{ year: 1939, month: 12, day: 31 }],
        is_range_date: false,
      },
      {
        title: '为抗大开展生产运动题词',
        authors: ['毛泽东'],
        page_start: 241,
        page_end: 242,
        dates: [{ year: 1939, month: 12 }],
        is_range_date: false,
      },
      {
        title: '为《陕甘宁边区实录》一书题名、题词叫',
        authors: ['毛泽东'],
        page_start: 243,
        page_end: 245,
        dates: [{ year: 1939, month: 12 }],
        is_range_date: false,
      },
      {
        title: '为恒念白求恩题词',
        authors: ['毛泽东'],
        page_start: 246,
        page_end: 247,
        dates: [{ year: 1939, month: 12 }],
        is_range_date: false,
      },
      {
        title: '诗歌以押韵为宜',
        authors: ['毛泽东'],
        page_start: 248,
        page_end: 248,
        dates: [{ year: 1939, month: 12 }],
        is_range_date: false,
      },
      {
        title: '《通讯》为新华社业务刊物题写刊头',
        authors: ['毛泽东'],
        page_start: 249,
        page_end: 249,
        dates: [{ year: 1939, month: 12 }],
        is_range_date: false,
      },
      {
        title: '给吴玉章"的信',
        authors: ['毛泽东'],
        page_start: 250,
        page_end: 251,
        dates: [{ year: 1939, month: 12 }],
        is_range_date: false,
      },
      {
        title: '谈抗大农庄',
        authors: ['毛泽东'],
        page_start: 252,
        page_end: 252,
        dates: [{ year: 1939 }],
        is_range_date: false,
      },
      {
        title: '题延安新市场联',
        authors: ['毛泽东'],
        page_start: 253,
        page_end: 253,
        dates: [{ year: 1939 }],
        is_range_date: false,
      },
      {
        title: '谈爬山',
        authors: ['毛泽东'],
        page_start: 254,
        page_end: 254,
        dates: [{ year: 1939 }],
        is_range_date: false,
      },
      {
        title: '为《抗日模范根据地普冀察边区》一书题名',
        authors: ['毛泽东'],
        page_start: 255,
        page_end: 256,
        dates: [{ year: 1939 }],
        is_range_date: false,
      },
      {
        title: '为《中国青年》题名',
        authors: ['毛泽东'],
        page_start: 257,
        page_end: 257,
        dates: [{ year: 1939 }],
        is_range_date: false,
      },
      {
        title: '为延安《团结》杂志题词',
        authors: ['毛泽东'],
        page_start: 258,
        page_end: 259,
        dates: [{ year: 1939 }],
        is_range_date: false,
      },
      {
        title: '读河上擎“著李达等译《马克思主义经济学基础理论》一书的批注',
        authors: ['毛泽东'],
        page_start: 260,
        page_end: 276,
        dates: [{ year: 1939 }],
        is_range_date: false,
      },
      {
        title: '为《大众日报》周年纪念题词',
        authors: ['毛泽东'],
        page_start: 277,
        page_end: 278,
        dates: [{ year: 1940, month: 1, day: 1 }],
        is_range_date: false,
      },
      {
        title: '为《通信战士》杂志题名',
        authors: ['毛泽东'],
        page_start: 279,
        page_end: 279,
        dates: [{ year: 1940, month: 1, day: 1 }],
        is_range_date: false,
      },
      {
        title: '为《通信战士》杂志题词',
        authors: ['毛泽东'],
        page_start: 280,
        page_end: 281,
        dates: [{ year: 1940, month: 1, day: 1 }],
        is_range_date: false,
      },
      {
        title: '准备应付华中急变',
        authors: ['毛泽东'],
        page_start: 282,
        page_end: 282,
        dates: [{ year: 1940, month: 1, day: 5 }],
        is_range_date: false,
      },
      {
        title: '致鼓荣臻、彭真电',
        authors: ['毛泽东'],
        page_start: 283,
        page_end: 283,
        dates: [{ year: 1940, month: 1, day: 5 }],
        is_range_date: false,
      },
      {
        title: '关于陇东问题谈判的条件给谢觉战的信',
        authors: ['毛泽东'],
        page_start: 284,
        page_end: 284,
        dates: [{ year: 1940, month: 1, day: 8 }],
        is_range_date: false,
      },
      {
        title: '关于山西新旧军的磨擦问题的讲话',
        authors: ['毛泽东'],
        page_start: 285,
        page_end: 285,
        dates: [{ year: 1940, month: 1, day: 10 }],
        is_range_date: false,
      },
      {
        title: '致王世英电',
        authors: ['毛泽东'],
        page_start: 286,
        page_end: 286,
        dates: [{ year: 1940, month: 1, day: 10 }],
        is_range_date: false,
      },
      {
        title: '目前不可能实行征兵制',
        authors: ['毛泽东'],
        page_start: 287,
        page_end: 287,
        dates: [{ year: 1940, month: 1, day: 11 }],
        is_range_date: false,
      },
      {
        title: '自前政治形势及对固锡山的方针',
        authors: ['毛泽东'],
        page_start: 288,
        page_end: 289,
        dates: [{ year: 1940, month: 1, day: 11 }],
        is_range_date: false,
      },
      {
        title: '吴玉章“寿辰祝词',
        authors: ['毛泽东'],
        page_start: 290,
        page_end: 291,
        dates: [{ year: 1940, month: 1, day: 15 }],
        is_range_date: false,
      },
      {
        title: '在陕甘宁边区第二届农工展览会开幕典礼上的讲话',
        authors: ['毛泽东'],
        page_start: 292,
        page_end: 293,
        dates: [{ year: 1940, month: 1, day: 16 }],
        is_range_date: false,
      },
      {
        title: '致王世英电',
        authors: ['毛泽东'],
        page_start: 294,
        page_end: 294,
        dates: [{ year: 1940, month: 1, day: 16 }],
        is_range_date: false,
      },
      {
        title: '致朱德、彭德怀、杨尚昆电',
        authors: ['毛泽东'],
        page_start: 295,
        page_end: 295,
        dates: [{ year: 1940, month: 1, day: 16 }],
        is_range_date: false,
      },
      {
        title: '致朱德、彭德怀等电',
        authors: ['毛泽东'],
        page_start: 296,
        page_end: 296,
        dates: [{ year: 1940, month: 1, day: 17 }],
        is_range_date: false,
      },
      {
        title: '在中共中央书记处会议上的讲话',
        authors: ['毛泽东'],
        page_start: 297,
        page_end: 297,
        dates: [{ year: 1940, month: 1, day: 18 }],
        is_range_date: false,
      },
      {
        title: '新民主主义论',
        authors: ['毛泽东'],
        page_start: 298,
        page_end: 350,
        dates: [{ year: 1940, month: 1 }],
        is_range_date: false,
      },
      {
        title: '致贺龙、关向应、滕代远等电',
        authors: ['毛泽东'],
        page_start: 351,
        page_end: 351,
        dates: [{ year: 1940, month: 1, day: 20 }],
        is_range_date: false,
      },
      {
        title: '给周扬"的信',
        authors: ['毛泽东'],
        page_start: 352,
        page_end: 352,
        dates: [{ year: 1940, month: 1, day: 21 }],
        is_range_date: false,
      },
      {
        title: '给周扬的信',
        authors: ['毛泽东'],
        page_start: 353,
        page_end: 353,
        dates: [{ year: 1940, month: 1, day: 23 }],
        is_range_date: false,
      },
      {
        title: '为国际反侵略运动大会中国分会成立两周年题词',
        authors: ['毛泽东'],
        page_start: 354,
        page_end: 355,
        dates: [{ year: 1940, month: 1, day: 23 }],
        is_range_date: false,
      },
      {
        title: '为战地文化资料展览会题词',
        authors: ['毛泽东'],
        page_start: 356,
        page_end: 357,
        dates: [{ year: 1940, month: 1, day: 24 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 358,
        page_end: 358,
        dates: [{ year: 1940, month: 1, day: 24 }],
        is_range_date: false,
      },
      {
        title: '为《八路军军政杂志创刊一周年题词',
        authors: ['毛泽东'],
        page_start: 359,
        page_end: 360,
        dates: [{ year: 1940, month: 1, day: 25 }],
        is_range_date: false,
      },
      {
        title: '关于和平解决普西事变致朱德等电',
        authors: ['毛泽东'],
        page_start: 361,
        page_end: 362,
        dates: [{ year: 1940, month: 1, day: 27 }],
        is_range_date: false,
      },
      {
        title: '集中力量发展武装，建立抗日根据地',
        authors: ['毛泽东'],
        page_start: 363,
        page_end: 364,
        dates: [{ year: 1940, month: 1, day: 28 }],
        is_range_date: false,
      },
      {
        title: '克服投降危险，力争时局好转叫',
        authors: ['毛泽东'],
        page_start: 365,
        page_end: 367,
        dates: [{ year: 1940, month: 1, day: 28 }],
        is_range_date: false,
      },
      {
        title: '皖南部队须力争江北',
        authors: ['毛泽东'],
        page_start: 368,
        page_end: 368,
        dates: [{ year: 1940, month: 1, day: 29 }],
        is_range_date: false,
      },
      {
        title: '在自卫原则下给进攻者以彻底打击',
        authors: ['毛泽东'],
        page_start: 369,
        page_end: 370,
        dates: [{ year: 1940, month: 1, day: 30 }],
        is_range_date: false,
      },
      {
        title: '关于扩军问题的指示',
        authors: ['毛泽东'],
        page_start: 371,
        page_end: 371,
        dates: [{ year: 1940, month: 1, day: 30 }],
        is_range_date: false,
      },
      {
        title: '关于山西新旧军冲突我之工作方针问题致朱德等电',
        authors: ['毛泽东'],
        page_start: 372,
        page_end: 373,
        dates: [{ year: 1940, month: 1, day: 31 }],
        is_range_date: false,
      },
      {
        title: '为陕甘宁边区文化协会第一次代表大会题词',
        authors: ['毛泽东'],
        page_start: 374,
        page_end: 374,
        dates: [{ year: 1940, month: 1 }],
        is_range_date: false,
      },
      {
        title: '为《中国文化》题词叫',
        authors: ['毛泽东'],
        page_start: 375,
        page_end: 376,
        dates: [{ year: 1940, month: 1 }],
        is_range_date: false,
      },
      {
        title: '团结一切抗日力量，反对反共颜固派',
        authors: ['毛泽东'],
        page_start: 377,
        page_end: 383,
        dates: [{ year: 1940, month: 2, day: 1 }],
        is_range_date: false,
      },
      {
        title: '向国民党的十点要求',
        authors: ['毛泽东'],
        page_start: 384,
        page_end: 388,
        dates: [{ year: 1940, month: 2, day: 1 }],
        is_range_date: false,
      },
      {
        title: '中共中央关于目前时局与党的任务的决定',
        authors: ['毛泽东'],
        page_start: 389,
        page_end: 392,
        dates: [{ year: 1940, month: 2, day: 1 }],
        is_range_date: false,
      },
      {
        title: '复王世英电',
        authors: ['毛泽东'],
        page_start: 393,
        page_end: 393,
        dates: [{ year: 1940, month: 2, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致国民参政会秘书处电',
        authors: ['毛泽东'],
        page_start: 394,
        page_end: 395,
        dates: [{ year: 1940, month: 2, day: 3 }],
        is_range_date: false,
      },
      {
        title: '致叶挺、项英电',
        authors: ['毛泽东'],
        page_start: 396,
        page_end: 396,
        dates: [{ year: 1940, month: 2, day: 3 }],
        is_range_date: false,
      },
      {
        title: '给陈云的信',
        authors: ['毛泽东'],
        page_start: 397,
        page_end: 397,
        dates: [{ year: 1940, month: 2, day: 3 }],
        is_range_date: false,
      },
      {
        title: '坚决彻底消灭石友三部',
        authors: ['毛泽东'],
        page_start: 398,
        page_end: 398,
        dates: [{ year: 1940, month: 2, day: 3 }],
        is_range_date: false,
      },
      {
        title: '在陕甘宁边区自然科学研究会成立大会上的讲语',
        authors: ['毛泽东'],
        page_start: 399,
        page_end: 400,
        dates: [{ year: 1940, month: 2, day: 5 }],
        is_range_date: false,
      },
      {
        title: '为《中国工人》出版题词可',
        authors: ['毛泽东'],
        page_start: 401,
        page_end: 402,
        dates: [{ year: 1940, month: 2, day: 7 }],
        is_range_date: false,
      },
      {
        title: '为《中国工人》题名',
        authors: ['毛泽东'],
        page_start: 403,
        page_end: 403,
        dates: [{ year: 1940, month: 2, day: 7 }],
        is_range_date: false,
      },
      {
        title: '中国工人》发刊词',
        authors: ['毛泽东'],
        page_start: 404,
        page_end: 405,
        dates: [{ year: 1940, month: 2, day: 7 }],
        is_range_date: false,
      },
      {
        title: '纪念《新中华报》新刊一周年',
        authors: ['毛泽东'],
        page_start: 406,
        page_end: 408,
        dates: [{ year: 1940, month: 2, day: 7 }],
        is_range_date: false,
      },
      {
        title: '为《新中华报》改版一周年题词叫',
        authors: ['毛泽东'],
        page_start: 409,
        page_end: 410,
        dates: [{ year: 1940, month: 2, day: 7 }],
        is_range_date: false,
      },
      {
        title: '复南方局电',
        authors: ['毛泽东'],
        page_start: 411,
        page_end: 411,
        dates: [{ year: 1940, month: 2, day: 9 }],
        is_range_date: false,
      },
      {
        title: '挺进军的战略任务',
        authors: ['毛泽东'],
        page_start: 412,
        page_end: 413,
        dates: [{ year: 1940, month: 2, day: 11 }],
        is_range_date: false,
      },
      {
        title: '彻底消灭颜固派，极力争取有希望之人叫',
        authors: ['毛泽东'],
        page_start: 414,
        page_end: 414,
        dates: [{ year: 1939, month: 2, day: 11 }],
        is_range_date: false,
      },
      {
        title: '关于处理普西事变的指示',
        authors: ['毛泽东'],
        page_start: 415,
        page_end: 416,
        dates: [{ year: 1940, month: 2, day: 12 }],
        is_range_date: false,
      },
      {
        title: '关于对阁锡山的态度与口号致朱德、彭德怀电',
        authors: ['毛泽东'],
        page_start: 417,
        page_end: 417,
        dates: [{ year: 1940, month: 2, day: 14 }],
        is_range_date: false,
      },
      {
        title: '为应云卫题词叫',
        authors: ['毛泽东'],
        page_start: 418,
        page_end: 418,
        dates: [{ year: 1940, month: 2, day: 15 }],
        is_range_date: false,
      },
      {
        title: '为吴茵题词',
        authors: ['毛泽东'],
        page_start: 419,
        page_end: 419,
        dates: [{ year: 1940, month: 2, day: 15 }],
        is_range_date: false,
      },
      {
        title: '为《中国文化》题名',
        authors: ['毛泽东'],
        page_start: 420,
        page_end: 421,
        dates: [{ year: 1940, month: 2, day: 15 }],
        is_range_date: false,
      },
      {
        title: '致高双成电',
        authors: ['毛泽东'],
        page_start: 422,
        page_end: 422,
        dates: [{ year: 1940, month: 2, day: 16 }],
        is_range_date: false,
      },
      {
        title: '在延安青年宪政促进会成立大会上的讲话',
        authors: ['毛泽东'],
        page_start: 423,
        page_end: 423,
        dates: [{ year: 1940, month: 2, day: 19 }],
        is_range_date: false,
      },
      {
        title: '致程潜电',
        authors: ['毛泽东'],
        page_start: 424,
        page_end: 424,
        dates: [{ year: 1940, month: 2, day: 19 }],
        is_range_date: false,
      },
      {
        title: '延安各界宪政促进会宣言',
        authors: ['毛泽东'],
        page_start: 425,
        page_end: 428,
        dates: [{ year: 1940, month: 2, day: 20 }],
        is_range_date: false,
      },
      {
        title: '新民主主义的宪政',
        authors: ['毛泽东'],
        page_start: 429,
        page_end: 437,
        dates: [{ year: 1940, month: 2, day: 20 }],
        is_range_date: false,
      },
      {
        title: '反磨擦斗争的形势',
        authors: ['毛泽东'],
        page_start: 438,
        page_end: 438,
        dates: [{ year: 1940, month: 2, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致贺龙、关向应等电',
        authors: ['毛泽东'],
        page_start: 439,
        page_end: 439,
        dates: [{ year: 1940, month: 2, day: 21 }],
        is_range_date: false,
      },
      {
        title: '致贺龙、关向应电',
        authors: ['毛泽东'],
        page_start: 440,
        page_end: 440,
        dates: [{ year: 1940, month: 2, day: 23 }],
        is_range_date: false,
      },
      {
        title: '致朱德、彭德怀等电',
        authors: ['毛泽东'],
        page_start: 441,
        page_end: 441,
        dates: [{ year: 1940, month: 2, day: 24 }],
        is_range_date: false,
      },
      {
        title: '对新军工作问题的指示',
        authors: ['毛泽东'],
        page_start: 442,
        page_end: 442,
        dates: [{ year: 1940, month: 2, day: 24 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话叫',
        authors: ['毛泽东'],
        page_start: 443,
        page_end: 443,
        dates: [{ year: 1940, month: 2, day: 28 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 444,
        page_end: 445,
        dates: [{ year: 1940, month: 2 }],
        is_range_date: false,
      },
      {
        title: '帮助萧克挺进军巩固平西根据地',
        authors: ['毛泽东'],
        page_start: 446,
        page_end: 447,
        dates: [{ year: 1940, month: 3, day: 3 }],
        is_range_date: false,
      },
      {
        title: '在陕甘宁边区党政联席会议上的讲话',
        authors: ['毛泽东'],
        page_start: 448,
        page_end: 449,
        dates: [{ year: 1940, month: 3, day: 4 }],
        is_range_date: false,
      },
      {
        title: '致八路军、北方局等电',
        authors: ['毛泽东'],
        page_start: 450,
        page_end: 450,
        dates: [{ year: 1940, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '争取对内和平，巩固已得阵地',
        authors: ['毛泽东'],
        page_start: 451,
        page_end: 453,
        dates: [{ year: 1940, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '致朱德、彭德怀、杨尚昆等电',
        authors: ['毛泽东'],
        page_start: 454,
        page_end: 454,
        dates: [{ year: 1940, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '致王震电',
        authors: ['毛泽东'],
        page_start: 455,
        page_end: 455,
        dates: [{ year: 1940, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '致项英等电',
        authors: ['毛泽东'],
        page_start: 456,
        page_end: 456,
        dates: [{ year: 1940, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '抗日根据地的政权问题',
        authors: ['毛泽东'],
        page_start: 457,
        page_end: 459,
        dates: [{ year: 1940, month: 3, day: 6 }],
        is_range_date: false,
      },
      {
        title: '对上海工作的指示',
        authors: ['毛泽东'],
        page_start: 460,
        page_end: 460,
        dates: [{ year: 1940, month: 3, day: 6 }],
        is_range_date: false,
      },
      {
        title: '给蔡元培家属的信电',
        authors: ['毛泽东'],
        page_start: 461,
        page_end: 461,
        dates: [{ year: 1940, month: 3, day: 7 }],
        is_range_date: false,
      },
      {
        title: '致朱德、彭德怀、杨尚昆电',
        authors: ['毛泽东'],
        page_start: 462,
        page_end: 462,
        dates: [{ year: 1940, month: 3, day: 7 }],
        is_range_date: false,
      },
      {
        title: '致鼓荣臻等电',
        authors: ['毛泽东'],
        page_start: 463,
        page_end: 463,
        dates: [{ year: 1940, month: 3, day: 8 }],
        is_range_date: false,
      },
      {
        title: '坚持国共长期合作',
        authors: ['毛泽东'],
        page_start: 464,
        page_end: 464,
        dates: [{ year: 1940, month: 3, day: 9 }],
        is_range_date: false,
      },
      {
        title: '给王枚的信',
        authors: ['毛泽东'],
        page_start: 465,
        page_end: 465,
        dates: [{ year: 1940, month: 3, day: 10 }],
        is_range_date: false,
      },
      {
        title: '自前抗日统一战线中的策略问题',
        authors: ['毛泽东'],
        page_start: 466,
        page_end: 474,
        dates: [{ year: 1940, month: 3, day: 11 }],
        is_range_date: false,
      },
      {
        title: '致琼崖部队领导人电',
        authors: ['毛泽东'],
        page_start: 475,
        page_end: 475,
        dates: [{ year: 1940, month: 3, day: 11 }],
        is_range_date: false,
      },
      {
        title: '反磨擦斗争必须注意自卫原则叫',
        authors: ['毛泽东'],
        page_start: 476,
        page_end: 476,
        dates: [{ year: 1940, month: 3, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致贺龙、关向应等电',
        authors: ['毛泽东'],
        page_start: 477,
        page_end: 477,
        dates: [{ year: 1940, month: 3, day: 14 }],
        is_range_date: false,
      },
      {
        title: '广泛印发讨江救国通电',
        authors: ['毛泽东'],
        page_start: 478,
        page_end: 479,
        dates: [{ year: 1940, month: 3, day: 15 }],
        is_range_date: false,
      },
      {
        title: '考虑作必要让步，避免破裂两党团结叫',
        authors: ['毛泽东'],
        page_start: 480,
        page_end: 480,
        dates: [{ year: 1940, month: 3, day: 15 }],
        is_range_date: false,
      },
      {
        title: '坚决阻止李文军渡河',
        authors: ['毛泽东'],
        page_start: 481,
        page_end: 481,
        dates: [{ year: 1940, month: 3, day: 15 }],
        is_range_date: false,
      },
      {
        title: '致卫立煌电',
        authors: ['毛泽东'],
        page_start: 482,
        page_end: 482,
        dates: [{ year: 1940, month: 3, day: 15 }],
        is_range_date: false,
      },
      {
        title: '给全国各台电的指示',
        authors: ['毛泽东'],
        page_start: 483,
        page_end: 483,
        dates: [{ year: 1940, month: 3, day: 15 }],
        is_range_date: false,
      },
      {
        title: '华北应在军事上立即转为守势',
        authors: ['毛泽东'],
        page_start: 484,
        page_end: 485,
        dates: [{ year: 1940, month: 3, day: 16 }],
        is_range_date: false,
      },
      {
        title: '在纪念三八国际妇女节大会上的讲话',
        authors: ['毛泽东'],
        page_start: 486,
        page_end: 486,
        dates: [{ year: 1940, month: 3, day: 16 }],
        is_range_date: false,
      },
      {
        title: '复朱德等电',
        authors: ['毛泽东'],
        page_start: 487,
        page_end: 487,
        dates: [{ year: 1940, month: 3, day: 19 }],
        is_range_date: false,
      },
      {
        title: '巩固华北发展鲁苏晓像鄂五省',
        authors: ['毛泽东'],
        page_start: 488,
        page_end: 489,
        dates: [{ year: 1940, month: 3, day: 19 }],
        is_range_date: false,
      },
      {
        title: '巩固中央与普东南及普察费之联络',
        authors: ['毛泽东'],
        page_start: 490,
        page_end: 490,
        dates: [{ year: 1940, month: 3, day: 19 }],
        is_range_date: false,
      },
      {
        title: '新四军的政治工作任务',
        authors: ['毛泽东'],
        page_start: 491,
        page_end: 491,
        dates: [{ year: 1940, month: 3, day: 19 }],
        is_range_date: false,
      },
      {
        title: '关于晋翼两省磨擦终止后团结友军推动时局好转的指示',
        authors: ['毛泽东'],
        page_start: 492,
        page_end: 492,
        dates: [{ year: 1940, month: 3, day: 20 }],
        is_range_date: false,
      },
      {
        title: '接助新四军创立皖东淮北苏北抗日根据地',
        authors: ['毛泽东'],
        page_start: 493,
        page_end: 497,
        dates: [{ year: 1940, month: 3, day: 21 }],
        is_range_date: false,
      },
      {
        title: '在中共中央书记处会议上的讲话',
        authors: ['毛泽东'],
        page_start: 498,
        page_end: 498,
        dates: [{ year: 1939, month: 3, day: 21 }],
        is_range_date: false,
      },
      {
        title: '致刘少奋及江北新四军各负责人电',
        authors: ['毛泽东'],
        page_start: 499,
        page_end: 499,
        dates: [{ year: 1940, month: 3, day: 21 }],
        is_range_date: false,
      },
      {
        title: '在中共中央书记处会议上的讲话',
        authors: ['毛泽东'],
        page_start: 500,
        page_end: 500,
        dates: [{ year: 1940, month: 3, day: 23 }],
        is_range_date: false,
      },
      {
        title: '对顽固派的斗争策略',
        authors: ['毛泽东'],
        page_start: 501,
        page_end: 501,
        dates: [{ year: 1940, month: 3, day: 25 }],
        is_range_date: false,
      },
      {
        title: '为《边区群众报》题名',
        authors: ['毛泽东'],
        page_start: 502,
        page_end: 503,
        dates: [{ year: 1940, month: 3, day: 25 }],
        is_range_date: false,
      },
      {
        title: '自前华中的军事策略',
        authors: ['毛泽东'],
        page_start: 504,
        page_end: 505,
        dates: [{ year: 1940, month: 3, day: 29 }],
        is_range_date: false,
      },
      {
        title: '为八路军一二师三五九旅题词',
        authors: ['毛泽东'],
        page_start: 506,
        page_end: 506,
        dates: [{ year: 1940, month: 3 }],
        is_range_date: false,
      },
      {
        title: '八路军致友军九十军书',
        authors: ['毛泽东'],
        page_start: 507,
        page_end: 508,
        dates: [{ year: 1940, month: 3 }],
        is_range_date: false,
      },
      {
        title: '对将介石在三月召开的全国参谋长会议上讲话的批语',
        authors: ['毛泽东'],
        page_start: 509,
        page_end: 509,
        dates: [{ year: 1940, month: 3 }],
        is_range_date: false,
      },
      {
        title: '目前八路军在华北华中的方针',
        authors: ['毛泽东'],
        page_start: 510,
        page_end: 512,
        dates: [{ year: 1940, month: 4, day: 1 }],
        is_range_date: false,
      },
      {
        title: '给肃劲光的信',
        authors: ['毛泽东'],
        page_start: 513,
        page_end: 513,
        dates: [{ year: 1940, month: 4, day: 1 }],
        is_range_date: false,
      },
      {
        title: '致朱德、彭德怀等电',
        authors: ['毛泽东'],
        page_start: 514,
        page_end: 514,
        dates: [{ year: 1940, month: 4, day: 1 }],
        is_range_date: false,
      },
      {
        title: '严防国民党军越过黄河进占缓德地区',
        authors: ['毛泽东'],
        page_start: 515,
        page_end: 515,
        dates: [{ year: 1940, month: 4, day: 1 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 516,
        page_end: 516,
        dates: [{ year: 1940, month: 4, day: 2 }],
        is_range_date: false,
      },
      {
        title: '新四军能否应付国民党的袭部',
        authors: ['毛泽东'],
        page_start: 517,
        page_end: 517,
        dates: [{ year: 1940, month: 4, day: 3 }],
        is_range_date: false,
      },
      {
        title: '致贺龙、关向应电',
        authors: ['毛泽东'],
        page_start: 518,
        page_end: 518,
        dates: [{ year: 1940, month: 4, day: 3 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 519,
        page_end: 519,
        dates: [{ year: 1940, month: 4, day: 4 }],
        is_range_date: false,
      },
      {
        title: '为儿童节题词',
        authors: ['毛泽东'],
        page_start: 520,
        page_end: 521,
        dates: [{ year: 1940, month: 4, day: 4 }],
        is_range_date: false,
      },
      {
        title: '发展华中根据地的部署',
        authors: ['毛泽东'],
        page_start: 522,
        page_end: 524,
        dates: [{ year: 1940, month: 4, day: 5 }],
        is_range_date: false,
      },
      {
        title: '致贺龙等电',
        authors: ['毛泽东'],
        page_start: 525,
        page_end: 525,
        dates: [{ year: 1940, month: 4, day: 6 }],
        is_range_date: false,
      },
      {
        title: '为鲁迅艺术文学院重新题写校名和校训',
        authors: ['毛泽东'],
        page_start: 526,
        page_end: 527,
        dates: [{ year: 1940, month: 4, day: 10 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 528,
        page_end: 528,
        dates: [{ year: 1940, month: 4, day: 11 }],
        is_range_date: false,
      },
      {
        title: '复朱德、彭德怀电',
        authors: ['毛泽东'],
        page_start: 529,
        page_end: 529,
        dates: [{ year: 1940, month: 4, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致朱德电',
        authors: ['毛泽东'],
        page_start: 530,
        page_end: 530,
        dates: [{ year: 1940, month: 4, day: 12 }],
        is_range_date: false,
      },
      {
        title: '对中间派应来取的方针',
        authors: ['毛泽东'],
        page_start: 531,
        page_end: 532,
        dates: [{ year: 1940, month: 4, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 533,
        page_end: 533,
        dates: [{ year: 1940, month: 4, day: 13 }],
        is_range_date: false,
      },
      {
        title: '给新疆督办盛世才的贺电',
        authors: ['毛泽东'],
        page_start: 534,
        page_end: 534,
        dates: [{ year: 1940, month: 4, day: 15 }],
        is_range_date: false,
      },
      {
        title: '关于对付韩德勤部问题致刘少奇等电',
        authors: ['毛泽东'],
        page_start: 535,
        page_end: 535,
        dates: [{ year: 1940, month: 4, day: 15 }],
        is_range_date: false,
      },
      {
        title: '为中华全国文艺界抗敌协会延安分会《大众文艺》题名',
        authors: ['毛泽东'],
        page_start: 536,
        page_end: 536,
        dates: [{ year: 1940, month: 4, day: 15 }],
        is_range_date: false,
      },
      {
        title: '致贺龙等电',
        authors: ['毛泽东'],
        page_start: 537,
        page_end: 537,
        dates: [{ year: 1940, month: 4, day: 16 }],
        is_range_date: false,
      },
      {
        title: '致项英电',
        authors: ['毛泽东'],
        page_start: 538,
        page_end: 538,
        dates: [{ year: 1940, month: 4, day: 18 }],
        is_range_date: false,
      },
      {
        title: '致刘少奇等电',
        authors: ['毛泽东'],
        page_start: 539,
        page_end: 539,
        dates: [{ year: 1940, month: 4, day: 21 }],
        is_range_date: false,
      },
      {
        title: '复贺龙、关向应电',
        authors: ['毛泽东'],
        page_start: 540,
        page_end: 540,
        dates: [{ year: 1940, month: 4, day: 21 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 541,
        page_end: 541,
        dates: [{ year: 1940, month: 4, day: 25 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 542,
        page_end: 542,
        dates: [{ year: 1940, month: 4, day: 29 }],
        is_range_date: false,
      },
    ],
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives8/maoquanji14.pdf',
};
