export default {
  entity: {
    id: 'maoquanji33',
    name: '毛泽东全集第33卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives0/main/mao-quanji/maoquanji33.pdf',
  },
  parser_option: {
    page_limits: [],
    articles: [
      {
        page_start: 32,
        page_end: 32,
        title: '加强斗争技术战术灭尽一切伞特',
        dates: [{ year: 1953, month: 3, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 33,
        page_end: 34,
        title: '转发第一次全国广播工作会议情况报告的批语',
        dates: [{ year: 1953, month: 3, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 35,
        page_end: 36,
        title: '在一封不同意批评胡风文艺思想的来信上的批语',
        dates: [{ year: 1953, month: 3, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 37,
        page_end: 37,
        title: '对李克农病况报告的批语',
        dates: [{ year: 1953, month: 3, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 38,
        page_end: 38,
        title: '慰问斯大林病情的电报',
        dates: [{ year: 1953, month: 3, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 39,
        page_end: 39,
        title: '对肖华关于派干部深入部队检查工作的报告的批语',
        dates: [{ year: 1953, month: 3, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 40,
        page_end: 40,
        title: '中央关于党的全国代表会议延期举行的通知',
        dates: [{ year: 1953, month: 3, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 41,
        page_end: 42,
        title: '关于悼念斯大林逝世的命令和电',
        dates: [{ year: 1953, month: 3, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 44,
        page_end: 45,
        title: '中央转发河北省委关于开展新三反斗争经验的批语',
        dates: [{ year: 1953, month: 3, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 46,
        page_end: 46,
        title: '中央转发华北局关于继续开展新三反的报告的批语',
        dates: [{ year: 1953, month: 3, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 47,
        page_end: 47,
        title: '对军委准备在沈阳市建立中心血库的批语',
        dates: [{ year: 1953, month: 3, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 48,
        page_end: 48,
        title: '在中央关于少数民族地区金融贸易政策的复文稿上加写的话',
        dates: [{ year: 1953, month: 3, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 49,
        page_end: 50,
        title: '给达赖喇嘛的信',
        dates: [{ year: 1953, month: 3, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 51,
        page_end: 52,
        title: '给黄炎培、陈叔通的信',
        dates: [{ year: 1953, month: 3, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 55,
        page_end: 59,
        title: '最伟大的友谊',
        dates: [{ year: 1953, month: 3, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 60,
        page_end: 60,
        title: '对财政部关于一九五二年所得税汇算清交工作报告的批语',
        dates: [{ year: 1953, month: 3, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 61,
        page_end: 62,
        title: '给达赖喇嘛的信',
        dates: [{ year: 1953, month: 3, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 63,
        page_end: 63,
        title: '给班禅额尔德尼的信',
        dates: [{ year: 1953, month: 3, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 64,
        page_end: 64,
        title: '军委关于同意西北匪部署的电报',
        dates: [{ year: 1953, month: 3, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 65,
        page_end: 65,
        title: '中央关于新三反的方针和部署的指示',
        dates: [{ year: 1953, month: 3, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 66,
        page_end: 66,
        title: '关于修筑通往福建的铁路线路问题给高岗的信',
        dates: [{ year: 1953, month: 3, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 67,
        page_end: 67,
        title: '对胡绩伟关于山东省级机关分散现象调查报告的批语',
        dates: [{ year: 1953, month: 3, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 68,
        page_end: 69,
        title: '对第二机械工业部反官僚主义报告的批语',
        dates: [{ year: 1953, month: 3, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 70,
        page_end: 70,
        title: '关于公开报道典型材料问题的批语',
        dates: [{ year: 1953, month: 3, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 72,
        page_end: 72,
        title: '在华南分局关于新三反给所属的指示上的批语',
        dates: [{ year: 1953, month: 3, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 73,
        page_end: 73,
        title: '悼念哥特瓦尔德逝世的电',
        dates: [{ year: 1953, month: 3, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 74,
        page_end: 74,
        title: '在军委关于同意中南军区一九五三年工作计划的复电稿上加写的话',
        dates: [{ year: 1953, month: 3, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 75,
        page_end: 76,
        title: '批判大汉族主义',
        dates: [{ year: 1953, month: 3, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 77,
        page_end: 77,
        title: '布置农村工作应照顾小农经济分散的特点',
        dates: [{ year: 1953, month: 3, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 78,
        page_end: 79,
        title:
          '对中央转发西北局关于甘肃临夏检查民族政策执行情况报告的批语和附注',
        dates: [{ year: 1953, month: 3, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 80,
        page_end: 81,
        title: '关于向陈云建议用毛巾蘸热水擦身的批语',
        dates: [{ year: 1953, month: 3, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 82,
        page_end: 85,
        title: '中央关于解决区乡工作中“五多”问题的指示',
        dates: [{ year: 1953, month: 3, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 86,
        page_end: 86,
        title: '关于减少军队专职体育运动员问题的批语',
        dates: [{ year: 1953, month: 3, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 87,
        page_end: 87,
        title: '对《上海市税务机关征税中违反政策现象严重》一文的批语',
        dates: [{ year: 1953, month: 3, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 88,
        page_end: 88,
        title: '关于处理日本渔轮侵入我渔区捕鱼问题的批语',
        dates: [{ year: 1953, month: 3, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 89,
        page_end: 89,
        title: '同意所提战俘交换方针',
        dates: [{ year: 1953, month: 3, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 90,
        page_end: 91,
        title: '关于准备同意讨论交换重伤病俘问题的电报',
        dates: [{ year: 1953, month: 3, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 92,
        page_end: 94,
        title: '对《中共中央关于农业生产互助合作决议》的批语和修改',
        dates: [{ year: 1953, month: 3, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 95,
        page_end: 98,
        title: '对湖北省委关于贯彻手工业代表会议精神的指示的批语',
        dates: [
          { year: 1953, month: 3, day: 24 },
          { year: 1953, month: 4, day: 4 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 99,
        page_end: 100,
        title: '中央关于如何在县区乡进行新三反的指示',
        dates: [{ year: 1953, month: 3, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 102,
        page_end: 102,
        title: '祝贺陶里亚蒂六十寿辰的电报',
        dates: [{ year: 1953, month: 3, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 103,
        page_end: 103,
        title: '关于通报上海市税务机关征税中严重违反政策的批语',
        dates: [{ year: 1953, month: 3, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 104,
        page_end: 104,
        title: '给黄炎培的信',
        dates: [{ year: 1953, month: 3, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 105,
        page_end: 105,
        title: '给林志钧的信',
        dates: [{ year: 1953, month: 3, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 106,
        page_end: 107,
        title: '中央转发山东分局关于新三反的报告的批语',
        dates: [{ year: 1953, month: 3, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 108,
        page_end: 109,
        title: '关于妥为处理四川万县事件和江津事件的批语',
        dates: [{ year: 1953, month: 3, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 110,
        page_end: 110,
        title: '关于减少中央及各部委所发全国性电报的批语',
        dates: [{ year: 1953, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 111,
        page_end: 112,
        title: '中央关于同意推迟执行群众性戒烟运动的指示的电报',
        dates: [{ year: 1953, month: 4, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 113,
        page_end: 114,
        title: '对中南行政委员会关于整顿小学的指示的批语',
        dates: [{ year: 1953, month: 4, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 115,
        page_end: 117,
        title: '关于检查军委卫生部领导工作的批语',
        dates: [
          { year: 1953, month: 4, day: 3 },
          { year: 1953, month: 4, day: 7 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 118,
        page_end: 118,
        title: '接受苏联新任驻华大使库兹涅佐夫呈递国书时的答词',
        dates: [{ year: 1953, month: 4, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 119,
        page_end: 119,
        title: '朝鲜停战后铁道兵须以大部修路一部进行技术训练',
        dates: [{ year: 1953, month: 4, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 120,
        page_end: 120,
        title: '给黄炎培、陈叔通的信',
        dates: [{ year: 1953, month: 4, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 121,
        page_end: 123,
        title: '对庆祝五一国际劳动节口号的批语和修改',
        dates: [{ year: 1953, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 124,
        page_end: 125,
        title: '印发关于供销合作社工作的两个文件的批语',
        dates: [{ year: 1953, month: 4, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 129,
        page_end: 129,
        title: '关于在反官僚主义的斗争中学习做领导工作的批语',
        dates: [{ year: 1953, month: 4, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 130,
        page_end: 130,
        title: '关于在中国政治法律学会章程及宣言中删去“毛泽东思想”字样的批语',
        dates: [{ year: 1953, month: 4, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 131,
        page_end: 131,
        title:
          '中央转发钱瑛关于广东发生官僚主义、命令主义和违法乱纪严重情况的报告的批语',
        dates: [{ year: 1953, month: 4, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 135,
        page_end: 135,
        title: '对安子文关于清理登记全国革命烈士的报告的批语',
        dates: [{ year: 1953, month: 4, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 136,
        page_end: 136,
        title: '给程潜的信',
        dates: [{ year: 1953, month: 4, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 138,
        page_end: 139,
        title: '对财政部关于全国农业税法会议请示的批语和对中央指示稿的修改',
        dates: [
          { year: 1953, month: 4, day: 16 },
          { year: 1953, month: 4, day: 21 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 140,
        page_end: 140,
        title: '给李烛尘的信',
        dates: [{ year: 1953, month: 4, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 143,
        page_end: 143,
        title: '要做好举行夏季战役的攻击准备',
        dates: [{ year: 1953, month: 4, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 144,
        page_end: 145,
        title: '对西南局关于加强对政府工作领导的规定的批语',
        dates: [{ year: 1953, month: 4, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 146,
        page_end: 146,
        title: '关于修改工会工作文件的批语',
        dates: [{ year: 1953, month: 4, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 147,
        page_end: 147,
        title: '关于同意推迟军衔评定工作的批语',
        dates: [{ year: 1953, month: 4, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 148,
        page_end: 148,
        title: '给李烛尘的信',
        dates: [{ year: 1953, month: 4, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 149,
        page_end: 149,
        title: '在中央关于派人下去检查工作的几项规定稿中加写的话',
        dates: [{ year: 1953, month: 4, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 153,
        page_end: 153,
        title: '对天津市委关于发动职工讨论生产计划的经验的批语',
        dates: [{ year: 1953, month: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 154,
        page_end: 154,
        title: '给毛泽荣的信',
        dates: [{ year: 1953, month: 5, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 157,
        page_end: 157,
        title: '关于解决任务与政策的矛盾的批语',
        dates: [{ year: 1953, month: 5, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 158,
        page_end: 158,
        title: '关于搜集敌战俘营中我伤病人员情况的电报',
        dates: [{ year: 1953, month: 5, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 159,
        page_end: 159,
        title: '关于大批减免西南灾区公粮和农业税的批语',
        dates: [{ year: 1953, month: 5, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 160,
        page_end: 160,
        title: '关于全国财政会议的议题和准备工作给陈云等的信',
        dates: [{ year: 1953, month: 5, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 161,
        page_end: 162,
        title: '对贾拓夫关于工业情况的报告稿的批语',
        dates: [{ year: 1953, month: 5, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 163,
        page_end: 163,
        title: '关于就战俘遣返方案同印度协商的意见',
        dates: [{ year: 1953, month: 5, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 164,
        page_end: 164,
        title: '中央关于基本同意西北军区甘青剿匪指挥部的布告的电报',
        dates: [{ year: 1953, month: 5, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 166,
        page_end: 166,
        title: '对中央关于限期完成购粮计划的指示稿的批语',
        dates: [{ year: 1953, month: 5, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 167,
        page_end: 167,
        title: '给张澜、黄炎培的信',
        dates: [{ year: 1953, month: 5, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 168,
        page_end: 168,
        title: '给黄炎培、陈叔通的信',
        dates: [{ year: 1953, month: 5, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 169,
        page_end: 169,
        title: '给黄炎培的信',
        dates: [{ year: 1953, month: 5, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 170,
        page_end: 172,
        title: '在中央政治局会议讨论高教、教育两部的请示报告上的指示',
        dates: [{ year: 1953, month: 5, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 173,
        page_end: 175,
        title: '对陈叔通来信的复信和批语',
        dates: [
          { year: 1953, month: 5, day: 18 },
          { year: 1953, month: 5, day: 19 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 176,
        page_end: 177,
        title: '关于用中央名义发文件、电报问题的信和批语',
        dates: [{ year: 1953, month: 5, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 178,
        page_end: 178,
        title: '对邓子恢报告中关于基本完成农村社会主义改造时间的传达问题的批语',
        dates: [{ year: 1953, month: 5, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 179,
        page_end: 180,
        title: '对总政布置调查美军虐待俘虏的报告稿的批语和修改',
        dates: [{ year: 1953, month: 5, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 181,
        page_end: 182,
        title: '给马叙伦的信',
        dates: [{ year: 1953, month: 5, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 183,
        page_end: 183,
        title: '关于邀请刘澜涛参加中央讨论经济工作的会议的批语',
        dates: [{ year: 1953, month: 5, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 184,
        page_end: 184,
        title: '关于付印三大条令草案的批语',
        dates: [{ year: 1953, month: 5, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 185,
        page_end: 185,
        title: '在中央会议中应有军委议程',
        dates: [{ year: 1953, month: 5, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 188,
        page_end: 188,
        title: '关于修改顾问工作守则给王稼祥的信',
        dates: [{ year: 1953, month: 5, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 191,
        page_end: 192,
        title: '中央转发华北局、新疆分局关于加强党对政府工作领导的决定的批语',
        dates: [{ year: 1953, month: 6, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 193,
        page_end: 193,
        title: '对高级步兵学校政治队第二期教育计划的批语',
        dates: [{ year: 1953, month: 6, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 194,
        page_end: 194,
        title: '关于印发有关新税制问题的几个文件的批语',
        dates: [{ year: 1953, month: 6, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 195,
        page_end: 195,
        title: '中央转发华南分局关于加强集体领导与各部门分工负责的决定的批语',
        dates: [{ year: 1953, month: 6, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 196,
        page_end: 198,
        title: '对陈叔通、黄炎培来信和附件的批语和复信',
        dates: [{ year: 1953, month: 6, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 199,
        page_end: 199,
        title: '在政治局会议上的讲话提纲',
        dates: [{ year: 1953, month: 6, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 200,
        page_end: 205,
        title: '在中共中央政治局会议上的讲话',
        dates: [{ year: 1953, month: 6, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 206,
        page_end: 207,
        title: '有关停战事务问题需早作准备',
        dates: [{ year: 1953, month: 6, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 208,
        page_end: 208,
        title: '停战签字必须推迟',
        dates: [{ year: 1953, month: 6, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 209,
        page_end: 209,
        title: '在警卫战士回乡探亲的调查报告上的批语',
        dates: [{ year: 1953, month: 6, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 211,
        page_end: 211,
        title: '给毛泽连的信',
        dates: [{ year: 1953, month: 6, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 212,
        page_end: 213,
        title: '中央转发莱阳地委关于物资供应工作总结报告的批语',
        dates: [{ year: 1953, month: 6, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 214,
        page_end: 216,
        title: '对《关于利用、限制和改造资本主义工商业的若干问题》的批语和修改',
        dates: [{ year: 1953, month: 6, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 217,
        page_end: 221,
        title: '青年团的工作要照顾青年的特点',
        dates: [{ year: 1953, month: 6, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 223,
        page_end: 224,
        title: '对青年团二大的指示',
        dates: [{ year: 1953, month: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 226,
        page_end: 226,
        title: '今冬明春农闲季节应集中力量解决区乡新三反问题',
        dates: [{ year: 1953, month: 7, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 227,
        page_end: 227,
        title: '接受蒙古驻华大使奥其巴特尔呈递国书时的答词',
        dates: [{ year: 1953, month: 7, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 228,
        page_end: 228,
        title: '为迁移马克思墓捐款给波立特的信',
        dates: [{ year: 1953, month: 7, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 229,
        page_end: 229,
        title: '对苏联一篇文章中批评“对立的统一”提法的批语',
        dates: [{ year: 1953, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 230,
        page_end: 230,
        title: '给符定一的信',
        dates: [{ year: 1953, month: 7, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 233,
        page_end: 234,
        title: '我们的方针仍然是掌握主动争取停战',
        dates: [{ year: 1953, month: 7, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 235,
        page_end: 235,
        title: '给张澜的信',
        dates: [{ year: 1953, month: 7, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 237,
        page_end: 237,
        title: '关于国家资本主义经济',
        dates: [{ year: 1953, month: 7, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 238,
        page_end: 239,
        title: '关于复会后的谈判应分两个步骤进行致李克农电',
        dates: [{ year: 1953, month: 7, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 240,
        page_end: 240,
        title: '中央关于小土地出租者、富农和地主贷款问题复西南局电',
        dates: [{ year: 1953, month: 7, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 242,
        page_end: 242,
        title: '关于缩减在辽东等地修建国防工事计划的批语',
        dates: [{ year: 1953, month: 7, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 243,
        page_end: 243,
        title: '给邹普勋的信',
        dates: [{ year: 1953, month: 7, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 244,
        page_end: 244,
        title: '涉及广大群众利益的事项未经允许不得下达',
        dates: [{ year: 1953, month: 7, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 245,
        page_end: 245,
        title: '为第一汽车制造厂奠基题词',
        dates: [{ year: 1953, month: 7, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 247,
        page_end: 248,
        title:
          '对全总关于加强资本主义工业企业中工会工作的指示和中央批语稿的修改',
        dates: [{ year: 1953, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 249,
        page_end: 249,
        title: '在黄克诚关于歼灭登陆之敌的部署的报告上的批语',
        dates: [{ year: 1953, month: 7, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 250,
        page_end: 252,
        title: '关于停战后工作安排和志愿军参加各委员会代表人选的问题',
        dates: [{ year: 1953, month: 7, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 253,
        page_end: 255,
        title: '关于朝鲜停战协定签字安排等问题的指示',
        dates: [{ year: 1953, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 256,
        page_end: 257,
        title: '坚决制止滥发统计报表',
        dates: [{ year: 1953, month: 7, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 258,
        page_end: 258,
        title: '停战协定签字后志愿军仍应提高警惕',
        dates: [{ year: 1953, month: 7, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 259,
        page_end: 259,
        title: '在中央关于处理湖东县劳改队看守打死群众事件的电报稿上加写的话',
        dates: [{ year: 1953, month: 7, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 260,
        page_end: 260,
        title: '对彭德怀谈话稿的修改意见',
        dates: [{ year: 1953, month: 7, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 261,
        page_end: 261,
        title: '关于朝鲜停战后空军作战等问题的批语',
        dates: [{ year: 1953, month: 7, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 263,
        page_end: 267,
        title: '在中央政治局扩大会议上的讲话',
        dates: [{ year: 1953, month: 7, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 268,
        page_end: 268,
        title: '给黄炎培的信',
        dates: [{ year: 1953, month: 7, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 269,
        page_end: 269,
        title: '答谢马林科夫、莫洛托夫祝贺朝鲜停战协定签字的电报',
        dates: [{ year: 1953, month: 7, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 270,
        page_end: 270,
        title: '给李济深的信',
        dates: [{ year: 1953, month: 7, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 272,
        page_end: 273,
        title: '关于国营企业中的工资、年终双薪、年休假问题的批语',
        dates: [{ year: 1953, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 274,
        page_end: 274,
        title: '关于不要劝龙云献出其公馆内浮财的批语',
        dates: [{ year: 1953, month: 8, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 275,
        page_end: 275,
        title: '对黄克诚关于英国商船要求我护航的报告的批语',
        dates: [{ year: 1953, month: 8, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 276,
        page_end: 276,
        title: '在中央关于西南文委机关反分散主义斗争的通报中加写的话',
        dates: [{ year: 1953, month: 8, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 277,
        page_end: 278,
        title: '总政转发中南军区党委关于召开高干会议检查工作的报告的批语',
        dates: [{ year: 1953, month: 8, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 279,
        page_end: 279,
        title: '对周恩来关于中德贸易问题复格罗提的信稿的批语和修改',
        dates: [{ year: 1953, month: 8, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 280,
        page_end: 281,
        title: '党在过渡时期的总路线',
        dates: [{ year: 1953, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 283,
        page_end: 290,
        title: '反对党内的资产阶级思想',
        dates: [{ year: 1953, month: 8, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 291,
        page_end: 291,
        title: '为祝贺朝鲜解放八周年致金科奉电',
        dates: [{ year: 1953, month: 8, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 292,
        page_end: 292,
        title: '在中央给罗贵波、邓一凡的电报稿上的批语',
        dates: [{ year: 1953, month: 8, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 293,
        page_end: 293,
        title: '在刘景范来信上的批语',
        dates: [{ year: 1953, month: 8, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 294,
        page_end: 294,
        title: '给叶恭绰的信',
        dates: [{ year: 1953, month: 8, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 296,
        page_end: 296,
        title: '关于海军执行运粮任务问题',
        dates: [{ year: 1953, month: 8, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 297,
        page_end: 297,
        title: '对“生产长一寸，福利长一分”口号的意见',
        dates: [{ year: 1953, month: 8, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 298,
        page_end: 299,
        title: '征询对告我方被俘人员书的意见',
        dates: [{ year: 1953, month: 8, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 300,
        page_end: 301,
        title: '给军事工程学院的训词',
        dates: [{ year: 1953, month: 8, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 302,
        page_end: 303,
        title: '对中央转发陕西省委传达全国财经会议精神的报告的批语和修改',
        dates: [
          { year: 1953, month: 8, day: 27 },
          { year: 1953, month: 8, day: 30 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 304,
        page_end: 304,
        title: '给李漱清的信',
        dates: [{ year: 1953, month: 8, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 306,
        page_end: 306,
        title: '给毛宇居的信',
        dates: [{ year: 1953, month: 8, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 308,
        page_end: 308,
        title: '给邹普勋的信',
        dates: [{ year: 1953, month: 8, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 309,
        page_end: 309,
        title:
          '在审阅中央关于增加生产、增加收入、厉行节约、紧缩开支、平衡国家预算的紧急指示稿时加写的话',
        dates: [{ year: 1953, month: 8, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 310,
        page_end: 310,
        title: '缩短主观主义时间的办法',
        dates: [{ year: 1953 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 311,
        page_end: 311,
        title: '为公安部队首届功臣模范代表大会题词',
        dates: [{ year: 1953, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 313,
        page_end: 314,
        title: '为祝贺抗日战争胜利八周年致马林科夫、莫洛托夫电',
        dates: [{ year: 1953, month: 9, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 315,
        page_end: 316,
        title: '对陈云在中央人民政府第二十六次会议上的报告要点稿的批语和修改',
        dates: [{ year: 1953, month: 9, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 317,
        page_end: 319,
        title: '改造资本主义工商业的必经之路',
        dates: [{ year: 1953, month: 9, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 321,
        page_end: 321,
        title: '给文涧泉的信',
        dates: [{ year: 1953, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 324,
        page_end: 324,
        title: '给张四维的信',
        dates: [{ year: 1953, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 325,
        page_end: 325,
        title: '在中央人民政府委员会第二十四次会议上关于抗美援朝战争的报告提纲',
        dates: [{ year: 1953, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 326,
        page_end: 330,
        title: '抗美援朝的伟大胜利和今后的任务',
        dates: [{ year: 1953, month: 9, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 334,
        page_end: 336,
        title: '给中国人民志愿军的慰问电',
        dates: [{ year: 1953, month: 9, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 339,
        page_end: 341,
        title: '关于感谢苏联政府援助我国经济建设的电报',
        dates: [{ year: 1953, month: 9, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 342,
        page_end: 350,
        title: '批判梁漱溟的反动思想',
        dates: [
          { year: 1953, month: 9, day: 16 },
          { year: 1953, month: 9, day: 18 },
        ],
        is_range_date: true,
        authors: ['毛泽东'],
      },
      {
        page_start: 353,
        page_end: 353,
        title: '对军委办公厅摘要报送空军安全会议情况报告的批语',
        dates: [{ year: 1953, month: 9, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 354,
        page_end: 354,
        title: '悼念布曼增迪的电报',
        dates: [{ year: 1953, month: 9, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 355,
        page_end: 355,
        title: '在朱德总司令国庆阅兵命令稿上加写的话',
        dates: [{ year: 1953, month: 9, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 356,
        page_end: 356,
        title: '关于阅处高岗起草的致苏联政府文件的批语',
        dates: [{ year: 1953, month: 9, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 357,
        page_end: 357,
        title: '关于一切文电必须将发文年月日写齐的批语',
        dates: [{ year: 1953, month: 9, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 358,
        page_end: 358,
        title: '给沈钧儒的信',
        dates: [{ year: 1953, month: 9, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 360,
        page_end: 360,
        title: '给易礼容的信',
        dates: [{ year: 1953, month: 9, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 361,
        page_end: 361,
        title: '关于更改拖拉机厂、矿山机械厂厂址问题的批语',
        dates: [{ year: 1953, month: 9, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 362,
        page_end: 362,
        title: '为《工学》报题写报头',
        dates: [{ year: 1953, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 366,
        page_end: 368,
        title: '关于粮食统购统销问题的讲话提纲',
        dates: [{ year: 1953 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 369,
        page_end: 371,
        title: '粮食统购统销问题',
        dates: [{ year: 1953, month: 10, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 372,
        page_end: 373,
        title: '给毛月秋的信',
        dates: [{ year: 1953, month: 10, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 376,
        page_end: 376,
        title: '给马叙伦的信',
        dates: [{ year: 1953, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 378,
        page_end: 378,
        title: '祝贺德意志民主共和国成立四周年的电报',
        dates: [{ year: 1953, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 379,
        page_end: 379,
        title: '在印尼总统祝贺我国国庆的电报上的批语',
        dates: [{ year: 1953, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 380,
        page_end: 380,
        title: '在李大梁来信上的批语',
        dates: [{ year: 1953, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 382,
        page_end: 382,
        title: '对周恩来在全国财经会议上的结论的批语',
        dates: [{ year: 1953, month: 10, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 383,
        page_end: 383,
        title: '美蒋签订军事协调谅解协定值得注意',
        dates: [{ year: 1953, month: 10, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 384,
        page_end: 385,
        title: '关于粮食征购、配售和管理等几个问题的提纲',
        dates: [{ year: 1953, month: 10, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 386,
        page_end: 386,
        title: '为冯玉祥将军骨灰安葬仪式题词',
        dates: [{ year: 1953, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 388,
        page_end: 396,
        title: '关于农业互助合作的两次谈话',
        dates: [
          { year: 1953, month: 10, day: 15 },
          { year: 1953, month: 11, day: 4 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 397,
        page_end: 398,
        title: '关于重要土特产和副食品的经营问题',
        dates: [{ year: 1953, month: 10, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 399,
        page_end: 400,
        title: '对华南分局关于具体执行粮食征购配售政策的意见的批语',
        dates: [{ year: 1953, month: 10, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 401,
        page_end: 402,
        title: '关于实行粮食计划收购与计划供应决议的通知和毛泽东对决议稿的修改',
        dates: [{ year: 1953, month: 10, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 403,
        page_end: 403,
        title: '给李漱清的信',
        dates: [{ year: 1953, month: 10, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 404,
        page_end: 405,
        title: '接见西藏国庆观礼团、参观团代表的谈话',
        dates: [{ year: 1953, month: 10, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 406,
        page_end: 407,
        title: '对朝中停战代表团首席委员发言稿的修改意见',
        dates: [{ year: 1953, month: 10, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 408,
        page_end: 408,
        title: '给杨尚昆的信',
        dates: [{ year: 1953, month: 10, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 410,
        page_end: 411,
        title: '对刘少奇等在全国组织工作会议领导小组会上的讲话稿的批语和修改',
        dates: [{ year: 1953, month: 10, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 413,
        page_end: 413,
        title: '给文九明的信',
        dates: [{ year: 1953, month: 10, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 416,
        page_end: 416,
        title: '接受印尼首任驻华大使莫诺努图呈递国书时的答词',
        dates: [{ year: 1953, month: 10, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 417,
        page_end: 418,
        title: '不怕破裂也不把门关死',
        dates: [{ year: 1953, month: 10, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 419,
        page_end: 419,
        title: '给邹普勋、谭熙春、毛锡臣的信',
        dates: [{ year: 1953, month: 10, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 420,
        page_end: 421,
        title: '关于李克农回国后停战代表团工作安排问题',
        dates: [{ year: 1953, month: 10, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 422,
        page_end: 424,
        title: '对中央关于统购粮食的宣传要点稿的修改',
        dates: [{ year: 1953, month: 10, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 425,
        page_end: 425,
        title: '中央关于批判党内的资本主义思想的指示',
        dates: [{ year: 1953, month: 11, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 426,
        page_end: 427,
        title: '对李维汉在全国工商联代表大会上的讲话稿的批语',
        dates: [{ year: 1953, month: 11, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 428,
        page_end: 428,
        title: '关于中央警卫团不应设立文工团的批语',
        dates: [{ year: 1953, month: 11, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 429,
        page_end: 430,
        title: '祝贺苏联十月革命三十六周年致马林科夫电',
        dates: [{ year: 1953, month: 11, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 431,
        page_end: 431,
        title: '拟公布美军细菌战战俘供词',
        dates: [{ year: 1953, month: 11, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 433,
        page_end: 434,
        title: '中央转发国家计委关于当前增产节约情况报告的批语',
        dates: [{ year: 1953, month: 11, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 435,
        page_end: 436,
        title: '关于召开全国军事系统党的高级干部会议和配备干部问题',
        dates: [{ year: 1953, month: 11, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 439,
        page_end: 439,
        title: '接受民主德国驻华大使柯尼希呈递国书时的答词',
        dates: [{ year: 1953, month: 11, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 440,
        page_end: 441,
        title:
          '中央转发天津市委统战部关于资本家对过渡时期总路线的反映的报告的批语',
        dates: [{ year: 1953, month: 11, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 442,
        page_end: 442,
        title: '关于签订中朝经济及文化合作协定等问题的批语',
        dates: [{ year: 1953, month: 11, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 443,
        page_end: 443,
        title:
          '对彭德怀《四年来军事工作总结和今后建军中的若干基本问题（初步定稿）》的批语',
        dates: [{ year: 1953, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 444,
        page_end: 446,
        title: '关于揭露美军对朝中军民暴行问题',
        dates: [
          { year: 1953, month: 12, day: 1 },
          { year: 1953, month: 12, day: 3 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 447,
        page_end: 447,
        title: '接受芬兰新任驻华公使孙士敦呈递国书时的答词',
        dates: [{ year: 1953, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 448,
        page_end: 448,
        title: '给黄炎培的信',
        dates: [{ year: 1953, month: 12, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 450,
        page_end: 450,
        title: '给袁希洛的信',
        dates: [{ year: 1953, month: 12, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 452,
        page_end: 452,
        title: '建设一支强大的海军',
        dates: [{ year: 1953, month: 12, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 453,
        page_end: 454,
        title: '关于为中央政治局会议准备文件给杨尚昆的信',
        dates: [{ year: 1953, month: 12, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 455,
        page_end: 455,
        title: '关于通过公债条例及批准中朝协定给周恩来的信',
        dates: [{ year: 1953, month: 12, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 457,
        page_end: 461,
        title: '对过渡时期总路线宣传提纲的批语和修改',
        dates: [
          { year: 1953, month: 12, day: 7 },
          { year: 1953, month: 12, day: 13 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 465,
        page_end: 465,
        title: '给戴毓本的信',
        dates: [{ year: 1953, month: 12, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 467,
        page_end: 470,
        title: '关于资本主义工商业改造和统战人士安排问题',
        dates: [{ year: 1953, month: 12, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 471,
        page_end: 471,
        title: '对胡乔木关于在他暂离期间由凯丰列席中央会议等问题的请示的批语',
        dates: [{ year: 1953, month: 12, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 472,
        page_end: 472,
        title: '对统战部召集人物安排工作会议请示报告的批语',
        dates: [{ year: 1953, month: 12, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 473,
        page_end: 473,
        title: '接受朝鲜驻华大使崔一呈递国书时的答词',
        dates: [{ year: 1953, month: 12, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 474,
        page_end: 474,
        title: '接受丹麦驻华公使格瑞杰生呈递国书时的答词',
        dates: [{ year: 1953, month: 12, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 476,
        page_end: 478,
        title: '对中央关于发展农业生产合作社的决议稿的批语和修改',
        dates: [
          { year: 1953, month: 12, day: 13 },
          { year: 1953, month: 12, day: 22 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 480,
        page_end: 481,
        title: '关于看望徐悲鸿夫人的信',
        dates: [{ year: 1953, month: 12, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 483,
        page_end: 483,
        title: '接受苏联驻华大使尤金呈递国书时的答词',
        dates: [{ year: 1953, month: 12, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 485,
        page_end: 485,
        title: '对金门作战建议的批语',
        dates: [{ year: 1953, month: 12, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 486,
        page_end: 486,
        title: '同意目前不打金门',
        dates: [{ year: 1953, month: 12, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 487,
        page_end: 487,
        title: '为《人民工兵》题名',
        dates: [{ year: 1953, month: 12, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 488,
        page_end: 488,
        title: '给鞍山钢铁公司全体职工的贺信',
        dates: [{ year: 1953, month: 12, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 490,
        page_end: 490,
        title: '为《铁道兵》题名',
        dates: [{ year: 1953, month: 12, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 491,
        page_end: 491,
        title: '关于党在过渡时期的任务',
        dates: [{ year: 1953 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 492,
        page_end: 493,
        title: '对学校领导骨干、教材等问题的指示',
        dates: [{ year: 1953 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 494,
        page_end: 494,
        title: '青少年的教育',
        dates: [{ year: 1953 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 495,
        page_end: 495,
        title: '为海南岛海榆中线公路纪念碑题词',
        dates: [{ year: 1953 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 497,
        page_end: 497,
        title: '为华北烈士陵园题词',
        dates: [{ year: 1953 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 499,
        page_end: 499,
        title: '为河北清苑革命残废军人学校题词',
        dates: [{ year: 1953 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 501,
        page_end: 501,
        title: '为韶山学校题名',
        dates: [{ year: 1953 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 506,
        page_end: 506,
        title: '在转发邓子恢关于老根据地干部情况报告时加写的话',
        dates: [{ year: 1954, month: 1, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 507,
        page_end: 508,
        title: '对关于增强党的团结的决议草案的修改',
        dates: [{ year: 1954, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 509,
        page_end: 511,
        title: '关于召开七届四中全会问题的建议',
        dates: [
          { year: 1954, month: 1, day: 7 },
          { year: 1954, month: 1, day: 8 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 513,
        page_end: 514,
        title: '宪法起草工作计划',
        dates: [{ year: 1954, month: 1, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 518,
        page_end: 518,
        title: '关于在七届四中全会前征求对增强党的团结的决议草案的意见的电报',
        dates: [{ year: 1954, month: 1, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 519,
        page_end: 519,
        title: '关于高岗来信和七届四中全会的开会方针问题致刘少奇电',
        dates: [{ year: 1954, month: 1, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 521,
        page_end: 521,
        title: '同意彭德怀在全国军事系统党的高级干部会议上的结论稿的电报',
        dates: [{ year: 1954, month: 1, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 522,
        page_end: 523,
        title: '关于全国军事系统党的高级干部会议闭幕词的修改意见致朱德电',
        dates: [{ year: 1954, month: 1, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 524,
        page_end: 524,
        title: '关于由杨尚昆转达四中全会文件修改情况和有关意见给刘少奇等的信',
        dates: [{ year: 1954, month: 1, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 532,
        page_end: 532,
        title: '祝贺中苏友好同盟互助条约签订四周年致马林科夫电',
        dates: [{ year: 1954, month: 2, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 533,
        page_end: 535,
        title: '关于宪法初稿的讨论和修改给刘少奇等的电报和信',
        dates: [{ year: 1954, month: 2, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 536,
        page_end: 537,
        title: '关于宪法草案初稿修改情况给刘少奇等的信',
        dates: [
          { year: 1954, month: 2, day: 24 },
          { year: 1954, month: 2, day: 26 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
    ],
    ext: 'pdf',
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives0/mao-quanji/maoquanji33.pdf',
};
