export default {
  entity: {
    id: 'maoquanji6',
    name: '毛泽东全集第6卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives8/main/maoquanji6.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '关于春耕问题的训令',
        authors: ['毛泽东'],
        page_start: 23,
        page_end: 25,
        dates: [{ year: 1932, month: 2, day: 8 }],
        is_range_date: false,
      },
      {
        title: '对于临时最高法庭审理AB团改组派军事犯等要犯的判决书的决议案',
        authors: ['毛泽东'],
        page_start: 26,
        page_end: 27,
        dates: [{ year: 1932, month: 2 }],
        is_range_date: false,
      },
      {
        title: '为揭穿国民党反动派制造所请“伍豪等脱离共党启事”的阴谋的布告',
        authors: ['毛泽东'],
        page_start: 28,
        page_end: 28,
        dates: [{ year: 1932, month: 2 }],
        is_range_date: false,
      },
      {
        title: '给袁国平的信',
        authors: ['毛泽东'],
        page_start: 29,
        page_end: 31,
        dates: [{ year: 1932, month: 3, day: 6 }],
        is_range_date: false,
      },
      {
        title: '为杭武工作给闽西的一封信',
        authors: ['毛泽东'],
        page_start: 32,
        page_end: 38,
        dates: [{ year: 1932, month: 3, day: 9 }],
        is_range_date: false,
      },
      {
        title: '人民委员会对于植树运动的决议案',
        authors: ['毛泽东'],
        page_start: 39,
        page_end: 40,
        dates: [{ year: 1932, month: 3, day: 16 }],
        is_range_date: false,
      },
      {
        title: '直下漳州泉州方能调动敌人',
        authors: ['毛泽东'],
        page_start: 41,
        page_end: 42,
        dates: [{ year: 1932, month: 3, day: 30 }],
        is_range_date: false,
      },
      {
        title: '临时中央政府给福建省第一次工农兵苏维埃大会的指示',
        authors: ['毛泽东'],
        page_start: 43,
        page_end: 48,
        dates: [{ year: 1932, month: 3 }],
        is_range_date: false,
      },
      {
        title: '直鹅潭泉部队必须更迅速更集中山',
        authors: ['毛泽东'],
        page_start: 49,
        page_end: 51,
        dates: [{ year: 1932, month: 4, day: 2 }],
        is_range_date: false,
      },
      {
        title: '龙岩战斗胜利原因和岩永今后工作',
        authors: ['毛泽东'],
        page_start: 52,
        page_end: 53,
        dates: [{ year: 1932, month: 4, day: 11 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃共和国临时中央政府宣布对日战争宣言',
        authors: ['毛泽东'],
        page_start: 54,
        page_end: 56,
        dates: [{ year: 1932, month: 4, day: 15 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃共和国临时中央政府关于动员对日宣战的训令',
        authors: ['毛泽东'],
        page_start: 57,
        page_end: 61,
        dates: [{ year: 1932, month: 4, day: 15 }],
        is_range_date: false,
      },
      {
        title:
          '中华苏维埃共和国临时中央政府为对日宣战向全世界无产阶级和被压道民族官言',
        authors: ['毛泽东'],
        page_start: 62,
        page_end: 63,
        dates: [{ year: 1932, month: 4, day: 15 }],
        is_range_date: false,
      },
      {
        title: '今后中心任务和新区、白区工作的意见',
        authors: ['毛泽东'],
        page_start: 64,
        page_end: 65,
        dates: [{ year: 1932, month: 4, day: 22 }],
        is_range_date: false,
      },
      {
        title: '对政治估量、军事战略和东西路军任务的意见',
        authors: ['毛泽东'],
        page_start: 66,
        page_end: 67,
        dates: [{ year: 1932, month: 5, day: 3 }],
        is_range_date: false,
      },
      {
        title: '反对国民党出卖淞泸协定通电',
        authors: ['毛泽东'],
        page_start: 68,
        page_end: 69,
        dates: [{ year: 1932, month: 5, day: 9 }],
        is_range_date: false,
      },
      {
        title: '中央执行委员会关于批准江西省苏第一次代表大会各种决议案的决议',
        authors: ['毛泽东'],
        page_start: 70,
        page_end: 71,
        dates: [{ year: 1932, month: 6, day: 3 }],
        is_range_date: false,
      },
      {
        title: '致朱德、王橡祥电',
        authors: ['毛泽东'],
        page_start: 72,
        page_end: 72,
        dates: [{ year: 1932, month: 6, day: 5 }],
        is_range_date: false,
      },
      {
        title: '中央政府给湘省工农兵代表大会电',
        authors: ['毛泽东'],
        page_start: 73,
        page_end: 75,
        dates: [{ year: 1932, month: 6, day: 9 }],
        is_range_date: false,
      },
      {
        title: '中央执行委员会命令执字第四号',
        authors: ['毛泽东'],
        page_start: 76,
        page_end: 76,
        dates: [{ year: 1932, month: 6, day: 9 }],
        is_range_date: false,
      },
      {
        title: '裁判部的暂行组织及裁判条例',
        authors: ['毛泽东'],
        page_start: 77,
        page_end: 83,
        dates: [{ year: 1932, month: 6, day: 9 }],
        is_range_date: false,
      },
      {
        title: '内务部的暂行组织纲要',
        authors: ['毛泽东'],
        page_start: 84,
        page_end: 86,
        dates: [{ year: 1932, month: 6, day: 20 }],
        is_range_date: false,
      },
      {
        title: '关于保护妇女权利与建立妇女生活改善委员会的组织和工作',
        authors: ['毛泽东'],
        page_start: 87,
        page_end: 92,
        dates: [{ year: 1932, month: 6, day: 20 }],
        is_range_date: false,
      },
      {
        title: '发行“革命战争”短期公债条例',
        authors: ['毛泽东'],
        page_start: 93,
        page_end: 94,
        dates: [{ year: 1932, month: 6, day: 25 }],
        is_range_date: false,
      },
      {
        title: '关于战争动员与后方工作',
        authors: ['毛泽东'],
        page_start: 95,
        page_end: 105,
        dates: [{ year: 1932, month: 7, day: 7 }],
        is_range_date: false,
      },
      {
        title: '修正暂行税则',
        authors: ['毛泽东'],
        page_start: 106,
        page_end: 109,
        dates: [{ year: 1932, month: 7, day: 15 }],
        is_range_date: false,
      },
      {
        title: '提议由毛泽东任总政委',
        authors: ['毛泽东'],
        page_start: 110,
        page_end: 110,
        dates: [{ year: 1932, month: 7, day: 25 }],
        is_range_date: false,
      },
      {
        title: '当前作战方向问题',
        authors: ['毛泽东'],
        page_start: 111,
        page_end: 112,
        dates: [{ year: 1932, month: 7, day: 25 }],
        is_range_date: false,
      },
      {
        title: '关于批准临时最高法庭对季黄反革命案件判决书的决议案',
        authors: ['毛泽东'],
        page_start: 113,
        page_end: 114,
        dates: [{ year: 1932, month: 8, day: 10 }],
        is_range_date: false,
      },
      {
        title: '消灭乐安之敌的训令',
        authors: ['毛泽东'],
        page_start: 115,
        page_end: 116,
        dates: [{ year: 1932, month: 8, day: 15 }],
        is_range_date: false,
      },
      {
        title: '宜黄乐安等地敌情和我军作战部署叫',
        authors: ['毛泽东'],
        page_start: 117,
        page_end: 118,
        dates: [{ year: 1932, month: 8, day: 15 }],
        is_range_date: false,
      },
      {
        title: '红一方面军乐安、宜黄战役要图',
        authors: ['毛泽东'],
        page_start: 119,
        page_end: 119,
        dates: [{ year: 1932, month: 8 }],
        is_range_date: false,
      },
      {
        title: '打击陈诚部队的训令',
        authors: ['毛泽东'],
        page_start: 120,
        page_end: 123,
        dates: [{ year: 1932, month: 8, day: 29 }],
        is_range_date: false,
      },
      {
        title: '红军第一方面军总部命令',
        authors: ['毛泽东'],
        page_start: 124,
        page_end: 124,
        dates: [{ year: 1932, month: 8, day: 31 }],
        is_range_date: false,
      },
      {
        title: '致周恩来、朱德、王橡祥电',
        authors: ['毛泽东'],
        page_start: 125,
        page_end: 125,
        dates: [{ year: 1932, month: 9, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致周恩来、朱德、王称祥电',
        authors: ['毛泽东'],
        page_start: 126,
        page_end: 126,
        dates: [{ year: 1932, month: 9, day: 3 }],
        is_range_date: false,
      },
      {
        title: '部队必须轻装的命令叫',
        authors: ['毛泽东'],
        page_start: 127,
        page_end: 132,
        dates: [{ year: 1932, month: 9, day: 5 }],
        is_range_date: false,
      },
      {
        title: '临时中央政府人民委员会命令第二十五号',
        authors: ['毛泽东'],
        page_start: 133,
        page_end: 134,
        dates: [{ year: 1932, month: 9, day: 17 }],
        is_range_date: false,
      },
      {
        title: '关于继续改造地方苏维埃政府问题',
        authors: ['毛泽东'],
        page_start: 135,
        page_end: 137,
        dates: [{ year: 1932, month: 9, day: 20 }],
        is_range_date: false,
      },
      {
        title: '关于日前军事行动的报告',
        authors: ['毛泽东'],
        page_start: 138,
        page_end: 140,
        dates: [{ year: 1932, month: 9, day: 23 }],
        is_range_date: false,
      },
      {
        title: '关于中央政府周年纪念',
        authors: ['毛泽东'],
        page_start: 141,
        page_end: 142,
        dates: [{ year: 1932, month: 9, day: 24 }],
        is_range_date: false,
      },
      {
        title: '提议在前方召开中央局全会讨论作战行动问题',
        authors: ['毛泽东'],
        page_start: 143,
        page_end: 145,
        dates: [{ year: 1932, month: 9, day: 25 }],
        is_range_date: false,
      },
      {
        title: '关于方面军行动与中央局全会地点问题的意见',
        authors: ['毛泽东'],
        page_start: 146,
        page_end: 147,
        dates: [{ year: 1932, month: 9, day: 26 }],
        is_range_date: false,
      },
      {
        title: '敌大举进攻前部队向北工作一时期的训令',
        authors: ['毛泽东'],
        page_start: 148,
        page_end: 153,
        dates: [{ year: 1932, month: 9, day: 26 }],
        is_range_date: false,
      },
      {
        title: '应紧急动员并布置中央苏区与各苏区行动',
        authors: ['毛泽东'],
        page_start: 154,
        page_end: 154,
        dates: [{ year: 1932, month: 9, day: 30 }],
        is_range_date: false,
      },
      {
        title: '关于鄂像院应选敌弱点好其一部的意见',
        authors: ['毛泽东'],
        page_start: 155,
        page_end: 156,
        dates: [{ year: 1932, month: 9, day: 30 }],
        is_range_date: false,
      },
      {
        title: '复中共苏区中央局等电',
        authors: ['毛泽东'],
        page_start: 157,
        page_end: 157,
        dates: [{ year: 1932, month: 9, day: 30 }],
        is_range_date: false,
      },
      {
        title: '反对国联调查团报告书通电',
        authors: ['毛泽东'],
        page_start: 158,
        page_end: 160,
        dates: [{ year: 1932, month: 10, day: 6 }],
        is_range_date: false,
      },
      {
        title: '关于战争紧急动员',
        authors: ['毛泽东'],
        page_start: 161,
        page_end: 166,
        dates: [{ year: 1932, month: 10, day: 13 }],
        is_range_date: false,
      },
      {
        title: '中央人民委员会第二十九号命令',
        authors: ['毛泽东'],
        page_start: 167,
        page_end: 167,
        dates: [{ year: 1932, month: 10, day: 13 }],
        is_range_date: false,
      },
      {
        title: '中央人民委员会第三十号命令',
        authors: ['毛泽东'],
        page_start: 168,
        page_end: 168,
        dates: [{ year: 1932, month: 10, day: 13 }],
        is_range_date: false,
      },
      {
        title: '红军第一方面军战役计划',
        authors: ['毛泽东'],
        page_start: 169,
        page_end: 174,
        dates: [{ year: 1932, month: 10, day: 14 }],
        is_range_date: false,
      },
      {
        title: '为发行第二期革命战争公债',
        authors: ['毛泽东'],
        page_start: 175,
        page_end: 178,
        dates: [{ year: 1932, month: 10, day: 21 }],
        is_range_date: false,
      },
      {
        title: '中央执行委员会给福建省苏主席团的指示信',
        authors: ['毛泽东'],
        page_start: 179,
        page_end: 180,
        dates: [{ year: 1932, month: 10, day: 31 }],
        is_range_date: false,
      },
      {
        title: '临时中央政府一周年纪念向全体选民的工作报告书',
        authors: ['毛泽东'],
        page_start: 181,
        page_end: 192,
        dates: [{ year: 1932, month: 11, day: 7 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃共和国临时中央政府成立周年纪念宣言',
        authors: ['毛泽东'],
        page_start: 193,
        page_end: 196,
        dates: [{ year: 1932, month: 11, day: 7 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃共和国临时中央政府人民委员会命令',
        authors: ['毛泽东'],
        page_start: 197,
        page_end: 198,
        dates: [{ year: 1932, month: 11, day: 12 }],
        is_range_date: false,
      },
      {
        title: '征发富农组织劳役队',
        authors: ['毛泽东'],
        page_start: 199,
        page_end: 199,
        dates: [{ year: 1932, month: 11, day: 25 }],
        is_range_date: false,
      },
      {
        title: '为多种杂粮禁种毒品事',
        authors: ['毛泽东'],
        page_start: 200,
        page_end: 201,
        dates: [{ year: 1932, month: 11, day: 25 }],
        is_range_date: false,
      },
      {
        title: '关于战争动员和工作方式',
        authors: ['毛泽东'],
        page_start: 202,
        page_end: 207,
        dates: [{ year: 1932, month: 11, day: 29 }],
        is_range_date: false,
      },
      {
        title: '关于各级选举运动的检查',
        authors: ['毛泽东'],
        page_start: 208,
        page_end: 210,
        dates: [{ year: 1932, month: 12, day: 1 }],
        is_range_date: false,
      },
      {
        title: '为纪念广州器动同时纪念宁都暴动周年纪念',
        authors: ['毛泽东'],
        page_start: 211,
        page_end: 211,
        dates: [{ year: 1932, month: 12, day: 2 }],
        is_range_date: false,
      },
      {
        title: '关于地方武装编制问题的密令叫',
        authors: ['毛泽东'],
        page_start: 212,
        page_end: 215,
        dates: [{ year: 1932, month: 12, day: 20 }],
        is_range_date: false,
      },
      {
        title: '中央人民委员会训令第八号',
        authors: ['毛泽东'],
        page_start: 216,
        page_end: 217,
        dates: [{ year: 1932, month: 12, day: 27 }],
        is_range_date: false,
      },
      {
        title: '为严紧出境行人事',
        authors: ['毛泽东'],
        page_start: 218,
        page_end: 219,
        dates: [{ year: 1932, month: 12, day: 27 }],
        is_range_date: false,
      },
      {
        title: '为提前春耕集中力量粉碎敌人大举进攻事',
        authors: ['毛泽东'],
        page_start: 220,
        page_end: 224,
        dates: [{ year: 1932, month: 12, day: 28 }],
        is_range_date: false,
      },
      {
        title: '为将宁都县改为博生县并举行追恒大会以纪念赵博生同志事',
        authors: ['毛泽东'],
        page_start: 225,
        page_end: 225,
        dates: [{ year: 1933, month: 1, day: 13 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃共和国临时政府及工农红军革命军事委员会宣言',
        authors: ['毛泽东'],
        page_start: 226,
        page_end: 229,
        dates: [{ year: 1933, month: 1, day: 17 }],
        is_range_date: false,
      },
      {
        title: '关于向富农募捐以充战费的训令',
        authors: ['毛泽东'],
        page_start: 230,
        page_end: 230,
        dates: [{ year: 1933, month: 2, day: 24 }],
        is_range_date: false,
      },
      {
        title: '关于政府工作人员实行帮助春利并自己种菜的训令叫',
        authors: ['毛泽东'],
        page_start: 231,
        page_end: 231,
        dates: [{ year: 1933, month: 2, day: 25 }],
        is_range_date: false,
      },
      {
        title: '和傅连瞳的谈话',
        authors: ['毛泽东'],
        page_start: 232,
        page_end: 232,
        dates: [{ year: 1933, month: 2 }],
        is_range_date: false,
      },
      {
        title: '为革命群众借谷供给红军',
        authors: ['毛泽东'],
        page_start: 233,
        page_end: 236,
        dates: [{ year: 1933, month: 3, day: 1 }],
        is_range_date: false,
      },
      {
        title:
          '中华苏维埃共和国中央执行委员会对于乡村工人分配土地及保留公田问题的决议',
        authors: ['毛泽东'],
        page_start: 237,
        page_end: 237,
        dates: [{ year: 1933, month: 3, day: 1 }],
        is_range_date: false,
      },
      {
        title: '反对日本帝国主义占领热河进攻平津',
        authors: ['毛泽东'],
        page_start: 238,
        page_end: 240,
        dates: [{ year: 1933, month: 3, day: 3 }],
        is_range_date: false,
      },
      {
        title: '为调节民食接济军粮',
        authors: ['毛泽东'],
        page_start: 241,
        page_end: 242,
        dates: [{ year: 1933, month: 3, day: 4 }],
        is_range_date: false,
      },
      {
        title: '订州不能轻易放弃',
        authors: ['毛泽东'],
        page_start: 243,
        page_end: 244,
        dates: [{ year: 1933, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '关于镇压内部反革命问题',
        authors: ['毛泽东'],
        page_start: 245,
        page_end: 247,
        dates: [{ year: 1933, month: 3, day: 15 }],
        is_range_date: false,
      },
      {
        title: '关于设立国民经济人民委员部及各级国民经济部的命令叫',
        authors: ['毛泽东'],
        page_start: 248,
        page_end: 248,
        dates: [{ year: 1933, month: 3, day: 23 }],
        is_range_date: false,
      },
      {
        title: '听取干观澜关于香田试点工作汇报时的指示',
        authors: ['毛泽东'],
        page_start: 249,
        page_end: 249,
        dates: [{ year: 1933, month: 3 }],
        is_range_date: false,
      },
      {
        title: '临时中央政府中央执行委员会命令第十八号',
        authors: ['毛泽东'],
        page_start: 250,
        page_end: 251,
        dates: [{ year: 1933, month: 4, day: 14 }],
        is_range_date: false,
      },
      {
        title: '临时中央政府与工农红军革命军事委员会的宣言',
        authors: ['毛泽东'],
        page_start: 252,
        page_end: 255,
        dates: [{ year: 1933, month: 4, day: 15 }],
        is_range_date: false,
      },
      {
        title: '为检查和取缩私人枪支禁止冒穿军服事',
        authors: ['毛泽东'],
        page_start: 256,
        page_end: 258,
        dates: [{ year: 1933, month: 4, day: 15 }],
        is_range_date: false,
      },
      {
        title: '中央执行委员会关于肃反委员会决议',
        authors: ['毛泽东'],
        page_start: 259,
        page_end: 260,
        dates: [{ year: 1933, month: 4, day: 15 }],
        is_range_date: false,
      },
      {
        title: '为夏耕运动给各级苏维埃负责人的信',
        authors: ['毛泽东'],
        page_start: 261,
        page_end: 262,
        dates: [{ year: 1933, month: 4, day: 22 }],
        is_range_date: false,
      },
      {
        title: '关于设文国民经济部的训令',
        authors: ['毛泽东'],
        page_start: 263,
        page_end: 264,
        dates: [{ year: 1933, month: 4, day: 28 }],
        is_range_date: false,
      },
      {
        title: '为限制特别快信',
        authors: ['毛泽东'],
        page_start: 265,
        page_end: 266,
        dates: [{ year: 1933, month: 5, day: 11 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃共和国中央政府告闽粤白军士兵书',
        authors: ['毛泽东'],
        page_start: 267,
        page_end: 268,
        dates: [{ year: 1933, month: 5, day: 28 }],
        is_range_date: false,
      },
      {
        title: '为“五州”运动会题词叫',
        authors: ['毛泽东'],
        page_start: 269,
        page_end: 269,
        dates: [{ year: 1933, month: 5 }],
        is_range_date: false,
      },
      {
        title: '苏维埃共和国中央政府为反对国民党出卖平津华北宣言',
        authors: ['毛泽东'],
        page_start: 270,
        page_end: 272,
        dates: [{ year: 1933, month: 6, day: 1 }],
        is_range_date: false,
      },
      {
        title: '中央政府关于香田运动的训令',
        authors: ['毛泽东'],
        page_start: 273,
        page_end: 276,
        dates: [{ year: 1933, month: 6, day: 1 }],
        is_range_date: false,
      },
      {
        title: '召集八县区以上苏维埃负责人员会议及八县贫农团代表大会',
        authors: ['毛泽东'],
        page_start: 277,
        page_end: 280,
        dates: [{ year: 1933, month: 6, day: 1 }],
        is_range_date: false,
      },
      {
        title: '为节省五方担谷子卖给红军告瑞金会昌博生石城四县群众',
        authors: ['毛泽东'],
        page_start: 281,
        page_end: 283,
        dates: [{ year: 1933, month: 6 }],
        is_range_date: false,
      },
      {
        title: '公认国民党签订卖国协定通电',
        authors: ['毛泽东'],
        page_start: 284,
        page_end: 286,
        dates: [{ year: 1933, month: 6, day: 10 }],
        is_range_date: false,
      },
      {
        title: '关于解决群众粮食问题',
        authors: ['毛泽东'],
        page_start: 287,
        page_end: 288,
        dates: [{ year: 1933, month: 6, day: 16 }],
        is_range_date: false,
      },
      {
        title: '香田运动是广大区域内的中心重大任务',
        authors: ['毛泽东'],
        page_start: 289,
        page_end: 292,
        dates: [{ year: 1933, month: 6 }],
        is_range_date: false,
      },
      {
        title: '香田运动的第一步组织上的大规模动员',
        authors: ['毛泽东'],
        page_start: 293,
        page_end: 295,
        dates: [{ year: 1933, month: 6 }],
        is_range_date: false,
      },
      {
        title: '香田运动的群众工作',
        authors: ['毛泽东'],
        page_start: 296,
        page_end: 302,
        dates: [{ year: 1933, month: 6 }],
        is_range_date: false,
      },
      {
        title: '依据农村中阶级斗争的发展状态的差别去开展香田运动',
        authors: ['毛泽东'],
        page_start: 303,
        page_end: 307,
        dates: [{ year: 1933, month: 6, day: 18 }],
        is_range_date: false,
      },
      {
        title: '八县区以上苏维埃负责人员香田运动大会所通过的结论',
        authors: ['毛泽东'],
        page_start: 308,
        page_end: 321,
        dates: [{ year: 1933, month: 6, day: 21 }],
        is_range_date: false,
      },
      {
        title: '关于倡办粮食合作社问题',
        authors: ['毛泽东'],
        page_start: 322,
        page_end: 323,
        dates: [{ year: 1933, month: 7, day: 4 }],
        is_range_date: false,
      },
      {
        title: '中央政府关于“八一”纪念运动的决议',
        authors: ['毛泽东'],
        page_start: 324,
        page_end: 326,
        dates: [{ year: 1933, month: 7, day: 11 }],
        is_range_date: false,
      },
      {
        title: '为香田运动给瑞金黄柏区苏的一封信',
        authors: ['毛泽东'],
        page_start: 327,
        page_end: 331,
        dates: [{ year: 1933, month: 7, day: 13 }],
        is_range_date: false,
      },
      {
        title: '资农团组织与工作大纲',
        authors: ['毛泽东'],
        page_start: 332,
        page_end: 338,
        dates: [{ year: 1933, month: 7, day: 15 }],
        is_range_date: false,
      },
      {
        title: '反对最近国民党卖国的大连会议通电',
        authors: ['毛泽东'],
        page_start: 339,
        page_end: 340,
        dates: [{ year: 1933, month: 7, day: 18 }],
        is_range_date: false,
      },
      {
        title: '中央执行委员会关于重新划分行政区域的决议',
        authors: ['毛泽东'],
        page_start: 341,
        page_end: 342,
        dates: [{ year: 1933, month: 7, day: 21 }],
        is_range_date: false,
      },
      {
        title: '关于执行重新划分行政区域的决议',
        authors: ['毛泽东'],
        page_start: 343,
        page_end: 344,
        dates: [{ year: 1933, month: 7, day: 22 }],
        is_range_date: false,
      },
      {
        title: '中央执行委员会关于发行经济建设公债的决议',
        authors: ['毛泽东'],
        page_start: 345,
        page_end: 346,
        dates: [{ year: 1933, month: 7, day: 22 }],
        is_range_date: false,
      },
      {
        title: '发行经济建设公债条例',
        authors: ['毛泽东'],
        page_start: 347,
        page_end: 348,
        dates: [{ year: 1933, month: 7, day: 22 }],
        is_range_date: false,
      },
      {
        title: '新的形势与新的任务',
        authors: ['毛泽东'],
        page_start: 349,
        page_end: 351,
        dates: [{ year: 1933, month: 7, day: 29 }],
        is_range_date: false,
      },
      {
        title: '临时中央政府召集第二次全国苏维埃代表大会宣言',
        authors: ['毛泽东'],
        page_start: 352,
        page_end: 355,
        dates: [{ year: 1933, month: 8, day: 1 }],
        is_range_date: false,
      },
      {
        title: '中央政府电贺东方红军的伟大胜利',
        authors: ['毛泽东'],
        page_start: 356,
        page_end: 356,
        dates: [{ year: 1933, month: 8, day: 8 }],
        is_range_date: false,
      },
      {
        title: '苏维埃暂行选举法',
        authors: ['毛泽东'],
        page_start: 357,
        page_end: 367,
        dates: [{ year: 1933, month: 8, day: 9 }],
        is_range_date: false,
      },
      {
        title: '中央执行委员会关于实施苏维埃暂行选举法》的决议',
        authors: ['毛泽东'],
        page_start: 368,
        page_end: 368,
        dates: [{ year: 1933, month: 8, day: 9 }],
        is_range_date: false,
      },
      {
        title: '关于此次选举运动的指示',
        authors: ['毛泽东'],
        page_start: 369,
        page_end: 377,
        dates: [{ year: 1933, month: 8, day: 9 }],
        is_range_date: false,
      },
      {
        title: '粉碎敌人五次“围刺与苏维埃经济建设任务的报告',
        authors: ['毛泽东'],
        page_start: 378,
        page_end: 382,
        dates: [{ year: 1933, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '必须注意经济工作',
        authors: ['毛泽东'],
        page_start: 383,
        page_end: 390,
        dates: [{ year: 1933, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '吉安的占领',
        authors: ['毛泽东'],
        page_start: 391,
        page_end: 394,
        dates: [{ year: 1933, month: 8, day: 13 }],
        is_range_date: false,
      },
      {
        title: '关于整顿财政部工作的训令',
        authors: ['毛泽东'],
        page_start: 395,
        page_end: 396,
        dates: [{ year: 1933, month: 8, day: 25 }],
        is_range_date: false,
      },
      {
        title: '为发行三百万经济建设公债',
        authors: ['毛泽东'],
        page_start: 397,
        page_end: 398,
        dates: [{ year: 1933, month: 8, day: 28 }],
        is_range_date: false,
      },
      {
        title: '关于推销公债的方法',
        authors: ['毛泽东'],
        page_start: 399,
        page_end: 401,
        dates: [{ year: 1933, month: 8, day: 28 }],
        is_range_date: false,
      },
      {
        title: '开展拥护国币的群众运动',
        authors: ['毛泽东'],
        page_start: 402,
        page_end: 402,
        dates: [{ year: 1933, month: 8, day: 28 }],
        is_range_date: false,
      },
      {
        title: '关于香田运动的初步总结',
        authors: ['毛泽东'],
        page_start: 403,
        page_end: 417,
        dates: [{ year: 1933, month: 8, day: 29 }],
        is_range_date: false,
      },
      {
        title: '全世界无产阶级与被压道民族联合起来',
        authors: ['毛泽东'],
        page_start: 418,
        page_end: 420,
        dates: [{ year: 1933, month: 8, day: 30 }],
        is_range_date: false,
      },
      {
        title: '为开展香田运动',
        authors: ['毛泽东'],
        page_start: 421,
        page_end: 424,
        dates: [{ year: 1933, month: 9, day: 1 }],
        is_range_date: false,
      },
      {
        title: '中央政府庆祝国际反帝非战大会开幕电',
        authors: ['毛泽东'],
        page_start: 425,
        page_end: 426,
        dates: [{ year: 1933, month: 9, day: 3 }],
        is_range_date: false,
      },
      {
        title: '今年的选举',
        authors: ['毛泽东'],
        page_start: 427,
        page_end: 438,
        dates: [{ year: 1933, month: 9, day: 6 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃共和国中央政府告全世界工农劳苦民众宣言',
        authors: ['毛泽东'],
        page_start: 439,
        page_end: 443,
        dates: [{ year: 1933, month: 9, day: 6 }],
        is_range_date: false,
      },
      {
        title: '关于教育工作',
        authors: ['毛泽东'],
        page_start: 444,
        page_end: 446,
        dates: [{ year: 1933, month: 9, day: 15 }],
        is_range_date: false,
      },
      {
        title: '农业税奢行税则',
        authors: ['毛泽东'],
        page_start: 447,
        page_end: 449,
        dates: [{ year: 1933, month: 9, day: 18 }],
        is_range_date: false,
      },
      {
        title: '纯正推销公债的命令主义',
        authors: ['毛泽东'],
        page_start: 450,
        page_end: 451,
        dates: [{ year: 1933, month: 9, day: 23 }],
        is_range_date: false,
      },
      {
        title: '怎样分析农村阶级',
        authors: ['毛泽东'],
        page_start: 452,
        page_end: 456,
        dates: [{ year: 1933, month: 10 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃共和国中央政府人民委员会命令第四十九号',
        authors: ['毛泽东'],
        page_start: 457,
        page_end: 458,
        dates: [{ year: 1933, month: 10, day: 10 }],
        is_range_date: false,
      },
      {
        title: '关于土地斗争中一些问题的决定',
        authors: ['毛泽东'],
        page_start: 459,
        page_end: 478,
        dates: [{ year: 1933, month: 10, day: 10 }],
        is_range_date: false,
      },
      {
        title: '关于重新颁布劳动法的决议',
        authors: ['毛泽东'],
        page_start: 479,
        page_end: 480,
        dates: [{ year: 1933, month: 10, day: 15 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃共和国劳动法',
        authors: ['毛泽东'],
        page_start: 481,
        page_end: 503,
        dates: [{ year: 1933, month: 10, day: 15 }],
        is_range_date: false,
      },
      {
        title: '违反劳动法令惩罚条例',
        authors: ['毛泽东'],
        page_start: 504,
        page_end: 505,
        dates: [{ year: 1933, month: 10, day: 15 }],
        is_range_date: false,
      },
      {
        title: '中央政府为粉碎五次“围紧急动员令',
        authors: ['毛泽东'],
        page_start: 506,
        page_end: 509,
        dates: [{ year: 1933, month: 10, day: 18 }],
        is_range_date: false,
      },
      {
        title:
          '中华苏维埃共和国临时中央政府成立两周年纪念对全体选民的工作报告书',
        authors: ['毛泽东'],
        page_start: 510,
        page_end: 516,
        dates: [{ year: 1933, month: 10, day: 24 }],
        is_range_date: false,
      },
      {
        title: '农业税奢行税则补充条例',
        authors: ['毛泽东'],
        page_start: 517,
        page_end: 521,
        dates: [{ year: 1933, month: 10, day: 26 }],
        is_range_date: false,
      },
      {
        title:
          '中华苏维埃共和国临时中央政府及革命军事委员会为“中日直接交涉告全国民众',
        authors: ['毛泽东'],
        page_start: 522,
        page_end: 524,
        dates: [{ year: 1933, month: 11, day: 11 }],
        is_range_date: false,
      },
    ],
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives8/maoquanji6.pdf',
};
