export default {
  entity: {
    id: 'maoquanji7-2',
    name: '毛泽东全集第7卷(2)',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives8/main/maoquanji7-2.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '婚姻法',
        authors: ['毛泽东'],
        page_start: 1,
        page_end: 4,
        dates: [{ year: 1934, month: 4, day: 8 }],
        is_range_date: false,
      },
      {
        title: '乡苏怎样工作？',
        authors: ['毛泽东'],
        page_start: 5,
        page_end: 19,
        dates: [{ year: 1934, month: 4, day: 10 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃共和国中央政府为援助上海美亚绸厂工人要工斗争宣言',
        authors: ['毛泽东'],
        page_start: 20,
        page_end: 21,
        dates: [{ year: 1934, month: 4, day: 16 }],
        is_range_date: false,
      },
      {
        title: '论日本帝国主义的防课',
        authors: ['毛泽东'],
        page_start: 22,
        page_end: 23,
        dates: [{ year: 1934, month: 4 }],
        is_range_date: false,
      },
      {
        title: '中央政府五一劳动节宣言',
        authors: ['毛泽东'],
        page_start: 24,
        page_end: 26,
        dates: [{ year: 1934, month: 4 }],
        is_range_date: false,
      },
      {
        title: '和刘晓、何长工的谈话',
        authors: ['毛泽东'],
        page_start: 27,
        page_end: 27,
        dates: [{ year: 1934, month: 4 }],
        is_range_date: false,
      },
      {
        title: '对红二十二师的指示',
        authors: ['毛泽东'],
        page_start: 28,
        page_end: 28,
        dates: [{ year: 1934, month: 5 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃共和国中央政府为反对国民党出卖华北宣言',
        authors: ['毛泽东'],
        page_start: 29,
        page_end: 33,
        dates: [{ year: 1934, month: 6, day: 19 }],
        is_range_date: false,
      },
      {
        title: '告白军官兵书',
        authors: ['毛泽东'],
        page_start: 34,
        page_end: 36,
        dates: [{ year: 1934, month: 6 }],
        is_range_date: false,
      },
      {
        title: '和刘晓、何长工的谈话',
        authors: ['毛泽东'],
        page_start: 37,
        page_end: 37,
        dates: [{ year: 1934, month: 6 }],
        is_range_date: false,
      },
      {
        title: '给中共会昌县委和县苏维埃的信',
        authors: ['毛泽东'],
        page_start: 38,
        page_end: 38,
        dates: [{ year: 1934, month: 6 }],
        is_range_date: false,
      },
      {
        title: '视察中央革命根据地南线时的谈话',
        authors: ['毛泽东'],
        page_start: 39,
        page_end: 39,
        dates: [{ year: 1934, month: 7, day: 1 }],
        is_range_date: false,
      },
      {
        title: '中国工农红军北上抗口宣言',
        authors: ['毛泽东'],
        page_start: 40,
        page_end: 43,
        dates: [{ year: 1934, month: 7, day: 15 }],
        is_range_date: false,
      },
      {
        title: '日前时局与红军抗日先遗队',
        authors: ['毛泽东'],
        page_start: 44,
        page_end: 49,
        dates: [{ year: 1934, month: 7, day: 31 }],
        is_range_date: false,
      },
      {
        title: '为《红星》报题词',
        authors: ['毛泽东'],
        page_start: 50,
        page_end: 50,
        dates: [{ year: 1934, month: 8, day: 1 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃共和国中央执行委员会命令',
        authors: ['毛泽东'],
        page_start: 51,
        page_end: 52,
        dates: [{ year: 1934, month: 8, day: 15 }],
        is_range_date: false,
      },
      {
        title: '在中共赣南省委召集的省、县、区三级主要干部会议上的讲话',
        authors: ['毛泽东'],
        page_start: 53,
        page_end: 53,
        dates: [{ year: 1934, month: 10, day: 15 }],
        is_range_date: false,
      },
      {
        title: '关于游击队动作的指示',
        authors: ['毛泽东'],
        page_start: 54,
        page_end: 94,
        dates: [{ year: 1934, month: 10 }],
        is_range_date: false,
      },
      {
        title: '和吴古清的谈话',
        authors: ['毛泽东'],
        page_start: 95,
        page_end: 95,
        dates: [{ year: 1934, month: 11 }],
        is_range_date: false,
      },
      {
        title: '出路在哪里？',
        authors: ['毛泽东'],
        page_start: 96,
        page_end: 102,
        dates: [{ year: 1934, month: 11, day: 7 }],
        is_range_date: false,
      },
      {
        title: '向白军士兵抗口六条纲领的建议',
        authors: ['毛泽东'],
        page_start: 103,
        page_end: 105,
        dates: [{ year: 1934 }],
        is_range_date: false,
      },
      {
        title: '在反“围”时鼓励红军的题词',
        authors: ['毛泽东'],
        page_start: 106,
        page_end: 113,
        dates: [{ year: 1934 }],
        is_range_date: false,
      },
      {
        title: '中央关于反对敌人五次“围”的总结决议',
        authors: ['毛泽东'],
        page_start: 114,
        page_end: 140,
        dates: [{ year: 1935, month: 1, day: 8 }],
        is_range_date: false,
      },
      {
        title: '中共中央政治局和中央军委给张国寿的电报',
        authors: ['毛泽东'],
        page_start: 141,
        page_end: 142,
        dates: [{ year: 1935, month: 1, day: 22 }],
        is_range_date: false,
      },
      {
        title: '中共中央政治局和中央军委给张国寿的电报',
        authors: ['毛泽东'],
        page_start: 143,
        page_end: 144,
        dates: [{ year: 1935, month: 1, day: 22 }],
        is_range_date: false,
      },
      {
        title: '中共中央政治局和中央军委给张国寿的电报',
        authors: ['毛泽东'],
        page_start: 145,
        page_end: 146,
        dates: [{ year: 1935, month: 1, day: 22 }],
        is_range_date: false,
      },
      {
        title: '杂言诗·改李白《赠汪伦》叫',
        authors: ['毛泽东'],
        page_start: 147,
        page_end: 147,
        dates: [{ year: 1935, month: 1 }],
        is_range_date: false,
      },
      {
        title: '忆秦嫩·爱山关',
        authors: ['毛泽东'],
        page_start: 148,
        page_end: 163,
        dates: [{ year: 1935, month: 2 }],
        is_range_date: false,
      },
      {
        title: '中央军委命令山',
        authors: ['毛泽东'],
        page_start: 164,
        page_end: 168,
        dates: [{ year: 1935, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '在中共中央、中革军委负责人会议上的讲话',
        authors: ['毛泽东'],
        page_start: 169,
        page_end: 169,
        dates: [{ year: 1935, month: 4, day: 28 }],
        is_range_date: false,
      },
      {
        title: '为反对日本并吞华北和将介石卖国宣言',
        authors: ['毛泽东'],
        page_start: 170,
        page_end: 174,
        dates: [{ year: 1935, month: 6, day: 15 }],
        is_range_date: false,
      },
      {
        title: '为同四方面军会合复四方面军电',
        authors: ['毛泽东'],
        page_start: 175,
        page_end: 175,
        dates: [{ year: 1935, month: 6, day: 16 }],
        is_range_date: false,
      },
      {
        title: '应在川陕甘三省建立苏维埃政权',
        authors: ['毛泽东'],
        page_start: 176,
        page_end: 178,
        dates: [{ year: 1935, month: 6, day: 16 }],
        is_range_date: false,
      },
      {
        title: '四方面军须力攻平武松潘',
        authors: ['毛泽东'],
        page_start: 179,
        page_end: 180,
        dates: [{ year: 1935, month: 6, day: 18 }],
        is_range_date: false,
      },
      {
        title: '四方面军须力攻平武松潘山',
        authors: ['毛泽东'],
        page_start: 181,
        page_end: 182,
        dates: [{ year: 1935, month: 6, day: 18 }],
        is_range_date: false,
      },
      {
        title: '力争实行川陕甘方针',
        authors: ['毛泽东'],
        page_start: 183,
        page_end: 184,
        dates: [{ year: 1935, month: 6, day: 20 }],
        is_range_date: false,
      },
      {
        title: '关于红一、红四方面军会师后的战略方针的无点意见',
        authors: ['毛泽东'],
        page_start: 185,
        page_end: 185,
        dates: [{ year: 1935, month: 6, day: 26 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局常委会议上的讲话',
        authors: ['毛泽东'],
        page_start: 186,
        page_end: 187,
        dates: [{ year: 1935, month: 6, day: 29 }],
        is_range_date: false,
      },
      {
        title: '四方面军应迅速北上',
        authors: ['毛泽东'],
        page_start: 188,
        page_end: 188,
        dates: [{ year: 1935, month: 7, day: 10 }],
        is_range_date: false,
      },
      {
        title: '红四方面军的工作问题',
        authors: ['毛泽东'],
        page_start: 189,
        page_end: 190,
        dates: [{ year: 1935, month: 7, day: 21 }],
        is_range_date: false,
      },
      {
        title: '红四方面军的工作问题',
        authors: ['毛泽东'],
        page_start: 191,
        page_end: 192,
        dates: [{ year: 1935, month: 7, day: 21 }],
        is_range_date: false,
      },
      {
        title: '红一、四方面军会师后的方针和任务',
        authors: ['毛泽东'],
        page_start: 193,
        page_end: 195,
        dates: [{ year: 1935, month: 7 }],
        is_range_date: false,
      },
      {
        title: '中央关于一、四方面军会合后的政治任务与形势的决议',
        authors: ['毛泽东'],
        page_start: 196,
        page_end: 214,
        dates: [{ year: 1935, month: 8, day: 5 }],
        is_range_date: false,
      },
      {
        title: '关于夏跳战役后行动问题的报告',
        authors: ['毛泽东'],
        page_start: 215,
        page_end: 215,
        dates: [{ year: 1935, month: 8, day: 20 }],
        is_range_date: false,
      },
      {
        title: '关于日前战略方针之补充决定',
        authors: ['毛泽东'],
        page_start: 216,
        page_end: 218,
        dates: [{ year: 1935, month: 8, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致朱德、张国寿电',
        authors: ['毛泽东'],
        page_start: 219,
        page_end: 219,
        dates: [{ year: 1935, month: 9, day: 1 }],
        is_range_date: false,
      },
      {
        title: '红一方面军的工作方针',
        authors: ['毛泽东'],
        page_start: 220,
        page_end: 220,
        dates: [{ year: 1935, month: 9, day: 2 }],
        is_range_date: false,
      },
      {
        title: '左路军应改道北上叫',
        authors: ['毛泽东'],
        page_start: 221,
        page_end: 226,
        dates: [{ year: 1935, month: 9, day: 8 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局扩大会议上的讲话',
        authors: ['毛泽东'],
        page_start: 227,
        page_end: 228,
        dates: [{ year: 1935, month: 9, day: 12 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局扩大会议上的讲话',
        authors: ['毛泽东'],
        page_start: 229,
        page_end: 231,
        dates: [{ year: 1935, month: 9, day: 12 }],
        is_range_date: false,
      },
      {
        title: '消灭腊子口之敌的部署',
        authors: ['毛泽东'],
        page_start: 232,
        page_end: 232,
        dates: [{ year: 1935, month: 9, day: 16 }],
        is_range_date: false,
      },
      {
        title: '部队的行动部署和严整纪律问题',
        authors: ['毛泽东'],
        page_start: 233,
        page_end: 233,
        dates: [{ year: 1935, month: 9, day: 18 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局常委会上的讲话',
        authors: ['毛泽东'],
        page_start: 234,
        page_end: 234,
        dates: [{ year: 1935, month: 9, day: 20 }],
        is_range_date: false,
      },
      {
        title: '行动方针与任务的报告叫',
        authors: ['毛泽东'],
        page_start: 235,
        page_end: 235,
        dates: [{ year: 1935, month: 9, day: 20 }],
        is_range_date: false,
      },
      {
        title: '部队宿营位置及三日行动部署叫',
        authors: ['毛泽东'],
        page_start: 236,
        page_end: 236,
        dates: [{ year: 1935, month: 10, day: 2 }],
        is_range_date: false,
      },
      {
        title: '近日各纵队的工作',
        authors: ['毛泽东'],
        page_start: 237,
        page_end: 237,
        dates: [{ year: 1935, month: 10, day: 3 }],
        is_range_date: false,
      },
      {
        title: '日内无急于求战之必要',
        authors: ['毛泽东'],
        page_start: 238,
        page_end: 238,
        dates: [{ year: 1935, month: 10, day: 6 }],
        is_range_date: false,
      },
      {
        title: '陕甘支队近期行动部署叫',
        authors: ['毛泽东'],
        page_start: 239,
        page_end: 239,
        dates: [{ year: 1935, month: 10, day: 6 }],
        is_range_date: false,
      },
      {
        title: '通过洪德城环县时须做战斗准备',
        authors: ['毛泽东'],
        page_start: 240,
        page_end: 240,
        dates: [{ year: 1935, month: 10, day: 13 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 241,
        page_end: 241,
        dates: [{ year: 1935, month: 10, day: 14 }],
        is_range_date: false,
      },
      {
        title: '部队争取在吴起镇金汤镇集结休息',
        authors: ['毛泽东'],
        page_start: 242,
        page_end: 245,
        dates: [{ year: 1935, month: 10, day: 16 }],
        is_range_date: false,
      },
      {
        title: '拟在铁边城以东地区消灭追敌',
        authors: ['毛泽东'],
        page_start: 246,
        page_end: 246,
        dates: [{ year: 1935, month: 10, day: 17 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局常委会议上的讲话',
        authors: ['毛泽东'],
        page_start: 247,
        page_end: 247,
        dates: [{ year: 1935, month: 10, day: 18 }],
        is_range_date: false,
      },
      {
        title: '陕甘支队的行动部署叫',
        authors: ['毛泽东'],
        page_start: 248,
        page_end: 249,
        dates: [{ year: 1935, month: 10, day: 19 }],
        is_range_date: false,
      },
      {
        title: '致林彪、鼓荣臻电',
        authors: ['毛泽东'],
        page_start: 250,
        page_end: 250,
        dates: [{ year: 1935, month: 10, day: 21 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 251,
        page_end: 252,
        dates: [{ year: 1935, month: 10, day: 22 }],
        is_range_date: false,
      },
      {
        title: '在陕甘支队团以上干部会议上的讲话',
        authors: ['毛泽东'],
        page_start: 253,
        page_end: 253,
        dates: [{ year: 1935, month: 10, day: 25 }],
        is_range_date: false,
      },
      {
        title: '致朱德等电',
        authors: ['毛泽东'],
        page_start: 254,
        page_end: 254,
        dates: [{ year: 1935, month: 10, day: 27 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局常委会议上的讲话',
        authors: ['毛泽东'],
        page_start: 255,
        page_end: 255,
        dates: [{ year: 1935, month: 10, day: 27 }],
        is_range_date: false,
      },
      {
        title: '七律.长征',
        authors: ['毛泽东'],
        page_start: 256,
        page_end: 276,
        dates: [{ year: 1935, month: 10 }],
        is_range_date: false,
      },
      {
        title: '念奴娇·昆仑',
        authors: ['毛泽东'],
        page_start: 277,
        page_end: 285,
        dates: [{ year: 1935, month: 10 }],
        is_range_date: false,
      },
      {
        title: '清平乐·六盘山世',
        authors: ['毛泽东'],
        page_start: 286,
        page_end: 291,
        dates: [{ year: 1935, month: 10 }],
        is_range_date: false,
      },
      {
        title: '六言诗以给彭德怀同志',
        authors: ['毛泽东'],
        page_start: 292,
        page_end: 293,
        dates: [{ year: 1935, month: 10 }],
        is_range_date: false,
      },
    ],
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives8/maoquanji7-2.pdf',
};
