export default {
  entity: {
    id: 'maoquanji41',
    name: '毛泽东全集第41卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives0/main/maoquanji41.pdf',
  },
  parser_option: {
    ext: 'pdf',
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
    page_limits: [],
    articles: [
      {
        page_start: 27,
        page_end: 28,
        title: '关于调查处理乡村干部中的打骂人问题给吴芝圃等的信',
        dates: [{ year: 1958, month: 11, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 29,
        page_end: 33,
        title: '在武汉和各协作区主任的讲话（一）',
        dates: [{ year: 1958, month: 11, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 34,
        page_end: 35,
        title: '中华人民共和国国防部三告台湾同胞书',
        dates: [{ year: 1958, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 36,
        page_end: 37,
        title: '在一份摘录斯大林论述过渡到共产主义三个基本条件的材料上的批语',
        dates: [{ year: 1958, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 38,
        page_end: 38,
        title: '为印发宦乡报告重拟的标题和批语',
        dates: [{ year: 1958, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 39,
        page_end: 40,
        title: '写在《参考资料》上的刘禹锡的一首诗',
        dates: [{ year: 1958, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 41,
        page_end: 42,
        title: '对李普曼《苏联的挑战》一文的批语和批注',
        dates: [{ year: 1958, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 43,
        page_end: 43,
        title: '为印发杜勒斯批评我国人民公社言论重拟的标题（提要）和批语',
        dates: [{ year: 1958, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 44,
        page_end: 45,
        title: '为印发杜勒斯演说重拟的标题、提要和批语',
        dates: [{ year: 1958, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 46,
        page_end: 47,
        title: '为印发《参考资料》的一则电讯稿重拟的标题（提要）和批语',
        dates: [{ year: 1958, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 48,
        page_end: 48,
        title: '对《人民日报》的两段指示',
        dates: [{ year: 1958, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 49,
        page_end: 49,
        title: '接见金日成时的谈话',
        dates: [{ year: 1958, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 50,
        page_end: 52,
        title: '关于帝国主义和一切反动派是不是真老虎的问题',
        dates: [{ year: 1958, month: 12, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 55,
        page_end: 56,
        title: '关于注意各地发生强迫命令、违法乱纪问题的批语',
        dates: [{ year: 1958, month: 12, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 57,
        page_end: 58,
        title: '为印发南越政治、军事情况动态而拟写的标题和批语',
        dates: [{ year: 1958, month: 12, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 59,
        page_end: 59,
        title: '为红线女题词',
        dates: [{ year: 1958, month: 12, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 61,
        page_end: 61,
        title: '关于我国决定同苏丹建交的复电',
        dates: [{ year: 1958, month: 12, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 62,
        page_end: 62,
        title: '祝贺加涅夫当选为保加利亚人民共和国国民议会主席团主席的电报',
        dates: [{ year: 1958, month: 12, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 63,
        page_end: 64,
        title: '对中共中央关于一九五九年国民经济计划的决议草稿的批语和修改',
        dates: [{ year: 1958, month: 12, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 65,
        page_end: 65,
        title: '对河北省委关于农村人民公社问题报告的批语',
        dates: [{ year: 1958, month: 12, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 66,
        page_end: 70,
        title: '关于当前宣传工作中应注意的几个问题的指示',
        dates: [{ year: 1958, month: 12, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 72,
        page_end: 72,
        title: '印发《外国报刊关于中国的反应》中三篇文章的批语',
        dates: [{ year: 1958, month: 12, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 73,
        page_end: 75,
        title: '为印发《张鲁传》写的批语',
        dates: [
          { year: 1958, month: 12, day: 7 },
          { year: 1958, month: 12, day: 10 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 76,
        page_end: 77,
        title: '对农业部党组关于土壤普查鉴定工作现场会情况报告的批语',
        dates: [{ year: 1958, month: 12, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 78,
        page_end: 80,
        title: '对同意毛泽东不作下届国家主席候选人的决定稿的批语和修改',
        dates: [
          { year: 1958, month: 12, day: 8 },
          { year: 1958, month: 12, day: 9 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 81,
        page_end: 86,
        title: '在中共八届六中全会上的讲话提纲',
        dates: [{ year: 1958, month: 12, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 87,
        page_end: 97,
        title: '在八届六中全会上的讲话',
        dates: [{ year: 1958, month: 12, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 102,
        page_end: 104,
        title: '在武汉和各协作区主任的讲话（二）',
        dates: [{ year: 1958, month: 12, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 105,
        page_end: 106,
        title: '对八届六中全会公报稿的批语和修改',
        dates: [{ year: 1958, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 107,
        page_end: 107,
        title: '对赫鲁晓夫在苏共中央全会上的报告的批语',
        dates: [{ year: 1958, month: 12, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 108,
        page_end: 108,
        title: '复霍查电',
        dates: [{ year: 1958, month: 12, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 109,
        page_end: 114,
        title: '在《毛主席诗词十九首》上的批注',
        dates: [{ year: 1958, month: 12, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 115,
        page_end: 116,
        title: '关于端正方向，争取一切可能争取的知识分子的批语',
        dates: [{ year: 1958, month: 12, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 117,
        page_end: 124,
        title: '接见参加全军政工会议的各军区负责同志时的谈话',
        dates: [{ year: 1958, month: 12, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 131,
        page_end: 131,
        title: '祝贺苏丹独立纪念日的电报',
        dates: [{ year: 1958, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 132,
        page_end: 134,
        title: '在共同社、英新处关于人民公社若干问题的决议的两篇评论上的批注',
        dates: [{ year: 1958, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 135,
        page_end: 154,
        title: '读斯大林《苏联社会主义经济问题》的批注',
        dates: [{ year: 1958 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 155,
        page_end: 155,
        title: '对大跃进报道的指示',
        dates: [{ year: 1958 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 156,
        page_end: 156,
        title: '对地方党委领导新闻事业的指示',
        dates: [{ year: 1958 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 157,
        page_end: 157,
        title: '关于造船方针的指示',
        dates: [{ year: 1958 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 158,
        page_end: 158,
        title: '为中央新闻纪录电影制片厂题名',
        dates: [{ year: 1958 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 159,
        page_end: 159,
        title: '四言韵语·养生十六字诀',
        dates: [{ year: 1958 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 161,
        page_end: 161,
        title: '七绝·刘',
        dates: [{ year: 1958 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 162,
        page_end: 162,
        title: '七绝·改梅白《夜登重庆枇杷山》',
        dates: [{ year: 1958 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 163,
        page_end: 163,
        title: '为《鲁山报》题写报头',
        dates: [{ year: 1958 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 165,
        page_end: 165,
        title: '祝贺缅甸联邦国庆的电报',
        dates: [{ year: 1959, month: 1, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 166,
        page_end: 167,
        title: '对福斯特来信的批语和复信',
        dates: [
          { year: 1959, month: 1, day: 11 },
          { year: 1959, month: 1, day: 17 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 168,
        page_end: 169,
        title: '对驻苏使馆关于中苏关系中一些问题的处理意见的批语',
        dates: [{ year: 1959, month: 1, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 170,
        page_end: 170,
        title: '给黄炎培的信',
        dates: [{ year: 1959, month: 1, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 171,
        page_end: 172,
        title: '对中央关于目前报刊宣传工作的通知稿的批语和修改',
        dates: [{ year: 1959, month: 1, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 173,
        page_end: 174,
        title: '对中央关于动员青壮年入藏屯垦生产的指示稿的批语和修改',
        dates: [{ year: 1959, month: 1, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 175,
        page_end: 175,
        title: '在西藏军区关于边坝等地叛匪活动的电报上的批语',
        dates: [{ year: 1959, month: 1, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 176,
        page_end: 176,
        title: '对《人民日报》社论稿《认真贯彻党的中医政策》的批语',
        dates: [{ year: 1959, month: 1, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 177,
        page_end: 179,
        title: '致苏共二十一大贺词',
        dates: [{ year: 1959, month: 1, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 180,
        page_end: 180,
        title: '印发陈伯达关于人民公社生产方面几个问题的来信的批语',
        dates: [{ year: 1959, month: 1, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 181,
        page_end: 181,
        title: '对新华社关于广东新会县人民公社劳动效率下降的报道的批语',
        dates: [{ year: 1959, month: 1, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 182,
        page_end: 182,
        title: '吾对新华社关于内地对香港副食品供应量锐减的报道的批语',
        dates: [{ year: 1959, month: 1, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 183,
        page_end: 183,
        title: '对新华社关于四川省委加强工业战线工作的报道的批语',
        dates: [{ year: 1959, month: 1, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 184,
        page_end: 184,
        title: '印发谭震林关于目前农村情况和农业生产问题的报告的批语',
        dates: [{ year: 1959, month: 1, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 185,
        page_end: 185,
        title: '祝贺印度共和国国庆的电报',
        dates: [{ year: 1959, month: 1, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 187,
        page_end: 187,
        title: '对中央农村工作部关于全国农村工作部长会议报告的批语',
        dates: [{ year: 1959, month: 1, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 188,
        page_end: 188,
        title: '接见德意志民主共和国政府代表团的谈话（摘录）',
        dates: [{ year: 1959, month: 1, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 189,
        page_end: 190,
        title: '对驻苏使馆关于约夫楚克若干哲学观点的报告的批语',
        dates: [{ year: 1959, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 191,
        page_end: 191,
        title: '在关于张国焘最近情况简报上的批语',
        dates: [{ year: 1959, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 192,
        page_end: 195,
        title: '关于谈哲学等问题给各省市自治区党委第一书记的信',
        dates: [{ year: 1959, month: 2, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 196,
        page_end: 203,
        title: '在省市委书记会上的讲话',
        dates: [{ year: 1959, month: 2, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 204,
        page_end: 204,
        title: '祝贺锡兰国庆的电报',
        dates: [{ year: 1959, month: 2, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 205,
        page_end: 205,
        title: '对驻英代办处关于英国同美、法、西德等国矛盾发展的初步总结的批语',
        dates: [{ year: 1959, month: 2, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 206,
        page_end: 208,
        title: '对中央外事小组文件和中央转发这一文件的指示稿的批语和修改',
        dates: [{ year: 1959, month: 2, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 210,
        page_end: 211,
        title: '对中央关于在对外关系中切实纠正骄傲现象的指示稿的批语和修改',
        dates: [{ year: 1959, month: 2, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 212,
        page_end: 216,
        title: '马列主义基本原理至今未变，个别结论可以改变',
        dates: [{ year: 1959, month: 2, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 217,
        page_end: 217,
        title: '接受罗马尼亚新任驻华大使查哈勒斯库呈递国书时的答词',
        dates: [{ year: 1959, month: 2, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 218,
        page_end: 218,
        title: '祝贺尼泊尔国庆的电报',
        dates: [{ year: 1959, month: 2, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 219,
        page_end: 222,
        title: '两次失败使我们学会了打仗',
        dates: [{ year: 1959, month: 2, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 223,
        page_end: 223,
        title: '在西藏武装叛乱情况简报上的批语',
        dates: [{ year: 1959, month: 2, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 224,
        page_end: 225,
        title: '对总参作战部关于平叛情况报告的批语和修改',
        dates: [{ year: 1959, month: 2, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 226,
        page_end: 226,
        title: '在关于英国各界对我撤销出口合同的反应报告上的批语',
        dates: [{ year: 1959, month: 2, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 227,
        page_end: 227,
        title: '对政协第三届全国委员会委员名单草案和说明的批语',
        dates: [{ year: 1959, month: 2, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 228,
        page_end: 231,
        title: '和新、洛、许、信四个地委座谈时的谈话',
        dates: [{ year: 1959, month: 2, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 232,
        page_end: 233,
        title: '非洲当前的任务是反对帝国主义',
        dates: [{ year: 1959, month: 2, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 234,
        page_end: 234,
        title: '祝贺阿拉伯联合共和国国庆的电报',
        dates: [{ year: 1959, month: 2, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 235,
        page_end: 237,
        title: '中央批转一个重要文件',
        dates: [{ year: 1959, month: 2, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 238,
        page_end: 240,
        title:
          '对《陈毅外长答新华社记者问，驳斥杜勒斯诬蔑中国的澜言》一文的批语和修改',
        dates: [{ year: 1959, month: 2, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 241,
        page_end: 242,
        title: '关于整顿人民公社问题给刘子厚的信',
        dates: [
          { year: 1959, month: 2, day: 24 },
          { year: 1959, month: 2, day: 27 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 243,
        page_end: 246,
        title: '在郑州会议上的讲话提纲',
        dates: [{ year: 1959, month: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 247,
        page_end: 256,
        title: '在郑州会议上的讲话（一）',
        dates: [{ year: 1959, month: 2, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 257,
        page_end: 264,
        title: '在郑州会议上的讲话（二）',
        dates: [{ year: 1959, month: 2, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 265,
        page_end: 273,
        title: '在郑州会议上的讲话（三）',
        dates: [{ year: 1959, month: 2, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 274,
        page_end: 276,
        title: '对山西省委关于整顿和巩固人民公社的决议的批语和注文',
        dates: [{ year: 1959, month: 2, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 277,
        page_end: 278,
        title: '关于目前农村集体所有制形式问题的批语',
        dates: [{ year: 1959, month: 2, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 279,
        page_end: 279,
        title: '在《杜勒斯谈如何抵挡东风》一文上的批语',
        dates: [{ year: 1959, month: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 280,
        page_end: 280,
        title: '在河南九县讨论郑州会议讲话情况报告上的批语',
        dates: [{ year: 1959, month: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 281,
        page_end: 286,
        title: '在郑州会议上的讲话（四）',
        dates: [{ year: 1959, month: 3, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 287,
        page_end: 291,
        title: '郑州会议期间给刘少奇、邓小平等的三封信',
        dates: [
          { year: 1959, month: 3, day: 1 },
          { year: 1959, month: 3, day: 2 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 292,
        page_end: 292,
        title: '祝贺柬埔寨国王生日和国庆的电报',
        dates: [{ year: 1959, month: 3, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 293,
        page_end: 301,
        title: '和拉丁美洲一些国家共产党领导人的谈话',
        dates: [{ year: 1959, month: 3, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 302,
        page_end: 311,
        title: '在郑州会议上的讲话（五）',
        dates: [{ year: 1959, month: 3, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 312,
        page_end: 312,
        title: '郑州会议纪要',
        dates: [{ year: 1959, month: 3, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 313,
        page_end: 314,
        title: '在郑州会议上的讲话（六）',
        dates: [{ year: 1959, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 315,
        page_end: 316,
        title: '关于传达湖北省委贯彻郑州会议精神的情况报告的两个批语',
        dates: [{ year: 1959, month: 3, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 317,
        page_end: 318,
        title:
          '对河南省六级干部会议关于人民公社若干问题讨论情况的综合材料的批语',
        dates: [{ year: 1959, month: 3, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 319,
        page_end: 321,
        title: '党内通信',
        dates: [{ year: 1959, month: 3, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 324,
        page_end: 324,
        title: '介绍安徽的经验',
        dates: [{ year: 1959, month: 3, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 325,
        page_end: 326,
        title: '关于湖南报告的意见',
        dates: [{ year: 1959, month: 3, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 327,
        page_end: 327,
        title: '介绍广东的经验',
        dates: [{ year: 1959, month: 3, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 329,
        page_end: 329,
        title: '祝贺丹麦国王生日和国庆的电报',
        dates: [{ year: 1959, month: 3, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 330,
        page_end: 330,
        title: '接受缅甸联邦新任驻华大使貌貌觉温呈递国书时的答词',
        dates: [{ year: 1959, month: 3, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 331,
        page_end: 332,
        title: '转发广东省委关于贯彻郑州会议精神的报告的批语',
        dates: [{ year: 1959, month: 3, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 339,
        page_end: 341,
        title: '党内通信',
        dates: [{ year: 1959, month: 3, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 342,
        page_end: 343,
        title: '在安徽省六级干部会议情况简报上的批语',
        dates: [{ year: 1959, month: 3, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 344,
        page_end: 344,
        title: '关于注意给达赖复信问题的批语',
        dates: [{ year: 1959, month: 3, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 345,
        page_end: 346,
        title: '转发湖北省委关于人民公社问题的决议草案等材料的批语',
        dates: [{ year: 1959, month: 3, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 347,
        page_end: 348,
        title: '关于召开县以下各级干部会议等问题给王任重的两封信',
        dates: [{ year: 1959, month: 3, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 349,
        page_end: 351,
        title: '党内通信',
        dates: [{ year: 1959, month: 3, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 352,
        page_end: 352,
        title: '转发河北省委关于六级干部会议情况报告的批语',
        dates: [{ year: 1959, month: 3, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 353,
        page_end: 354,
        title: '转发《山东的经验》的批语',
        dates: [{ year: 1959, month: 3, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 355,
        page_end: 357,
        title: '西太平洋要西太平洋国家自己来管',
        dates: [{ year: 1959, month: 3, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 359,
        page_end: 359,
        title: '转发河南荥阳县四级干部大会经验的批语',
        dates: [{ year: 1959, month: 3, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 363,
        page_end: 363,
        title: '祝贺突尼斯独立纪念日的电报',
        dates: [{ year: 1959, month: 3, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 364,
        page_end: 365,
        title: '毛泽东等纪念匈牙利苏维埃共和国四十周年的电报',
        dates: [{ year: 1959, month: 3, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 366,
        page_end: 367,
        title: '对《四川的经验》的批语',
        dates: [{ year: 1959, month: 3, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 368,
        page_end: 369,
        title: '介绍河南的经验',
        dates: [
          { year: 1959, month: 3, day: 19 },
          { year: 1959, month: 3, day: 24 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 370,
        page_end: 371,
        title: '和江西省委和部分地、市委负责人谈话提纲',
        dates: [{ year: 1959, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 372,
        page_end: 373,
        title: '关于人民公社若干问题的提纲',
        dates: [{ year: 1959, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 374,
        page_end: 374,
        title: '关于要少讲空话多讲办法的批语',
        dates: [{ year: 1959, month: 3, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 375,
        page_end: 375,
        title: '对《山西省委的经验》的批语',
        dates: [{ year: 1959, month: 3, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 376,
        page_end: 376,
        title: '对河北省委关于贯彻郑州会议精神的十二条措施的批语',
        dates: [{ year: 1959, month: 3, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 377,
        page_end: 377,
        title: '祝贺巴基斯坦国庆的电报',
        dates: [{ year: 1959, month: 3, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 378,
        page_end: 379,
        title: '关于社会主义集体所有制过渡问题的批注',
        dates: [{ year: 1959, month: 3, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 380,
        page_end: 380,
        title: '转发《四川的经验》的批语',
        dates: [{ year: 1959, month: 3, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 381,
        page_end: 381,
        title: '转发《福建的经验》的批语',
        dates: [{ year: 1959, month: 3, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 382,
        page_end: 383,
        title: '对浙江省委关于整顿人民公社的十项规定的批语',
        dates: [{ year: 1959, month: 3, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 384,
        page_end: 384,
        title: '在上海会议上的讲话提纲',
        dates: [{ year: 1959, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 385,
        page_end: 385,
        title: '关于请上海会议各同志阅读薄一波发言稿的批语',
        dates: [{ year: 1959, month: 3, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 386,
        page_end: 387,
        title: '介绍安徽的十项规定',
        dates: [{ year: 1959, month: 3, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 388,
        page_end: 391,
        title: '对新华社关于西藏叛乱事件的公报稿的批语和修改',
        dates: [{ year: 1959, month: 3, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 392,
        page_end: 393,
        title: '党内通信',
        dates: [{ year: 1959, month: 3, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 394,
        page_end: 394,
        title: '对人民银行总行党组关于收回农业贷款中发生问题的检查报告的批语',
        dates: [{ year: 1959, month: 3, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 395,
        page_end: 398,
        title: '关于人民公社化运动中的旧账一般要算等问题的批注',
        dates: [{ year: 1959, month: 3, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 399,
        page_end: 402,
        title: '价值法则是一个伟大的学校',
        dates: [
          { year: 1959, month: 3 },
          { year: 1959, month: 4 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 403,
        page_end: 404,
        title: '关于同意董必武辞去现职改换工作的批语',
        dates: [{ year: 1959, month: 3, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 405,
        page_end: 405,
        title:
          '对班禅额尔德尼拥护国务院解散西藏地方政府和平息叛乱命令的电报的批语',
        dates: [{ year: 1959, month: 3, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 406,
        page_end: 406,
        title: '关于改变集体所有制体制的几条原则',
        dates: [{ year: 1959, month: 3, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 407,
        page_end: 408,
        title: '第一批反映',
        dates: [{ year: 1959, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 409,
        page_end: 409,
        title: '在上海会议上的讲话（摘录）',
        dates: [{ year: 1959, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 410,
        page_end: 412,
        title: '在上海会议上的讲话和插话',
        dates: [
          { year: 1959, month: 3 },
          { year: 1959, month: 4 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 413,
        page_end: 415,
        title: '对上海会议纪要修正稿的批语和修改',
        dates: [{ year: 1959, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 416,
        page_end: 418,
        title: '介绍麻城的经验',
        dates: [
          { year: 1959, month: 4, day: 2 },
          { year: 1959, month: 4, day: 3 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 419,
        page_end: 420,
        title: '毛泽东等祝贺牙利解放十四周年的电报',
        dates: [{ year: 1959, month: 4, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 421,
        page_end: 421,
        title: '关于是否担任政协名誉主席问题的批语',
        dates: [{ year: 1959, month: 4, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 422,
        page_end: 423,
        title: '在中共八届七中全会上的讲话提纲',
        dates: [{ year: 1959, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 424,
        page_end: 424,
        title: '生产增长速度有高有低，是波浪式的前进',
        dates: [{ year: 1959, month: 4, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 425,
        page_end: 426,
        title: '给汪锋的信',
        dates: [{ year: 1959, month: 4, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 427,
        page_end: 428,
        title: '对印度新闻社关于西藏叛乱的两篇报道的批语',
        dates: [{ year: 1959, month: 4, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 429,
        page_end: 429,
        title: '关于发表国外对西藏叛乱反应的材料的批语',
        dates: [{ year: 1959, month: 4, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 430,
        page_end: 437,
        title: '关于西藏平叛',
        dates: [{ year: 1959, month: 4, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 438,
        page_end: 439,
        title: '接受越南新任驻华大使陈子平呈递国书时的答词',
        dates: [{ year: 1959, month: 4, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 440,
        page_end: 441,
        title: '关于政府工作报告稿的两个批语',
        dates: [
          { year: 1959, month: 4, day: 15 },
          { year: 1959, month: 4, day: 16 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 442,
        page_end: 443,
        title: '中央转发吴芝圃关于分期分批召开社员代表大会等问题的报告的批语',
        dates: [{ year: 1959, month: 4, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 444,
        page_end: 444,
        title: '关于解决春荒缺粮问题的批语',
        dates: [{ year: 1959, month: 4, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 449,
        page_end: 449,
        title: '转发周小舟关于处理少数违法乱纪干部的意见的批语',
        dates: [{ year: 1959, month: 4, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 450,
        page_end: 452,
        title: '和意大利共产党代表团的谈话',
        dates: [{ year: 1959, month: 4, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 453,
        page_end: 454,
        title: '工业界的新事',
        dates: [{ year: 1959, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 457,
        page_end: 457,
        title: '对陶铸关于广东召开公社代表大会部署的报告的批语',
        dates: [{ year: 1959, month: 4, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 458,
        page_end: 459,
        title: '中央转发江苏省委关于贯彻八届七中全会精神的报告的批语',
        dates: [{ year: 1959, month: 4, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 460,
        page_end: 460,
        title: '在陈关于一九五九年常规武器试制任务安排情况报告上的批语',
        dates: [{ year: 1959, month: 4, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 461,
        page_end: 461,
        title: '在李先念关于吕泗洋风暴事故后最近情况报告上的批语',
        dates: [{ year: 1959, month: 4, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 462,
        page_end: 462,
        title: '关于调演豫剧《破洪州》给周恩来的信',
        dates: [{ year: 1959, month: 4, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 464,
        page_end: 464,
        title: '为阅看《关于（三国演义》》前两部分给林克的批语',
        dates: [{ year: 1959, month: 4, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 465,
        page_end: 467,
        title: '关于西藏叛乱事件的宣传报道问题的批语',
        dates: [{ year: 1959, month: 4, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 468,
        page_end: 469,
        title:
          '对外交部就印度发生侮辱我国元首事件给驻印使馆的指示稿的批语和修改',
        dates: [{ year: 1959, month: 4, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 470,
        page_end: 470,
        title: '关于妥善安排渡过春荒的批语',
        dates: [{ year: 1959, month: 4, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 471,
        page_end: 472,
        title: '对全国人大二届一次会议关于西藏问题决议稿的批语',
        dates: [{ year: 1959, month: 4, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 473,
        page_end: 475,
        title: '西藏人民群众拥护人民解放军平叛，亲如家人',
        dates: [{ year: 1959, month: 4, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 476,
        page_end: 476,
        title: '转发西藏工委关于西藏各阶层最近动态的报告的批语',
        dates: [{ year: 1959, month: 4, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 477,
        page_end: 477,
        title:
          '对《光明日报》发表《落后、黑暗、反动、残酷的西藏社会制度》资料的批语',
        dates: [{ year: 1959, month: 4, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 478,
        page_end: 483,
        title: '党内通信',
        dates: [
          { year: 1959, month: 4, day: 29 },
          { year: 1959, month: 5, day: 2 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 484,
        page_end: 492,
        title: '工作方法十六条',
        dates: [{ year: 1959, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 493,
        page_end: 494,
        title: '党内通信',
        dates: [{ year: 1959, month: 5, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 495,
        page_end: 496,
        title: '关于反击挪威报纸侮辱我国领袖问题的批语',
        dates: [{ year: 1959, month: 5, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 497,
        page_end: 497,
        title: '关于注意逃缅蒋军配合西藏叛乱在我边境扩大骚扰的批语',
        dates: [{ year: 1959, month: 5, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 498,
        page_end: 500,
        title: '接见苏联等十一国代表团和驻华使节时的谈话',
        dates: [{ year: 1959, month: 5, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 501,
        page_end: 502,
        title: '对中央关于农业的五条紧急指示稿的批语和修改',
        dates: [{ year: 1959, month: 5, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 508,
        page_end: 514,
        title: '西藏平叛后的有关方针政策',
        dates: [{ year: 1959, month: 5, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 515,
        page_end: 516,
        title:
          '对中央关于给社员分配自留地以利发展猪鸡鹅鸭问题的指示稿的批语和修改',
        dates: [{ year: 1959, month: 5, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 517,
        page_end: 518,
        title: '毛泽东等祝贺捷克斯洛伐克国庆的电报',
        dates: [{ year: 1959, month: 5, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 519,
        page_end: 519,
        title:
          '对中央转发湖北等省省委关于人民公社和农村工作情况报告的指示稿的批语',
        dates: [{ year: 1959, month: 5, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 520,
        page_end: 520,
        title: '对驻印使馆关于孟买发生侮辱我国元首事件的处理意见的批语',
        dates: [{ year: 1959, month: 5, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 521,
        page_end: 522,
        title: '中央转发湖北省委关于麻城县开展算账运动的情况报告的批语',
        dates: [
          { year: 1959, month: 5, day: 9 },
          { year: 1959, month: 5, day: 11 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 523,
        page_end: 526,
        title: '关于西藏问题和台湾问题',
        dates: [{ year: 1959, month: 5, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 528,
        page_end: 528,
        title: '给周世钊的信',
        dates: [{ year: 1959, month: 5, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 529,
        page_end: 530,
        title: '中央转发孝感地委关于贯彻农业方面六个问题指示的情况报告的批语',
        dates: [{ year: 1959, month: 5, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 531,
        page_end: 532,
        title: '中央转发山东省委关于分配自留地的规定的批语',
        dates: [{ year: 1959, month: 5, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
    ],
  },
  parser_id: 'automation',
  path: '/archives0/maoquanji41.pdf',
};
