export default {
  entity: {
    id: 'maoquanji18',
    name: '毛泽东全集第18卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives8/main/maoquanji18.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中共中央关于何时打败日本问题的宣传工作的指示',
        authors: ['毛泽东'],
        page_start: 25,
        page_end: 26,
        dates: [{ year: 1943, month: 5, day: 1 }],
        is_range_date: false,
      },
      {
        title: '在志丹陵园红星纪念塔上的题词',
        authors: ['毛泽东'],
        page_start: 27,
        page_end: 28,
        dates: [{ year: 1943, month: 5, day: 2 }],
        is_range_date: false,
      },
      {
        title: '给贸拓夫的信',
        authors: ['毛泽东'],
        page_start: 29,
        page_end: 29,
        dates: [{ year: 1943, month: 5, day: 4 }],
        is_range_date: false,
      },
      {
        title: '复周恩来等电',
        authors: ['毛泽东'],
        page_start: 30,
        page_end: 30,
        dates: [{ year: 1943, month: 5, day: 8 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 31,
        page_end: 31,
        dates: [{ year: 1943, month: 5, day: 18 }],
        is_range_date: false,
      },
      {
        title: '复周恩来电',
        authors: ['毛泽东'],
        page_start: 32,
        page_end: 32,
        dates: [{ year: 1943, month: 5, day: 19 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 33,
        page_end: 33,
        dates: [{ year: 1943, month: 5, day: 21 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 34,
        page_end: 34,
        dates: [{ year: 1943, month: 5, day: 24 }],
        is_range_date: false,
      },
      {
        title: '关于共产国际解散问题的报告',
        authors: ['毛泽东'],
        page_start: 35,
        page_end: 39,
        dates: [{ year: 1943, month: 5, day: 26 }],
        is_range_date: false,
      },
      {
        title:
          '中国共产党中央委员会关于共产国际执委主席团提议解散共产国际的决定',
        authors: ['毛泽东'],
        page_start: 40,
        page_end: 43,
        dates: [{ year: 1943, month: 5, day: 26 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 44,
        page_end: 44,
        dates: [{ year: 1943, month: 5, day: 26 }],
        is_range_date: false,
      },
      {
        title: '在今后三年中应力求巩固，屹立不败',
        authors: ['毛泽东'],
        page_start: 45,
        page_end: 46,
        dates: [{ year: 1943, month: 6, day: 1 }],
        is_range_date: false,
      },
      {
        title: '关于领导方法的若干问题',
        authors: ['毛泽东'],
        page_start: 47,
        page_end: 52,
        dates: [{ year: 1943, month: 6, day: 1 }],
        is_range_date: false,
      },
      {
        title: '为抗大七周年题词',
        authors: ['毛泽东'],
        page_start: 53,
        page_end: 54,
        dates: [{ year: 1943, month: 6, day: 1 }],
        is_range_date: false,
      },
      {
        title: '给周小舟的信',
        authors: ['毛泽东'],
        page_start: 55,
        page_end: 55,
        dates: [{ year: 1943, month: 6, day: 1 }],
        is_range_date: false,
      },
      {
        title: '复周恩来电',
        authors: ['毛泽东'],
        page_start: 56,
        page_end: 56,
        dates: [{ year: 1943, month: 6, day: 4 }],
        is_range_date: false,
      },
      {
        title: '给彭德怀"的信',
        authors: ['毛泽东'],
        page_start: 57,
        page_end: 58,
        dates: [{ year: 1943, month: 6, day: 6 }],
        is_range_date: false,
      },
      {
        title: '紧紧抓住整风这个关键',
        authors: ['毛泽东'],
        page_start: 59,
        page_end: 60,
        dates: [{ year: 1943, month: 6, day: 6 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 61,
        page_end: 61,
        dates: [{ year: 1943, month: 6, day: 9 }],
        is_range_date: false,
      },
      {
        title: '致周恩来、林彪电',
        authors: ['毛泽东'],
        page_start: 62,
        page_end: 62,
        dates: [{ year: 1943, month: 6, day: 15 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 63,
        page_end: 64,
        dates: [{ year: 1943, month: 6, day: 16 }],
        is_range_date: false,
      },
      {
        title: '英勇斗争的二十二年',
        authors: ['毛泽东'],
        page_start: 65,
        page_end: 71,
        dates: [{ year: 1943, month: 7, day: 1 }],
        is_range_date: false,
      },
      {
        title: '防好工作的两条路线',
        authors: ['毛泽东'],
        page_start: 72,
        page_end: 72,
        dates: [{ year: 1943, month: 7, day: 1 }],
        is_range_date: false,
      },
      {
        title: '中共中央为抗战六周年纪念宣言叫',
        authors: ['毛泽东'],
        page_start: 73,
        page_end: 84,
        dates: [{ year: 1943, month: 7, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致周子健电',
        authors: ['毛泽东'],
        page_start: 85,
        page_end: 85,
        dates: [{ year: 1943, month: 7, day: 3 }],
        is_range_date: false,
      },
      {
        title: '立即行动，制止内战',
        authors: ['毛泽东'],
        page_start: 86,
        page_end: 86,
        dates: [{ year: 1943, month: 7, day: 4 }],
        is_range_date: false,
      },
      {
        title: '致周子健电',
        authors: ['毛泽东'],
        page_start: 87,
        page_end: 87,
        dates: [{ year: 1943, month: 7, day: 4 }],
        is_range_date: false,
      },
      {
        title: '致董必武电',
        authors: ['毛泽东'],
        page_start: 88,
        page_end: 88,
        dates: [{ year: 1943, month: 7, day: 6 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 89,
        page_end: 89,
        dates: [{ year: 1943, month: 7, day: 7 }],
        is_range_date: false,
      },
      {
        title: '致周子健电',
        authors: ['毛泽东'],
        page_start: 90,
        page_end: 90,
        dates: [{ year: 1943, month: 7, day: 7 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 91,
        page_end: 91,
        dates: [{ year: 1943, month: 7, day: 7 }],
        is_range_date: false,
      },
      {
        title: '准备对付蒋介石进攻边区的军事部署叫',
        authors: ['毛泽东'],
        page_start: 92,
        page_end: 92,
        dates: [{ year: 1943, month: 7, day: 9 }],
        is_range_date: false,
      },
      {
        title: '复周恩来、林彪电',
        authors: ['毛泽东'],
        page_start: 93,
        page_end: 93,
        dates: [{ year: 1943, month: 7, day: 9 }],
        is_range_date: false,
      },
      {
        title: '致周恩来、林彪电',
        authors: ['毛泽东'],
        page_start: 94,
        page_end: 94,
        dates: [{ year: 1943, month: 7, day: 10 }],
        is_range_date: false,
      },
      {
        title: '中共“七七”宣言在重庆被扣',
        authors: ['毛泽东'],
        page_start: 95,
        page_end: 97,
        dates: [{ year: 1943, month: 7, day: 11 }],
        is_range_date: false,
      },
      {
        title: '质问国民党',
        authors: ['毛泽东'],
        page_start: 98,
        page_end: 104,
        dates: [{ year: 1943, month: 7, day: 12 }],
        is_range_date: false,
      },
      {
        title: '中国政治黑暗，抗战不力，英美盟邦大不满意',
        authors: ['毛泽东'],
        page_start: 105,
        page_end: 107,
        dates: [{ year: 1943, month: 7, day: 12 }],
        is_range_date: false,
      },
      {
        title: '关于在敌后抓紧实行六大政策的指示',
        authors: ['毛泽东'],
        page_start: 108,
        page_end: 108,
        dates: [{ year: 1943, month: 7, day: 12 }],
        is_range_date: false,
      },
      {
        title: '复彭德怀电',
        authors: ['毛泽东'],
        page_start: 109,
        page_end: 109,
        dates: [{ year: 1943, month: 7, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致景荣臻等电',
        authors: ['毛泽东'],
        page_start: 110,
        page_end: 110,
        dates: [{ year: 1943, month: 7, day: 12 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 111,
        page_end: 112,
        dates: [{ year: 1943, month: 7, day: 13 }],
        is_range_date: false,
      },
      {
        title: '致董必武电',
        authors: ['毛泽东'],
        page_start: 113,
        page_end: 113,
        dates: [{ year: 1943, month: 7, day: 13 }],
        is_range_date: false,
      },
      {
        title: '致周子健电',
        authors: ['毛泽东'],
        page_start: 114,
        page_end: 114,
        dates: [{ year: 1943, month: 7, day: 13 }],
        is_range_date: false,
      },
      {
        title: '复山东分局电',
        authors: ['毛泽东'],
        page_start: 115,
        page_end: 115,
        dates: [{ year: 1943, month: 7, day: 15 }],
        is_range_date: false,
      },
      {
        title: '致朱瑞电',
        authors: ['毛泽东'],
        page_start: 116,
        page_end: 116,
        dates: [{ year: 1943, month: 7, day: 15 }],
        is_range_date: false,
      },
      {
        title: '给博古、陆定一的信',
        authors: ['毛泽东'],
        page_start: 117,
        page_end: 117,
        dates: [{ year: 1943, month: 7, day: 19 }],
        is_range_date: false,
      },
      {
        title: '关于公布《评（中国之命运）》一文',
        authors: ['毛泽东'],
        page_start: 118,
        page_end: 119,
        dates: [{ year: 1943, month: 7, day: 21 }],
        is_range_date: false,
      },
      {
        title: '给林伯渠“的信',
        authors: ['毛泽东'],
        page_start: 120,
        page_end: 120,
        dates: [{ year: 1943, month: 7, day: 24 }],
        is_range_date: false,
      },
      {
        title: '关于审干的九条方针和在敌后的八项政策',
        authors: ['毛泽东'],
        page_start: 121,
        page_end: 123,
        dates: [{ year: 1943, month: 7, day: 30 }],
        is_range_date: false,
      },
      {
        title: '和袁任远的谈话',
        authors: ['毛泽东'],
        page_start: 124,
        page_end: 129,
        dates: [{ year: 1943, month: 7 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 130,
        page_end: 130,
        dates: [{ year: 1943, month: 8, day: 2 }],
        is_range_date: false,
      },
      {
        title: '给林森治丧机关的暗电',
        authors: ['毛泽东'],
        page_start: 131,
        page_end: 131,
        dates: [{ year: 1943, month: 8, day: 4 }],
        is_range_date: false,
      },
      {
        title: '晋察翼应下决心实行精简叫',
        authors: ['毛泽东'],
        page_start: 132,
        page_end: 132,
        dates: [{ year: 1943, month: 8, day: 5 }],
        is_range_date: false,
      },
      {
        title: '在中央党校第二部开学典礼上的讲话',
        authors: ['毛泽东'],
        page_start: 133,
        page_end: 140,
        dates: [{ year: 1943, month: 8, day: 8 }],
        is_range_date: false,
      },
      {
        title: '一面支持斗争一面保存干部',
        authors: ['毛泽东'],
        page_start: 141,
        page_end: 141,
        dates: [{ year: 1943, month: 8, day: 11 }],
        is_range_date: false,
      },
      {
        title: '致慧荣臻电山',
        authors: ['毛泽东'],
        page_start: 142,
        page_end: 142,
        dates: [{ year: 1943, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致普察翼分局电',
        authors: ['毛泽东'],
        page_start: 143,
        page_end: 143,
        dates: [{ year: 1943, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '对击退国民党第三次反共高潮后形势的分析和关于党的政策的指示叫',
        authors: ['毛泽东'],
        page_start: 144,
        page_end: 145,
        dates: [{ year: 1943, month: 8, day: 13 }],
        is_range_date: false,
      },
      {
        title: '中共中央关于审香干部的决定',
        authors: ['毛泽东'],
        page_start: 146,
        page_end: 151,
        dates: [{ year: 1943, month: 8, day: 15 }],
        is_range_date: false,
      },
      {
        title: '给中共太行分局书记邓小平转太行分局各同志的电报',
        authors: ['毛泽东'],
        page_start: 152,
        page_end: 152,
        dates: [{ year: 1943, month: 8, day: 16 }],
        is_range_date: false,
      },
      {
        title: '对周恩来关于揭破国民党参政会的阴课问题给毛泽东的信的批语',
        authors: ['毛泽东'],
        page_start: 153,
        page_end: 154,
        dates: [{ year: 1943, month: 8, day: 19 }],
        is_range_date: false,
      },
      {
        title: '给胡乔木的信叫',
        authors: ['毛泽东'],
        page_start: 155,
        page_end: 155,
        dates: [{ year: 1943, month: 8, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致贺龙电山',
        authors: ['毛泽东'],
        page_start: 156,
        page_end: 156,
        dates: [{ year: 1943, month: 8, day: 22 }],
        is_range_date: false,
      },
      {
        title: '在中共驻重庆办事处关于《质问国民觉一文发表后的反映材料上的批注',
        authors: ['毛泽东'],
        page_start: 157,
        page_end: 157,
        dates: [{ year: 1943, month: 8, day: 22 }],
        is_range_date: false,
      },
      {
        title: '给各负责同志的指示',
        authors: ['毛泽东'],
        page_start: 158,
        page_end: 158,
        dates: [{ year: 1943, month: 8, day: 25 }],
        is_range_date: false,
      },
      {
        title: '致董必武电',
        authors: ['毛泽东'],
        page_start: 159,
        page_end: 159,
        dates: [{ year: 1943, month: 8, day: 27 }],
        is_range_date: false,
      },
      {
        title: '在胡宗南等对批判《中国之命运》的文章的情况“反映上的批语',
        authors: ['毛泽东'],
        page_start: 160,
        page_end: 162,
        dates: [{ year: 1943, month: 8, day: 30 }],
        is_range_date: false,
      },
      {
        title: '复山东临时参议会电',
        authors: ['毛泽东'],
        page_start: 163,
        page_end: 163,
        dates: [{ year: 1943, month: 9, day: 1 }],
        is_range_date: false,
      },
      {
        title: '对出版发行工作的指示',
        authors: ['毛泽东'],
        page_start: 164,
        page_end: 164,
        dates: [{ year: 1943, month: 9, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致陈毅等电',
        authors: ['毛泽东'],
        page_start: 165,
        page_end: 167,
        dates: [{ year: 1943, month: 9, day: 3 }],
        is_range_date: false,
      },
      {
        title: '给博古的信',
        authors: ['毛泽东'],
        page_start: 168,
        page_end: 169,
        dates: [{ year: 1943, month: 9, day: 11 }],
        is_range_date: false,
      },
      {
        title: '复董必武电',
        authors: ['毛泽东'],
        page_start: 170,
        page_end: 170,
        dates: [{ year: 1943, month: 9, day: 26 }],
        is_range_date: false,
      },
      {
        title: '复董必武电山',
        authors: ['毛泽东'],
        page_start: 171,
        page_end: 171,
        dates: [{ year: 1943, month: 9, day: 28 }],
        is_range_date: false,
      },
      {
        title: '致重必武电',
        authors: ['毛泽东'],
        page_start: 172,
        page_end: 173,
        dates: [{ year: 1943, month: 9, day: 29 }],
        is_range_date: false,
      },
      {
        title: '致董必武电',
        authors: ['毛泽东'],
        page_start: 174,
        page_end: 174,
        dates: [{ year: 1943, month: 9 }],
        is_range_date: false,
      },
      {
        title: '关于减租、生产、拥政爱民及宣传十大政策的指示',
        authors: ['毛泽东'],
        page_start: 175,
        page_end: 181,
        dates: [{ year: 1943, month: 10, day: 1 }],
        is_range_date: false,
      },
      {
        title: '宣传学习《关于减租、生产、拥政爱民及宣传十大政策的指示》的通知',
        authors: ['毛泽东'],
        page_start: 182,
        page_end: 183,
        dates: [{ year: 1943, month: 10 }],
        is_range_date: false,
      },
      {
        title: '评国民党十一中全会和三届二次国民参政会',
        authors: ['毛泽东'],
        page_start: 184,
        page_end: 196,
        dates: [{ year: 1943, month: 10, day: 5 }],
        is_range_date: false,
      },
      {
        title: '关于暂时停止揭露国民党以示缓和致董必武电',
        authors: ['毛泽东'],
        page_start: 197,
        page_end: 197,
        dates: [{ year: 1943, month: 10, day: 5 }],
        is_range_date: false,
      },
      {
        title: '复董必武电',
        authors: ['毛泽东'],
        page_start: 198,
        page_end: 198,
        dates: [{ year: 1943, month: 10, day: 5 }],
        is_range_date: false,
      },
      {
        title: '致晋绥分局电',
        authors: ['毛泽东'],
        page_start: 199,
        page_end: 199,
        dates: [{ year: 1943, month: 10, day: 9 }],
        is_range_date: false,
      },
      {
        title: '关于审查干部的指示',
        authors: ['毛泽东'],
        page_start: 200,
        page_end: 200,
        dates: [{ year: 1943, month: 10, day: 9 }],
        is_range_date: false,
      },
      {
        title: '复董必武电',
        authors: ['毛泽东'],
        page_start: 201,
        page_end: 201,
        dates: [{ year: 1943, month: 10, day: 10 }],
        is_range_date: false,
      },
      {
        title: '切实执行十大政策',
        authors: ['毛泽东'],
        page_start: 202,
        page_end: 210,
        dates: [{ year: 1943, month: 10, day: 14 }],
        is_range_date: false,
      },
      {
        title: '论合作社',
        authors: ['毛泽东'],
        page_start: 211,
        page_end: 214,
        dates: [{ year: 1943, month: 10, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致重必武电',
        authors: ['毛泽东'],
        page_start: 215,
        page_end: 215,
        dates: [{ year: 1943, month: 10, day: 17 }],
        is_range_date: false,
      },
      {
        title: '给侯健存"的信',
        authors: ['毛泽东'],
        page_start: 216,
        page_end: 216,
        dates: [{ year: 1943, month: 10, day: 21 }],
        is_range_date: false,
      },
      {
        title: '致邓小平等电',
        authors: ['毛泽东'],
        page_start: 217,
        page_end: 217,
        dates: [{ year: 1943, month: 10, day: 21 }],
        is_range_date: false,
      },
      {
        title: '视察南泥湾时的讲话',
        authors: ['毛泽东'],
        page_start: 218,
        page_end: 219,
        dates: [{ year: 1943, month: 10 }],
        is_range_date: false,
      },
      {
        title: '在致朱德电上的批示叫',
        authors: ['毛泽东'],
        page_start: 220,
        page_end: 220,
        dates: [{ year: 1943, month: 10 }],
        is_range_date: false,
      },
      {
        title: '宣传要点',
        authors: ['毛泽东'],
        page_start: 221,
        page_end: 221,
        dates: [{ year: 1943, month: 11, day: 4 }],
        is_range_date: false,
      },
      {
        title: '认真执行中央关于审查干部的指示',
        authors: ['毛泽东'],
        page_start: 222,
        page_end: 223,
        dates: [{ year: 1943, month: 11, day: 5 }],
        is_range_date: false,
      },
      {
        title: '庆祝十月革命节给斯大林的贺电',
        authors: ['毛泽东'],
        page_start: 224,
        page_end: 224,
        dates: [{ year: 1943, month: 11, day: 5 }],
        is_range_date: false,
      },
      {
        title: '在庆祝十月革命节干部晚会上的讲话',
        authors: ['毛泽东'],
        page_start: 225,
        page_end: 227,
        dates: [{ year: 1943, month: 11, day: 6 }],
        is_range_date: false,
      },
      {
        title: '致邓小平等电',
        authors: ['毛泽东'],
        page_start: 228,
        page_end: 228,
        dates: [{ year: 1943, month: 11, day: 11 }],
        is_range_date: false,
      },
      {
        title: '为中直军直生产展览会题词',
        authors: ['毛泽东'],
        page_start: 229,
        page_end: 229,
        dates: [{ year: 1943, month: 11, day: 13 }],
        is_range_date: false,
      },
      {
        title: '在重必武来电上的批示',
        authors: ['毛泽东'],
        page_start: 230,
        page_end: 232,
        dates: [{ year: 1943, month: 11, day: 13 }],
        is_range_date: false,
      },
      {
        title: '复董必武电山',
        authors: ['毛泽东'],
        page_start: 233,
        page_end: 233,
        dates: [{ year: 1943, month: 11, day: 15 }],
        is_range_date: false,
      },
      {
        title: '组织起来',
        authors: ['毛泽东'],
        page_start: 234,
        page_end: 248,
        dates: [{ year: 1943, month: 11, day: 29 }],
        is_range_date: false,
      },
      {
        title: '为八路军留守兵团部队生产展览会题词',
        authors: ['毛泽东'],
        page_start: 249,
        page_end: 250,
        dates: [{ year: 1943, month: 11, day: 29 }],
        is_range_date: false,
      },
      {
        title: '为刘刚题词',
        authors: ['毛泽东'],
        page_start: 251,
        page_end: 252,
        dates: [{ year: 1943, month: 11 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 253,
        page_end: 253,
        dates: [{ year: 1943, month: 12, day: 1 }],
        is_range_date: false,
      },
      {
        title: '给续范亭的信',
        authors: ['毛泽东'],
        page_start: 254,
        page_end: 254,
        dates: [{ year: 1943, month: 12, day: 4 }],
        is_range_date: false,
      },
      {
        title: '致各中央局等电',
        authors: ['毛泽东'],
        page_start: 255,
        page_end: 255,
        dates: [{ year: 1943, month: 12, day: 10 }],
        is_range_date: false,
      },
      {
        title: '自前国际形势及对中国时局的影响',
        authors: ['毛泽东'],
        page_start: 256,
        page_end: 257,
        dates: [{ year: 1943, month: 12, day: 16 }],
        is_range_date: false,
      },
      {
        title: '在刘少奇给续范亭信上的批语',
        authors: ['毛泽东'],
        page_start: 258,
        page_end: 272,
        dates: [{ year: 1943, month: 12, day: 17 }],
        is_range_date: false,
      },
      {
        title: '给胡乔木的信',
        authors: ['毛泽东'],
        page_start: 273,
        page_end: 273,
        dates: [{ year: 1943, month: 12, day: 20 }],
        is_range_date: false,
      },
      {
        title: '在中共中央书记处会议上的讲话',
        authors: ['毛泽东'],
        page_start: 274,
        page_end: 274,
        dates: [{ year: 1943, month: 12, day: 22 }],
        is_range_date: false,
      },
      {
        title: '致邓小平等电',
        authors: ['毛泽东'],
        page_start: 275,
        page_end: 275,
        dates: [{ year: 1943, month: 12, day: 22 }],
        is_range_date: false,
      },
      {
        title: '给刘少奇的信',
        authors: ['毛泽东'],
        page_start: 276,
        page_end: 276,
        dates: [{ year: 1943, month: 12, day: 24 }],
        is_range_date: false,
      },
      {
        title: '反特务斗争必须坚持一个不杀大部不提方针',
        authors: ['毛泽东'],
        page_start: 277,
        page_end: 278,
        dates: [{ year: 1943, month: 12, day: 27 }],
        is_range_date: false,
      },
      {
        title: '研究党的路线问题是整风的深人与高级阶段',
        authors: ['毛泽东'],
        page_start: 279,
        page_end: 280,
        dates: [{ year: 1943, month: 12, day: 28 }],
        is_range_date: false,
      },
      {
        title: '在参观工农业展览会上的讲话',
        authors: ['毛泽东'],
        page_start: 281,
        page_end: 283,
        dates: [{ year: 1943, month: 12 }],
        is_range_date: false,
      },
      {
        title: '接见外地来延安的工作干部时的讲话',
        authors: ['毛泽东'],
        page_start: 284,
        page_end: 284,
        dates: [{ year: 1943 }],
        is_range_date: false,
      },
      {
        title: '挽蔡和森、蔡畅母葛太夫人联',
        authors: ['毛泽东'],
        page_start: 285,
        page_end: 285,
        dates: [{ year: 1943 }],
        is_range_date: false,
      },
      {
        title: '为严炳武题词',
        authors: ['毛泽东'],
        page_start: 286,
        page_end: 287,
        dates: [{ year: 1943 }],
        is_range_date: false,
      },
      {
        title: '为王明祥题词',
        authors: ['毛泽东'],
        page_start: 288,
        page_end: 289,
        dates: [{ year: 1943 }],
        is_range_date: false,
      },
      {
        title: '为王梦权题词',
        authors: ['毛泽东'],
        page_start: 290,
        page_end: 291,
        dates: [{ year: 1943 }],
        is_range_date: false,
      },
      {
        title: '为延安枣园中央俱乐部题词',
        authors: ['毛泽东'],
        page_start: 292,
        page_end: 293,
        dates: [{ year: 1943 }],
        is_range_date: false,
      },
      {
        title: '为中央印刷厂全体劳动模范题词',
        authors: ['毛泽东'],
        page_start: 294,
        page_end: 295,
        dates: [{ year: 1943 }],
        is_range_date: false,
      },
      {
        title: '题写“光明在前',
        authors: ['毛泽东'],
        page_start: 296,
        page_end: 300,
        dates: [{ year: 1943 }],
        is_range_date: false,
      },
      {
        title: '给郭沫若“的信',
        authors: ['毛泽东'],
        page_start: 301,
        page_end: 301,
        dates: [{ year: 1944, month: 1, day: 9 }],
        is_range_date: false,
      },
      {
        title: '给杨绍营、齐燕铭的信',
        authors: ['毛泽东'],
        page_start: 302,
        page_end: 303,
        dates: [{ year: 1944, month: 1, day: 9 }],
        is_range_date: false,
      },
      {
        title: '给彭德怀的信',
        authors: ['毛泽东'],
        page_start: 304,
        page_end: 306,
        dates: [{ year: 1944, month: 1, day: 10 }],
        is_range_date: false,
      },
      {
        title: '复张云逸、饶淞石电',
        authors: ['毛泽东'],
        page_start: 307,
        page_end: 307,
        dates: [{ year: 1944, month: 1, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致山西省沁源县电',
        authors: ['毛泽东'],
        page_start: 308,
        page_end: 308,
        dates: [{ year: 1944, month: 1, day: 17 }],
        is_range_date: false,
      },
      {
        title: '在国民党军进攻时应执行自卫原则',
        authors: ['毛泽东'],
        page_start: 309,
        page_end: 309,
        dates: [{ year: 1944, month: 1, day: 18 }],
        is_range_date: false,
      },
      {
        title: '给林伯渠“的信',
        authors: ['毛泽东'],
        page_start: 310,
        page_end: 311,
        dates: [{ year: 1944, month: 1, day: 19 }],
        is_range_date: false,
      },
      {
        title:
          '在中共中央书记处关于对坦白分子进行甄别工作致邓小平等电上加写的话',
        authors: ['毛泽东'],
        page_start: 312,
        page_end: 312,
        dates: [{ year: 1944, month: 1, day: 24 }],
        is_range_date: false,
      },
      {
        title: '和郭仲容的谈话',
        authors: ['毛泽东'],
        page_start: 313,
        page_end: 313,
        dates: [{ year: 1944, month: 1 }],
        is_range_date: false,
      },
      {
        title: '国共有协调之必要与可能',
        authors: ['毛泽东'],
        page_start: 314,
        page_end: 314,
        dates: [{ year: 1944, month: 2, day: 4 }],
        is_range_date: false,
      },
      {
        title: '对延安市民众代表的讲话叫',
        authors: ['毛泽东'],
        page_start: 315,
        page_end: 317,
        dates: [{ year: 1944, month: 2, day: 7 }],
        is_range_date: false,
      },
      {
        title: '给罗荣植“的信',
        authors: ['毛泽东'],
        page_start: 318,
        page_end: 318,
        dates: [{ year: 1944, month: 2, day: 8 }],
        is_range_date: false,
      },
      {
        title: '应付图锡山部六十一军东进的方针',
        authors: ['毛泽东'],
        page_start: 319,
        page_end: 320,
        dates: [{ year: 1944, month: 2, day: 8 }],
        is_range_date: false,
      },
      {
        title: '复山东省文协电',
        authors: ['毛泽东'],
        page_start: 321,
        page_end: 321,
        dates: [{ year: 1944, month: 2, day: 8 }],
        is_range_date: false,
      },
      {
        title: '在金城六日关于“抢救运动”冲击到钱拯及其子女的一份报告上的批示',
        authors: ['毛泽东'],
        page_start: 322,
        page_end: 322,
        dates: [{ year: 1944, month: 2, day: 8 }],
        is_range_date: false,
      },
      {
        title: '致阁锡山电',
        authors: ['毛泽东'],
        page_start: 323,
        page_end: 323,
        dates: [{ year: 1944, month: 2, day: 8 }],
        is_range_date: false,
      },
      {
        title: '致邓小平等电',
        authors: ['毛泽东'],
        page_start: 324,
        page_end: 324,
        dates: [{ year: 1944, month: 2, day: 9 }],
        is_range_date: false,
      },
      {
        title: '复张云逸、饶激石电',
        authors: ['毛泽东'],
        page_start: 325,
        page_end: 325,
        dates: [{ year: 1944, month: 2, day: 14 }],
        is_range_date: false,
      },
      {
        title: '复邓小平等电',
        authors: ['毛泽东'],
        page_start: 326,
        page_end: 326,
        dates: [{ year: 1944, month: 2, day: 22 }],
        is_range_date: false,
      },
      {
        title: '复邓小平、滕代远电',
        authors: ['毛泽东'],
        page_start: 327,
        page_end: 328,
        dates: [{ year: 1944, month: 2, day: 26 }],
        is_range_date: false,
      },
      {
        title: '关于宪政问题',
        authors: ['毛泽东'],
        page_start: 329,
        page_end: 329,
        dates: [{ year: 1944, month: 3, day: 1 }],
        is_range_date: false,
      },
      {
        title: '关于路线学习、工作作风和时局问题',
        authors: ['毛泽东'],
        page_start: 330,
        page_end: 340,
        dates: [{ year: 1944, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '复黎玉等电',
        authors: ['毛泽东'],
        page_start: 341,
        page_end: 341,
        dates: [{ year: 1944, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '陈毅“在内战和抗战时期是有功劳的',
        authors: ['毛泽东'],
        page_start: 342,
        page_end: 344,
        dates: [{ year: 1944, month: 3, day: 15 }],
        is_range_date: false,
      },
      {
        title: '给罗荣柜等的指示叫',
        authors: ['毛泽东'],
        page_start: 345,
        page_end: 345,
        dates: [{ year: 1944, month: 3, day: 16 }],
        is_range_date: false,
      },
      {
        title: '为马本斋题写换词叫',
        authors: ['毛泽东'],
        page_start: 346,
        page_end: 347,
        dates: [{ year: 1944, month: 3, day: 17 }],
        is_range_date: false,
      },
      {
        title: '关于陕甘宁边区的文化教育问题',
        authors: ['毛泽东'],
        page_start: 348,
        page_end: 363,
        dates: [{ year: 1944, month: 3, day: 22 }],
        is_range_date: false,
      },
      {
        title: '关于对国民党顽军应来取自卫原则的指示',
        authors: ['毛泽东'],
        page_start: 364,
        page_end: 365,
        dates: [{ year: 1944, month: 3, day: 27 }],
        is_range_date: false,
      },
      {
        title: '给周扬“的信',
        authors: ['毛泽东'],
        page_start: 366,
        page_end: 367,
        dates: [{ year: 1944, month: 4, day: 2 }],
        is_range_date: false,
      },
      {
        title: '必须做好经济建设工作',
        authors: ['毛泽东'],
        page_start: 368,
        page_end: 369,
        dates: [{ year: 1944, month: 4, day: 3 }],
        is_range_date: false,
      },
      {
        title: '致中共中央华中局等电',
        authors: ['毛泽东'],
        page_start: 370,
        page_end: 370,
        dates: [{ year: 1944, month: 4, day: 3 }],
        is_range_date: false,
      },
      {
        title: '致罗荣植等电',
        authors: ['毛泽东'],
        page_start: 371,
        page_end: 371,
        dates: [{ year: 1944, month: 4, day: 5 }],
        is_range_date: false,
      },
      {
        title: '给陈毅“的信',
        authors: ['毛泽东'],
        page_start: 372,
        page_end: 372,
        dates: [{ year: 1944, month: 4, day: 9 }],
        is_range_date: false,
      },
      {
        title: '抚钟太夫人联',
        authors: ['毛泽东'],
        page_start: 373,
        page_end: 373,
        dates: [{ year: 1944, month: 4, day: 10 }],
        is_range_date: false,
      },
      {
        title: '在《关于军队政治工作问题上加写的一段话',
        authors: ['毛泽东'],
        page_start: 374,
        page_end: 375,
        dates: [{ year: 1944, month: 4, day: 11 }],
        is_range_date: false,
      },
      {
        title: '学习和时局',
        authors: ['毛泽东'],
        page_start: 376,
        page_end: 434,
        dates: [{ year: 1944, month: 4, day: 12 }],
        is_range_date: false,
      },
      {
        title: '在林伯渠报告上加写的一段话',
        authors: ['毛泽东'],
        page_start: 435,
        page_end: 435,
        dates: [{ year: 1944, month: 4, day: 14 }],
        is_range_date: false,
      },
      {
        title: '在中共中央书记处会议上的讲话',
        authors: ['毛泽东'],
        page_start: 436,
        page_end: 436,
        dates: [{ year: 1944, month: 4, day: 15 }],
        is_range_date: false,
      },
      {
        title: '致滕代远、邓小平等电',
        authors: ['毛泽东'],
        page_start: 437,
        page_end: 437,
        dates: [{ year: 1944, month: 4, day: 22 }],
        is_range_date: false,
      },
      {
        title: '给李鼎铭"的信',
        authors: ['毛泽东'],
        page_start: 438,
        page_end: 439,
        dates: [{ year: 1944, month: 4, day: 29 }],
        is_range_date: false,
      },
      {
        title: '致重必武等电',
        authors: ['毛泽东'],
        page_start: 440,
        page_end: 440,
        dates: [{ year: 1944, month: 4, day: 30 }],
        is_range_date: false,
      },
      {
        title: '和续范亭的谈话',
        authors: ['毛泽东'],
        page_start: 441,
        page_end: 441,
        dates: [{ year: 1944, month: 4, day: 30 }],
        is_range_date: false,
      },
      {
        title: '复林伯渠电',
        authors: ['毛泽东'],
        page_start: 442,
        page_end: 442,
        dates: [{ year: 1944, month: 5, day: 11 }],
        is_range_date: false,
      },
      {
        title: '向国民党提出的二十条谈判意见',
        authors: ['毛泽东'],
        page_start: 443,
        page_end: 446,
        dates: [{ year: 1944, month: 5, day: 15 }],
        is_range_date: false,
      },
      {
        title: '在中共中央书记处会议上的讲话',
        authors: ['毛泽东'],
        page_start: 447,
        page_end: 447,
        dates: [{ year: 1944, month: 5, day: 19 }],
        is_range_date: false,
      },
      {
        title: '自前国际国内的形势中',
        authors: ['毛泽东'],
        page_start: 448,
        page_end: 448,
        dates: [{ year: 1944, month: 5, day: 20 }],
        is_range_date: false,
      },
      {
        title: '在中共六届七中全会上的工作报告',
        authors: ['毛泽东'],
        page_start: 449,
        page_end: 457,
        dates: [{ year: 1944, month: 5, day: 21 }],
        is_range_date: false,
      },
      {
        title: '共产党是要努力于中国的工业化的',
        authors: ['毛泽东'],
        page_start: 458,
        page_end: 459,
        dates: [{ year: 1944, month: 5, day: 22 }],
        is_range_date: false,
      },
      {
        title: '在延安大学开学典礼上的讲话',
        authors: ['毛泽东'],
        page_start: 460,
        page_end: 469,
        dates: [{ year: 1944, month: 5, day: 24 }],
        is_range_date: false,
      },
      {
        title: '延安大学教育方针',
        authors: ['毛泽东'],
        page_start: 470,
        page_end: 472,
        dates: [{ year: 1944, month: 5, day: 24 }],
        is_range_date: false,
      },
      {
        title: '给胡乔木的信',
        authors: ['毛泽东'],
        page_start: 473,
        page_end: 473,
        dates: [{ year: 1944, month: 5, day: 27 }],
        is_range_date: false,
      },
      {
        title: '为中央直属机关个人生产展览会题词',
        authors: ['毛泽东'],
        page_start: 474,
        page_end: 475,
        dates: [{ year: 1944, month: 5, day: 28 }],
        is_range_date: false,
      },
      {
        title: '致林伯渠电',
        authors: ['毛泽东'],
        page_start: 476,
        page_end: 476,
        dates: [{ year: 1944, month: 5, day: 31 }],
        is_range_date: false,
      },
      {
        title: '为特等劳动英雄李强题词',
        authors: ['毛泽东'],
        page_start: 477,
        page_end: 478,
        dates: [{ year: 1944, month: 5 }],
        is_range_date: false,
      },
      {
        title: '为特等劳动英雄钱志道题词',
        authors: ['毛泽东'],
        page_start: 479,
        page_end: 480,
        dates: [{ year: 1944, month: 5 }],
        is_range_date: false,
      },
      {
        title: '为特等劳动英雄陈振夏题词',
        authors: ['毛泽东'],
        page_start: 481,
        page_end: 482,
        dates: [{ year: 1944, month: 5 }],
        is_range_date: false,
      },
      {
        title: '对中共中央党校即将到前线去的学员的讲话',
        authors: ['毛泽东'],
        page_start: 483,
        page_end: 483,
        dates: [{ year: 1944, month: 5 }],
        is_range_date: false,
      },
      {
        title: '复林伯渠等电',
        authors: ['毛泽东'],
        page_start: 484,
        page_end: 484,
        dates: [{ year: 1944, month: 6, day: 3 }],
        is_range_date: false,
      },
      {
        title: '中共中央关于城市工作的指示',
        authors: ['毛泽东'],
        page_start: 485,
        page_end: 492,
        dates: [{ year: 1944, month: 6, day: 5 }],
        is_range_date: false,
      },
      {
        title: '会见中外记者西北参观团的讲话',
        authors: ['毛泽东'],
        page_start: 493,
        page_end: 500,
        dates: [{ year: 1944, month: 6, day: 12 }],
        is_range_date: false,
      },
      {
        title: '纪念联合国日，保卫西安与西北：',
        authors: ['毛泽东'],
        page_start: 501,
        page_end: 505,
        dates: [{ year: 1944, month: 6, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致晋察费分局电',
        authors: ['毛泽东'],
        page_start: 506,
        page_end: 506,
        dates: [{ year: 1944, month: 6, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致中共各中央局等电',
        authors: ['毛泽东'],
        page_start: 507,
        page_end: 507,
        dates: [{ year: 1944, month: 6, day: 18 }],
        is_range_date: false,
      },
      {
        title: '在《中共抗战一般情况的介绍》“上加写的一段话',
        authors: ['毛泽东'],
        page_start: 508,
        page_end: 508,
        dates: [{ year: 1944, month: 6, day: 22 }],
        is_range_date: false,
      },
      {
        title: '长沙失陷后的危机',
        authors: ['毛泽东'],
        page_start: 509,
        page_end: 512,
        dates: [{ year: 1944, month: 6, day: 24 }],
        is_range_date: false,
      },
      {
        title: '致林伯渠、董必武电',
        authors: ['毛泽东'],
        page_start: 513,
        page_end: 513,
        dates: [{ year: 1944, month: 6, day: 28 }],
        is_range_date: false,
      },
      {
        title: '致林伯渠、董必武电',
        authors: ['毛泽东'],
        page_start: 514,
        page_end: 514,
        dates: [{ year: 1944, month: 6, day: 30 }],
        is_range_date: false,
      },
      {
        title: '致林伯渠、董必武电',
        authors: ['毛泽东'],
        page_start: 515,
        page_end: 515,
        dates: [{ year: 1944, month: 6, day: 30 }],
        is_range_date: false,
      },
      {
        title: '为延安卫生展览会题词',
        authors: ['毛泽东'],
        page_start: 516,
        page_end: 517,
        dates: [{ year: 1944, month: 6 }],
        is_range_date: false,
      },
      {
        title: '中共中央关于整训部队的指示叫',
        authors: ['毛泽东'],
        page_start: 518,
        page_end: 522,
        dates: [{ year: 1944, month: 7, day: 1 }],
        is_range_date: false,
      },
      {
        title: '给了玲、欧阳山“的信',
        authors: ['毛泽东'],
        page_start: 523,
        page_end: 524,
        dates: [{ year: 1944, month: 7, day: 1 }],
        is_range_date: false,
      },
      {
        title: '复林伯渠、董必武电',
        authors: ['毛泽东'],
        page_start: 525,
        page_end: 525,
        dates: [{ year: 1944, month: 7, day: 2 }],
        is_range_date: false,
      },
      {
        title: '发展边区经济文化',
        authors: ['毛泽东'],
        page_start: 526,
        page_end: 527,
        dates: [{ year: 1944, month: 7, day: 3 }],
        is_range_date: false,
      },
      {
        title: '召开恢甘宁边区第二届参议会第二次大会的决定',
        authors: ['毛泽东'],
        page_start: 528,
        page_end: 533,
        dates: [{ year: 1944, month: 7, day: 5 }],
        is_range_date: false,
      },
      {
        title: '在关于学习问题给淮北区党委的信上加写的一段话',
        authors: ['毛泽东'],
        page_start: 534,
        page_end: 534,
        dates: [{ year: 1944, month: 7, day: 5 }],
        is_range_date: false,
      },
      {
        title: '复林伯渠、董必武电',
        authors: ['毛泽东'],
        page_start: 535,
        page_end: 535,
        dates: [{ year: 1944, month: 7, day: 7 }],
        is_range_date: false,
      },
    ],
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives8/maoquanji18.pdf',
};
