export default {
  entity: {
    id: 'maoquanji23',
    name: '毛泽东全集第23卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives8/main/maoquanji23.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '攻克蟠龙后的行动部署',
        authors: ['毛泽东'],
        page_start: 33,
        page_end: 34,
        dates: [{ year: 1947, month: 5, day: 4 }],
        is_range_date: false,
      },
      {
        title: '刘邓陈菜普南陕北各部队的作战任务',
        authors: ['毛泽东'],
        page_start: 35,
        page_end: 36,
        dates: [{ year: 1947, month: 5, day: 4 }],
        is_range_date: false,
      },
      {
        title: '只要有耐心总有弃敌机会',
        authors: ['毛泽东'],
        page_start: 37,
        page_end: 38,
        dates: [{ year: 1947, month: 5, day: 4 }],
        is_range_date: false,
      },
      {
        title: '能否解决敌一四四旅',
        authors: ['毛泽东'],
        page_start: 39,
        page_end: 39,
        dates: [{ year: 1947, month: 5, day: 5 }],
        is_range_date: false,
      },
      {
        title: '待敌分散疲备之时发起歼击为宜',
        authors: ['毛泽东'],
        page_start: 40,
        page_end: 40,
        dates: [{ year: 1947, month: 5, day: 5 }],
        is_range_date: false,
      },
      {
        title: '部队防酸休整一时期再出关中陇东',
        authors: ['毛泽东'],
        page_start: 41,
        page_end: 41,
        dates: [{ year: 1947, month: 5, day: 5 }],
        is_range_date: false,
      },
      {
        title: '不性急不分兵待机敌',
        authors: ['毛泽东'],
        page_start: 42,
        page_end: 44,
        dates: [{ year: 1947, month: 5, day: 6 }],
        is_range_date: false,
      },
      {
        title: '退滞故军行动拖护青化芯作战',
        authors: ['毛泽东'],
        page_start: 45,
        page_end: 45,
        dates: [{ year: 1947, month: 5, day: 6 }],
        is_range_date: false,
      },
      {
        title: '攻击昌潍可能引起的几种情况及处置办法',
        authors: ['毛泽东'],
        page_start: 46,
        page_end: 46,
        dates: [{ year: 1947, month: 5, day: 6 }],
        is_range_date: false,
      },
      {
        title: '击破顾祝同系统第一线兵力的部署',
        authors: ['毛泽东'],
        page_start: 47,
        page_end: 48,
        dates: [{ year: 1947, month: 5, day: 8 }],
        is_range_date: false,
      },
      {
        title: '钳制关内敌军配合东北作战',
        authors: ['毛泽东'],
        page_start: 49,
        page_end: 49,
        dates: [{ year: 1947, month: 5, day: 8 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀、习仲勋电',
        authors: ['毛泽东'],
        page_start: 50,
        page_end: 50,
        dates: [{ year: 1947, month: 5, day: 10 }],
        is_range_date: false,
      },
      {
        title: '致陈毅、饶激石、黎玉等电',
        authors: ['毛泽东'],
        page_start: 51,
        page_end: 51,
        dates: [{ year: 1947, month: 5, day: 10 }],
        is_range_date: false,
      },
      {
        title: '将介石驱我至黄河以北而歼灭的方针将归于破产',
        authors: ['毛泽东'],
        page_start: 52,
        page_end: 53,
        dates: [{ year: 1947, month: 5, day: 11 }],
        is_range_date: false,
      },
      {
        title: '须不失时机齐击一路好打之敌',
        authors: ['毛泽东'],
        page_start: 54,
        page_end: 54,
        dates: [{ year: 1947, month: 5, day: 12 }],
        is_range_date: false,
      },
      {
        title: '同意西北野战兵团六月作战方针',
        authors: ['毛泽东'],
        page_start: 55,
        page_end: 55,
        dates: [{ year: 1947, month: 5, day: 14 }],
        is_range_date: false,
      },
      {
        title: '集中兵力打破一路则全局好转',
        authors: ['毛泽东'],
        page_start: 56,
        page_end: 57,
        dates: [{ year: 1947, month: 5, day: 14 }],
        is_range_date: false,
      },
      {
        title: '吸引敌人主力组织打接战役',
        authors: ['毛泽东'],
        page_start: 58,
        page_end: 58,
        dates: [{ year: 1947, month: 5, day: 16 }],
        is_range_date: false,
      },
      {
        title: '萌蔽休整待机再战',
        authors: ['毛泽东'],
        page_start: 59,
        page_end: 59,
        dates: [{ year: 1947, month: 5, day: 18 }],
        is_range_date: false,
      },
      {
        title: '给内蒙人民代表大会的贺电',
        authors: ['毛泽东'],
        page_start: 60,
        page_end: 60,
        dates: [{ year: 1947, month: 5, day: 19 }],
        is_range_date: false,
      },
      {
        title: '东北作战方针及关内战局',
        authors: ['毛泽东'],
        page_start: 61,
        page_end: 63,
        dates: [{ year: 1947, month: 5, day: 20 }],
        is_range_date: false,
      },
      {
        title: '山东战场的作战方针',
        authors: ['毛泽东'],
        page_start: 64,
        page_end: 65,
        dates: [{ year: 1947, month: 5, day: 22 }],
        is_range_date: false,
      },
      {
        title: '对陈谢纵队西进作战的部署',
        authors: ['毛泽东'],
        page_start: 66,
        page_end: 67,
        dates: [{ year: 1947, month: 5, day: 24 }],
        is_range_date: false,
      },
      {
        title: '陈谢纵队应立即发起吕梁战役',
        authors: ['毛泽东'],
        page_start: 68,
        page_end: 68,
        dates: [{ year: 1947, month: 5, day: 26 }],
        is_range_date: false,
      },
      {
        title: '中原军起了极大的战略作用',
        authors: ['毛泽东'],
        page_start: 69,
        page_end: 70,
        dates: [{ year: 1947, month: 5, day: 28 }],
        is_range_date: false,
      },
      {
        title: '将介石政府已处在全民的包围中心',
        authors: ['毛泽东'],
        page_start: 71,
        page_end: 75,
        dates: [{ year: 1947, month: 5, day: 30 }],
        is_range_date: false,
      },
      {
        title: '目前阶段陈乘谭军与刘邓军只作战略配合',
        authors: ['毛泽东'],
        page_start: 76,
        page_end: 76,
        dates: [{ year: 1947, month: 6, day: 1 }],
        is_range_date: false,
      },
      {
        title: '同意刘邓全军休整月底渡河',
        authors: ['毛泽东'],
        page_start: 77,
        page_end: 77,
        dates: [{ year: 1947, month: 6, day: 3 }],
        is_range_date: false,
      },
      {
        title: '先打八十一师后打十八师',
        authors: ['毛泽东'],
        page_start: 78,
        page_end: 78,
        dates: [{ year: 1947, month: 6, day: 4 }],
        is_range_date: false,
      },
      {
        title: '六月中旬作战以全弃敌七个旅为目标',
        authors: ['毛泽东'],
        page_start: 79,
        page_end: 79,
        dates: [{ year: 1947, month: 6, day: 4 }],
        is_range_date: false,
      },
      {
        title: '一切大规模破坏铁路的行动应予停止',
        authors: ['毛泽东'],
        page_start: 80,
        page_end: 80,
        dates: [{ year: 1947, month: 6, day: 4 }],
        is_range_date: false,
      },
      {
        title: '在修改《破车不能再开评第四届第三次国民参政会》时加写的两段话',
        authors: ['毛泽东'],
        page_start: 81,
        page_end: 81,
        dates: [{ year: 1947, month: 6, day: 4 }],
        is_range_date: false,
      },
      {
        title: '做好夺取大西北的一切准备',
        authors: ['毛泽东'],
        page_start: 82,
        page_end: 83,
        dates: [{ year: 1947, month: 6, day: 6 }],
        is_range_date: false,
      },
      {
        title: '关于保密问题的指示',
        authors: ['毛泽东'],
        page_start: 84,
        page_end: 84,
        dates: [{ year: 1947, month: 6, day: 13 }],
        is_range_date: false,
      },
      {
        title: '各战场形势和中工委今后六个月内的工作',
        authors: ['毛泽东'],
        page_start: 85,
        page_end: 87,
        dates: [{ year: 1947, month: 6, day: 14 }],
        is_range_date: false,
      },
      {
        title: '陕甘宁边区三个月的作战情况',
        authors: ['毛泽东'],
        page_start: 88,
        page_end: 88,
        dates: [{ year: 1947, month: 6, day: 15 }],
        is_range_date: false,
      },
      {
        title: '致林伯渠、王维舟等电',
        authors: ['毛泽东'],
        page_start: 89,
        page_end: 89,
        dates: [{ year: 1947, month: 6, day: 15 }],
        is_range_date: false,
      },
      {
        title: '自前宜打分散与较弱之敌',
        authors: ['毛泽东'],
        page_start: 90,
        page_end: 91,
        dates: [{ year: 1947, month: 6, day: 17 }],
        is_range_date: false,
      },
      {
        title: '普察英主力的作战方向',
        authors: ['毛泽东'],
        page_start: 92,
        page_end: 93,
        dates: [{ year: 1947, month: 6, day: 19 }],
        is_range_date: false,
      },
      {
        title: '陈谢军七月中旬开始向榆林方向出击',
        authors: ['毛泽东'],
        page_start: 94,
        page_end: 94,
        dates: [{ year: 1947, month: 6, day: 20 }],
        is_range_date: false,
      },
      {
        title: '边区野战军与陈谢军的作战方针',
        authors: ['毛泽东'],
        page_start: 95,
        page_end: 96,
        dates: [{ year: 1947, month: 6, day: 20 }],
        is_range_date: false,
      },
      {
        title: '在修改《袁号无济于事》时加写的两段话',
        authors: ['毛泽东'],
        page_start: 97,
        page_end: 97,
        dates: [{ year: 1947, month: 6, day: 21 }],
        is_range_date: false,
      },
      {
        title: '不要打无把握之使',
        authors: ['毛泽东'],
        page_start: 98,
        page_end: 99,
        dates: [{ year: 1947, month: 6, day: 22 }],
        is_range_date: false,
      },
      {
        title: '复彭德怀、习仲勋电',
        authors: ['毛泽东'],
        page_start: 100,
        page_end: 100,
        dates: [{ year: 1947, month: 6, day: 22 }],
        is_range_date: false,
      },
      {
        title: '中共中央转发普翼鲁豫中央局六月十六日通报的指示',
        authors: ['毛泽东'],
        page_start: 101,
        page_end: 101,
        dates: [{ year: 1947, month: 6, day: 22 }],
        is_range_date: false,
      },
      {
        title: '复林彪、罗荣柜电',
        authors: ['毛泽东'],
        page_start: 102,
        page_end: 102,
        dates: [{ year: 1947, month: 6, day: 25 }],
        is_range_date: false,
      },
      {
        title: '致陈质、谢富治、韩钧等电',
        authors: ['毛泽东'],
        page_start: 103,
        page_end: 103,
        dates: [{ year: 1947, month: 6, day: 25 }],
        is_range_date: false,
      },
      {
        title: '应取分路出击敌远后方之方针',
        authors: ['毛泽东'],
        page_start: 104,
        page_end: 105,
        dates: [{ year: 1947, month: 6, day: 29 }],
        is_range_date: false,
      },
      {
        title: '部署强大力量准备马鸿透逃跑时轩灭之',
        authors: ['毛泽东'],
        page_start: 106,
        page_end: 106,
        dates: [{ year: 1947, month: 6, day: 30 }],
        is_range_date: false,
      },
      {
        title: '每战应以齐灭孤立分散之敌为书',
        authors: ['毛泽东'],
        page_start: 107,
        page_end: 108,
        dates: [{ year: 1947, month: 7, day: 1 }],
        is_range_date: false,
      },
      {
        title:
          '修改《努力奋斗迎接胜利一纪念中国共产党创立二十六周年》时加写的两段话',
        authors: ['毛泽东'],
        page_start: 109,
        page_end: 109,
        dates: [{ year: 1947, month: 7, day: 1 }],
        is_range_date: false,
      },
      {
        title: '以神速动作打开与刘邓会师之道路',
        authors: ['毛泽东'],
        page_start: 110,
        page_end: 111,
        dates: [{ year: 1947, month: 7, day: 2 }],
        is_range_date: false,
      },
      {
        title: '将政府又一穷极无聊的尝试',
        authors: ['毛泽东'],
        page_start: 112,
        page_end: 113,
        dates: [{ year: 1947, month: 7, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致林彪、罗荣柜、刘亚楼电',
        authors: ['毛泽东'],
        page_start: 114,
        page_end: 114,
        dates: [{ year: 1947, month: 7, day: 2 }],
        is_range_date: false,
      },
      {
        title: '普察莫野战军下半年的行动部署',
        authors: ['毛泽东'],
        page_start: 115,
        page_end: 116,
        dates: [{ year: 1947, month: 7, day: 3 }],
        is_range_date: false,
      },
      {
        title: '以尽齐泰安至临城全线之敌为第一目标',
        authors: ['毛泽东'],
        page_start: 117,
        page_end: 117,
        dates: [{ year: 1947, month: 7, day: 3 }],
        is_range_date: false,
      },
      {
        title: '击灭胡宗南夺取大西北的两个方案',
        authors: ['毛泽东'],
        page_start: 118,
        page_end: 119,
        dates: [{ year: 1947, month: 7, day: 4 }],
        is_range_date: false,
      },
      {
        title: '自前应采取四路分兵各打各的方针',
        authors: ['毛泽东'],
        page_start: 120,
        page_end: 121,
        dates: [{ year: 1947, month: 7, day: 4 }],
        is_range_date: false,
      },
      {
        title: '齐击第八军并相机攻取潍县',
        authors: ['毛泽东'],
        page_start: 122,
        page_end: 122,
        dates: [{ year: 1947, month: 7, day: 5 }],
        is_range_date: false,
      },
      {
        title: '致陈毅、栗裕、谭震林等电',
        authors: ['毛泽东'],
        page_start: 123,
        page_end: 123,
        dates: [{ year: 1947, month: 7, day: 9 }],
        is_range_date: false,
      },
      {
        title: '争取在内线多敌人',
        authors: ['毛泽东'],
        page_start: 124,
        page_end: 125,
        dates: [{ year: 1947, month: 7, day: 10 }],
        is_range_date: false,
      },
      {
        title: '一年作战总结及今后计划',
        authors: ['毛泽东'],
        page_start: 126,
        page_end: 129,
        dates: [{ year: 1947, month: 7, day: 10 }],
        is_range_date: false,
      },
      {
        title: '放手歼敌粉碎鲁中敌军进攻',
        authors: ['毛泽东'],
        page_start: 130,
        page_end: 130,
        dates: [{ year: 1947, month: 7, day: 12 }],
        is_range_date: false,
      },
      {
        title: '部队是否西移须依情况决定',
        authors: ['毛泽东'],
        page_start: 131,
        page_end: 131,
        dates: [{ year: 1947, month: 7, day: 12 }],
        is_range_date: false,
      },
      {
        title: '给陈理昆“的信',
        authors: ['毛泽东'],
        page_start: 132,
        page_end: 132,
        dates: [{ year: 1947, month: 7, day: 13 }],
        is_range_date: false,
      },
      {
        title: '将贼介石卖国频民国人都可得而课之',
        authors: ['毛泽东'],
        page_start: 133,
        page_end: 134,
        dates: [{ year: 1947, month: 7, day: 13 }],
        is_range_date: false,
      },
      {
        title: '给续范亭的信',
        authors: ['毛泽东'],
        page_start: 135,
        page_end: 135,
        dates: [{ year: 1947, month: 7, day: 13 }],
        is_range_date: false,
      },
      {
        title: '致刘伯承、邓小平等电',
        authors: ['毛泽东'],
        page_start: 136,
        page_end: 136,
        dates: [{ year: 1947, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '日前应放手攻占泗水等七城',
        authors: ['毛泽东'],
        page_start: 137,
        page_end: 138,
        dates: [{ year: 1947, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '陈谢纵队使用方向改为渡河南进',
        authors: ['毛泽东'],
        page_start: 139,
        page_end: 140,
        dates: [{ year: 1947, month: 7, day: 19 }],
        is_range_date: false,
      },
      {
        title: '在小河中共中央扩大会议上的讲话',
        authors: ['毛泽东'],
        page_start: 141,
        page_end: 149,
        dates: [{ year: 1947, month: 7, day: 21 }],
        is_range_date: false,
      },
      {
        title: '陈谢等部速作好出豫西的准备',
        authors: ['毛泽东'],
        page_start: 150,
        page_end: 151,
        dates: [{ year: 1947, month: 7, day: 22 }],
        is_range_date: false,
      },
      {
        title: '对确保与扩大战略动权的军事部署',
        authors: ['毛泽东'],
        page_start: 152,
        page_end: 154,
        dates: [{ year: 1947, month: 7, day: 23 }],
        is_range_date: false,
      },
      {
        title: '给李井泉的信',
        authors: ['毛泽东'],
        page_start: 155,
        page_end: 156,
        dates: [{ year: 1947, month: 7, day: 23 }],
        is_range_date: false,
      },
      {
        title: '对刘少奇《给普缓同志的信》的批语',
        authors: ['毛泽东'],
        page_start: 157,
        page_end: 157,
        dates: [{ year: 1947, month: 7, day: 25 }],
        is_range_date: false,
      },
      {
        title: '复林彪电',
        authors: ['毛泽东'],
        page_start: 158,
        page_end: 158,
        dates: [{ year: 1947, month: 7, day: 25 }],
        is_range_date: false,
      },
      {
        title: '致朱德、刘少奇、康生电',
        authors: ['毛泽东'],
        page_start: 159,
        page_end: 159,
        dates: [{ year: 1947, month: 7, day: 26 }],
        is_range_date: false,
      },
      {
        title: '做好到国民党区域作战的准备工作',
        authors: ['毛泽东'],
        page_start: 160,
        page_end: 161,
        dates: [{ year: 1947, month: 7, day: 26 }],
        is_range_date: false,
      },
      {
        title: '刘邓军立即集结休整准备南进',
        authors: ['毛泽东'],
        page_start: 162,
        page_end: 163,
        dates: [{ year: 1947, month: 7, day: 27 }],
        is_range_date: false,
      },
      {
        title: '同意临胸战役后我主力移诸城营具地区',
        authors: ['毛泽东'],
        page_start: 164,
        page_end: 164,
        dates: [{ year: 1947, month: 7, day: 27 }],
        is_range_date: false,
      },
      {
        title: '陈谢集团归刘邓指挥并组织前委',
        authors: ['毛泽东'],
        page_start: 165,
        page_end: 165,
        dates: [{ year: 1947, month: 7, day: 27 }],
        is_range_date: false,
      },
      {
        title: '致刘伯承、邓小平等电',
        authors: ['毛泽东'],
        page_start: 166,
        page_end: 166,
        dates: [{ year: 1947, month: 7, day: 27 }],
        is_range_date: false,
      },
      {
        title: '刘邓陈谢等部的作战任务',
        authors: ['毛泽东'],
        page_start: 167,
        page_end: 168,
        dates: [{ year: 1947, month: 7, day: 29 }],
        is_range_date: false,
      },
      {
        title: '致各区各级首长电',
        authors: ['毛泽东'],
        page_start: 169,
        page_end: 169,
        dates: [{ year: 1947, month: 7, day: 29 }],
        is_range_date: false,
      },
      {
        title: '必须于两个战役间争取休息',
        authors: ['毛泽东'],
        page_start: 170,
        page_end: 172,
        dates: [{ year: 1947, month: 7, day: 30 }],
        is_range_date: false,
      },
      {
        title: '刘邓军出大别山的准备工作',
        authors: ['毛泽东'],
        page_start: 173,
        page_end: 174,
        dates: [{ year: 1947, month: 7, day: 30 }],
        is_range_date: false,
      },
      {
        title: '致刘伯承、邓小平电',
        authors: ['毛泽东'],
        page_start: 175,
        page_end: 175,
        dates: [{ year: 1947, month: 7, day: 30 }],
        is_range_date: false,
      },
      {
        title: '致刘伯承、邓小平等电',
        authors: ['毛泽东'],
        page_start: 176,
        page_end: 176,
        dates: [{ year: 1947, month: 8, day: 3 }],
        is_range_date: false,
      },
      {
        title: '菜裕迅去绑城指挥五个纵队策应刘邓作战',
        authors: ['毛泽东'],
        page_start: 177,
        page_end: 177,
        dates: [{ year: 1947, month: 8, day: 4 }],
        is_range_date: false,
      },
      {
        title: '华野五个纵队渡运河后的作战任务',
        authors: ['毛泽东'],
        page_start: 178,
        page_end: 179,
        dates: [{ year: 1947, month: 8, day: 5 }],
        is_range_date: false,
      },
      {
        title: '立足鲁西南粉碎敌驱我过黄河企图',
        authors: ['毛泽东'],
        page_start: 180,
        page_end: 181,
        dates: [{ year: 1947, month: 8, day: 5 }],
        is_range_date: false,
      },
      {
        title: '对刘邓出动后敌之对策的估计',
        authors: ['毛泽东'],
        page_start: 182,
        page_end: 183,
        dates: [{ year: 1947, month: 8, day: 6 }],
        is_range_date: false,
      },
      {
        title: '刘邓陈菜等部配合作战的部署叫',
        authors: ['毛泽东'],
        page_start: 184,
        page_end: 186,
        dates: [{ year: 1947, month: 8, day: 6 }],
        is_range_date: false,
      },
      {
        title: '整顿队势以利争取新胜利',
        authors: ['毛泽东'],
        page_start: 187,
        page_end: 188,
        dates: [{ year: 1947, month: 8, day: 6 }],
        is_range_date: false,
      },
      {
        title: '陈菜应速西去',
        authors: ['毛泽东'],
        page_start: 189,
        page_end: 190,
        dates: [{ year: 1947, month: 8, day: 6 }],
        is_range_date: false,
      },
      {
        title: '陈菜六个纵队集中处于内线钳制敌人',
        authors: ['毛泽东'],
        page_start: 191,
        page_end: 192,
        dates: [{ year: 1947, month: 8, day: 7 }],
        is_range_date: false,
      },
      {
        title: '陈谢集团应提前渡河',
        authors: ['毛泽东'],
        page_start: 193,
        page_end: 193,
        dates: [{ year: 1947, month: 8, day: 9 }],
        is_range_date: false,
      },
      {
        title: '刘邓南进决心完全正确',
        authors: ['毛泽东'],
        page_start: 194,
        page_end: 195,
        dates: [{ year: 1947, month: 8, day: 10 }],
        is_range_date: false,
      },
      {
        title: '令王世泰部直出长武彬具速占泾滑间诸县',
        authors: ['毛泽东'],
        page_start: 196,
        page_end: 196,
        dates: [{ year: 1947, month: 8, day: 10 }],
        is_range_date: false,
      },
      {
        title: '致刘伯承、邓小平电',
        authors: ['毛泽东'],
        page_start: 197,
        page_end: 197,
        dates: [{ year: 1947, month: 8, day: 10 }],
        is_range_date: false,
      },
      {
        title: '华东野战军西兵团统归刘邓指挥',
        authors: ['毛泽东'],
        page_start: 198,
        page_end: 198,
        dates: [{ year: 1947, month: 8, day: 11 }],
        is_range_date: false,
      },
      {
        title: '总意图是将战争引面国民党区域',
        authors: ['毛泽东'],
        page_start: 199,
        page_end: 199,
        dates: [{ year: 1947, month: 8, day: 11 }],
        is_range_date: false,
      },
      {
        title: '停攻榆林城集中兵力打钟松部',
        authors: ['毛泽东'],
        page_start: 200,
        page_end: 201,
        dates: [{ year: 1947, month: 8, day: 11 }],
        is_range_date: false,
      },
      {
        title: '对我军南进的三点意见',
        authors: ['毛泽东'],
        page_start: 202,
        page_end: 203,
        dates: [{ year: 1947, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '陈谢宜早日渡河接助刘邓',
        authors: ['毛泽东'],
        page_start: 204,
        page_end: 204,
        dates: [{ year: 1947, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀等电',
        authors: ['毛泽东'],
        page_start: 205,
        page_end: 205,
        dates: [{ year: 1947, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '中共中央对刘少奇关于土地会议各地汇报情形及今后意见的报告的指示',
        authors: ['毛泽东'],
        page_start: 206,
        page_end: 207,
        dates: [{ year: 1947, month: 8, day: 13 }],
        is_range_date: false,
      },
      {
        title: '注意分割敌人逐一歼灭之',
        authors: ['毛泽东'],
        page_start: 208,
        page_end: 208,
        dates: [{ year: 1947, month: 8, day: 15 }],
        is_range_date: false,
      },
      {
        title: '军委关于陕北部队配合南线三路大军的行动部署的指示',
        authors: ['毛泽东'],
        page_start: 209,
        page_end: 210,
        dates: [{ year: 1947, month: 8, day: 16 }],
        is_range_date: false,
      },
      {
        title: '陈菜部的供应和普要鲁像三个纵队行动问题',
        authors: ['毛泽东'],
        page_start: 211,
        page_end: 212,
        dates: [{ year: 1947, month: 8, day: 16 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 213,
        page_end: 214,
        dates: [{ year: 1947, month: 8, day: 19 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 215,
        page_end: 215,
        dates: [{ year: 1947, month: 8, day: 19 }],
        is_range_date: false,
      },
      {
        title: '复陈毅、栗裕等电',
        authors: ['毛泽东'],
        page_start: 216,
        page_end: 216,
        dates: [{ year: 1947, month: 8, day: 19 }],
        is_range_date: false,
      },
      {
        title: '在今后四个月内争取整个军事形势的转变',
        authors: ['毛泽东'],
        page_start: 217,
        page_end: 219,
        dates: [{ year: 1947, month: 8, day: 21 }],
        is_range_date: false,
      },
      {
        title: '对西北战场形势的分析',
        authors: ['毛泽东'],
        page_start: 220,
        page_end: 221,
        dates: [{ year: 1947, month: 8, day: 22 }],
        is_range_date: false,
      },
      {
        title: '新华社记者评陕北之捷',
        authors: ['毛泽东'],
        page_start: 222,
        page_end: 223,
        dates: [{ year: 1947, month: 8, day: 23 }],
        is_range_date: false,
      },
      {
        title: '在沙家店战役总结会上的讲话',
        authors: ['毛泽东'],
        page_start: 224,
        page_end: 224,
        dates: [{ year: 1947, month: 8, day: 23 }],
        is_range_date: false,
      },
      {
        title: '西兵团“的作战任务',
        authors: ['毛泽东'],
        page_start: 225,
        page_end: 227,
        dates: [{ year: 1947, month: 8, day: 24 }],
        is_range_date: false,
      },
      {
        title: '我车对将介右企图在胶东抽兵的对策',
        authors: ['毛泽东'],
        page_start: 228,
        page_end: 229,
        dates: [{ year: 1947, month: 8, day: 25 }],
        is_range_date: false,
      },
      {
        title: '陈谢渡河后应放手向豫西发展',
        authors: ['毛泽东'],
        page_start: 230,
        page_end: 230,
        dates: [{ year: 1947, month: 8, day: 26 }],
        is_range_date: false,
      },
      {
        title: '致陈毅、采裕电',
        authors: ['毛泽东'],
        page_start: 231,
        page_end: 231,
        dates: [{ year: 1947, month: 8, day: 27 }],
        is_range_date: false,
      },
      {
        title: '陈菜部应迅速渡河南进打开局面',
        authors: ['毛泽东'],
        page_start: 232,
        page_end: 233,
        dates: [{ year: 1947, month: 8, day: 28 }],
        is_range_date: false,
      },
      {
        title: '给敌以并灭与弃灭性打击须同时注重',
        authors: ['毛泽东'],
        page_start: 234,
        page_end: 236,
        dates: [{ year: 1947, month: 8, day: 28 }],
        is_range_date: false,
      },
      {
        title: '采取于运动中华歼灭半击潢的作战方针心',
        authors: ['毛泽东'],
        page_start: 237,
        page_end: 237,
        dates: [{ year: 1947, month: 8, day: 29 }],
        is_range_date: false,
      },
      {
        title: '东北我军应于九月下句开始作战以配合南线',
        authors: ['毛泽东'],
        page_start: 238,
        page_end: 238,
        dates: [{ year: 1947, month: 8, day: 29 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 239,
        page_end: 239,
        dates: [{ year: 1947, month: 8, day: 29 }],
        is_range_date: false,
      },
      {
        title: '致各首长电',
        authors: ['毛泽东'],
        page_start: 240,
        page_end: 240,
        dates: [{ year: 1947, month: 8, day: 30 }],
        is_range_date: false,
      },
      {
        title: '陈谢主力速抢占陕县灵宝等具',
        authors: ['毛泽东'],
        page_start: 241,
        page_end: 242,
        dates: [{ year: 1947, month: 8, day: 30 }],
        is_range_date: false,
      },
      {
        title: '先敌抢占缓清间一段阻敌南进',
        authors: ['毛泽东'],
        page_start: 243,
        page_end: 243,
        dates: [{ year: 1947, month: 8, day: 30 }],
        is_range_date: false,
      },
      {
        title: '新华社记者评论抵饰美国亡华罪行鹤母城女串演双簧',
        authors: ['毛泽东'],
        page_start: 244,
        page_end: 246,
        dates: [{ year: 1947, month: 8, day: 30 }],
        is_range_date: false,
      },
      {
        title: '致陈毅、栗裕电',
        authors: ['毛泽东'],
        page_start: 247,
        page_end: 247,
        dates: [{ year: 1947, month: 8, day: 30 }],
        is_range_date: false,
      },
      {
        title: '刘邓部日前的行动方向叫',
        authors: ['毛泽东'],
        page_start: 248,
        page_end: 248,
        dates: [{ year: 1947, month: 8, day: 31 }],
        is_range_date: false,
      },
      {
        title: '解放战争第二年的战略方针叫',
        authors: ['毛泽东'],
        page_start: 249,
        page_end: 253,
        dates: [{ year: 1947, month: 9, day: 1 }],
        is_range_date: false,
      },
      {
        title: '陈谢部的作战范围和原则',
        authors: ['毛泽东'],
        page_start: 254,
        page_end: 255,
        dates: [{ year: 1947, month: 9, day: 2 }],
        is_range_date: false,
      },
      {
        title: '西北野战军羊力迅速南进相机攻占洛川等城',
        authors: ['毛泽东'],
        page_start: 256,
        page_end: 256,
        dates: [{ year: 1947, month: 9, day: 2 }],
        is_range_date: false,
      },
      {
        title: '迅速建立无后方作战的思想',
        authors: ['毛泽东'],
        page_start: 257,
        page_end: 258,
        dates: [{ year: 1947, month: 9, day: 3 }],
        is_range_date: false,
      },
      {
        title: '要有建立鄂豫陕根据地的决心',
        authors: ['毛泽东'],
        page_start: 259,
        page_end: 260,
        dates: [{ year: 1947, month: 9, day: 4 }],
        is_range_date: false,
      },
      {
        title: '在修改《军队中的民主运动时加写的一段话',
        authors: ['毛泽东'],
        page_start: 261,
        page_end: 262,
        dates: [{ year: 1947, month: 9, day: 4 }],
        is_range_date: false,
      },
      {
        title: '土地会议叫应该采取彻底平分土地的方针',
        authors: ['毛泽东'],
        page_start: 263,
        page_end: 264,
        dates: [{ year: 1947, month: 9, day: 6 }],
        is_range_date: false,
      },
      {
        title: '致陈废、谢富治、韩钧电',
        authors: ['毛泽东'],
        page_start: 265,
        page_end: 265,
        dates: [{ year: 1947, month: 9, day: 6 }],
        is_range_date: false,
      },
      {
        title: '注意轩灭运动中的中央系各部及滇军',
        authors: ['毛泽东'],
        page_start: 266,
        page_end: 266,
        dates: [{ year: 1947, month: 9, day: 11 }],
        is_range_date: false,
      },
      {
        title: '在黄河、淮河、运河、平汉之间创造根据地有重大战略意义',
        authors: ['毛泽东'],
        page_start: 267,
        page_end: 269,
        dates: [{ year: 1947, month: 9, day: 11 }],
        is_range_date: false,
      },
      {
        title: '在修改新《人民解放军大举反攻》时加写的两段话',
        authors: ['毛泽东'],
        page_start: 270,
        page_end: 270,
        dates: [{ year: 1947, month: 9, day: 11 }],
        is_range_date: false,
      },
      {
        title: '给毛岸英的信',
        authors: ['毛泽东'],
        page_start: 271,
        page_end: 272,
        dates: [{ year: 1947, month: 9, day: 12 }],
        is_range_date: false,
      },
      {
        title: '陈谢集团攻克卢氏后的作战任务',
        authors: ['毛泽东'],
        page_start: 273,
        page_end: 273,
        dates: [{ year: 1947, month: 9, day: 13 }],
        is_range_date: false,
      },
      {
        title: '中国十地法大纲',
        authors: ['毛泽东'],
        page_start: 274,
        page_end: 277,
        dates: [{ year: 1947, month: 9, day: 13 }],
        is_range_date: false,
      },
      {
        title: '致陈毅、菜裕电',
        authors: ['毛泽东'],
        page_start: 278,
        page_end: 278,
        dates: [{ year: 1947, month: 9, day: 13 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 279,
        page_end: 279,
        dates: [{ year: 1947, month: 9, day: 14 }],
        is_range_date: false,
      },
      {
        title: '西兵团暂不分兵运河以东为好',
        authors: ['毛泽东'],
        page_start: 280,
        page_end: 281,
        dates: [{ year: 1947, month: 9, day: 15 }],
        is_range_date: false,
      },
      {
        title: '陈谢部的行动计划',
        authors: ['毛泽东'],
        page_start: 282,
        page_end: 283,
        dates: [{ year: 1947, month: 9, day: 15 }],
        is_range_date: false,
      },
      {
        title: '自前各战区的作战情况',
        authors: ['毛泽东'],
        page_start: 284,
        page_end: 285,
        dates: [{ year: 1947, month: 9, day: 15 }],
        is_range_date: false,
      },
      {
        title: '西北野战军应配合陈谢完成重要任务',
        authors: ['毛泽东'],
        page_start: 286,
        page_end: 286,
        dates: [{ year: 1947, month: 9, day: 16 }],
        is_range_date: false,
      },
      {
        title: '部队自行解决棉衣问题',
        authors: ['毛泽东'],
        page_start: 287,
        page_end: 288,
        dates: [{ year: 1947, month: 9, day: 16 }],
        is_range_date: false,
      },
      {
        title: '七两纵目前不宜离开滨海',
        authors: ['毛泽东'],
        page_start: 289,
        page_end: 289,
        dates: [{ year: 1947, month: 9, day: 16 }],
        is_range_date: false,
      },
      {
        title: '抓住时机打开陕东陕南局面',
        authors: ['毛泽东'],
        page_start: 290,
        page_end: 290,
        dates: [{ year: 1947, month: 9, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀等电',
        authors: ['毛泽东'],
        page_start: 291,
        page_end: 291,
        dates: [{ year: 1947, month: 9, day: 17 }],
        is_range_date: false,
      },
      {
        title: '西北野战军有配合陈质兵团争取战略胜利之任务',
        authors: ['毛泽东'],
        page_start: 292,
        page_end: 293,
        dates: [{ year: 1947, month: 9, day: 18 }],
        is_range_date: false,
      },
      {
        title: '西北野战军主力南进的部署叫',
        authors: ['毛泽东'],
        page_start: 294,
        page_end: 299,
        dates: [{ year: 1947, month: 9, day: 18 }],
        is_range_date: false,
      },
      {
        title: '致陈赛、谢富治、韩钧电',
        authors: ['毛泽东'],
        page_start: 300,
        page_end: 300,
        dates: [{ year: 1947, month: 9, day: 18 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 301,
        page_end: 301,
        dates: [{ year: 1947, month: 9, day: 19 }],
        is_range_date: false,
      },
      {
        title: '致普察货中央局电',
        authors: ['毛泽东'],
        page_start: 302,
        page_end: 302,
        dates: [{ year: 1947, month: 9, day: 19 }],
        is_range_date: false,
      },
      {
        title: '同意陈谢韩三路出兵意见',
        authors: ['毛泽东'],
        page_start: 303,
        page_end: 304,
        dates: [{ year: 1947, month: 9, day: 20 }],
        is_range_date: false,
      },
      {
        title: '为续范亭题写换联',
        authors: ['毛泽东'],
        page_start: 305,
        page_end: 305,
        dates: [{ year: 1947, month: 9, day: 22 }],
        is_range_date: false,
      },
      {
        title: '四纵东进协同秦纵齐击李铁军部',
        authors: ['毛泽东'],
        page_start: 306,
        page_end: 307,
        dates: [{ year: 1947, month: 9, day: 23 }],
        is_range_date: false,
      },
      {
        title: '打李铁军部的部署',
        authors: ['毛泽东'],
        page_start: 308,
        page_end: 309,
        dates: [{ year: 1947, month: 9, day: 23 }],
        is_range_date: false,
      },
      {
        title: '西北主力应在内线完成三项任务',
        authors: ['毛泽东'],
        page_start: 310,
        page_end: 310,
        dates: [{ year: 1947, month: 9, day: 23 }],
        is_range_date: false,
      },
      {
        title: '复朱德、刘少奇等电',
        authors: ['毛泽东'],
        page_start: 311,
        page_end: 311,
        dates: [{ year: 1947, month: 9, day: 24 }],
        is_range_date: false,
      },
      {
        title: '打李铁军及以后的作战任务叫',
        authors: ['毛泽东'],
        page_start: 312,
        page_end: 315,
        dates: [{ year: 1947, month: 9, day: 25 }],
        is_range_date: false,
      },
      {
        title: '四纵第十二旅应在陕南建立根据地',
        authors: ['毛泽东'],
        page_start: 316,
        page_end: 316,
        dates: [{ year: 1947, month: 9, day: 26 }],
        is_range_date: false,
      },
      {
        title: '致陈唐、谢富治、韩钧电',
        authors: ['毛泽东'],
        page_start: 317,
        page_end: 317,
        dates: [{ year: 1947, month: 9, day: 26 }],
        is_range_date: false,
      },
      {
        title: '复徐向前、滕代远、薄一波等电',
        authors: ['毛泽东'],
        page_start: 318,
        page_end: 318,
        dates: [{ year: 1947, month: 9, day: 26 }],
        is_range_date: false,
      },
      {
        title: '在辽东三纵队诉苦教育经验报告上加写的一段话',
        authors: ['毛泽东'],
        page_start: 319,
        page_end: 319,
        dates: [{ year: 1947, month: 9, day: 28 }],
        is_range_date: false,
      },
      {
        title: '同意陈菜部分两路前进方针',
        authors: ['毛泽东'],
        page_start: 320,
        page_end: 320,
        dates: [{ year: 1947, month: 9, day: 30 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 321,
        page_end: 321,
        dates: [{ year: 1947, month: 9, day: 30 }],
        is_range_date: false,
      },
      {
        title: '为中共佳县县委题词',
        authors: ['毛泽东'],
        page_start: 322,
        page_end: 323,
        dates: [{ year: 1947, month: 9 }],
        is_range_date: false,
      },
      {
        title: '清润瓦宠堡两处可先打一处',
        authors: ['毛泽东'],
        page_start: 324,
        page_end: 324,
        dates: [{ year: 1947, month: 10, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 325,
        page_end: 325,
        dates: [{ year: 1947, month: 10, day: 2 }],
        is_range_date: false,
      },
      {
        title: '陈菜部在一两个月内应只打小仗不打大使',
        authors: ['毛泽东'],
        page_start: 326,
        page_end: 327,
        dates: [{ year: 1947, month: 10, day: 3 }],
        is_range_date: false,
      },
      {
        title: '陈菜部在一两个月内应只打小食不打大使',
        authors: ['毛泽东'],
        page_start: 328,
        page_end: 329,
        dates: [{ year: 1947, month: 10, day: 3 }],
        is_range_date: false,
      },
      {
        title: '在新区作战的方针',
        authors: ['毛泽东'],
        page_start: 330,
        page_end: 332,
        dates: [{ year: 1947, month: 10, day: 4 }],
        is_range_date: false,
      },
      {
        title: '华东野战军西兵团各纵的作战任务',
        authors: ['毛泽东'],
        page_start: 333,
        page_end: 334,
        dates: [{ year: 1947, month: 10, day: 4 }],
        is_range_date: false,
      },
      {
        title: '凡无把握之仗不要打',
        authors: ['毛泽东'],
        page_start: 335,
        page_end: 335,
        dates: [{ year: 1947, month: 10, day: 8 }],
        is_range_date: false,
      },
      {
        title: '我军已全面转人反攻',
        authors: ['毛泽东'],
        page_start: 336,
        page_end: 336,
        dates: [{ year: 1947, month: 10, day: 8 }],
        is_range_date: false,
      },
      {
        title: '给毛岸英“的信',
        authors: ['毛泽东'],
        page_start: 337,
        page_end: 338,
        dates: [{ year: 1947, month: 10, day: 8 }],
        is_range_date: false,
      },
      {
        title: '致刘伯承、邓小平电',
        authors: ['毛泽东'],
        page_start: 339,
        page_end: 339,
        dates: [{ year: 1947, month: 10, day: 8 }],
        is_range_date: false,
      },
      {
        title: '致中央工委、普察翼中央局电',
        authors: ['毛泽东'],
        page_start: 340,
        page_end: 340,
        dates: [{ year: 1947, month: 10, day: 9 }],
        is_range_date: false,
      },
      {
        title: '中国人民解放军宣言',
        authors: ['毛泽东'],
        page_start: 341,
        page_end: 346,
        dates: [{ year: 1947, month: 10, day: 10 }],
        is_range_date: false,
      },
      {
        title: '中国人民解放军总部颁布三大纪律八项注意训令',
        authors: ['毛泽东'],
        page_start: 347,
        page_end: 350,
        dates: [{ year: 1947, month: 10, day: 10 }],
        is_range_date: false,
      },
      {
        title: '关于公布《中国土地法大纲》的决议',
        authors: ['毛泽东'],
        page_start: 351,
        page_end: 352,
        dates: [{ year: 1947, month: 10, day: 10 }],
        is_range_date: false,
      },
      {
        title: '中国人民解放军训令',
        authors: ['毛泽东'],
        page_start: 353,
        page_end: 353,
        dates: [{ year: 1947, month: 10, day: 10 }],
        is_range_date: false,
      },
      {
        title: '固守清润杀伤消耗敌人待机举行反突击',
        authors: ['毛泽东'],
        page_start: 354,
        page_end: 354,
        dates: [{ year: 1947, month: 10, day: 11 }],
        is_range_date: false,
      },
      {
        title: '西北战场的情况与经验',
        authors: ['毛泽东'],
        page_start: 355,
        page_end: 358,
        dates: [{ year: 1947, month: 10, day: 11 }],
        is_range_date: false,
      },
      {
        title: '中共发言人严正揭露将美勾结行区追害民主人士',
        authors: ['毛泽东'],
        page_start: 359,
        page_end: 360,
        dates: [{ year: 1947, month: 10, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致刘伯承、邓小平等电',
        authors: ['毛泽东'],
        page_start: 361,
        page_end: 361,
        dates: [{ year: 1947, month: 10, day: 12 }],
        is_range_date: false,
      },
      {
        title: '复彭德怀等电',
        authors: ['毛泽东'],
        page_start: 362,
        page_end: 362,
        dates: [{ year: 1947, month: 10, day: 13 }],
        is_range_date: false,
      },
      {
        title: '攻克吉林后应将主攻方向转至北宁平缓两线',
        authors: ['毛泽东'],
        page_start: 363,
        page_end: 364,
        dates: [{ year: 1947, month: 10, day: 13 }],
        is_range_date: false,
      },
      {
        title: '东西兵团的指挥和建制等问题',
        authors: ['毛泽东'],
        page_start: 365,
        page_end: 366,
        dates: [{ year: 1947, month: 10, day: 15 }],
        is_range_date: false,
      },
      {
        title: '陈谢部休整后的行动部署',
        authors: ['毛泽东'],
        page_start: 367,
        page_end: 368,
        dates: [{ year: 1947, month: 10, day: 20 }],
        is_range_date: false,
      },
      {
        title: '组织野战机动兵团及分散作战的部署',
        authors: ['毛泽东'],
        page_start: 369,
        page_end: 370,
        dates: [{ year: 1947, month: 10, day: 20 }],
        is_range_date: false,
      },
      {
        title: '同意三军举行大破平汉路战役',
        authors: ['毛泽东'],
        page_start: 371,
        page_end: 371,
        dates: [{ year: 1947, month: 10, day: 21 }],
        is_range_date: false,
      },
      {
        title: '攻石门打援兵的部署叫',
        authors: ['毛泽东'],
        page_start: 372,
        page_end: 374,
        dates: [{ year: 1947, month: 10, day: 23 }],
        is_range_date: false,
      },
      {
        title: '致杨得志、杨成武、耿腿等电',
        authors: ['毛泽东'],
        page_start: 375,
        page_end: 375,
        dates: [{ year: 1947, month: 10, day: 23 }],
        is_range_date: false,
      },
      {
        title: '同意陈菜提早集中主力大破陇海路叫',
        authors: ['毛泽东'],
        page_start: 376,
        page_end: 377,
        dates: [{ year: 1947, month: 10, day: 24 }],
        is_range_date: false,
      },
      {
        title: '对待自由资产阶级须防止过无倾向',
        authors: ['毛泽东'],
        page_start: 378,
        page_end: 379,
        dates: [{ year: 1947, month: 10, day: 26 }],
        is_range_date: false,
      },
      {
        title: '对关于反对刘航探一类反动计划的指示稿的修改和批语',
        authors: ['毛泽东'],
        page_start: 380,
        page_end: 381,
        dates: [{ year: 1947, month: 10, day: 27 }],
        is_range_date: false,
      },
      {
        title: '致刘少奇电',
        authors: ['毛泽东'],
        page_start: 382,
        page_end: 382,
        dates: [{ year: 1947, month: 10, day: 31 }],
        is_range_date: false,
      },
      {
        title: '对佳县县委的指示',
        authors: ['毛泽东'],
        page_start: 383,
        page_end: 383,
        dates: [{ year: 1947, month: 10 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀、张宗逊电',
        authors: ['毛泽东'],
        page_start: 384,
        page_end: 384,
        dates: [{ year: 1947, month: 11, day: 2 }],
        is_range_date: false,
      },
      {
        title: '民盟的教训',
        authors: ['毛泽东'],
        page_start: 385,
        page_end: 386,
        dates: [{ year: 1947, month: 11, day: 3 }],
        is_range_date: false,
      },
      {
        title: '对胡宗南企图打通陇海线应取的方针',
        authors: ['毛泽东'],
        page_start: 387,
        page_end: 387,
        dates: [{ year: 1947, month: 11, day: 4 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀、张宗逊电则',
        authors: ['毛泽东'],
        page_start: 388,
        page_end: 388,
        dates: [{ year: 1947, month: 11, day: 4 }],
        is_range_date: false,
      },
      {
        title: '关于攻取榆林城和打接的问题',
        authors: ['毛泽东'],
        page_start: 389,
        page_end: 389,
        dates: [{ year: 1947, month: 11, day: 5 }],
        is_range_date: false,
      },
      {
        title: '充分准备彻底破毁陇海路注徐段',
        authors: ['毛泽东'],
        page_start: 390,
        page_end: 390,
        dates: [{ year: 1947, month: 11, day: 6 }],
        is_range_date: false,
      },
      {
        title: '我们完全有把握彻底打倒蒋介石反动集团',
        authors: ['毛泽东'],
        page_start: 391,
        page_end: 391,
        dates: [{ year: 1947, month: 11, day: 6 }],
        is_range_date: false,
      },
      {
        title: '庆贺十月革命三十周年致斯大林元帅电',
        authors: ['毛泽东'],
        page_start: 392,
        page_end: 392,
        dates: [{ year: 1947, month: 11, day: 6 }],
        is_range_date: false,
      },
      {
        title: '给傅连障的信',
        authors: ['毛泽东'],
        page_start: 393,
        page_end: 393,
        dates: [{ year: 1947, month: 11, day: 10 }],
        is_range_date: false,
      },
      {
        title: '对敌援军宜先打十八师',
        authors: ['毛泽东'],
        page_start: 394,
        page_end: 394,
        dates: [{ year: 1947, month: 11, day: 11 }],
        is_range_date: false,
      },
      {
        title: '东北局应全力加强军事工业建设支援全国作战',
        authors: ['毛泽东'],
        page_start: 395,
        page_end: 396,
        dates: [{ year: 1947, month: 11, day: 13 }],
        is_range_date: false,
      },
      {
        title: '致杨得志、杨成武、耿腿电',
        authors: ['毛泽东'],
        page_start: 397,
        page_end: 397,
        dates: [{ year: 1947, month: 11, day: 13 }],
        is_range_date: false,
      },
      {
        title: '对集结之敌的打法',
        authors: ['毛泽东'],
        page_start: 398,
        page_end: 398,
        dates: [{ year: 1947, month: 11, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀、张宗逊电',
        authors: ['毛泽东'],
        page_start: 399,
        page_end: 399,
        dates: [{ year: 1947, month: 11, day: 16 }],
        is_range_date: false,
      },
      {
        title: '普察冀野战军准备配合东北作战',
        authors: ['毛泽东'],
        page_start: 400,
        page_end: 401,
        dates: [{ year: 1947, month: 11, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致普察中央局等电',
        authors: ['毛泽东'],
        page_start: 402,
        page_end: 402,
        dates: [{ year: 1947, month: 11, day: 17 }],
        is_range_date: false,
      },
      {
        title: '给陈理昆“的信',
        authors: ['毛泽东'],
        page_start: 403,
        page_end: 403,
        dates: [{ year: 1947, month: 11, day: 18 }],
        is_range_date: false,
      },
      {
        title: '给吴玉章的信',
        authors: ['毛泽东'],
        page_start: 404,
        page_end: 404,
        dates: [{ year: 1947, month: 11, day: 18 }],
        is_range_date: false,
      },
      {
        title: '给张曙时的信',
        authors: ['毛泽东'],
        page_start: 405,
        page_end: 405,
        dates: [{ year: 1947, month: 11, day: 18 }],
        is_range_date: false,
      },
      {
        title: '给吴创国的信',
        authors: ['毛泽东'],
        page_start: 406,
        page_end: 406,
        dates: [{ year: 1947, month: 11, day: 18 }],
        is_range_date: false,
      },
      {
        title: '致王震等电',
        authors: ['毛泽东'],
        page_start: 407,
        page_end: 407,
        dates: [{ year: 1947, month: 11, day: 22 }],
        is_range_date: false,
      },
      {
        title: '出击三边及进攻榆林问题',
        authors: ['毛泽东'],
        page_start: 408,
        page_end: 408,
        dates: [{ year: 1947, month: 11, day: 23 }],
        is_range_date: false,
      },
      {
        title: '给大连大众书店，大众书店同人自治会、大众印刷厂全体职工的信',
        authors: ['毛泽东'],
        page_start: 409,
        page_end: 409,
        dates: [{ year: 1947, month: 11, day: 23 }],
        is_range_date: false,
      },
      {
        title: '陈唐部队目前的中心任务',
        authors: ['毛泽东'],
        page_start: 410,
        page_end: 410,
        dates: [{ year: 1947, month: 11, day: 28 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀、张宗逊电',
        authors: ['毛泽东'],
        page_start: 411,
        page_end: 411,
        dates: [{ year: 1947, month: 11, day: 28 }],
        is_range_date: false,
      },
      {
        title: '致菜裕等电',
        authors: ['毛泽东'],
        page_start: 412,
        page_end: 412,
        dates: [{ year: 1947, month: 11, day: 28 }],
        is_range_date: false,
      },
      {
        title: '在土地改革中注意纠正“左”倾错误',
        authors: ['毛泽东'],
        page_start: 413,
        page_end: 414,
        dates: [{ year: 1947, month: 11, day: 29 }],
        is_range_date: false,
      },
      {
        title: '中共中央发言人严序将美航脏买卖',
        authors: ['毛泽东'],
        page_start: 415,
        page_end: 416,
        dates: [{ year: 1947, month: 12, day: 2 }],
        is_range_date: false,
      },
      {
        title: '同意再打运城',
        authors: ['毛泽东'],
        page_start: 417,
        page_end: 417,
        dates: [{ year: 1947, month: 12, day: 4 }],
        is_range_date: false,
      },
      {
        title: '刘邓军明年的任务',
        authors: ['毛泽东'],
        page_start: 418,
        page_end: 420,
        dates: [{ year: 1947, month: 12, day: 4 }],
        is_range_date: false,
      },
      {
        title: '建立空军已成党的道切任务',
        authors: ['毛泽东'],
        page_start: 421,
        page_end: 421,
        dates: [{ year: 1947, month: 12, day: 5 }],
        is_range_date: false,
      },
      {
        title: '复杨得志、罗瑞卿等电',
        authors: ['毛泽东'],
        page_start: 422,
        page_end: 422,
        dates: [{ year: 1947, month: 12, day: 7 }],
        is_range_date: false,
      },
      {
        title: '致刘伯承、邓小平等电',
        authors: ['毛泽东'],
        page_start: 423,
        page_end: 423,
        dates: [{ year: 1947, month: 12, day: 8 }],
        is_range_date: false,
      },
      {
        title: '菜部与陈谢部配合攻击平汉路',
        authors: ['毛泽东'],
        page_start: 424,
        page_end: 425,
        dates: [{ year: 1947, month: 12, day: 9 }],
        is_range_date: false,
      },
      {
        title: '自前华野仍以打中等规模之仗为有利',
        authors: ['毛泽东'],
        page_start: 426,
        page_end: 426,
        dates: [{ year: 1947, month: 12, day: 9 }],
        is_range_date: false,
      },
      {
        title: '菜裕及陈谢两部长期配合刘邓行动的部署叫',
        authors: ['毛泽东'],
        page_start: 427,
        page_end: 428,
        dates: [{ year: 1947, month: 12, day: 20 }],
        is_range_date: false,
      },
      {
        title: '菜裕部可南下破路弃故',
        authors: ['毛泽东'],
        page_start: 429,
        page_end: 429,
        dates: [{ year: 1947, month: 12, day: 20 }],
        is_range_date: false,
      },
      {
        title: '改造旧艺术创造新艺术',
        authors: ['毛泽东'],
        page_start: 430,
        page_end: 433,
        dates: [{ year: 1947, month: 12, day: 21 }],
        is_range_date: false,
      },
      {
        title: '致菜裕等电',
        authors: ['毛泽东'],
        page_start: 434,
        page_end: 434,
        dates: [{ year: 1947, month: 12, day: 21 }],
        is_range_date: false,
      },
      {
        title: '关于东北冬季作战的部署',
        authors: ['毛泽东'],
        page_start: 435,
        page_end: 436,
        dates: [{ year: 1947, month: 12, day: 23 }],
        is_range_date: false,
      },
      {
        title: '新华社记者评南线我军破击战大捷',
        authors: ['毛泽东'],
        page_start: 437,
        page_end: 472,
        dates: [{ year: 1947, month: 12, day: 24 }],
        is_range_date: false,
      },
      {
        title: '八两纵的作战任务',
        authors: ['毛泽东'],
        page_start: 473,
        page_end: 473,
        dates: [{ year: 1947, month: 12, day: 29 }],
        is_range_date: false,
      },
      {
        title: '致林彪、罗荣柜电',
        authors: ['毛泽东'],
        page_start: 474,
        page_end: 474,
        dates: [{ year: 1947, month: 12, day: 29 }],
        is_range_date: false,
      },
      {
        title: '为延安中学某同志题词',
        authors: ['毛泽东'],
        page_start: 475,
        page_end: 475,
        dates: [{ year: 1947 }],
        is_range_date: false,
      },
      {
        title: '致王益久电',
        authors: ['毛泽东'],
        page_start: 476,
        page_end: 477,
        dates: [{ year: 1947 }],
        is_range_date: false,
      },
      {
        title: '三条理由和三条规定',
        authors: ['毛泽东'],
        page_start: 478,
        page_end: 478,
        dates: [{ year: 1947 }],
        is_range_date: false,
      },
      {
        title: '为《抗日游击战争的战术问题》题名',
        authors: ['毛泽东'],
        page_start: 479,
        page_end: 481,
        dates: [{ year: 1947 }],
        is_range_date: false,
      },
      {
        title: '五律·张冠道中间',
        authors: ['毛泽东'],
        page_start: 482,
        page_end: 482,
        dates: [{ year: 1947 }],
        is_range_date: false,
      },
      {
        title: '五律·喜闻捷报',
        authors: ['毛泽东'],
        page_start: 483,
        page_end: 488,
        dates: [{ year: 1947 }],
        is_range_date: false,
      },
      {
        title: '庆祝刘邓大军之胜利',
        authors: ['毛泽东'],
        page_start: 489,
        page_end: 489,
        dates: [{ year: 1948, month: 1, day: 1 }],
        is_range_date: false,
      },
      {
        title: '三军协力解决大别山困难',
        authors: ['毛泽东'],
        page_start: 490,
        page_end: 493,
        dates: [{ year: 1948, month: 1, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致林彪、罗荣植等电',
        authors: ['毛泽东'],
        page_start: 494,
        page_end: 494,
        dates: [{ year: 1948, month: 1, day: 6 }],
        is_range_date: false,
      },
      {
        title: '关于建立报告制度',
        authors: ['毛泽东'],
        page_start: 495,
        page_end: 497,
        dates: [{ year: 1948, month: 1, day: 7 }],
        is_range_date: false,
      },
      {
        title: '对某些铁路不破坏或只作战术性破坏',
        authors: ['毛泽东'],
        page_start: 498,
        page_end: 498,
        dates: [{ year: 1948, month: 1, day: 8 }],
        is_range_date: false,
      },
      {
        title: '应向全军施行政策与纪律教育',
        authors: ['毛泽东'],
        page_start: 499,
        page_end: 499,
        dates: [{ year: 1948, month: 1, day: 9 }],
        is_range_date: false,
      },
      {
        title: '中原和西北地区的作战部署',
        authors: ['毛泽东'],
        page_start: 500,
        page_end: 502,
        dates: [{ year: 1948, month: 1, day: 9 }],
        is_range_date: false,
      },
      {
        title: '对习仲勋关于检查绥属各县土地改革情况的报告的批示',
        authors: ['毛泽东'],
        page_start: 503,
        page_end: 504,
        dates: [{ year: 1948, month: 1, day: 9 }],
        is_range_date: false,
      },
      {
        title: '对菜裕部在宽大区域机动作战的指示',
        authors: ['毛泽东'],
        page_start: 505,
        page_end: 506,
        dates: [{ year: 1948, month: 1, day: 10 }],
        is_range_date: false,
      },
      {
        title: '对可以争取的中间派应采取积极争取与合作态度',
        authors: ['毛泽东'],
        page_start: 507,
        page_end: 508,
        dates: [{ year: 1948, month: 1, day: 14 }],
        is_range_date: false,
      },
      {
        title: '征询邓小平对新解放区若干政策问题的意见',
        authors: ['毛泽东'],
        page_start: 509,
        page_end: 510,
        dates: [{ year: 1948, month: 1, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致菜裕、陈士渠、唐亮等电',
        authors: ['毛泽东'],
        page_start: 511,
        page_end: 511,
        dates: [{ year: 1948, month: 1, day: 14 }],
        is_range_date: false,
      },
      {
        title: '对中共中央关于执行土地法的指示草案的意见',
        authors: ['毛泽东'],
        page_start: 512,
        page_end: 512,
        dates: [{ year: 1948, month: 1, day: 14 }],
        is_range_date: false,
      },
      {
        title: '在西北野战军前委扩大会议上的讲语',
        authors: ['毛泽东'],
        page_start: 513,
        page_end: 525,
        dates: [{ year: 1948, month: 1, day: 15 }],
        is_range_date: false,
      },
      {
        title: '边区政权机关不应只代表农民',
        authors: ['毛泽东'],
        page_start: 526,
        page_end: 527,
        dates: [{ year: 1948, month: 1, day: 16 }],
        is_range_date: false,
      },
      {
        title: '关于目前党的政策中的几个重要问题',
        authors: ['毛泽东'],
        page_start: 528,
        page_end: 534,
        dates: [{ year: 1948, month: 1, day: 18 }],
        is_range_date: false,
      },
      {
        title: '致刘少奇电',
        authors: ['毛泽东'],
        page_start: 535,
        page_end: 535,
        dates: [{ year: 1948, month: 1, day: 18 }],
        is_range_date: false,
      },
      {
        title: '转发习仲勋关于西北土改工作情况的报告的批语',
        authors: ['毛泽东'],
        page_start: 536,
        page_end: 536,
        dates: [{ year: 1948, month: 1, day: 20 }],
        is_range_date: false,
      },
      {
        title: '新解放区土改斗争策略',
        authors: ['毛泽东'],
        page_start: 537,
        page_end: 541,
        dates: [{ year: 1948, month: 1, day: 22 }],
        is_range_date: false,
      },
      {
        title: '对中央一月决定“的补充意见',
        authors: ['毛泽东'],
        page_start: 542,
        page_end: 543,
        dates: [{ year: 1948, month: 1, day: 24 }],
        is_range_date: false,
      },
      {
        title: '南线三军三个月的作战方针',
        authors: ['毛泽东'],
        page_start: 544,
        page_end: 546,
        dates: [{ year: 1948, month: 1, day: 26 }],
        is_range_date: false,
      },
      {
        title: '致菜裕电',
        authors: ['毛泽东'],
        page_start: 547,
        page_end: 548,
        dates: [{ year: 1948, month: 1, day: 27 }],
        is_range_date: false,
      },
      {
        title: '来取潮海整军经验开展军队的民主运动',
        authors: ['毛泽东'],
        page_start: 549,
        page_end: 549,
        dates: [{ year: 1948, month: 1, day: 28 }],
        is_range_date: false,
      },
    ],
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives8/maoquanji23.pdf',
};
