export default {
  entity: {
    id: 'maoquanji51',
    name: '毛泽东全集第51卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives0/main/mao-quanji/maoquanji51.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
    articles: [
      {
        page_start: 29,
        page_end: 35,
        title: '和黎笋的谈话',
        dates: [{ year: 1970, month: 5, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 36,
        page_end: 38,
        title: '全世界人民团结起来，打败美国侵略者及其一切走狗',
        dates: [{ year: 1970, month: 5, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 49,
        page_end: 50,
        title: '转发武汉军区党委抓点情况报告的批语',
        dates: [{ year: 1970, month: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 51,
        page_end: 51,
        title:
          '对中央转发北京二七机车厂、上海国棉十七厂整党建党情况报告的指示稿的批语',
        dates: [{ year: 1970, month: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 52,
        page_end: 52,
        title: '对中央关于开展增产节约运动指示稿的批语',
        dates: [{ year: 1970, month: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 53,
        page_end: 53,
        title: '对理工科大学教学改革两份材料的批语',
        dates: [{ year: 1970, month: 6, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 54,
        page_end: 54,
        title: '现代化武器吓不倒人民',
        dates: [{ year: 1970, month: 6, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 56,
        page_end: 57,
        title: '和苏丹政府友好代表团团长马哈古卜谈话纪要',
        dates: [{ year: 1970, month: 6, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 58,
        page_end: 59,
        title: '转发全国重点钢铁企业座谈会纪要和煤炭工业会议情况报告的批语',
        dates: [{ year: 1970, month: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 60,
        page_end: 60,
        title: '暂不发表毛泽东关于医疗卫生工作谈话整理稿的批语',
        dates: [{ year: 1970, month: 6, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 61,
        page_end: 61,
        title: '为铁道兵司令部工作人员题词',
        dates: [{ year: 1970, month: 6, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 63,
        page_end: 64,
        title: '帝国主义怕第三世界',
        dates: [{ year: 1970, month: 7, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 65,
        page_end: 66,
        title: '国际间的事要由大家商量解决',
        dates: [{ year: 1970, month: 7, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 68,
        page_end: 68,
        title: '要研究海军落后的原因',
        dates: [{ year: 1970, month: 7, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 69,
        page_end: 69,
        title: '对刘少奇、王光美专案组关于王光美处理意见的报告的批语',
        dates: [{ year: 1970, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 70,
        page_end: 71,
        title: '毛泽东等祝贺罗马尼亚解放二十六周年的电报',
        dates: [{ year: 1970, month: 8, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 74,
        page_end: 77,
        title: '我的一点意见',
        dates: [{ year: 1970, month: 8, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 78,
        page_end: 78,
        title: '对政治局讨论中央关于西藏社会主义改造问题指示草案情况报告的批语',
        dates: [{ year: 1970, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 79,
        page_end: 80,
        title: '毛泽东等祝贺越南民主共和国宣布独立二十五周年的电报',
        dates: [{ year: 1970, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 81,
        page_end: 81,
        title: '对江西找到大盐矿报告的批语',
        dates: [{ year: 1970, month: 9, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 82,
        page_end: 83,
        title: '在中共九届二中全会闭幕会上的讲话',
        dates: [{ year: 1970, month: 9, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 86,
        page_end: 86,
        title: '对中共九届二中全会公报稿的批语',
        dates: [{ year: 1970, month: 9, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 87,
        page_end: 88,
        title: '毛泽东等祝贺朝鲜民主主义人民共和国成立二十二周年的电报',
        dates: [{ year: 1970, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 89,
        page_end: 89,
        title: '对中央关于组织群众广泛讨论宪法修改草案通知稿的批语',
        dates: [{ year: 1970, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 90,
        page_end: 91,
        title: '在南京军区等单位传达九届二中全会精神情况摘要上的批语',
        dates: [{ year: 1970, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 92,
        page_end: 93,
        title: '关于海上作战等问题',
        dates: [{ year: 1970, month: 9, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 94,
        page_end: 94,
        title: '关于党的高级干部读书问题的批语',
        dates: [{ year: 1970, month: 9, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 106,
        page_end: 108,
        title: '对抗美援朝决策的回顾',
        dates: [{ year: 1970, month: 10, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 109,
        page_end: 113,
        title: '对吴法宪检讨信的批语和批注',
        dates: [{ year: 1970, month: 10, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 114,
        page_end: 118,
        title: '对叶群检讨信的批语和批注',
        dates: [{ year: 1970, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 119,
        page_end: 119,
        title: '对中央关于召开地方各级党代表大会通知稿的批语',
        dates: [{ year: 1970, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 120,
        page_end: 120,
        title: '关于同意会见美国作家斯诺的批语',
        dates: [{ year: 1970, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 121,
        page_end: 121,
        title: '悼念戴高乐逝世的电',
        dates: [{ year: 1970, month: 11, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 122,
        page_end: 122,
        title: '和巴基斯坦总统叶海亚的谈话',
        dates: [{ year: 1970, month: 11, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 124,
        page_end: 125,
        title: '同意印发《我的一点意见》的批语',
        dates: [{ year: 1970, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 127,
        page_end: 128,
        title: '在北京卫戌区关于部队战备野营拉练总结报告上的批语',
        dates: [
          { year: 1970, month: 11 },
          { year: 1970, month: 12 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 131,
        page_end: 132,
        title: '毛泽东等祝贺阿尔巴尼亚解放二十六周年的电报',
        dates: [{ year: 1970, month: 11, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 133,
        page_end: 133,
        title: '不要求外国人承认中国人的思想',
        dates: [{ year: 1970, month: 12, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 134,
        page_end: 134,
        title: '对中央关于加强安全生产的通知稿的批语',
        dates: [{ year: 1970, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 135,
        page_end: 135,
        title: '在三十八军检举陈伯达反党罪行报告上的批语',
        dates: [{ year: 1970, month: 12, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 136,
        page_end: 156,
        title: '会见斯诺的谈话纪要',
        dates: [{ year: 1970, month: 12, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 157,
        page_end: 158,
        title: '关于开好华北会议的批语',
        dates: [{ year: 1970, month: 12, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 159,
        page_end: 160,
        title: '毛泽东等祝贺越南南方民族解放阵线成立十周年的电报',
        dates: [{ year: 1970, month: 12, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 161,
        page_end: 161,
        title: '在《参考消息》第四三七七期上的批语',
        dates: [{ year: 1970, month: 12, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 162,
        page_end: 162,
        title: '对姚文元关于最近学习情况等问题报告的批语',
        dates: [{ year: 1970, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 163,
        page_end: 163,
        title: '转载英国《卫报》有关中国对东海大陆架拥有主权文章的批语',
        dates: [{ year: 1970, month: 12, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 164,
        page_end: 164,
        title: '关于同意兴建葛洲坝水利枢纽工程的批语',
        dates: [{ year: 1970, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 168,
        page_end: 169,
        title: '对江青在华北会议上的讲话的批语',
        dates: [{ year: 1971, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 170,
        page_end: 171,
        title: '转发济南军区政治部学习贯彻毛泽东“军队要谨慎”指示情况报告的批语',
        dates: [{ year: 1971, month: 1, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 172,
        page_end: 173,
        title: '对周恩来在华北会议上的讲话提纲的批语',
        dates: [{ year: 1971, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 174,
        page_end: 174,
        title: '对张秀龙来信的批语',
        dates: [{ year: 1971, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 175,
        page_end: 175,
        title: '关于批陈整风运动重点在批陈的批语',
        dates: [{ year: 1971, month: 2, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 176,
        page_end: 177,
        title: '在军委办事组关于学习讨论毛主席“重点在批陈”指示情况报告上的批语',
        dates: [{ year: 1971, month: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 178,
        page_end: 178,
        title: '在外交部关于美国人来华问题请示报告上的批语',
        dates: [{ year: 1971, month: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 179,
        page_end: 179,
        title: '应对南昌起义和朱毛两军会师作正确解说',
        dates: [{ year: 1971, month: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 180,
        page_end: 180,
        title: '对军委办事组传达毛泽东批陈整风指示报告的批语',
        dates: [{ year: 1971, month: 3, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 181,
        page_end: 181,
        title: '对中国党政代表团访问越南的两个文件送审稿的批语',
        dates: [{ year: 1971, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 182,
        page_end: 183,
        title: '对两报一刊编辑部文章《无产阶级专政胜利万岁》送审稿的批语',
        dates: [{ year: 1971, month: 3, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 184,
        page_end: 184,
        title: '对成功发射“实践一号”科学实验卫星新闻稿的批语',
        dates: [{ year: 1971, month: 3, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 185,
        page_end: 185,
        title: '对黄永胜、邱会作、李作鹏的检讨信的批语',
        dates: [{ year: 1971, month: 3, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 186,
        page_end: 187,
        title: '毛泽东等祝贺印度支那三国人民抗美救国战争伟大胜利的电报',
        dates: [{ year: 1971, month: 3, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 188,
        page_end: 189,
        title: '对召开批陈整风汇报会议等问题的批语',
        dates: [{ year: 1971, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 192,
        page_end: 193,
        title: '关于黄、吴、叶、李、邱的自我批评的批语',
        dates: [{ year: 1971, month: 4, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 194,
        page_end: 195,
        title: '在李德生报告上的批语',
        dates: [{ year: 1971, month: 4, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 196,
        page_end: 197,
        title: '对周恩来关于批陈整风汇报会议请示报告的批语',
        dates: [{ year: 1971, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 198,
        page_end: 198,
        title: '对周恩来批陈整风汇报会议讲话提纲的批语',
        dates: [{ year: 1971, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 199,
        page_end: 199,
        title: '对周恩来的信和报送材料的批语',
        dates: [{ year: 1971, month: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 201,
        page_end: 201,
        title: '会见齐奥塞斯库率领的罗马尼亚党政代表团谈话的报道',
        dates: [{ year: 1971, month: 6, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 203,
        page_end: 204,
        title: '毛泽东等祝贺中朝友好合作互助条约签订十周年的电报',
        dates: [{ year: 1971, month: 7, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 205,
        page_end: 206,
        title: '毛泽东等祝贺罗马尼亚解放二十七周年的电报',
        dates: [{ year: 1971, month: 8, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 207,
        page_end: 207,
        title: '对中央关于新疆、云南少数民族地区划分阶级成分问题指示稿的批语',
        dates: [{ year: 1971, month: 8, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 208,
        page_end: 208,
        title: '清平乐·视察*',
        dates: [{ year: 1971, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 209,
        page_end: 209,
        title: '对中央转发《全国教育工作会议纪要》的批语',
        dates: [{ year: 1971, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 210,
        page_end: 210,
        title: '对中央转发《广州军区三支两军政治思想工作座谈会纪要》的批语',
        dates: [{ year: 1971, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 211,
        page_end: 221,
        title: '在外地巡视期间和沿途各地负责人谈话纪要',
        dates: [
          { year: 1971, month: 8 },
          { year: 1971, month: 9 },
        ],
        is_range_date: true,
        authors: ['毛泽东'],
      },
      {
        page_start: 223,
        page_end: 225,
        title: '在武昌和华国锋、汪东兴的谈话',
        dates: [{ year: 1971, month: 8, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 226,
        page_end: 227,
        title: '在长沙和华国锋、卜占亚、汪东兴的谈话（摘要）',
        dates: [{ year: 1971, month: 8, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 228,
        page_end: 233,
        title: '在长沙和刘兴元、丁盛、韦国清、汪东兴的谈话',
        dates: [{ year: 1971, month: 8, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 234,
        page_end: 240,
        title: '在长沙和刘兴元、丁盛、韦国清、华国锋、卜占亚及汪东兴的谈话',
        dates: [{ year: 1971, month: 8, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 241,
        page_end: 242,
        title: '在南昌和许世友、韩先楚、程世清、汪东兴的谈话',
        dates: [{ year: 1971, month: 8, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 243,
        page_end: 245,
        title: '在杭州和南萍、熊应堂、陈励耘、汪东兴的谈话',
        dates: [{ year: 1971, month: 9, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 246,
        page_end: 249,
        title: '在丰台和李德生、纪登奎、吴德、吴忠、汪东兴的谈话',
        dates: [{ year: 1971, month: 9, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 250,
        page_end: 251,
        title: '毛泽东等祝贺越南民主共和国成立二十六周年的电报',
        dates: [{ year: 1971, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 252,
        page_end: 253,
        title: '毛泽东等对越南北方遭受严重水灾的慰问电',
        dates: [{ year: 1971, month: 9, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 254,
        page_end: 255,
        title: '毛泽东等祝贺朝鲜民主主义人民共和国成立二十三周年的电报',
        dates: [{ year: 1971, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 256,
        page_end: 256,
        title: '对周恩来关于召开九届三中全会等问题请示报告的批语',
        dates: [{ year: 1971, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 257,
        page_end: 257,
        title: '对中央关于林彪叛国出逃、自取灭亡通知稿的批语',
        dates: [{ year: 1971, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 259,
        page_end: 259,
        title: '对中央关于黄永胜等离职反省通知稿的批语',
        dates: [{ year: 1971, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 260,
        page_end: 260,
        title: '对成立中央专案组的通知稿的批语',
        dates: [{ year: 1971, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 261,
        page_end: 261,
        title: '对中央关于撤销军委办事组通知稿的批语',
        dates: [{ year: 1971, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 262,
        page_end: 270,
        title: '恢复联合国席位后的谈话',
        dates: [
          { year: 1971, month: 10, day: 26 },
          { year: 1971, month: 11, day: 8 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 272,
        page_end: 274,
        title: '接见参加成都地区座谈会的人员时的谈话（节录）',
        dates: [{ year: 1971, month: 11, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 275,
        page_end: 275,
        title: '在外交部关于为出席第二十六届联大代表团送行计划报告上的批语',
        dates: [{ year: 1971, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 276,
        page_end: 276,
        title: '对中国代表团到达纽约机场的书面讲话稿的批语',
        dates: [{ year: 1971, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 277,
        page_end: 277,
        title: '对中国代表团团长在联合国大会发言稿的批语',
        dates: [{ year: 1971, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 278,
        page_end: 279,
        title: '毛泽东等祝贺阿尔巴尼亚解放二十七周年的电报',
        dates: [{ year: 1971, month: 11, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 280,
        page_end: 280,
        title:
          '对中央关于传达、讨论《粉碎林陈反党集团反革命政变的斗争（材料之一）》通知稿的批语',
        dates: [{ year: 1971, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 281,
        page_end: 282,
        title: '毛泽东等祝贺越南南方民族解放阵线成立十一周年的电报',
        dates: [{ year: 1971, month: 12, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 283,
        page_end: 283,
        title: '对中央关于农村人民公社分配问题指示稿的批语',
        dates: [{ year: 1971, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 285,
        page_end: 285,
        title: '四言诗·题折扇',
        dates: [{ year: 1971 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 286,
        page_end: 286,
        title: '七绝·戏改李攀龙《怀明卿》',
        dates: [{ year: 1971 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 287,
        page_end: 287,
        title: '七言诗·戏改杜甫《咏怀古迹》其三',
        dates: [{ year: 1971 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 288,
        page_end: 288,
        title: '七绝·读《红楼梦》',
        dates: [{ year: 1971 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 290,
        page_end: 290,
        title: '对陈毅悼词的批语',
        dates: [{ year: 1972, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 293,
        page_end: 293,
        title: '对吴冷西来信的批语',
        dates: [{ year: 1972, month: 1, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 294,
        page_end: 294,
        title: '对李卓然、何长工来信的批语',
        dates: [
          { year: 1972, month: 1 },
          { year: 1972, month: 9 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 295,
        page_end: 295,
        title: '悼念斯诺逝世的电',
        dates: [{ year: 1972, month: 2, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 296,
        page_end: 304,
        title: '会见尼克松时的谈话',
        dates: [{ year: 1972, month: 2, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 311,
        page_end: 311,
        title: '四言诗·赠尼克松总统',
        dates: [{ year: 1972 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 312,
        page_end: 312,
        title: '对苏振华来信的批语',
        dates: [{ year: 1972, month: 3, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 313,
        page_end: 313,
        title: '对外交部关于中美联合公报通报稿的批语',
        dates: [{ year: 1972, month: 3, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 314,
        page_end: 314,
        title: '对编发尼克松访华和中美联合公报国际反映的请示报告的批语',
        dates: [{ year: 1972, month: 3, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 315,
        page_end: 315,
        title: '对杨成武家属来信的批语',
        dates: [{ year: 1972, month: 3, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 316,
        page_end: 317,
        title: '毛泽东等祝贺金日成六十寿辰的电报',
        dates: [{ year: 1972, month: 4, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 318,
        page_end: 319,
        title: '毛泽东等祝贺朝鲜人民革命军成立四十周年的电报',
        dates: [{ year: 1972, month: 4, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 320,
        page_end: 320,
        title: '对反映白坚情况摘报的批语',
        dates: [{ year: 1972, month: 5, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 321,
        page_end: 321,
        title: '对李克如来信的批语',
        dates: [{ year: 1972, month: 6, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 322,
        page_end: 322,
        title: '对贺诚来信的批语',
        dates: [{ year: 1972, month: 6, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 324,
        page_end: 325,
        title: '对廖汉生家属来信的批语',
        dates: [{ year: 1972, month: 7, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 326,
        page_end: 326,
        title: '苏联的政策是声东击西',
        dates: [{ year: 1972, month: 7, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 327,
        page_end: 327,
        title: '对陈云来信的批语',
        dates: [{ year: 1972, month: 7, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 328,
        page_end: 328,
        title: '对外交部关于向美国友人等谈林彪问题的请示报告的批语',
        dates: [{ year: 1972, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 329,
        page_end: 329,
        title: '为王季范题挽词',
        dates: [{ year: 1972, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 330,
        page_end: 330,
        title: '在林枫家属来信摘要上的批语',
        dates: [{ year: 1972, month: 8, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 331,
        page_end: 332,
        title: '对邓小平来信的批语',
        dates: [{ year: 1972, month: 8, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 333,
        page_end: 334,
        title: '毛泽东等祝贺罗马尼亚解放二十八周年的电报',
        dates: [{ year: 1972, month: 8, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 335,
        page_end: 336,
        title: '毛泽东等祝贺越南民主共和国成立二十七周年的电报',
        dates: [{ year: 1972, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 337,
        page_end: 337,
        title: '在赠周世钊《两般秋雨庵随笔》一书封面上的题字',
        dates: [{ year: 1972, month: 9, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 338,
        page_end: 338,
        title: '给周世钊的信',
        dates: [{ year: 1972, month: 9, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 339,
        page_end: 339,
        title:
          '对中央转发外交部《关于接待日本田中首相访华的内部宣传提纲》的通知稿的批语',
        dates: [{ year: 1972, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 340,
        page_end: 341,
        title: '毛泽东等祝贺朝鲜民主主义人民共和国成立二十四周年的电报',
        dates: [{ year: 1972, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 342,
        page_end: 346,
        title: '解决中日复交问题，日方还是靠自民党政府',
        dates: [{ year: 1972, month: 9, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 352,
        page_end: 352,
        title: '对海军党委扩大会议如何开展批林整风的意见',
        dates: [{ year: 1972 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 353,
        page_end: 353,
        title: '对国防工业院校存在问题及改进意见的批语',
        dates: [{ year: 1972, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 354,
        page_end: 355,
        title: '在反映许涤新、范长江、江一真、李一夫情况来信摘要上的批语',
        dates: [
          { year: 1972, month: 10 },
          { year: 1972, month: 12 },
        ],
        is_range_date: true,
        authors: ['毛泽东'],
      },
      {
        page_start: 356,
        page_end: 356,
        title: '对华罗庚来信的批语',
        dates: [{ year: 1972, month: 11, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 357,
        page_end: 358,
        title: '在反映柴沫情况的两封来信摘报上的批语',
        dates: [
          { year: 1972, month: 11, day: 4 },
          { year: 1972, month: 12, day: 5 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 359,
        page_end: 359,
        title: '在周培源关于六六至七○届大专毕业生转正定级问题来信上的批语',
        dates: [{ year: 1972, month: 11, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 360,
        page_end: 360,
        title: '对中南海门诊部关于周恩来心脏病情况报告的批语',
        dates: [{ year: 1972, month: 11, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 361,
        page_end: 362,
        title: '毛泽东等祝贺阿尔巴尼亚独立六十周年和解放二十八周年的电报',
        dates: [{ year: 1972, month: 11, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 363,
        page_end: 363,
        title: '深挖洞，广积粮，不称霸',
        dates: [{ year: 1972, month: 12, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 364,
        page_end: 364,
        title: '对反映国防科研单位一些问题来信的批语',
        dates: [{ year: 1972, month: 12, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 365,
        page_end: 366,
        title: '毛泽东等祝贺金日成当选朝鲜民主主义人民共和国主席的电报',
        dates: [{ year: 1972, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 367,
        page_end: 367,
        title: '会见越南南方共和临时政府外长阮氏萍谈话的报道',
        dates: [{ year: 1972, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 368,
        page_end: 368,
        title: '对刘建章家属来信的批语',
        dates: [{ year: 1972, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 370,
        page_end: 370,
        title: '在王稼祥来信上的批语',
        dates: [{ year: 1972, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 371,
        page_end: 371,
        title: '赠刘兴元联',
        dates: [{ year: 1972 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 373,
        page_end: 373,
        title: '对谭震林来信的批语',
        dates: [{ year: 1973, month: 1, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 377,
        page_end: 379,
        title: '毛泽东等祝贺《越南问题的巴黎协定》正式签订的电报',
        dates: [{ year: 1973, month: 1, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 381,
        page_end: 382,
        title: '对反映李一氓、舒同、林铁情况来信的批语',
        dates: [
          { year: 1973, month: 1 },
          { year: 1973, month: 6 },
        ],
        is_range_date: true,
        authors: ['毛泽东'],
      },
      {
        page_start: 383,
        page_end: 399,
        title: '接见基辛格时的谈话',
        dates: [
          { year: 1973, month: 2 },
          { year: 1973, month: 11 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 401,
        page_end: 402,
        title:
          '对周恩来送审的中央关于恢复邓小平党组织生活和国务院副总理职务决定稿的批语',
        dates: [{ year: 1973, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 404,
        page_end: 404,
        title: '五绝·呈郭老',
        dates: [{ year: 1973 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 406,
        page_end: 406,
        title: '给李庆霖的信',
        dates: [{ year: 1973, month: 4, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 407,
        page_end: 407,
        title: '七言诗·外交家风采联句',
        dates: [{ year: 1973, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 408,
        page_end: 408,
        title: '对谭政来信的批语',
        dates: [{ year: 1973, month: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 409,
        page_end: 410,
        title: '会见外宾几次谈话的报道',
        dates: [
          { year: 1973, month: 6 },
          { year: 1973, month: 11 },
        ],
        is_range_date: true,
        authors: ['毛泽东'],
      },
      {
        page_start: 413,
        page_end: 413,
        title: '会见马里国家元首特拉奥雷时的谈话（节录）',
        dates: [{ year: 1973, month: 6, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 415,
        page_end: 415,
        title: '对叶飞来信的批语',
        dates: [{ year: 1973, month: 6, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 416,
        page_end: 420,
        title: '和王洪文、张春桥的谈话',
        dates: [{ year: 1973, month: 7, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 421,
        page_end: 421,
        title: '七言诗·戏续李白《梁甫吟》',
        dates: [{ year: 1973, month: 7, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 422,
        page_end: 423,
        title: '在周恩来给外交部党的核心小组及美大组的一封信上的批语',
        dates: [{ year: 1973, month: 7, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 424,
        page_end: 424,
        title: '对中共十大政治报告稿的批语',
        dates: [{ year: 1973, month: 7, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 430,
        page_end: 430,
        title: '对廖静文来信的批语',
        dates: [{ year: 1973, month: 7, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 432,
        page_end: 433,
        title: '和恩古瓦比的谈话',
        dates: [{ year: 1973, month: 7, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 434,
        page_end: 434,
        title: '对郭化若来信的批语',
        dates: [{ year: 1973, month: 8, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 436,
        page_end: 437,
        title: '七律·读《封建论》呈郭老',
        dates: [{ year: 1973, month: 8, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 438,
        page_end: 439,
        title: '毛泽东等祝贺朝鲜民主主义人民共和国成立二十五周年的电报',
        dates: [{ year: 1973, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 441,
        page_end: 441,
        title: '要办好工农兵干部学习班',
        dates: [{ year: 1973 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 444,
        page_end: 444,
        title: '对罗瑞卿来信的批语',
        dates: [{ year: 1973, month: 11, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 445,
        page_end: 445,
        title: '对批评江青的一封信的批语',
        dates: [{ year: 1973, month: 11, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 449,
        page_end: 450,
        title: '毛泽东等祝贺阿尔巴尼亚解放二十九周年的电报',
        dates: [{ year: 1973, month: 11, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 451,
        page_end: 451,
        title: '对江青诬陷周恩来的批评',
        dates: [{ year: 1973, month: 12, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 452,
        page_end: 452,
        title: '中国将修建青藏铁路',
        dates: [{ year: 1973, month: 12, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 453,
        page_end: 461,
        title: '关于大军区司令员对调等问题的谈话要点',
        dates: [{ year: 1973, month: 12, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 463,
        page_end: 463,
        title: '赠邓小平联',
        dates: [{ year: 1973, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 465,
        page_end: 465,
        title: '对王洪文、江青报送的《林彪与孔孟之道（材料之一）》的批语',
        dates: [{ year: 1974, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 466,
        page_end: 466,
        title: '为广西大藤峡题字',
        dates: [{ year: 1974, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 468,
        page_end: 472,
        title: '给江青的信和批语',
        dates: [
          { year: 1974, month: 2 },
          { year: 1974, month: 11 },
        ],
        is_range_date: true,
        authors: ['毛泽东'],
      },
      {
        page_start: 473,
        page_end: 473,
        title: '给叶剑英的信',
        dates: [{ year: 1974, month: 2, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 474,
        page_end: 476,
        title: '和卡翁达、布迈丁谈话内容的通报',
        dates: [
          { year: 1974, month: 2, day: 22 },
          { year: 1974, month: 2, day: 25 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 479,
        page_end: 480,
        title: '和尼雷尔谈话主要内容的通报',
        dates: [{ year: 1974, month: 3, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 482,
        page_end: 483,
        title: '对邓小平在联大特别会议发言稿的批语',
        dates: [{ year: 1974, month: 4, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 488,
        page_end: 491,
        title: '和希思谈话内容的通报',
        dates: [{ year: 1974, month: 5, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 496,
        page_end: 500,
        title: '对“四人帮”的几次批评',
        dates: [{ year: 1974 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 501,
        page_end: 502,
        title: '毛泽东等祝贺罗马尼亚解放三十周年的电报',
        dates: [{ year: 1974, month: 8, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 503,
        page_end: 503,
        title: '以安定团结为好',
        dates: [{ year: 1974 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 505,
        page_end: 505,
        title: '对外交部关于美议员访华团成员问题请示报告的批语',
        dates: [{ year: 1974, month: 8, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 507,
        page_end: 507,
        title: '浪淘沙·赠王洪文同志*',
        dates: [{ year: 1974, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 508,
        page_end: 508,
        title: '对陈不显来信的批语',
        dates: [{ year: 1974, month: 9, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 513,
        page_end: 513,
        title: '关于四届人大筹备工作和人事安排的一点意见',
        dates: [{ year: 1974, month: 10, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 516,
        page_end: 516,
        title: '和邓小平在长沙的一次谈话（节录）',
        dates: [{ year: 1974, month: 11, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 518,
        page_end: 518,
        title: '对外交部《关于与基辛格会谈方案的请示》的批语',
        dates: [{ year: 1974, month: 11, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 519,
        page_end: 520,
        title: '毛泽东等祝贺阿尔巴尼亚解放三十周年的电报',
        dates: [{ year: 1974, month: 11, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 521,
        page_end: 521,
        title: '把国民经济搞上去',
        dates: [{ year: 1974, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 522,
        page_end: 522,
        title: '对电影《园丁之歌》的评价',
        dates: [{ year: 1974, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 523,
        page_end: 523,
        title: '对反映刘景范情况来信的批语',
        dates: [{ year: 1974, month: 12, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 524,
        page_end: 525,
        title: '关于理论问题的谈话要点',
        dates: [{ year: 1974, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 527,
        page_end: 527,
        title: '关于民兵不要参与两派对立的意见',
        dates: [{ year: 1974, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 528,
        page_end: 529,
        title: '关于国际问题几次谈话的要点',
        dates: [{ year: 1974 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 530,
        page_end: 531,
        title: '周恩来在政治局常委会上传达的毛泽东谈话要点（节录）',
        dates: [{ year: 1974 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 532,
        page_end: 532,
        title: '诉衷情',
        dates: [{ year: 1974 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 535,
        page_end: 535,
        title: '给江青的信',
        dates: [{ year: 1975, month: 1, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 539,
        page_end: 539,
        title: '印发张春桥、姚文元摘录的列宁关于无产阶级专政论述的批语',
        dates: [{ year: 1975, month: 2, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 540,
        page_end: 541,
        title: '关于释放战犯问题的意见',
        dates: [{ year: 1975, month: 2, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 542,
        page_end: 543,
        title: '毛泽东等祝贺柬埔寨民族解放人民武装力量完全解放金边的电报',
        dates: [{ year: 1975, month: 4, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 545,
        page_end: 545,
        title: '苏联的战略重点在欧洲和中东',
        dates: [{ year: 1975, month: 4, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 546,
        page_end: 546,
        title: '对新华社关于报道学习无产阶级专政理论问题请示报告的批语',
        dates: [{ year: 1975, month: 4, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 547,
        page_end: 548,
        title: '毛泽东等祝贺越南南方军民彻底摧毁南越愧儡政权解放西贡的电报',
        dates: [{ year: 1975, month: 4, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 549,
        page_end: 549,
        title: '关于知识分子的两句话',
        dates: [{ year: 1975, month: 5, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
    ],
  },
  parser_id: 'automation',
  path: '/archives0/mao-quanji/maoquanji51.pdf',
};
