export default {
  entity: {
    id: 'maoquanji48',
    name: '毛泽东全集第48卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives0/main/mao-quanji/maoquanji48.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
    articles: [
      {
        page_start: 27,
        page_end: 27,
        title: '坚决打击入侵海南岛上空的美机',
        dates: [{ year: 1965, month: 4, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 28,
        page_end: 28,
        title: '对中央关于加强备战工作的指示稿的批语',
        dates: [{ year: 1965, month: 4, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 30,
        page_end: 30,
        title: '接见中南局第九次全体会议代表时的指示',
        dates: [{ year: 1965, month: 4, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 31,
        page_end: 31,
        title: '关于反空降和战略战术问题',
        dates: [{ year: 1965, month: 4, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 32,
        page_end: 32,
        title: '对棉花收购、分配和战略储备情况摘报的批语',
        dates: [{ year: 1965, month: 4, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 33,
        page_end: 34,
        title: '关于劳改工作的指示',
        dates: [{ year: 1965, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 35,
        page_end: 36,
        title: '毛泽东等祝贺捷克斯洛伐克解放二十周年的电报',
        dates: [{ year: 1965, month: 5, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 37,
        page_end: 40,
        title: '支持多米尼加人民反对美国武装侵略的声明L',
        dates: [
          { year: 1965, month: 5, day: 11 },
          { year: 1965, month: 5, day: 12 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 41,
        page_end: 41,
        title: '对关于第二次核试验试爆时间的报告和新闻公报稿的批语',
        dates: [{ year: 1965, month: 5, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 42,
        page_end: 44,
        title: '祝贺印度尼西亚共产党成立四十五周年的电报',
        dates: [
          { year: 1965, month: 5, day: 15 },
          { year: 1965, month: 5, day: 20 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 45,
        page_end: 46,
        title: '毛泽东等祝贺胡志明七十五寿辰的电报',
        dates: [{ year: 1965, month: 5, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 49,
        page_end: 50,
        title: '水调歌头·重上井冈山',
        dates: [{ year: 1965, month: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 62,
        page_end: 62,
        title: '对中央常委接见军委作战会议全体同志时指示纪要的批语',
        dates: [{ year: 1965, month: 5, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 63,
        page_end: 64,
        title: '念奴娇·井冈山',
        dates: [{ year: 1965, month: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 65,
        page_end: 65,
        title: '为《山西农民》题写报头',
        dates: [{ year: 1965, month: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 67,
        page_end: 67,
        title: '为郭国群题词',
        dates: [{ year: 1965, month: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 68,
        page_end: 68,
        title: '毛泽东等祝贺中蒙友好互助条约签订五周年的电报',
        dates: [{ year: 1965, month: 5, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 69,
        page_end: 69,
        title: '在国际关系研究所一份内部材料上的批语',
        dates: [{ year: 1965, month: 6, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 70,
        page_end: 71,
        title: '在《山西省农民讲习所办得很好》材料上的批语',
        dates: [{ year: 1965, month: 6, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 72,
        page_end: 72,
        title: '现在我们要准备打仗',
        dates: [{ year: 1965, month: 6, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 73,
        page_end: 73,
        title: '对《把反对赫鲁晓夫修正主义的斗争进行到底》一文的批语',
        dates: [{ year: 1965, month: 6, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 74,
        page_end: 76,
        title: '在杭州听取计划工作汇报时的讲话',
        dates: [{ year: 1965, month: 6, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 77,
        page_end: 77,
        title: '给章士钊的信',
        dates: [{ year: 1965, month: 6, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 80,
        page_end: 81,
        title: '对卫生工作的指示',
        dates: [{ year: 1965, month: 6, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 82,
        page_end: 83,
        title: '对第十四次全国公安会议两个文件的批语和修改',
        dates: [
          { year: 1965, month: 6, day: 29 },
          { year: 1965, month: 7, day: 10 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 84,
        page_end: 84,
        title: '关于学校要减轻学生负担的批语',
        dates: [{ year: 1965, month: 7, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 85,
        page_end: 86,
        title: '毛泽东等祝贺蒙古人民革命四十四周年的电报',
        dates: [{ year: 1965, month: 7, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 87,
        page_end: 87,
        title: '对中共中央、国务院给苏共中央、苏联部长会议的复信稿的批语',
        dates: [{ year: 1965, month: 7, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 88,
        page_end: 89,
        title: '对李宗仁回国问题的报告的批语和修改',
        dates: [
          { year: 1965, month: 7, day: 12 },
          { year: 1965, month: 7, day: 15 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 90,
        page_end: 90,
        title: '对军队文工团到农村、工厂去锻炼的指示',
        dates: [{ year: 1965, month: 7, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 93,
        page_end: 94,
        title: '关于绘画使用模特问题的批语',
        dates: [{ year: 1965, month: 7, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 95,
        page_end: 95,
        title: '给郭沫若的信',
        dates: [{ year: 1965, month: 7, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 98,
        page_end: 98,
        title: '给章士钊的信',
        dates: [{ year: 1965, month: 7, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 101,
        page_end: 101,
        title: '为《西藏自治区画集》题名',
        dates: [{ year: 1965, month: 7, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 102,
        page_end: 102,
        title: '为《山西青年报》题写报头',
        dates: [{ year: 1965, month: 7, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 103,
        page_end: 104,
        title: '对刘少奇关于转发湖北九个材料的报告的批语',
        dates: [{ year: 1965, month: 7, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 106,
        page_end: 107,
        title: '和医务人员的谈话',
        dates: [{ year: 1965, month: 7, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 108,
        page_end: 108,
        title: '给北京人民大会堂工作人员高殿英的题词',
        dates: [{ year: 1965, month: 7, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 110,
        page_end: 110,
        title: '在全国公交系统四清工作座谈会上的讲话',
        dates: [{ year: 1965, month: 7, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 111,
        page_end: 113,
        title: '给陈毅的信',
        dates: [{ year: 1965, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 116,
        page_end: 116,
        title: '给华罗庚的信',
        dates: [{ year: 1965, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 118,
        page_end: 119,
        title: '毛泽东等祝贺波兰国庆二十一周年的电报',
        dates: [{ year: 1965, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 120,
        page_end: 121,
        title: '毛泽东等祝贺古巴人民武装起义十二周年的电报',
        dates: [{ year: 1965, month: 7, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 122,
        page_end: 122,
        title: '对首批援越高炮部队开赴越南问题请示信的批语',
        dates: [{ year: 1965, month: 7, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 123,
        page_end: 123,
        title: '给于立群的信',
        dates: [{ year: 1965, month: 7, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 127,
        page_end: 127,
        title: '和李宗仁及其夫人的谈话',
        dates: [{ year: 1965, month: 7, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 129,
        page_end: 129,
        title: '关于毛泽民出生年月的批语',
        dates: [{ year: 1965, month: 7, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 130,
        page_end: 131,
        title: '对中央转发谷牧关于设计革命运动报告的通知的批语',
        dates: [{ year: 1965, month: 7, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 132,
        page_end: 132,
        title: '对一篇谈李宗仁回国问题的材料的批语',
        dates: [{ year: 1965, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 133,
        page_end: 133,
        title: '对《四清工作队员的一些意见》的批语',
        dates: [{ year: 1965, month: 8, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 134,
        page_end: 134,
        title: '关于查找杜牧全集的便条',
        dates: [{ year: 1965, month: 8, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 135,
        page_end: 135,
        title: '对卫生部党委关于进一步改革北京医院工作的报告的批语',
        dates: [{ year: 1965, month: 8, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 136,
        page_end: 141,
        title: '在接见汇报卫生工作同志时的谈话',
        dates: [{ year: 1965, month: 8, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 142,
        page_end: 148,
        title: '接见法国事务部长马尔罗时的谈话',
        dates: [{ year: 1965, month: 8, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 149,
        page_end: 150,
        title: '给康生的信',
        dates: [{ year: 1965, month: 8, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 151,
        page_end: 156,
        title: '打仗主要靠自己创造经验',
        dates: [{ year: 1965, month: 8, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 157,
        page_end: 161,
        title: '接见几内亚教育代表团、总检察长时的谈话',
        dates: [{ year: 1965, month: 8, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 162,
        page_end: 162,
        title: '关于找韩昌黎全集的便条',
        dates: [{ year: 1965, month: 8, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 163,
        page_end: 164,
        title: '毛泽东等祝贺朝鲜解放二十周年的电报',
        dates: [{ year: 1965, month: 8, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 165,
        page_end: 165,
        title: '给李先念的信',
        dates: [{ year: 1965, month: 8, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 166,
        page_end: 166,
        title: '对击沉国民党军“剑门”“章江”两舰战斗经验总结报告的批语',
        dates: [{ year: 1965, month: 8, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 167,
        page_end: 168,
        title: '关于军队干部参加地方社会主义教育运动的批语',
        dates: [{ year: 1965, month: 8, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 171,
        page_end: 172,
        title: '毛泽东等祝贺罗马尼亚解放二十一周年的电报',
        dates: [{ year: 1965, month: 8, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 173,
        page_end: 173,
        title: '对湖南各级社教领导机构实行革命化的材料的批语',
        dates: [{ year: 1965, month: 8, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 176,
        page_end: 176,
        title: '为钟学坤题词',
        dates: [{ year: 1965, month: 8, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 178,
        page_end: 179,
        title:
          '在中组部关于在南方各省区培养提拔本地领导干部问题的报告上加写的话',
        dates: [{ year: 1965, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 180,
        page_end: 180,
        title: '为《西藏日报》题写报头',
        dates: [{ year: 1965, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 181,
        page_end: 182,
        title: '毛泽东等祝贺越南民主共和国成立二十周年的电报',
        dates: [{ year: 1965, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 183,
        page_end: 187,
        title: '对胡乔木二十七首诗词稿的批语',
        dates: [
          { year: 1965, month: 9, day: 5 },
          { year: 1965, month: 9, day: 15 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 188,
        page_end: 189,
        title: '毛泽东等祝贺朝鲜民主主义人民共和国成立十七周年的电报',
        dates: [{ year: 1965, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 190,
        page_end: 190,
        title: '毛泽东等祝贺保加利亚社会主义革命二十一周年的电报',
        dates: [{ year: 1965, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 192,
        page_end: 192,
        title: '和黑非洲留法学生联合代表团的谈话（摘录）',
        dates: [{ year: 1965, month: 9, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 193,
        page_end: 193,
        title: '为中国人民广播事业创建二十周年题词',
        dates: [{ year: 1965, month: 9, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 195,
        page_end: 195,
        title: '为《空军报》题写报头',
        dates: [{ year: 1965, month: 9, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 197,
        page_end: 197,
        title: '接见阿尔巴尼亚内务部代表团时的谈话',
        dates: [{ year: 1965, month: 9, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 198,
        page_end: 199,
        title: '在外交部给印度政府的复照稿上的批语',
        dates: [{ year: 1965, month: 9, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 200,
        page_end: 201,
        title: '对中央高级党校关于杨献珍问题和处理意见的报告的批语',
        dates: [{ year: 1965, month: 9, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 202,
        page_end: 202,
        title: '给邓颖超的信',
        dates: [{ year: 1965, month: 9, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 204,
        page_end: 205,
        title: '念奴娇·鸟儿问答',
        dates: [{ year: 1965 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 207,
        page_end: 207,
        title: '对纪念孙中山诞辰百周年筹委会名单（草案）的批语',
        dates: [{ year: 1965, month: 9, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 208,
        page_end: 208,
        title: '关于民族工作的一次指示',
        dates: [{ year: 1965, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 209,
        page_end: 209,
        title: '为《山西日报》题写报头',
        dates: [{ year: 1965, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 210,
        page_end: 210,
        title: '为《新疆日报》题写报头',
        dates: [{ year: 1965, month: 10, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 218,
        page_end: 219,
        title: '对外交部关于陈毅出访五国概况汇报的批语',
        dates: [{ year: 1965, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 220,
        page_end: 221,
        title: '毛泽东等祝贺德意志民主共和国成立十六周年的电报',
        dates: [{ year: 1965, month: 10, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 222,
        page_end: 224,
        title: '战争准备要放在两个可能上',
        dates: [{ year: 1965, month: 10, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 226,
        page_end: 228,
        title: '胜利的信念是从斗争中得来的',
        dates: [{ year: 1965, month: 10, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 229,
        page_end: 229,
        title:
          '对总政关于突出政治、落实四好、加强战备的情况和意见（草稿）的批语',
        dates: [{ year: 1965, month: 10, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 230,
        page_end: 230,
        title: '在全国第二批城市“四清”部署情况简报上的批语',
        dates: [{ year: 1965, month: 10, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 231,
        page_end: 232,
        title: '关于大学文科改革的指示（摘录）',
        dates: [{ year: 1965, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 233,
        page_end: 234,
        title: '毛泽东等祝贺十月社会主义革命四十八周年的电报',
        dates: [{ year: 1965, month: 11, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 235,
        page_end: 235,
        title: '对林彪所提五项原则的批语',
        dates: [{ year: 1965, month: 11, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 236,
        page_end: 238,
        title: '要把美国帝国主义分子同美国人民划分清楚',
        dates: [{ year: 1965, month: 11, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 240,
        page_end: 241,
        title: '毛泽东等祝贺阿尔巴尼亚解放二十一周年的电报',
        dates: [{ year: 1965, month: 11, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 242,
        page_end: 243,
        title: '对越南南方领导人接见我新闻工作队的谈话纪要的批语',
        dates: [{ year: 1965, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 244,
        page_end: 245,
        title: '要争取快一点把后方建设起来',
        dates: [{ year: 1965, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 246,
        page_end: 246,
        title: '路过济南在火车上听取汇报时的指示',
        dates: [{ year: 1965, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 248,
        page_end: 248,
        title: '在听取汇报时的插话',
        dates: [{ year: 1965, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 249,
        page_end: 249,
        title: '为《郑州晚报》题写报头',
        dates: [{ year: 1965, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 250,
        page_end: 250,
        title: '批判罗瑞卿',
        dates: [{ year: 1965, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 251,
        page_end: 251,
        title: '给陈伯达的信',
        dates: [{ year: 1965, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 252,
        page_end: 252,
        title: '对林彪同志一封来信的批语',
        dates: [{ year: 1965, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 253,
        page_end: 257,
        title: '反对折中主义',
        dates: [{ year: 1965, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 258,
        page_end: 260,
        title: '在兰州军区党委一个报告上的批语',
        dates: [
          { year: 1965, month: 12, day: 2 },
          { year: 1965, month: 12, day: 7 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 261,
        page_end: 261,
        title: '关于机要保密、警卫工作的指示',
        dates: [{ year: 1965, month: 12, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 262,
        page_end: 263,
        title: '关于印发《论十大关系》的批语',
        dates: [{ year: 1965, month: 12, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 264,
        page_end: 269,
        title: '在杭州会议上的讲话',
        dates: [{ year: 1965, month: 12, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 270,
        page_end: 271,
        title: '上面要靠党的领导下面要靠广大群众',
        dates: [{ year: 1965, month: 12, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 272,
        page_end: 273,
        title: '毛泽东等祝贺古巴解放七周年的电报',
        dates: [{ year: 1965, month: 12, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 274,
        page_end: 275,
        title: '在一九六五年《哲学研究》第四期上的批语',
        dates: [{ year: 1965 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 276,
        page_end: 277,
        title: '关于礼宾工作的指示',
        dates: [{ year: 1965 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 278,
        page_end: 279,
        title: '重读《长冈乡调查》时写的批注',
        dates: [{ year: 1965 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 280,
        page_end: 280,
        title: '七律·洪都',
        dates: [{ year: 1965 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 281,
        page_end: 281,
        title: '为《吉林日报》题写报头',
        dates: [{ year: 1965 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 283,
        page_end: 283,
        title: '卜算子·悼艾地同志',
        dates: [{ year: 1965, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 284,
        page_end: 287,
        title: '在李达主编的《马克思主义哲学大纲》上的批注',
        dates: [{ year: 1965 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 290,
        page_end: 291,
        title: '毛泽东等祝贺阿尔巴尼亚人民共和国成立二十周年的电报',
        dates: [{ year: 1966, month: 1, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 292,
        page_end: 293,
        title: '给章士钊的信',
        dates: [{ year: 1966, month: 1, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 294,
        page_end: 294,
        title: '给周世钊的信',
        dates: [{ year: 1966, month: 1, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 295,
        page_end: 295,
        title: '对有关《海瑞罢官》问题七个材料的批语',
        dates: [{ year: 1966, month: 2, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 296,
        page_end: 296,
        title: '为焦裕禄题词*',
        dates: [{ year: 1966, month: 2, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 297,
        page_end: 298,
        title: '关于重新印发毛泽东在七千人大会上讲话的批语',
        dates: [
          { year: 1966, month: 2, day: 6 },
          { year: 1966, month: 2, day: 12 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 299,
        page_end: 299,
        title: '关于《海瑞罢官》的谈话',
        dates: [{ year: 1966, month: 2, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 300,
        page_end: 301,
        title: '和毛远新的谈话',
        dates: [{ year: 1966, month: 2, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 302,
        page_end: 304,
        title: '对湖北省委关于逐步实现农业机械化设想的批语',
        dates: [{ year: 1966, month: 2, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 305,
        page_end: 306,
        title: '诱敌深入要做两手准备',
        dates: [
          { year: 1966, month: 2, day: 21 },
          { year: 1966, month: 2, day: 22 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 307,
        page_end: 307,
        title: '为罗丽华题词',
        dates: [{ year: 1966, month: 2, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 309,
        page_end: 310,
        title: '对王任重关于政治挂帅问题发言稿的批语',
        dates: [
          { year: 1966, month: 2 },
          { year: 1966, month: 4 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 311,
        page_end: 313,
        title: '关于农业机械化问题的一封信',
        dates: [{ year: 1966, month: 3, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 315,
        page_end: 315,
        title: '看了“人工喉”“断手再植”“止血粉”等文章后对医务工作者的指示',
        dates: [{ year: 1966, month: 3, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 317,
        page_end: 327,
        title: '在中央政治局常委扩大会议上的讲话',
        dates: [{ year: 1966, month: 3, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 328,
        page_end: 328,
        title: '对中共代表团与日共代表团联合公报草案中一段文字的修改',
        dates: [{ year: 1966, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 329,
        page_end: 335,
        title:
          '对《林彪同志委托江青同志召开的部队文艺工作座谈会纪要》的批语和修改',
        dates: [
          { year: 1966, month: 3 },
          { year: 1966, month: 4 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 336,
        page_end: 340,
        title: '对中宣部和北京市委的批评',
        dates: [
          { year: 1966, month: 3 },
          { year: 1966, month: 4 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 341,
        page_end: 342,
        title: '对《在京艺术院校试行半工（农）半读》一文的批语',
        dates: [{ year: 1966, month: 4, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 343,
        page_end: 343,
        title: '对全国政协第一届会议开幕词中一段话的批注',
        dates: [{ year: 1966, month: 4, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 344,
        page_end: 344,
        title: '对高教部党委部署深入开展学术批判情况简报的批语',
        dates: [{ year: 1966, month: 4, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 345,
        page_end: 351,
        title:
          '对中央关于撤销《文化革命五人小组关于当前学术讨论的汇报提纲》通知稿的批语和修改',
        dates: [{ year: 1966, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 352,
        page_end: 353,
        title: '对《毛主席诗词》（注释本）中几个问题处理意见的修改和批语',
        dates: [{ year: 1966, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 354,
        page_end: 354,
        title: '对林一山关于修建长江三峡工程报告的批语',
        dates: [{ year: 1966, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 355,
        page_end: 355,
        title: '对共青团九届三中全会的指示',
        dates: [{ year: 1966, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 357,
        page_end: 357,
        title: '中国是否会出修正主义',
        dates: [{ year: 1966, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 358,
        page_end: 359,
        title: '在接见阿尔巴尼亚党政代表团代表时的谈话（节录）',
        dates: [{ year: 1966, month: 5, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 360,
        page_end: 362,
        title: '对总后勤部关于进一步搞好部队农副业生产报告的批语',
        dates: [
          { year: 1966, month: 5, day: 7 },
          { year: 1966, month: 5, day: 14 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 367,
        page_end: 367,
        title: '印发张恩慈对北大“四清”运动意见的批语',
        dates: [{ year: 1966, month: 5, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 368,
        page_end: 370,
        title: '为中共中央“五·一六”通知加写的几段话',
        dates: [{ year: 1966, month: 5, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 371,
        page_end: 373,
        title: '对章士钊关于暂不出版《柳文指要》来信的批语和批注',
        dates: [{ year: 1966, month: 5, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 374,
        page_end: 374,
        title: '关于同意派临时工作组去人民日报社的批语',
        dates: [{ year: 1966, month: 5, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 375,
        page_end: 375,
        title:
          '关于播发《宋硕、陆平、彭佩云在文化革命中究竟干些什么？》大字报的批语',
        dates: [{ year: 1966, month: 6, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 379,
        page_end: 388,
        title: '在杭州和胡志明的谈话（节录）',
        dates: [{ year: 1966, month: 6, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 390,
        page_end: 391,
        title: '关于暂不发表毛泽东在七千人大会上的讲话等问题的批语',
        dates: [{ year: 1966, month: 6, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 392,
        page_end: 392,
        title: '七律·有所思',
        dates: [{ year: 1966, month: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 396,
        page_end: 396,
        title: '必须组织和发展无产阶级左派队伍',
        dates: [{ year: 1966 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 397,
        page_end: 398,
        title:
          '对中共中央、国务院关于工交企业和基建单位如何开展文化大革命运动通知稿的批语',
        dates: [{ year: 1966, month: 7, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 401,
        page_end: 404,
        title: '给江青的信',
        dates: [{ year: 1966, month: 7, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 405,
        page_end: 405,
        title: '对陶铸、张平化关于中宣部的组织和工作问题请示信的批语',
        dates: [{ year: 1966, month: 7, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 406,
        page_end: 406,
        title: '在接见日本、古巴、巴西和阿根廷朋友时的谈话',
        dates: [{ year: 1966, month: 7, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 407,
        page_end: 407,
        title: '对北京语言学院七名学生来信的批语',
        dates: [{ year: 1966, month: 7, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 408,
        page_end: 408,
        title: '畅游长江时的谈话',
        dates: [{ year: 1966, month: 7, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 422,
        page_end: 426,
        title: '工作组要撤，文化革命要依靠革命师生',
        dates: [{ year: 1966, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 427,
        page_end: 429,
        title: '在会见大区书记和中央文革小组成员的讲话',
        dates: [{ year: 1966, month: 7, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 430,
        page_end: 430,
        title: '关于北大“六·一八”事件',
        dates: [{ year: 1966, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 431,
        page_end: 434,
        title: '对中央关于文化大革命的决定稿的批语',
        dates: [
          { year: 1966, month: 7 },
          { year: 1966, month: 8 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 439,
        page_end: 440,
        title: '关于不要用“顶峰”“最高指示”一类词语的批语',
        dates: [
          { year: 1966, month: 7, day: 25 },
          { year: 1966, month: 8, day: 4 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 441,
        page_end: 442,
        title: '给清华大学附属中学红卫兵的信',
        dates: [
          { year: 1966, month: 7, day: 31 },
          { year: 1966, month: 8, day: 1 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 443,
        page_end: 444,
        title: '凡是镇压学生运动的人，都没有好下场',
        dates: [{ year: 1966, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 445,
        page_end: 445,
        title: '对共青团中央的批评',
        dates: [{ year: 1966, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 446,
        page_end: 446,
        title: '关于打人问题',
        dates: [{ year: 1966, month: 8, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 447,
        page_end: 449,
        title: '不许镇压学生运动',
        dates: [{ year: 1966, month: 8, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 450,
        page_end: 452,
        title: '炮打司令部',
        dates: [{ year: 1966, month: 8, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 461,
        page_end: 461,
        title: '在《欢呼北大的一张大字报》一文中加写的批注',
        dates: [{ year: 1966, month: 8, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 462,
        page_end: 465,
        title: '对中共八届十一中全会公报稿的批语和修改',
        dates: [
          { year: 1966, month: 8, day: 5 },
          { year: 1966, month: 8, day: 9 },
          { year: 1966, month: 8, day: 11 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 467,
        page_end: 467,
        title: '对李达来信的批语',
        dates: [{ year: 1966, month: 8, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 468,
        page_end: 468,
        title: '在中央接待站会见首都群众时的讲话',
        dates: [{ year: 1966, month: 8, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 470,
        page_end: 471,
        title: '在中共八届十一中全会闭幕会上的讲话',
        dates: [{ year: 1966, month: 8, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 473,
        page_end: 473,
        title: '对陈伯达、康生关于李雪峰不再兼任北京市委书记请示报告的批语',
        dates: [{ year: 1966, month: 8, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 474,
        page_end: 474,
        title: '给刘少奇的信',
        dates: [{ year: 1966, month: 8, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 475,
        page_end: 475,
        title: '对林彪三篇讲话稿的批语',
        dates: [{ year: 1966, month: 8, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 476,
        page_end: 476,
        title: '为北京大学校刊题名',
        dates: [{ year: 1966, month: 8, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 477,
        page_end: 477,
        title: '在首都庆祝文化大革命大会上同林彪的谈话',
        dates: [{ year: 1966, month: 8, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 511,
        page_end: 512,
        title: '在天安门城楼上和北大附中红卫兵谈话纪要',
        dates: [{ year: 1966, month: 8, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 513,
        page_end: 513,
        title: '革命要靠自己',
        dates: [{ year: 1966 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 518,
        page_end: 518,
        title: '为《中国妇女》杂志题名',
        dates: [{ year: 1966, month: 8, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 520,
        page_end: 520,
        title: '对薄一波来信的批语',
        dates: [{ year: 1966, month: 8, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 521,
        page_end: 521,
        title: '在中央工作会议上的讲话',
        dates: [{ year: 1966, month: 8, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 522,
        page_end: 522,
        title: '对谢富治关于公安部机关精简设想的批语',
        dates: [{ year: 1966, month: 8, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 523,
        page_end: 523,
        title: '关于传阅文件问题的批语',
        dates: [{ year: 1966, month: 8, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 524,
        page_end: 524,
        title: '在李富春关于国务院八个口机关文化大革命问题报告上的批语',
        dates: [{ year: 1966, month: 8, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 525,
        page_end: 525,
        title: '对关锋、戚本禹反映北京市文化大革命情况报告的批语',
        dates: [{ year: 1966, month: 8, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 527,
        page_end: 527,
        title: '在章士钊反映被抄家情况来信上的批语',
        dates: [{ year: 1966, month: 8, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
    ],
  },
  parser_id: 'automation',
  path: '/archives0/mao-quanji/maoquanji48.pdf',
};
