export default {
  entity: {
    id: 'maoquanji1',
    name: '毛泽东全集第1卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives8/main/maoquanji1.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '杂言诗·迎春叫',
        authors: ['毛泽东'],
        page_start: 55,
        page_end: 66,
        dates: [{ year: 1901 }],
        is_range_date: false,
      },
      {
        title: '和邹春培先生应对联（之一）',
        authors: ['毛泽东'],
        page_start: 67,
        page_end: 70,
        dates: [{ year: 1902 }],
        is_range_date: false,
      },
      {
        title: '和邹春培先生应对联（之二）',
        authors: ['毛泽东'],
        page_start: 71,
        page_end: 74,
        dates: [{ year: 1903 }],
        is_range_date: false,
      },
      {
        title: '五言诗·并赞',
        authors: ['毛泽东'],
        page_start: 75,
        page_end: 78,
        dates: [{ year: 1906 }],
        is_range_date: false,
      },
      {
        title: '五古·咏指甲花',
        authors: ['毛泽东'],
        page_start: 79,
        page_end: 80,
        dates: [{ year: 1907 }],
        is_range_date: false,
      },
      {
        title: '杂言诗·耕田乐',
        authors: ['毛泽东'],
        page_start: 81,
        page_end: 86,
        dates: [{ year: 1907 }],
        is_range_date: false,
      },
      {
        title: '七绝·呈父亲',
        authors: ['毛泽东'],
        page_start: 87,
        page_end: 89,
        dates: [{ year: 1910 }],
        is_range_date: false,
      },
      {
        title: '七绝·咏蛙',
        authors: ['毛泽东'],
        page_start: 90,
        page_end: 90,
        dates: [{ year: 1910 }],
        is_range_date: false,
      },
      {
        title: '和东山小学堂先生应对联',
        authors: ['毛泽东'],
        page_start: 91,
        page_end: 93,
        dates: [{ year: 1910 }],
        is_range_date: false,
      },
      {
        title: '和萧三的谈话',
        authors: ['毛泽东'],
        page_start: 94,
        page_end: 94,
        dates: [{ year: 1910 }],
        is_range_date: false,
      },
      {
        title: '看报谈话',
        authors: ['毛泽东'],
        page_start: 95,
        page_end: 98,
        dates: [{ year: 1910 }],
        is_range_date: false,
      },
      {
        title: '商鞅徒木立信论',
        authors: ['毛泽东'],
        page_start: 99,
        page_end: 104,
        dates: [{ year: 1912, month: 6 }],
        is_range_date: false,
      },
      {
        title: '五言诗·登高泛海',
        authors: ['毛泽东'],
        page_start: 105,
        page_end: 105,
        dates: [{ year: 1913, month: 10 }],
        is_range_date: false,
      },
      {
        title: '讲堂录',
        authors: ['毛泽东'],
        page_start: 106,
        page_end: 164,
        dates: [
          { year: 1913, month: 10 },
          { year: 1913, month: 12 },
        ],
        is_range_date: true,
      },
      {
        title: '五言排律·湘江漫游联句',
        authors: ['毛泽东'],
        page_start: 165,
        page_end: 168,
        dates: [{ year: 1914 }],
        is_range_date: false,
      },
      {
        title: '给文脉昌的信',
        authors: ['毛泽东'],
        page_start: 169,
        page_end: 170,
        dates: [{ year: 1915, month: 2, day: 24 }],
        is_range_date: false,
      },
      {
        title: '杨昌济记毛泽东的谈话',
        authors: ['毛泽东'],
        page_start: 171,
        page_end: 171,
        dates: [{ year: 1915, month: 4, day: 5 }],
        is_range_date: false,
      },
      {
        title: '掉友人易咏啡',
        authors: ['毛泽东'],
        page_start: 172,
        page_end: 172,
        dates: [{ year: 1915, month: 5 }],
        is_range_date: false,
      },
      {
        title: '五古.抚易昌陶间',
        authors: ['毛泽东'],
        page_start: 173,
        page_end: 176,
        dates: [{ year: 1915, month: 5 }],
        is_range_date: false,
      },
      {
        title: '给湘生的信',
        authors: ['毛泽东'],
        page_start: 177,
        page_end: 184,
        dates: [{ year: 1915, month: 6, day: 25 }],
        is_range_date: false,
      },
      {
        title: '给友人的信',
        authors: ['毛泽东'],
        page_start: 185,
        page_end: 187,
        dates: [{ year: 1915, month: 7 }],
        is_range_date: false,
      },
      {
        title: '给萧子升的信',
        authors: ['毛泽东'],
        page_start: 188,
        page_end: 189,
        dates: [{ year: 1915, month: 8, day: 3 }],
        is_range_date: false,
      },
      {
        title: '给萧子升的信',
        authors: ['毛泽东'],
        page_start: 190,
        page_end: 192,
        dates: [{ year: 1915, month: 8 }],
        is_range_date: false,
      },
      {
        title: '给站子升的信',
        authors: ['毛泽东'],
        page_start: 193,
        page_end: 198,
        dates: [{ year: 1915, month: 9, day: 6 }],
        is_range_date: false,
      },
      {
        title: '给萧子升的信',
        authors: ['毛泽东'],
        page_start: 199,
        page_end: 200,
        dates: [{ year: 1915, month: 9, day: 27 }],
        is_range_date: false,
      },
      {
        title: '征友启事',
        authors: ['毛泽东'],
        page_start: 201,
        page_end: 201,
        dates: [{ year: 1915, month: 9 }],
        is_range_date: false,
      },
      {
        title: '给黎锦熙的信',
        authors: ['毛泽东'],
        page_start: 202,
        page_end: 203,
        dates: [{ year: 1915, month: 11, day: 9 }],
        is_range_date: false,
      },
      {
        title: '给黎锦熙的信',
        authors: ['毛泽东'],
        page_start: 204,
        page_end: 208,
        dates: [{ year: 1915, month: 11, day: 9 }],
        is_range_date: false,
      },
      {
        title: '无律·登云麓宜联布',
        authors: ['毛泽东'],
        page_start: 209,
        page_end: 210,
        dates: [{ year: 1915 }],
        is_range_date: false,
      },
      {
        title: '杂言诗·游泳启事',
        authors: ['毛泽东'],
        page_start: 211,
        page_end: 211,
        dates: [{ year: 1915 }],
        is_range_date: false,
      },
      {
        title: '治学联',
        authors: ['毛泽东'],
        page_start: 212,
        page_end: 212,
        dates: [{ year: 1915 }],
        is_range_date: false,
      },
      {
        title: '贺廖廷旋、皮述莲同学新婚联',
        authors: ['毛泽东'],
        page_start: 213,
        page_end: 213,
        dates: [{ year: 1915 }],
        is_range_date: false,
      },
      {
        title: '赠毛泽建联',
        authors: ['毛泽东'],
        page_start: 214,
        page_end: 216,
        dates: [{ year: 1915 }],
        is_range_date: false,
      },
      {
        title: '给萧子升的信',
        authors: ['毛泽东'],
        page_start: 217,
        page_end: 217,
        dates: [{ year: 1916, month: 1, day: 28 }],
        is_range_date: false,
      },
      {
        title: '给肃子升的信',
        authors: ['毛泽东'],
        page_start: 218,
        page_end: 218,
        dates: [{ year: 1916, month: 2, day: 19 }],
        is_range_date: false,
      },
      {
        title: '给肃子升的信',
        authors: ['毛泽东'],
        page_start: 219,
        page_end: 219,
        dates: [{ year: 1916, month: 2, day: 29 }],
        is_range_date: false,
      },
      {
        title: '挖吴竹面联',
        authors: ['毛泽东'],
        page_start: 220,
        page_end: 220,
        dates: [{ year: 1916, month: 5 }],
        is_range_date: false,
      },
      {
        title: '给肃子升的信',
        authors: ['毛泽东'],
        page_start: 221,
        page_end: 221,
        dates: [{ year: 1916, month: 6, day: 24 }],
        is_range_date: false,
      },
      {
        title: '给萧子升的信',
        authors: ['毛泽东'],
        page_start: 222,
        page_end: 223,
        dates: [{ year: 1916, month: 6, day: 26 }],
        is_range_date: false,
      },
      {
        title: '给肃子升的信',
        authors: ['毛泽东'],
        page_start: 224,
        page_end: 228,
        dates: [{ year: 1916, month: 7, day: 18 }],
        is_range_date: false,
      },
      {
        title: '给肃子升的信',
        authors: ['毛泽东'],
        page_start: 229,
        page_end: 236,
        dates: [{ year: 1916, month: 7, day: 25 }],
        is_range_date: false,
      },
      {
        title: '给黎锦熙的信科',
        authors: ['毛泽东'],
        page_start: 237,
        page_end: 239,
        dates: [{ year: 1916, month: 12, day: 9 }],
        is_range_date: false,
      },
      {
        title: '怎样看待别人',
        authors: ['毛泽东'],
        page_start: 240,
        page_end: 245,
        dates: [{ year: 1916 }],
        is_range_date: false,
      },
      {
        title: '体育之研究',
        authors: ['毛泽东'],
        page_start: 246,
        page_end: 267,
        dates: [{ year: 1917, month: 4, day: 1 }],
        is_range_date: false,
      },
      {
        title: '给黎锦熙的信',
        authors: ['毛泽东'],
        page_start: 268,
        page_end: 275,
        dates: [{ year: 1917, month: 8, day: 23 }],
        is_range_date: false,
      },
      {
        title: '国文教授案',
        authors: ['毛泽东'],
        page_start: 276,
        page_end: 277,
        dates: [{ year: 1917, month: 9 }],
        is_range_date: false,
      },
      {
        title: '张昆弟记毛泽东的两次谈话',
        authors: ['毛泽东'],
        page_start: 278,
        page_end: 280,
        dates: [{ year: 1917, month: 9 }],
        is_range_date: false,
      },
      {
        title: '夜学招学广告',
        authors: ['毛泽东'],
        page_start: 281,
        page_end: 284,
        dates: [{ year: 1917, month: 10, day: 30 }],
        is_range_date: false,
      },
      {
        title: '夜学日志首卷山',
        authors: ['毛泽东'],
        page_start: 285,
        page_end: 297,
        dates: [{ year: 1917, month: 11 }],
        is_range_date: false,
      },
      {
        title: '七律·游学即景',
        authors: ['毛泽东'],
        page_start: 298,
        page_end: 298,
        dates: [{ year: 1917 }],
        is_range_date: false,
      },
      {
        title: '七绝·赠刘翰林联句',
        authors: ['毛泽东'],
        page_start: 299,
        page_end: 299,
        dates: [{ year: 1917 }],
        is_range_date: false,
      },
      {
        title: '五言诗·玉潭即景联句',
        authors: ['毛泽东'],
        page_start: 300,
        page_end: 300,
        dates: [{ year: 1917 }],
        is_range_date: false,
      },
      {
        title: '四言诗·露宿',
        authors: ['毛泽东'],
        page_start: 301,
        page_end: 301,
        dates: [{ year: 1917 }],
        is_range_date: false,
      },
      {
        title: '四言诗·题安化北宝塔壁',
        authors: ['毛泽东'],
        page_start: 302,
        page_end: 302,
        dates: [{ year: 1917 }],
        is_range_date: false,
      },
      {
        title: '七古“·游泳',
        authors: ['毛泽东'],
        page_start: 303,
        page_end: 304,
        dates: [{ year: 1917 }],
        is_range_date: false,
      },
      {
        title: '五律·赠周世钉',
        authors: ['毛泽东'],
        page_start: 305,
        page_end: 305,
        dates: [{ year: 1917 }],
        is_range_date: false,
      },
      {
        title: '四言诗·奋斗',
        authors: ['毛泽东'],
        page_start: 306,
        page_end: 306,
        dates: [{ year: 1917 }],
        is_range_date: false,
      },
      {
        title: '题湖南省立第一师范病故同学追恒会联',
        authors: ['毛泽东'],
        page_start: 307,
        page_end: 307,
        dates: [{ year: 1917 }],
        is_range_date: false,
      },
      {
        title: '挽某同学联',
        authors: ['毛泽东'],
        page_start: 308,
        page_end: 308,
        dates: [{ year: 1917 }],
        is_range_date: false,
      },
      {
        title: '心之力',
        authors: ['毛泽东'],
        page_start: 309,
        page_end: 470,
        dates: [{ year: 1917 }],
        is_range_date: false,
      },
      {
        title: '夜学招学广告',
        authors: ['毛泽东'],
        page_start: 471,
        page_end: 472,
        dates: [{ year: 1918, month: 3, day: 2 }],
        is_range_date: false,
      },
      {
        title: '七古叫.送级字一郎东行',
        authors: ['毛泽东'],
        page_start: 473,
        page_end: 475,
        dates: [{ year: 1918, month: 4 }],
        is_range_date: false,
      },
      {
        title: '学友会五月十日事录',
        authors: ['毛泽东'],
        page_start: 476,
        page_end: 482,
        dates: [{ year: 1918, month: 5, day: 29 }],
        is_range_date: false,
      },
      {
        title: '题湖南省立第一师范附属小学礼堂联',
        authors: ['毛泽东'],
        page_start: 483,
        page_end: 483,
        dates: [{ year: 1918 }],
        is_range_date: false,
      },
      {
        title: '给罗学的信',
        authors: ['毛泽东'],
        page_start: 484,
        page_end: 486,
        dates: [{ year: 1918, month: 8, day: 11 }],
        is_range_date: false,
      },
      {
        title: '给七、八剪父的信',
        authors: ['毛泽东'],
        page_start: 487,
        page_end: 487,
        dates: [{ year: 1918, month: 8 }],
        is_range_date: false,
      },
      {
        title: '七绝·魏都怀古',
        authors: ['毛泽东'],
        page_start: 488,
        page_end: 495,
        dates: [{ year: 1918, month: 8, day: 18 }],
        is_range_date: false,
      },
      {
        title: '五言诗·大活口观海',
        authors: ['毛泽东'],
        page_start: 496,
        page_end: 497,
        dates: [{ year: 1919, month: 3, day: 12 }],
        is_range_date: false,
      },
      {
        title: '给七、八男父母的信',
        authors: ['毛泽东'],
        page_start: 498,
        page_end: 500,
        dates: [{ year: 1919, month: 4, day: 28 }],
        is_range_date: false,
      },
      {
        title: '《湘江评论》创刊宣言',
        authors: ['毛泽东'],
        page_start: 501,
        page_end: 507,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '各国的姜工风潮',
        authors: ['毛泽东'],
        page_start: 508,
        page_end: 512,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '陈独秀之被捕及营救',
        authors: ['毛泽东'],
        page_start: 513,
        page_end: 517,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '强叫化',
        authors: ['毛泽东'],
        page_start: 518,
        page_end: 518,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '研究过激党',
        authors: ['毛泽东'],
        page_start: 519,
        page_end: 519,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '实行封锁',
        authors: ['毛泽东'],
        page_start: 520,
        page_end: 520,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '证明协约国的平等正义',
        authors: ['毛泽东'],
        page_start: 521,
        page_end: 521,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '阿富汗执戈而起',
        authors: ['毛泽东'],
        page_start: 522,
        page_end: 522,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '来因共和国是孔国',
        authors: ['毛泽东'],
        page_start: 523,
        page_end: 523,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '好个民族自决',
        authors: ['毛泽东'],
        page_start: 524,
        page_end: 524,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '可岭的威尔进',
        authors: ['毛泽东'],
        page_start: 525,
        page_end: 525,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '炸弹暴举',
        authors: ['毛泽东'],
        page_start: 526,
        page_end: 526,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '不许实业专制',
        authors: ['毛泽东'],
        page_start: 527,
        page_end: 527,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '割地赔偿不两全',
        authors: ['毛泽东'],
        page_start: 528,
        page_end: 528,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '为社会党造成流血之地',
        authors: ['毛泽东'],
        page_start: 529,
        page_end: 529,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '彭斯坦',
        authors: ['毛泽东'],
        page_start: 530,
        page_end: 530,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '各国没有明伦堂',
        authors: ['毛泽东'],
        page_start: 531,
        page_end: 531,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '什么是民国所宜',
        authors: ['毛泽东'],
        page_start: 532,
        page_end: 532,
        dates: [{ year: 1919, month: 7, day: 14 }],
        is_range_date: false,
      },
    ],
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives8/maoquanji1.pdf',
};
