export default {
  entity: {
    id: 'maoquanji43',
    name: '毛泽东全集第43卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives0/main/maoquanji43.pdf',
  },
  parser_option: {
    ext: 'pdf',
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
    page_limits: [],
    articles: [
      {
        page_start: 26,
        page_end: 27,
        title: '毛泽东等给苏联共产党和国家领导人的新年贺电',
        dates: [{ year: 1959, month: 12, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 28,
        page_end: 28,
        title: '给陈云的信',
        dates: [{ year: 1959, month: 12, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 31,
        page_end: 31,
        title: '给李讷的信',
        dates: [{ year: 1959, month: 12, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 32,
        page_end: 32,
        title: '给田士清的信',
        dates: [{ year: 1959, month: 12, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 34,
        page_end: 35,
        title: '对《彻底驳倒富裕中农反对“八字宪法”的谬论》等三个材料的批语',
        dates: [{ year: 1959, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 36,
        page_end: 36,
        title: '对国家计委关于今后八年钢铁工业发展的初步设想的批语',
        dates: [{ year: 1959, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 37,
        page_end: 37,
        title: '对新华社的指示',
        dates: [{ year: 1959, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 38,
        page_end: 38,
        title: '对国家计委关于我国主要工业产品产量赶超情况预测材料的批语',
        dates: [{ year: 1959, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 39,
        page_end: 83,
        title: '读苏联《政治经济学教科书》的谈话（节选）',
        dates: [
          { year: 1959, month: 12 },
          { year: 1959, month: 1960, day: 2 },
        ],
        is_range_date: true,
        authors: ['毛泽东'],
      },
      {
        page_start: 84,
        page_end: 85,
        title: '七律·读报有感之一',
        dates: [{ year: 1959 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 86,
        page_end: 86,
        title: '七律·读报有感之二',
        dates: [{ year: 1959, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 87,
        page_end: 87,
        title: '为《星火燎原》题名',
        dates: [{ year: 1959, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 88,
        page_end: 88,
        title: '赠陈云同志联',
        dates: [{ year: 1959 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 89,
        page_end: 89,
        title: '江山如此多娇',
        dates: [{ year: 1959 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 91,
        page_end: 91,
        title: '为湖南烈士公园纪念碑题名',
        dates: [{ year: 1959 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 92,
        page_end: 92,
        title: '为《大众摄影》题名',
        dates: [{ year: 1959 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 95,
        page_end: 95,
        title: '为中国摄影学会题名',
        dates: [{ year: 1959 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 97,
        page_end: 97,
        title: '为《中国摄影》杂志题名',
        dates: [{ year: 1959 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 99,
        page_end: 103,
        title: '关于《红楼梦》的一组谈话',
        dates: [{ year: 1959 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 106,
        page_end: 106,
        title: '关于确定中央政治局扩大会议开会地点的批语',
        dates: [{ year: 1960, month: 1, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 107,
        page_end: 110,
        title: '在关于国际情况的一期简讯上的批语',
        dates: [{ year: 1960, month: 1, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 111,
        page_end: 111,
        title: '印发《外国资产阶级怎样议论中苏分歧》材料的批语',
        dates: [{ year: 1960, month: 1, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 112,
        page_end: 112,
        title: '让伍修权请苏联驻华大使转告赫鲁晓夫的一段话',
        dates: [{ year: 1960, month: 1, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 113,
        page_end: 114,
        title: '印发冶金部党组关于钢铁企业“小洋群”情况报告的批语',
        dates: [{ year: 1960, month: 1, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 115,
        page_end: 115,
        title: '印发《纳赛尔与社会党全面破裂》材料的批语',
        dates: [{ year: 1960, month: 1, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 116,
        page_end: 116,
        title: '给刘松林的信',
        dates: [{ year: 1960, month: 1, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 117,
        page_end: 117,
        title: '对七省市和十四个重点企业一季度工业生产安排情况的批语',
        dates: [{ year: 1960, month: 1, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 118,
        page_end: 119,
        title: '转发太原市委关于开展技术革新和技术革命运动的决议的批语',
        dates: [{ year: 1960, month: 1, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 120,
        page_end: 121,
        title: '关于广泛阅读、讨论中国政府给印度政府照会的批语',
        dates: [{ year: 1960, month: 1, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 122,
        page_end: 123,
        title: '关于派代表参加华沙条约缔约国政治协商会议例会给赫鲁晓夫的复信',
        dates: [
          { year: 1960, month: 1, day: 31 },
          { year: 1960, month: 2, day: 1 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 124,
        page_end: 124,
        title: '在驻德意志民主共和国大使馆给外交部的一份电报上的批语',
        dates: [{ year: 1960, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 125,
        page_end: 126,
        title: '在关于台湾情况的一份内部材料上的批语',
        dates: [{ year: 1960, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 127,
        page_end: 128,
        title: '对《关于共产主义我们必须知道些什么》一书摘录的批语',
        dates: [{ year: 1960, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 129,
        page_end: 129,
        title: '在上海会议上的讲话',
        dates: [{ year: 1960, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 130,
        page_end: 130,
        title: '关于科学奖金和学衔的指示',
        dates: [{ year: 1960, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 131,
        page_end: 133,
        title: '毛泽东等祝贺中苏友好同盟互助条约签订十周年的电报',
        dates: [{ year: 1960, month: 2, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 134,
        page_end: 134,
        title: '请罗光禄购买《哲学研究》杂志的批语',
        dates: [{ year: 1960, month: 2, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 135,
        page_end: 135,
        title: '给林彪的信',
        dates: [{ year: 1960, month: 2, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 138,
        page_end: 140,
        title: '对国家经委党组关于工业、交通生产情况报告的批语',
        dates: [{ year: 1960, month: 2, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 141,
        page_end: 141,
        title: '毛泽东等为祝贺藏历新年复班禅额尔德尼电',
        dates: [{ year: 1960, month: 2, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 142,
        page_end: 143,
        title: '在农业部党组关于全国农业科学研究工作会议情况报告上的批语',
        dates: [{ year: 1960, month: 2, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 144,
        page_end: 148,
        title: '中央转发广东省委关于当前人民公社工作中几个问题的指示的批语',
        dates: [
          { year: 1960, month: 3, day: 2 },
          { year: 1960, month: 3, day: 3 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 149,
        page_end: 151,
        title: '中央转发贵州省委关于目前农村公共食堂情况报告的批语',
        dates: [
          { year: 1960, month: 3, day: 2 },
          { year: 1960, month: 3, day: 4 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 152,
        page_end: 153,
        title: '中央转发吉林省委关于技术革新和技术革命运动情况报告的批语',
        dates: [{ year: 1960, month: 3, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 155,
        page_end: 155,
        title:
          '为审阅中央转发广东、吉林、贵州省委报告的三个批语稿给刘少奇、邓小平的信',
        dates: [{ year: 1960, month: 3, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 156,
        page_end: 156,
        title: '在河南省委关于当前抗旱浇麦情况简报上的批语',
        dates: [{ year: 1960, month: 3, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 157,
        page_end: 158,
        title: '关于干部中存在的三个大问题',
        dates: [{ year: 1960, month: 3, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 159,
        page_end: 162,
        title: '对中央关于城市人民公社问题指示稿的批语和修改',
        dates: [{ year: 1960, month: 3, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 163,
        page_end: 165,
        title: '中央转发河南省委关于五级干部会议情况报告的批语',
        dates: [{ year: 1960, month: 3, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 166,
        page_end: 166,
        title: '中央转发江苏省委关于召开六级干部大会部署报告的批语',
        dates: [{ year: 1960, month: 3, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 170,
        page_end: 171,
        title: '中央转发山东省委关于生活安排情况报告的批语',
        dates: [{ year: 1960, month: 3, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 172,
        page_end: 173,
        title: '中央转发湖南省农业生产情况综合报告的批语',
        dates: [{ year: 1960, month: 3, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 174,
        page_end: 175,
        title:
          '为审阅中央转发湖南、山东、江苏省委报告的三个批语稿给刘少奇、邓小平的信',
        dates: [{ year: 1960, month: 3, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 176,
        page_end: 176,
        title: '在黑龙江省农村公共食堂情况汇报上写的几句话',
        dates: [{ year: 1960, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 177,
        page_end: 183,
        title: '中央关于加强公共食堂领导的批语',
        dates: [{ year: 1960, month: 3, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 184,
        page_end: 186,
        title: '中央关于加强技术革新和技术革命运动领导的批语',
        dates: [{ year: 1960, month: 3, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 187,
        page_end: 189,
        title: '中央关于卫生工作的指示',
        dates: [{ year: 1960, month: 3, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 190,
        page_end: 191,
        title:
          '为审阅中央关于技术革命、食堂问题、卫生工作的批语稿和指示稿给刘少奇、邓小平的信',
        dates: [{ year: 1960, month: 3, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 192,
        page_end: 192,
        title: '关于修改李富春、李先念向人代会的报告的批语',
        dates: [{ year: 1960, month: 3, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 193,
        page_end: 200,
        title: '中尼边界要永远和平友好',
        dates: [{ year: 1960, month: 3, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 201,
        page_end: 201,
        title: '对缔结中蒙友好合作条约问题的批语',
        dates: [{ year: 1960, month: 3, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 202,
        page_end: 204,
        title: '中央转发鞍山市委关于技术革新和技术革命运动开展情况报告的批语',
        dates: [{ year: 1960, month: 3, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 205,
        page_end: 208,
        title: '关于反华问题',
        dates: [{ year: 1960, month: 3, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 209,
        page_end: 209,
        title: '给田家英的信',
        dates: [{ year: 1960, month: 3, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 210,
        page_end: 213,
        title: '中央转发山东省六级干部会议情况简报的批语',
        dates: [
          { year: 1960, month: 3, day: 22 },
          { year: 1960, month: 3, day: 23 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 214,
        page_end: 215,
        title: '转发聂荣臻关于广州、重庆两市技术革命运动情况报告的批语',
        dates: [{ year: 1960, month: 3, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 216,
        page_end: 216,
        title: '关于印发哈尔滨市建成两条养猪自动线材料的批语',
        dates: [{ year: 1960, month: 3, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 217,
        page_end: 218,
        title: '关于中央批转的文件字要印大一些的批语',
        dates: [{ year: 1960, month: 3, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 219,
        page_end: 220,
        title: '对李富春关于一九六○年国民经济计划草案报告稿的修改',
        dates: [{ year: 1960, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 221,
        page_end: 223,
        title:
          '对李先念关于一九五九年国家决算和一九六O年国家预算草案报告稿的批语和修改',
        dates: [{ year: 1960, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 224,
        page_end: 228,
        title: '中央关于反对官僚主义的指示',
        dates: [{ year: 1960, month: 3, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 236,
        page_end: 237,
        title:
          '对中央转发宁夏区党委关于纠正中宁县工作中错误问题报告的指示稿的批语',
        dates: [{ year: 1960, month: 3, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 238,
        page_end: 241,
        title: '在天津会议上的讲话',
        dates: [{ year: 1960, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 243,
        page_end: 244,
        title: '毛泽东等祝贺匈牙利解放十五周年的电报',
        dates: [{ year: 1960, month: 4, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 245,
        page_end: 246,
        title: '对陆定一在全国人代会上的发言稿《教学必须改革》的批语',
        dates: [{ year: 1960, month: 4, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 247,
        page_end: 248,
        title: '中央转发江苏省六级干部大会报告的批语',
        dates: [{ year: 1960, month: 4, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 249,
        page_end: 250,
        title:
          '对吉林省委“三反”部署报告的批语和在中央转发这一报告的指示稿上加写的话',
        dates: [
          { year: 1960, month: 4, day: 7 },
          { year: 1960, month: 4, day: 11 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 251,
        page_end: 252,
        title: '关于阅读有关英、法、美、西德关系等五篇文章的批语',
        dates: [{ year: 1960, month: 4, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 253,
        page_end: 255,
        title: '中央转发山西省委六级干部会议情况报告的批语',
        dates: [{ year: 1960, month: 4, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 257,
        page_end: 257,
        title: '在全国民兵代表会议筹备情况和安排意见报告上的批语',
        dates: [{ year: 1960, month: 4, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 258,
        page_end: 261,
        title: '对《列宁主义万岁》一文送审稿的批语和修改',
        dates: [{ year: 1960, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 262,
        page_end: 263,
        title: '中央转发中南协作区常委会议情况报告的批语',
        dates: [{ year: 1960, month: 4, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 264,
        page_end: 265,
        title:
          '中央转发《各行各业办机械是高速度发展机械工业的好办法》一文的批语',
        dates: [{ year: 1960, month: 4, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 266,
        page_end: 268,
        title:
          '对中央转发山西省委推广万荣县注音扫盲经验报告的指示稿的批语和修改',
        dates: [{ year: 1960, month: 4, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 269,
        page_end: 270,
        title: '对冶金部关于继续大办钢铁“小洋群”和“小洋群”升级问题的报告的批语',
        dates: [{ year: 1960, month: 4, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 271,
        page_end: 271,
        title: '给杨开英的信',
        dates: [{ year: 1960, month: 4, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 274,
        page_end: 275,
        title: '关于查找城市人民公社问题发言材料等的批语',
        dates: [{ year: 1960, month: 4, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 276,
        page_end: 277,
        title: '对薄一波关于技术革新、技术革命运动报告的批语',
        dates: [{ year: 1960, month: 4, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 280,
        page_end: 281,
        title: '对资本主义社会内有社会主义经济形式存在的论点的批语',
        dates: [{ year: 1960, month: 4, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 282,
        page_end: 282,
        title: '给杨开英的信',
        dates: [{ year: 1960, month: 4, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 284,
        page_end: 285,
        title: '对中央转发聂荣臻关于公开报道“四化”运动意见的批语稿的修改',
        dates: [{ year: 1960, month: 4, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 286,
        page_end: 290,
        title: '读《古巴人民社会党党纲草案》时写的批注',
        dates: [{ year: 1960, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 292,
        page_end: 292,
        title: '关于要写一篇《同库西宁同志商榨》的文章的批语',
        dates: [{ year: 1960, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 297,
        page_end: 300,
        title: '现在是帝国主义怕我们的时代',
        dates: [{ year: 1960, month: 5, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 314,
        page_end: 322,
        title: '帝国主义是不可怕的',
        dates: [{ year: 1960, month: 5, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 323,
        page_end: 324,
        title: '毛泽东等祝贺德意志民主共和国解放十五周年的电报',
        dates: [{ year: 1960, month: 5, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 325,
        page_end: 325,
        title: '关于三大作风提法的批语',
        dates: [{ year: 1960, month: 5, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 326,
        page_end: 327,
        title: '接见拉丁美洲八个国家的代表和著名人士时的谈话',
        dates: [{ year: 1960, month: 5, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 328,
        page_end: 329,
        title: '毛泽东等祝贺捷克斯洛伐克解放十五周年的电报',
        dates: [{ year: 1960, month: 5, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 330,
        page_end: 336,
        title: '接见伊拉克、伊朗和塞浦路斯代表团时的谈话',
        dates: [{ year: 1960, month: 5, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 343,
        page_end: 343,
        title: '在《参考资料》第三五九○期上的批语',
        dates: [{ year: 1960, month: 5, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 344,
        page_end: 345,
        title: '坚决支持日本人民反对日美军事同盟条约的斗争',
        dates: [{ year: 1960, month: 5, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 347,
        page_end: 351,
        title: '被压迫的人民就是要不屈服',
        dates: [{ year: 1960, month: 5, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 352,
        page_end: 353,
        title: '毛泽东等祝贺胡志明七十寿辰的电报',
        dates: [{ year: 1960, month: 5, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 354,
        page_end: 367,
        title: '和蒙哥马利的谈话',
        dates: [{ year: 1960, month: 5, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 368,
        page_end: 369,
        title: '给卡斯特罗的信',
        dates: [{ year: 1960, month: 5, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 370,
        page_end: 370,
        title: '对一份摘录南斯拉夫方面言论的内部材料的批语',
        dates: [{ year: 1960, month: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 371,
        page_end: 372,
        title: '对《四国首脑会议破裂后的初步反应》一文的批语',
        dates: [{ year: 1960, month: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 374,
        page_end: 374,
        title: '印发我国参加东巴基斯坦国际工业展览会总结报告的批语',
        dates: [{ year: 1960, month: 6, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 375,
        page_end: 376,
        title: '对宦乡关于四国首脑会议流产后国际形势的分析和展望的批语',
        dates: [{ year: 1960, month: 6, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 377,
        page_end: 378,
        title: '对《有关美国军事生产的一些资料》的批语',
        dates: [
          { year: 1960, month: 6, day: 8 },
          { year: 1960, month: 6, day: 9 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 380,
        page_end: 382,
        title: '关于召开各国共产党和工人党代表会议的两点建议给苏共中央的信',
        dates: [{ year: 1960, month: 6, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 383,
        page_end: 384,
        title: '七律·读报有感之三',
        dates: [{ year: 1960, month: 6, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 386,
        page_end: 388,
        title: '中央转发广东省委关于农村“三反”问题的两个文件的批语',
        dates: [{ year: 1960, month: 6, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 390,
        page_end: 390,
        title: '在上海会议上的讲话',
        dates: [{ year: 1960, month: 6, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 391,
        page_end: 392,
        title: '在中央政治局扩大会议上印发四个文件的批语',
        dates: [{ year: 1960, month: 6, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 394,
        page_end: 394,
        title: '在上海会议上的讲话',
        dates: [{ year: 1960, month: 6, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 395,
        page_end: 398,
        title: '十年总结',
        dates: [{ year: 1960, month: 6, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 400,
        page_end: 401,
        title: '对蒙哥马利《我同毛的会谈》一文的批语',
        dates: [{ year: 1960, month: 6, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 402,
        page_end: 402,
        title: '对蒙哥马利《一种清醒的作法》一书的批语',
        dates: [{ year: 1960, month: 6, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 403,
        page_end: 410,
        title: '美帝国主义是中日两国人民的共同敌人',
        dates: [{ year: 1960, month: 6, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 411,
        page_end: 411,
        title: '关于通知吴启瑞来上海给陈不显的信',
        dates: [{ year: 1960, month: 6, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 412,
        page_end: 412,
        title: '对《高举莫斯科宣言的马克思列宁主义革命旗帜》社论稿的修改',
        dates: [{ year: 1960, month: 6, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 413,
        page_end: 413,
        title: '对蒙哥马利在德拉鲁公司宴会上的讲话摘要的批语',
        dates: [{ year: 1960, month: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 414,
        page_end: 414,
        title: '印发十六件关于目前形势的报道的批语',
        dates: [{ year: 1960, month: 7, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 415,
        page_end: 416,
        title: '毛泽东等祝贺蒙古人民革命胜利三十九周年的电报',
        dates: [{ year: 1960, month: 7, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 417,
        page_end: 417,
        title: '在北戴河会议上的讲话',
        dates: [{ year: 1960, month: 7, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 421,
        page_end: 421,
        title: '在《宣教动态》第五十期上的批语',
        dates: [{ year: 1960, month: 7, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 425,
        page_end: 427,
        title: '对周扬在第三次全国文代会上的报告稿的批语和修改',
        dates: [{ year: 1960, month: 7, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 436,
        page_end: 437,
        title: '毛泽东等祝贺波兰国庆十六周年的电报',
        dates: [{ year: 1960, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 438,
        page_end: 440,
        title: '在《内部参考》增刊第三十期上的批语',
        dates: [{ year: 1960, month: 7, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 441,
        page_end: 442,
        title: '在关于辩论现代修正主义问题的两份材料上的批语',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 443,
        page_end: 443,
        title: '在苏联《政治自学》杂志发表有关国际问题文章的情况报告上的批语',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 444,
        page_end: 444,
        title: '在关于近两日苏联对古巴、刚果局势态度的电报上的批语',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 446,
        page_end: 446,
        title: '在阿尔巴尼亚驻罗大使谈话摘要报告上的批语',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 447,
        page_end: 447,
        title: '对《美军重视研究现代战争中“人的因素”》一文的批语',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 448,
        page_end: 448,
        title: '在可否将中苏分歧向使馆干部传达的请示报告上的批语',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 449,
        page_end: 449,
        title: '在关于最近苏联对中国大使馆的态度变化情况报告上的批语',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 450,
        page_end: 450,
        title: '在一份关于捷共学生党员与中国留学生谈话情况报告上的批语',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 451,
        page_end: 451,
        title: '在一份关于萨瓦茨基提到加强与中国友谊的报告上的批语',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 452,
        page_end: 452,
        title: '在一份关于日夫科夫正在撰文批评中共“教条主义”的情况报告上的批语',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 453,
        page_end: 454,
        title: '对第一坦克学校部分学员讨论“战争与和平”问题的材料的批注',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 455,
        page_end: 455,
        title: '在一份关于西德扩军备战的材料上的批语',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 456,
        page_end: 456,
        title: '在一位保共党员对中共看法的报告上的批语',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 457,
        page_end: 457,
        title: '印发《中国年》一文的批语',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 458,
        page_end: 458,
        title: '在一位捷共工人党员谈话情况报告上的批语',
        dates: [{ year: 1960, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 459,
        page_end: 460,
        title: '对阿登纳和戴高乐会谈的三条消息的批语',
        dates: [{ year: 1960, month: 8, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 461,
        page_end: 461,
        title: '关于在西沙群岛建立海军据点问题的批语',
        dates: [{ year: 1960, month: 8, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 462,
        page_end: 462,
        title: '关于请各省市区报告雨情的批语',
        dates: [{ year: 1960, month: 8, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 463,
        page_end: 463,
        title: '对金门蒋军向我炮击的处置意见的批语',
        dates: [{ year: 1960, month: 8, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 464,
        page_end: 464,
        title: '对中央关于全党动手大办农业、大办粮食的指示稿的批语',
        dates: [{ year: 1960, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 466,
        page_end: 466,
        title: '关于抄录昆明滇池对联的批语',
        dates: [{ year: 1960, month: 8, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 467,
        page_end: 468,
        title: '毛泽东等祝贺朝鲜解放十五周年的电报',
        dates: [{ year: 1960, month: 8, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 469,
        page_end: 470,
        title: '关于坚决地认真地清理劳动力加强农业生产第一线的紧急指示',
        dates: [{ year: 1960, month: 8, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 471,
        page_end: 471,
        title: '关于酌情安排夏在伯等三人工作的批语',
        dates: [{ year: 1960, month: 8, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 477,
        page_end: 478,
        title: '毛泽东等祝贺罗马尼亚解放十六周年的电报',
        dates: [{ year: 1960, month: 8, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 479,
        page_end: 480,
        title: '中央转发江苏省委常委扩大会议情况简报的批语',
        dates: [{ year: 1960, month: 8, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 481,
        page_end: 481,
        title: '中央转发河南省委贯彻北戴河会议部署情况简报的批语',
        dates: [{ year: 1960, month: 8, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 482,
        page_end: 483,
        title: '对阿里埃蒂关于布加勒斯特会议的看法的批语',
        dates: [{ year: 1960, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 484,
        page_end: 485,
        title: '转发黑龙江省委传达北戴河会议精神报告的批语',
        dates: [{ year: 1960, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 486,
        page_end: 488,
        title: '毛泽东等祝贺越南民主共和国成立十五周年的电报',
        dates: [{ year: 1960, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 489,
        page_end: 489,
        title: '给张维的信',
        dates: [{ year: 1960, month: 9, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 491,
        page_end: 491,
        title: '给田士清的信',
        dates: [{ year: 1960, month: 9, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 493,
        page_end: 493,
        title: '给吴启瑞的信',
        dates: [{ year: 1960, month: 9, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 494,
        page_end: 495,
        title: '毛泽东等祝贺保加利亚社会主义革命十六周年的电报',
        dates: [{ year: 1960, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 499,
        page_end: 500,
        title: '中央转发安徽省委传达北戴河会议精神报告的批语',
        dates: [{ year: 1960, month: 9, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 501,
        page_end: 505,
        title: '和夏基、狄克逊的谈话',
        dates: [{ year: 1960, month: 9, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 506,
        page_end: 507,
        title: '对谭震林关于晋冀鲁豫辽五省农业情况报告的批语',
        dates: [{ year: 1960, month: 9, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 508,
        page_end: 510,
        title: '只要双方友好，边界问题就好解决',
        dates: [{ year: 1960, month: 9, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 511,
        page_end: 513,
        title: '和阿尔及利亚临时政府总理阿巴斯的谈话要点',
        dates: [{ year: 1960, month: 9, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 515,
        page_end: 515,
        title: '感谢几内亚总统祝贺我国国庆的电报',
        dates: [{ year: 1960, month: 10, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 520,
        page_end: 521,
        title: '感谢泰国前总理比里·帕侬荣祝贺我国国庆的复信',
        dates: [
          { year: 1960, month: 10, day: 3 },
          { year: 1960, month: 10, day: 8 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 522,
        page_end: 523,
        title: '毛泽东等祝贺德意志民主共和国成立十一周年的电报',
        dates: [{ year: 1960, month: 10, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 524,
        page_end: 524,
        title: '为中央办公厅工作人员题词',
        dates: [{ year: 1960, month: 10, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 525,
        page_end: 528,
        title: '关于转发湖北和福建省委两个文件的批语',
        dates: [
          { year: 1960, month: 10, day: 10 },
          { year: 1960, month: 10, day: 12 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 529,
        page_end: 530,
        title: '关于会谈国际形势给刘少奇、周恩来、朱德等的信',
        dates: [{ year: 1960, month: 10, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 531,
        page_end: 532,
        title: '对《麦克米伦的作用》一文的批语',
        dates: [{ year: 1960, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
    ],
  },
  parser_id: 'automation',
  path: '/archives0/maoquanji43.pdf',
};
