export default {
  entity: {
    id: 'maoquanji4-2',
    name: '毛泽东全集第4卷(2)',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives8/main/maoquanji4-2.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '告全国士兵弟兄书',
        authors: ['毛泽东'],
        page_start: 1,
        page_end: 5,
        dates: [{ year: 1929 }],
        is_range_date: false,
      },
      {
        title: '告绿林弟兄书',
        authors: ['毛泽东'],
        page_start: 6,
        page_end: 11,
        dates: [{ year: 1929 }],
        is_range_date: false,
      },
      {
        title: '星星之火，可以燎原',
        authors: ['毛泽东'],
        page_start: 12,
        page_end: 30,
        dates: [{ year: 1930, month: 1, day: 5 }],
        is_range_date: false,
      },
      {
        title: '中国红军第四军告国民党军队士兵书',
        authors: ['毛泽东'],
        page_start: 31,
        page_end: 37,
        dates: [{ year: 1930, month: 1 }],
        is_range_date: false,
      },
      {
        title: '如梦令·元日',
        authors: ['毛泽东'],
        page_start: 38,
        page_end: 40,
        dates: [{ year: 1930, month: 1 }],
        is_range_date: false,
      },
      {
        title: '减字木兰花·广昌路上',
        authors: ['毛泽东'],
        page_start: 41,
        page_end: 48,
        dates: [{ year: 1930, month: 2 }],
        is_range_date: false,
      },
      {
        title: '土地法',
        authors: ['毛泽东'],
        page_start: 49,
        page_end: 54,
        dates: [{ year: 1930, month: 2, day: 7 }],
        is_range_date: false,
      },
      {
        title: '关于古领吉安建立江西苏维埃政府',
        authors: ['毛泽东'],
        page_start: 55,
        page_end: 60,
        dates: [{ year: 1930, month: 2, day: 14 }],
        is_range_date: false,
      },
      {
        title: '联席会议的结论并宣告前委成立',
        authors: ['毛泽东'],
        page_start: 61,
        page_end: 63,
        dates: [{ year: 1930, month: 2, day: 16 }],
        is_range_date: false,
      },
      {
        title: '分兵争取群众的意义及工作路线',
        authors: ['毛泽东'],
        page_start: 64,
        page_end: 69,
        dates: [{ year: 1930, month: 3, day: 18 }],
        is_range_date: false,
      },
      {
        title: '关于第一次攻赣州的经验教训的训令',
        authors: ['毛泽东'],
        page_start: 70,
        page_end: 71,
        dates: [{ year: 1930, month: 3, day: 19 }],
        is_range_date: false,
      },
      {
        title: '整顿军风纪的训令',
        authors: ['毛泽东'],
        page_start: 72,
        page_end: 72,
        dates: [{ year: 1930, month: 3, day: 21 }],
        is_range_date: false,
      },
      {
        title: '关于官兵考绩的训令',
        authors: ['毛泽东'],
        page_start: 73,
        page_end: 76,
        dates: [{ year: 1930, month: 3, day: 29 }],
        is_range_date: false,
      },
      {
        title: '征募和教育新兵问题的训令',
        authors: ['毛泽东'],
        page_start: 77,
        page_end: 78,
        dates: [{ year: 1930, month: 3, day: 29 }],
        is_range_date: false,
      },
      {
        title: '官传员工作纲要',
        authors: ['毛泽东'],
        page_start: 79,
        page_end: 80,
        dates: [{ year: 1930, month: 4, day: 26 }],
        is_range_date: false,
      },
      {
        title: '加强体力与提高射击技术的训令',
        authors: ['毛泽东'],
        page_start: 81,
        page_end: 82,
        dates: [{ year: 1930, month: 4 }],
        is_range_date: false,
      },
      {
        title: '反对本本主义',
        authors: ['毛泽东'],
        page_start: 83,
        page_end: 93,
        dates: [{ year: 1930, month: 5 }],
        is_range_date: false,
      },
      {
        title: '寻乌调查',
        authors: ['毛泽东'],
        page_start: 94,
        page_end: 218,
        dates: [{ year: 1930, month: 5 }],
        is_range_date: false,
      },
    ],
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives8/maoquanji4-2.pdf',
};
