export default {
  entity: {
    id: 'maoquanji12',
    name: '毛泽东全集第12卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives8/main/maoquanji12.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '在延安反侵略大会上的演说',
        authors: ['毛泽东'],
        page_start: 27,
        page_end: 28,
        dates: [{ year: 1938, month: 2, day: 11 }],
        is_range_date: false,
      },
      {
        title: '给范长江的信',
        authors: ['毛泽东'],
        page_start: 29,
        page_end: 33,
        dates: [{ year: 1938, month: 2, day: 15 }],
        is_range_date: false,
      },
      {
        title: '茅山山脉利于新四军发展',
        authors: ['毛泽东'],
        page_start: 34,
        page_end: 35,
        dates: [{ year: 1938, month: 2, day: 15 }],
        is_range_date: false,
      },
      {
        title: '关于一一五师分三步向河北山东等地进军的意见',
        authors: ['毛泽东'],
        page_start: 36,
        page_end: 37,
        dates: [{ year: 1938, month: 2, day: 15 }],
        is_range_date: false,
      },
      {
        title: '在中共中央常委会议上的讲话',
        authors: ['毛泽东'],
        page_start: 38,
        page_end: 38,
        dates: [{ year: 1938, month: 2, day: 18 }],
        is_range_date: false,
      },
      {
        title: '力争建立长期抗战的主要战略支点',
        authors: ['毛泽东'],
        page_start: 39,
        page_end: 40,
        dates: [{ year: 1938, month: 2, day: 21 }],
        is_range_date: false,
      },
      {
        title: '为陕北公学第六、七、八、九、十队毕业题词',
        authors: ['毛泽东'],
        page_start: 41,
        page_end: 41,
        dates: [{ year: 1938, month: 2, day: 22 }],
        is_range_date: false,
      },
      {
        title: '关于战略计划和将来行动的意见',
        authors: ['毛泽东'],
        page_start: 42,
        page_end: 45,
        dates: [{ year: 1938, month: 2, day: 23 }],
        is_range_date: false,
      },
      {
        title: '须尽全力齐灭府城西进之敌',
        authors: ['毛泽东'],
        page_start: 46,
        page_end: 46,
        dates: [{ year: 1938, month: 2, day: 25 }],
        is_range_date: false,
      },
      {
        title: '给何长工的信',
        authors: ['毛泽东'],
        page_start: 47,
        page_end: 47,
        dates: [{ year: 1938, month: 2, day: 25 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 48,
        page_end: 48,
        dates: [{ year: 1938, month: 2, day: 28 }],
        is_range_date: false,
      },
      {
        title: '三四三旅应即改变作战计划',
        authors: ['毛泽东'],
        page_start: 49,
        page_end: 50,
        dates: [{ year: 1938, month: 2, day: 28 }],
        is_range_date: false,
      },
      {
        title: '鲁迅艺术学院创文缘起',
        authors: ['毛泽东'],
        page_start: 51,
        page_end: 52,
        dates: [{ year: 1938, month: 2 }],
        is_range_date: false,
      },
      {
        title: '和合众社记者王公达的谈话',
        authors: ['毛泽东'],
        page_start: 53,
        page_end: 57,
        dates: [{ year: 1938, month: 2 }],
        is_range_date: false,
      },
      {
        title: '关于巩固河防的部署',
        authors: ['毛泽东'],
        page_start: 58,
        page_end: 59,
        dates: [{ year: 1938, month: 3, day: 2 }],
        is_range_date: false,
      },
      {
        title: '对陕北公学毕业同学的临别赠言',
        authors: ['毛泽东'],
        page_start: 60,
        page_end: 65,
        dates: [{ year: 1938, month: 3, day: 3 }],
        is_range_date: false,
      },
      {
        title: '我后路不被隔断的条件下主力可留普击故',
        authors: ['毛泽东'],
        page_start: 66,
        page_end: 66,
        dates: [{ year: 1938, month: 3, day: 3 }],
        is_range_date: false,
      },
      {
        title: '敌情与一一五师之部署叫',
        authors: ['毛泽东'],
        page_start: 67,
        page_end: 68,
        dates: [{ year: 1938, month: 3, day: 3 }],
        is_range_date: false,
      },
      {
        title: '给毛岸英、毛岸青的信',
        authors: ['毛泽东'],
        page_start: 69,
        page_end: 69,
        dates: [{ year: 1938, month: 3, day: 4 }],
        is_range_date: false,
      },
      {
        title: '为“抗大同学会”成立题词',
        authors: ['毛泽东'],
        page_start: 70,
        page_end: 71,
        dates: [{ year: 1938, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '对陈光罗荣柜部行动问题的指示',
        authors: ['毛泽东'],
        page_start: 72,
        page_end: 73,
        dates: [{ year: 1938, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '复彭雪枫电',
        authors: ['毛泽东'],
        page_start: 74,
        page_end: 74,
        dates: [{ year: 1938, month: 3, day: 6 }],
        is_range_date: false,
      },
      {
        title: '有计划地部署普豫边的游击战争',
        authors: ['毛泽东'],
        page_start: 75,
        page_end: 76,
        dates: [{ year: 1938, month: 3, day: 6 }],
        is_range_date: false,
      },
      {
        title: '一二〇师应与傅作义协力击破西进之敌',
        authors: ['毛泽东'],
        page_start: 77,
        page_end: 78,
        dates: [{ year: 1938, month: 3, day: 6 }],
        is_range_date: false,
      },
      {
        title: '三五八旅宜从委烦方向打起',
        authors: ['毛泽东'],
        page_start: 79,
        page_end: 80,
        dates: [{ year: 1938, month: 3, day: 7 }],
        is_range_date: false,
      },
      {
        title: '军委指导只提出大的方针',
        authors: ['毛泽东'],
        page_start: 81,
        page_end: 81,
        dates: [{ year: 1938, month: 3, day: 8 }],
        is_range_date: false,
      },
      {
        title: '为陕甘宁边区妇女联合会第一次代表大会题词叫',
        authors: ['毛泽东'],
        page_start: 82,
        page_end: 82,
        dates: [{ year: 1938, month: 3, day: 8 }],
        is_range_date: false,
      },
      {
        title: '八路军应准备转战陕甘像地区',
        authors: ['毛泽东'],
        page_start: 83,
        page_end: 85,
        dates: [{ year: 1938, month: 3, day: 9 }],
        is_range_date: false,
      },
      {
        title: '在纪念孙中山逝世十三周年暨追惊抗敌阵亡将士大会上的讲话',
        authors: ['毛泽东'],
        page_start: 86,
        page_end: 91,
        dates: [{ year: 1938, month: 3, day: 12 }],
        is_range_date: false,
      },
      {
        title: '题纪念孙中山逝世十三周年暨追停抗敌阵亡将士大会联',
        authors: ['毛泽东'],
        page_start: 92,
        page_end: 92,
        dates: [{ year: 1938, month: 3 }],
        is_range_date: false,
      },
      {
        title: '给金城“的信',
        authors: ['毛泽东'],
        page_start: 93,
        page_end: 93,
        dates: [{ year: 1938, month: 3, day: 13 }],
        is_range_date: false,
      },
      {
        title: '刘伯承师徐海东旅主力以担任正太作战任务为宜',
        authors: ['毛泽东'],
        page_start: 94,
        page_end: 94,
        dates: [{ year: 1938, month: 3, day: 14 }],
        is_range_date: false,
      },
      {
        title: '在抗大第三期三大队毕业典礼上的讲话',
        authors: ['毛泽东'],
        page_start: 95,
        page_end: 95,
        dates: [{ year: 1938, month: 3, day: 15 }],
        is_range_date: false,
      },
      {
        title: '对巩固吕梁山脉问题的指示',
        authors: ['毛泽东'],
        page_start: 96,
        page_end: 97,
        dates: [{ year: 1938, month: 3, day: 16 }],
        is_range_date: false,
      },
      {
        title: '与国民党谈华北军事时注意分两个阶段',
        authors: ['毛泽东'],
        page_start: 98,
        page_end: 99,
        dates: [{ year: 1938, month: 3, day: 17 }],
        is_range_date: false,
      },
      {
        title: '刘伯承师目前留东边活动有利',
        authors: ['毛泽东'],
        page_start: 100,
        page_end: 100,
        dates: [{ year: 1938, month: 3, day: 18 }],
        is_range_date: false,
      },
      {
        title: '为华侨记老团题词叫',
        authors: ['毛泽东'],
        page_start: 101,
        page_end: 101,
        dates: [{ year: 1938, month: 3, day: 18 }],
        is_range_date: false,
      },
      {
        title: '为《南国日报》题词叫',
        authors: ['毛泽东'],
        page_start: 102,
        page_end: 102,
        dates: [{ year: 1938, month: 3, day: 18 }],
        is_range_date: false,
      },
      {
        title: '在抗大第四期第五大队开学典礼上的讲话',
        authors: ['毛泽东'],
        page_start: 103,
        page_end: 103,
        dates: [{ year: 1938, month: 3, day: 19 }],
        is_range_date: false,
      },
      {
        title: '认识中国社会性质是重要的中心的一点',
        authors: ['毛泽东'],
        page_start: 104,
        page_end: 109,
        dates: [{ year: 1938, month: 3, day: 20 }],
        is_range_date: false,
      },
      {
        title: '贺龙师主力须逐渐南下以代林彪师陈光旅',
        authors: ['毛泽东'],
        page_start: 110,
        page_end: 110,
        dates: [{ year: 1938, month: 3, day: 21 }],
        is_range_date: false,
      },
      {
        title: '致八路军总部等电',
        authors: ['毛泽东'],
        page_start: 111,
        page_end: 111,
        dates: [{ year: 1938, month: 3, day: 22 }],
        is_range_date: false,
      },
      {
        title: '在中共中央常委会议上的讲话',
        authors: ['毛泽东'],
        page_start: 112,
        page_end: 112,
        dates: [{ year: 1938, month: 3, day: 23 }],
        is_range_date: false,
      },
      {
        title: '为梁毅题词',
        authors: ['毛泽东'],
        page_start: 113,
        page_end: 114,
        dates: [{ year: 1938, month: 3, day: 23 }],
        is_range_date: false,
      },
      {
        title: '和邓静溪的谈话',
        authors: ['毛泽东'],
        page_start: 115,
        page_end: 115,
        dates: [{ year: 1938, month: 3, day: 24 }],
        is_range_date: false,
      },
      {
        title: '以最快速度创造巩固的英普像根据地',
        authors: ['毛泽东'],
        page_start: 116,
        page_end: 117,
        dates: [{ year: 1938, month: 3, day: 24 }],
        is_range_date: false,
      },
      {
        title: '普东南作战的主要任务',
        authors: ['毛泽东'],
        page_start: 118,
        page_end: 118,
        dates: [{ year: 1938, month: 3, day: 24 }],
        is_range_date: false,
      },
      {
        title: '立即组织以八路军名义出现的游击兵团',
        authors: ['毛泽东'],
        page_start: 119,
        page_end: 120,
        dates: [{ year: 1938, month: 3, day: 24 }],
        is_range_date: false,
      },
      {
        title: '英鲁像急需建立军政统一领导',
        authors: ['毛泽东'],
        page_start: 121,
        page_end: 122,
        dates: [{ year: 1938, month: 3, day: 25 }],
        is_range_date: false,
      },
      {
        title: '致贺龙、萧克、关向应电',
        authors: ['毛泽东'],
        page_start: 123,
        page_end: 123,
        dates: [{ year: 1938, month: 3, day: 29 }],
        is_range_date: false,
      },
      {
        title: '刘伯承师徐海东旅宜位于同蒲路东侧',
        authors: ['毛泽东'],
        page_start: 124,
        page_end: 124,
        dates: [{ year: 1938, month: 3, day: 29 }],
        is_range_date: false,
      },
      {
        title: '对陕北公学第十一至第二十队学员的讲话',
        authors: ['毛泽东'],
        page_start: 125,
        page_end: 125,
        dates: [{ year: 1938, month: 3, day: 29 }],
        is_range_date: false,
      },
      {
        title: '对抗大干部的讲话',
        authors: ['毛泽东'],
        page_start: 126,
        page_end: 126,
        dates: [{ year: 1938, month: 3, day: 30 }],
        is_range_date: false,
      },
      {
        title: '在《接助陕北》一书上的题词',
        authors: ['毛泽东'],
        page_start: 127,
        page_end: 127,
        dates: [{ year: 1938, month: 3 }],
        is_range_date: false,
      },
      {
        title: '在陕北公学第二期开学典礼大会上的讲话',
        authors: ['毛泽东'],
        page_start: 128,
        page_end: 132,
        dates: [{ year: 1938, month: 4, day: 1 }],
        is_range_date: false,
      },
      {
        title: '抗日军人必须具备三个条件0',
        authors: ['毛泽东'],
        page_start: 133,
        page_end: 133,
        dates: [{ year: 1938, month: 4, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致周恩来、叶剑英电',
        authors: ['毛泽东'],
        page_start: 134,
        page_end: 134,
        dates: [{ year: 1938, month: 4, day: 5 }],
        is_range_date: false,
      },
      {
        title: '国共两党合作问题',
        authors: ['毛泽东'],
        page_start: 135,
        page_end: 142,
        dates: [{ year: 1938, month: 4, day: 5 }],
        is_range_date: false,
      },
      {
        title: '在抗大应当学习什么？回',
        authors: ['毛泽东'],
        page_start: 143,
        page_end: 147,
        dates: [{ year: 1938, month: 4, day: 9 }],
        is_range_date: false,
      },
      {
        title: '在鲁迅艺术学院成立大会上的讲话',
        authors: ['毛泽东'],
        page_start: 148,
        page_end: 148,
        dates: [{ year: 1938, month: 4, day: 10 }],
        is_range_date: false,
      },
      {
        title: '在边区国防教育会第一次代表大会开幕典礼上的讲话',
        authors: ['毛泽东'],
        page_start: 149,
        page_end: 149,
        dates: [{ year: 1938, month: 4, day: 11 }],
        is_range_date: false,
      },
      {
        title: '为西北青年救国联合会成立一周年题词',
        authors: ['毛泽东'],
        page_start: 150,
        page_end: 150,
        dates: [{ year: 1938, month: 4, day: 15 }],
        is_range_date: false,
      },
      {
        title: '致贺龙、萧克、关向应电',
        authors: ['毛泽东'],
        page_start: 151,
        page_end: 151,
        dates: [{ year: 1938, month: 4, day: 18 }],
        is_range_date: false,
      },
      {
        title: '中共中央关于开除张国寿党籍的决定',
        authors: ['毛泽东'],
        page_start: 152,
        page_end: 153,
        dates: [{ year: 1938, month: 4, day: 18 }],
        is_range_date: false,
      },
      {
        title: '巩固与发展普察童根据地',
        authors: ['毛泽东'],
        page_start: 154,
        page_end: 156,
        dates: [{ year: 1938, month: 4, day: 20 }],
        is_range_date: false,
      },
      {
        title: '结团体，打日本',
        authors: ['毛泽东'],
        page_start: 157,
        page_end: 159,
        dates: [{ year: 1938, month: 4, day: 20 }],
        is_range_date: false,
      },
      {
        title: '在河北山东平原地区大量发展游击战争',
        authors: ['毛泽东'],
        page_start: 160,
        page_end: 162,
        dates: [{ year: 1938, month: 4, day: 21 }],
        is_range_date: false,
      },
      {
        title: '复项英电',
        authors: ['毛泽东'],
        page_start: 163,
        page_end: 163,
        dates: [{ year: 1938, month: 4, day: 24 }],
        is_range_date: false,
      },
      {
        title: '在鲁迅艺术学院的讲话',
        authors: ['毛泽东'],
        page_start: 164,
        page_end: 169,
        dates: [{ year: 1938, month: 4, day: 28 }],
        is_range_date: false,
      },
      {
        title: '为“五一”节纪念题词叫',
        authors: ['毛泽东'],
        page_start: 170,
        page_end: 170,
        dates: [{ year: 1938, month: 4, day: 30 }],
        is_range_date: false,
      },
      {
        title: '在抗大第三期第二大队毕业典礼上的讲话',
        authors: ['毛泽东'],
        page_start: 171,
        page_end: 171,
        dates: [{ year: 1938, month: 4, day: 30 }],
        is_range_date: false,
      },
      {
        title: '和白求恩的谈话',
        authors: ['毛泽东'],
        page_start: 172,
        page_end: 172,
        dates: [{ year: 1938, month: 4 }],
        is_range_date: false,
      },
      {
        title: '为“鲁小”第一届毕业生题词',
        authors: ['毛泽东'],
        page_start: 173,
        page_end: 173,
        dates: [{ year: 1938, month: 4 }],
        is_range_date: false,
      },
      {
        title: '为陕甘宁边区《边区教师》杂志题词',
        authors: ['毛泽东'],
        page_start: 174,
        page_end: 175,
        dates: [{ year: 1938, month: 4 }],
        is_range_date: false,
      },
      {
        title: '为抗战文艺工作团写的介绍信',
        authors: ['毛泽东'],
        page_start: 176,
        page_end: 176,
        dates: [{ year: 1938, month: 4 }],
        is_range_date: false,
      },
      {
        title: '关于共产党对三民主义的态度问题的讲话',
        authors: ['毛泽东'],
        page_start: 177,
        page_end: 177,
        dates: [{ year: 1938, month: 5, day: 3 }],
        is_range_date: false,
      },
      {
        title: '合则两利，分则两伤',
        authors: ['毛泽东'],
        page_start: 178,
        page_end: 182,
        dates: [{ year: 1938, month: 5, day: 4 }],
        is_range_date: false,
      },
      {
        title: '放手开展敌后游击战争',
        authors: ['毛泽东'],
        page_start: 183,
        page_end: 185,
        dates: [{ year: 1938, month: 5, day: 4 }],
        is_range_date: false,
      },
      {
        title: '和卡尔逊的谈话',
        authors: ['毛泽东'],
        page_start: 186,
        page_end: 186,
        dates: [{ year: 1938, month: 5, day: 5 }],
        is_range_date: false,
      },
      {
        title: '给长江局的指示',
        authors: ['毛泽东'],
        page_start: 187,
        page_end: 187,
        dates: [{ year: 1938, month: 5, day: 6 }],
        is_range_date: false,
      },
      {
        title: '对来延安参观的平汉铁路工人破坏大队的讲话',
        authors: ['毛泽东'],
        page_start: 188,
        page_end: 188,
        dates: [{ year: 1938, month: 5, day: 8 }],
        is_range_date: false,
      },
      {
        title: '关于中日战争形势的报告叫',
        authors: ['毛泽东'],
        page_start: 189,
        page_end: 189,
        dates: [{ year: 1938, month: 5, day: 10 }],
        is_range_date: false,
      },
      {
        title: '答施方白间',
        authors: ['毛泽东'],
        page_start: 190,
        page_end: 191,
        dates: [{ year: 1938, month: 5, day: 11 }],
        is_range_date: false,
      },
      {
        title: '复陈绍禹、周恩来等电',
        authors: ['毛泽东'],
        page_start: 192,
        page_end: 192,
        dates: [{ year: 1938, month: 5, day: 12 }],
        is_range_date: false,
      },
      {
        title: '为施方白题词',
        authors: ['毛泽东'],
        page_start: 193,
        page_end: 194,
        dates: [{ year: 1938, month: 5, day: 12 }],
        is_range_date: false,
      },
      {
        title: '给郭化荐的信',
        authors: ['毛泽东'],
        page_start: 195,
        page_end: 195,
        dates: [{ year: 1938, month: 5, day: 12 }],
        is_range_date: false,
      },
      {
        title: '《大公报》提倡准决战的论调是不对的叫',
        authors: ['毛泽东'],
        page_start: 196,
        page_end: 196,
        dates: [{ year: 1938, month: 5, day: 13 }],
        is_range_date: false,
      },
      {
        title: '致八路军第一二师并总部北方局等电',
        authors: ['毛泽东'],
        page_start: 197,
        page_end: 197,
        dates: [{ year: 1938, month: 5, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致朱德、彭德怀等电',
        authors: ['毛泽东'],
        page_start: 198,
        page_end: 198,
        dates: [{ year: 1938, month: 5, day: 14 }],
        is_range_date: false,
      },
      {
        title: '进攻是主要的，也是有条件的',
        authors: ['毛泽东'],
        page_start: 199,
        page_end: 199,
        dates: [{ year: 1938, month: 5, day: 14 }],
        is_range_date: false,
      },
      {
        title: '中央关于新四军行动方针的指示',
        authors: ['毛泽东'],
        page_start: 200,
        page_end: 200,
        dates: [{ year: 1938, month: 5, day: 14 }],
        is_range_date: false,
      },
      {
        title: '硬甘宁边区政府第八路军后方留守处布告',
        authors: ['毛泽东'],
        page_start: 201,
        page_end: 203,
        dates: [{ year: 1938, month: 5, day: 15 }],
        is_range_date: false,
      },
      {
        title: '关于接待抗战文艺工作团的电报',
        authors: ['毛泽东'],
        page_start: 204,
        page_end: 204,
        dates: [{ year: 1938, month: 5, day: 19 }],
        is_range_date: false,
      },
      {
        title: '准备向豫皖苏鲁敌后发展',
        authors: ['毛泽东'],
        page_start: 205,
        page_end: 205,
        dates: [{ year: 1938, month: 5, day: 20 }],
        is_range_date: false,
      },
      {
        title: '在抗大对第三期进行总结的干部会议上的讲话',
        authors: ['毛泽东'],
        page_start: 206,
        page_end: 206,
        dates: [{ year: 1938, month: 5, day: 21 }],
        is_range_date: false,
      },
      {
        title: '为抗大第四期开学题词',
        authors: ['毛泽东'],
        page_start: 207,
        page_end: 210,
        dates: [{ year: 1938, month: 5, day: 21 }],
        is_range_date: false,
      },
      {
        title: '电贺各警备兵团“五三十”抗运大会',
        authors: ['毛泽东'],
        page_start: 211,
        page_end: 211,
        dates: [{ year: 1938, month: 5, day: 22 }],
        is_range_date: false,
      },
      {
        title: '给毛宇居的信',
        authors: ['毛泽东'],
        page_start: 212,
        page_end: 213,
        dates: [{ year: 1938, month: 5, day: 26 }],
        is_range_date: false,
      },
      {
        title: '在华北应广泛开展游击战争叫',
        authors: ['毛泽东'],
        page_start: 214,
        page_end: 215,
        dates: [{ year: 1938, month: 5, day: 26 }],
        is_range_date: false,
      },
      {
        title: '抗日战争没有战略进攻只有战役反攻及战略反攻',
        authors: ['毛泽东'],
        page_start: 216,
        page_end: 216,
        dates: [{ year: 1938, month: 5, day: 28 }],
        is_range_date: false,
      },
      {
        title: '给刘雪节的信',
        authors: ['毛泽东'],
        page_start: 217,
        page_end: 217,
        dates: [{ year: 1938, month: 5, day: 28 }],
        is_range_date: false,
      },
      {
        title: '抗日游击战争的战略问题',
        authors: ['毛泽东'],
        page_start: 218,
        page_end: 251,
        dates: [{ year: 1938, month: 5 }],
        is_range_date: false,
      },
      {
        title: '悦王铭章将军联',
        authors: ['毛泽东'],
        page_start: 252,
        page_end: 252,
        dates: [{ year: 1938, month: 5 }],
        is_range_date: false,
      },
      {
        title: '为《五日时事》报题写报头',
        authors: ['毛泽东'],
        page_start: 253,
        page_end: 254,
        dates: [{ year: 1938, month: 5 }],
        is_range_date: false,
      },
      {
        title: '论持久战',
        authors: ['毛泽东'],
        page_start: 255,
        page_end: 341,
        dates: [{ year: 1938, month: 5 }],
        is_range_date: false,
      },
      {
        title: '为《论持久战》题写书名',
        authors: ['毛泽东'],
        page_start: 342,
        page_end: 343,
        dates: [{ year: 1938, month: 5 }],
        is_range_date: false,
      },
      {
        title: '新四军可放手在敌后活动',
        authors: ['毛泽东'],
        page_start: 344,
        page_end: 345,
        dates: [{ year: 1938, month: 6, day: 2 }],
        is_range_date: false,
      },
      {
        title: '紧急声明',
        authors: ['毛泽东'],
        page_start: 346,
        page_end: 346,
        dates: [{ year: 1938, month: 6, day: 3 }],
        is_range_date: false,
      },
      {
        title: '同意郭洪涛关于山东四支队恢复用八路军番号的建议',
        authors: ['毛泽东'],
        page_start: 347,
        page_end: 347,
        dates: [{ year: 1938, month: 6, day: 6 }],
        is_range_date: false,
      },
      {
        title: '在邱踪"来信上的批示',
        authors: ['毛泽东'],
        page_start: 348,
        page_end: 348,
        dates: [{ year: 1938, month: 6, day: 6 }],
        is_range_date: false,
      },
      {
        title: '致邓小平电',
        authors: ['毛泽东'],
        page_start: 349,
        page_end: 349,
        dates: [{ year: 1938, month: 6, day: 7 }],
        is_range_date: false,
      },
      {
        title: '致周恩来、朱德、彭德怀电',
        authors: ['毛泽东'],
        page_start: 350,
        page_end: 350,
        dates: [{ year: 1938, month: 6, day: 8 }],
        is_range_date: false,
      },
      {
        title: '复美共产党全代大会等',
        authors: ['毛泽东'],
        page_start: 351,
        page_end: 351,
        dates: [{ year: 1938, month: 6, day: 8 }],
        is_range_date: false,
      },
      {
        title: '复周恩来等电',
        authors: ['毛泽东'],
        page_start: 352,
        page_end: 352,
        dates: [{ year: 1938, month: 6, day: 9 }],
        is_range_date: false,
      },
      {
        title: '拟创造大青山根据地',
        authors: ['毛泽东'],
        page_start: 353,
        page_end: 353,
        dates: [{ year: 1938, month: 6, day: 11 }],
        is_range_date: false,
      },
      {
        title: '致八路军总部及各师等电',
        authors: ['毛泽东'],
        page_start: 354,
        page_end: 354,
        dates: [{ year: 1938, month: 6, day: 12 }],
        is_range_date: false,
      },
      {
        title: '和诸述初的谈话',
        authors: ['毛泽东'],
        page_start: 355,
        page_end: 355,
        dates: [{ year: 1938, month: 6, day: 14 }],
        is_range_date: false,
      },
      {
        title: '复林伯渠电',
        authors: ['毛泽东'],
        page_start: 356,
        page_end: 356,
        dates: [{ year: 1938, month: 6, day: 15 }],
        is_range_date: false,
      },
      {
        title: '致第一二师负责人等电',
        authors: ['毛泽东'],
        page_start: 357,
        page_end: 357,
        dates: [{ year: 1938, month: 6, day: 15 }],
        is_range_date: false,
      },
      {
        title: '给吴亮平·的信',
        authors: ['毛泽东'],
        page_start: 358,
        page_end: 358,
        dates: [{ year: 1938, month: 6, day: 15 }],
        is_range_date: false,
      },
      {
        title: '在华北西北放手发展游击战争',
        authors: ['毛泽东'],
        page_start: 359,
        page_end: 360,
        dates: [{ year: 1938, month: 6, day: 15 }],
        is_range_date: false,
      },
      {
        title: '为抗战一周年和中国共产党诞生十七周年题词',
        authors: ['毛泽东'],
        page_start: 361,
        page_end: 361,
        dates: [{ year: 1938, month: 6, day: 30 }],
        is_range_date: false,
      },
      {
        title: '为《边区儿童》创刊题词',
        authors: ['毛泽东'],
        page_start: 362,
        page_end: 363,
        dates: [{ year: 1938, month: 6 }],
        is_range_date: false,
      },
      {
        title: '为中国人民抗日军政大学题词',
        authors: ['毛泽东'],
        page_start: 364,
        page_end: 365,
        dates: [{ year: 1938, month: 6 }],
        is_range_date: false,
      },
      {
        title: '硬甘宁边区政府暨八路军后方留守处致全国各界人士公函',
        authors: ['毛泽东'],
        page_start: 366,
        page_end: 367,
        dates: [{ year: 1938, month: 6 }],
        is_range_date: false,
      },
      {
        title: '为影片《西北线上》题名',
        authors: ['毛泽东'],
        page_start: 368,
        page_end: 368,
        dates: [{ year: 1938, month: 6 }],
        is_range_date: false,
      },
      {
        title: '为香港青年摄影团题词',
        authors: ['毛泽东'],
        page_start: 369,
        page_end: 371,
        dates: [{ year: 1938, month: 6 }],
        is_range_date: false,
      },
      {
        title: '为《解放》周刊纪念抗战一周年、中国共产党诞生十七周年专刊题词',
        authors: ['毛泽东'],
        page_start: 372,
        page_end: 373,
        dates: [{ year: 1938, month: 7, day: 1 }],
        is_range_date: false,
      },
      {
        title: '在中共中央召集的欢迎世界学联代表团的干部会议上的欢迎词',
        authors: ['毛泽东'],
        page_start: 374,
        page_end: 374,
        dates: [{ year: 1938, month: 7, day: 1 }],
        is_range_date: false,
      },
      {
        title: '和世界学联代表团的谈话叫',
        authors: ['毛泽东'],
        page_start: 375,
        page_end: 382,
        dates: [{ year: 1938, month: 7, day: 2 }],
        is_range_date: false,
      },
      {
        title: '在抗大欢迎世界学联代表团大会上的欢迎词',
        authors: ['毛泽东'],
        page_start: 383,
        page_end: 385,
        dates: [{ year: 1938, month: 7, day: 3 }],
        is_range_date: false,
      },
      {
        title: '在敌后比较空虚地区发动游击战争',
        authors: ['毛泽东'],
        page_start: 386,
        page_end: 386,
        dates: [{ year: 1938, month: 7, day: 3 }],
        is_range_date: false,
      },
      {
        title: '我们对于国民参政会的意见',
        authors: ['毛泽东'],
        page_start: 387,
        page_end: 391,
        dates: [{ year: 1938, month: 7, day: 5 }],
        is_range_date: false,
      },
      {
        title: '致国民参政会的贺电',
        authors: ['毛泽东'],
        page_start: 392,
        page_end: 392,
        dates: [{ year: 1938, month: 7, day: 5 }],
        is_range_date: false,
      },
      {
        title: '关于巩固山西统战工作问题致杨尚昆等电',
        authors: ['毛泽东'],
        page_start: 393,
        page_end: 393,
        dates: [{ year: 1938, month: 7, day: 5 }],
        is_range_date: false,
      },
      {
        title: '中共中央为抗战一周年给将委员长及全国抗战将士电',
        authors: ['毛泽东'],
        page_start: 394,
        page_end: 394,
        dates: [{ year: 1938, month: 7, day: 6 }],
        is_range_date: false,
      },
      {
        title: '为抗日阵亡将士和死难同胞的题词',
        authors: ['毛泽东'],
        page_start: 395,
        page_end: 395,
        dates: [{ year: 1938, month: 7, day: 7 }],
        is_range_date: false,
      },
      {
        title: '莫东敌情及对该地区工作的要求',
        authors: ['毛泽东'],
        page_start: 396,
        page_end: 397,
        dates: [{ year: 1938, month: 7, day: 8 }],
        is_range_date: false,
      },
      {
        title: '致西安等处中共负责人电',
        authors: ['毛泽东'],
        page_start: 398,
        page_end: 398,
        dates: [{ year: 1938, month: 7, day: 8 }],
        is_range_date: false,
      },
      {
        title: '在抗大纪念“七一”“七七”及突击运动总结大会上的讲话',
        authors: ['毛泽东'],
        page_start: 399,
        page_end: 399,
        dates: [{ year: 1938, month: 7, day: 9 }],
        is_range_date: false,
      },
      {
        title: '对八路军留守兵团负责干部的讲话',
        authors: ['毛泽东'],
        page_start: 400,
        page_end: 400,
        dates: [{ year: 1938, month: 7, day: 16 }],
        is_range_date: false,
      },
      {
        title: '致朱德、彭德怀等电',
        authors: ['毛泽东'],
        page_start: 401,
        page_end: 401,
        dates: [{ year: 1938, month: 7, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致国际和平大会电',
        authors: ['毛泽东'],
        page_start: 402,
        page_end: 402,
        dates: [{ year: 1938, month: 7, day: 18 }],
        is_range_date: false,
      },
      {
        title: '对苏鲁豫皖边区的工作的指示',
        authors: ['毛泽东'],
        page_start: 403,
        page_end: 403,
        dates: [{ year: 1938, month: 7, day: 22 }],
        is_range_date: false,
      },
      {
        title: '复周恩来电',
        authors: ['毛泽东'],
        page_start: 404,
        page_end: 404,
        dates: [{ year: 1938, month: 7, day: 26 }],
        is_range_date: false,
      },
      {
        title: '和毛华初的谈话',
        authors: ['毛泽东'],
        page_start: 405,
        page_end: 407,
        dates: [{ year: 1938, month: 7 }],
        is_range_date: false,
      },
      {
        title: '为抗大第四期毕业学员题词回',
        authors: ['毛泽东'],
        page_start: 408,
        page_end: 409,
        dates: [{ year: 1938, month: 8, day: 1 }],
        is_range_date: false,
      },
      {
        title: '在抗大四期毕业欢送大会上的讲话',
        authors: ['毛泽东'],
        page_start: 410,
        page_end: 410,
        dates: [{ year: 1938, month: 8, day: 1 }],
        is_range_date: false,
      },
      {
        title: '在抗大第四期毕业证书上题词',
        authors: ['毛泽东'],
        page_start: 411,
        page_end: 413,
        dates: [{ year: 1938, month: 8, day: 1 }],
        is_range_date: false,
      },
      {
        title: '对抗大第四期第一大队、第二大队，第六大队毕业学员的讲话',
        authors: ['毛泽东'],
        page_start: 414,
        page_end: 414,
        dates: [{ year: 1938, month: 8, day: 2 }],
        is_range_date: false,
      },
      {
        title: '复朱德、彭德怀电',
        authors: ['毛泽东'],
        page_start: 415,
        page_end: 415,
        dates: [{ year: 1938, month: 8, day: 3 }],
        is_range_date: false,
      },
      {
        title: '抗大同学毕业出去后怎样工作',
        authors: ['毛泽东'],
        page_start: 416,
        page_end: 416,
        dates: [{ year: 1938, month: 8, day: 5 }],
        is_range_date: false,
      },
      {
        title: '致陈绍禹、凯丰电',
        authors: ['毛泽东'],
        page_start: 417,
        page_end: 417,
        dates: [{ year: 1938, month: 8, day: 6 }],
        is_range_date: false,
      },
      {
        title: '我们在抗战过程中的总方针',
        authors: ['毛泽东'],
        page_start: 418,
        page_end: 418,
        dates: [{ year: 1938, month: 8, day: 6 }],
        is_range_date: false,
      },
      {
        title: '关于目前英南工作的意见',
        authors: ['毛泽东'],
        page_start: 419,
        page_end: 419,
        dates: [{ year: 1938, month: 8, day: 8 }],
        is_range_date: false,
      },
      {
        title: '致陈绍禹、周恩来、博古、凯丰电',
        authors: ['毛泽东'],
        page_start: 420,
        page_end: 420,
        dates: [{ year: 1938, month: 8, day: 10 }],
        is_range_date: false,
      },
      {
        title: '复贺龙、关向应电',
        authors: ['毛泽东'],
        page_start: 421,
        page_end: 421,
        dates: [{ year: 1938, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '八路军第四纵队的工作方针',
        authors: ['毛泽东'],
        page_start: 422,
        page_end: 422,
        dates: [{ year: 1938, month: 8, day: 13 }],
        is_range_date: false,
      },
      {
        title: '复林伯渠电',
        authors: ['毛泽东'],
        page_start: 423,
        page_end: 423,
        dates: [{ year: 1938, month: 8, day: 16 }],
        is_range_date: false,
      },
      {
        title: '边区的货币政策',
        authors: ['毛泽东'],
        page_start: 424,
        page_end: 425,
        dates: [{ year: 1938, month: 8, day: 17 }],
        is_range_date: false,
      },
      {
        title: '和鹿钟麟谈判时应坚持的原则',
        authors: ['毛泽东'],
        page_start: 426,
        page_end: 426,
        dates: [{ year: 1938, month: 8, day: 18 }],
        is_range_date: false,
      },
      {
        title: '对河北工作的指示',
        authors: ['毛泽东'],
        page_start: 427,
        page_end: 427,
        dates: [{ year: 1938, month: 8, day: 20 }],
        is_range_date: false,
      },
      {
        title: '关于英南新政府成立后的工作指示',
        authors: ['毛泽东'],
        page_start: 428,
        page_end: 428,
        dates: [{ year: 1938, month: 8, day: 20 }],
        is_range_date: false,
      },
      {
        title: '在中共中央党校的讲话',
        authors: ['毛泽东'],
        page_start: 429,
        page_end: 429,
        dates: [{ year: 1938, month: 8, day: 22 }],
        is_range_date: false,
      },
      {
        title: '对山西新旧势力的冲突问题的指示',
        authors: ['毛泽东'],
        page_start: 430,
        page_end: 430,
        dates: [{ year: 1938, month: 8, day: 22 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀等电',
        authors: ['毛泽东'],
        page_start: 431,
        page_end: 431,
        dates: [{ year: 1938, month: 8, day: 24 }],
        is_range_date: false,
      },
      {
        title: '对普英像党和八路军的任务的指示',
        authors: ['毛泽东'],
        page_start: 432,
        page_end: 432,
        dates: [{ year: 1938, month: 8, day: 24 }],
        is_range_date: false,
      },
      {
        title: '为欧阳平题词叫',
        authors: ['毛泽东'],
        page_start: 433,
        page_end: 433,
        dates: [{ year: 1938, month: 8 }],
        is_range_date: false,
      },
      {
        title: '为韦统泰题词叫',
        authors: ['毛泽东'],
        page_start: 434,
        page_end: 435,
        dates: [{ year: 1938, month: 8 }],
        is_range_date: false,
      },
      {
        title: '为边区儿童保育院成立题词',
        authors: ['毛泽东'],
        page_start: 436,
        page_end: 436,
        dates: [{ year: 1938, month: 9, day: 5 }],
        is_range_date: false,
      },
      {
        title: '致郭洪涛电',
        authors: ['毛泽东'],
        page_start: 437,
        page_end: 438,
        dates: [{ year: 1938, month: 9, day: 7 }],
        is_range_date: false,
      },
      {
        title: '对张随梧有计划的获取正太路以北地区的对策',
        authors: ['毛泽东'],
        page_start: 439,
        page_end: 439,
        dates: [{ year: 1938, month: 9, day: 7 }],
        is_range_date: false,
      },
      {
        title: '给孔祥熙的信',
        authors: ['毛泽东'],
        page_start: 440,
        page_end: 440,
        dates: [{ year: 1938, month: 9, day: 10 }],
        is_range_date: false,
      },
      {
        title: '翼东形势和使翼东游击队迅速正规化',
        authors: ['毛泽东'],
        page_start: 441,
        page_end: 441,
        dates: [{ year: 1938, month: 9, day: 10 }],
        is_range_date: false,
      },
      {
        title: '程子华率队进击柳林西北地区',
        authors: ['毛泽东'],
        page_start: 442,
        page_end: 443,
        dates: [{ year: 1938, month: 9, day: 11 }],
        is_range_date: false,
      },
      {
        title: '为陕甘宁边区文化协会《文艺突击》杂志“题名',
        authors: ['毛泽东'],
        page_start: 444,
        page_end: 445,
        dates: [{ year: 1938, month: 9, day: 17 }],
        is_range_date: false,
      },
      {
        title: '给前线将士的惠问信',
        authors: ['毛泽东'],
        page_start: 446,
        page_end: 446,
        dates: [{ year: 1938, month: 9, day: 18 }],
        is_range_date: false,
      },
      {
        title: '克服困难创建贺热察根据地',
        authors: ['毛泽东'],
        page_start: 447,
        page_end: 448,
        dates: [{ year: 1938, month: 9, day: 26 }],
        is_range_date: false,
      },
      {
        title: '给将介石的信',
        authors: ['毛泽东'],
        page_start: 449,
        page_end: 450,
        dates: [{ year: 1938, month: 9, day: 29 }],
        is_range_date: false,
      },
      {
        title: '和抗大第三期毕业学员的谈话',
        authors: ['毛泽东'],
        page_start: 451,
        page_end: 451,
        dates: [{ year: 1938, month: 9 }],
        is_range_date: false,
      },
      {
        title: '关于诗歌的指示',
        authors: ['毛泽东'],
        page_start: 452,
        page_end: 452,
        dates: [{ year: 1938, month: 9 }],
        is_range_date: false,
      },
      {
        title: '为吴伯萧题词',
        authors: ['毛泽东'],
        page_start: 453,
        page_end: 453,
        dates: [{ year: 1938, month: 9 }],
        is_range_date: false,
      },
      {
        title: '在翼热边区创造根据地具有战略意义',
        authors: ['毛泽东'],
        page_start: 454,
        page_end: 456,
        dates: [{ year: 1938, month: 10, day: 2 }],
        is_range_date: false,
      },
      {
        title: '各方动员战胜敌人对普察翼边区的围攻',
        authors: ['毛泽东'],
        page_start: 457,
        page_end: 459,
        dates: [{ year: 1938, month: 10, day: 2 }],
        is_range_date: false,
      },
      {
        title: '论新阶段',
        authors: ['毛泽东'],
        page_start: 460,
        page_end: 555,
        dates: [{ year: 1938, month: 10 }],
        is_range_date: false,
      },
    ],
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives8/maoquanji12.pdf',
};
