export default {
  entity: {
    id: 'maoquanji20',
    name: '毛泽东全集第20卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives8/main/maoquanji20.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '论军队生产自给，兼论整风和生产两大运动的重要性',
        authors: ['毛泽东'],
        page_start: 23,
        page_end: 27,
        dates: [{ year: 1945, month: 4, day: 27 }],
        is_range_date: false,
      },
      {
        title: '关于提议将王明等选进“七大”中央委员会的讲话',
        authors: ['毛泽东'],
        page_start: 28,
        page_end: 28,
        dates: [{ year: 1945, month: 4 }],
        is_range_date: false,
      },
      {
        title: '为八路军一二○师三五九旅七一九团烈士纪念碑题词',
        authors: ['毛泽东'],
        page_start: 29,
        page_end: 29,
        dates: [{ year: 1945, month: 5, day: 1 }],
        is_range_date: false,
      },
      {
        title: '为苏联红军攻克柏林给斯大林的贺电',
        authors: ['毛泽东'],
        page_start: 30,
        page_end: 30,
        dates: [{ year: 1945, month: 5, day: 3 }],
        is_range_date: false,
      },
      {
        title: '湘鄂赣边区根据地必须创立',
        authors: ['毛泽东'],
        page_start: 31,
        page_end: 32,
        dates: [{ year: 1945, month: 5, day: 4 }],
        is_range_date: false,
      },
      {
        title: '在中共七大主席团和各代表团主任会议上的讲话',
        authors: ['毛泽东'],
        page_start: 33,
        page_end: 33,
        dates: [{ year: 1945, month: 5, day: 8 }],
        is_range_date: false,
      },
      {
        title: '在中共七大主席团和各代表团主任会议上的讲话',
        authors: ['毛泽东'],
        page_start: 34,
        page_end: 34,
        dates: [{ year: 1945, month: 5, day: 23 }],
        is_range_date: false,
      },
      {
        title: '第七届中央委员会的选举方针叫',
        authors: ['毛泽东'],
        page_start: 35,
        page_end: 52,
        dates: [{ year: 1945, month: 5, day: 24 }],
        is_range_date: false,
      },
      {
        title: '在中共七大主席团和各代表团主任会议上的讲话',
        authors: ['毛泽东'],
        page_start: 53,
        page_end: 53,
        dates: [{ year: 1945, month: 5, day: 27 }],
        is_range_date: false,
      },
      {
        title: '给冈野进的信',
        authors: ['毛泽东'],
        page_start: 54,
        page_end: 55,
        dates: [{ year: 1945, month: 5, day: 28 }],
        is_range_date: false,
      },
      {
        title: '在中国共产党第七次全国代表大会上的结论',
        authors: ['毛泽东'],
        page_start: 56,
        page_end: 100,
        dates: [{ year: 1945, month: 5, day: 31 }],
        is_range_date: false,
      },
      {
        title: '在中共七大主席团和各代表团主任会议上的讲话',
        authors: ['毛泽东'],
        page_start: 101,
        page_end: 101,
        dates: [{ year: 1945, month: 6, day: 2 }],
        is_range_date: false,
      },
      {
        title: '在准备南下支队干部会议上的讲话',
        authors: ['毛泽东'],
        page_start: 102,
        page_end: 102,
        dates: [{ year: 1945, month: 6, day: 7 }],
        is_range_date: false,
      },
      {
        title: '复罗荣柜电',
        authors: ['毛泽东'],
        page_start: 103,
        page_end: 103,
        dates: [{ year: 1945, month: 6, day: 9 }],
        is_range_date: false,
      },
      {
        title: '致邓小平电',
        authors: ['毛泽东'],
        page_start: 104,
        page_end: 104,
        dates: [{ year: 1945, month: 6, day: 10 }],
        is_range_date: false,
      },
      {
        title: '关于第七届候补中央委员选举问题',
        authors: ['毛泽东'],
        page_start: 105,
        page_end: 114,
        dates: [{ year: 1945, month: 6, day: 10 }],
        is_range_date: false,
      },
      {
        title: '惠公移山',
        authors: ['毛泽东'],
        page_start: 115,
        page_end: 119,
        dates: [{ year: 1945, month: 6, day: 11 }],
        is_range_date: false,
      },
      {
        title: '中共不出席四届一次参政会',
        authors: ['毛泽东'],
        page_start: 120,
        page_end: 121,
        dates: [{ year: 1945, month: 6, day: 15 }],
        is_range_date: false,
      },
      {
        title: '王震王首道部的行动方针',
        authors: ['毛泽东'],
        page_start: 122,
        page_end: 124,
        dates: [{ year: 1945, month: 6, day: 15 }],
        is_range_date: false,
      },
      {
        title: '在中共七大主席团和各代表团主任会议上的讲话',
        authors: ['毛泽东'],
        page_start: 125,
        page_end: 125,
        dates: [{ year: 1945, month: 6, day: 15 }],
        is_range_date: false,
      },
      {
        title: '在中国革命死难烈士追恒大会上的演说',
        authors: ['毛泽东'],
        page_start: 126,
        page_end: 133,
        dates: [{ year: 1945, month: 6, day: 17 }],
        is_range_date: false,
      },
      {
        title: '在中国革命死难烈士追恒大会上的惊词',
        authors: ['毛泽东'],
        page_start: 134,
        page_end: 135,
        dates: [{ year: 1945, month: 6, day: 17 }],
        is_range_date: false,
      },
      {
        title: '为中国革命死难烈士题写挖词',
        authors: ['毛泽东'],
        page_start: 136,
        page_end: 136,
        dates: [{ year: 1945, month: 6, day: 17 }],
        is_range_date: false,
      },
      {
        title: '抚抗日烈士联',
        authors: ['毛泽东'],
        page_start: 137,
        page_end: 137,
        dates: [{ year: 1945, month: 6, day: 17 }],
        is_range_date: false,
      },
      {
        title: '欢迎七参政员来延安商谈国是的复电',
        authors: ['毛泽东'],
        page_start: 138,
        page_end: 138,
        dates: [{ year: 1945, month: 6, day: 18 }],
        is_range_date: false,
      },
      {
        title: '豫中、豫东日军占领区较利于建立根据地',
        authors: ['毛泽东'],
        page_start: 139,
        page_end: 140,
        dates: [{ year: 1945, month: 6, day: 18 }],
        is_range_date: false,
      },
      {
        title: '致王若飞电',
        authors: ['毛泽东'],
        page_start: 141,
        page_end: 141,
        dates: [{ year: 1945, month: 6, day: 18 }],
        is_range_date: false,
      },
      {
        title: '在中共七届一中全会第一次会议上的讲话',
        authors: ['毛泽东'],
        page_start: 142,
        page_end: 142,
        dates: [{ year: 1945, month: 6, day: 19 }],
        is_range_date: false,
      },
      {
        title: '南下部队"应依据五岭山脉建立根据地',
        authors: ['毛泽东'],
        page_start: 143,
        page_end: 145,
        dates: [{ year: 1945, month: 6, day: 24 }],
        is_range_date: false,
      },
      {
        title: '给各级党部的通知',
        authors: ['毛泽东'],
        page_start: 146,
        page_end: 146,
        dates: [{ year: 1945, month: 6, day: 26 }],
        is_range_date: false,
      },
      {
        title: '抚李公朴、闻一多联',
        authors: ['毛泽东'],
        page_start: 147,
        page_end: 147,
        dates: [{ year: 1945, month: 6, day: 27 }],
        is_range_date: false,
      },
      {
        title: '复沈钓儒、陶行知、张申府电',
        authors: ['毛泽东'],
        page_start: 148,
        page_end: 148,
        dates: [{ year: 1945, month: 6, day: 30 }],
        is_range_date: false,
      },
      {
        title: '在延安各界欢迎全国感劳总会北路感劳团晚会上的讲话',
        authors: ['毛泽东'],
        page_start: 149,
        page_end: 150,
        dates: [{ year: 1945 }],
        is_range_date: false,
      },
      {
        title: '和褚辅成等六参政员的谈话',
        authors: ['毛泽东'],
        page_start: 151,
        page_end: 151,
        dates: [{ year: 1945, month: 7, day: 2 }],
        is_range_date: false,
      },
      {
        title: '和国民参政会参政员的会谈记录',
        authors: ['毛泽东'],
        page_start: 152,
        page_end: 158,
        dates: [{ year: 1945, month: 7, day: 4 }],
        is_range_date: false,
      },
      {
        title: '和黄炎培谈跳出周期律',
        authors: ['毛泽东'],
        page_start: 159,
        page_end: 160,
        dates: [{ year: 1945, month: 7, day: 4 }],
        is_range_date: false,
      },
      {
        title: '给傅斯年的短笔和条幅',
        authors: ['毛泽东'],
        page_start: 161,
        page_end: 162,
        dates: [{ year: 1945, month: 7, day: 5 }],
        is_range_date: false,
      },
      {
        title: '评蒋介石七七演说',
        authors: ['毛泽东'],
        page_start: 163,
        page_end: 165,
        dates: [{ year: 1945, month: 7, day: 8 }],
        is_range_date: false,
      },
      {
        title: '赫尔利和蒋介石的双簧已经破产',
        authors: ['毛泽东'],
        page_start: 166,
        page_end: 169,
        dates: [{ year: 1945, month: 7, day: 10 }],
        is_range_date: false,
      },
      {
        title: '评赫尔利政策的危险',
        authors: ['毛泽东'],
        page_start: 170,
        page_end: 171,
        dates: [{ year: 1945, month: 7, day: 12 }],
        is_range_date: false,
      },
      {
        title: '开群郑州许昌等地甚为必要',
        authors: ['毛泽东'],
        page_start: 172,
        page_end: 172,
        dates: [{ year: 1945, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '人豫部队的作战方针',
        authors: ['毛泽东'],
        page_start: 173,
        page_end: 175,
        dates: [{ year: 1945, month: 7, day: 15 }],
        is_range_date: false,
      },
      {
        title: '在《新华社记者再评赫尔利政策》上加写的一段话',
        authors: ['毛泽东'],
        page_start: 176,
        page_end: 176,
        dates: [{ year: 1945, month: 7, day: 19 }],
        is_range_date: false,
      },
      {
        title: '争取年底到达五岭与王震部会合',
        authors: ['毛泽东'],
        page_start: 177,
        page_end: 178,
        dates: [{ year: 1945, month: 7, day: 22 }],
        is_range_date: false,
      },
      {
        title: '争取时间在粤北湘南创立五岭根据地',
        authors: ['毛泽东'],
        page_start: 179,
        page_end: 180,
        dates: [{ year: 1945, month: 7, day: 22 }],
        is_range_date: false,
      },
      {
        title: '评国民参政会关于国民大会的决议',
        authors: ['毛泽东'],
        page_start: 181,
        page_end: 183,
        dates: [{ year: 1945, month: 7, day: 22 }],
        is_range_date: false,
      },
      {
        title: '争取目前时间创立五岭根据地',
        authors: ['毛泽东'],
        page_start: 184,
        page_end: 184,
        dates: [{ year: 1945, month: 7, day: 22 }],
        is_range_date: false,
      },
      {
        title: '争取年底到达五岭与二王会合',
        authors: ['毛泽东'],
        page_start: 185,
        page_end: 185,
        dates: [{ year: 1945, month: 7, day: 22 }],
        is_range_date: false,
      },
      {
        title: '关于扩大反内战宣传及建立云、贵、川农村据点的指示',
        authors: ['毛泽东'],
        page_start: 186,
        page_end: 186,
        dates: [{ year: 1945, month: 7, day: 22 }],
        is_range_date: false,
      },
      {
        title: '在中共中央书记处会议上的讲话',
        authors: ['毛泽东'],
        page_start: 187,
        page_end: 187,
        dates: [{ year: 1945, month: 7, day: 23 }],
        is_range_date: false,
      },
      {
        title: '爷台山战事扩大',
        authors: ['毛泽东'],
        page_start: 188,
        page_end: 189,
        dates: [{ year: 1945, month: 7, day: 25 }],
        is_range_date: false,
      },
      {
        title: '坚决将人侵之胡军打出去',
        authors: ['毛泽东'],
        page_start: 190,
        page_end: 190,
        dates: [{ year: 1945, month: 7, day: 27 }],
        is_range_date: false,
      },
      {
        title: '致福斯特电',
        authors: ['毛泽东'],
        page_start: 191,
        page_end: 192,
        dates: [{ year: 1945, month: 7, day: 29 }],
        is_range_date: false,
      },
      {
        title: '关于批评美国对华政策的电报',
        authors: ['毛泽东'],
        page_start: 193,
        page_end: 193,
        dates: [{ year: 1945, month: 7, day: 30 }],
        is_range_date: false,
      },
      {
        title: '批转太行区党委关于检讨统一领导问题的报告',
        authors: ['毛泽东'],
        page_start: 194,
        page_end: 194,
        dates: [{ year: 1945, month: 7, day: 30 }],
        is_range_date: false,
      },
      {
        title: '胡军侵占边区问题及我军对策叫',
        authors: ['毛泽东'],
        page_start: 195,
        page_end: 195,
        dates: [{ year: 1945, month: 7, day: 30 }],
        is_range_date: false,
      },
      {
        title: '对留守兵团工作的分析',
        authors: ['毛泽东'],
        page_start: 196,
        page_end: 197,
        dates: [{ year: 1945, month: 7 }],
        is_range_date: false,
      },
      {
        title: '准备应付必然到来的内战局面',
        authors: ['毛泽东'],
        page_start: 198,
        page_end: 199,
        dates: [{ year: 1945, month: 8, day: 4 }],
        is_range_date: false,
      },
      {
        title: '准备与王震王首道部会合开创湘尊边根据地',
        authors: ['毛泽东'],
        page_start: 200,
        page_end: 203,
        dates: [{ year: 1945, month: 8, day: 4 }],
        is_range_date: false,
      },
      {
        title: '复王震、王首道电',
        authors: ['毛泽东'],
        page_start: 204,
        page_end: 204,
        dates: [{ year: 1945, month: 8, day: 4 }],
        is_range_date: false,
      },
      {
        title: '中央关于造成控制山东全局的条件给山东分局的指示',
        authors: ['毛泽东'],
        page_start: 205,
        page_end: 206,
        dates: [{ year: 1945, month: 8, day: 6 }],
        is_range_date: false,
      },
      {
        title: '对日寇的最后一战',
        authors: ['毛泽东'],
        page_start: 207,
        page_end: 211,
        dates: [{ year: 1945, month: 8, day: 9 }],
        is_range_date: false,
      },
      {
        title: '致斯大林电',
        authors: ['毛泽东'],
        page_start: 212,
        page_end: 212,
        dates: [{ year: 1945, month: 8, day: 9 }],
        is_range_date: false,
      },
      {
        title: '在中共七届一中全会第二次会议上的讲话',
        authors: ['毛泽东'],
        page_start: 213,
        page_end: 214,
        dates: [{ year: 1945, month: 8, day: 9 }],
        is_range_date: false,
      },
      {
        title: '争取一切条件准备对付内战',
        authors: ['毛泽东'],
        page_start: 215,
        page_end: 215,
        dates: [{ year: 1945, month: 8, day: 10 }],
        is_range_date: false,
      },
      {
        title: '关于日本投降后党的任务',
        authors: ['毛泽东'],
        page_start: 216,
        page_end: 218,
        dates: [{ year: 1945, month: 8, day: 11 }],
        is_range_date: false,
      },
      {
        title: '坚决创造根据地准备对付内战',
        authors: ['毛泽东'],
        page_start: 219,
        page_end: 219,
        dates: [{ year: 1945, month: 8, day: 11 }],
        is_range_date: false,
      },
      {
        title: '华中准备对付内战的部署',
        authors: ['毛泽东'],
        page_start: 220,
        page_end: 221,
        dates: [{ year: 1945, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '必须力争占领之交通线及沿线城市叫',
        authors: ['毛泽东'],
        page_start: 222,
        page_end: 223,
        dates: [{ year: 1945, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '齐天傅作义东进部队迎接外蒙军及红军',
        authors: ['毛泽东'],
        page_start: 224,
        page_end: 224,
        dates: [{ year: 1945, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '速即完成出发准备，待命开往东北',
        authors: ['毛泽东'],
        page_start: 225,
        page_end: 225,
        dates: [{ year: 1945, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致郑位三、李先念及河南区党委电',
        authors: ['毛泽东'],
        page_start: 226,
        page_end: 226,
        dates: [{ year: 1945, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '抗日战争胜利后的时局和我们的方针叫',
        authors: ['毛泽东'],
        page_start: 227,
        page_end: 241,
        dates: [{ year: 1945, month: 8, day: 13 }],
        is_range_date: false,
      },
      {
        title: '将介石在挑动内战',
        authors: ['毛泽东'],
        page_start: 242,
        page_end: 245,
        dates: [{ year: 1945, month: 8, day: 13 }],
        is_range_date: false,
      },
      {
        title: '在战役上须占绝对优势不可浪打',
        authors: ['毛泽东'],
        page_start: 246,
        page_end: 246,
        dates: [{ year: 1945, month: 8, day: 13 }],
        is_range_date: false,
      },
      {
        title: '河南部队目前的任务',
        authors: ['毛泽东'],
        page_start: 247,
        page_end: 248,
        dates: [{ year: 1945, month: 8, day: 13 }],
        is_range_date: false,
      },
      {
        title: '第十八集团军总司令给将介石的两个电报',
        authors: ['毛泽东'],
        page_start: 249,
        page_end: 261,
        dates: [{ year: 1945, month: 8 }],
        is_range_date: false,
      },
      {
        title: '广占乡村不打大城市',
        authors: ['毛泽东'],
        page_start: 262,
        page_end: 263,
        dates: [{ year: 1945, month: 8, day: 15 }],
        is_range_date: false,
      },
      {
        title: '关于警察问题致华中局电',
        authors: ['毛泽东'],
        page_start: 264,
        page_end: 267,
        dates: [{ year: 1945, month: 8, day: 15 }],
        is_range_date: false,
      },
      {
        title: '评蒋介石发言人谈话',
        authors: ['毛泽东'],
        page_start: 268,
        page_end: 271,
        dates: [{ year: 1945, month: 8, day: 16 }],
        is_range_date: false,
      },
      {
        title: '华中部队当前任务和作战方法',
        authors: ['毛泽东'],
        page_start: 272,
        page_end: 273,
        dates: [{ year: 1945, month: 8, day: 16 }],
        is_range_date: false,
      },
      {
        title: '包围大同和解决太原问题',
        authors: ['毛泽东'],
        page_start: 274,
        page_end: 274,
        dates: [{ year: 1945, month: 8, day: 16 }],
        is_range_date: false,
      },
      {
        title: '就去重庆会见问题复蒋介石电',
        authors: ['毛泽东'],
        page_start: 275,
        page_end: 280,
        dates: [{ year: 1945, month: 8, day: 16 }],
        is_range_date: false,
      },
      {
        title: '学会机动作战及分散游击，避免无把握的硬仗',
        authors: ['毛泽东'],
        page_start: 281,
        page_end: 281,
        dates: [{ year: 1945, month: 8, day: 18 }],
        is_range_date: false,
      },
      {
        title: '东北干部凡能调动者尽可能调至万毅部',
        authors: ['毛泽东'],
        page_start: 282,
        page_end: 282,
        dates: [{ year: 1945, month: 8, day: 18 }],
        is_range_date: false,
      },
      {
        title: '山西国民党军部署及我军作战任务',
        authors: ['毛泽东'],
        page_start: 283,
        page_end: 284,
        dates: [{ year: 1945, month: 8, day: 19 }],
        is_range_date: false,
      },
      {
        title: '抽九个团赴东三省',
        authors: ['毛泽东'],
        page_start: 285,
        page_end: 286,
        dates: [{ year: 1945, month: 8, day: 20 }],
        is_range_date: false,
      },
      {
        title: '彻底执行上海起义的方针',
        authors: ['毛泽东'],
        page_start: 287,
        page_end: 287,
        dates: [{ year: 1945, month: 8, day: 20 }],
        is_range_date: false,
      },
      {
        title: '动员城内人民起义配合我军夺取城市',
        authors: ['毛泽东'],
        page_start: 288,
        page_end: 288,
        dates: [{ year: 1945, month: 8, day: 20 }],
        is_range_date: false,
      },
      {
        title: '改变上海起义的方针',
        authors: ['毛泽东'],
        page_start: 289,
        page_end: 289,
        dates: [{ year: 1945, month: 8, day: 21 }],
        is_range_date: false,
      },
      {
        title:
          '审改中共中央和中央军委关于改变占领大城市方针的指示稿时加写的一段话',
        authors: ['毛泽东'],
        page_start: 290,
        page_end: 290,
        dates: [{ year: 1945, month: 8, day: 22 }],
        is_range_date: false,
      },
      {
        title: '抗日战争胜利后的新形势和新任务',
        authors: ['毛泽东'],
        page_start: 291,
        page_end: 297,
        dates: [{ year: 1945, month: 8, day: 23 }],
        is_range_date: false,
      },
      {
        title: '目前党的方针及新四军的工作部署',
        authors: ['毛泽东'],
        page_start: 298,
        page_end: 299,
        dates: [{ year: 1945, month: 8, day: 24 }],
        is_range_date: false,
      },
      {
        title: '力求占领许多中小城市',
        authors: ['毛泽东'],
        page_start: 300,
        page_end: 300,
        dates: [{ year: 1945, month: 8, day: 25 }],
        is_range_date: false,
      },
      {
        title: '中国共产党中央委员会对目前时局宣言',
        authors: ['毛泽东'],
        page_start: 301,
        page_end: 303,
        dates: [{ year: 1945, month: 8, day: 25 }],
        is_range_date: false,
      },
      {
        title: '复王震、王首道电',
        authors: ['毛泽东'],
        page_start: 304,
        page_end: 304,
        dates: [{ year: 1945, month: 8, day: 25 }],
        is_range_date: false,
      },
      {
        title: '复魏德迈电',
        authors: ['毛泽东'],
        page_start: 305,
        page_end: 305,
        dates: [{ year: 1945, month: 8, day: 25 }],
        is_range_date: false,
      },
      {
        title: '和刘伯承、邓小平的谈话',
        authors: ['毛泽东'],
        page_start: 306,
        page_end: 307,
        dates: [{ year: 1945, month: 8, day: 25 }],
        is_range_date: false,
      },
      {
        title: '站在自卫立场坚决反击国民觉进攻',
        authors: ['毛泽东'],
        page_start: 308,
        page_end: 308,
        dates: [{ year: 1945, month: 8, day: 26 }],
        is_range_date: false,
      },
      {
        title: '赴重庆谈判前在政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 309,
        page_end: 311,
        dates: [{ year: 1945, month: 8, day: 26 }],
        is_range_date: false,
      },
      {
        title: '中共中央关于同国民觉进行和平谈判的通知',
        authors: ['毛泽东'],
        page_start: 312,
        page_end: 315,
        dates: [{ year: 1945, month: 8, day: 26 }],
        is_range_date: false,
      },
      {
        title: '致林枫等电',
        authors: ['毛泽东'],
        page_start: 316,
        page_end: 316,
        dates: [{ year: 1945, month: 8, day: 26 }],
        is_range_date: false,
      },
      {
        title: '毛泽东赴重庆谈判期间由刘少奇代理中共中央主席职务',
        authors: ['毛泽东'],
        page_start: 317,
        page_end: 332,
        dates: [{ year: 1945, month: 8, day: 27 }],
        is_range_date: false,
      },
      {
        title: '在重庆机场发表的谈话',
        authors: ['毛泽东'],
        page_start: 333,
        page_end: 353,
        dates: [{ year: 1945, month: 8, day: 28 }],
        is_range_date: false,
      },
      {
        title: '在重庆第十八集团军办事处的谈话',
        authors: ['毛泽东'],
        page_start: 354,
        page_end: 362,
        dates: [{ year: 1945, month: 8, day: 29 }],
        is_range_date: false,
      },
      {
        title: '和国民党谈判的十一条意见',
        authors: ['毛泽东'],
        page_start: 363,
        page_end: 365,
        dates: [{ year: 1945, month: 8, day: 30 }],
        is_range_date: false,
      },
      {
        title: '对国共两党谈判提出的八项原则性意见',
        authors: ['毛泽东'],
        page_start: 366,
        page_end: 382,
        dates: [{ year: 1945, month: 9, day: 2 }],
        is_range_date: false,
      },
      {
        title: '为民主人士题词',
        authors: ['毛泽东'],
        page_start: 383,
        page_end: 383,
        dates: [{ year: 1945, month: 9, day: 2 }],
        is_range_date: false,
      },
      {
        title: '为庆祝抗战胜利题词',
        authors: ['毛泽东'],
        page_start: 384,
        page_end: 385,
        dates: [{ year: 1945, month: 9, day: 2 }],
        is_range_date: false,
      },
      {
        title: '和大公报记者的谈话',
        authors: ['毛泽东'],
        page_start: 386,
        page_end: 386,
        dates: [{ year: 1945, month: 9, day: 5 }],
        is_range_date: false,
      },
      {
        title: '为中学生卢国琦题词',
        authors: ['毛泽东'],
        page_start: 387,
        page_end: 388,
        dates: [{ year: 1945, month: 9, day: 6 }],
        is_range_date: false,
      },
      {
        title: '在重庆的公开声明',
        authors: ['毛泽东'],
        page_start: 389,
        page_end: 389,
        dates: [{ year: 1945, month: 9, day: 13 }],
        is_range_date: false,
      },
      {
        title: '尽快派人到上海等地办报',
        authors: ['毛泽东'],
        page_start: 390,
        page_end: 391,
        dates: [{ year: 1945, month: 9, day: 14 }],
        is_range_date: false,
      },
      {
        title: '复中共中央电',
        authors: ['毛泽东'],
        page_start: 392,
        page_end: 392,
        dates: [{ year: 1945, month: 9, day: 15 }],
        is_range_date: false,
      },
      {
        title: '在参政会茶会上的演说',
        authors: ['毛泽东'],
        page_start: 393,
        page_end: 393,
        dates: [{ year: 1945, month: 9, day: 18 }],
        is_range_date: false,
      },
      {
        title: '复中共中央电',
        authors: ['毛泽东'],
        page_start: 394,
        page_end: 394,
        dates: [{ year: 1945, month: 9, day: 19 }],
        is_range_date: false,
      },
      {
        title: '为《大公报》题词',
        authors: ['毛泽东'],
        page_start: 395,
        page_end: 395,
        dates: [{ year: 1945, month: 9, day: 20 }],
        is_range_date: false,
      },
      {
        title: '为徐退题词',
        authors: ['毛泽东'],
        page_start: 396,
        page_end: 397,
        dates: [{ year: 1945, month: 9, day: 22 }],
        is_range_date: false,
      },
      {
        title: '答路透社记者甘贝尔间',
        authors: ['毛泽东'],
        page_start: 398,
        page_end: 404,
        dates: [{ year: 1945, month: 9, day: 27 }],
        is_range_date: false,
      },
      {
        title: '中国只能走和平一条路',
        authors: ['毛泽东'],
        page_start: 405,
        page_end: 406,
        dates: [{ year: 1945, month: 10, day: 8 }],
        is_range_date: false,
      },
      {
        title: '七律·重庆谈判',
        authors: ['毛泽东'],
        page_start: 407,
        page_end: 421,
        dates: [{ year: 1945 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 422,
        page_end: 423,
        dates: [{ year: 1945, month: 10, day: 11 }],
        is_range_date: false,
      },
      {
        title: '《双十协定》公布后应注意的问题',
        authors: ['毛泽东'],
        page_start: 424,
        page_end: 426,
        dates: [{ year: 1945, month: 10, day: 12 }],
        is_range_date: false,
      },
      {
        title: '关于退带国民党军北进致刘伯承、邓小平电',
        authors: ['毛泽东'],
        page_start: 427,
        page_end: 428,
        dates: [{ year: 1945, month: 10, day: 12 }],
        is_range_date: false,
      },
      {
        title: '夺取平缓战役“的胜利意义重大',
        authors: ['毛泽东'],
        page_start: 429,
        page_end: 431,
        dates: [{ year: 1945, month: 10, day: 16 }],
        is_range_date: false,
      },
      {
        title: '致刘伯承、邓小平等电',
        authors: ['毛泽东'],
        page_start: 432,
        page_end: 432,
        dates: [{ year: 1945, month: 10, day: 16 }],
        is_range_date: false,
      },
      {
        title: '东北应坚决阻止蒋军登陆',
        authors: ['毛泽东'],
        page_start: 433,
        page_end: 433,
        dates: [{ year: 1945, month: 10, day: 16 }],
        is_range_date: false,
      },
      {
        title: '致景荣臻电',
        authors: ['毛泽东'],
        page_start: 434,
        page_end: 434,
        dates: [{ year: 1945, month: 10, day: 16 }],
        is_range_date: false,
      },
      {
        title: '关于重庆谈判',
        authors: ['毛泽东'],
        page_start: 435,
        page_end: 444,
        dates: [{ year: 1945, month: 10, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致王震电',
        authors: ['毛泽东'],
        page_start: 445,
        page_end: 445,
        dates: [{ year: 1945, month: 10, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致各中央局、分局及各军区电',
        authors: ['毛泽东'],
        page_start: 446,
        page_end: 451,
        dates: [{ year: 1945, month: 10, day: 17 }],
        is_range_date: false,
      },
      {
        title: '给续范亭的信',
        authors: ['毛泽东'],
        page_start: 452,
        page_end: 452,
        dates: [{ year: 1945, month: 10, day: 18 }],
        is_range_date: false,
      },
      {
        title: '应抽调地方军补充野战军',
        authors: ['毛泽东'],
        page_start: 453,
        page_end: 453,
        dates: [{ year: 1945, month: 10, day: 19 }],
        is_range_date: false,
      },
      {
        title: '日前东北发展方针',
        authors: ['毛泽东'],
        page_start: 454,
        page_end: 454,
        dates: [{ year: 1945, month: 10, day: 19 }],
        is_range_date: false,
      },
      {
        title: '组织一支野战军进行津浦战役山',
        authors: ['毛泽东'],
        page_start: 455,
        page_end: 456,
        dates: [{ year: 1945, month: 10, day: 19 }],
        is_range_date: false,
      },
      {
        title: '致陈赛等电',
        authors: ['毛泽东'],
        page_start: 457,
        page_end: 457,
        dates: [{ year: 1945, month: 10, day: 19 }],
        is_range_date: false,
      },
      {
        title: '自前时局及今后六个月的任务',
        authors: ['毛泽东'],
        page_start: 458,
        page_end: 460,
        dates: [{ year: 1945, month: 10, day: 20 }],
        is_range_date: false,
      },
      {
        title: '关于山东华中作战问题的指示',
        authors: ['毛泽东'],
        page_start: 461,
        page_end: 462,
        dates: [{ year: 1945, month: 10, day: 22 }],
        is_range_date: false,
      },
      {
        title: '集中力量在桐柏山区创造战场',
        authors: ['毛泽东'],
        page_start: 463,
        page_end: 464,
        dates: [{ year: 1945, month: 10, day: 22 }],
        is_range_date: false,
      },
      {
        title: '归缓包头大同等地必须占领',
        authors: ['毛泽东'],
        page_start: 465,
        page_end: 465,
        dates: [{ year: 1945, month: 10, day: 22 }],
        is_range_date: false,
      },
      {
        title: '组织普察英第二野战军歼灭向承德进攻之敌',
        authors: ['毛泽东'],
        page_start: 466,
        page_end: 467,
        dates: [{ year: 1945, month: 10, day: 23 }],
        is_range_date: false,
      },
      {
        title: '孤立傅作义部于集宁后再齐灭之',
        authors: ['毛泽东'],
        page_start: 468,
        page_end: 468,
        dates: [{ year: 1945, month: 10, day: 24 }],
        is_range_date: false,
      },
      {
        title: '攻占打成一片的几个城市以利野战',
        authors: ['毛泽东'],
        page_start: 469,
        page_end: 469,
        dates: [{ year: 1945, month: 10, day: 24 }],
        is_range_date: false,
      },
      {
        title: '东北我军力量的布置',
        authors: ['毛泽东'],
        page_start: 470,
        page_end: 470,
        dates: [{ year: 1945, month: 10, day: 24 }],
        is_range_date: false,
      },
      {
        title: '致郑位三、李先念电叫',
        authors: ['毛泽东'],
        page_start: 471,
        page_end: 471,
        dates: [{ year: 1945, month: 10, day: 24 }],
        is_range_date: false,
      },
      {
        title: '迅速组织热河野战军和费东纵队',
        authors: ['毛泽东'],
        page_start: 472,
        page_end: 473,
        dates: [{ year: 1945, month: 10, day: 25 }],
        is_range_date: false,
      },
      {
        title: '在抗大七分校的讲话',
        authors: ['毛泽东'],
        page_start: 474,
        page_end: 477,
        dates: [{ year: 1945, month: 10, day: 25 }],
        is_range_date: false,
      },
      {
        title: '尽快抽调部队海运东北',
        authors: ['毛泽东'],
        page_start: 478,
        page_end: 479,
        dates: [{ year: 1945, month: 10, day: 25 }],
        is_range_date: false,
      },
      {
        title: '程子华速去热河准备反击将军进攻承德',
        authors: ['毛泽东'],
        page_start: 480,
        page_end: 481,
        dates: [{ year: 1945, month: 10, day: 27 }],
        is_range_date: false,
      },
      {
        title: '准备集中全力齐灭傅作义部夺取归缓',
        authors: ['毛泽东'],
        page_start: 482,
        page_end: 482,
        dates: [{ year: 1945, month: 10, day: 27 }],
        is_range_date: false,
      },
      {
        title: '致东北局电',
        authors: ['毛泽东'],
        page_start: 483,
        page_end: 483,
        dates: [{ year: 1945, month: 10, day: 28 }],
        is_range_date: false,
      },
      {
        title: '和国民党谈判的补充意见',
        authors: ['毛泽东'],
        page_start: 484,
        page_end: 485,
        dates: [{ year: 1945, month: 10, day: 29 }],
        is_range_date: false,
      },
      {
        title: '普察冀第二野战军十一月份必须完成三项任务',
        authors: ['毛泽东'],
        page_start: 486,
        page_end: 487,
        dates: [{ year: 1945, month: 10, day: 30 }],
        is_range_date: false,
      },
      {
        title: '赵尔陆即率部兼程至临城地区叫',
        authors: ['毛泽东'],
        page_start: 488,
        page_end: 488,
        dates: [{ year: 1945, month: 10, day: 30 }],
        is_range_date: false,
      },
      {
        title: '致热河分委等电',
        authors: ['毛泽东'],
        page_start: 489,
        page_end: 489,
        dates: [{ year: 1945, month: 10, day: 30 }],
        is_range_date: false,
      },
      {
        title: '集中优势兵力各个歼灭当面之敌然后再打援敌',
        authors: ['毛泽东'],
        page_start: 490,
        page_end: 491,
        dates: [{ year: 1945, month: 10, day: 30 }],
        is_range_date: false,
      },
      {
        title: '准备钳制王仲廉可能北援之部队',
        authors: ['毛泽东'],
        page_start: 492,
        page_end: 492,
        dates: [{ year: 1945, month: 10, day: 30 }],
        is_range_date: false,
      },
      {
        title: '轩天霍守义陈大庆李品仙部即是接助华北东北',
        authors: ['毛泽东'],
        page_start: 493,
        page_end: 494,
        dates: [{ year: 1945, month: 10, day: 30 }],
        is_range_date: false,
      },
      {
        title: '准备在邹、滕地区打大齐灭战',
        authors: ['毛泽东'],
        page_start: 495,
        page_end: 496,
        dates: [{ year: 1945, month: 10, day: 31 }],
        is_range_date: false,
      },
      {
        title: '集中最大兵力歼灭当面之敌',
        authors: ['毛泽东'],
        page_start: 497,
        page_end: 497,
        dates: [{ year: 1945, month: 10, day: 31 }],
        is_range_date: false,
      },
      {
        title: '致赵尔陆电',
        authors: ['毛泽东'],
        page_start: 498,
        page_end: 498,
        dates: [{ year: 1945, month: 10, day: 31 }],
        is_range_date: false,
      },
      {
        title: '抵抗由营口葫芦岛登陆之将军道其缓进',
        authors: ['毛泽东'],
        page_start: 499,
        page_end: 500,
        dates: [{ year: 1945, month: 10, day: 31 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 501,
        page_end: 501,
        dates: [{ year: 1945, month: 10, day: 31 }],
        is_range_date: false,
      },
      {
        title: '致东北局电',
        authors: ['毛泽东'],
        page_start: 502,
        page_end: 502,
        dates: [{ year: 1945, month: 10, day: 31 }],
        is_range_date: false,
      },
      {
        title: '为陕甘宁晋绥五省联防军政治部宣传队题词',
        authors: ['毛泽东'],
        page_start: 503,
        page_end: 503,
        dates: [{ year: 1945, month: 10 }],
        is_range_date: false,
      },
      {
        title: '为李少石题换词',
        authors: ['毛泽东'],
        page_start: 504,
        page_end: 505,
        dates: [{ year: 1945, month: 10 }],
        is_range_date: false,
      },
      {
        title: '抗范旭东先生联',
        authors: ['毛泽东'],
        page_start: 506,
        page_end: 506,
        dates: [{ year: 1945, month: 10 }],
        is_range_date: false,
      },
      {
        title: '书鲁迅《自喇》摘句',
        authors: ['毛泽东'],
        page_start: 507,
        page_end: 508,
        dates: [{ year: 1945, month: 10 }],
        is_range_date: false,
      },
      {
        title: '为柳亚子的诗尹瘦石的画联展题词',
        authors: ['毛泽东'],
        page_start: 509,
        page_end: 510,
        dates: [{ year: 1945, month: 10 }],
        is_range_date: false,
      },
      {
        title: '十一月作战部署',
        authors: ['毛泽东'],
        page_start: 511,
        page_end: 513,
        dates: [{ year: 1945, month: 11, day: 1 }],
        is_range_date: false,
      },
      {
        title: '英中地区动员一切力量破坏铁路',
        authors: ['毛泽东'],
        page_start: 514,
        page_end: 514,
        dates: [{ year: 1945, month: 11, day: 1 }],
        is_range_date: false,
      },
      {
        title: '在山海关锦州地区坚决齐灭北进之敌',
        authors: ['毛泽东'],
        page_start: 515,
        page_end: 516,
        dates: [{ year: 1945, month: 11, day: 1 }],
        is_range_date: false,
      },
    ],
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives8/maoquanji20.pdf',
};
