export default {
  entity: {
    id: 'maoquanji44',
    name: '毛泽东全集第44卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives0/main/mao-quanji/maoquanji44.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
    articles: [
      {
        page_start: 26,
        page_end: 27,
        title: '对王海容《我的经验》一文的修改和批语',
        dates: [{ year: 1960, month: 10, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 28,
        page_end: 30,
        title: '转发山西省委关于农村劳动力问题的报告的批语',
        dates: [{ year: 1960, month: 10, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 31,
        page_end: 31,
        title: '对公安部党组关于第二批特救和减刑战犯名单的请示报告的批语',
        dates: [{ year: 1960, month: 10, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 33,
        page_end: 43,
        title: '和斯诺的谈话',
        dates: [{ year: 1960, month: 10, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 44,
        page_end: 44,
        title: '对中共中央答谢古巴人民社会党的电报稿的修改',
        dates: [{ year: 1960, month: 10, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 45,
        page_end: 45,
        title: '关于为黄绍、刘王立明摘掉右派帽子的批语',
        dates: [{ year: 1960, month: 10, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 46,
        page_end: 46,
        title: '对中组部、中监委关于信阳问题的调查材料的批语',
        dates: [{ year: 1960, month: 10, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 47,
        page_end: 47,
        title: '印发胡乔木关于推广小球藻等粮食代用品生产的建议的批语',
        dates: [{ year: 1960, month: 10, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 48,
        page_end: 48,
        title: '印发河北省关于农村口粮标准、办好食堂和分配等问题的措施的批语',
        dates: [{ year: 1960, month: 10, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 49,
        page_end: 51,
        title: '对《中国人民革命胜利经验的基本总结》一文的批语和修改',
        dates: [
          { year: 1960, month: 10, day: 28 },
          { year: 1960, month: 10, day: 29 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 52,
        page_end: 54,
        title: '中央转发安徽省委关于召开五级干部大会贯彻政策情况报告的批语',
        dates: [{ year: 1960, month: 11, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 55,
        page_end: 58,
        title: '对中央关于农村人民公社当前政策问题的紧急指示信的批语和修改',
        dates: [{ year: 1960, month: 11, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 61,
        page_end: 61,
        title: '在中央关于不准请客送礼和停止新建招待所的通知稿上的批语',
        dates: [{ year: 1960, month: 11, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 62,
        page_end: 64,
        title: '毛泽东等祝贺苏联十月革命四十三周年的电报',
        dates: [{ year: 1960, month: 11, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 67,
        page_end: 68,
        title: '对《工农业并举是我国社会主义经济的一个重要规律》一文的批语',
        dates: [{ year: 1960, month: 11, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 69,
        page_end: 69,
        title: '对《关于矛盾同一性和斗争性问题的讨论》等文章的批语',
        dates: [{ year: 1960, month: 11, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 70,
        page_end: 71,
        title: '在中央机关抽调万名干部下放基层情况报告上的批语',
        dates: [{ year: 1960, month: 11, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 72,
        page_end: 75,
        title: '中央关于彻底纠正“五风”问题的指示',
        dates: [{ year: 1960, month: 11, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 77,
        page_end: 77,
        title: '在林彪不同意军队向各地党委反映地方情况报告上的批语',
        dates: [{ year: 1960, month: 11, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 78,
        page_end: 79,
        title: '在甘肃省委关于贯彻中央紧急指示信的第二次报告上的批语',
        dates: [{ year: 1960, month: 11, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 80,
        page_end: 81,
        title: '中央转发四川省委贯彻执行中央紧急指示信的情况简报的批语',
        dates: [{ year: 1960, month: 11, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 82,
        page_end: 83,
        title: '对浙江省委关于重点商品粮地区存在问题的报告的批语',
        dates: [{ year: 1960, month: 11, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 84,
        page_end: 86,
        title: '中央转发甘肃省委关于贯彻中央紧急指示信的第四次报告的批语',
        dates: [{ year: 1960, month: 11, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 88,
        page_end: 90,
        title: '中央转发浙江省委关于贯彻执行中央紧急指示信的报告的批语',
        dates: [{ year: 1960, month: 11, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 91,
        page_end: 92,
        title: '毛泽东等祝贺阿尔巴尼亚解放十六周年的电报',
        dates: [{ year: 1960, month: 11, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 93,
        page_end: 94,
        title: '关于资本家下放问题的批语',
        dates: [{ year: 1960, month: 11, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 99,
        page_end: 100,
        title: '给黄炎培的信',
        dates: [{ year: 1960, month: 12, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 101,
        page_end: 102,
        title: '《红旗》编辑部给中共哈尔滨工业大学机床及自动化专业分总支的信',
        dates: [{ year: 1960, month: 12, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 104,
        page_end: 104,
        title: '转发《代食品会议情况反映》的批语',
        dates: [{ year: 1960, month: 12, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 105,
        page_end: 108,
        title:
          '对《关于加强军队政治思想工作的决议》和中央转发这一决议的指示稿的批语和修改',
        dates: [
          { year: 1960, month: 12, day: 14 },
          { year: 1960, month: 12, day: 21 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 109,
        page_end: 110,
        title: '中央转发湖南省委关于整风整社运动部署报告的批语',
        dates: [{ year: 1960, month: 12, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 111,
        page_end: 112,
        title: '印发关于河北省三个人民公社调查简报的批语',
        dates: [{ year: 1960, month: 12, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 113,
        page_end: 113,
        title: '印发谭震林关于粮食情况报告的批语',
        dates: [{ year: 1960, month: 12, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 114,
        page_end: 115,
        title: '应当充分地批判地利用文化遗产',
        dates: [{ year: 1960, month: 12, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 116,
        page_end: 117,
        title: '毛泽东等祝贺中德友好合作条约签订五周年的电报',
        dates: [{ year: 1960, month: 12, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 118,
        page_end: 119,
        title: '中央转发陕西省委关于当前市场问题的报告的批语',
        dates: [{ year: 1960, month: 12, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 120,
        page_end: 120,
        title: '为杨颖题词',
        dates: [{ year: 1960, month: 12, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 122,
        page_end: 123,
        title: '要结合实际总结革命战争经验',
        dates: [{ year: 1960, month: 12, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 124,
        page_end: 125,
        title: '给即将下放的身边工作人员的信',
        dates: [{ year: 1960, month: 12, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 126,
        page_end: 126,
        title: '印发人民来信对中央紧急指示信的反映的批语',
        dates: [{ year: 1960, month: 12, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 127,
        page_end: 127,
        title: '印发《在粮食问题上进行思想教育的一些值得注意的情况》一文的批语',
        dates: [{ year: 1960, month: 12, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 128,
        page_end: 129,
        title: '毛泽东等给苏联领导人的新年贺电',
        dates: [{ year: 1960, month: 12, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 131,
        page_end: 131,
        title: '印发关于美、英、苏农业劳动力负担情况资料的批语',
        dates: [{ year: 1960, month: 12, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 132,
        page_end: 136,
        title: '坚决退赔，刹住“共产风”',
        dates: [{ year: 1960, month: 12, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 137,
        page_end: 138,
        title:
          '对信阳地委关于整风、生产救灾情况报告和中央转发这一报告的指示稿的批语和修改',
        dates: [{ year: 1960, month: 12, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 139,
        page_end: 139,
        title: '给毛岸青的信',
        dates: [{ year: 1960 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 140,
        page_end: 140,
        title: '给林克的信',
        dates: [{ year: 1960 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 141,
        page_end: 141,
        title: '为《新湘评论》题名',
        dates: [{ year: 1960 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 142,
        page_end: 142,
        title: '请林克查找现、战二韵所在声部的批语',
        dates: [{ year: 1960 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 144,
        page_end: 145,
        title: '中央转发河南省委关于贯彻执行毛泽东等对信阳问题批示的文件的批语',
        dates: [{ year: 1961, month: 1, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 146,
        page_end: 147,
        title: '对党政干部“三大纪律、八项注意（草案）”的批语',
        dates: [{ year: 1961, month: 1, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 148,
        page_end: 149,
        title: '关于推广锦州四○一厂解决职工闹粮问题经验的批语',
        dates: [{ year: 1961, month: 1, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 150,
        page_end: 154,
        title: '大兴调查研究之风',
        dates: [{ year: 1961, month: 1, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 155,
        page_end: 161,
        title: '在八届九中全会上的讲话',
        dates: [{ year: 1961, month: 1, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 163,
        page_end: 164,
        title: '给田家英的信',
        dates: [{ year: 1961, month: 1, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 165,
        page_end: 166,
        title: '对中共八届九中全会公报稿的批语和修改',
        dates: [{ year: 1961, month: 1, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 167,
        page_end: 171,
        title: '对何其芳《（不怕鬼的故事）序》的修改和批语',
        dates: [
          { year: 1961, month: 1, day: 23 },
          { year: 1961, month: 1, day: 24 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 173,
        page_end: 180,
        title: '和班禅额尔德尼的谈话',
        dates: [{ year: 1961, month: 1, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 181,
        page_end: 188,
        title: '日本人民斗争的影响是很深远的',
        dates: [{ year: 1961, month: 1, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 189,
        page_end: 190,
        title: '对《光明日报》《框框乎？指导原则乎？》一文的批语',
        dates: [{ year: 1961, month: 2, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 191,
        page_end: 192,
        title: '对罗瑞卿关于几个地区部队情况考察报告的批语',
        dates: [{ year: 1961, month: 2, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 193,
        page_end: 193,
        title: '七绝·为女民兵题照',
        dates: [{ year: 1961, month: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 195,
        page_end: 195,
        title: '庐山会议反右这股风把原来的反“左”割断了',
        dates: [{ year: 1961, month: 3, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 196,
        page_end: 196,
        title:
          '解决了队与队、人与人之间分配拉平的问题，就可以调动起群众的积极性',
        dates: [{ year: 1961, month: 3, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 197,
        page_end: 197,
        title: '不要老是要下面报“账”不要发那么多文件',
        dates: [{ year: 1961, month: 3, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 198,
        page_end: 198,
        title: '公社划小不划小主要应听群众的意见',
        dates: [{ year: 1961, month: 3, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 199,
        page_end: 200,
        title: '关于请朱德、陆定一参加南三区会议等问题的批语',
        dates: [{ year: 1961, month: 3, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 201,
        page_end: 201,
        title: '对《调查工作》一文的说明和批语',
        dates: [{ year: 1961, month: 3, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 204,
        page_end: 205,
        title: '反对两个平均主义',
        dates: [{ year: 1961, month: 3, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 206,
        page_end: 209,
        title: '要做系统的由历史到现状的调查研究',
        dates: [{ year: 1961, month: 3, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 210,
        page_end: 211,
        title: '对关于农村人民公社若干问题的一次座谈会记录的批语',
        dates: [{ year: 1961, month: 3, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 212,
        page_end: 212,
        title: '对南海县沥西大队试行生产队上调任务包干办法的批语',
        dates: [{ year: 1961, month: 3, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 213,
        page_end: 214,
        title: '对南三区会议情况简报第三号的批语',
        dates: [{ year: 1961, month: 3, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 215,
        page_end: 216,
        title:
          '对《华东几个同志关于当前农村人民公社需要解决的几个问题的意见》的批语',
        dates: [{ year: 1961, month: 3, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 217,
        page_end: 217,
        title: '印发两份农村见闻材料的批语',
        dates: [{ year: 1961, month: 3, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 218,
        page_end: 218,
        title: '印发南充市火花公社一九六O年决算分配经验的批语',
        dates: [{ year: 1961, month: 3, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 219,
        page_end: 220,
        title: '印发《关于东北地区农村人民公社和农业生产的若干问题》的批语',
        dates: [{ year: 1961, month: 3, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 221,
        page_end: 221,
        title: '印发《一些社员和干部对于按劳分配问题的意见》的批语',
        dates: [{ year: 1961, month: 3, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 222,
        page_end: 232,
        title: '在广州中央工作会议上的讲话',
        dates: [{ year: 1961, month: 3, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 233,
        page_end: 234,
        title: '对中央关于认真进行调查工作问题的指示信的修改',
        dates: [{ year: 1961, month: 3, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 235,
        page_end: 236,
        title: '在山东省召开公社体制问题座谈会的情况简报上的批语',
        dates: [{ year: 1961, month: 3, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 238,
        page_end: 238,
        title: '关于查找南宋几部诗文集的批语',
        dates: [{ year: 1961, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 239,
        page_end: 239,
        title: '为《南宁晚报》题写报头',
        dates: [{ year: 1961, month: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 240,
        page_end: 241,
        title: '毛泽东等祝贺牙利解放十六周年的电报',
        dates: [{ year: 1961, month: 4, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 242,
        page_end: 243,
        title: '关于请王任重、王延春帮助湖南解决一些问题的批语',
        dates: [{ year: 1961, month: 4, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 244,
        page_end: 246,
        title: '印发胡乔木报送的关于解决公社食堂问题等调查材料的批语',
        dates: [{ year: 1961, month: 4, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 247,
        page_end: 248,
        title: '/中央转发西北局关于调查研究问题报告的批语',
        dates: [{ year: 1961, month: 4, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 249,
        page_end: 249,
        title: '和古巴文化代表团的谈话',
        dates: [{ year: 1961, month: 4, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 250,
        page_end: 250,
        title: '给臧克家的信',
        dates: [{ year: 1961, month: 4, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 251,
        page_end: 252,
        title: '给邓小平的信',
        dates: [{ year: 1961, month: 4, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 256,
        page_end: 260,
        title: '非洲是斗争的前线',
        dates: [{ year: 1961, month: 4, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 261,
        page_end: 261,
        title: '对杨朔《樱花雨》一文的批语',
        dates: [{ year: 1961, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 264,
        page_end: 265,
        title: '为推迟召开中央工作会议起草的通知和批语',
        dates: [{ year: 1961, month: 5, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 266,
        page_end: 266,
        title: '对张平化关于湖南工作来信的批语',
        dates: [{ year: 1961, month: 5, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 267,
        page_end: 268,
        title: '给李井泉、陈正人的信',
        dates: [{ year: 1961, month: 5, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 269,
        page_end: 269,
        title: '转发周恩来关于公共食堂等问题调查汇报的批语',
        dates: [{ year: 1961, month: 5, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 270,
        page_end: 270,
        title: '关于下连队调查极为有用给林彪的批语',
        dates: [{ year: 1961, month: 5, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 271,
        page_end: 271,
        title: '转发李井泉关于粮食问题来信的批语',
        dates: [{ year: 1961, month: 5, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 272,
        page_end: 273,
        title: '转发胡乔木关于湖南调查来信的批语',
        dates: [{ year: 1961, month: 5, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 274,
        page_end: 274,
        title: '关于胡乔木推迟返京、继续调查的批语',
        dates: [{ year: 1961, month: 5, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 279,
        page_end: 280,
        title: '转发邓小平、彭真关于调查农村人民公社几个问题来信的批语',
        dates: [{ year: 1961, month: 5, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 281,
        page_end: 281,
        title: '给张平化的信',
        dates: [{ year: 1961, month: 5, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 282,
        page_end: 283,
        title: '转发李井泉关于恢复供销合作社试点工作来信的批语',
        dates: [{ year: 1961, month: 5, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 284,
        page_end: 285,
        title: '对王任重关于湖南省三级干部会议情况来信的批语',
        dates: [{ year: 1961, month: 5, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 286,
        page_end: 287,
        title: '转发阎红彦关于调查农村人民公社几个问题来信的批语',
        dates: [{ year: 1961, month: 5, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 289,
        page_end: 291,
        title: '对《关于“调查研究”的调查》一文的批语和修改',
        dates: [
          { year: 1961, month: 5, day: 28 },
          { year: 1961, month: 5, day: 30 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 292,
        page_end: 293,
        title: '转发农村商业要办活一点的调查材料的批语',
        dates: [{ year: 1961, month: 5, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 294,
        page_end: 294,
        title: '印发关于湖南工作的四封信的批语',
        dates: [{ year: 1961, month: 6, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 296,
        page_end: 297,
        title: '关于中央工作会议第二、三阶段日程安排的批语',
        dates: [
          { year: 1961, month: 6, day: 3 },
          { year: 1961, month: 6, day: 4 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 298,
        page_end: 299,
        title:
          '对中央关于举办“抗大”式政治学校训练一批知识青年到农村工作的指示稿的批语',
        dates: [{ year: 1961, month: 6, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 300,
        page_end: 302,
        title:
          '对中央关于讨论和试行农村人民公社工作条例修正草案指示稿等的批语和修改',
        dates: [
          { year: 1961, month: 6, day: 11 },
          { year: 1961, month: 6, day: 17 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 303,
        page_end: 304,
        title:
          '印发关于王国藩社西铺大队粮食生产与畜牧业生产相结合的调查材料的批语',
        dates: [{ year: 1961, month: 6, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 305,
        page_end: 311,
        title: '总结经验，教育干部',
        dates: [{ year: 1961, month: 6, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 312,
        page_end: 312,
        title: '给刘松林的信',
        dates: [{ year: 1961, month: 6, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 313,
        page_end: 314,
        title: '中国在联合国只能有一个代表',
        dates: [{ year: 1961, month: 6, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 318,
        page_end: 318,
        title: '给邓小平的信',
        dates: [{ year: 1961, month: 6, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 319,
        page_end: 320,
        title: '对刘少奇在庆祝中国共产党成立四十周年大会上的讲话稿的修改',
        dates: [{ year: 1961, month: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 325,
        page_end: 325,
        title: '给张维的信',
        dates: [{ year: 1961, month: 7, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 326,
        page_end: 327,
        title: '毛泽东等祝贺蒙古人民革命四十周年的电报',
        dates: [{ year: 1961, month: 7, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 329,
        page_end: 329,
        title: '在关于日本经济政策和国防工业发展问题的一份材料上的批语',
        dates: [{ year: 1961, month: 7, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 331,
        page_end: 332,
        title: '毛泽东等祝贺波兰国庆十七周年的电报',
        dates: [{ year: 1961, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 333,
        page_end: 333,
        title: '祝贺古巴人民武装起义八周年的电报',
        dates: [{ year: 1961, month: 7, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 334,
        page_end: 335,
        title: '给江西共产主义劳动大学的一封信',
        dates: [{ year: 1961, month: 7, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 336,
        page_end: 336,
        title: '关于同意会见古巴桑切斯少校的批语',
        dates: [{ year: 1961, month: 8, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 337,
        page_end: 337,
        title: '祝贺苏联第二个载人宇宙飞船发射成功的电报',
        dates: [{ year: 1961, month: 8, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 338,
        page_end: 339,
        title: '毛泽东等祝贺朝鲜解放十六周年的电报',
        dates: [{ year: 1961, month: 8, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 341,
        page_end: 341,
        title: '祝贺印度尼西亚独立十六周年的电报',
        dates: [{ year: 1961, month: 8, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 345,
        page_end: 346,
        title: '世界大战的两种可能性',
        dates: [{ year: 1961, month: 8, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 347,
        page_end: 347,
        title: '搞社会主义我们还没有一套，还要碰钉子',
        dates: [{ year: 1961, month: 8, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 348,
        page_end: 348,
        title: '给胡乔木的信',
        dates: [{ year: 1961, month: 8, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 350,
        page_end: 350,
        title: '在林彪关于总政选印《毛选》部分文章的请示报告上的批语',
        dates: [{ year: 1961, month: 8, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 359,
        page_end: 360,
        title: '毛泽东等祝贺越南民主共和国成立十六周年的电报',
        dates: [{ year: 1961, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 361,
        page_end: 362,
        title: '对各地贯彻执行农业六十条情况简报的批语',
        dates: [{ year: 1961, month: 9, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 363,
        page_end: 363,
        title: '给董必武的信',
        dates: [{ year: 1961, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 365,
        page_end: 366,
        title: '毛泽东等祝贺保加利亚社会主义革命十七周年的电报',
        dates: [{ year: 1961, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 367,
        page_end: 367,
        title: '七绝·为李进同志题所摄庐山仙人洞照',
        dates: [{ year: 1961, month: 9, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 368,
        page_end: 368,
        title: '在中央关于轮训干部的决定修正稿上的批语',
        dates: [{ year: 1961, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 370,
        page_end: 370,
        title: '在庐山书赠中央常委的诗句',
        dates: [{ year: 1961, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 402,
        page_end: 404,
        title: '在《社会主义建设的几个问题（学习材料）》上的批语',
        dates: [{ year: 1961, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 405,
        page_end: 406,
        title: '在中央关于讨论和试行国营工业企业工作条例草案指示稿上的批语',
        dates: [{ year: 1961, month: 9, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 407,
        page_end: 424,
        title: '和蒙哥马利的谈话',
        dates: [{ year: 1961, month: 9, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 426,
        page_end: 427,
        title: '核武器是吓人的东西，不会用的',
        dates: [{ year: 1961, month: 9, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 430,
        page_end: 432,
        title: '邯郸谈话会记录',
        dates: [{ year: 1961, month: 9, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 434,
        page_end: 437,
        title: '给中央常委的信',
        dates: [{ year: 1961, month: 9, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 442,
        page_end: 442,
        title: '关于召集中央局书记讨论“队为基础”问题的批语',
        dates: [{ year: 1961, month: 10, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 443,
        page_end: 445,
        title: '和尼泊尔国王马亨德拉和王后的谈话',
        dates: [{ year: 1961, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 446,
        page_end: 447,
        title: '对胡耀邦农村考察报告的批语',
        dates: [{ year: 1961, month: 10, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 448,
        page_end: 449,
        title: '毛泽东等祝贺德意志民主共和国成立十二周年的电报',
        dates: [{ year: 1961, month: 10, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 450,
        page_end: 452,
        title: '对中央关于农村基本核算单位问题的指示稿的批语和修改',
        dates: [{ year: 1961, month: 10, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 453,
        page_end: 456,
        title: '日本人民的前途是光明的',
        dates: [{ year: 1961, month: 10, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 458,
        page_end: 458,
        title: '为日本访华朋友们题词',
        dates: [{ year: 1961, month: 10, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 460,
        page_end: 460,
        title: '对《光明日报》发表的《论假说》一文的批语',
        dates: [{ year: 1961, month: 10, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 461,
        page_end: 462,
        title: '对苏共第二十二次代表大会的贺词',
        dates: [{ year: 1961, month: 10, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 463,
        page_end: 463,
        title: '对开滦煤炭生产中存在的几个问题材料的批语',
        dates: [{ year: 1961, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 464,
        page_end: 465,
        title: '在《关于党的生活的几个问题（学习材料）》上的批语',
        dates: [{ year: 1961, month: 10, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 466,
        page_end: 466,
        title: '为发展和阿尔巴尼亚的友好关系题词',
        dates: [{ year: 1961, month: 10, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 468,
        page_end: 469,
        title: '关于转发南宫县贯彻大包干政策经验的批语',
        dates: [
          { year: 1961, month: 10, day: 22 },
          { year: 1961, month: 10, day: 23 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 471,
        page_end: 472,
        title: '对中央关于当前农村工作的几点指示稿等的批语',
        dates: [{ year: 1961, month: 10, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 473,
        page_end: 473,
        title: '为李家骥题词',
        dates: [{ year: 1961, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 475,
        page_end: 475,
        title: '七绝·屈原',
        dates: [{ year: 1961 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 476,
        page_end: 477,
        title: '毛泽东等祝贺苏联十月社会主义革命四十四周年的电报',
        dates: [{ year: 1961, month: 11, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 478,
        page_end: 479,
        title: '苏联和保加利亚的两件事',
        dates: [{ year: 1961, month: 11, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 480,
        page_end: 481,
        title: '七律·和郭沫若同志',
        dates: [{ year: 1961, month: 11, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 484,
        page_end: 485,
        title: '关于选看一些材料给江青的批语',
        dates: [{ year: 1961, month: 11, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 486,
        page_end: 488,
        title:
          '对中央转发邓子恢关于农村人民公社基本核算单位试点情况调查报告的批语',
        dates: [{ year: 1961, month: 11, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 489,
        page_end: 491,
        title: '毛泽东等祝贺阿尔巴尼亚解放十七周年的电报',
        dates: [{ year: 1961, month: 11, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 492,
        page_end: 492,
        title: '给臧克家的信',
        dates: [{ year: 1961, month: 11, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 493,
        page_end: 493,
        title: '既要有总路线，还要有具体政策',
        dates: [{ year: 1961, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 495,
        page_end: 495,
        title: '关于了解江苏省经济工作的经验给李先念、姚依林的信',
        dates: [{ year: 1961, month: 12, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 497,
        page_end: 497,
        title: '过去走了弯路应该首先由中央负责',
        dates: [{ year: 1961, month: 12, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 498,
        page_end: 498,
        title: '给张仙朋的信',
        dates: [{ year: 1961, month: 12, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 499,
        page_end: 499,
        title: '给周世钊的信',
        dates: [{ year: 1961, month: 12, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 502,
        page_end: 502,
        title: '给臧克家的信',
        dates: [{ year: 1961, month: 12, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 506,
        page_end: 507,
        title: '印发中共中央关于支持美共反迫害斗争的宣传通知的批语',
        dates: [{ year: 1961, month: 12, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 508,
        page_end: 509,
        title: '卜算子·咏梅',
        dates: [{ year: 1961, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 521,
        page_end: 522,
        title: '印发《光明日报》上发表的几首诗的批语',
        dates: [{ year: 1961, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 523,
        page_end: 523,
        title: '给刘松林的信',
        dates: [{ year: 1961, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 524,
        page_end: 525,
        title: '毛泽东等给苏联领导人的新年贺电',
        dates: [{ year: 1961, month: 12, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 526,
        page_end: 526,
        title: '对一篇关于人道主义文章的摘报的批语',
        dates: [{ year: 1961, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 527,
        page_end: 528,
        title: '七律·答友人',
        dates: [{ year: 1961 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 532,
        page_end: 533,
        title: '七绝两首·纪念鲁迅八十寿辰',
        dates: [{ year: 1961 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 534,
        page_end: 534,
        title: '七律·改鲁迅诗',
        dates: [{ year: 1961 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
    ],
  },
  parser_id: 'automation',
  path: '/archives0/mao-quanji/maoquanji44.pdf',
};
