export default {
  entity: {
    id: 'maoquanji25',
    name: '毛泽东全集第25卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives8/main/maoquanji25.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '同意杨成武部主力向西行动',
        authors: ['毛泽东'],
        page_start: 33,
        page_end: 34,
        dates: [{ year: 1948, month: 10, day: 11 }],
        is_range_date: false,
      },
      {
        title: '故占彰武对我攻锦并非不利',
        authors: ['毛泽东'],
        page_start: 35,
        page_end: 35,
        dates: [{ year: 1948, month: 10, day: 11 }],
        is_range_date: false,
      },
      {
        title: '关于淮海战役的作战方针叫',
        authors: ['毛泽东'],
        page_start: 36,
        page_end: 40,
        dates: [{ year: 1948, month: 10, day: 11 }],
        is_range_date: false,
      },
      {
        title: '致刘伯承、陈毅、邓小平、李达电',
        authors: ['毛泽东'],
        page_start: 41,
        page_end: 41,
        dates: [{ year: 1948, month: 10, day: 11 }],
        is_range_date: false,
      },
      {
        title: '对援锦敌军动向的分析',
        authors: ['毛泽东'],
        page_start: 42,
        page_end: 43,
        dates: [{ year: 1948, month: 10, day: 12 }],
        is_range_date: false,
      },
      {
        title: '望令陈锡联陈赛部全力攻击郑州',
        authors: ['毛泽东'],
        page_start: 44,
        page_end: 45,
        dates: [{ year: 1948, month: 10, day: 13 }],
        is_range_date: false,
      },
      {
        title: '望杨罗耿部弃敌十六军一部',
        authors: ['毛泽东'],
        page_start: 46,
        page_end: 46,
        dates: [{ year: 1948, month: 10, day: 13 }],
        is_range_date: false,
      },
      {
        title: '甜制徐州援敌齐灭黄百韬兵团',
        authors: ['毛泽东'],
        page_start: 47,
        page_end: 50,
        dates: [{ year: 1948, month: 10, day: 14 }],
        is_range_date: false,
      },
      {
        title: '力争于月底攻取包头',
        authors: ['毛泽东'],
        page_start: 51,
        page_end: 51,
        dates: [{ year: 1948, month: 10, day: 14 }],
        is_range_date: false,
      },
      {
        title: '推退攻击郑州加紧完成淮海战役准备',
        authors: ['毛泽东'],
        page_start: 52,
        page_end: 54,
        dates: [{ year: 1948, month: 10, day: 14 }],
        is_range_date: false,
      },
      {
        title: '将锦西援敌诱至锦州附近包围齐灭之',
        authors: ['毛泽东'],
        page_start: 55,
        page_end: 60,
        dates: [{ year: 1948, month: 10, day: 14 }],
        is_range_date: false,
      },
      {
        title: '对付冯治安部及侧击徐州援敌的部署',
        authors: ['毛泽东'],
        page_start: 61,
        page_end: 62,
        dates: [{ year: 1948, month: 10, day: 15 }],
        is_range_date: false,
      },
      {
        title: '准海战役计划不应变更',
        authors: ['毛泽东'],
        page_start: 63,
        page_end: 64,
        dates: [{ year: 1948, month: 10, day: 15 }],
        is_range_date: false,
      },
      {
        title: '复刘伯承、陈毅、邓小平等电',
        authors: ['毛泽东'],
        page_start: 65,
        page_end: 65,
        dates: [{ year: 1948, month: 10, day: 15 }],
        is_range_date: false,
      },
      {
        title: '不失时机争取六十军起义',
        authors: ['毛泽东'],
        page_start: 66,
        page_end: 67,
        dates: [{ year: 1948, month: 10, day: 16 }],
        is_range_date: false,
      },
      {
        title: '下一步行动宜打锦西葫芦岛',
        authors: ['毛泽东'],
        page_start: 68,
        page_end: 70,
        dates: [{ year: 1948, month: 10, day: 17 }],
        is_range_date: false,
      },
      {
        title: '攻郑时机似以再推退两三天为好叫',
        authors: ['毛泽东'],
        page_start: 71,
        page_end: 72,
        dates: [{ year: 1948, month: 10, day: 17 }],
        is_range_date: false,
      },
      {
        title: '速派部队阻绝沈敌从营口撤退',
        authors: ['毛泽东'],
        page_start: 73,
        page_end: 74,
        dates: [{ year: 1948, month: 10, day: 18 }],
        is_range_date: false,
      },
      {
        title: '致东北局等电',
        authors: ['毛泽东'],
        page_start: 75,
        page_end: 75,
        dates: [{ year: 1948, month: 10, day: 18 }],
        is_range_date: false,
      },
      {
        title: '宜以五纵六纵十二级堵塞沈敌向营口的退路',
        authors: ['毛泽东'],
        page_start: 76,
        page_end: 76,
        dates: [{ year: 1948, month: 10, day: 19 }],
        is_range_date: false,
      },
      {
        title: '占领长春后的作战方针和部署叫',
        authors: ['毛泽东'],
        page_start: 77,
        page_end: 78,
        dates: [{ year: 1948, month: 10, day: 19 }],
        is_range_date: false,
      },
      {
        title: '准备各个歼灭廖耀湘部',
        authors: ['毛泽东'],
        page_start: 79,
        page_end: 80,
        dates: [{ year: 1948, month: 10, day: 19 }],
        is_range_date: false,
      },
      {
        title: '准备全齐廖耀湘兵团攻取沈阳',
        authors: ['毛泽东'],
        page_start: 81,
        page_end: 81,
        dates: [{ year: 1948, month: 10, day: 20 }],
        is_range_date: false,
      },
      {
        title: '即刻部著全牙廖耀湘兵团',
        authors: ['毛泽东'],
        page_start: 82,
        page_end: 84,
        dates: [{ year: 1948, month: 10, day: 20 }],
        is_range_date: false,
      },
      {
        title: '对轩灭廖耀湘兵团具体部署的意见',
        authors: ['毛泽东'],
        page_start: 85,
        page_end: 86,
        dates: [{ year: 1948, month: 10, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致刘伯承、陈毅、邓小平电',
        authors: ['毛泽东'],
        page_start: 87,
        page_end: 87,
        dates: [{ year: 1948, month: 10, day: 20 }],
        is_range_date: false,
      },
      {
        title: '同意围齐廖兵团及其他项部署',
        authors: ['毛泽东'],
        page_start: 88,
        page_end: 88,
        dates: [{ year: 1948, month: 10, day: 21 }],
        is_range_date: false,
      },
      {
        title: '部队休整后宜西移攻取同官耀县等地',
        authors: ['毛泽东'],
        page_start: 89,
        page_end: 90,
        dates: [{ year: 1948, month: 10, day: 21 }],
        is_range_date: false,
      },
      {
        title: '陈邓部攻克郑州后迅即东进',
        authors: ['毛泽东'],
        page_start: 91,
        page_end: 92,
        dates: [{ year: 1948, month: 10, day: 22 }],
        is_range_date: false,
      },
      {
        title: '我军解放郑州',
        authors: ['毛泽东'],
        page_start: 93,
        page_end: 94,
        dates: [{ year: 1948, month: 10, day: 22 }],
        is_range_date: false,
      },
      {
        title: '同意照淮海战役的修改部署执行',
        authors: ['毛泽东'],
        page_start: 95,
        page_end: 97,
        dates: [{ year: 1948, month: 10, day: 22 }],
        is_range_date: false,
      },
      {
        title: '致林彪、罗荣植、刘亚楼电',
        authors: ['毛泽东'],
        page_start: 98,
        page_end: 98,
        dates: [{ year: 1948, month: 10, day: 22 }],
        is_range_date: false,
      },
      {
        title: '电勉吴化文',
        authors: ['毛泽东'],
        page_start: 99,
        page_end: 99,
        dates: [{ year: 1948, month: 10, day: 22 }],
        is_range_date: false,
      },
      {
        title: '菜裕谭震林速赴南线指挥作战',
        authors: ['毛泽东'],
        page_start: 100,
        page_end: 101,
        dates: [{ year: 1948, month: 10, day: 23 }],
        is_range_date: false,
      },
      {
        title: '中共中央委员会电贺郑州解放',
        authors: ['毛泽东'],
        page_start: 102,
        page_end: 103,
        dates: [{ year: 1948, month: 10, day: 23 }],
        is_range_date: false,
      },
      {
        title: '控制营口阻塞敌人海上逃路',
        authors: ['毛泽东'],
        page_start: 104,
        page_end: 106,
        dates: [{ year: 1948, month: 10, day: 24 }],
        is_range_date: false,
      },
      {
        title: '应到蒙城集中以利机动作战',
        authors: ['毛泽东'],
        page_start: 107,
        page_end: 108,
        dates: [{ year: 1948, month: 10, day: 25 }],
        is_range_date: false,
      },
      {
        title: '忽视对营口的控制是不小的失着',
        authors: ['毛泽东'],
        page_start: 109,
        page_end: 110,
        dates: [{ year: 1948, month: 10, day: 25 }],
        is_range_date: false,
      },
      {
        title: '同意杨成武部打归缓的意见',
        authors: ['毛泽东'],
        page_start: 111,
        page_end: 111,
        dates: [{ year: 1948, month: 10, day: 25 }],
        is_range_date: false,
      },
      {
        title: '中共中央委员会电贺解放郑州、开封',
        authors: ['毛泽东'],
        page_start: 112,
        page_end: 112,
        dates: [{ year: 1948, month: 10, day: 25 }],
        is_range_date: false,
      },
      {
        title: '钳制邱清泉李弥两兵团分割齐灭黄百兵团的具体部署',
        authors: ['毛泽东'],
        page_start: 113,
        page_end: 115,
        dates: [{ year: 1948, month: 10, day: 26 }],
        is_range_date: false,
      },
      {
        title: '给刘少奇的信',
        authors: ['毛泽东'],
        page_start: 116,
        page_end: 116,
        dates: [{ year: 1948, month: 10, day: 26 }],
        is_range_date: false,
      },
      {
        title: '动员一切力量齐水可能向石家庄进扰之敌',
        authors: ['毛泽东'],
        page_start: 117,
        page_end: 118,
        dates: [{ year: 1948, month: 10, day: 26 }],
        is_range_date: false,
      },
      {
        title: '东北解放军正举行全线进攻',
        authors: ['毛泽东'],
        page_start: 119,
        page_end: 120,
        dates: [{ year: 1948, month: 10, day: 27 }],
        is_range_date: false,
      },
      {
        title: '淮海战役的部署要估计到情况的变化',
        authors: ['毛泽东'],
        page_start: 121,
        page_end: 123,
        dates: [{ year: 1948, month: 10, day: 27 }],
        is_range_date: false,
      },
      {
        title: '望以有力兵团东渡辽河歼灭营口一带之敌',
        authors: ['毛泽东'],
        page_start: 124,
        page_end: 124,
        dates: [{ year: 1948, month: 10, day: 27 }],
        is_range_date: false,
      },
      {
        title: '复曾泽生等电',
        authors: ['毛泽东'],
        page_start: 125,
        page_end: 125,
        dates: [{ year: 1948, month: 10, day: 27 }],
        is_range_date: false,
      },
      {
        title: '立即抽几个纵队兼程东进好天沈阳逃敌',
        authors: ['毛泽东'],
        page_start: 126,
        page_end: 126,
        dates: [{ year: 1948, month: 10, day: 28 }],
        is_range_date: false,
      },
      {
        title: '引证不良战例以为鉴戒',
        authors: ['毛泽东'],
        page_start: 127,
        page_end: 127,
        dates: [{ year: 1948, month: 10, day: 28 }],
        is_range_date: false,
      },
      {
        title: '复陈毅、邓小平电',
        authors: ['毛泽东'],
        page_start: 128,
        page_end: 128,
        dates: [{ year: 1948, month: 10, day: 28 }],
        is_range_date: false,
      },
      {
        title: '关于华北三纵七纵的行动部署',
        authors: ['毛泽东'],
        page_start: 129,
        page_end: 129,
        dates: [{ year: 1948, month: 10, day: 29 }],
        is_range_date: false,
      },
      {
        title: '十一纵可到三河集结相机攻击通具一带',
        authors: ['毛泽东'],
        page_start: 130,
        page_end: 131,
        dates: [{ year: 1948, month: 10, day: 29 }],
        is_range_date: false,
      },
      {
        title: '请考虑将东北第十一纵派往通县北平方向活动',
        authors: ['毛泽东'],
        page_start: 132,
        page_end: 132,
        dates: [{ year: 1948, month: 10, day: 29 }],
        is_range_date: false,
      },
      {
        title: '东北南调部队宜放在玉田面州等地区',
        authors: ['毛泽东'],
        page_start: 133,
        page_end: 133,
        dates: [{ year: 1948, month: 10, day: 29 }],
        is_range_date: false,
      },
      {
        title: '打归缓可稍为推退',
        authors: ['毛泽东'],
        page_start: 134,
        page_end: 135,
        dates: [{ year: 1948, month: 10, day: 29 }],
        is_range_date: false,
      },
      {
        title: '给胡乔木的信',
        authors: ['毛泽东'],
        page_start: 136,
        page_end: 136,
        dates: [{ year: 1948, month: 10, day: 29 }],
        is_range_date: false,
      },
      {
        title: '致杨得志、罗瑞卿、耿魔等电',
        authors: ['毛泽东'],
        page_start: 137,
        page_end: 137,
        dates: [{ year: 1948, month: 10, day: 29 }],
        is_range_date: false,
      },
      {
        title: '给刘少白“的信',
        authors: ['毛泽东'],
        page_start: 138,
        page_end: 139,
        dates: [{ year: 1948, month: 10, day: 30 }],
        is_range_date: false,
      },
      {
        title: '对黄李邮三兵团在同一个晚上发起攻击为好叫',
        authors: ['毛泽东'],
        page_start: 140,
        page_end: 141,
        dates: [{ year: 1948, month: 10, day: 30 }],
        is_range_date: false,
      },
      {
        title: '东北华北部队准备协方夺取平津地区',
        authors: ['毛泽东'],
        page_start: 142,
        page_end: 144,
        dates: [{ year: 1948, month: 10, day: 31 }],
        is_range_date: false,
      },
      {
        title: '评蒋傅军梦想偷袭石家庄',
        authors: ['毛泽东'],
        page_start: 145,
        page_end: 147,
        dates: [{ year: 1948, month: 10, day: 31 }],
        is_range_date: false,
      },
      {
        title: '为《中国青年》杂志题名',
        authors: ['毛泽东'],
        page_start: 148,
        page_end: 151,
        dates: [{ year: 1948, month: 10 }],
        is_range_date: false,
      },
      {
        title: '宜首先歼灭黄百密指挥所',
        authors: ['毛泽东'],
        page_start: 152,
        page_end: 152,
        dates: [{ year: 1948, month: 11, day: 1 }],
        is_range_date: false,
      },
      {
        title: '整个战役统一受陈毅、邓小平指挥',
        authors: ['毛泽东'],
        page_start: 153,
        page_end: 154,
        dates: [{ year: 1948, month: 11, day: 1 }],
        is_range_date: false,
      },
      {
        title: '杨罗耿兵团应进至满城以西地区待命',
        authors: ['毛泽东'],
        page_start: 155,
        page_end: 155,
        dates: [{ year: 1948, month: 11, day: 1 }],
        is_range_date: false,
      },
      {
        title: '除对付邮孙两兵团外还要对付黄维兵团',
        authors: ['毛泽东'],
        page_start: 156,
        page_end: 158,
        dates: [{ year: 1948, month: 11, day: 1 }],
        is_range_date: false,
      },
      {
        title: '破击平汉路延滞敌八十五军北上',
        authors: ['毛泽东'],
        page_start: 159,
        page_end: 160,
        dates: [{ year: 1948, month: 11, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致习仲勋、林伯渠等电',
        authors: ['毛泽东'],
        page_start: 161,
        page_end: 161,
        dates: [{ year: 1948, month: 11, day: 3 }],
        is_range_date: false,
      },
      {
        title: '四纵十一纵及各独立师进至遵化葡州地区之计划不变',
        authors: ['毛泽东'],
        page_start: 162,
        page_end: 163,
        dates: [{ year: 1948, month: 11, day: 4 }],
        is_range_date: false,
      },
      {
        title: '复林彪、罗荣柜、刘亚楼、谭政电',
        authors: ['毛泽东'],
        page_start: 164,
        page_end: 164,
        dates: [{ year: 1948, month: 11, day: 4 }],
        is_range_date: false,
      },
      {
        title: '致东北局等电',
        authors: ['毛泽东'],
        page_start: 165,
        page_end: 165,
        dates: [{ year: 1948, month: 11, day: 5 }],
        is_range_date: false,
      },
      {
        title: '在宿蚌地区作战的两个方案',
        authors: ['毛泽东'],
        page_start: 166,
        page_end: 167,
        dates: [{ year: 1948, month: 11, day: 5 }],
        is_range_date: false,
      },
      {
        title: '攻击归缓的部署叫',
        authors: ['毛泽东'],
        page_start: 168,
        page_end: 169,
        dates: [{ year: 1948, month: 11, day: 5 }],
        is_range_date: false,
      },
      {
        title: '中原我军占领南阳',
        authors: ['毛泽东'],
        page_start: 170,
        page_end: 173,
        dates: [{ year: 1948, month: 11, day: 5 }],
        is_range_date: false,
      },
      {
        title: '苏联十月革命节的贺电',
        authors: ['毛泽东'],
        page_start: 174,
        page_end: 174,
        dates: [{ year: 1948, month: 11, day: 5 }],
        is_range_date: false,
      },
      {
        title: '对冯治安部之抵抗和游移不决者应坚决弃灭',
        authors: ['毛泽东'],
        page_start: 175,
        page_end: 176,
        dates: [{ year: 1948, month: 11, day: 6 }],
        is_range_date: false,
      },
      {
        title: '复陈毅、邓小平等电',
        authors: ['毛泽东'],
        page_start: 177,
        page_end: 177,
        dates: [{ year: 1948, month: 11, day: 6 }],
        is_range_date: false,
      },
      {
        title: '准海战役第一仗和第二位的齐敌任务叫',
        authors: ['毛泽东'],
        page_start: 178,
        page_end: 179,
        dates: [{ year: 1948, month: 11, day: 7 }],
        is_range_date: false,
      },
      {
        title: '给刘少奇等的信',
        authors: ['毛泽东'],
        page_start: 180,
        page_end: 180,
        dates: [{ year: 1948, month: 11, day: 8 }],
        is_range_date: false,
      },
      {
        title: '应迅速分割包围黄兵团',
        authors: ['毛泽东'],
        page_start: 181,
        page_end: 181,
        dates: [{ year: 1948, month: 11, day: 8 }],
        is_range_date: false,
      },
      {
        title: '复菜裕、陈士架、张震电',
        authors: ['毛泽东'],
        page_start: 182,
        page_end: 182,
        dates: [{ year: 1948, month: 11, day: 8 }],
        is_range_date: false,
      },
      {
        title: '截断宿蚌路，歼敌于淮河长江以北',
        authors: ['毛泽东'],
        page_start: 183,
        page_end: 184,
        dates: [{ year: 1948, month: 11, day: 9 }],
        is_range_date: false,
      },
      {
        title: '极力争取在徐州附近齐灭敌人主方',
        authors: ['毛泽东'],
        page_start: 185,
        page_end: 185,
        dates: [{ year: 1948, month: 11, day: 9 }],
        is_range_date: false,
      },
      {
        title: '待东北我军南下攻平津杨成武部再攻归缓',
        authors: ['毛泽东'],
        page_start: 186,
        page_end: 186,
        dates: [{ year: 1948, month: 11, day: 9 }],
        is_range_date: false,
      },
      {
        title: '致杨成武、李井泉、李天焕电',
        authors: ['毛泽东'],
        page_start: 187,
        page_end: 187,
        dates: [{ year: 1948, month: 11, day: 9 }],
        is_range_date: false,
      },
      {
        title: '集中四个纵队全力攻取宿县叫',
        authors: ['毛泽东'],
        page_start: 188,
        page_end: 188,
        dates: [{ year: 1948, month: 11, day: 10 }],
        is_range_date: false,
      },
      {
        title: '应以勇猛神速手段弃灭李弥兵团',
        authors: ['毛泽东'],
        page_start: 189,
        page_end: 189,
        dates: [{ year: 1948, month: 11, day: 10 }],
        is_range_date: false,
      },
      {
        title: '开火孙元良部控制徐蚌段',
        authors: ['毛泽东'],
        page_start: 190,
        page_end: 191,
        dates: [{ year: 1948, month: 11, day: 10 }],
        is_range_date: false,
      },
      {
        title: '注意堵击黄百韬兵团',
        authors: ['毛泽东'],
        page_start: 192,
        page_end: 193,
        dates: [{ year: 1948, month: 11, day: 10 }],
        is_range_date: false,
      },
      {
        title: '力争齐灭孙元良部包围徐州叫',
        authors: ['毛泽东'],
        page_start: 194,
        page_end: 195,
        dates: [{ year: 1948, month: 11, day: 11 }],
        is_range_date: false,
      },
      {
        title: '隔断黄维与邱清泉李弥兵团之联系完成攻徐作战之战略展开',
        authors: ['毛泽东'],
        page_start: 196,
        page_end: 198,
        dates: [{ year: 1948, month: 11, day: 11 }],
        is_range_date: false,
      },
      {
        title: '同意围牙黄百韬兵团的部署',
        authors: ['毛泽东'],
        page_start: 199,
        page_end: 200,
        dates: [{ year: 1948, month: 11, day: 11 }],
        is_range_date: false,
      },
      {
        title: '再有一年左右时间即可从根本上打倒国民党',
        authors: ['毛泽东'],
        page_start: 201,
        page_end: 202,
        dates: [{ year: 1948, month: 11, day: 11 }],
        is_range_date: false,
      },
      {
        title: '中国军事形势的重大变化',
        authors: ['毛泽东'],
        page_start: 203,
        page_end: 206,
        dates: [{ year: 1948, month: 11, day: 12 }],
        is_range_date: false,
      },
      {
        title: '黄百韬解决后华野主力速移宿县地区叫',
        authors: ['毛泽东'],
        page_start: 207,
        page_end: 207,
        dates: [{ year: 1948, month: 11, day: 13 }],
        is_range_date: false,
      },
      {
        title: '阻止黄维部向毫县涡阳永城前进',
        authors: ['毛泽东'],
        page_start: 208,
        page_end: 209,
        dates: [{ year: 1948, month: 11, day: 13 }],
        is_range_date: false,
      },
      {
        title: '让邱清泉向东深人徐图齐灭之',
        authors: ['毛泽东'],
        page_start: 210,
        page_end: 210,
        dates: [{ year: 1948, month: 11, day: 13 }],
        is_range_date: false,
      },
      {
        title: '让邱清泉深人断其后路并包围之',
        authors: ['毛泽东'],
        page_start: 211,
        page_end: 211,
        dates: [{ year: 1948, month: 11, day: 14 }],
        is_range_date: false,
      },
      {
        title: '目前首要任务是阻止邱清泉李弥，歼灭黄百韬',
        authors: ['毛泽东'],
        page_start: 212,
        page_end: 213,
        dates: [{ year: 1948, month: 11, day: 14 }],
        is_range_date: false,
      },
      {
        title: '准海战役的作战部著',
        authors: ['毛泽东'],
        page_start: 214,
        page_end: 216,
        dates: [{ year: 1948, month: 11, day: 14 }],
        is_range_date: false,
      },
      {
        title: '将介石政府正在覆没',
        authors: ['毛泽东'],
        page_start: 217,
        page_end: 219,
        dates: [{ year: 1948, month: 11, day: 14 }],
        is_range_date: false,
      },
      {
        title: '外灭黄百韬后再定下一步作战方针',
        authors: ['毛泽东'],
        page_start: 220,
        page_end: 221,
        dates: [{ year: 1948, month: 11, day: 15 }],
        is_range_date: false,
      },
      {
        title: '复方方电',
        authors: ['毛泽东'],
        page_start: 222,
        page_end: 222,
        dates: [{ year: 1948, month: 11, day: 15 }],
        is_range_date: false,
      },
      {
        title: '推退攻击宿县切断固镇蚌埠间联系',
        authors: ['毛泽东'],
        page_start: 223,
        page_end: 223,
        dates: [{ year: 1948, month: 11, day: 16 }],
        is_range_date: false,
      },
      {
        title: '推退总攻确庄诱敌深人',
        authors: ['毛泽东'],
        page_start: 224,
        page_end: 224,
        dates: [{ year: 1948, month: 11, day: 16 }],
        is_range_date: false,
      },
      {
        title: '祝贺越南人民取得“边界战役”的胜利',
        authors: ['毛泽东'],
        page_start: 225,
        page_end: 226,
        dates: [{ year: 1950, month: 10, day: 16 }],
        is_range_date: false,
      },
      {
        title: '东北主力是否早日人关为好叫',
        authors: ['毛泽东'],
        page_start: 227,
        page_end: 228,
        dates: [{ year: 1948, month: 11, day: 16 }],
        is_range_date: false,
      },
      {
        title: '推退攻取太原',
        authors: ['毛泽东'],
        page_start: 229,
        page_end: 229,
        dates: [{ year: 1948, month: 11, day: 16 }],
        is_range_date: false,
      },
      {
        title: '由刘陈邓菜谭组成总前委统筹一切',
        authors: ['毛泽东'],
        page_start: 230,
        page_end: 232,
        dates: [{ year: 1948, month: 11, day: 16 }],
        is_range_date: false,
      },
      {
        title: '总攻确庄同时攻击邱清泉李弥兵团',
        authors: ['毛泽东'],
        page_start: 233,
        page_end: 234,
        dates: [{ year: 1948, month: 11, day: 16 }],
        is_range_date: false,
      },
      {
        title: '准备在国民党军再度进扰石家庄时南下歼敌',
        authors: ['毛泽东'],
        page_start: 235,
        page_end: 236,
        dates: [{ year: 1948, month: 11, day: 16 }],
        is_range_date: false,
      },
      {
        title: '防止北平天津张家口唐山玻军逃走的部署',
        authors: ['毛泽东'],
        page_start: 237,
        page_end: 238,
        dates: [{ year: 1948, month: 11, day: 18 }],
        is_range_date: false,
      },
      {
        title: '东北野战军取捷径迅速人关包围唐山塘活天津之敌',
        authors: ['毛泽东'],
        page_start: 239,
        page_end: 240,
        dates: [{ year: 1948, month: 11, day: 18 }],
        is_range_date: false,
      },
      {
        title: '关于阻齐南线敌人的部署叫',
        authors: ['毛泽东'],
        page_start: 241,
        page_end: 242,
        dates: [{ year: 1948, month: 11, day: 18 }],
        is_range_date: false,
      },
      {
        title: '关于淮海战役下一步作战方针',
        authors: ['毛泽东'],
        page_start: 243,
        page_end: 245,
        dates: [{ year: 1948, month: 11, day: 19 }],
        is_range_date: false,
      },
      {
        title: '对邱清泉李弥各军以先齐一部为宜',
        authors: ['毛泽东'],
        page_start: 246,
        page_end: 247,
        dates: [{ year: 1948, month: 11, day: 19 }],
        is_range_date: false,
      },
      {
        title: '华东野战军应抽出必要兵力对付李延年叫',
        authors: ['毛泽东'],
        page_start: 248,
        page_end: 249,
        dates: [{ year: 1948, month: 11, day: 19 }],
        is_range_date: false,
      },
      {
        title: '复彭泽湘电',
        authors: ['毛泽东'],
        page_start: 250,
        page_end: 250,
        dates: [{ year: 1948, month: 11, day: 19 }],
        is_range_date: false,
      },
      {
        title: '打李延年兵团由华东野战军负责',
        authors: ['毛泽东'],
        page_start: 251,
        page_end: 252,
        dates: [{ year: 1948, month: 11, day: 20 }],
        is_range_date: false,
      },
      {
        title: '先以四个纵队夜行晓宿秘密人关',
        authors: ['毛泽东'],
        page_start: 253,
        page_end: 255,
        dates: [{ year: 1948, month: 11, day: 20 }],
        is_range_date: false,
      },
      {
        title: '东北部队人关的时间路线和任务',
        authors: ['毛泽东'],
        page_start: 256,
        page_end: 257,
        dates: [{ year: 1948, month: 11, day: 21 }],
        is_range_date: false,
      },
      {
        title: '华东野战军今后一时期的主要任务是齐灭李延年',
        authors: ['毛泽东'],
        page_start: 258,
        page_end: 259,
        dates: [{ year: 1948, month: 11, day: 21 }],
        is_range_date: false,
      },
      {
        title: '给刘少奇等的信',
        authors: ['毛泽东'],
        page_start: 260,
        page_end: 260,
        dates: [{ year: 1948, month: 11, day: 21 }],
        is_range_date: false,
      },
      {
        title: '复杨得志、罗瑞卿等电',
        authors: ['毛泽东'],
        page_start: 261,
        page_end: 261,
        dates: [{ year: 1948, month: 11, day: 21 }],
        is_range_date: false,
      },
      {
        title: '杨成武部主力准备东进切断北平张家口之联系',
        authors: ['毛泽东'],
        page_start: 262,
        page_end: 262,
        dates: [{ year: 1948, month: 11, day: 22 }],
        is_range_date: false,
      },
      {
        title: '必须准备连续作战争取战役全胜',
        authors: ['毛泽东'],
        page_start: 263,
        page_end: 265,
        dates: [{ year: 1948, month: 11, day: 23 }],
        is_range_date: false,
      },
      {
        title: '同意歼灭李延年的部署',
        authors: ['毛泽东'],
        page_start: 266,
        page_end: 267,
        dates: [{ year: 1948, month: 11, day: 23 }],
        is_range_date: false,
      },
      {
        title: '同意先打黄维',
        authors: ['毛泽东'],
        page_start: 268,
        page_end: 268,
        dates: [{ year: 1948, month: 11, day: 24 }],
        is_range_date: false,
      },
      {
        title: '暂不理山海关秦皇岛之敌',
        authors: ['毛泽东'],
        page_start: 269,
        page_end: 270,
        dates: [{ year: 1948, month: 11, day: 24 }],
        is_range_date: false,
      },
      {
        title: '杨成武主力三个纵队的行动部署',
        authors: ['毛泽东'],
        page_start: 271,
        page_end: 272,
        dates: [{ year: 1948, month: 11, day: 24 }],
        is_range_date: false,
      },
      {
        title: '给吴晗"的信',
        authors: ['毛泽东'],
        page_start: 273,
        page_end: 275,
        dates: [{ year: 1948, month: 11, day: 24 }],
        is_range_date: false,
      },
      {
        title: '致华东局等电',
        authors: ['毛泽东'],
        page_start: 276,
        page_end: 276,
        dates: [{ year: 1948, month: 11, day: 24 }],
        is_range_date: false,
      },
      {
        title: '关于杨罗耿部的行动部署',
        authors: ['毛泽东'],
        page_start: 277,
        page_end: 277,
        dates: [{ year: 1948, month: 11, day: 26 }],
        is_range_date: false,
      },
      {
        title: '东北大军人关后的作战计划叫',
        authors: ['毛泽东'],
        page_start: 278,
        page_end: 279,
        dates: [{ year: 1948, month: 11, day: 26 }],
        is_range_date: false,
      },
      {
        title: '注意对付黄维的最后挣扎',
        authors: ['毛泽东'],
        page_start: 280,
        page_end: 281,
        dates: [{ year: 1948, month: 11, day: 26 }],
        is_range_date: false,
      },
      {
        title: '迅速抓住扭打平张线上之敌',
        authors: ['毛泽东'],
        page_start: 282,
        page_end: 284,
        dates: [{ year: 1948, month: 11, day: 27 }],
        is_range_date: false,
      },
      {
        title: '引李延年部前进打击其侧后叫',
        authors: ['毛泽东'],
        page_start: 285,
        page_end: 285,
        dates: [{ year: 1948, month: 11, day: 27 }],
        is_range_date: false,
      },
      {
        title: '向国民党军黄维兵团的广播讲话',
        authors: ['毛泽东'],
        page_start: 286,
        page_end: 289,
        dates: [{ year: 1948, month: 11, day: 27 }],
        is_range_date: false,
      },
      {
        title: '请考虑淮海战役第三阶段作战的兵力部署问题',
        authors: ['毛泽东'],
        page_start: 290,
        page_end: 292,
        dates: [{ year: 1948, month: 11, day: 28 }],
        is_range_date: false,
      },
      {
        title: '程子华黄志勇部暂在原地待命',
        authors: ['毛泽东'],
        page_start: 293,
        page_end: 294,
        dates: [{ year: 1948, month: 11, day: 28 }],
        is_range_date: false,
      },
      {
        title: '请考虑在歼灭固镇曹老集敌人以后可否渡淮作战',
        authors: ['毛泽东'],
        page_start: 295,
        page_end: 295,
        dates: [{ year: 1948, month: 11, day: 28 }],
        is_range_date: false,
      },
      {
        title: '给徐向前“的信',
        authors: ['毛泽东'],
        page_start: 296,
        page_end: 296,
        dates: [{ year: 1948, month: 11, day: 29 }],
        is_range_date: false,
      },
      {
        title: '开天黄维兵团是解决徐蚌全敌的关键',
        authors: ['毛泽东'],
        page_start: 297,
        page_end: 298,
        dates: [{ year: 1948, month: 11, day: 29 }],
        is_range_date: false,
      },
      {
        title: '包围张宣之敌务使不能逃跑',
        authors: ['毛泽东'],
        page_start: 299,
        page_end: 299,
        dates: [{ year: 1948, month: 11, day: 29 }],
        is_range_date: false,
      },
      {
        title: '开灭黄维后全力解决邱清泉季弥孙元良部',
        authors: ['毛泽东'],
        page_start: 300,
        page_end: 301,
        dates: [{ year: 1948, month: 11, day: 30 }],
        is_range_date: false,
      },
      {
        title: '程黄部仍接原计划准备西进',
        authors: ['毛泽东'],
        page_start: 302,
        page_end: 303,
        dates: [{ year: 1948, month: 11, day: 30 }],
        is_range_date: false,
      },
      {
        title: '为张天义题词',
        authors: ['毛泽东'],
        page_start: 304,
        page_end: 305,
        dates: [{ year: 1948, month: 11, day: 30 }],
        is_range_date: false,
      },
      {
        title: '给胡乔木的信',
        authors: ['毛泽东'],
        page_start: 306,
        page_end: 306,
        dates: [{ year: 1948, month: 11, day: 30 }],
        is_range_date: false,
      },
      {
        title: '给胡乔木的信',
        authors: ['毛泽东'],
        page_start: 307,
        page_end: 308,
        dates: [{ year: 1948, month: 11 }],
        is_range_date: false,
      },
      {
        title: '全世界革命力量团结起来，反对帝国主义的侵略',
        authors: ['毛泽东'],
        page_start: 309,
        page_end: 312,
        dates: [{ year: 1948, month: 11 }],
        is_range_date: false,
      },
      {
        title: '防止敌军向两准或连云港逃跑山',
        authors: ['毛泽东'],
        page_start: 313,
        page_end: 313,
        dates: [{ year: 1948, month: 12, day: 1 }],
        is_range_date: false,
      },
      {
        title: '抓住胡宗南使其兵方不能他调',
        authors: ['毛泽东'],
        page_start: 314,
        page_end: 315,
        dates: [{ year: 1948, month: 12, day: 1 }],
        is_range_date: false,
      },
      {
        title: '杨成武部务必包围几部敌人',
        authors: ['毛泽东'],
        page_start: 316,
        page_end: 316,
        dates: [{ year: 1948, month: 12, day: 1 }],
        is_range_date: false,
      },
      {
        title: '程子华黄志勇部立即向南口怀来前进',
        authors: ['毛泽东'],
        page_start: 317,
        page_end: 317,
        dates: [{ year: 1948, month: 12, day: 2 }],
        is_range_date: false,
      },
      {
        title: '加强兵力确保切断张家口宣化敌之联系',
        authors: ['毛泽东'],
        page_start: 318,
        page_end: 318,
        dates: [{ year: 1948, month: 12, day: 2 }],
        is_range_date: false,
      },
      {
        title: '华东野战军应派两个纵队培西逃之敌',
        authors: ['毛泽东'],
        page_start: 319,
        page_end: 319,
        dates: [{ year: 1948, month: 12, day: 2 }],
        is_range_date: false,
      },
      {
        title: '重点应放在隔断张宣两地之敌',
        authors: ['毛泽东'],
        page_start: 320,
        page_end: 320,
        dates: [{ year: 1948, month: 12, day: 3 }],
        is_range_date: false,
      },
      {
        title: '应以最快手段攻占下花园地区',
        authors: ['毛泽东'],
        page_start: 321,
        page_end: 321,
        dates: [{ year: 1948, month: 12, day: 4 }],
        is_range_date: false,
      },
      {
        title: '大胆插入敌各军之间以利齐击',
        authors: ['毛泽东'],
        page_start: 322,
        page_end: 322,
        dates: [{ year: 1948, month: 12, day: 4 }],
        is_range_date: false,
      },
      {
        title: '平张线上各兵团的作战任务',
        authors: ['毛泽东'],
        page_start: 323,
        page_end: 324,
        dates: [{ year: 1948, month: 12, day: 4 }],
        is_range_date: false,
      },
      {
        title: '开灭强敌必须用强攻方法',
        authors: ['毛泽东'],
        page_start: 325,
        page_end: 326,
        dates: [{ year: 1948, month: 12, day: 4 }],
        is_range_date: false,
      },
      {
        title: '一纵必须全部用于切断张宣联系',
        authors: ['毛泽东'],
        page_start: 327,
        page_end: 327,
        dates: [{ year: 1948, month: 12, day: 4 }],
        is_range_date: false,
      },
      {
        title: '务使张家口之敌不能东退',
        authors: ['毛泽东'],
        page_start: 328,
        page_end: 329,
        dates: [{ year: 1948, month: 12, day: 4 }],
        is_range_date: false,
      },
      {
        title: '六纵应加强阻击李延年北进',
        authors: ['毛泽东'],
        page_start: 330,
        page_end: 330,
        dates: [{ year: 1948, month: 12, day: 4 }],
        is_range_date: false,
      },
      {
        title: '对一个美国记者在香港的谈话材料“的批语',
        authors: ['毛泽东'],
        page_start: 331,
        page_end: 331,
        dates: [{ year: 1948, month: 12, day: 4 }],
        is_range_date: false,
      },
      {
        title: '给刘少奇等的信',
        authors: ['毛泽东'],
        page_start: 332,
        page_end: 332,
        dates: [{ year: 1948, month: 12, day: 4 }],
        is_range_date: false,
      },
      {
        title: '为防止蚌埠敌人威肪应构筑多层坚强防御阵地',
        authors: ['毛泽东'],
        page_start: 333,
        page_end: 333,
        dates: [{ year: 1948, month: 12, day: 5 }],
        is_range_date: false,
      },
      {
        title: '对怀来敌如何攻击依情况决定',
        authors: ['毛泽东'],
        page_start: 334,
        page_end: 335,
        dates: [{ year: 1948, month: 12, day: 5 }],
        is_range_date: false,
      },
      {
        title: '阻止可能从张家口西逃之敌',
        authors: ['毛泽东'],
        page_start: 336,
        page_end: 336,
        dates: [{ year: 1948, month: 12, day: 5 }],
        is_range_date: false,
      },
      {
        title: '关于杨李部部署的指示电',
        authors: ['毛泽东'],
        page_start: 337,
        page_end: 338,
        dates: [{ year: 1948, month: 12, day: 6 }],
        is_range_date: false,
      },
      {
        title: '围轩张家口宣化怀来诸敌的部署叫',
        authors: ['毛泽东'],
        page_start: 339,
        page_end: 341,
        dates: [{ year: 1948, month: 12, day: 6 }],
        is_range_date: false,
      },
      {
        title: '占领徐州及齐故情况的通报则',
        authors: ['毛泽东'],
        page_start: 342,
        page_end: 343,
        dates: [{ year: 1948, month: 12, day: 6 }],
        is_range_date: false,
      },
      {
        title: '全力堵追张家口宣化向东突围之敌',
        authors: ['毛泽东'],
        page_start: 344,
        page_end: 344,
        dates: [{ year: 1948, month: 12, day: 7 }],
        is_range_date: false,
      },
      {
        title: '程黄部协助杨罗耿歼灭东逃之敌',
        authors: ['毛泽东'],
        page_start: 345,
        page_end: 346,
        dates: [{ year: 1948, month: 12, day: 7 }],
        is_range_date: false,
      },
      {
        title: '华北部队应遵军委命令阻敌东逃',
        authors: ['毛泽东'],
        page_start: 347,
        page_end: 348,
        dates: [{ year: 1948, month: 12, day: 7 }],
        is_range_date: false,
      },
      {
        title: '务将三十五军与怀来联系完全切断',
        authors: ['毛泽东'],
        page_start: 349,
        page_end: 349,
        dates: [{ year: 1948, month: 12, day: 8 }],
        is_range_date: false,
      },
      {
        title: '准备隔断平津，包围唐山，开击芦台塘活之敌',
        authors: ['毛泽东'],
        page_start: 350,
        page_end: 353,
        dates: [{ year: 1948, month: 12, day: 8 }],
        is_range_date: false,
      },
      {
        title: '如东进追敌来不及则以八纵等协助包围张培',
        authors: ['毛泽东'],
        page_start: 354,
        page_end: 355,
        dates: [{ year: 1948, month: 12, day: 8 }],
        is_range_date: false,
      },
      {
        title: '杨成武部应以全力包围张家口之敌',
        authors: ['毛泽东'],
        page_start: 356,
        page_end: 356,
        dates: [{ year: 1948, month: 12, day: 8 }],
        is_range_date: false,
      },
      {
        title: '对新保安张家口之敌采取长围久困待命攻击之方针',
        authors: ['毛泽东'],
        page_start: 357,
        page_end: 358,
        dates: [{ year: 1948, month: 12, day: 8 }],
        is_range_date: false,
      },
      {
        title: '关于齐灭怀来之敌的指示电',
        authors: ['毛泽东'],
        page_start: 359,
        page_end: 359,
        dates: [{ year: 1948, month: 12, day: 9 }],
        is_range_date: false,
      },
      {
        title: '东北部队以三五两纵威肤北平钳制敌人',
        authors: ['毛泽东'],
        page_start: 360,
        page_end: 361,
        dates: [{ year: 1948, month: 12, day: 10 }],
        is_range_date: false,
      },
      {
        title: '歼灭一〇四军的作战应力求迅速',
        authors: ['毛泽东'],
        page_start: 362,
        page_end: 363,
        dates: [{ year: 1948, month: 12, day: 10 }],
        is_range_date: false,
      },
      {
        title: '复何基洋、张克侠电',
        authors: ['毛泽东'],
        page_start: 364,
        page_end: 364,
        dates: [{ year: 1948, month: 12, day: 10 }],
        is_range_date: false,
      },
      {
        title: '迅速构筑阻击阵地务使各敌不能逃脱',
        authors: ['毛泽东'],
        page_start: 365,
        page_end: 366,
        dates: [{ year: 1948, month: 12, day: 10 }],
        is_range_date: false,
      },
      {
        title: '关于平津地区的形势及部署',
        authors: ['毛泽东'],
        page_start: 367,
        page_end: 368,
        dates: [{ year: 1948, month: 12, day: 11 }],
        is_range_date: false,
      },
      {
        title: '关于平津战役的作战方针',
        authors: ['毛泽东'],
        page_start: 369,
        page_end: 373,
        dates: [{ year: 1948, month: 12, day: 11 }],
        is_range_date: false,
      },
      {
        title: '关于五纵三纵十级的部署',
        authors: ['毛泽东'],
        page_start: 374,
        page_end: 374,
        dates: [{ year: 1948, month: 12, day: 11 }],
        is_range_date: false,
      },
      {
        title: '确实围住三十五军全力防敌突围',
        authors: ['毛泽东'],
        page_start: 375,
        page_end: 375,
        dates: [{ year: 1948, month: 12, day: 11 }],
        is_range_date: false,
      },
      {
        title: '杨成武部须准备打退敌人多次进攻',
        authors: ['毛泽东'],
        page_start: 376,
        page_end: 376,
        dates: [{ year: 1948, month: 12, day: 11 }],
        is_range_date: false,
      },
      {
        title: '三纵到北平以东可试图切断平津路叫',
        authors: ['毛泽东'],
        page_start: 377,
        page_end: 377,
        dates: [{ year: 1948, month: 12, day: 11 }],
        is_range_date: false,
      },
      {
        title: '华北部队应归林罗刘谭统一指挥',
        authors: ['毛泽东'],
        page_start: 378,
        page_end: 378,
        dates: [{ year: 1948, month: 12, day: 11 }],
        is_range_date: false,
      },
      {
        title: '同意以程黄两纵及五纱包围南口昌平之敌',
        authors: ['毛泽东'],
        page_start: 379,
        page_end: 380,
        dates: [{ year: 1948, month: 12, day: 11 }],
        is_range_date: false,
      },
      {
        title: '同意迅速包围南口昌平唐山等敌',
        authors: ['毛泽东'],
        page_start: 381,
        page_end: 381,
        dates: [{ year: 1948, month: 12, day: 12 }],
        is_range_date: false,
      },
      {
        title: '包围通县之敌切断平津联系',
        authors: ['毛泽东'],
        page_start: 382,
        page_end: 382,
        dates: [{ year: 1948, month: 12, day: 12 }],
        is_range_date: false,
      },
      {
        title: '对今后作战方针的意见',
        authors: ['毛泽东'],
        page_start: 383,
        page_end: 385,
        dates: [{ year: 1948, month: 12, day: 12 }],
        is_range_date: false,
      },
      {
        title: '防止北平通县敌人逃跑',
        authors: ['毛泽东'],
        page_start: 386,
        page_end: 387,
        dates: [{ year: 1948, month: 12, day: 13 }],
        is_range_date: false,
      },
      {
        title: '巩固地控制南口八达岭一带',
        authors: ['毛泽东'],
        page_start: 388,
        page_end: 388,
        dates: [{ year: 1948, month: 12, day: 13 }],
        is_range_date: false,
      },
      {
        title: '迅速包围塘活以防平津等故从海上逃跑',
        authors: ['毛泽东'],
        page_start: 389,
        page_end: 389,
        dates: [{ year: 1948, month: 12, day: 13 }],
        is_range_date: false,
      },
      {
        title: '准备阻击可能由天津经济南向青岛逃跑之敌',
        authors: ['毛泽东'],
        page_start: 390,
        page_end: 390,
        dates: [{ year: 1948, month: 12, day: 13 }],
        is_range_date: false,
      },
      {
        title: '牙灭津塘线之敌然后控制海口叫',
        authors: ['毛泽东'],
        page_start: 391,
        page_end: 391,
        dates: [{ year: 1948, month: 12, day: 13 }],
        is_range_date: false,
      },
      {
        title: '堵住北平通县天津之敌的退路叫',
        authors: ['毛泽东'],
        page_start: 392,
        page_end: 393,
        dates: [{ year: 1948, month: 12, day: 13 }],
        is_range_date: false,
      },
      {
        title: '中央军委关于准备接收北平、天津、唐山的指示',
        authors: ['毛泽东'],
        page_start: 394,
        page_end: 395,
        dates: [{ year: 1948, month: 12, day: 13 }],
        is_range_date: false,
      },
      {
        title: '全力阻击延退敌人南逃',
        authors: ['毛泽东'],
        page_start: 396,
        page_end: 396,
        dates: [{ year: 1948, month: 12, day: 13 }],
        is_range_date: false,
      },
      {
        title: '从东南面包围北平之敌',
        authors: ['毛泽东'],
        page_start: 397,
        page_end: 399,
        dates: [{ year: 1948, month: 12, day: 13 }],
        is_range_date: false,
      },
      {
        title: '四纵应留南口八达岭防御',
        authors: ['毛泽东'],
        page_start: 400,
        page_end: 400,
        dates: [{ year: 1948, month: 12, day: 14 }],
        is_range_date: false,
      },
      {
        title: '制弃杜事明邱清泉李弥的各纵只作防御不作攻击',
        authors: ['毛泽东'],
        page_start: 401,
        page_end: 401,
        dates: [{ year: 1948, month: 12, day: 14 }],
        is_range_date: false,
      },
      {
        title: '加厚对北平东南的阻击兵方',
        authors: ['毛泽东'],
        page_start: 402,
        page_end: 403,
        dates: [{ year: 1948, month: 12, day: 15 }],
        is_range_date: false,
      },
      {
        title: '攻击三十五军需在完成对平津包围之后叫',
        authors: ['毛泽东'],
        page_start: 404,
        page_end: 404,
        dates: [{ year: 1948, month: 12, day: 15 }],
        is_range_date: false,
      },
      {
        title: '致林彪、罗荣柜、刘亚楼等电',
        authors: ['毛泽东'],
        page_start: 405,
        page_end: 405,
        dates: [{ year: 1948, month: 12, day: 15 }],
        is_range_date: false,
      },
      {
        title: '华北第二第三兵团归林罗刘直接指挥',
        authors: ['毛泽东'],
        page_start: 406,
        page_end: 406,
        dates: [{ year: 1948, month: 12, day: 16 }],
        is_range_date: false,
      },
      {
        title: '准备增加包围张家口的兵方',
        authors: ['毛泽东'],
        page_start: 407,
        page_end: 408,
        dates: [{ year: 1948, month: 12, day: 16 }],
        is_range_date: false,
      },
      {
        title: '抽调两个旅参加夺取张家口战役',
        authors: ['毛泽东'],
        page_start: 409,
        page_end: 409,
        dates: [{ year: 1948, month: 12, day: 16 }],
        is_range_date: false,
      },
      {
        title: '向杜事明邱清泉李弥部连续进行政治攻势',
        authors: ['毛泽东'],
        page_start: 410,
        page_end: 410,
        dates: [{ year: 1948, month: 12, day: 16 }],
        is_range_date: false,
      },
      {
        title: '同意林罗刘的军事部署意见叫',
        authors: ['毛泽东'],
        page_start: 411,
        page_end: 411,
        dates: [{ year: 1948, month: 12, day: 16 }],
        is_range_date: false,
      },
      {
        title: '致林彪、罗荣柜、刘亚楼电',
        authors: ['毛泽东'],
        page_start: 412,
        page_end: 412,
        dates: [{ year: 1948, month: 12, day: 16 }],
        is_range_date: false,
      },
      {
        title: '华北军一兵团不要去张家口叫',
        authors: ['毛泽东'],
        page_start: 413,
        page_end: 413,
        dates: [{ year: 1948, month: 12, day: 17 }],
        is_range_date: false,
      },
      {
        title: '应继续攻歼尚义一带之敌',
        authors: ['毛泽东'],
        page_start: 414,
        page_end: 414,
        dates: [{ year: 1948, month: 12, day: 17 }],
        is_range_date: false,
      },
      {
        title: '约在明年一月正式攻击天津北平张家口之敌',
        authors: ['毛泽东'],
        page_start: 415,
        page_end: 416,
        dates: [{ year: 1948, month: 12, day: 17 }],
        is_range_date: false,
      },
      {
        title: '充分注意保护北平工业及重要文化古选',
        authors: ['毛泽东'],
        page_start: 417,
        page_end: 417,
        dates: [{ year: 1948, month: 12, day: 17 }],
        is_range_date: false,
      },
      {
        title: '教促杜事明等投降书叫',
        authors: ['毛泽东'],
        page_start: 418,
        page_end: 420,
        dates: [{ year: 1948, month: 12, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致刘伯承、陈毅、邓小平电',
        authors: ['毛泽东'],
        page_start: 421,
        page_end: 421,
        dates: [{ year: 1948, month: 12, day: 17 }],
        is_range_date: false,
      },
      {
        title: '迅速切断天津与新河塘活等处联系',
        authors: ['毛泽东'],
        page_start: 422,
        page_end: 423,
        dates: [{ year: 1948, month: 12, day: 18 }],
        is_range_date: false,
      },
      {
        title: '四纵速至张家口西面办同华北第三兵团培弃逃敌',
        authors: ['毛泽东'],
        page_start: 424,
        page_end: 424,
        dates: [{ year: 1948, month: 12, day: 18 }],
        is_range_date: false,
      },
      {
        title: '密切注视胡宗南部动向',
        authors: ['毛泽东'],
        page_start: 425,
        page_end: 426,
        dates: [{ year: 1948, month: 12, day: 18 }],
        is_range_date: false,
      },
      {
        title: '致高岗等电',
        authors: ['毛泽东'],
        page_start: 427,
        page_end: 427,
        dates: [{ year: 1948, month: 12, day: 18 }],
        is_range_date: false,
      },
      {
        title: '关于平缓线上的作战计划',
        authors: ['毛泽东'],
        page_start: 428,
        page_end: 429,
        dates: [{ year: 1948, month: 12, day: 19 }],
        is_range_date: false,
      },
      {
        title: '调查能否炮击塘沽口岸敌船则',
        authors: ['毛泽东'],
        page_start: 430,
        page_end: 430,
        dates: [{ year: 1948, month: 12, day: 19 }],
        is_range_date: false,
      },
      {
        title: '关于日前解放区农村妇女工作的决定',
        authors: ['毛泽东'],
        page_start: 431,
        page_end: 439,
        dates: [{ year: 1948, month: 12, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致林彪、罗荣柜、刘亚楼电',
        authors: ['毛泽东'],
        page_start: 440,
        page_end: 440,
        dates: [{ year: 1948, month: 12, day: 20 }],
        is_range_date: false,
      },
      {
        title: '中原野战军各纵待李延年北进时担任南线防御',
        authors: ['毛泽东'],
        page_start: 441,
        page_end: 442,
        dates: [{ year: 1948, month: 12, day: 21 }],
        is_range_date: false,
      },
      {
        title: '军事攻势与政治攻势同时并举叫',
        authors: ['毛泽东'],
        page_start: 443,
        page_end: 444,
        dates: [{ year: 1948, month: 12, day: 21 }],
        is_range_date: false,
      },
      {
        title: '复廖运周等电',
        authors: ['毛泽东'],
        page_start: 445,
        page_end: 445,
        dates: [{ year: 1948, month: 12, day: 21 }],
        is_range_date: false,
      },
      {
        title: '立即将大部厚房补人部队',
        authors: ['毛泽东'],
        page_start: 446,
        page_end: 446,
        dates: [{ year: 1948, month: 12, day: 22 }],
        is_range_date: false,
      },
      {
        title: '华东野战军全军可多休整数日',
        authors: ['毛泽东'],
        page_start: 447,
        page_end: 447,
        dates: [{ year: 1948, month: 12, day: 22 }],
        is_range_date: false,
      },
      {
        title: '暂时不必普遍立条例',
        authors: ['毛泽东'],
        page_start: 448,
        page_end: 448,
        dates: [{ year: 1948, month: 12, day: 22 }],
        is_range_date: false,
      },
      {
        title: '致林彪、罗荣柜、刘亚楼电',
        authors: ['毛泽东'],
        page_start: 449,
        page_end: 449,
        dates: [{ year: 1948, month: 12, day: 23 }],
        is_range_date: false,
      },
      {
        title: '包围大同归绥之敌',
        authors: ['毛泽东'],
        page_start: 450,
        page_end: 450,
        dates: [{ year: 1948, month: 12, day: 24 }],
        is_range_date: false,
      },
      {
        title: '自前不要忙于包围胡宗南军',
        authors: ['毛泽东'],
        page_start: 451,
        page_end: 452,
        dates: [{ year: 1948, month: 12, day: 24 }],
        is_range_date: false,
      },
      {
        title: '庆祝张家口的伟大胜利',
        authors: ['毛泽东'],
        page_start: 453,
        page_end: 453,
        dates: [{ year: 1948, month: 12, day: 24 }],
        is_range_date: false,
      },
      {
        title: '防止天津敌人向南突围',
        authors: ['毛泽东'],
        page_start: 454,
        page_end: 454,
        dates: [{ year: 1948, month: 12, day: 25 }],
        is_range_date: false,
      },
      {
        title: '陕北某权威人士谈战犯名单问题',
        authors: ['毛泽东'],
        page_start: 455,
        page_end: 455,
        dates: [{ year: 1948, month: 12, day: 25 }],
        is_range_date: false,
      },
      {
        title: '攻击塘活时间推退至下月上句为宜',
        authors: ['毛泽东'],
        page_start: 456,
        page_end: 456,
        dates: [{ year: 1948, month: 12, day: 26 }],
        is_range_date: false,
      },
      {
        title: '推退攻击两活，严防平津两敌突围',
        authors: ['毛泽东'],
        page_start: 457,
        page_end: 458,
        dates: [{ year: 1948, month: 12, day: 26 }],
        is_range_date: false,
      },
      {
        title: '迅速控制卢沟桥静海等处防敌南逃',
        authors: ['毛泽东'],
        page_start: 459,
        page_end: 459,
        dates: [{ year: 1948, month: 12, day: 26 }],
        is_range_date: false,
      },
      {
        title: '准备堵击平津南逃之敌',
        authors: ['毛泽东'],
        page_start: 460,
        page_end: 460,
        dates: [{ year: 1948, month: 12, day: 26 }],
        is_range_date: false,
      },
      {
        title: '南方游击区应注意的几个问题',
        authors: ['毛泽东'],
        page_start: 461,
        page_end: 462,
        dates: [{ year: 1948, month: 12, day: 27 }],
        is_range_date: false,
      },
      {
        title: '如傅作义南逃华北第一兵团三个纵队应到石家庄堵击',
        authors: ['毛泽东'],
        page_start: 463,
        page_end: 463,
        dates: [{ year: 1948, month: 12, day: 27 }],
        is_range_date: false,
      },
      {
        title: '我们应对民主人士采取保护政策',
        authors: ['毛泽东'],
        page_start: 464,
        page_end: 464,
        dates: [{ year: 1948, month: 12, day: 27 }],
        is_range_date: false,
      },
      {
        title: '给刘少奇等的信',
        authors: ['毛泽东'],
        page_start: 465,
        page_end: 465,
        dates: [{ year: 1948, month: 12, day: 27 }],
        is_range_date: false,
      },
      {
        title: '关于攻击太原所需兵力的问题',
        authors: ['毛泽东'],
        page_start: 466,
        page_end: 466,
        dates: [{ year: 1948, month: 12, day: 28 }],
        is_range_date: false,
      },
      {
        title: '加强对被围之敌的政治攻势',
        authors: ['毛泽东'],
        page_start: 467,
        page_end: 468,
        dates: [{ year: 1948, month: 12, day: 28 }],
        is_range_date: false,
      },
      {
        title: '同意调两杨兵团参加平津会战',
        authors: ['毛泽东'],
        page_start: 469,
        page_end: 469,
        dates: [{ year: 1948, month: 12, day: 28 }],
        is_range_date: false,
      },
      {
        title: '放弃两沽集中夺取天津',
        authors: ['毛泽东'],
        page_start: 470,
        page_end: 470,
        dates: [{ year: 1948, month: 12, day: 29 }],
        is_range_date: false,
      },
      {
        title: '同意杨罗耿部参战及军事部署叫',
        authors: ['毛泽东'],
        page_start: 471,
        page_end: 471,
        dates: [{ year: 1948, month: 12, day: 30 }],
        is_range_date: false,
      },
      {
        title: '将革命进行到底',
        authors: ['毛泽东'],
        page_start: 472,
        page_end: 485,
        dates: [{ year: 1948, month: 12, day: 30 }],
        is_range_date: false,
      },
      {
        title: '各军原地休息然后渡江南进',
        authors: ['毛泽东'],
        page_start: 486,
        page_end: 486,
        dates: [{ year: 1948, month: 12, day: 31 }],
        is_range_date: false,
      },
      {
        title: '为新华书店题名',
        authors: ['毛泽东'],
        page_start: 487,
        page_end: 487,
        dates: [{ year: 1948, month: 12 }],
        is_range_date: false,
      },
      {
        title: '为《人民邮电》题写报头',
        authors: ['毛泽东'],
        page_start: 488,
        page_end: 489,
        dates: [{ year: 1948, month: 12 }],
        is_range_date: false,
      },
      {
        title: '为革命母亲夏娘娘“八十寿辰题词',
        authors: ['毛泽东'],
        page_start: 490,
        page_end: 490,
        dates: [{ year: 1948 }],
        is_range_date: false,
      },
      {
        title: '为华北大学·题名',
        authors: ['毛泽东'],
        page_start: 491,
        page_end: 494,
        dates: [{ year: 1948 }],
        is_range_date: false,
      },
      {
        title: '复林彪电',
        authors: ['毛泽东'],
        page_start: 495,
        page_end: 496,
        dates: [{ year: 1949, month: 1, day: 1 }],
        is_range_date: false,
      },
      {
        title: '致林彪电',
        authors: ['毛泽东'],
        page_start: 497,
        page_end: 497,
        dates: [{ year: 1949, month: 1, day: 3 }],
        is_range_date: false,
      },
      {
        title: '评战犯求和',
        authors: ['毛泽东'],
        page_start: 498,
        page_end: 501,
        dates: [{ year: 1949, month: 1, day: 4 }],
        is_range_date: false,
      },
      {
        title: '对孤守工厂区敌军可劝降以减少破坏',
        authors: ['毛泽东'],
        page_start: 502,
        page_end: 502,
        dates: [{ year: 1949, month: 1, day: 6 }],
        is_range_date: false,
      },
      {
        title: '攻天津时需特别注意学校',
        authors: ['毛泽东'],
        page_start: 503,
        page_end: 504,
        dates: [{ year: 1949, month: 1, day: 6 }],
        is_range_date: false,
      },
      {
        title: '中共中央关于欢迎民主人士工作致东北局、李富春、洛甫电',
        authors: ['毛泽东'],
        page_start: 505,
        page_end: 506,
        dates: [{ year: 1949, month: 1, day: 6 }],
        is_range_date: false,
      },
      {
        title: '复林彪电',
        authors: ['毛泽东'],
        page_start: 507,
        page_end: 507,
        dates: [{ year: 1949, month: 1, day: 7 }],
        is_range_date: false,
      },
      {
        title: '致林彪电',
        authors: ['毛泽东'],
        page_start: 508,
        page_end: 508,
        dates: [{ year: 1949, month: 1, day: 7 }],
        is_range_date: false,
      },
      {
        title: '目前形势和党在一九四九年的任务',
        authors: ['毛泽东'],
        page_start: 509,
        page_end: 515,
        dates: [{ year: 1949, month: 1, day: 8 }],
        is_range_date: false,
      },
      {
        title: '复林彪、鼓荣臻电',
        authors: ['毛泽东'],
        page_start: 516,
        page_end: 516,
        dates: [{ year: 1949, month: 1, day: 9 }],
        is_range_date: false,
      },
      {
        title: '中央决定林彪罗荣柜慧荣臻组织总前委叫',
        authors: ['毛泽东'],
        page_start: 517,
        page_end: 518,
        dates: [{ year: 1949, month: 1, day: 10 }],
        is_range_date: false,
      },
      {
        title: '在中共中央对普绥分局关于党代会以后综合报告上写的批注',
        authors: ['毛泽东'],
        page_start: 519,
        page_end: 519,
        dates: [{ year: 1949, month: 1, day: 10 }],
        is_range_date: false,
      },
      {
        title: '致林彪、鼓荣臻电',
        authors: ['毛泽东'],
        page_start: 520,
        page_end: 520,
        dates: [{ year: 1949, month: 1, day: 11 }],
        is_range_date: false,
      },
      {
        title: '复林彪、鼓荣臻电',
        authors: ['毛泽东'],
        page_start: 521,
        page_end: 521,
        dates: [{ year: 1949, month: 1, day: 11 }],
        is_range_date: false,
      },
      {
        title: '对付天津守敌的方针',
        authors: ['毛泽东'],
        page_start: 522,
        page_end: 522,
        dates: [{ year: 1949, month: 1, day: 12 }],
        is_range_date: false,
      },
      {
        title: '华东野战军中原野战车接部署休整完成渡江作战准备',
        authors: ['毛泽东'],
        page_start: 523,
        page_end: 523,
        dates: [{ year: 1949, month: 1, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致林彪、鼓荣臻电',
        authors: ['毛泽东'],
        page_start: 524,
        page_end: 524,
        dates: [{ year: 1949, month: 1, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致东北局电',
        authors: ['毛泽东'],
        page_start: 525,
        page_end: 525,
        dates: [{ year: 1949, month: 1, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致各中央局等电',
        authors: ['毛泽东'],
        page_start: 526,
        page_end: 526,
        dates: [{ year: 1949, month: 1, day: 14 }],
        is_range_date: false,
      },
      {
        title: '中共中央毛泽东主席关于时局的声明',
        authors: ['毛泽东'],
        page_start: 527,
        page_end: 531,
        dates: [{ year: 1949, month: 1, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致各中央局等电',
        authors: ['毛泽东'],
        page_start: 532,
        page_end: 532,
        dates: [{ year: 1949, month: 1, day: 15 }],
        is_range_date: false,
      },
      {
        title: '致博作义公函',
        authors: ['毛泽东'],
        page_start: 533,
        page_end: 533,
        dates: [{ year: 1949, month: 1, day: 15 }],
        is_range_date: false,
      },
      {
        title: '复林彪等电',
        authors: ['毛泽东'],
        page_start: 534,
        page_end: 534,
        dates: [{ year: 1949, month: 1, day: 15 }],
        is_range_date: false,
      },
      {
        title: '同傅作义部谈判的补充意见和积极作好攻城准备问题',
        authors: ['毛泽东'],
        page_start: 535,
        page_end: 536,
        dates: [{ year: 1949, month: 1, day: 16 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 537,
        page_end: 537,
        dates: [{ year: 1949, month: 1, day: 16 }],
        is_range_date: false,
      },
      {
        title: '注意防止北平敌人突围',
        authors: ['毛泽东'],
        page_start: 538,
        page_end: 538,
        dates: [{ year: 1949, month: 1, day: 17 }],
        is_range_date: false,
      },
      {
        title: '复斯大林电',
        authors: ['毛泽东'],
        page_start: 539,
        page_end: 539,
        dates: [{ year: 1949, month: 1, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致华东、中原两野战军首长等电',
        authors: ['毛泽东'],
        page_start: 540,
        page_end: 544,
        dates: [{ year: 1949, month: 1, day: 17 }],
        is_range_date: false,
      },
      {
        title: '不允许任何外国及联合国干涉中国内政',
        authors: ['毛泽东'],
        page_start: 545,
        page_end: 546,
        dates: [{ year: 1949, month: 1, day: 19 }],
        is_range_date: false,
      },
    ],
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives8/maoquanji25.pdf',
};
