export default {
  entity: {
    id: 'maoquanji29',
    name: '毛泽东全集第29卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives0/main/maoquanji29.pdf',
  },
  parser_option: {
    page_limits: [],
    articles: [
      {
        page_start: 38,
        page_end: 38,
        title: '给吴启瑞的信',
        dates: [{ year: 1950, month: 7, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 40,
        page_end: 41,
        title: '关于苏联来华之空军师的驻地和我空军混成旅改装训练问题',
        dates: [{ year: 1950, month: 7, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 42,
        page_end: 43,
        title: '要根治淮河',
        dates: [
          { year: 1950, month: 7 },
          { year: 1950, month: 9 },
        ],
        is_range_date: true,
        authors: ['毛泽东'],
      },
      {
        page_start: 45,
        page_end: 45,
        title: '中央转发北京市委关于整风工作报告的批语',
        dates: [{ year: 1950, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 46,
        page_end: 46,
        title: '同意华东军区对金门岛敌情的判断与截击部署',
        dates: [{ year: 1950, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 47,
        page_end: 47,
        title: '关于东北边防军统由东北军区指挥与供应的批语',
        dates: [{ year: 1950, month: 7, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 48,
        page_end: 48,
        title: '反对南非联邦政府的“种族隔离法案',
        dates: [{ year: 1950, month: 7, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 49,
        page_end: 49,
        title: '应先打小仗然后才有可能打较大的仗',
        dates: [{ year: 1950, month: 7, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 50,
        page_end: 50,
        title: '同意四十三军的集结位置',
        dates: [{ year: 1950, month: 7, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 51,
        page_end: 52,
        title: '关于炮兵观察队赴朝鲜前线考察问题的批语',
        dates: [{ year: 1950, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 53,
        page_end: 53,
        title: '为《美洲华侨日报》创刊十周年题词',
        dates: [{ year: 1950, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 55,
        page_end: 55,
        title: '为中央民族访问团题词',
        dates: [{ year: 1950, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 57,
        page_end: 57,
        title: '为《新体育》杂志题名',
        dates: [{ year: 1950, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 58,
        page_end: 58,
        title: '为《西江报》题写报头',
        dates: [{ year: 1950, month: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 59,
        page_end: 62,
        title: '军委关于在军队中实施文化教育的指示',
        dates: [{ year: 1950, month: 8, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 63,
        page_end: 63,
        title: '关于从班禅集团选择适当人员参加西北军政委员会工作的电报',
        dates: [{ year: 1950, month: 8, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 64,
        page_end: 64,
        title: '关于钱昌照建议的批语',
        dates: [{ year: 1950, month: 8, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 65,
        page_end: 65,
        title: '军委转发十九兵团复员工作报告的批语',
        dates: [{ year: 1950, month: 8, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 66,
        page_end: 67,
        title: '东北边防军应在月内完成一切作战准备',
        dates: [{ year: 1950, month: 8, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 68,
        page_end: 68,
        title: '给黄炎培的信',
        dates: [{ year: 1950, month: 8, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 69,
        page_end: 69,
        title: '中央转发中南局关于不要强调组织生产互助组指示的批语',
        dates: [{ year: 1950, month: 8, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 70,
        page_end: 70,
        title: '关于公开批评宣化市错误问题的批语',
        dates: [{ year: 1950, month: 8, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 71,
        page_end: 72,
        title: '对中财委关于全国进出口会议情况摘报的批语',
        dates: [{ year: 1950, month: 8, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 73,
        page_end: 73,
        title: '接受缅甸驻华大使吴敏登呈递国书时的答词',
        dates: [{ year: 1950, month: 8, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 75,
        page_end: 75,
        title: '为第一届全国卫生工作会议题词',
        dates: [{ year: 1950, month: 8, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 77,
        page_end: 77,
        title: '在一封反映大学毕业生分配中学用不一致问题来信上的批语',
        dates: [{ year: 1950, month: 8, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 78,
        page_end: 78,
        title: '给栗裕的信',
        dates: [{ year: 1950, month: 8, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 80,
        page_end: 80,
        title: '中央转发北京市委关于区人民代表会议经验的初步总结的批语',
        dates: [{ year: 1950, month: 8, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 81,
        page_end: 81,
        title: '给蒋竹如的信',
        dates: [{ year: 1950, month: 8, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 82,
        page_end: 83,
        title: '关于华东军区工作的指示',
        dates: [{ year: 1950, month: 8, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 84,
        page_end: 84,
        title: '对中央关于调整若干工作关系问题的指示草案的批语',
        dates: [{ year: 1950, month: 8, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 85,
        page_end: 86,
        title: '同意周恩来拟同印度驻华大使会谈的内容',
        dates: [{ year: 1950, month: 8, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 87,
        page_end: 87,
        title: '关于边防军务必在九月底以前完成一切作战准备致高岗电',
        dates: [{ year: 1950, month: 8, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 88,
        page_end: 88,
        title: '询问向昌都进军的几个问题',
        dates: [{ year: 1950, month: 8, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 89,
        page_end: 89,
        title: '对王明来信的批语',
        dates: [{ year: 1950, month: 8, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 90,
        page_end: 90,
        title: '中央转发华东局关于组织人民法庭指示的批语',
        dates: [{ year: 1950, month: 8, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 91,
        page_end: 91,
        title: '对上海党政群机关团体编制情况报告的批语',
        dates: [{ year: 1950, month: 8, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 92,
        page_end: 92,
        title: '给徐海东的信',
        dates: [{ year: 1950, month: 8, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 94,
        page_end: 94,
        title: '对配备第二线兵力报告的批语',
        dates: [{ year: 1950, month: 8, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 95,
        page_end: 96,
        title: '力争今年占领昌都明年进军拉萨',
        dates: [{ year: 1950, month: 8, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 97,
        page_end: 98,
        title: '尽快筹备进军西藏所需高空运输机',
        dates: [
          { year: 1950, month: 8, day: 23 },
          { year: 1950, month: 8, day: 24 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 99,
        page_end: 99,
        title: '给夏百源的信',
        dates: [{ year: 1950, month: 8, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 100,
        page_end: 100,
        title: '给李漱清的信',
        dates: [{ year: 1950, month: 8, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 101,
        page_end: 101,
        title: '给蒋浩然的信',
        dates: [{ year: 1950, month: 8, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 102,
        page_end: 102,
        title: '给罗石泉的信',
        dates: [{ year: 1950, month: 8, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 103,
        page_end: 104,
        title: '边界战役须有连续作战的思想',
        dates: [{ year: 1950, month: 8, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 105,
        page_end: 105,
        title: '准备对付敌军可能向潮汕及海陆丰登陆袭击',
        dates: [{ year: 1950, month: 8, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 106,
        page_end: 106,
        title: '中央转发西北局关于整风经验报告的批语',
        dates: [{ year: 1950, month: 8, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 107,
        page_end: 107,
        title: '给徐悲鸿的信',
        dates: [{ year: 1950, month: 8, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 108,
        page_end: 108,
        title: '帮助越南训练和装备新兵',
        dates: [{ year: 1950, month: 8, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 110,
        page_end: 110,
        title: '中央关于中央局负责人来京开会的通知',
        dates: [{ year: 1950, month: 8, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 111,
        page_end: 111,
        title: '须集中十二个军以便机动',
        dates: [{ year: 1950, month: 8, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 112,
        page_end: 112,
        title: '对选派干部去朝鲜战场了解情况报告的批语',
        dates: [{ year: 1950, month: 8, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 113,
        page_end: 114,
        title: '对华东局关于整理华东各级党刊的决定的批语',
        dates: [{ year: 1950, month: 8, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 115,
        page_end: 115,
        title: '关于希望西藏代表团九月中旬到京谈判的批语',
        dates: [{ year: 1950, month: 8, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 116,
        page_end: 116,
        title: '关于催促西藏代表团马上动身来京的批语',
        dates: [{ year: 1950, month: 8, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 117,
        page_end: 117,
        title: '给陈寄生的信',
        dates: [{ year: 1950, month: 8, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 118,
        page_end: 118,
        title: '给郭梓材的信',
        dates: [{ year: 1950, month: 8, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 119,
        page_end: 119,
        title: '给越南民主政府的贺电',
        dates: [{ year: 1950, month: 8, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 120,
        page_end: 120,
        title: '给谭世瑛的信',
        dates: [{ year: 1950, month: 8, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 121,
        page_end: 123,
        title: '对当前工作的指示',
        dates: [{ year: 1950, month: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 125,
        page_end: 125,
        title: '保密问题值得引起我们极大注意',
        dates: [{ year: 1950, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 126,
        page_end: 126,
        title: '关于中央系统整风工作领导问题的批语',
        dates: [{ year: 1950, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 127,
        page_end: 127,
        title: '给黄炎培的信',
        dates: [{ year: 1950, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 128,
        page_end: 131,
        title: '对东北边防军准备工作等问题报告的批语和复信',
        dates: [
          { year: 1950, month: 9, day: 1 },
          { year: 1950, month: 9, day: 3 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 132,
        page_end: 134,
        title: '朝鲜战局和我们的方针',
        dates: [{ year: 1950, month: 9, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 135,
        page_end: 135,
        title: '关于中国基督教会三自宣言签名运动的批语',
        dates: [{ year: 1950, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 136,
        page_end: 136,
        title: '九兵团全部开到徐济线整训',
        dates: [{ year: 1950, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 137,
        page_end: 138,
        title: '请周恩来约谈柴君武指示任务和方法',
        dates: [{ year: 1950, month: 9, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 139,
        page_end: 139,
        title: '中央转发川南区党委关于整风情况报告的批语',
        dates: [{ year: 1950, month: 9, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 140,
        page_end: 141,
        title: '中宣部转发东北局关于学校整风的指示的批语',
        dates: [{ year: 1950, month: 9, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 142,
        page_end: 142,
        title: '中央转发河南淮阳地区夏季征粮情况报告的批语',
        dates: [{ year: 1950, month: 9, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 143,
        page_end: 143,
        title: '关于失业工人救济问题的批语',
        dates: [{ year: 1950, month: 9, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 144,
        page_end: 144,
        title: '开展连队民主运动加强战斗力',
        dates: [{ year: 1950, month: 9, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 145,
        page_end: 147,
        title: '在一封匿名信上的批语',
        dates: [{ year: 1950, month: 9, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 148,
        page_end: 148,
        title: '关于整党中应注意检查统一战线工作的批语',
        dates: [{ year: 1950, month: 9, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 149,
        page_end: 149,
        title: '给陈郁的信',
        dates: [{ year: 1950, month: 9, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 151,
        page_end: 151,
        title: '对关于铁道兵团领导关系报告的批语',
        dates: [{ year: 1950, month: 9, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 152,
        page_end: 152,
        title: '中央转发河北省政府直属机关整风经验的批语',
        dates: [{ year: 1950, month: 9, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 153,
        page_end: 153,
        title: '中央转发华北局关于改造绥远起义部队的报告的批语',
        dates: [{ year: 1950, month: 9, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 154,
        page_end: 154,
        title: '关于检查督促政府各部门向中央报告工作的批语',
        dates: [{ year: 1950, month: 9, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 155,
        page_end: 155,
        title: '在薄一波送审的一九五一年预算草案上的批语',
        dates: [{ year: 1950, month: 9, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 156,
        page_end: 156,
        title: '同意陆军大学设在南京',
        dates: [{ year: 1950, month: 9, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 157,
        page_end: 157,
        title: '复南非联邦杜邦城南非印度人大会会议联合书记电',
        dates: [{ year: 1950, month: 9, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 158,
        page_end: 159,
        title: '同意以大战略区为单位在上海设办事处',
        dates: [{ year: 1950, month: 9, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 160,
        page_end: 160,
        title: '希望各军区党委报告第一期整风情况',
        dates: [{ year: 1950, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 161,
        page_end: 161,
        title: '关于区域自治问题的批语',
        dates: [{ year: 1950, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 162,
        page_end: 163,
        title: '粤桂等地军事部署及对剿匪等项工作的指示',
        dates: [{ year: 1950, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 164,
        page_end: 164,
        title: '军委关于广西我军注意不要超出国界的电报',
        dates: [{ year: 1950, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 165,
        page_end: 165,
        title: '关于抗议美机美舰对我侵袭问题的批语',
        dates: [{ year: 1950, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 166,
        page_end: 166,
        title: '关于各大区在天津设联合办事处问题的批语',
        dates: [{ year: 1950, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 167,
        page_end: 167,
        title: '对云南军区关于复员军人复审工作报告的批语',
        dates: [{ year: 1950, month: 9, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 168,
        page_end: 168,
        title: '给张维的信',
        dates: [{ year: 1950, month: 9, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 170,
        page_end: 170,
        title: '贺张维母王老夫人八十寿辰联',
        dates: [{ year: 1950, month: 9, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 172,
        page_end: 172,
        title: '在华北局关于工农业情况和意见的综合报告上的批语',
        dates: [{ year: 1950, month: 9, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 173,
        page_end: 173,
        title: '给罗荣桓的信',
        dates: [{ year: 1950, month: 9, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 174,
        page_end: 174,
        title: '关于立即停止在韶山为毛泽东建房给黄克诚等的信',
        dates: [{ year: 1950, month: 9, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 176,
        page_end: 177,
        title: '在争夺战中大量歼敌有生力量是很有利的',
        dates: [{ year: 1950, month: 9, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 178,
        page_end: 178,
        title: '中央关于华北局各项报告处理情况的电报',
        dates: [{ year: 1950, month: 9, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 179,
        page_end: 180,
        title: '在全国战斗英雄和劳动模范代表会议上的祝词',
        dates: [{ year: 1950, month: 9, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 182,
        page_end: 182,
        title: '为全国战斗英雄代表会议题词',
        dates: [{ year: 1950, month: 9, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 190,
        page_end: 190,
        title: '在全国经济保卫工作会议总结上的批语',
        dates: [{ year: 1950, month: 9, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 191,
        page_end: 192,
        title: '转发关于长期作战问题致朝鲜同志电',
        dates: [{ year: 1950, month: 9, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 193,
        page_end: 193,
        title: '对《关于重申保密纪律的训令》的修改',
        dates: [{ year: 1950, month: 9, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 194,
        page_end: 194,
        title: '在宣传中不说打台湾西藏的时间',
        dates: [{ year: 1950, month: 9, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 195,
        page_end: 195,
        title: '务使确有把握每战获胜',
        dates: [{ year: 1950, month: 9, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 196,
        page_end: 196,
        title: '接受保加利亚驻华大使彼得科夫呈递国书时的答词',
        dates: [{ year: 1950, month: 9, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 197,
        page_end: 197,
        title: '为萌芽学校题名',
        dates: [{ year: 1950, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 199,
        page_end: 199,
        title: '为北京师范大学题名',
        dates: [{ year: 1950, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 205,
        page_end: 205,
        title: '东北边防军随时待命出动',
        dates: [{ year: 1950, month: 10, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 206,
        page_end: 208,
        title: '关于派志愿军入朝参战问题',
        dates: [{ year: 1950, month: 10, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 209,
        page_end: 209,
        title: '无法北撤的朝鲜人民军应在原地坚持打游击',
        dates: [{ year: 1950, month: 10, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 210,
        page_end: 210,
        title: '关于我赴朝武官参观组的任务',
        dates: [{ year: 1950, month: 10, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 211,
        page_end: 212,
        title: '对公安部队建设报告的批语',
        dates: [{ year: 1950, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 213,
        page_end: 213,
        title: '为中苏友好协会成立一周年题词',
        dates: [{ year: 1950, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 215,
        page_end: 215,
        title: '为湖南省立第一师范题写校牌',
        dates: [{ year: 1950, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 216,
        page_end: 216,
        title: '先歼东溪西南被围之敌再歼高平南逃之敌',
        dates: [{ year: 1950, month: 10, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 217,
        page_end: 217,
        title: '组成中国人民志愿军的命令',
        dates: [{ year: 1950, month: 10, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 219,
        page_end: 219,
        title: '决定派遣志愿军入朝作战',
        dates: [{ year: 1950, month: 10, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 222,
        page_end: 222,
        title: '关于援助朝鲜事务的处理',
        dates: [{ year: 1950, month: 10, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 223,
        page_end: 223,
        title: '开辟敌后战场在战略上是必须的有利的',
        dates: [{ year: 1950, month: 10, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 224,
        page_end: 225,
        title: '中国同志必须随时检讨自己的方法和态度',
        dates: [{ year: 1950, month: 10, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 226,
        page_end: 227,
        title: '同意四个军三个炮兵师全部出动待机歼敌',
        dates: [{ year: 1950, month: 10, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 228,
        page_end: 228,
        title: '关于全歼拉本兵团及七溪守敌',
        dates: [{ year: 1950, month: 10, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 229,
        page_end: 229,
        title: '人民解放军必须进入西藏',
        dates: [{ year: 1950, month: 10, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 230,
        page_end: 230,
        title: '关于接济湖南教育界老人给王首道的信',
        dates: [{ year: 1950, month: 10, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 231,
        page_end: 231,
        title: '关于九兵团提前北上致陈毅电',
        dates: [{ year: 1950, month: 10, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 232,
        page_end: 232,
        title: '十三兵团仍在原地训练',
        dates: [{ year: 1950, month: 10, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 233,
        page_end: 233,
        title: '东北各部队和宋时轮九兵团仍在原地整训',
        dates: [{ year: 1950, month: 10, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 234,
        page_end: 234,
        title: '转发总政治部关于全国战斗英雄代表会议总结报告的批语',
        dates: [{ year: 1950, month: 10, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 235,
        page_end: 235,
        title: '对航空学校是否迁移报告的批语',
        dates: [{ year: 1950, month: 10, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 236,
        page_end: 236,
        title: '为中国人民解放军全军青年工作会议题词',
        dates: [{ year: 1950, month: 10, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 238,
        page_end: 239,
        title: '中国人民志愿军应当和必须入朝参战',
        dates: [{ year: 1950, month: 10, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 240,
        page_end: 240,
        title: '关于停止追击由七溪逃往那岭之敌',
        dates: [{ year: 1950, month: 10, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 241,
        page_end: 241,
        title: '宋时轮九兵团到泰安曲阜区域集结待命',
        dates: [{ year: 1950, month: 10, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 242,
        page_end: 243,
        title: '朝鲜情况和对我军入朝参战的意见',
        dates: [{ year: 1950, month: 10, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 244,
        page_end: 245,
        title: '中国人民志愿军入朝作战的方针和部署',
        dates: [{ year: 1950, month: 10, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 246,
        page_end: 246,
        title: '关于宗教信仰自由保护问题的批语',
        dates: [{ year: 1950, month: 10, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 247,
        page_end: 247,
        title: '可以通知法国派飞机投掷粮食及运走重伤员',
        dates: [{ year: 1950, month: 10, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 248,
        page_end: 248,
        title: '关于立即前运志愿军粮食致高岗等电',
        dates: [{ year: 1950, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 249,
        page_end: 249,
        title: '志愿军参战部队出动的时间',
        dates: [{ year: 1950, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 250,
        page_end: 250,
        title: '在中财委关于近日市场情况报告上的批语',
        dates: [{ year: 1950, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 251,
        page_end: 251,
        title: '在外交部关于捷克打算编辑出版毛泽东著作报告上的批语',
        dates: [{ year: 1950, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 252,
        page_end: 252,
        title: '请即派人到安东接引彭德怀与金日成会面',
        dates: [{ year: 1950, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 253,
        page_end: 253,
        title: '请与苏联商量先调一个空军师保护首都空防',
        dates: [{ year: 1950, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 254,
        page_end: 254,
        title: '关于志愿军先头部队出动时间致彭德怀、高岗等电',
        dates: [{ year: 1950, month: 10, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 255,
        page_end: 255,
        title: '关于志愿军按预定计划入朝作战致邓华等电',
        dates: [{ year: 1950, month: 10, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 256,
        page_end: 256,
        title: '在华北局关于绥远非党干部对我批评意见的报告上的批语',
        dates: [{ year: 1950, month: 10, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 257,
        page_end: 257,
        title: '志愿军参战目前只做不说',
        dates: [{ year: 1950, month: 10, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 258,
        page_end: 258,
        title: '给刘天民的信',
        dates: [{ year: 1950, month: 10, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 259,
        page_end: 260,
        title: '中央转发华北局及察哈尔省委关于调整城乡关系的报告的批语',
        dates: [{ year: 1950, month: 10, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 261,
        page_end: 262,
        title: '志愿军打好出国第一仗',
        dates: [{ year: 1950, month: 10, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 263,
        page_end: 263,
        title: '争取战机迅速完成战役部署',
        dates: [{ year: 1950, month: 10, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 264,
        page_end: 264,
        title: '控制妙香山小白山隔断东西两敌',
        dates: [{ year: 1950, month: 10, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 265,
        page_end: 265,
        title: '对四十军行动部署的意见',
        dates: [{ year: 1950, month: 10, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 266,
        page_end: 266,
        title: '关于四五天内不登志愿军消息给胡乔木的信',
        dates: [{ year: 1950, month: 10, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 267,
        page_end: 267,
        title: '关于广播吴耀宗文章给胡乔木的信',
        dates: [{ year: 1950, month: 10, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 268,
        page_end: 270,
        title: '在博川军隅里及其以北地区围歼伪第六第八两师',
        dates: [{ year: 1950, month: 10, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 271,
        page_end: 272,
        title: '立即占领妙香山杏川洞',
        dates: [{ year: 1950, month: 10, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 273,
        page_end: 273,
        title: '十九兵团待命开东北',
        dates: [{ year: 1950, month: 10, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 274,
        page_end: 274,
        title: '西藏问题任何外国无权过问',
        dates: [{ year: 1950, month: 10, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 275,
        page_end: 276,
        title: '在稳当可靠的基础上争取一切可能的胜利',
        dates: [{ year: 1950, month: 10, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 279,
        page_end: 281,
        title: '对第一次战役的部署',
        dates: [{ year: 1950, month: 10, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 282,
        page_end: 282,
        title: '诱敌深入利于歼击',
        dates: [{ year: 1950, month: 10, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 283,
        page_end: 283,
        title: '捕捉战机最关紧要',
        dates: [{ year: 1950, month: 10, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 284,
        page_end: 284,
        title: '九兵团须从速准备开动',
        dates: [{ year: 1950, month: 10, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 285,
        page_end: 285,
        title: '六十六军赴朝作战问题',
        dates: [{ year: 1950, month: 10, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 286,
        page_end: 286,
        title: '诱敌深入山地然后围歼之',
        dates: [{ year: 1950, month: 10, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 287,
        page_end: 287,
        title: '志愿军司令部组成须有朝鲜同志参加',
        dates: [{ year: 1950, month: 10, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 288,
        page_end: 288,
        title: '关于抗议美机侵入我国领空的批语',
        dates: [{ year: 1950, month: 10, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 289,
        page_end: 289,
        title: '志愿军领导机构设置和主要干部配备',
        dates: [{ year: 1950, month: 10, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 290,
        page_end: 291,
        title: '必须准备与向鸭绿江进攻之敌作战',
        dates: [{ year: 1950, month: 10, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 292,
        page_end: 292,
        title: '第一仗似以打伪军为主为适宜',
        dates: [{ year: 1950, month: 10, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 294,
        page_end: 294,
        title: '关于敌方对我军行动的反映致彭德怀、邓华电',
        dates: [{ year: 1950, month: 10, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 295,
        page_end: 295,
        title: '先抓住一两部敌军围攻吸引敌主力增援',
        dates: [{ year: 1950, month: 10, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 296,
        page_end: 296,
        title: '军委关于伪一、六、八师行动情况的电报',
        dates: [{ year: 1950, month: 10, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 297,
        page_end: 297,
        title: '六十六军由志愿军司令部直接指挥',
        dates: [{ year: 1950, month: 10, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 298,
        page_end: 298,
        title: '先歼伪第一第六第八师后打美英军',
        dates: [{ year: 1950, month: 10, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 299,
        page_end: 300,
        title: '同意彭德怀提出的对敌作战方针',
        dates: [{ year: 1950, month: 10, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 301,
        page_end: 302,
        title: '对三十九军作战行动的部署',
        dates: [{ year: 1950, month: 10, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 303,
        page_end: 303,
        title: '歼灭伪第一第六第八师的作战部署',
        dates: [{ year: 1950, month: 10, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 304,
        page_end: 304,
        title: '对军委设立军事运输部门报告的批语',
        dates: [{ year: 1950, month: 10, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 305,
        page_end: 306,
        title: '九兵团北调整训和敌军行动情况',
        dates: [{ year: 1950, month: 10, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 307,
        page_end: 307,
        title: '按新情况重新确定攻击目标',
        dates: [{ year: 1950, month: 10, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 308,
        page_end: 308,
        title: '关于暂时不宜发表作战新闻致彭德怀电',
        dates: [{ year: 1950, month: 10, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 309,
        page_end: 309,
        title: '对在天安门前建立毛泽东大铜像建议的批语',
        dates: [{ year: 1950, month: 10, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 310,
        page_end: 310,
        title: '赞同聚歼伪军四个师的部署',
        dates: [{ year: 1950, month: 10, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 311,
        page_end: 311,
        title: '第一次战役的关键有两点',
        dates: [{ year: 1950, month: 10, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 312,
        page_end: 312,
        title: '诱敌深入定宣泰龟泰川等区域以利歼击',
        dates: [{ year: 1950, month: 10, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 313,
        page_end: 313,
        title: '在起义军官较多的团以上部队均可组织军政委员会',
        dates: [{ year: 1950, month: 10, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 314,
        page_end: 314,
        title: '转发华北军区高干会情况报告的批语',
        dates: [{ year: 1950, month: 10, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 315,
        page_end: 315,
        title: '在袁仲贤关于梅农同申健谈西藏问题报告上的批语',
        dates: [{ year: 1950, month: 10, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 316,
        page_end: 316,
        title: '使用九兵团主力对付可能由咸兴向北进攻之敌',
        dates: [{ year: 1950, month: 10, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 317,
        page_end: 318,
        title: '以全歼当面之敌为目标是正确的',
        dates: [{ year: 1950, month: 10, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 319,
        page_end: 320,
        title: '关于南朝鲜军队战斗特点的通报',
        dates: [{ year: 1950, month: 10, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 321,
        page_end: 321,
        title: '九兵团的作战任务',
        dates: [{ year: 1950, month: 10, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 322,
        page_end: 322,
        title: '关于将志愿军入朝作战注意事项等汇送宋时轮的批语',
        dates: [{ year: 1950, month: 10, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 323,
        page_end: 323,
        title: '为《解放军画报》题名',
        dates: [{ year: 1950, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 324,
        page_end: 324,
        title: '不能听任美国侵入中朝边界而置之不理',
        dates: [{ year: 1950, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 325,
        page_end: 326,
        title: '浣溪沙·和柳亚子先生',
        dates: [{ year: 1950, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 331,
        page_end: 331,
        title: '为抗美援朝题词',
        dates: [{ year: 1950, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 332,
        page_end: 332,
        title: '为《任弼时同志逝世纪念集》题词',
        dates: [{ year: 1950, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 334,
        page_end: 334,
        title: '对中国人民志愿军指示的团结朝鲜人民四项原则',
        dates: [{ year: 1950 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 335,
        page_end: 335,
        title: '为中国人民志愿军制定的第一阶段作战方针',
        dates: [{ year: 1950, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 336,
        page_end: 336,
        title: '以四十二军一部迅占宁远德川孟山诸点',
        dates: [{ year: 1950, month: 11, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 337,
        page_end: 338,
        title: '同意志愿军的作战部署',
        dates: [{ year: 1950, month: 11, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 339,
        page_end: 339,
        title: '伪首都师和美二师动向及我之部署',
        dates: [{ year: 1950, month: 11, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 340,
        page_end: 341,
        title: '关于三十八军等部的作战部署',
        dates: [{ year: 1950, month: 11, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 342,
        page_end: 342,
        title: '全局关键在于隔断南北敌人联系歼灭美军第二师',
        dates: [{ year: 1950, month: 11, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 343,
        page_end: 343,
        title: '关于九兵团部署问题致彭德怀、高岗电',
        dates: [{ year: 1950, month: 11, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 344,
        page_end: 344,
        title: '关于发表北京大学教师联名给毛泽东的信的批语',
        dates: [{ year: 1950, month: 11, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 345,
        page_end: 345,
        title: '注意各个歼灭可能向我举行反攻之敌',
        dates: [{ year: 1950, month: 11, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 346,
        page_end: 346,
        title: '关于《各民主党派联合宣言》给胡乔木的信',
        dates: [{ year: 1950, month: 11, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 347,
        page_end: 347,
        title: '争取在元山顺川铁路线以北创造战场',
        dates: [{ year: 1950, month: 11, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 348,
        page_end: 348,
        title: '三十八军应尽可能争取歼灭伪七师一两个团',
        dates: [{ year: 1950, month: 11, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 349,
        page_end: 349,
        title: '关于目前不宜以联合司令部名义发表战报的电报',
        dates: [{ year: 1950, month: 11, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 350,
        page_end: 350,
        title: '九兵团以诱敌深入寻机各个歼敌为方针',
        dates: [{ year: 1950, month: 11, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 351,
        page_end: 351,
        title: '关于九兵团行动问题的批语',
        dates: [{ year: 1950, month: 11, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 352,
        page_end: 352,
        title: '为庆祝十月社会主义革命三十三周年给苏联的贺电',
        dates: [{ year: 1950, month: 11, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 353,
        page_end: 353,
        title: '对出版志愿军报纸请示报告的批语',
        dates: [{ year: 1950, month: 11, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 354,
        page_end: 355,
        title: '同意志愿军下一步的作战方针和部署',
        dates: [{ year: 1950, month: 11, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 356,
        page_end: 356,
        title: '对暂时放弃攻打金门任务报告的批语',
        dates: [{ year: 1950, month: 11, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 357,
        page_end: 357,
        title: '中央转发北京市委关于抗美援朝运动开展情况报告的批语',
        dates: [{ year: 1950, month: 11, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 358,
        page_end: 358,
        title: '必须精心组织歼灭美军陆战第一师',
        dates: [{ year: 1950, month: 11, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 359,
        page_end: 359,
        title: '与朝鲜同志商谈应注意方式',
        dates: [{ year: 1950, month: 11, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 360,
        page_end: 360,
        title: '给李漱清的信',
        dates: [{ year: 1950, month: 11, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 361,
        page_end: 361,
        title: '朝鲜战局是可以转变的',
        dates: [{ year: 1950, month: 11, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 362,
        page_end: 363,
        title: '关于肃清广西匪患和增强广东兵力的电报',
        dates: [{ year: 1950, month: 11, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 364,
        page_end: 364,
        title: '对《综合各方对朝鲜战争反映》电报稿的修改',
        dates: [{ year: 1950, month: 11, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 365,
        page_end: 366,
        title: '关于西南局综合报告的复电和批语',
        dates: [{ year: 1950, month: 11, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 367,
        page_end: 368,
        title: '中央关于西南局镇压反革命活动报告的批语和复电',
        dates: [{ year: 1950, month: 11, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 370,
        page_end: 370,
        title: '关于转发西南军区剿匪简报第四号的电报',
        dates: [{ year: 1950, month: 11, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 371,
        page_end: 371,
        title: '关于统筹两广对付美蒋进犯',
        dates: [{ year: 1950, month: 11, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 372,
        page_end: 373,
        title: '广东广西的工作安排和兵力部署',
        dates: [{ year: 1950, month: 11, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 374,
        page_end: 375,
        title: '加强华东军区领导做好剿匪工作',
        dates: [{ year: 1950, month: 11, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 376,
        page_end: 376,
        title: '关于朝鲜主力战场的新闻报道的指示',
        dates: [{ year: 1950, month: 11, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 377,
        page_end: 377,
        title: '只要多打几个胜仗整个国际局势就会改观',
        dates: [{ year: 1950, month: 11, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 378,
        page_end: 379,
        title: '及时补充兵力连续作战',
        dates: [{ year: 1950, month: 11, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 380,
        page_end: 381,
        title: '中央关于北京市委镇压反革命活动报告的批语和复电',
        dates: [{ year: 1950, month: 11, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 382,
        page_end: 382,
        title: '必须做到土改与剿匪相结合',
        dates: [{ year: 1950, month: 11, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 383,
        page_end: 383,
        title: '加紧准备防空战胜敌人可能的空袭',
        dates: [{ year: 1950, month: 11, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 384,
        page_end: 385,
        title: '出国作战部队应加强同美军作战的思想准备',
        dates: [{ year: 1950, month: 11, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 386,
        page_end: 386,
        title: '给郭耿光的信',
        dates: [{ year: 1950, month: 11, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 387,
        page_end: 387,
        title: '给胡乔木的信',
        dates: [{ year: 1950, month: 11, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 388,
        page_end: 388,
        title: '关于发布剿匪通报问题致中南、华东西南军区电',
        dates: [{ year: 1950, month: 11, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 389,
        page_end: 390,
        title: '致彭德怀、邓华、洪学智电',
        dates: [{ year: 1950, month: 11, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 391,
        page_end: 392,
        title: '准备随时扑灭空降敌人',
        dates: [{ year: 1950, month: 11, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 393,
        page_end: 393,
        title: '集中四个军歼灭美军三个师的主力',
        dates: [{ year: 1950, month: 11, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 395,
        page_end: 395,
        title: '关于鼓励士气争取大胜致彭德怀等电',
        dates: [{ year: 1950, month: 11, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 396,
        page_end: 396,
        title: '中央转发关于处理群众来信问题报告的批语',
        dates: [{ year: 1950, month: 11, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 397,
        page_end: 397,
        title: '利用两个战役之间作必要的休息整训',
        dates: [{ year: 1950, month: 11, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 398,
        page_end: 399,
        title: '浣溪沙·和柳亚子先生',
        dates: [{ year: 1950, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 401,
        page_end: 401,
        title: '为全军保卫工作会议题词',
        dates: [{ year: 1950, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 403,
        page_end: 403,
        title: '四十二军应从侧面威胁平壤',
        dates: [{ year: 1950, month: 12, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 404,
        page_end: 405,
        title: '坚决站在抗美援朝保家卫国的爱国立场上',
        dates: [{ year: 1950, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 406,
        page_end: 406,
        title: '增强南北阻援阻止敌人突围',
        dates: [{ year: 1950, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 407,
        page_end: 407,
        title: '西线各主力应准备继续作战',
        dates: [{ year: 1950, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 408,
        page_end: 408,
        title: '二十六军南下作战九兵团准备打增援之敌',
        dates: [{ year: 1950, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 409,
        page_end: 409,
        title: '主力宜在顺川肃川线作战',
        dates: [{ year: 1950, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 410,
        page_end: 410,
        title: '给黄念田的信',
        dates: [{ year: 1950, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 412,
        page_end: 412,
        title: '关于改变一九五一年部队教育时间比例的指示',
        dates: [{ year: 1950, month: 12, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 413,
        page_end: 414,
        title: '围而不歼诱敌来援',
        dates: [{ year: 1950, month: 12, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 415,
        page_end: 415,
        title: '为了解就地取给粮草等情况致彭德怀、高岗电',
        dates: [{ year: 1950, month: 12, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 416,
        page_end: 416,
        title: '战争应从最坏方面着想',
        dates: [{ year: 1950, month: 12, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 417,
        page_end: 417,
        title: '应迅速控制飞机场不使被围美军撤走',
        dates: [{ year: 1950, month: 12, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 418,
        page_end: 418,
        title: '如平壤敌撤退则志愿军向三八线攻进',
        dates: [{ year: 1950, month: 12, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 419,
        page_end: 419,
        title: '相机占领平壤',
        dates: [{ year: 1950, month: 12, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 420,
        page_end: 421,
        title: '对全军立功奖励问题报告的批语',
        dates: [{ year: 1950, month: 12, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 422,
        page_end: 424,
        title: '解放平壤的两则电讯和播发此讯的批语',
        dates: [
          { year: 1950, month: 12, day: 4 },
          { year: 1950, month: 12, day: 5 },
          { year: 1950, month: 12, day: 6 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 425,
        page_end: 426,
        title: '同意东西两线作战部署',
        dates: [{ year: 1950, month: 12, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 427,
        page_end: 427,
        title: '关于目前只宜强调召开各界人民代表会议的批语',
        dates: [{ year: 1950, month: 12, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 428,
        page_end: 429,
        title: '关于志愿军西线主力行动和中朝军队协同作战问题',
        dates: [{ year: 1950, month: 12, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 430,
        page_end: 430,
        title: '军委关于同意海南岛的海防部署致邓子恢等电',
        dates: [{ year: 1950, month: 12, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 431,
        page_end: 431,
        title: '军委关于九兵团指挥所的防空荫蔽问题的电报',
        dates: [{ year: 1950, month: 12, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 432,
        page_end: 433,
        title: '对华东军区剿匪经验通报的复电',
        dates: [{ year: 1950, month: 12, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 434,
        page_end: 435,
        title: '请求苏联帮助越南解决汽车和汽油问题',
        dates: [{ year: 1950, month: 12, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 436,
        page_end: 436,
        title: '中央转发南京学生反美控诉运动经验的批语',
        dates: [{ year: 1950, month: 12, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 437,
        page_end: 438,
        title: '关于美军准备从朝鲜撤退的情报致彭德怀等电',
        dates: [{ year: 1950, month: 12, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 440,
        page_end: 440,
        title: '在广州市机关物资疏散情况报告上的批语',
        dates: [{ year: 1950, month: 12, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 441,
        page_end: 441,
        title: '对成立化学兵学校报告的批语',
        dates: [{ year: 1950, month: 12, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 442,
        page_end: 442,
        title: '中国人民志愿军必须越过三八线作战',
        dates: [{ year: 1950, month: 12, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 443,
        page_end: 444,
        title: '关于志愿军兵力使用的意见',
        dates: [{ year: 1950, month: 12, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 445,
        page_end: 446,
        title: '我军能够战胜装备优良的美国军队',
        dates: [{ year: 1950, month: 12, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 447,
        page_end: 447,
        title: '给陈叔通的信',
        dates: [{ year: 1950, month: 12, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 449,
        page_end: 449,
        title: '中宣部转发西南局宣传部关于清匪反霸报道问题的意见的批语',
        dates: [{ year: 1950, month: 12, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 450,
        page_end: 457,
        title: '关于镇压反革命',
        dates: [
          { year: 1950, month: 12 },
          { year: 1950, month: 1951, day: 10 },
        ],
        is_range_date: true,
        authors: ['毛泽东'],
      },
      {
        page_start: 458,
        page_end: 459,
        title: '朝鲜作战必须作长期打算',
        dates: [{ year: 1950, month: 12, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 460,
        page_end: 460,
        title: '对我国关于联合国大会通过“朝鲜停战三人委员会”决议的声明的修改',
        dates: [{ year: 1950, month: 12, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 461,
        page_end: 461,
        title: '目前应使敌集中以利歼击',
        dates: [{ year: 1950, month: 12, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 463,
        page_end: 464,
        title: '第三次战役结束后全军主力均应后撤休整',
        dates: [{ year: 1950, month: 12, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 465,
        page_end: 465,
        title: '征调老战士补充志愿军部队',
        dates: [{ year: 1950, month: 12, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 466,
        page_end: 466,
        title: '祝贺法国共产党成立三十周年的电报',
        dates: [{ year: 1950, month: 12, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 467,
        page_end: 467,
        title: '关于发表《实践论》等文章给胡乔木的信',
        dates: [{ year: 1950, month: 12, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 468,
        page_end: 468,
        title: '关于重新发表中共中央关于领导方法的决定等文件给胡乔木的信',
        dates: [{ year: 1950, month: 12, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 469,
        page_end: 470,
        title: '打一个胜仗后休整准备春季攻势',
        dates: [{ year: 1950, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 471,
        page_end: 471,
        title: '加紧督促桂粤湘三省剿匪巩固广东防务',
        dates: [{ year: 1950, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 472,
        page_end: 472,
        title: '转发中南军区秋季剿匪情况报告的批语',
        dates: [{ year: 1950, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 474,
        page_end: 474,
        title: '在华南分局关于广州市预防空袭疏散物资情况报告上的批语',
        dates: [{ year: 1950, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 475,
        page_end: 475,
        title: '给黄炎培的信',
        dates: [{ year: 1950, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 476,
        page_end: 476,
        title: '给周世钊的信',
        dates: [{ year: 1950, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 478,
        page_end: 478,
        title: '为湖南省立第一师范学校题词',
        dates: [{ year: 1950, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 480,
        page_end: 480,
        title: '为机要工作题词',
        dates: [{ year: 1950, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 481,
        page_end: 481,
        title: '中央转发中南局关于镇压反革命的第二次指示的批语',
        dates: [{ year: 1950, month: 12, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 482,
        page_end: 482,
        title: '中央转发西北局关于工会工作报告的批语',
        dates: [{ year: 1950, month: 12, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 483,
        page_end: 484,
        title: '给王震的电报和复才旦朋杰、扎西才让的信',
        dates: [{ year: 1950, month: 12, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 485,
        page_end: 486,
        title: '为《瞿秋白文集》题词和给杨之华的信',
        dates: [{ year: 1950, month: 12, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 487,
        page_end: 487,
        title: '关于同意朝鲜新解放区借粮办法的电报',
        dates: [{ year: 1950, month: 12, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 488,
        page_end: 489,
        title: '军委关于查告志愿军伤亡失踪人数致彭德怀等电',
        dates: [{ year: 1950, month: 12, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 491,
        page_end: 491,
        title: '军委为询问九兵团情况致宋时轮电',
        dates: [{ year: 1950, month: 12, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 492,
        page_end: 492,
        title: '为人民教育出版社题名',
        dates: [{ year: 1950, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 493,
        page_end: 493,
        title: '为南开大学题写校名',
        dates: [{ year: 1950 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 494,
        page_end: 494,
        title: '和郭沫若题齐白石画',
        dates: [{ year: 1950 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 496,
        page_end: 496,
        title: '为《公安建设》题名',
        dates: [{ year: 1950 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 498,
        page_end: 498,
        title: '给张有晋的信',
        dates: [{ year: 1950 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 500,
        page_end: 500,
        title: '为张子敬题词',
        dates: [{ year: 1950 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 502,
        page_end: 502,
        title: '为黄宝珣题词',
        dates: [{ year: 1950 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 504,
        page_end: 504,
        title: '为北京医院题名',
        dates: [{ year: 1950 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 506,
        page_end: 507,
        title: '关于同意广西剿匪计划致张云逸等电',
        dates: [{ year: 1951, month: 1, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 508,
        page_end: 508,
        title: '中央关于同意华南分局对海南岛的工作计划的电报',
        dates: [{ year: 1951, month: 1, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 509,
        page_end: 509,
        title: '征调老兵补充志愿军具有极大意义',
        dates: [{ year: 1951, month: 1, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 510,
        page_end: 510,
        title: '同意对湖南军大旧军官中反动分子的处理意见',
        dates: [{ year: 1951, month: 1, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 511,
        page_end: 512,
        title: '关于修筑入藏公路的批语',
        dates: [{ year: 1951, month: 1, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 513,
        page_end: 514,
        title: '中央对高岗关于与苏联军事人员建立良好关系的电报的批语和复电',
        dates: [{ year: 1951, month: 1, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 515,
        page_end: 515,
        title: '关于处理生日贺电的批语',
        dates: [{ year: 1951, month: 1, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 516,
        page_end: 516,
        title: '给李讷的信',
        dates: [{ year: 1951, month: 1, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 517,
        page_end: 517,
        title: '对陈渠珍一案的处理意见',
        dates: [{ year: 1951, month: 1, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 518,
        page_end: 518,
        title: '给黄炎培的信',
        dates: [{ year: 1951, month: 1, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 519,
        page_end: 519,
        title: '为《人民周报》题写报头',
        dates: [{ year: 1951, month: 1, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 520,
        page_end: 521,
        title: '对陶铸关于广西剿匪工作报告的批语和复电',
        dates: [
          { year: 1951, month: 1, day: 7 },
          { year: 1951, month: 1, day: 9 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 522,
        page_end: 523,
        title: '四十五军四十六军应集中整训应付万',
        dates: [{ year: 1951, month: 1, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 524,
        page_end: 524,
        title: '给饶漱石、陈不显的信',
        dates: [{ year: 1951, month: 1, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 525,
        page_end: 525,
        title: '中央转发北京市委关于工商界抗美援朝运动报告的批语',
        dates: [{ year: 1951, month: 1, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 526,
        page_end: 526,
        title: '关于志愿军九兵团改善装备的批语',
        dates: [{ year: 1951, month: 1, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 527,
        page_end: 527,
        title: '同意中南军区集中兵力应付广东方面情况的电报',
        dates: [{ year: 1951, month: 1, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 528,
        page_end: 529,
        title: '关于防御国民党军队进攻厦门、汕头的电报',
        dates: [{ year: 1951, month: 1, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 530,
        page_end: 530,
        title: '在中央关于对朝鲜战争宣传应注意之点的电报稿上的批语',
        dates: [{ year: 1951, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 531,
        page_end: 531,
        title: '关于青海骑兵支队配合十八军入藏问题致邓小平电',
        dates: [{ year: 1951, month: 1, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 533,
        page_end: 533,
        title: '关于改写给金日成的备忘录的批语',
        dates: [{ year: 1951, month: 1, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 534,
        page_end: 534,
        title: '对出版《八一》杂志报告的批语',
        dates: [{ year: 1951, month: 1, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 535,
        page_end: 537,
        title: '给徐悲鸿的信',
        dates: [{ year: 1951, month: 1, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 538,
        page_end: 538,
        title: '给李思安的信',
        dates: [{ year: 1951, month: 1, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 541,
        page_end: 541,
        title: '给戴毓本的信',
        dates: [{ year: 1951, month: 1, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 542,
        page_end: 542,
        title: '为中国人民解放军军事学院成立题词',
        dates: [{ year: 1951, month: 1, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 544,
        page_end: 544,
        title: '给马叙伦的信',
        dates: [{ year: 1951, month: 1, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 545,
        page_end: 545,
        title: '确保厦门并加强华东沿海防务',
        dates: [{ year: 1951, month: 1, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 546,
        page_end: 547,
        title: '关于对反革命分子必须打得稳打得准打得狠的电报',
        dates: [{ year: 1951, month: 1, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
    ],
    ext: 'pdf',
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives0/maoquanji29.pdf',
};
