export default {
  entity: {
    id: 'maoquanji4-1',
    name: '毛泽东全集第4卷(1)',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives8/main/maoquanji4-1.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '湖南农民运动的真实情形',
        authors: ['毛泽东'],
        page_start: 17,
        page_end: 27,
        dates: [{ year: 1927, month: 6, day: 22 }],
        is_range_date: false,
      },
      {
        title: '中央农运讲习所给各省党部函',
        authors: ['毛泽东'],
        page_start: 28,
        page_end: 28,
        dates: [{ year: 1927, month: 6 }],
        is_range_date: false,
      },
      {
        title: '考送学生章程',
        authors: ['毛泽东'],
        page_start: 29,
        page_end: 33,
        dates: [{ year: 1927, month: 6 }],
        is_range_date: false,
      },
      {
        title: '中央农运讲习所招生计划',
        authors: ['毛泽东'],
        page_start: 34,
        page_end: 36,
        dates: [{ year: 1927, month: 6 }],
        is_range_date: false,
      },
      {
        title: '全国农协对于农运之新规划',
        authors: ['毛泽东'],
        page_start: 37,
        page_end: 40,
        dates: [{ year: 1927, month: 6 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局常委会第三十四次会议上的讲话',
        authors: ['毛泽东'],
        page_start: 41,
        page_end: 42,
        dates: [{ year: 1927, month: 7, day: 4 }],
        is_range_date: false,
      },
      {
        title: '日前农民运动的总策略',
        authors: ['毛泽东'],
        page_start: 43,
        page_end: 48,
        dates: [{ year: 1927, month: 7, day: 20 }],
        is_range_date: false,
      },
      {
        title: '中央委员宣言',
        authors: ['毛泽东'],
        page_start: 49,
        page_end: 55,
        dates: [{ year: 1927, month: 8, day: 1 }],
        is_range_date: false,
      },
      {
        title: '在中央紧急会议上的发言',
        authors: ['毛泽东'],
        page_start: 56,
        page_end: 60,
        dates: [{ year: 1927, month: 8, day: 7 }],
        is_range_date: false,
      },
      {
        title: '湘南运动大钢',
        authors: ['毛泽东'],
        page_start: 61,
        page_end: 62,
        dates: [{ year: 1927, month: 8 }],
        is_range_date: false,
      },
      {
        title: '湖南民众组织更需要武装',
        authors: ['毛泽东'],
        page_start: 63,
        page_end: 63,
        dates: [{ year: 1927, month: 8, day: 9 }],
        is_range_date: false,
      },
      {
        title: '关于土地问题的意见',
        authors: ['毛泽东'],
        page_start: 64,
        page_end: 64,
        dates: [{ year: 1927, month: 8, day: 18 }],
        is_range_date: false,
      },
      {
        title: '湖南秋收暴动要有军队帮助',
        authors: ['毛泽东'],
        page_start: 65,
        page_end: 65,
        dates: [{ year: 1927, month: 8, day: 18 }],
        is_range_date: false,
      },
      {
        title: '中共湖南省委给中共中央的报告',
        authors: ['毛泽东'],
        page_start: 66,
        page_end: 66,
        dates: [{ year: 1927, month: 8, day: 19 }],
        is_range_date: false,
      },
      {
        title: '湖南致中央函',
        authors: ['毛泽东'],
        page_start: 67,
        page_end: 68,
        dates: [{ year: 1927, month: 8, day: 20 }],
        is_range_date: false,
      },
      {
        title: '湖南常委来信',
        authors: ['毛泽东'],
        page_start: 69,
        page_end: 69,
        dates: [{ year: 1927, month: 8, day: 30 }],
        is_range_date: false,
      },
      {
        title: '不打长沙转兵向南',
        authors: ['毛泽东'],
        page_start: 70,
        page_end: 70,
        dates: [{ year: 1927, month: 9, day: 20 }],
        is_range_date: false,
      },
      {
        title: '给杨开慧的信',
        authors: ['毛泽东'],
        page_start: 71,
        page_end: 71,
        dates: [{ year: 1927, month: 9 }],
        is_range_date: false,
      },
      {
        title: '给中共湖南省委的信',
        authors: ['毛泽东'],
        page_start: 72,
        page_end: 72,
        dates: [{ year: 1927, month: 12, day: 18 }],
        is_range_date: false,
      },
      {
        title: '西江月·秋收起义',
        authors: ['毛泽东'],
        page_start: 73,
        page_end: 86,
        dates: [{ year: 1927 }],
        is_range_date: false,
      },
      {
        title: '题军旗联',
        authors: ['毛泽东'],
        page_start: 87,
        page_end: 88,
        dates: [{ year: 1927 }],
        is_range_date: false,
      },
      {
        title: '到安源时之报告',
        authors: ['毛泽东'],
        page_start: 89,
        page_end: 94,
        dates: [{ year: 1927 }],
        is_range_date: false,
      },
      {
        title: '题送川公审土豪劣绅大会联',
        authors: ['毛泽东'],
        page_start: 95,
        page_end: 98,
        dates: [{ year: 1928, month: 1 }],
        is_range_date: false,
      },
      {
        title: '为井冈山群众题春联',
        authors: ['毛泽东'],
        page_start: 99,
        page_end: 99,
        dates: [{ year: 1928 }],
        is_range_date: false,
      },
      {
        title: '给江西省委和中央的报告',
        authors: ['毛泽东'],
        page_start: 100,
        page_end: 109,
        dates: [{ year: 1928, month: 5, day: 2 }],
        is_range_date: false,
      },
      {
        title: '给湖南江西省委转中央的信',
        authors: ['毛泽东'],
        page_start: 110,
        page_end: 114,
        dates: [{ year: 1928, month: 6, day: 16 }],
        is_range_date: false,
      },
      {
        title: '中共湘赣边特委和红四军军委给湖南省委的报告',
        authors: ['毛泽东'],
        page_start: 115,
        page_end: 119,
        dates: [{ year: 1928, month: 7, day: 4 }],
        is_range_date: false,
      },
      {
        title: '湘赣边界特委致湖南省委信',
        authors: ['毛泽东'],
        page_start: 120,
        page_end: 121,
        dates: [{ year: 1928, month: 8 }],
        is_range_date: false,
      },
      {
        title: '中国的红色政权为什么能够存在？m',
        authors: ['毛泽东'],
        page_start: 122,
        page_end: 135,
        dates: [{ year: 1928, month: 10, day: 5 }],
        is_range_date: false,
      },
      {
        title: '湘赣边界各县党第二次代表大会决议案',
        authors: ['毛泽东'],
        page_start: 136,
        page_end: 145,
        dates: [{ year: 1928, month: 10, day: 5 }],
        is_range_date: false,
      },
      {
        title: '晚王尔琢联',
        authors: ['毛泽东'],
        page_start: 146,
        page_end: 150,
        dates: [{ year: 1928, month: 10 }],
        is_range_date: false,
      },
      {
        title: '开冈山的斗争',
        authors: ['毛泽东'],
        page_start: 151,
        page_end: 189,
        dates: [{ year: 1928, month: 11, day: 25 }],
        is_range_date: false,
      },
      {
        title: '（并冈山）土地法',
        authors: ['毛泽东'],
        page_start: 190,
        page_end: 193,
        dates: [{ year: 1928, month: 12 }],
        is_range_date: false,
      },
      {
        title: '红军第四军六次代表大会决议案',
        authors: ['毛泽东'],
        page_start: 194,
        page_end: 201,
        dates: [{ year: 1928, month: 12, day: 16 }],
        is_range_date: false,
      },
      {
        title: '和何长工应对联',
        authors: ['毛泽东'],
        page_start: 202,
        page_end: 204,
        dates: [{ year: 1928 }],
        is_range_date: false,
      },
      {
        title: '红军第四军司令部布告',
        authors: ['毛泽东'],
        page_start: 205,
        page_end: 208,
        dates: [{ year: 1929, month: 1 }],
        is_range_date: false,
      },
      {
        title: '共产党宣言',
        authors: ['毛泽东'],
        page_start: 209,
        page_end: 211,
        dates: [{ year: 1929, month: 1 }],
        is_range_date: false,
      },
      {
        title: '筹款公函',
        authors: ['毛泽东'],
        page_start: 212,
        page_end: 213,
        dates: [{ year: 1929, month: 2, day: 13 }],
        is_range_date: false,
      },
      {
        title: '告商人及知识分子',
        authors: ['毛泽东'],
        page_start: 214,
        page_end: 216,
        dates: [{ year: 1929, month: 3, day: 16 }],
        is_range_date: false,
      },
      {
        title: '红军第四车前委给中央的信',
        authors: ['毛泽东'],
        page_start: 217,
        page_end: 221,
        dates: [{ year: 1929, month: 3, day: 20 }],
        is_range_date: false,
      },
      {
        title: '敬告士兵群众书',
        authors: ['毛泽东'],
        page_start: 222,
        page_end: 222,
        dates: [{ year: 1929, month: 3, day: 27 }],
        is_range_date: false,
      },
      {
        title: '红军第四军前委给中央的信',
        authors: ['毛泽东'],
        page_start: 223,
        page_end: 233,
        dates: [{ year: 1929, month: 4, day: 5 }],
        is_range_date: false,
      },
      {
        title: '四军军部命令',
        authors: ['毛泽东'],
        page_start: 234,
        page_end: 235,
        dates: [{ year: 1929, month: 4, day: 10 }],
        is_range_date: false,
      },
      {
        title: '给湘赣边界特委的信',
        authors: ['毛泽东'],
        page_start: 236,
        page_end: 236,
        dates: [{ year: 1929, month: 4, day: 13 }],
        is_range_date: false,
      },
      {
        title: '（兴国县）土地法',
        authors: ['毛泽东'],
        page_start: 237,
        page_end: 239,
        dates: [{ year: 1929, month: 4 }],
        is_range_date: false,
      },
      {
        title: '农民协会章程',
        authors: ['毛泽东'],
        page_start: 240,
        page_end: 244,
        dates: [{ year: 1929, month: 5 }],
        is_range_date: false,
      },
      {
        title: '红军第四军前委书记毛泽东给中央的报告',
        authors: ['毛泽东'],
        page_start: 245,
        page_end: 251,
        dates: [{ year: 1929, month: 6, day: 1 }],
        is_range_date: false,
      },
      {
        title: '给林彪的信',
        authors: ['毛泽东'],
        page_start: 252,
        page_end: 266,
        dates: [{ year: 1929, month: 6, day: 14 }],
        is_range_date: false,
      },
      {
        title: '红军第四军司令、政治部布告',
        authors: ['毛泽东'],
        page_start: 267,
        page_end: 275,
        dates: [{ year: 1929, month: 6 }],
        is_range_date: false,
      },
      {
        title: '采柔子山.重阳',
        authors: ['毛泽东'],
        page_start: 276,
        page_end: 288,
        dates: [{ year: 1929, month: 10 }],
        is_range_date: false,
      },
      {
        title: '从蚊洋到达江州后给中央的信',
        authors: ['毛泽东'],
        page_start: 289,
        page_end: 291,
        dates: [{ year: 1929, month: 11, day: 28 }],
        is_range_date: false,
      },
      {
        title: '给李立三“的信',
        authors: ['毛泽东'],
        page_start: 292,
        page_end: 294,
        dates: [{ year: 1929, month: 11, day: 28 }],
        is_range_date: false,
      },
      {
        title: '中国共产党红军第四军第九次代表大会决议案',
        authors: ['毛泽东'],
        page_start: 295,
        page_end: 339,
        dates: [{ year: 1929, month: 12 }],
        is_range_date: false,
      },
    ],
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives8/maoquanji4-1.pdf',
};
