export default {
  entity: {
    id: 'maoquanji32',
    name: '毛泽东全集第32卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives0/main/mao-quanji/maoquanji32.pdf',
  },
  parser_option: {
    page_limits: [
      [11, 34],
      [35, 49],
      [51, 94],
      [98, 110],
      [113, 113],
      [115, 122],
      [124, 124],
      [126, 135],
      [137, 148],
      [150, 153],
      [155, 164],
      [166, 191],
      [194, 197],
      [199, 202],
      [204, 204],
      [206, 208],
      [210, 211],
      [215, 229],
      [232, 246],
      [248, 249],
      [251, 264],
      [266, 269],
      [271, 271],
      [275, 278],
      [280, 281],
      [283, 289],
      [291, 308],
      [310, 312],
      [320, 320],
      [325, 325],
      [327, 337],
      [339, 339],
      [341, 349],
      [352, 358],
      [360, 373],
      [375, 386],
      [388, 390],
      [392, 408],
      [410, 410],
      [412, 414],
      [416, 416],
      [419, 425],
      [428, 436],
      [438, 477],
      [483, 499],
      [504, 504],
      [520, 520],
      [526, 535],
    ],
    articles: [
      {
        page_start: 35,
        page_end: 36,
        title: '中央转发薄一波关于上海五反第二期部署的报告的批语',
        dates: [{ year: 1952, month: 4, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 37,
        page_end: 38,
        title: '对中央关于干部交代同资产阶级关系的指示稿的批语和修改',
        dates: [{ year: 1952, month: 4, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 39,
        page_end: 42,
        title: '中共中央关于西藏工作方针的指示',
        dates: [{ year: 1952, month: 4, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 43,
        page_end: 44,
        title: '有关西藏的重要问题由中央处理',
        dates: [{ year: 1952, month: 4, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 45,
        page_end: 45,
        title: '中央对华北局一份情况通报的批语',
        dates: [{ year: 1952, month: 4, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 46,
        page_end: 47,
        title: '中央转发薄一波关于上海五反第二期经验报告的批语',
        dates: [{ year: 1952, month: 4, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 48,
        page_end: 48,
        title: '对徐子荣关于公安人员贩运盗卖毒品及包庇毒犯的情况报告的批语',
        dates: [{ year: 1952, month: 4, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 49,
        page_end: 49,
        title: '关于转载《三千多种商品牌价为什么能够降低？》一文给邓拓的信',
        dates: [{ year: 1952, month: 4, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 51,
        page_end: 52,
        title: '对湖南宁乡农民检举周震鳞问题来信的批语',
        dates: [{ year: 1952, month: 4, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 53,
        page_end: 53,
        title: '对曹彦昆献赠《清明上河图》画卷的批语',
        dates: [{ year: 1952, month: 4, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 54,
        page_end: 54,
        title: '中央关于各中央局、分局在近期召开全体委员会议的指示',
        dates: [{ year: 1952, month: 4, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 55,
        page_end: 55,
        title: '对北京市防疫工作会议情况报告的批语',
        dates: [{ year: 1952, month: 4, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 56,
        page_end: 57,
        title: '对反动分子的斗争实行有理有利有节的方针',
        dates: [{ year: 1952, month: 4, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 58,
        page_end: 59,
        title: '西藏工委处理非法“人民会议”的方针是正确的',
        dates: [{ year: 1952, month: 4, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 60,
        page_end: 60,
        title: '目前只作政治斗争',
        dates: [{ year: 1952, month: 4, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 61,
        page_end: 62,
        title: '对当前西藏工作的几点指示',
        dates: [{ year: 1952, month: 4, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 63,
        page_end: 64,
        title: '争取达赖和噶厦同意将两司曹撤职',
        dates: [{ year: 1952, month: 4, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 65,
        page_end: 66,
        title: '对薄一波关于上海五反报告的批语和在中央复电稿中加写的话',
        dates: [
          { year: 1952, month: 4, day: 15 },
          { year: 1952, month: 4, day: 16 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 67,
        page_end: 67,
        title: '中央转发上海市委关于争取违法资本家立功赎罪的经验的批语',
        dates: [{ year: 1952, month: 4, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 68,
        page_end: 69,
        title: '处理非法“人民会议”要又坚决又慎重',
        dates: [{ year: 1952, month: 4, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 70,
        page_end: 71,
        title: '关于揭露两司曹的罪恶和将其撤职的问题',
        dates: [{ year: 1952, month: 4, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 72,
        page_end: 72,
        title: '祝贺贝鲁特六十寿辰的电报',
        dates: [{ year: 1952, month: 4, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 73,
        page_end: 74,
        title: '在总参关于赴朝参观团的补充规定稿上加写的话',
        dates: [{ year: 1952, month: 4, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 75,
        page_end: 76,
        title: '坚持解散非法“人民会议”和将两司曹撤职',
        dates: [{ year: 1952, month: 4, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 77,
        page_end: 81,
        title: '对中华人民共和国惩治贪污条例草案说明稿的批语和修改',
        dates: [
          { year: 1952, month: 4, day: 16 },
          { year: 1952, month: 4, day: 17 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 82,
        page_end: 83,
        title:
          '中央转发轻工业部关于党内外干部普遍交代经济关系和社会关系报告的批语',
        dates: [{ year: 1952, month: 4, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 84,
        page_end: 84,
        title:
          '中央转发北京市委关于处理违法工商户中发动工人把关的经验报告的批语',
        dates: [{ year: 1952, month: 4, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 85,
        page_end: 86,
        title: '中央转发华东局关于上海五反第二战役经验的批语',
        dates: [{ year: 1952, month: 4, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 87,
        page_end: 87,
        title: '对北京市高等学校三反情况简报的批语',
        dates: [{ year: 1952, month: 4, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 88,
        page_end: 89,
        title: '关于朝鲜停战谈判问题复李克农电',
        dates: [{ year: 1952, month: 4, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 90,
        page_end: 91,
        title:
          '中央关于地方各级财委和军队后勤部门应作违反财政纪律的检讨报告的指示',
        dates: [{ year: 1952, month: 4, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 92,
        page_end: 92,
        title: '中央同意西藏工委关于藏政官员人选等问题的处理意见的电报',
        dates: [{ year: 1952, month: 4, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 93,
        page_end: 93,
        title: '五反宣传不要用军事术语',
        dates: [{ year: 1952, month: 4, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 94,
        page_end: 94,
        title: '为中共中央办公厅工作人员题词',
        dates: [{ year: 1952, month: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 98,
        page_end: 99,
        title: '对施复亮的报告的批语',
        dates: [{ year: 1952, month: 5, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 100,
        page_end: 100,
        title: '中央对中南局关于防止追赃时发生错误的指示的批语',
        dates: [{ year: 1952, month: 5, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 101,
        page_end: 102,
        title: '中央转发罗瑞卿关于华南军区纠正三反定案中右倾思想的报告的批语',
        dates: [{ year: 1952, month: 5, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 103,
        page_end: 105,
        title: '中央关于五反定案、补退工作等的指示',
        dates: [{ year: 1952, month: 5, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 106,
        page_end: 106,
        title: '中央对华北局关于正确结束三反运动的指示的批语',
        dates: [{ year: 1952, month: 5, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 107,
        page_end: 107,
        title: '中央转发重工业部关于三反追赃定案经验报告的批语',
        dates: [{ year: 1952, month: 5, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 108,
        page_end: 108,
        title: '对反细菌战防疫工作情况报告的批语',
        dates: [{ year: 1952, month: 5, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 109,
        page_end: 109,
        title: '对志愿军火炮筹补方案的批语',
        dates: [{ year: 1952, month: 5, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 110,
        page_end: 110,
        title: '给陈嘉庚的信',
        dates: [{ year: 1952, month: 5, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 113,
        page_end: 113,
        title: '关于成立后方勤务学院的命令',
        dates: [{ year: 1952, month: 5, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 115,
        page_end: 116,
        title: '对叶恭绰等要求保全袁崇焕祠墓的信的批语和复信',
        dates: [
          { year: 1952, month: 5, day: 16 },
          { year: 1952, month: 5, day: 25 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 117,
        page_end: 117,
        title: '处理同藏族有关的工作均须事前报告中央',
        dates: [{ year: 1952, month: 5, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 118,
        page_end: 118,
        title: '中央关于印发争取五反斗争胜利结束的几个问题的指示的批语',
        dates: [{ year: 1952, month: 5, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 119,
        page_end: 119,
        title: '庆祝和平解放西藏办法的协议签订一周年致达赖、班禅电',
        dates: [{ year: 1952, month: 5, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 120,
        page_end: 120,
        title: '对美蒋妄图骚扰华南沿海的情报的批语',
        dates: [{ year: 1952, month: 5, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 121,
        page_end: 121,
        title: '对中办秘书室关于群众来信反映失业情况的报告的批语',
        dates: [{ year: 1952, month: 5, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 122,
        page_end: 122,
        title: '为荆江分洪工程全体员工题词',
        dates: [{ year: 1952, month: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 124,
        page_end: 124,
        title: '为北京育英学校题词',
        dates: [{ year: 1952, month: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 126,
        page_end: 126,
        title: '对马光斗所作搞好劳资关系报告的反映的批语',
        dates: [{ year: 1952, month: 6, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 127,
        page_end: 127,
        title: '工人阶级与民族资产阶级的矛盾是国内的主要矛盾',
        dates: [{ year: 1952, month: 6, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 128,
        page_end: 128,
        title: '在《统战部长会议中所反映的问题简报》第一号上的批语',
        dates: [{ year: 1952, month: 6, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 129,
        page_end: 130,
        title: '中央关于谭震林等任职和军队整编问题复陈毅电',
        dates: [{ year: 1952, month: 6, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 131,
        page_end: 131,
        title: '接受波兰驻华大使基里洛克呈递国书时的答词',
        dates: [{ year: 1952, month: 6, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 132,
        page_end: 132,
        title: '接受芬兰驻华公使克诺林呈递国书时的答词',
        dates: [{ year: 1952, month: 6, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 133,
        page_end: 133,
        title: '给黄炎培的信',
        dates: [{ year: 1952, month: 6, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 134,
        page_end: 134,
        title: '给易礼容的信',
        dates: [{ year: 1952, month: 6, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 135,
        page_end: 135,
        title: '为中华全国体育总会成立大会题词',
        dates: [{ year: 1952, month: 6, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 137,
        page_end: 137,
        title: '对聂荣臻关于中南军区南迁问题的报告的批语',
        dates: [{ year: 1952, month: 6, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 138,
        page_end: 139,
        title: '中央转发出版总署关于发动交代关系和思想检查的总结报告的批语',
        dates: [{ year: 1952, month: 6, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 140,
        page_end: 140,
        title: '对空军司令部五月份战果报告的批语',
        dates: [{ year: 1952, month: 6, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 141,
        page_end: 141,
        title: '干部子弟学校应逐步废除',
        dates: [{ year: 1952, month: 6, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 142,
        page_end: 142,
        title: '关于来京开会问题致赛福鼎电',
        dates: [{ year: 1952, month: 6, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 143,
        page_end: 144,
        title: '为了解苏共关于中央机构设置的经验致斯大林电',
        dates: [{ year: 1952, month: 6, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 145,
        page_end: 145,
        title: '关于美国邀请印尼等五国视察美军巨济岛战俘营问题的批语',
        dates: [{ year: 1952, month: 6, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 146,
        page_end: 147,
        title: '中央转发朱德关于全党纪律检查工作总结报告的批语',
        dates: [{ year: 1952, month: 6, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 148,
        page_end: 148,
        title: '给毛泽连的信',
        dates: [{ year: 1952, month: 6, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 150,
        page_end: 150,
        title: '对原国民党军官费帖要求就业问题的来信的批语',
        dates: [{ year: 1952, month: 6, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 151,
        page_end: 152,
        title: '中央转发安子文关于中央机关三反处理阶段工作情况报告的批语',
        dates: [{ year: 1952, month: 6, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 153,
        page_end: 153,
        title: '为成渝铁路通车题词',
        dates: [{ year: 1952, month: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 155,
        page_end: 156,
        title: '对新疆农业区土改和牧区工作两个决议稿的批语',
        dates: [{ year: 1952, month: 7, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 157,
        page_end: 157,
        title: '关于解决军队干部子女入学入托问题的批语',
        dates: [{ year: 1952, month: 7, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 158,
        page_end: 158,
        title: '给张有成的信',
        dates: [{ year: 1952, month: 7, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 159,
        page_end: 159,
        title: '对彭德怀关于公安部队隶属关系的报告的批语',
        dates: [{ year: 1952, month: 7, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 160,
        page_end: 162,
        title: '对军事学院第一期毕业学员的训词',
        dates: [{ year: 1952, month: 7, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 163,
        page_end: 163,
        title: '给毛宇居的信',
        dates: [{ year: 1952, month: 7, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 164,
        page_end: 164,
        title: '给邹普勋的信',
        dates: [{ year: 1952, month: 7, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 166,
        page_end: 166,
        title: '同意志愿军兵员补充、部队轮换和整编结合进行的方案',
        dates: [{ year: 1952, month: 7, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 167,
        page_end: 168,
        title: '对达赖喇嘛来信的批语和复信',
        dates: [
          { year: 1952, month: 7, day: 11 },
          { year: 1952, month: 8, day: 18 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 169,
        page_end: 170,
        title: '对全军后勤组织和整编问题的批语',
        dates: [{ year: 1952, month: 7, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 171,
        page_end: 171,
        title: '对《人民日报》社论稿《日本人民争取独立的道路》的批语',
        dates: [{ year: 1952, month: 7, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 172,
        page_end: 172,
        title: '对军事建设五年计划的批语',
        dates: [{ year: 1952, month: 7, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 173,
        page_end: 173,
        title: '中央同意习仲勋关于新疆情况的分析和工作方针报告的电报',
        dates: [{ year: 1952, month: 7, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 174,
        page_end: 174,
        title: '关于检查财政机关及后勤部门对违反财政纪律的检讨情况的批语',
        dates: [{ year: 1952, month: 7, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 175,
        page_end: 175,
        title: '对吴晗再次要求入党的来信的批语',
        dates: [{ year: 1952, month: 7, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 176,
        page_end: 176,
        title:
          '在中央转发薄一波关于检查违反财政纪律的初步总结报告的批语稿上加写的话',
        dates: [{ year: 1952, month: 7, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 177,
        page_end: 177,
        title: '朝鲜战争结束前不要进行对大陈岛的作战',
        dates: [{ year: 1952, month: 7, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 178,
        page_end: 178,
        title: '对总后关于赴朝调查野战救护等工作的报告的批语',
        dates: [{ year: 1952, month: 7, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 179,
        page_end: 179,
        title: '关于“八一”发贺电问题给徐冰的信',
        dates: [{ year: 1952, month: 7, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 180,
        page_end: 180,
        title: '对关于向军委主席报告工作情况问题的批语',
        dates: [{ year: 1952, month: 8, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 181,
        page_end: 181,
        title:
          '对一九五一年度国家预算执行情况及一九五二年度国家预算草案的报告稿的批语和加写的话',
        dates: [{ year: 1952, month: 8, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 182,
        page_end: 182,
        title: '同意海军后勤建立垂直系统的意见',
        dates: [{ year: 1952, month: 8, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 183,
        page_end: 184,
        title: '对刘少奇关于加强党中央办事机构报告的批语',
        dates: [{ year: 1952, month: 8, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 185,
        page_end: 185,
        title: '对八九两月全国卫生运动具体要求的指示稿的批语和加写的话',
        dates: [{ year: 1952, month: 8, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 186,
        page_end: 186,
        title: '在中央转发华东局关于司法改革工作指示的批语稿上加写的话',
        dates: [{ year: 1952, month: 8, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 187,
        page_end: 189,
        title: '团结起来，划清敌我界限',
        dates: [{ year: 1952, month: 8, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 190,
        page_end: 191,
        title: '关于军费减少问题',
        dates: [{ year: 1952, month: 8, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 194,
        page_end: 194,
        title: '应基本谢绝黑水地区群众对军队的慰劳品',
        dates: [{ year: 1952, month: 8, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 195,
        page_end: 195,
        title: '祝贺朝鲜解放七周年的电报',
        dates: [{ year: 1952, month: 8, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 196,
        page_end: 196,
        title: '对烟潍铁路修建方案的批语',
        dates: [{ year: 1952, month: 8, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 197,
        page_end: 197,
        title: '给陈毅的信',
        dates: [{ year: 1952, month: 8, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 199,
        page_end: 199,
        title: '关于同意向东南亚国家出售大米的批语',
        dates: [{ year: 1952, month: 8, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 200,
        page_end: 200,
        title: '对肖向荣摘报的总后情况简报第一号的批语',
        dates: [{ year: 1952, month: 8, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 201,
        page_end: 201,
        title: '对政务院关于设置文史研究馆的决定草案的批语',
        dates: [{ year: 1952, month: 8, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 202,
        page_end: 202,
        title: '为康藏公路开工题词',
        dates: [{ year: 1952, month: 8, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 204,
        page_end: 204,
        title: '给毛宇居的信',
        dates: [{ year: 1952, month: 8, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 206,
        page_end: 206,
        title: '对增修两个机场报告的批语',
        dates: [{ year: 1952, month: 8, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 207,
        page_end: 207,
        title: '关于向朝鲜赠送冬服的批语',
        dates: [{ year: 1952, month: 8, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 208,
        page_end: 208,
        title: '对总政关于全军文化教育座谈会的报告的批语',
        dates: [{ year: 1952, month: 8, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 210,
        page_end: 210,
        title: '对聂荣臻关于中南军区部队二期整编工作报告的批语',
        dates: [{ year: 1952, month: 8, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 211,
        page_end: 211,
        title: '在总政关于全军体育运动大会总结报告上的批语',
        dates: [{ year: 1952, month: 8, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 215,
        page_end: 215,
        title: '关于同意苏联提出的旅顺口换文和移交中长路公告的电报',
        dates: [{ year: 1952, month: 8, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 216,
        page_end: 217,
        title: '给赛福鼎和帕哈太克里乡农民的信',
        dates: [{ year: 1952, month: 8, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 218,
        page_end: 218,
        title: '对军事学院关于遗失文件问题的报告的批语',
        dates: [{ year: 1952, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 219,
        page_end: 219,
        title: '为《四川日报》题写报头',
        dates: [{ year: 1952, month: 9, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 220,
        page_end: 220,
        title: '对赵尔陆关于二机部初建情况报告的批语',
        dates: [{ year: 1952, month: 9, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 221,
        page_end: 221,
        title: '对柯托夫关于空军飞行事故问题报告的批语',
        dates: [{ year: 1952, month: 9, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 222,
        page_end: 222,
        title: '庆祝抗日战争胜利七周年致斯大林电',
        dates: [{ year: 1952, month: 9, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 223,
        page_end: 224,
        title: '对全军整编情况和在朝作战部队轮换计划的批语',
        dates: [{ year: 1952, month: 9, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 225,
        page_end: 229,
        title: '对黄炎培一篇讲话稿的复信、批语和修改',
        dates: [
          { year: 1952, month: 9, day: 5 },
          { year: 1952, month: 9, day: 13 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 232,
        page_end: 232,
        title: '关于同意中、苏、蒙对修中蒙铁路的意见的电报',
        dates: [{ year: 1952, month: 9, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 233,
        page_end: 233,
        title: '对习仲勋在中共新疆省第二届代表会议上的报告的批语',
        dates: [{ year: 1952, month: 9, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 234,
        page_end: 234,
        title: '对军马疫病防治问题报告的批语',
        dates: [{ year: 1952, month: 9, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 235,
        page_end: 235,
        title: '对空军消灭飞行事故会议情况报告的批语',
        dates: [{ year: 1952, month: 9, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 236,
        page_end: 236,
        title: '关于提倡做提要的批语',
        dates: [{ year: 1952, month: 9, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 237,
        page_end: 237,
        title: '关于解决华北各地职工疾病问题的批语',
        dates: [{ year: 1952, month: 9, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 238,
        page_end: 238,
        title: '中央同意中财委关于清偿解放前人民存款问题的方案的批语',
        dates: [{ year: 1952, month: 9, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 239,
        page_end: 240,
        title: '关于联合国大会准备讨论朝鲜问题等致周恩来电',
        dates: [{ year: 1952, month: 9, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 241,
        page_end: 241,
        title: '给章汉夫的信',
        dates: [{ year: 1952, month: 9, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 242,
        page_end: 242,
        title: '关于不能接受墨西哥对战俘问题的三点建议的电报',
        dates: [{ year: 1952, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 243,
        page_end: 243,
        title: '在中央转发定西地委关于执行民族政策的检查报告的电报稿上加写的话',
        dates: [{ year: 1952, month: 9, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 244,
        page_end: 244,
        title: '关于朝鲜前线阵地播音问题的批语',
        dates: [{ year: 1952, month: 9, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 245,
        page_end: 245,
        title: '对水利部关于汉江黄家场决口后情况报告的批语',
        dates: [{ year: 1952, month: 9, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 246,
        page_end: 246,
        title: '给李达的信',
        dates: [{ year: 1952, month: 9, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 248,
        page_end: 248,
        title: '给李贡人的信',
        dates: [{ year: 1952, month: 9, day: 17 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 249,
        page_end: 249,
        title: '为爱晚亭题名',
        dates: [{ year: 1952, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 251,
        page_end: 252,
        title: '关于较重要外交复文的送审问题的批语',
        dates: [
          { year: 1952, month: 9, day: 17 },
          { year: 1952, month: 9, day: 18 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 253,
        page_end: 253,
        title: '对轻工业部七八两月工作综合报告的批语',
        dates: [{ year: 1952, month: 9, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 254,
        page_end: 254,
        title: '关于《毛泽东选集》俄译本分卷问题致周恩来电',
        dates: [{ year: 1952, month: 9, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 255,
        page_end: 255,
        title: '关于实行小仓库制问题的批语',
        dates: [{ year: 1952, month: 9, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 256,
        page_end: 256,
        title: '致阜新发电厂工程队职工电',
        dates: [{ year: 1952, month: 9, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 257,
        page_end: 257,
        title: '关于发表周恩来离莫斯科时在机场的谈话给章汉夫等的信',
        dates: [{ year: 1952, month: 9, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 258,
        page_end: 258,
        title: '关于由东北帮助朝鲜收容孤儿和办工业大学复高岗等电',
        dates: [{ year: 1952, month: 9, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 259,
        page_end: 259,
        title: '关于高岗早日来中央工作的电报',
        dates: [{ year: 1952, month: 9, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 260,
        page_end: 260,
        title: '对章汉夫检讨的批语',
        dates: [{ year: 1952, month: 9, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 261,
        page_end: 261,
        title: '对《人民日报》国庆社论提纲草稿的批语',
        dates: [{ year: 1952, month: 9, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 262,
        page_end: 262,
        title: '对王观澜关于开凿胶莱运河建议的批语',
        dates: [{ year: 1952, month: 9, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 263,
        page_end: 263,
        title: '对《社会情报辑要》第三十一号的批语',
        dates: [{ year: 1952, month: 9, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 264,
        page_end: 264,
        title: '接受印度驻华大使赖嘉文呈递国书时的答词',
        dates: [{ year: 1952, month: 9, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 266,
        page_end: 266,
        title: '中央转发安子文关于整党建党工作报告的批语',
        dates: [{ year: 1952, month: 9, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 267,
        page_end: 268,
        title: '给黄炎培的信',
        dates: [{ year: 1952, month: 9, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 269,
        page_end: 269,
        title: '为天兰路全线通车题词',
        dates: [{ year: 1952, month: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 271,
        page_end: 271,
        title: '在国庆宴会上的讲话',
        dates: [{ year: 1952, month: 9, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 275,
        page_end: 275,
        title: '谢觉哉摘要转报的中央湖北灾情视察组报告的批语',
        dates: [{ year: 1952, month: 10, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 276,
        page_end: 276,
        title: '给毛宇居的信',
        dates: [{ year: 1952, month: 10, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 277,
        page_end: 277,
        title: '给谭熙春的信',
        dates: [{ year: 1952, month: 10, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 278,
        page_end: 278,
        title: '祝贺亚洲及太平洋区域和平会议召开的电报',
        dates: [{ year: 1952, month: 10, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 280,
        page_end: 280,
        title: '关于胡志明去莫斯科和致苏共十九大贺电致刘少奇电',
        dates: [{ year: 1952, month: 10, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 281,
        page_end: 281,
        title: '给齐白石的信',
        dates: [{ year: 1952, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 283,
        page_end: 283,
        title: '祝贺德意志民主共和国成立三周年的电报',
        dates: [{ year: 1952, month: 10, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 284,
        page_end: 284,
        title: '对罗瑞卿关于一起杀人案的判处意见的批语',
        dates: [{ year: 1952, month: 10, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 285,
        page_end: 285,
        title: '对聂荣臻关于志愿军第二步反击已取得初步胜利的报告的批语',
        dates: [{ year: 1952, month: 10, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 286,
        page_end: 286,
        title: '为《后勤通讯》题名',
        dates: [{ year: 1952, month: 10, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 287,
        page_end: 288,
        title: '接见西藏致敬团代表的谈话要点',
        dates: [{ year: 1952, month: 10, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 289,
        page_end: 289,
        title: '给宋庆龄的信',
        dates: [{ year: 1952, month: 10, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 291,
        page_end: 291,
        title: '给毛爱桂的信',
        dates: [{ year: 1952, month: 10, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 292,
        page_end: 292,
        title: '对铁道部队建设报告的批语',
        dates: [{ year: 1952, month: 10, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 293,
        page_end: 293,
        title: '关于国民党军队给其在大陆残余力量空投装备问题的批语',
        dates: [{ year: 1952, month: 10, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 294,
        page_end: 298,
        title: '人民革命军事委员会关于纠正放松军事教育和纪律废弛现象的指示',
        dates: [{ year: 1952, month: 10, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 299,
        page_end: 300,
        title: '必须切实解决农民负担过重问题',
        dates: [{ year: 1952, month: 10, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 301,
        page_end: 301,
        title: '对海军党委综合报告的批语',
        dates: [{ year: 1952, month: 10, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 302,
        page_end: 302,
        title: '对总后关于追加一九五二年国防建设费预算的报告的批语',
        dates: [{ year: 1952, month: 10, day: 18 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 303,
        page_end: 303,
        title: '关于中央同意刘少奇、王稼祥在苏休养的电报',
        dates: [{ year: 1952, month: 10, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 304,
        page_end: 304,
        title: '对民主同盟工作的意见',
        dates: [{ year: 1952, month: 10, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 305,
        page_end: 305,
        title: '给罗元鲲的信',
        dates: [{ year: 1952, month: 10, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 306,
        page_end: 306,
        title: '对军委办公厅关于贯彻反官僚主义问题报告的批语',
        dates: [{ year: 1952, month: 10, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 307,
        page_end: 308,
        title: '祝贺中国人民志愿军的重大胜利',
        dates: [{ year: 1952, month: 10, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 310,
        page_end: 311,
        title: '中央转发中纪委报告的批语',
        dates: [{ year: 1952, month: 10, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 312,
        page_end: 312,
        title: '对颁发八一奖章荣誉奖章条例报告的批语',
        dates: [{ year: 1952, month: 10, day: 24 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 320,
        page_end: 320,
        title: '视察黄河时的谈话',
        dates: [{ year: 1952, month: 10, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 325,
        page_end: 325,
        title: '为袁仲谦题写碑文',
        dates: [{ year: 1952, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 327,
        page_end: 327,
        title: '为《团结报》题写报头',
        dates: [{ year: 1952, month: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 328,
        page_end: 328,
        title: '祝贺十月革命三十五周年致斯大林电',
        dates: [{ year: 1952, month: 11, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 329,
        page_end: 329,
        title: '对改善志愿军部队物质生活和精神生活情况报告的批语',
        dates: [{ year: 1952, month: 11, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 330,
        page_end: 331,
        title:
          '对杨成武关于苏联顾问可否参加部队党委会议的请示报告的批语和对军委复电稿的修改',
        dates: [
          { year: 1952, month: 11, day: 7 },
          { year: 1952, month: 11, day: 11 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 332,
        page_end: 332,
        title: '关于罗瑞卿传达实现社会主义的时间问题给各同志的信',
        dates: [{ year: 1952, month: 11, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 333,
        page_end: 334,
        title: '美帝国主义要打下去就只有失败',
        dates: [{ year: 1952, month: 11, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 335,
        page_end: 336,
        title: '对中央关于调整商业的指示稿的批语和修改',
        dates: [{ year: 1952, month: 11, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 337,
        page_end: 337,
        title: '为全国各级军校毕业证书题词',
        dates: [{ year: 1952, month: 11, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 339,
        page_end: 339,
        title: '中央关于印发贯彻婚姻法的指示的批语',
        dates: [{ year: 1952, month: 11, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 341,
        page_end: 341,
        title: '对贺诚关于召开第二届全国卫生会议的报告的批语',
        dates: [{ year: 1952, month: 11, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 342,
        page_end: 342,
        title: '在中央对全总党组报告的批语稿中加写的话',
        dates: [{ year: 1952, month: 11, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 343,
        page_end: 343,
        title: '对成立军委兵役法研究委员会报告的批语',
        dates: [{ year: 1952, month: 11, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 344,
        page_end: 344,
        title: '在中央转发的中财委党组关于增产节约运动给邮电部的指示中加写的话',
        dates: [{ year: 1952, month: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 345,
        page_end: 346,
        title: '各地应设立捕歼空降特务的武装据点',
        dates: [{ year: 1952, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 347,
        page_end: 347,
        title: '对《一九五三年兵工生产会议备忘录》的批语',
        dates: [{ year: 1952, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 348,
        page_end: 348,
        title: '对聂荣臻关于今冬动员新兵三十五万人的计划的批语',
        dates: [{ year: 1952, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 349,
        page_end: 349,
        title:
          '对华东局关于上海国棉二厂团结技术人员解决生产关键问题的经验通报的批语',
        dates: [{ year: 1952, month: 12, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 352,
        page_end: 352,
        title: '在外交部一份外交工作汇报上的批语',
        dates: [{ year: 1952, month: 12, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 353,
        page_end: 353,
        title: '接受瑞典驻华大使魏斯特朗呈递国书时的答词',
        dates: [{ year: 1952, month: 12, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 354,
        page_end: 354,
        title: '致班禅额尔德尼电',
        dates: [{ year: 1952, month: 12, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 355,
        page_end: 355,
        title: '部队每年应进行点验一次至二次',
        dates: [{ year: 1952, month: 12, day: 6 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 356,
        page_end: 357,
        title: '关于组织部队机关干部轮换到朝鲜战场锻炼的批语',
        dates: [
          { year: 1952, month: 12, day: 6 },
          { year: 1952, month: 12, day: 19 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 358,
        page_end: 358,
        title: '为第二届爱国卫生工作会议题词',
        dates: [{ year: 1952, month: 12, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 360,
        page_end: 360,
        title: '关于志愿军必须火急准备粉碎敌人登陆计划的电报',
        dates: [{ year: 1952, month: 12, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 361,
        page_end: 361,
        title:
          '对中宣部关于在京高级干部学习《苏联社会主义经济问题》等的情况报告的批语',
        dates: [{ year: 1952, month: 12, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 362,
        page_end: 363,
        title: '在邓华关于朝鲜战局形势与明年方针任务的报告上的批语',
        dates: [{ year: 1952, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 364,
        page_end: 364,
        title:
          '对肖华关于朝鲜要求提供为加强瓦解敌伪军工作所需的印刷宣传器材等的报告的批语',
        dates: [{ year: 1952, month: 12, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 365,
        page_end: 365,
        title: '对陈伯达等关于筹备马克思主义教师学校等问题的报告的批语',
        dates: [{ year: 1952, month: 12, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 366,
        page_end: 366,
        title:
          '对中宣部关于成立马克思主义教师学校和马恩列斯著作编译所具体事宜的请示报告的批语',
        dates: [{ year: 1952, month: 12, day: 10 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 367,
        page_end: 368,
        title: '对有关防敌在志愿军侧后登陆等问题的批语',
        dates: [
          { year: 1952, month: 12, day: 11 },
          { year: 1952, month: 12, day: 27 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 369,
        page_end: 369,
        title: '中央关于将召开党的全国代表会议致刘少奇电',
        dates: [{ year: 1952, month: 12, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 370,
        page_end: 370,
        title: '加紧准备打敌在我后方登陆',
        dates: [{ year: 1952, month: 12, day: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 371,
        page_end: 371,
        title: '对肖克关于军训部与苏联顾问合作问题的总结报告的批语',
        dates: [{ year: 1952, month: 12, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 372,
        page_end: 372,
        title: '给鞍山钢铁公司炼钢厂全体职工的信',
        dates: [{ year: 1952, month: 12, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 373,
        page_end: 373,
        title: '接受苏联驻华大使潘友新呈递国书时的答词',
        dates: [{ year: 1952, month: 12, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 375,
        page_end: 375,
        title: '对海军党委反官僚主义布置的批语',
        dates: [{ year: 1952, month: 12, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 376,
        page_end: 378,
        title: '中央转发安子文两个报告的批语和毛泽东给安子文的信',
        dates: [{ year: 1952, month: 12, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 379,
        page_end: 379,
        title: '对薄一波关于乡镇摊派名目繁多问题的报告的批语',
        dates: [{ year: 1952, month: 12, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 380,
        page_end: 380,
        title: '对统战部关于查询苏南破坏寺庙情况的电报的批语',
        dates: [{ year: 1952, month: 12, day: 19 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 381,
        page_end: 383,
        title: '准备一切必要条件，坚决粉碎敌人登陆冒险',
        dates: [{ year: 1952, month: 12, day: 20 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 384,
        page_end: 385,
        title: '对东北农村工作会议有关文件的批语',
        dates: [{ year: 1952, month: 12, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 386,
        page_end: 386,
        title: '给易南屏的信',
        dates: [{ year: 1952, month: 12, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 388,
        page_end: 389,
        title: '对中央转发三年来侨汇、华侨投资情况报告的批语稿的修改',
        dates: [{ year: 1952, month: 12, day: 22 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 390,
        page_end: 390,
        title: '对薄一波关于修建福建铁路问题的报告的批语',
        dates: [{ year: 1952, month: 12, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 392,
        page_end: 392,
        title: '对高岗报送的在苏共十九大文件学习讨论会上的发言的批语',
        dates: [{ year: 1952, month: 12, day: 25 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 393,
        page_end: 394,
        title: '同意反登陆作战准备等项军事部署',
        dates: [{ year: 1952, month: 12, day: 27 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 395,
        page_end: 396,
        title: '中央和军委关于加强防敌进攻福建沿海的指示',
        dates: [{ year: 1952, month: 12, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 397,
        page_end: 397,
        title: '关于采用会议简报办法的批语',
        dates: [{ year: 1952, month: 12, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 398,
        page_end: 398,
        title: '明年应建立兵役机构',
        dates: [{ year: 1952, month: 12, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 399,
        page_end: 400,
        title: '关于解决志愿军坑道部队日用品供给问题的批语',
        dates: [{ year: 1952, month: 12, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 401,
        page_end: 401,
        title: '对总干部部关于检查与苏联顾问关系的报告的批语',
        dates: [{ year: 1952, month: 12, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 402,
        page_end: 402,
        title: '对西藏工委关于成立农牧部未报中央的检讨的批语',
        dates: [{ year: 1952, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 403,
        page_end: 403,
        title: '对权五稷祝贺毛泽东生日电报的批语',
        dates: [{ year: 1952, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 404,
        page_end: 404,
        title: '接受罗马尼亚驻华大使郭佐文呈递国书时的答词',
        dates: [{ year: 1952, month: 12, day: 29 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 405,
        page_end: 406,
        title:
          '中央转发妇联党组关于当前妇女参加农业生产的情况和存在问题的报告的批语',
        dates: [{ year: 1952, month: 12, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 407,
        page_end: 407,
        title: '感谢苏联将中国长春铁路的一切权利和财产移交中国致斯大林电',
        dates: [{ year: 1952, month: 12, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 408,
        page_end: 408,
        title: '党对政府工作的领导责任',
        dates: [{ year: 1952, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 410,
        page_end: 410,
        title: '为《广州日报》题写报头',
        dates: [{ year: 1952, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 412,
        page_end: 412,
        title: '为蔡协民烈士遗像题字',
        dates: [{ year: 1952, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 413,
        page_end: 413,
        title: '为《人民装甲兵》题名',
        dates: [{ year: 1952, month: 12 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 414,
        page_end: 414,
        title: '为《中国工运》题名',
        dates: [{ year: 1952 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 416,
        page_end: 416,
        title: '为罗元鲲旧居题字',
        dates: [{ year: 1952 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 419,
        page_end: 420,
        title: '转发肖向荣关于各军事部门与苏联顾问的关系的总结的批语',
        dates: [{ year: 1953, month: 1, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 421,
        page_end: 422,
        title: '关于确定康藏公路线路问题的批语',
        dates: [{ year: 1953, month: 1, day: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 423,
        page_end: 423,
        title: '在罗瑞卿关于敌人破坏我企业生产的综合报告上的批语',
        dates: [{ year: 1953, month: 1, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 424,
        page_end: 425,
        title: '对曾山、姚依林关于商业问题的来信的批语',
        dates: [{ year: 1953, month: 1, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 428,
        page_end: 430,
        title: '中央关于反对官僚主义、反对命令主义、反对违法乱纪的指示',
        dates: [{ year: 1953, month: 1, day: 5 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 431,
        page_end: 431,
        title: '给总高级步兵学校的训词',
        dates: [{ year: 1953, month: 1, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 432,
        page_end: 432,
        title: '给黄炎培的信',
        dates: [{ year: 1953, month: 1, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 433,
        page_end: 434,
        title: '对安子文关于原察哈尔省农村整党工作的报告的批语',
        dates: [{ year: 1953, month: 1, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 435,
        page_end: 436,
        title: '关于领导责任和领导方法问题的批语',
        dates: [{ year: 1953, month: 1, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 438,
        page_end: 438,
        title: '关于抗议敌方屠杀战俘问题的处理意见的电报',
        dates: [{ year: 1953, month: 1, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 439,
        page_end: 444,
        title: '关于召开全国人民代表大会的几点说明',
        dates: [{ year: 1953, month: 1, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 445,
        page_end: 445,
        title: '关于召开全国和地方各级人民代表大会问题的讲话',
        dates: [{ year: 1953, month: 1, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 446,
        page_end: 446,
        title: '军委对中南军区关于海防检查及今后建设意见的报告的批语',
        dates: [{ year: 1953, month: 1, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 447,
        page_end: 447,
        title: '对总政关于一九五二年敌军工作报告的批语',
        dates: [{ year: 1953, month: 1, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 448,
        page_end: 449,
        title: '对国家计委关于一九五三年第一季度工作要点的批语',
        dates: [{ year: 1953, month: 1, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 450,
        page_end: 450,
        title: '关于新税制问题给周恩来等的信',
        dates: [{ year: 1953, month: 1, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 451,
        page_end: 451,
        title: '对新华社《内部参考》的意见',
        dates: [{ year: 1953, month: 1, day: 16 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 452,
        page_end: 452,
        title: '对军委关于秘密文件的保密工作细则的批语',
        dates: [{ year: 1953, month: 1, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 453,
        page_end: 453,
        title: '对李克农等关于俘虏管理工作请示的批语',
        dates: [{ year: 1953, month: 1, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 454,
        page_end: 458,
        title: '对文字改革工作的指示及一些问题的回答',
        dates: [{ year: 1953, month: 1, day: 26 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 459,
        page_end: 459,
        title: '关于对印度遣俘提案的态度问题的批语',
        dates: [{ year: 1953, month: 1, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 460,
        page_end: 461,
        title: '关于编印公安局长违法乱纪事例的小册子的批语',
        dates: [{ year: 1953, month: 1, day: 30 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 462,
        page_end: 462,
        title: '给后勤学院的训词',
        dates: [{ year: 1953, month: 1, day: 31 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 463,
        page_end: 463,
        title: '为《八一杂志》题名',
        dates: [{ year: 1953, month: 1 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 464,
        page_end: 464,
        title: '关于转发《河北省农村基层干部违法乱纪情况严重》一稿给新华社的信',
        dates: [{ year: 1953, month: 2, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 465,
        page_end: 465,
        title: '中央转发河北省委关于扩军工作的报告的批语',
        dates: [{ year: 1953, month: 2, day: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 466,
        page_end: 467,
        title: '在军队干部评级工作总结和实施军衔制度报告上的批语',
        dates: [
          { year: 1953, month: 2, day: 2 },
          { year: 1953, month: 2, day: 11 },
          { year: 1953, month: 2, day: 14 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 468,
        page_end: 469,
        title: '关于加强上海防空工作的批语',
        dates: [
          { year: 1953, month: 2, day: 4 },
          { year: 1953, month: 2, day: 9 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 470,
        page_end: 471,
        title: '对安子文关于反对官僚主义的发言稿的批语和修改',
        dates: [
          { year: 1953, month: 2, day: 6 },
          { year: 1953, month: 2, day: 7 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 472,
        page_end: 477,
        title: '在全国政协一届四次会议闭幕会上的讲话',
        dates: [{ year: 1953, month: 2, day: 7 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 483,
        page_end: 483,
        title: '关于讨论一九五三年国家概算表等问题的批语',
        dates: [{ year: 1953, month: 2, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 484,
        page_end: 484,
        title: '对空军配合志愿军反敌登陆作战报告的批语',
        dates: [{ year: 1953, month: 2, day: 8 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 485,
        page_end: 486,
        title: '中央转发安子文关于目前整党建党情况报告的批语',
        dates: [{ year: 1953, month: 2, day: 9 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 487,
        page_end: 489,
        title: '对薄一波关于一九五三年国家预算报告稿的批语和修改',
        dates: [
          { year: 1953, month: 2, day: 9 },
          { year: 1953, month: 2, day: 13 },
        ],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 490,
        page_end: 491,
        title: '关于揭露对方破坏协议、击伤我方代表团工作人员等问题的电报',
        dates: [{ year: 1953, month: 2, day: 11 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 492,
        page_end: 492,
        title: '军委转发陈毅关于华东军区开展反官僚主义斗争的电报的批语',
        dates: [{ year: 1953, month: 2, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 493,
        page_end: 493,
        title: '关于检查改进政府部门工作问题的批语',
        dates: [{ year: 1953, month: 2, day: 13 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 494,
        page_end: 495,
        title:
          '中央转发罗瑞卿关于在公安系统开展反官僚主义、反命令主义、反违法乱纪斗争的报告的批语',
        dates: [{ year: 1953, month: 2, day: 14 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 496,
        page_end: 496,
        title: '中央关于印行农业生产互助合作正式决议的通知',
        dates: [{ year: 1953, month: 2, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 497,
        page_end: 497,
        title: '对薄一波关于私营轮船公司合营问题的报告的批语',
        dates: [{ year: 1953, month: 2, day: 15 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 498,
        page_end: 499,
        title: '我在此次旅行中所收集的意见',
        dates: [
          { year: 1953, month: 2, day: 15 },
          { year: 1953, month: 2, day: 26 },
        ],
        is_range_date: true,
        authors: ['毛泽东'],
      },
      {
        page_start: 504,
        page_end: 504,
        title: '为人民海军题词',
        dates: [{ year: 1953, month: 2, day: 21 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 520,
        page_end: 520,
        title: '为《新华日报》题写报头',
        dates: [{ year: 1953, month: 2, day: 23 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 526,
        page_end: 526,
        title: '在反官僚主义斗争中研究加强思想领导和政治领导LA',
        dates: [{ year: 1953, month: 2, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 527,
        page_end: 527,
        title: '关于移载台湾大道通讯社两条消息的批语',
        dates: [{ year: 1953, month: 2, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 528,
        page_end: 528,
        title: '对陈云病况报告的批语',
        dates: [{ year: 1953, month: 2, day: 28 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 529,
        page_end: 529,
        title: '为《抗美援朝专刊》题名',
        dates: [{ year: 1953, month: 2 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 530,
        page_end: 531,
        title: '关于政府方面要经中央批准的事请邓小平多管一些的批语',
        dates: [{ year: 1953, month: 3, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 532,
        page_end: 533,
        title: '中央转发习仲勋关于文委分党组布置反官僚主义斗争的报告的批语',
        dates: [{ year: 1953, month: 3, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 534,
        page_end: 534,
        title: '在日侨回国工作简报上的批语',
        dates: [{ year: 1953, month: 3, day: 3 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
      {
        page_start: 535,
        page_end: 535,
        title: '中央转发华北局关于春耕生产的指示的批语',
        dates: [{ year: 1953, month: 3, day: 4 }],
        is_range_date: false,
        authors: ['毛泽东'],
      },
    ],
    ext: 'pdf',
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives0/mao-quanji/maoquanji32.pdf',
};
