export default {
  entity: {
    id: 'maoquanji16',
    name: '毛泽东全集第16卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives8/main/maoquanji16.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '中国共产党对苏日中立条约发表意见',
        authors: ['毛泽东'],
        page_start: 31,
        page_end: 32,
        dates: [{ year: 1941, month: 4, day: 16 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 33,
        page_end: 33,
        dates: [{ year: 1941, month: 4, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致彭雪枫电',
        authors: ['毛泽东'],
        page_start: 34,
        page_end: 34,
        dates: [{ year: 1941, month: 4, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致贺龙、关向应等电',
        authors: ['毛泽东'],
        page_start: 35,
        page_end: 35,
        dates: [{ year: 1941, month: 4, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致彭雪枫等电',
        authors: ['毛泽东'],
        page_start: 36,
        page_end: 36,
        dates: [{ year: 1941, month: 4, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致彭雪枫等电',
        authors: ['毛泽东'],
        page_start: 37,
        page_end: 37,
        dates: [{ year: 1941, month: 4, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀、左权等电',
        authors: ['毛泽东'],
        page_start: 38,
        page_end: 38,
        dates: [{ year: 1941, month: 4, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 39,
        page_end: 39,
        dates: [{ year: 1941, month: 4, day: 20 }],
        is_range_date: false,
      },
      {
        title: '日苏缔约后英美及中国各派政治力量态度的分析',
        authors: ['毛泽东'],
        page_start: 40,
        page_end: 41,
        dates: [{ year: 1941, month: 4, day: 20 }],
        is_range_date: false,
      },
      {
        title: '关于国共继续团结抗日问题致周恩来电',
        authors: ['毛泽东'],
        page_start: 42,
        page_end: 42,
        dates: [{ year: 1941, month: 4, day: 26 }],
        is_range_date: false,
      },
      {
        title: '给任时的信',
        authors: ['毛泽东'],
        page_start: 43,
        page_end: 44,
        dates: [{ year: 1941, month: 4, day: 28 }],
        is_range_date: false,
      },
      {
        title: '发展上海到福州广大地区的游击战争',
        authors: ['毛泽东'],
        page_start: 45,
        page_end: 47,
        dates: [{ year: 1941, month: 4, day: 30 }],
        is_range_date: false,
      },
      {
        title: '硬甘宁边区施政纲领',
        authors: ['毛泽东'],
        page_start: 48,
        page_end: 52,
        dates: [{ year: 1941, month: 5, day: 1 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 53,
        page_end: 53,
        dates: [{ year: 1941, month: 5, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致陈毅等电',
        authors: ['毛泽东'],
        page_start: 54,
        page_end: 54,
        dates: [{ year: 1941, month: 5, day: 5 }],
        is_range_date: false,
      },
      {
        title: '给周恩来的信',
        authors: ['毛泽东'],
        page_start: 55,
        page_end: 55,
        dates: [{ year: 1941, month: 5, day: 5 }],
        is_range_date: false,
      },
      {
        title: '关于打退第二次反共高潮的总结',
        authors: ['毛泽东'],
        page_start: 56,
        page_end: 60,
        dates: [{ year: 1941, month: 5, day: 8 }],
        is_range_date: false,
      },
      {
        title: '复周恩来电',
        authors: ['毛泽东'],
        page_start: 61,
        page_end: 61,
        dates: [{ year: 1941, month: 5, day: 8 }],
        is_range_date: false,
      },
      {
        title: '当前形势与我们的方针',
        authors: ['毛泽东'],
        page_start: 62,
        page_end: 63,
        dates: [{ year: 1941, month: 5, day: 9 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 64,
        page_end: 64,
        dates: [{ year: 1941, month: 5, day: 10 }],
        is_range_date: false,
      },
      {
        title: '致陈毅、刘少奋电',
        authors: ['毛泽东'],
        page_start: 65,
        page_end: 65,
        dates: [{ year: 1941, month: 5, day: 12 }],
        is_range_date: false,
      },
      {
        title: '为护士节题词',
        authors: ['毛泽东'],
        page_start: 66,
        page_end: 67,
        dates: [{ year: 1941, month: 5, day: 12 }],
        is_range_date: false,
      },
      {
        title: '团结对敌有计划地配合友军作战',
        authors: ['毛泽东'],
        page_start: 68,
        page_end: 68,
        dates: [{ year: 1941, month: 5, day: 14 }],
        is_range_date: false,
      },
      {
        title: '关于华北我军配合国民党对日作战等问题的指示',
        authors: ['毛泽东'],
        page_start: 69,
        page_end: 70,
        dates: [{ year: 1941, month: 5, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致廖承志电',
        authors: ['毛泽东'],
        page_start: 71,
        page_end: 71,
        dates: [{ year: 1941, month: 5, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 72,
        page_end: 72,
        dates: [{ year: 1941, month: 5, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀、左权电',
        authors: ['毛泽东'],
        page_start: 73,
        page_end: 73,
        dates: [{ year: 1941, month: 5, day: 15 }],
        is_range_date: false,
      },
      {
        title: '八路军新四军均在敌后猛击敌人',
        authors: ['毛泽东'],
        page_start: 74,
        page_end: 74,
        dates: [{ year: 1941, month: 5, day: 15 }],
        is_range_date: false,
      },
      {
        title: '关于出版《解放日报》和改进新华社工作的通知',
        authors: ['毛泽东'],
        page_start: 75,
        page_end: 76,
        dates: [{ year: 1941, month: 5, day: 15 }],
        is_range_date: false,
      },
      {
        title: '延安《解放日报》发刊词',
        authors: ['毛泽东'],
        page_start: 77,
        page_end: 78,
        dates: [{ year: 1941, month: 5, day: 16 }],
        is_range_date: false,
      },
      {
        title: '为《解放日报》题写报头',
        authors: ['毛泽东'],
        page_start: 79,
        page_end: 79,
        dates: [{ year: 1941, month: 5, day: 16 }],
        is_range_date: false,
      },
      {
        title: '请看今日之域中竞是谁家之天下',
        authors: ['毛泽东'],
        page_start: 80,
        page_end: 84,
        dates: [{ year: 1941, month: 5, day: 18 }],
        is_range_date: false,
      },
      {
        title: '改造我们的学习叫',
        authors: ['毛泽东'],
        page_start: 85,
        page_end: 96,
        dates: [{ year: 1941, month: 5, day: 19 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话叫',
        authors: ['毛泽东'],
        page_start: 97,
        page_end: 97,
        dates: [{ year: 1941, month: 5, day: 20 }],
        is_range_date: false,
      },
      {
        title: '谨防扒手',
        authors: ['毛泽东'],
        page_start: 98,
        page_end: 100,
        dates: [{ year: 1941, month: 5, day: 23 }],
        is_range_date: false,
      },
      {
        title: '延安评论家对时局之评论',
        authors: ['毛泽东'],
        page_start: 101,
        page_end: 101,
        dates: [{ year: 1941, month: 5, day: 24 }],
        is_range_date: false,
      },
      {
        title: '揭破远东慕尼黑的阴课',
        authors: ['毛泽东'],
        page_start: 102,
        page_end: 102,
        dates: [{ year: 1941, month: 5, day: 25 }],
        is_range_date: false,
      },
      {
        title: '关于目前形势和统一宣传问题致八路军新四军各负责人电',
        authors: ['毛泽东'],
        page_start: 103,
        page_end: 103,
        dates: [{ year: 1941, month: 5, day: 25 }],
        is_range_date: false,
      },
      {
        title: '给王履孚、甄玉莹等的信',
        authors: ['毛泽东'],
        page_start: 104,
        page_end: 104,
        dates: [{ year: 1941, month: 5, day: 25 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 105,
        page_end: 105,
        dates: [{ year: 1941, month: 5, day: 26 }],
        is_range_date: false,
      },
      {
        title: '致卫立焊电',
        authors: ['毛泽东'],
        page_start: 106,
        page_end: 106,
        dates: [{ year: 1941, month: 5, day: 26 }],
        is_range_date: false,
      },
      {
        title: '复周恩来电',
        authors: ['毛泽东'],
        page_start: 107,
        page_end: 107,
        dates: [{ year: 1941, month: 5, day: 26 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 108,
        page_end: 108,
        dates: [{ year: 1941, month: 5, day: 26 }],
        is_range_date: false,
      },
      {
        title: '谣言与烟幕',
        authors: ['毛泽东'],
        page_start: 109,
        page_end: 112,
        dates: [{ year: 1941, month: 5, day: 28 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 113,
        page_end: 113,
        dates: [{ year: 1941, month: 5, day: 30 }],
        is_range_date: false,
      },
      {
        title: '延安评论家称炉边闲话具有两面性',
        authors: ['毛泽东'],
        page_start: 114,
        page_end: 115,
        dates: [{ year: 1941, month: 5, day: 30 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 116,
        page_end: 116,
        dates: [{ year: 1941, month: 5, day: 31 }],
        is_range_date: false,
      },
      {
        title: '为“抗大五周年纪念特刊”题词',
        authors: ['毛泽东'],
        page_start: 117,
        page_end: 117,
        dates: [{ year: 1941, month: 5 }],
        is_range_date: false,
      },
      {
        title: '为陈叔亮《解放区速写》画册题字',
        authors: ['毛泽东'],
        page_start: 118,
        page_end: 119,
        dates: [{ year: 1941, month: 5 }],
        is_range_date: false,
      },
      {
        title: '军委关于陵甘宁边区部队生产工作的指示',
        authors: ['毛泽东'],
        page_start: 120,
        page_end: 121,
        dates: [{ year: 1941, month: 5 }],
        is_range_date: false,
      },
      {
        title: '延安评论家之评论',
        authors: ['毛泽东'],
        page_start: 122,
        page_end: 122,
        dates: [{ year: 1941, month: 6, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 123,
        page_end: 123,
        dates: [{ year: 1941, month: 6, day: 6 }],
        is_range_date: false,
      },
      {
        title: '给凯丰、胡乔木的批语叫',
        authors: ['毛泽东'],
        page_start: 124,
        page_end: 124,
        dates: [{ year: 1941, month: 6, day: 6 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 125,
        page_end: 125,
        dates: [{ year: 1941, month: 6, day: 7 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀、左权等电',
        authors: ['毛泽东'],
        page_start: 126,
        page_end: 126,
        dates: [{ year: 1941, month: 6, day: 7 }],
        is_range_date: false,
      },
      {
        title: '与友军配合作战坚决破坏敌之进攻',
        authors: ['毛泽东'],
        page_start: 127,
        page_end: 129,
        dates: [{ year: 1941, month: 6, day: 9 }],
        is_range_date: false,
      },
      {
        title: '河北平原反“蚕食”斗争的政策',
        authors: ['毛泽东'],
        page_start: 130,
        page_end: 131,
        dates: [{ year: 1941, month: 6, day: 9 }],
        is_range_date: false,
      },
      {
        title: '目前我党方针是拉蒋抗战',
        authors: ['毛泽东'],
        page_start: 132,
        page_end: 132,
        dates: [{ year: 1941, month: 6, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀、无权、罗瑞卿电',
        authors: ['毛泽东'],
        page_start: 133,
        page_end: 135,
        dates: [{ year: 1941, month: 6, day: 13 }],
        is_range_date: false,
      },
      {
        title: '国民党缺少什么',
        authors: ['毛泽东'],
        page_start: 136,
        page_end: 139,
        dates: [{ year: 1941, month: 6, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 140,
        page_end: 140,
        dates: [{ year: 1941, month: 6, day: 17 }],
        is_range_date: false,
      },
      {
        title: '关于反法西斯的国际统一战线',
        authors: ['毛泽东'],
        page_start: 141,
        page_end: 141,
        dates: [{ year: 1941, month: 6, day: 23 }],
        is_range_date: false,
      },
      {
        title: '复彭德怀、左权、罗瑞卿电',
        authors: ['毛泽东'],
        page_start: 142,
        page_end: 142,
        dates: [{ year: 1941, month: 6, day: 23 }],
        is_range_date: false,
      },
      {
        title: '当前时局与我们的方针',
        authors: ['毛泽东'],
        page_start: 143,
        page_end: 143,
        dates: [{ year: 1941, month: 6, day: 26 }],
        is_range_date: false,
      },
      {
        title: '抗战中对大地主大资产阶级实行一拉一打政策',
        authors: ['毛泽东'],
        page_start: 144,
        page_end: 144,
        dates: [{ year: 1941, month: 6, day: 28 }],
        is_range_date: false,
      },
      {
        title: '复彭雪枫电',
        authors: ['毛泽东'],
        page_start: 145,
        page_end: 145,
        dates: [{ year: 1941, month: 6, day: 28 }],
        is_range_date: false,
      },
      {
        title: '关于中国共产党诞生二十周年、抗战四周年纪念的指示',
        authors: ['毛泽东'],
        page_start: 146,
        page_end: 147,
        dates: [{ year: 1941, month: 6 }],
        is_range_date: false,
      },
      {
        title: '给周恩来的信',
        authors: ['毛泽东'],
        page_start: 148,
        page_end: 148,
        dates: [{ year: 1941, month: 6 }],
        is_range_date: false,
      },
      {
        title: '在陕甘宁边区第三届参议会上的讲话',
        authors: ['毛泽东'],
        page_start: 149,
        page_end: 150,
        dates: [{ year: 1941, month: 7, day: 1 }],
        is_range_date: false,
      },
      {
        title: '关于增强党性的决定',
        authors: ['毛泽东'],
        page_start: 151,
        page_end: 153,
        dates: [{ year: 1941, month: 7, day: 1 }],
        is_range_date: false,
      },
      {
        title: '准备在战略上配合苏军作战',
        authors: ['毛泽东'],
        page_start: 154,
        page_end: 154,
        dates: [{ year: 1941, month: 7, day: 2 }],
        is_range_date: false,
      },
      {
        title: '给续范亭的信',
        authors: ['毛泽东'],
        page_start: 155,
        page_end: 155,
        dates: [{ year: 1941, month: 7, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 156,
        page_end: 156,
        dates: [{ year: 1941, month: 7, day: 5 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 157,
        page_end: 157,
        dates: [{ year: 1941, month: 7, day: 5 }],
        is_range_date: false,
      },
      {
        title: '中国共产党中央委员会为抗战四周年纪念宣言',
        authors: ['毛泽东'],
        page_start: 158,
        page_end: 163,
        dates: [{ year: 1941, month: 7, day: 7 }],
        is_range_date: false,
      },
      {
        title: '为“七七”事变四周年题词',
        authors: ['毛泽东'],
        page_start: 164,
        page_end: 164,
        dates: [{ year: 1941, month: 7, day: 7 }],
        is_range_date: false,
      },
      {
        title: '致周恩来、廖承志电',
        authors: ['毛泽东'],
        page_start: 165,
        page_end: 165,
        dates: [{ year: 1941, month: 7, day: 8 }],
        is_range_date: false,
      },
      {
        title: '骏序何应钦',
        authors: ['毛泽东'],
        page_start: 166,
        page_end: 166,
        dates: [{ year: 1941, month: 7, day: 9 }],
        is_range_date: false,
      },
      {
        title: '帮助苏联红军我们决取广泛游击战的长期斗争方针',
        authors: ['毛泽东'],
        page_start: 167,
        page_end: 169,
        dates: [{ year: 1941, month: 7, day: 15 }],
        is_range_date: false,
      },
      {
        title: '给刘雪节"的信',
        authors: ['毛泽东'],
        page_start: 170,
        page_end: 171,
        dates: [{ year: 1941, month: 7, day: 15 }],
        is_range_date: false,
      },
      {
        title: '为中国医科大学第十四期毕业生题词',
        authors: ['毛泽东'],
        page_start: 172,
        page_end: 173,
        dates: [{ year: 1941, month: 7, day: 15 }],
        is_range_date: false,
      },
      {
        title: '八路军新四军应取长期斗争方针',
        authors: ['毛泽东'],
        page_start: 174,
        page_end: 175,
        dates: [{ year: 1941, month: 7, day: 18 }],
        is_range_date: false,
      },
      {
        title: '复周恩来、董必武电',
        authors: ['毛泽东'],
        page_start: 176,
        page_end: 176,
        dates: [{ year: 1941, month: 7, day: 22 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 177,
        page_end: 177,
        dates: [{ year: 1941, month: 7, day: 24 }],
        is_range_date: false,
      },
      {
        title: '给各兵团首长的指示',
        authors: ['毛泽东'],
        page_start: 178,
        page_end: 178,
        dates: [{ year: 1941, month: 7, day: 30 }],
        is_range_date: false,
      },
      {
        title: '自卫方针应准备长期坚持下去',
        authors: ['毛泽东'],
        page_start: 179,
        page_end: 180,
        dates: [{ year: 1941, month: 7, day: 30 }],
        is_range_date: false,
      },
      {
        title: '给林伯渠、谢觉敌的信',
        authors: ['毛泽东'],
        page_start: 181,
        page_end: 181,
        dates: [{ year: 1941, month: 7, day: 31 }],
        is_range_date: false,
      },
      {
        title: '中共中央关于调查研究的决定',
        authors: ['毛泽东'],
        page_start: 182,
        page_end: 185,
        dates: [{ year: 1941, month: 8, day: 1 }],
        is_range_date: false,
      },
      {
        title: '给萧军的信',
        authors: ['毛泽东'],
        page_start: 186,
        page_end: 187,
        dates: [{ year: 1941, month: 8, day: 2 }],
        is_range_date: false,
      },
      {
        title: '军渡赢口线之河防应该加强',
        authors: ['毛泽东'],
        page_start: 188,
        page_end: 188,
        dates: [{ year: 1941, month: 8, day: 3 }],
        is_range_date: false,
      },
      {
        title: '给谢觉故的信',
        authors: ['毛泽东'],
        page_start: 189,
        page_end: 189,
        dates: [{ year: 1941, month: 8, day: 5 }],
        is_range_date: false,
      },
      {
        title: '关于财经建设的基本方针给谢觉敌的信',
        authors: ['毛泽东'],
        page_start: 190,
        page_end: 192,
        dates: [{ year: 1941, month: 8, day: 6 }],
        is_range_date: false,
      },
      {
        title: '给谢觉故的信',
        authors: ['毛泽东'],
        page_start: 193,
        page_end: 194,
        dates: [{ year: 1941, month: 8, day: 9 }],
        is_range_date: false,
      },
      {
        title: '给高岗、陈正人的信',
        authors: ['毛泽东'],
        page_start: 195,
        page_end: 195,
        dates: [{ year: 1941, month: 8, day: 9 }],
        is_range_date: false,
      },
      {
        title: '给萧军的信',
        authors: ['毛泽东'],
        page_start: 196,
        page_end: 196,
        dates: [{ year: 1941, month: 8, day: 10 }],
        is_range_date: false,
      },
      {
        title: '给谢觉截的信',
        authors: ['毛泽东'],
        page_start: 197,
        page_end: 197,
        dates: [{ year: 1941, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '给萧军的信',
        authors: ['毛泽东'],
        page_start: 198,
        page_end: 198,
        dates: [{ year: 1941, month: 8, day: 12 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 199,
        page_end: 199,
        dates: [{ year: 1941, month: 8, day: 13 }],
        is_range_date: false,
      },
      {
        title: '给张冲家属的暗电',
        authors: ['毛泽东'],
        page_start: 200,
        page_end: 200,
        dates: [{ year: 1941, month: 8, day: 13 }],
        is_range_date: false,
      },
      {
        title: '接见绥德警备区学生参观团代表时的讲话',
        authors: ['毛泽东'],
        page_start: 201,
        page_end: 201,
        dates: [{ year: 1941, month: 8, day: 14 }],
        is_range_date: false,
      },
      {
        title: '派一个团带干部去发展中条山的游击战争',
        authors: ['毛泽东'],
        page_start: 202,
        page_end: 202,
        dates: [{ year: 1941, month: 8, day: 17 }],
        is_range_date: false,
      },
      {
        title: '对伪军的政策及对伪官兵的处理意见',
        authors: ['毛泽东'],
        page_start: 203,
        page_end: 204,
        dates: [{ year: 1941, month: 8, day: 17 }],
        is_range_date: false,
      },
      {
        title: '复陈毅、刘少奇电',
        authors: ['毛泽东'],
        page_start: 205,
        page_end: 205,
        dates: [{ year: 1941, month: 8, day: 17 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 206,
        page_end: 206,
        dates: [{ year: 1941, month: 8, day: 18 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 207,
        page_end: 207,
        dates: [{ year: 1941, month: 8, day: 18 }],
        is_range_date: false,
      },
      {
        title: '给陈正人“的信',
        authors: ['毛泽东'],
        page_start: 208,
        page_end: 208,
        dates: [{ year: 1941, month: 8, day: 19 }],
        is_range_date: false,
      },
      {
        title: '中共中央关于最近国际事件的声明',
        authors: ['毛泽东'],
        page_start: 209,
        page_end: 211,
        dates: [{ year: 1941, month: 8, day: 19 }],
        is_range_date: false,
      },
      {
        title: '征求华北各战略单位对军区建设的意见',
        authors: ['毛泽东'],
        page_start: 212,
        page_end: 213,
        dates: [{ year: 1941, month: 8, day: 21 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 214,
        page_end: 214,
        dates: [{ year: 1941, month: 8, day: 22 }],
        is_range_date: false,
      },
      {
        title: '在延安日本工农学校！第二期工作报告上的批示',
        authors: ['毛泽东'],
        page_start: 215,
        page_end: 215,
        dates: [{ year: 1941, month: 8, day: 22 }],
        is_range_date: false,
      },
      {
        title: '关于总结财经工作经验给谢觉敌的信',
        authors: ['毛泽东'],
        page_start: 216,
        page_end: 218,
        dates: [{ year: 1941, month: 8, day: 22 }],
        is_range_date: false,
      },
      {
        title: '《鲁思才长征记》一文按语叫',
        authors: ['毛泽东'],
        page_start: 219,
        page_end: 219,
        dates: [{ year: 1941, month: 8, day: 26 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 220,
        page_end: 220,
        dates: [{ year: 1941, month: 8, day: 27 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 221,
        page_end: 221,
        dates: [{ year: 1941, month: 8, day: 30 }],
        is_range_date: false,
      },
      {
        title: '和国民党联络参课陈宏模等的谈话',
        authors: ['毛泽东'],
        page_start: 222,
        page_end: 222,
        dates: [{ year: 1941, month: 9, day: 1 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 223,
        page_end: 223,
        dates: [{ year: 1941, month: 9, day: 1 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 224,
        page_end: 224,
        dates: [{ year: 1941, month: 9, day: 8 }],
        is_range_date: false,
      },
      {
        title: '配合国民党军作战争取时局好转',
        authors: ['毛泽东'],
        page_start: 225,
        page_end: 225,
        dates: [{ year: 1941, month: 9, day: 9 }],
        is_range_date: false,
      },
      {
        title: '反对主观主义和宗派主义',
        authors: ['毛泽东'],
        page_start: 226,
        page_end: 230,
        dates: [{ year: 1941, month: 9, day: 10 }],
        is_range_date: false,
      },
      {
        title: '关于农村调查',
        authors: ['毛泽东'],
        page_start: 231,
        page_end: 237,
        dates: [{ year: 1941, month: 9, day: 13 }],
        is_range_date: false,
      },
      {
        title: '给高岗、陈正人的信',
        authors: ['毛泽东'],
        page_start: 238,
        page_end: 238,
        dates: [{ year: 1941, month: 9, day: 16 }],
        is_range_date: false,
      },
      {
        title: '关于张李驾进世给国民参政会的信电',
        authors: ['毛泽东'],
        page_start: 239,
        page_end: 239,
        dates: [{ year: 1941, month: 9, day: 18 }],
        is_range_date: false,
      },
      {
        title: '给续范享“的信',
        authors: ['毛泽东'],
        page_start: 240,
        page_end: 240,
        dates: [{ year: 1941, month: 9, day: 22 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 241,
        page_end: 241,
        dates: [{ year: 1941, month: 9, day: 24 }],
        is_range_date: false,
      },
      {
        title: '中央关于高级学习组的决定',
        authors: ['毛泽东'],
        page_start: 242,
        page_end: 243,
        dates: [{ year: 1941, month: 9, day: 26 }],
        is_range_date: false,
      },
      {
        title: '致中央研究组及高级研究组叫电',
        authors: ['毛泽东'],
        page_start: 244,
        page_end: 252,
        dates: [{ year: 1941, month: 9, day: 29 }],
        is_range_date: false,
      },
      {
        title: '接见陇东分区士绅参观团时的谈话',
        authors: ['毛泽东'],
        page_start: 253,
        page_end: 253,
        dates: [{ year: 1941, month: 9 }],
        is_range_date: false,
      },
      {
        title: '致刘少奇电',
        authors: ['毛泽东'],
        page_start: 254,
        page_end: 254,
        dates: [{ year: 1941, month: 10, day: 3 }],
        is_range_date: false,
      },
      {
        title: '复刘少奇电',
        authors: ['毛泽东'],
        page_start: 255,
        page_end: 255,
        dates: [{ year: 1941, month: 10, day: 11 }],
        is_range_date: false,
      },
      {
        title: '给周恩来的信',
        authors: ['毛泽东'],
        page_start: 256,
        page_end: 257,
        dates: [{ year: 1941, month: 10, day: 15 }],
        is_range_date: false,
      },
      {
        title: '关于各地应即组织高级学习组的指示',
        authors: ['毛泽东'],
        page_start: 258,
        page_end: 258,
        dates: [{ year: 1941, month: 10, day: 18 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 259,
        page_end: 259,
        dates: [{ year: 1941, month: 10, day: 18 }],
        is_range_date: false,
      },
      {
        title: '致刘少奋、陈毅电',
        authors: ['毛泽东'],
        page_start: 260,
        page_end: 260,
        dates: [{ year: 1941, month: 10, day: 18 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 261,
        page_end: 261,
        dates: [{ year: 1941, month: 10, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致周恩来等电',
        authors: ['毛泽东'],
        page_start: 262,
        page_end: 262,
        dates: [{ year: 1941, month: 10, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致贺龙、周士第等电',
        authors: ['毛泽东'],
        page_start: 263,
        page_end: 263,
        dates: [{ year: 1941, month: 10, day: 20 }],
        is_range_date: false,
      },
      {
        title: '普遍设立炸弹制造厂',
        authors: ['毛泽东'],
        page_start: 264,
        page_end: 264,
        dates: [{ year: 1941, month: 10, day: 23 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 265,
        page_end: 265,
        dates: [{ year: 1941, month: 10, day: 29 }],
        is_range_date: false,
      },
      {
        title: '在东方各民族反法西斯大会上的讲语',
        authors: ['毛泽东'],
        page_start: 266,
        page_end: 267,
        dates: [{ year: 1941, month: 10, day: 30 }],
        is_range_date: false,
      },
      {
        title: '用马克思主义的立场方法分析新事物，解决新问题',
        authors: ['毛泽东'],
        page_start: 268,
        page_end: 275,
        dates: [{ year: 1941, month: 10, day: 30 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 276,
        page_end: 276,
        dates: [{ year: 1941, month: 11, day: 1 }],
        is_range_date: false,
      },
      {
        title: '理论研究阅读材料目录',
        authors: ['毛泽东'],
        page_start: 277,
        page_end: 278,
        dates: [{ year: 1941, month: 11, day: 1 }],
        is_range_date: false,
      },
      {
        title: '本年内的学习任务及学习方法',
        authors: ['毛泽东'],
        page_start: 279,
        page_end: 280,
        dates: [{ year: 1941, month: 11, day: 4 }],
        is_range_date: false,
      },
      {
        title: '在陵甘宁边区参议会的演说',
        authors: ['毛泽东'],
        page_start: 281,
        page_end: 287,
        dates: [{ year: 1941, month: 11, day: 6 }],
        is_range_date: false,
      },
      {
        title: '和国民党联络参课陈宏漠等的谈话',
        authors: ['毛泽东'],
        page_start: 288,
        page_end: 288,
        dates: [{ year: 1941, month: 11, day: 6 }],
        is_range_date: false,
      },
      {
        title: '关于世界反法西斯斗争和中国抗日战争的广播讲演',
        authors: ['毛泽东'],
        page_start: 289,
        page_end: 290,
        dates: [{ year: 1941, month: 11, day: 7 }],
        is_range_date: false,
      },
      {
        title: '中央革命军事委员会关于抗日根据地军事建设的指示',
        authors: ['毛泽东'],
        page_start: 291,
        page_end: 298,
        dates: [{ year: 1941, month: 11, day: 7 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 299,
        page_end: 299,
        dates: [{ year: 1941, month: 11, day: 10 }],
        is_range_date: false,
      },
      {
        title: '致周恩来、重必武电',
        authors: ['毛泽东'],
        page_start: 300,
        page_end: 300,
        dates: [{ year: 1941, month: 11, day: 11 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 301,
        page_end: 301,
        dates: [{ year: 1941, month: 11, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致周恩来、董必武、邓颖超电',
        authors: ['毛泽东'],
        page_start: 302,
        page_end: 302,
        dates: [{ year: 1941, month: 11, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 303,
        page_end: 303,
        dates: [{ year: 1941, month: 11, day: 16 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 304,
        page_end: 304,
        dates: [{ year: 1941, month: 11, day: 16 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 305,
        page_end: 305,
        dates: [{ year: 1941, month: 11, day: 17 }],
        is_range_date: false,
      },
      {
        title: '关于发理论材料目录等问题',
        authors: ['毛泽东'],
        page_start: 306,
        page_end: 306,
        dates: [{ year: 1941, month: 11, day: 17 }],
        is_range_date: false,
      },
      {
        title: '在陕甘宁边区第二届参议会闭幕会上的讲话',
        authors: ['毛泽东'],
        page_start: 307,
        page_end: 307,
        dates: [{ year: 1941, month: 11, day: 21 }],
        is_range_date: false,
      },
      {
        title: '各地高级学习组应根据组织条例实施',
        authors: ['毛泽东'],
        page_start: 308,
        page_end: 308,
        dates: [{ year: 1941, month: 11, day: 26 }],
        is_range_date: false,
      },
      {
        title: '关于实施高级学习组组织条例致刘少奇电',
        authors: ['毛泽东'],
        page_start: 309,
        page_end: 310,
        dates: [{ year: 1941, month: 11, day: 26 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 311,
        page_end: 311,
        dates: [{ year: 1941, month: 11, day: 30 }],
        is_range_date: false,
      },
      {
        title: '晚张冲先生联',
        authors: ['毛泽东'],
        page_start: 312,
        page_end: 312,
        dates: [{ year: 1941, month: 11 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 313,
        page_end: 313,
        dates: [{ year: 1941, month: 12, day: 1 }],
        is_range_date: false,
      },
      {
        title: '中共中央关于太平洋反日统一战线的指示',
        authors: ['毛泽东'],
        page_start: 314,
        page_end: 316,
        dates: [{ year: 1941, month: 12, day: 9 }],
        is_range_date: false,
      },
      {
        title: '对国际战争形势的估计',
        authors: ['毛泽东'],
        page_start: 317,
        page_end: 318,
        dates: [{ year: 1941, month: 12, day: 12 }],
        is_range_date: false,
      },
      {
        title: '关于敌后各根据地领导方法的指示',
        authors: ['毛泽东'],
        page_start: 319,
        page_end: 319,
        dates: [{ year: 1941, month: 12, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 320,
        page_end: 320,
        dates: [{ year: 1941, month: 12, day: 13 }],
        is_range_date: false,
      },
      {
        title: '给蔡畅"的信',
        authors: ['毛泽东'],
        page_start: 321,
        page_end: 322,
        dates: [{ year: 1941, month: 12, day: 16 }],
        is_range_date: false,
      },
      {
        title: '为王观澜题词',
        authors: ['毛泽东'],
        page_start: 323,
        page_end: 324,
        dates: [{ year: 1941, month: 12, day: 16 }],
        is_range_date: false,
      },
      {
        title: '中共中央关于延安干部学校的决定',
        authors: ['毛泽东'],
        page_start: 325,
        page_end: 328,
        dates: [{ year: 1941, month: 12, day: 17 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 329,
        page_end: 330,
        dates: [{ year: 1941, month: 12, day: 18 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 331,
        page_end: 331,
        dates: [{ year: 1941, month: 12, day: 20 }],
        is_range_date: false,
      },
      {
        title: '给续范亭的停',
        authors: ['毛泽东'],
        page_start: 332,
        page_end: 332,
        dates: [{ year: 1941, month: 12, day: 23 }],
        is_range_date: false,
      },
      {
        title: '给任师时的信',
        authors: ['毛泽东'],
        page_start: 333,
        page_end: 333,
        dates: [{ year: 1941, month: 12, day: 25 }],
        is_range_date: false,
      },
      {
        title: '一九四二年的中心工作任务',
        authors: ['毛泽东'],
        page_start: 334,
        page_end: 335,
        dates: [{ year: 1941, month: 12, day: 28 }],
        is_range_date: false,
      },
      {
        title: '关于中共党史学习问题致周恩来电',
        authors: ['毛泽东'],
        page_start: 336,
        page_end: 337,
        dates: [{ year: 1941, month: 12, day: 30 }],
        is_range_date: false,
      },
      {
        title: '骏第三次“无”倾路线（节选',
        authors: ['毛泽东'],
        page_start: 338,
        page_end: 348,
        dates: [{ year: 1941 }],
        is_range_date: false,
      },
      {
        title: '为军委机要工作题词',
        authors: ['毛泽东'],
        page_start: 349,
        page_end: 350,
        dates: [{ year: 1941 }],
        is_range_date: false,
      },
      {
        title: '为王履丰题词叫',
        authors: ['毛泽东'],
        page_start: 351,
        page_end: 351,
        dates: [{ year: 1941 }],
        is_range_date: false,
      },
      {
        title: '为延安西北青年救国联合会主办的青运工作展览会题词',
        authors: ['毛泽东'],
        page_start: 352,
        page_end: 356,
        dates: [{ year: 1941 }],
        is_range_date: false,
      },
      {
        title: '致周恩来等电',
        authors: ['毛泽东'],
        page_start: 357,
        page_end: 357,
        dates: [{ year: 1942, month: 1, day: 7 }],
        is_range_date: false,
      },
      {
        title: '复周恩来电',
        authors: ['毛泽东'],
        page_start: 358,
        page_end: 358,
        dates: [{ year: 1942, month: 1, day: 8 }],
        is_range_date: false,
      },
      {
        title: '在周恩来关于国民党五届九中全会情况的材料上加写的一段话',
        authors: ['毛泽东'],
        page_start: 359,
        page_end: 359,
        dates: [{ year: 1942, month: 1, day: 10 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀等电',
        authors: ['毛泽东'],
        page_start: 360,
        page_end: 360,
        dates: [{ year: 1942, month: 1, day: 12 }],
        is_range_date: false,
      },
      {
        title: '《文化课本》序言',
        authors: ['毛泽东'],
        page_start: 361,
        page_end: 361,
        dates: [{ year: 1942, month: 1, day: 17 }],
        is_range_date: false,
      },
      {
        title: '为翟宪文题词叫',
        authors: ['毛泽东'],
        page_start: 362,
        page_end: 363,
        dates: [{ year: 1942, month: 1, day: 18 }],
        is_range_date: false,
      },
      {
        title: '在审改的一份情况通报上加写的一段话',
        authors: ['毛泽东'],
        page_start: 364,
        page_end: 364,
        dates: [{ year: 1942, month: 1, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀等电',
        authors: ['毛泽东'],
        page_start: 365,
        page_end: 365,
        dates: [{ year: 1942, month: 1, day: 21 }],
        is_range_date: false,
      },
      {
        title: '致朱瑞等电',
        authors: ['毛泽东'],
        page_start: 366,
        page_end: 366,
        dates: [{ year: 1942, month: 1, day: 21 }],
        is_range_date: false,
      },
      {
        title: '在关于太平洋战争后论陷区情况的通报材料上加写的一段话',
        authors: ['毛泽东'],
        page_start: 367,
        page_end: 367,
        dates: [{ year: 1942, month: 1, day: 22 }],
        is_range_date: false,
      },
      {
        title: '在欢迎七一七团晚会上的讲话',
        authors: ['毛泽东'],
        page_start: 368,
        page_end: 368,
        dates: [{ year: 1942, month: 1, day: 22 }],
        is_range_date: false,
      },
      {
        title: '印发和学习红四军九次党代表大会决议',
        authors: ['毛泽东'],
        page_start: 369,
        page_end: 370,
        dates: [{ year: 1942, month: 1, day: 23 }],
        is_range_date: false,
      },
      {
        title: '致周恩来、董必武电',
        authors: ['毛泽东'],
        page_start: 371,
        page_end: 371,
        dates: [{ year: 1942, month: 1, day: 23 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 372,
        page_end: 373,
        dates: [{ year: 1942, month: 1, day: 24 }],
        is_range_date: false,
      },
      {
        title: '中宣部宣传要点',
        authors: ['毛泽东'],
        page_start: 374,
        page_end: 376,
        dates: [{ year: 1942, month: 1, day: 26 }],
        is_range_date: false,
      },
      {
        title: '中共中央关于抗日根据地土地政策的决定',
        authors: ['毛泽东'],
        page_start: 377,
        page_end: 381,
        dates: [{ year: 1942, month: 1, day: 28 }],
        is_range_date: false,
      },
      {
        title: '为《八路军军政》杂志创刊三周年题词',
        authors: ['毛泽东'],
        page_start: 382,
        page_end: 383,
        dates: [{ year: 1942, month: 1 }],
        is_range_date: false,
      },
      {
        title: '整顿党的作风',
        authors: ['毛泽东'],
        page_start: 384,
        page_end: 402,
        dates: [{ year: 1942, month: 2, day: 1 }],
        is_range_date: false,
      },
      {
        title: '给周文"的信',
        authors: ['毛泽东'],
        page_start: 403,
        page_end: 403,
        dates: [{ year: 1942, month: 2, day: 1 }],
        is_range_date: false,
      },
      {
        title: '给各地党部及军队负责人的通知',
        authors: ['毛泽东'],
        page_start: 404,
        page_end: 404,
        dates: [{ year: 1942, month: 2, day: 2 }],
        is_range_date: false,
      },
      {
        title: '复彭德怀电',
        authors: ['毛泽东'],
        page_start: 405,
        page_end: 405,
        dates: [{ year: 1942, month: 2, day: 3 }],
        is_range_date: false,
      },
      {
        title: '中央关于如何执行土地政策决定的指示',
        authors: ['毛泽东'],
        page_start: 406,
        page_end: 410,
        dates: [{ year: 1942, month: 2, day: 4 }],
        is_range_date: false,
      },
      {
        title: '以集资料写名人列传',
        authors: ['毛泽东'],
        page_start: 411,
        page_end: 412,
        dates: [{ year: 1942, month: 2, day: 4 }],
        is_range_date: false,
      },
      {
        title: '中共中央关于抗日根据地土地政策决定的附件',
        authors: ['毛泽东'],
        page_start: 413,
        page_end: 417,
        dates: [{ year: 1942, month: 2, day: 6 }],
        is_range_date: false,
      },
      {
        title: '延安观察家之评论',
        authors: ['毛泽东'],
        page_start: 418,
        page_end: 418,
        dates: [{ year: 1942, month: 2, day: 6 }],
        is_range_date: false,
      },
      {
        title: '延安评论家称两年内击溃日寇',
        authors: ['毛泽东'],
        page_start: 419,
        page_end: 419,
        dates: [{ year: 1942, month: 2, day: 6 }],
        is_range_date: false,
      },
      {
        title: '反对党八股',
        authors: ['毛泽东'],
        page_start: 420,
        page_end: 442,
        dates: [{ year: 1942, month: 2, day: 8 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 443,
        page_end: 444,
        dates: [{ year: 1942, month: 2, day: 11 }],
        is_range_date: false,
      },
      {
        title:
          '在《中央宣传部关于进行反主观主义，反教条主义、反宗派主义、反党八股给各级宣传部的指示》上的批示',
        authors: ['毛泽东'],
        page_start: 445,
        page_end: 445,
        dates: [{ year: 1942, month: 2, day: 11 }],
        is_range_date: false,
      },
      {
        title: '复陈毅、刘少奇电',
        authors: ['毛泽东'],
        page_start: 446,
        page_end: 446,
        dates: [{ year: 1942, month: 2, day: 13 }],
        is_range_date: false,
      },
      {
        title: '庆祝红军二十四周年',
        authors: ['毛泽东'],
        page_start: 447,
        page_end: 448,
        dates: [{ year: 1942, month: 2, day: 18 }],
        is_range_date: false,
      },
      {
        title: '目前应以整顿内部训练干部为工作中心',
        authors: ['毛泽东'],
        page_start: 449,
        page_end: 450,
        dates: [{ year: 1942, month: 2, day: 20 }],
        is_range_date: false,
      },
      {
        title: '关于时局估计、干部教育、财政经济等问题的指示',
        authors: ['毛泽东'],
        page_start: 451,
        page_end: 452,
        dates: [{ year: 1942, month: 2, day: 20 }],
        is_range_date: false,
      },
      {
        title: '在一份情况通报上加写一段话',
        authors: ['毛泽东'],
        page_start: 453,
        page_end: 453,
        dates: [{ year: 1942, month: 2, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致刘少奋及华中局电',
        authors: ['毛泽东'],
        page_start: 454,
        page_end: 454,
        dates: [{ year: 1942, month: 2, day: 20 }],
        is_range_date: false,
      },
      {
        title: '讨论过去路线问题宗自是惩前瑟后，治病救人',
        authors: ['毛泽东'],
        page_start: 455,
        page_end: 456,
        dates: [{ year: 1942, month: 2, day: 21 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀等电',
        authors: ['毛泽东'],
        page_start: 457,
        page_end: 457,
        dates: [{ year: 1942, month: 2, day: 21 }],
        is_range_date: false,
      },
      {
        title: '致陈毅等电',
        authors: ['毛泽东'],
        page_start: 458,
        page_end: 458,
        dates: [{ year: 1942, month: 2, day: 23 }],
        is_range_date: false,
      },
      {
        title: '中共中央关于在职干部教育的决定',
        authors: ['毛泽东'],
        page_start: 459,
        page_end: 464,
        dates: [{ year: 1942, month: 2, day: 28 }],
        is_range_date: false,
      },
      {
        title: '在中共中央白区工作总结委员会上的一段讲话',
        authors: ['毛泽东'],
        page_start: 465,
        page_end: 465,
        dates: [{ year: 1942, month: 3, day: 2 }],
        is_range_date: false,
      },
      {
        title: '给谢觉敌的信',
        authors: ['毛泽东'],
        page_start: 466,
        page_end: 466,
        dates: [{ year: 1942, month: 3, day: 2 }],
        is_range_date: false,
      },
      {
        title: '增长力量，准备反攻',
        authors: ['毛泽东'],
        page_start: 467,
        page_end: 469,
        dates: [{ year: 1942, month: 3, day: 4 }],
        is_range_date: false,
      },
      {
        title: '为“三八”国际劳动妇女节题词叫',
        authors: ['毛泽东'],
        page_start: 470,
        page_end: 471,
        dates: [{ year: 1942, month: 3, day: 8 }],
        is_range_date: false,
      },
      {
        title: '为张浩题揽词',
        authors: ['毛泽东'],
        page_start: 472,
        page_end: 474,
        dates: [{ year: 1942, month: 3, day: 9 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 475,
        page_end: 475,
        dates: [{ year: 1942, month: 3, day: 11 }],
        is_range_date: false,
      },
      {
        title: '复彭德怀电',
        authors: ['毛泽东'],
        page_start: 476,
        page_end: 476,
        dates: [{ year: 1942, month: 3, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致王世英电',
        authors: ['毛泽东'],
        page_start: 477,
        page_end: 477,
        dates: [{ year: 1940, month: 3, day: 13 }],
        is_range_date: false,
      },
      {
        title: '党报应吸收党外人员发表言论',
        authors: ['毛泽东'],
        page_start: 478,
        page_end: 479,
        dates: [{ year: 1942, month: 3, day: 14 }],
        is_range_date: false,
      },
      {
        title: '关于共产党员与党外人员的关系',
        authors: ['毛泽东'],
        page_start: 480,
        page_end: 484,
        dates: [{ year: 1942, month: 3, day: 19 }],
        is_range_date: false,
      },
      {
        title: '致刘少奇电',
        authors: ['毛泽东'],
        page_start: 485,
        page_end: 485,
        dates: [{ year: 1942, month: 3, day: 21 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀、左权等电',
        authors: ['毛泽东'],
        page_start: 486,
        page_end: 486,
        dates: [{ year: 1942, month: 3, day: 24 }],
        is_range_date: false,
      },
      {
        title: '致周恩来、董必武电',
        authors: ['毛泽东'],
        page_start: 487,
        page_end: 487,
        dates: [{ year: 1942, month: 3, day: 24 }],
        is_range_date: false,
      },
      {
        title: '如何研究中共党中',
        authors: ['毛泽东'],
        page_start: 488,
        page_end: 500,
        dates: [{ year: 1942, month: 3, day: 30 }],
        is_range_date: false,
      },
      {
        title: '在《解放日报》改版座谈会上的讲话',
        authors: ['毛泽东'],
        page_start: 501,
        page_end: 502,
        dates: [{ year: 1942, month: 3, day: 31 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 503,
        page_end: 503,
        dates: [{ year: 1942, month: 4, day: 2 }],
        is_range_date: false,
      },
      {
        title: '为儿童节题词',
        authors: ['毛泽东'],
        page_start: 504,
        page_end: 505,
        dates: [{ year: 1942, month: 4, day: 4 }],
        is_range_date: false,
      },
      {
        title: '给萧军的信',
        authors: ['毛泽东'],
        page_start: 506,
        page_end: 506,
        dates: [{ year: 1942, month: 4, day: 4 }],
        is_range_date: false,
      },
      {
        title: '为《八路军抗战烈士纪念册》题词叫',
        authors: ['毛泽东'],
        page_start: 507,
        page_end: 507,
        dates: [{ year: 1942, month: 4, day: 5 }],
        is_range_date: false,
      },
      {
        title: '给欧阳山“的信',
        authors: ['毛泽东'],
        page_start: 508,
        page_end: 508,
        dates: [{ year: 1942, month: 4, day: 9 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 509,
        page_end: 509,
        dates: [{ year: 1942, month: 4, day: 11 }],
        is_range_date: false,
      },
      {
        title: '给欧阳山、草明的信',
        authors: ['毛泽东'],
        page_start: 510,
        page_end: 511,
        dates: [{ year: 1942, month: 4, day: 13 }],
        is_range_date: false,
      },
      {
        title: '关于时局的报告',
        authors: ['毛泽东'],
        page_start: 512,
        page_end: 512,
        dates: [{ year: 1942, month: 4, day: 13 }],
        is_range_date: false,
      },
      {
        title: '给欧阳山、草明的信',
        authors: ['毛泽东'],
        page_start: 513,
        page_end: 514,
        dates: [{ year: 1942, month: 4, day: 17 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局会议上的讲话',
        authors: ['毛泽东'],
        page_start: 515,
        page_end: 515,
        dates: [{ year: 1942, month: 4, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致陈毅电',
        authors: ['毛泽东'],
        page_start: 516,
        page_end: 516,
        dates: [{ year: 1942, month: 4, day: 19 }],
        is_range_date: false,
      },
      {
        title: '关于整顿三风',
        authors: ['毛泽东'],
        page_start: 517,
        page_end: 529,
        dates: [{ year: 1942, month: 4, day: 20 }],
        is_range_date: false,
      },
      {
        title: '准备应付反共高潮继续抓紧党内教育',
        authors: ['毛泽东'],
        page_start: 530,
        page_end: 530,
        dates: [{ year: 1942, month: 4, day: 21 }],
        is_range_date: false,
      },
      {
        title: '给萧军的信',
        authors: ['毛泽东'],
        page_start: 531,
        page_end: 531,
        dates: [{ year: 1942, month: 4, day: 27 }],
        is_range_date: false,
      },
      {
        title: '延安文艺座谈会请乘',
        authors: ['毛泽东'],
        page_start: 532,
        page_end: 533,
        dates: [{ year: 1942, month: 4, day: 27 }],
        is_range_date: false,
      },
      {
        title: '复周恩来电',
        authors: ['毛泽东'],
        page_start: 534,
        page_end: 534,
        dates: [{ year: 1942, month: 5, day: 7 }],
        is_range_date: false,
      },
    ],
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives8/maoquanji16.pdf',
};
