export default {
  entity: {
    id: 'maoquanji8',
    name: '毛泽东全集第8卷',
    internal: false,
    type: 'pdf',
    official: false,
    author: '张迪杰',
    files:
      'https://raw.githubusercontent.com/banned-historical-archives/banned-historical-archives8/main/maoquanji8.pdf',
  },
  parser_option: {
    page_limits: [],
    ext: 'pdf',
    articles: [
      {
        title: '致林彪、慧荣臻等电',
        authors: ['毛泽东'],
        page_start: 35,
        page_end: 35,
        dates: [{ year: 1935, month: 11, day: 2 }],
        is_range_date: false,
      },
      {
        title: '中央对外名义和作战方针问题',
        authors: ['毛泽东'],
        page_start: 36,
        page_end: 36,
        dates: [{ year: 1935, month: 11, day: 3 }],
        is_range_date: false,
      },
      {
        title: '关于组成西北革命军事委员会的通令',
        authors: ['毛泽东'],
        page_start: 37,
        page_end: 37,
        dates: [{ year: 1935, month: 11, day: 3 }],
        is_range_date: false,
      },
      {
        title: '关于委任红一方面军领导人的命令叫',
        authors: ['毛泽东'],
        page_start: 38,
        page_end: 38,
        dates: [{ year: 1935, month: 11, day: 3 }],
        is_range_date: false,
      },
      {
        title: '致林彪、鼓荣臻等电',
        authors: ['毛泽东'],
        page_start: 39,
        page_end: 39,
        dates: [{ year: 1935, month: 11, day: 4 }],
        is_range_date: false,
      },
      {
        title: '对随行部队的讲话',
        authors: ['毛泽东'],
        page_start: 40,
        page_end: 40,
        dates: [{ year: 1935, month: 11, day: 5 }],
        is_range_date: false,
      },
      {
        title: '调查直罗镇附近道路地形情况',
        authors: ['毛泽东'],
        page_start: 41,
        page_end: 42,
        dates: [{ year: 1935, month: 11, day: 6 }],
        is_range_date: false,
      },
      {
        title: '致林彪、鼓荣臻等电',
        authors: ['毛泽东'],
        page_start: 43,
        page_end: 43,
        dates: [{ year: 1935, month: 11, day: 7 }],
        is_range_date: false,
      },
      {
        title: '关于委任军委各部首长的命令',
        authors: ['毛泽东'],
        page_start: 44,
        page_end: 45,
        dates: [{ year: 1935, month: 11, day: 8 }],
        is_range_date: false,
      },
      {
        title: '致林彪、鼓荣臻等电',
        authors: ['毛泽东'],
        page_start: 46,
        page_end: 46,
        dates: [{ year: 1935, month: 11, day: 8 }],
        is_range_date: false,
      },
      {
        title: '致林彪、最荣臻等电',
        authors: ['毛泽东'],
        page_start: 47,
        page_end: 47,
        dates: [{ year: 1935, month: 11, day: 8 }],
        is_range_date: false,
      },
      {
        title: '致林彪、鼓荣臻等电',
        authors: ['毛泽东'],
        page_start: 48,
        page_end: 48,
        dates: [{ year: 1935, month: 11, day: 9 }],
        is_range_date: false,
      },
      {
        title: '致林彪、最荣臻等电',
        authors: ['毛泽东'],
        page_start: 49,
        page_end: 49,
        dates: [{ year: 1935, month: 11, day: 11 }],
        is_range_date: false,
      },
      {
        title:
          '中国共产党中央委员会为日本帝国主义并吞华北及将介石出卖华北出卖中国宣言',
        authors: ['毛泽东'],
        page_start: 50,
        page_end: 51,
        dates: [{ year: 1935, month: 11, day: 13 }],
        is_range_date: false,
      },
      {
        title:
          '中国共产党中央委员会为日本帝国主义并吞华北及将介石出卖华北出卖中国宣言',
        authors: ['毛泽东'],
        page_start: 52,
        page_end: 55,
        dates: [{ year: 1935, month: 11, day: 13 }],
        is_range_date: false,
      },
      {
        title: '关于举行西北革命军事委员会会议问题致林彪等电',
        authors: ['毛泽东'],
        page_start: 56,
        page_end: 56,
        dates: [{ year: 1935, month: 11, day: 13 }],
        is_range_date: false,
      },
      {
        title: '在西北革命军事委员会会议上的报告',
        authors: ['毛泽东'],
        page_start: 57,
        page_end: 57,
        dates: [{ year: 1935, month: 11, day: 18 }],
        is_range_date: false,
      },
      {
        title: '详细考察陕北苏区肃反中的问题',
        authors: ['毛泽东'],
        page_start: 58,
        page_end: 58,
        dates: [{ year: 1935, month: 11, day: 18 }],
        is_range_date: false,
      },
      {
        title: '致林彪、最荣臻电',
        authors: ['毛泽东'],
        page_start: 59,
        page_end: 59,
        dates: [{ year: 1935, month: 11, day: 19 }],
        is_range_date: false,
      },
      {
        title: '消灭直罗镇一带之敌',
        authors: ['毛泽东'],
        page_start: 60,
        page_end: 60,
        dates: [{ year: 1935, month: 11, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 61,
        page_end: 62,
        dates: [{ year: 1935, month: 11, day: 21 }],
        is_range_date: false,
      },
      {
        title: '直罗镇战役弃敌情况',
        authors: ['毛泽东'],
        page_start: 63,
        page_end: 64,
        dates: [{ year: 1935, month: 11, day: 21 }],
        is_range_date: false,
      },
      {
        title: '对敌一〇六师及董英斌部作战部署',
        authors: ['毛泽东'],
        page_start: 65,
        page_end: 65,
        dates: [{ year: 1935, month: 11, day: 22 }],
        is_range_date: false,
      },
      {
        title: '从侧面和正面抑制敌一一七师',
        authors: ['毛泽东'],
        page_start: 66,
        page_end: 66,
        dates: [{ year: 1935, month: 11, day: 22 }],
        is_range_date: false,
      },
      {
        title: '消灭重英斌沈克两师之部署',
        authors: ['毛泽东'],
        page_start: 67,
        page_end: 67,
        dates: [{ year: 1935, month: 11, day: 23 }],
        is_range_date: false,
      },
      {
        title: '一军团十五军团行动部署叫',
        authors: ['毛泽东'],
        page_start: 68,
        page_end: 68,
        dates: [{ year: 1935, month: 11, day: 23 }],
        is_range_date: false,
      },
      {
        title: '关于在直罗镇战役的指示',
        authors: ['毛泽东'],
        page_start: 69,
        page_end: 70,
        dates: [{ year: 1935, month: 11, day: 23 }],
        is_range_date: false,
      },
      {
        title: '追击逃敌董英斌的部署',
        authors: ['毛泽东'],
        page_start: 71,
        page_end: 71,
        dates: [{ year: 1935, month: 11, day: 24 }],
        is_range_date: false,
      },
      {
        title: '序将介石荒唐无班的卖国辩',
        authors: ['毛泽东'],
        page_start: 72,
        page_end: 75,
        dates: [{ year: 1935, month: 11, day: 25 }],
        is_range_date: false,
      },
      {
        title: '致景荣臻并林彪电',
        authors: ['毛泽东'],
        page_start: 76,
        page_end: 76,
        dates: [{ year: 1935, month: 11, day: 25 }],
        is_range_date: false,
      },
      {
        title: '对沈克一O六师的基本方针',
        authors: ['毛泽东'],
        page_start: 77,
        page_end: 77,
        dates: [{ year: 1935, month: 11, day: 26 }],
        is_range_date: false,
      },
      {
        title: '致董英斌电',
        authors: ['毛泽东'],
        page_start: 78,
        page_end: 78,
        dates: [{ year: 1935, month: 11, day: 26 }],
        is_range_date: false,
      },
      {
        title: '致林彪、楚荣臻等电',
        authors: ['毛泽东'],
        page_start: 79,
        page_end: 79,
        dates: [{ year: 1935, month: 11, day: 26 }],
        is_range_date: false,
      },
      {
        title:
          '中华苏维埃共和国中央政府、中国工农红军革命军事委员会抗日救国宣言',
        authors: ['毛泽东'],
        page_start: 80,
        page_end: 82,
        dates: [{ year: 1935, month: 11, day: 28 }],
        is_range_date: false,
      },
      {
        title: '致博古电',
        authors: ['毛泽东'],
        page_start: 83,
        page_end: 83,
        dates: [{ year: 1935, month: 11, day: 28 }],
        is_range_date: false,
      },
      {
        title: '目前根本方针应是南征与东讨',
        authors: ['毛泽东'],
        page_start: 84,
        page_end: 84,
        dates: [{ year: 1935, month: 11, day: 30 }],
        is_range_date: false,
      },
      {
        title: '直罗战役同目前的形势与任务',
        authors: ['毛泽东'],
        page_start: 85,
        page_end: 94,
        dates: [{ year: 1935, month: 11, day: 30 }],
        is_range_date: false,
      },
      {
        title: '中国工农红军第一方面军告围攻硬甘苏区的各部队官长与七兵书',
        authors: ['毛泽东'],
        page_start: 95,
        page_end: 96,
        dates: [{ year: 1935, month: 11 }],
        is_range_date: false,
      },
      {
        title: '红军靠近外蒙的根本方针等问题',
        authors: ['毛泽东'],
        page_start: 97,
        page_end: 98,
        dates: [{ year: 1935, month: 12, day: 1 }],
        is_range_date: false,
      },
      {
        title: '致朱德等电',
        authors: ['毛泽东'],
        page_start: 99,
        page_end: 99,
        dates: [{ year: 1935, month: 12, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致洛审、李德电',
        authors: ['毛泽东'],
        page_start: 100,
        page_end: 100,
        dates: [{ year: 1935, month: 12, day: 5 }],
        is_range_date: false,
      },
      {
        title: '给杜斌示的信以',
        authors: ['毛泽东'],
        page_start: 101,
        page_end: 101,
        dates: [{ year: 1935, month: 12, day: 5 }],
        is_range_date: false,
      },
      {
        title: '给杨虎城的信（节录）',
        authors: ['毛泽东'],
        page_start: 102,
        page_end: 103,
        dates: [{ year: 1935, month: 12, day: 5 }],
        is_range_date: false,
      },
      {
        title: '关于规定伤病员柴菜费、调养费及抚恤费的通令',
        authors: ['毛泽东'],
        page_start: 104,
        page_end: 104,
        dates: [{ year: 1935, month: 12, day: 5 }],
        is_range_date: false,
      },
      {
        title: '告陕甘苏区工农劳苦群众书',
        authors: ['毛泽东'],
        page_start: 105,
        page_end: 107,
        dates: [{ year: 1935, month: 12, day: 8 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃人民共和国中央政府对内蒙古人民的宣言',
        authors: ['毛泽东'],
        page_start: 108,
        page_end: 110,
        dates: [{ year: 1935, month: 12, day: 10 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃共和国中央执行委员会关于改变对富农政策的命令',
        authors: ['毛泽东'],
        page_start: 111,
        page_end: 112,
        dates: [{ year: 1935, month: 12, day: 15 }],
        is_range_date: false,
      },
      {
        title: '同意夺取甘泉宜加',
        authors: ['毛泽东'],
        page_start: 113,
        page_end: 115,
        dates: [{ year: 1935, month: 12, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 116,
        page_end: 116,
        dates: [{ year: 1935, month: 12, day: 19 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀并转林彪电',
        authors: ['毛泽东'],
        page_start: 117,
        page_end: 117,
        dates: [{ year: 1935, month: 12, day: 21 }],
        is_range_date: false,
      },
      {
        title: '中央关于军事战略问题的决议',
        authors: ['毛泽东'],
        page_start: 118,
        page_end: 126,
        dates: [{ year: 1935, month: 12, day: 23 }],
        is_range_date: false,
      },
      {
        title: '准备东征的行动计划',
        authors: ['毛泽东'],
        page_start: 127,
        page_end: 129,
        dates: [{ year: 1935, month: 12, day: 24 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 130,
        page_end: 130,
        dates: [{ year: 1935, month: 12, day: 24 }],
        is_range_date: false,
      },
      {
        title: '中央关于目前政治形势与党的任务的决议',
        authors: ['毛泽东'],
        page_start: 131,
        page_end: 151,
        dates: [{ year: 1935, month: 12, day: 25 }],
        is_range_date: false,
      },
      {
        title: '论反对日本帝国主义的策略',
        authors: ['毛泽东'],
        page_start: 152,
        page_end: 180,
        dates: [{ year: 1935, month: 12, day: 27 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀等电',
        authors: ['毛泽东'],
        page_start: 181,
        page_end: 181,
        dates: [{ year: 1935, month: 12, day: 27 }],
        is_range_date: false,
      },
      {
        title: '在中共中央政治局常委会议上的发言叫',
        authors: ['毛泽东'],
        page_start: 182,
        page_end: 182,
        dates: [{ year: 1935, month: 12, day: 29 }],
        is_range_date: false,
      },
      {
        title: '关于红二十八、红二十九军的组建问题则',
        authors: ['毛泽东'],
        page_start: 183,
        page_end: 183,
        dates: [{ year: 1935, month: 12, day: 30 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀等电',
        authors: ['毛泽东'],
        page_start: 184,
        page_end: 184,
        dates: [{ year: 1935, month: 12, day: 31 }],
        is_range_date: false,
      },
      {
        title: '歌谣诗·洛甫摔胶',
        authors: ['毛泽东'],
        page_start: 185,
        page_end: 185,
        dates: [{ year: 1935 }],
        is_range_date: false,
      },
      {
        title: '在抗大校务办公会议上的讲话',
        authors: ['毛泽东'],
        page_start: 186,
        page_end: 186,
        dates: [{ year: 1935 }],
        is_range_date: false,
      },
      {
        title: '和樱明德的谈话',
        authors: ['毛泽东'],
        page_start: 187,
        page_end: 190,
        dates: [{ year: 1935 }],
        is_range_date: false,
      },
      {
        title: '致朱德电',
        authors: ['毛泽东'],
        page_start: 191,
        page_end: 191,
        dates: [{ year: 1936, month: 1, day: 1 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 192,
        page_end: 192,
        dates: [{ year: 1936, month: 1, day: 1 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 193,
        page_end: 193,
        dates: [{ year: 1936, month: 1, day: 4 }],
        is_range_date: false,
      },
      {
        title: '一军团及二十五军的行动部署叫',
        authors: ['毛泽东'],
        page_start: 194,
        page_end: 195,
        dates: [{ year: 1936, month: 1, day: 5 }],
        is_range_date: false,
      },
      {
        title: '同意北征军打故援兵的部署叫',
        authors: ['毛泽东'],
        page_start: 196,
        page_end: 196,
        dates: [{ year: 1936, month: 1, day: 7 }],
        is_range_date: false,
      },
      {
        title: '消灭袁克征团等部的部署',
        authors: ['毛泽东'],
        page_start: 197,
        page_end: 197,
        dates: [{ year: 1936, month: 1, day: 9 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀、杨尚昆电',
        authors: ['毛泽东'],
        page_start: 198,
        page_end: 198,
        dates: [{ year: 1936, month: 1, day: 9 }],
        is_range_date: false,
      },
      {
        title: '敌我力量对比情况',
        authors: ['毛泽东'],
        page_start: 199,
        page_end: 199,
        dates: [{ year: 1936, month: 1, day: 10 }],
        is_range_date: false,
      },
      {
        title: '休息训练准备接受新任务',
        authors: ['毛泽东'],
        page_start: 200,
        page_end: 201,
        dates: [{ year: 1936, month: 1, day: 13 }],
        is_range_date: false,
      },
      {
        title: '关于同东北军谈判的条件致彭德怀电',
        authors: ['毛泽东'],
        page_start: 202,
        page_end: 202,
        dates: [{ year: 1936, month: 1, day: 15 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 203,
        page_end: 203,
        dates: [{ year: 1936, month: 1, day: 16 }],
        is_range_date: false,
      },
      {
        title: '关于自前行动方针与计划',
        authors: ['毛泽东'],
        page_start: 204,
        page_end: 204,
        dates: [{ year: 1936, month: 1, day: 17 }],
        is_range_date: false,
      },
      {
        title: '关于红军东进抗日讨伐卖国贼图锡山的命令',
        authors: ['毛泽东'],
        page_start: 205,
        page_end: 205,
        dates: [{ year: 1936, month: 1, day: 19 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 206,
        page_end: 206,
        dates: [{ year: 1936, month: 1, day: 19 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 207,
        page_end: 207,
        dates: [{ year: 1936, month: 1, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀等电',
        authors: ['毛泽东'],
        page_start: 208,
        page_end: 208,
        dates: [{ year: 1936, month: 1, day: 21 }],
        is_range_date: false,
      },
      {
        title: '红军为愿意同东北军联合抗日致东北军全体将士书',
        authors: ['毛泽东'],
        page_start: 209,
        page_end: 212,
        dates: [{ year: 1936, month: 1, day: 25 }],
        is_range_date: false,
      },
      {
        title: '复彭德怀电',
        authors: ['毛泽东'],
        page_start: 213,
        page_end: 213,
        dates: [{ year: 1936, month: 1, day: 25 }],
        is_range_date: false,
      },
      {
        title: '致左权电',
        authors: ['毛泽东'],
        page_start: 214,
        page_end: 214,
        dates: [{ year: 1936, month: 1, day: 31 }],
        is_range_date: false,
      },
      {
        title: '和红色中华社记者的谈话',
        authors: ['毛泽东'],
        page_start: 215,
        page_end: 218,
        dates: [{ year: 1936, month: 1 }],
        is_range_date: false,
      },
      {
        title: '致周恩来、博古、邓发电',
        authors: ['毛泽东'],
        page_start: 219,
        page_end: 219,
        dates: [{ year: 1936, month: 2, day: 3 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 220,
        page_end: 220,
        dates: [{ year: 1936, month: 2, day: 3 }],
        is_range_date: false,
      },
      {
        title: '致曾希圣电',
        authors: ['毛泽东'],
        page_start: 221,
        page_end: 221,
        dates: [{ year: 1936, month: 2, day: 3 }],
        is_range_date: false,
      },
      {
        title: '致叶剑英、林彪等电',
        authors: ['毛泽东'],
        page_start: 222,
        page_end: 222,
        dates: [{ year: 1936, month: 2, day: 6 }],
        is_range_date: false,
      },
      {
        title: '致叶剑英等电',
        authors: ['毛泽东'],
        page_start: 223,
        page_end: 223,
        dates: [{ year: 1936, month: 2, day: 8 }],
        is_range_date: false,
      },
      {
        title: '致叶剑英、杨立三电',
        authors: ['毛泽东'],
        page_start: 224,
        page_end: 224,
        dates: [{ year: 1936, month: 2, day: 8 }],
        is_range_date: false,
      },
      {
        title: '致叶剑英等电',
        authors: ['毛泽东'],
        page_start: 225,
        page_end: 225,
        dates: [{ year: 1936, month: 2, day: 10 }],
        is_range_date: false,
      },
      {
        title: '致叶剑英等电',
        authors: ['毛泽东'],
        page_start: 226,
        page_end: 226,
        dates: [{ year: 1936, month: 2, day: 10 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 227,
        page_end: 227,
        dates: [{ year: 1936, month: 2, day: 11 }],
        is_range_date: false,
      },
      {
        title: '传达与讨论东征命令及部队开进问题',
        authors: ['毛泽东'],
        page_start: 228,
        page_end: 230,
        dates: [{ year: 1936, month: 2, day: 12 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 231,
        page_end: 231,
        dates: [{ year: 1936, month: 2, day: 12 }],
        is_range_date: false,
      },
      {
        title: '东渡前抓紧提拨干部',
        authors: ['毛泽东'],
        page_start: 232,
        page_end: 232,
        dates: [{ year: 1936, month: 2, day: 13 }],
        is_range_date: false,
      },
      {
        title: '行军中严格注意隐藏',
        authors: ['毛泽东'],
        page_start: 233,
        page_end: 233,
        dates: [{ year: 1936, month: 2, day: 16 }],
        is_range_date: false,
      },
      {
        title: '全力争取东面胜利与二十八军的行动部署叫',
        authors: ['毛泽东'],
        page_start: 234,
        page_end: 235,
        dates: [{ year: 1936, month: 2, day: 17 }],
        is_range_date: false,
      },
      {
        title: '红军东征的任务',
        authors: ['毛泽东'],
        page_start: 236,
        page_end: 236,
        dates: [{ year: 1936, month: 2, day: 18 }],
        is_range_date: false,
      },
      {
        title: '关于东征作战的命令',
        authors: ['毛泽东'],
        page_start: 237,
        page_end: 240,
        dates: [{ year: 1936, month: 2, day: 18 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 241,
        page_end: 241,
        dates: [{ year: 1936, month: 2, day: 18 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 242,
        page_end: 242,
        dates: [{ year: 1936, month: 2, day: 19 }],
        is_range_date: false,
      },
      {
        title: '关于坚持联合抗日不为谣言所动致王以哲、张学良电',
        authors: ['毛泽东'],
        page_start: 243,
        page_end: 243,
        dates: [{ year: 1936, month: 2, day: 19 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 244,
        page_end: 244,
        dates: [{ year: 1936, month: 2, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀等电',
        authors: ['毛泽东'],
        page_start: 245,
        page_end: 245,
        dates: [{ year: 1936, month: 2, day: 21 }],
        is_range_date: false,
      },
      {
        title: '致徐海东、程子华电',
        authors: ['毛泽东'],
        page_start: 246,
        page_end: 246,
        dates: [{ year: 1936, month: 2, day: 21 }],
        is_range_date: false,
      },
      {
        title: '给李克农的训令',
        authors: ['毛泽东'],
        page_start: 247,
        page_end: 247,
        dates: [{ year: 1936, month: 2, day: 21 }],
        is_range_date: false,
      },
      {
        title: '两军团应乘胜向石楼急进',
        authors: ['毛泽东'],
        page_start: 248,
        page_end: 248,
        dates: [{ year: 1936, month: 2, day: 21 }],
        is_range_date: false,
      },
      {
        title: '游击队过河后的任务及组织拍架队问题',
        authors: ['毛泽东'],
        page_start: 249,
        page_end: 251,
        dates: [{ year: 1936, month: 2, day: 21 }],
        is_range_date: false,
      },
      {
        title: '我军日前方针是建立作战根据地',
        authors: ['毛泽东'],
        page_start: 252,
        page_end: 253,
        dates: [{ year: 1936, month: 2, day: 23 }],
        is_range_date: false,
      },
      {
        title: '致徐海东、程子华电',
        authors: ['毛泽东'],
        page_start: 254,
        page_end: 254,
        dates: [{ year: 1936, month: 2, day: 23 }],
        is_range_date: false,
      },
      {
        title: '致徐海东、程子华电',
        authors: ['毛泽东'],
        page_start: 255,
        page_end: 255,
        dates: [{ year: 1936, month: 2, day: 23 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 256,
        page_end: 256,
        dates: [{ year: 1936, month: 2, day: 24 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 257,
        page_end: 257,
        dates: [{ year: 1936, month: 2, day: 24 }],
        is_range_date: false,
      },
      {
        title: '争取在山西发展抗日根据地的训令',
        authors: ['毛泽东'],
        page_start: 258,
        page_end: 259,
        dates: [{ year: 1936, month: 2, day: 24 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 260,
        page_end: 260,
        dates: [{ year: 1936, month: 2, day: 25 }],
        is_range_date: false,
      },
      {
        title: '派一个师开赴车鸣岭关上等作战要地',
        authors: ['毛泽东'],
        page_start: 261,
        page_end: 261,
        dates: [{ year: 1936, month: 2, day: 25 }],
        is_range_date: false,
      },
      {
        title: '消灭关上水头两地之敌',
        authors: ['毛泽东'],
        page_start: 262,
        page_end: 262,
        dates: [{ year: 1936, month: 2, day: 25 }],
        is_range_date: false,
      },
      {
        title: '致林彪、鼓荣臻电',
        authors: ['毛泽东'],
        page_start: 263,
        page_end: 263,
        dates: [{ year: 1936, month: 2, day: 26 }],
        is_range_date: false,
      },
      {
        title: '全力消灭关上之敌',
        authors: ['毛泽东'],
        page_start: 264,
        page_end: 264,
        dates: [{ year: 1936, month: 2, day: 26 }],
        is_range_date: false,
      },
      {
        title: '在有利条件下攻击水头之敌',
        authors: ['毛泽东'],
        page_start: 265,
        page_end: 265,
        dates: [{ year: 1936, month: 2, day: 26 }],
        is_range_date: false,
      },
      {
        title: '关上村战况及我继续弃敌之部署',
        authors: ['毛泽东'],
        page_start: 266,
        page_end: 266,
        dates: [{ year: 1936, month: 2, day: 28 }],
        is_range_date: false,
      },
      {
        title: '两军团宿营位置以利于打击前进之敌为原则',
        authors: ['毛泽东'],
        page_start: 267,
        page_end: 267,
        dates: [{ year: 1936, month: 2, day: 28 }],
        is_range_date: false,
      },
      {
        title: '在关上水头地区创造作战根据地',
        authors: ['毛泽东'],
        page_start: 268,
        page_end: 269,
        dates: [{ year: 1936, month: 2, day: 28 }],
        is_range_date: false,
      },
      {
        title: '致李克农电',
        authors: ['毛泽东'],
        page_start: 270,
        page_end: 270,
        dates: [{ year: 1936, month: 2, day: 28 }],
        is_range_date: false,
      },
      {
        title: '复李克农电',
        authors: ['毛泽东'],
        page_start: 271,
        page_end: 271,
        dates: [{ year: 1936, month: 2, day: 29 }],
        is_range_date: false,
      },
      {
        title: '西北抗日红军大学招生布告',
        authors: ['毛泽东'],
        page_start: 272,
        page_end: 274,
        dates: [{ year: 1936, month: 2 }],
        is_range_date: false,
      },
      {
        title: '沁园春·雪',
        authors: ['毛泽东'],
        page_start: 275,
        page_end: 290,
        dates: [{ year: 1936, month: 2 }],
        is_range_date: false,
      },
      {
        title: '中国人民红军抗日先锋军布告',
        authors: ['毛泽东'],
        page_start: 291,
        page_end: 292,
        dates: [{ year: 1936, month: 3, day: 1 }],
        is_range_date: false,
      },
      {
        title: '一切为着打第二个胜付叫',
        authors: ['毛泽东'],
        page_start: 293,
        page_end: 294,
        dates: [{ year: 1936, month: 3, day: 1 }],
        is_range_date: false,
      },
      {
        title: '渡河以来战况与黄河以西的军事部署',
        authors: ['毛泽东'],
        page_start: 295,
        page_end: 296,
        dates: [{ year: 1936, month: 3, day: 1 }],
        is_range_date: false,
      },
      {
        title: '关于执行优待厚房政策的问题',
        authors: ['毛泽东'],
        page_start: 297,
        page_end: 297,
        dates: [{ year: 1936, month: 3, day: 2 }],
        is_range_date: false,
      },
      {
        title: '关于向东北军传达我东征车捷信及与之合作抗日等问题致李克农电',
        authors: ['毛泽东'],
        page_start: 298,
        page_end: 299,
        dates: [{ year: 1936, month: 3, day: 3 }],
        is_range_date: false,
      },
      {
        title: '致博古电',
        authors: ['毛泽东'],
        page_start: 300,
        page_end: 300,
        dates: [{ year: 1936, month: 3, day: 4 }],
        is_range_date: false,
      },
      {
        title: '谈判联合抗日的三个基本条件',
        authors: ['毛泽东'],
        page_start: 301,
        page_end: 301,
        dates: [{ year: 1936, month: 3, day: 4 }],
        is_range_date: false,
      },
      {
        title: '与南京当局谈判之意见',
        authors: ['毛泽东'],
        page_start: 302,
        page_end: 302,
        dates: [{ year: 1936, month: 3, day: 4 }],
        is_range_date: false,
      },
      {
        title:
          '关于与王以哲订立互不侵犯及经济通商口头协定等问题致博古、罗迈等电',
        authors: ['毛泽东'],
        page_start: 303,
        page_end: 303,
        dates: [{ year: 1936, month: 3, day: 4 }],
        is_range_date: false,
      },
      {
        title: '关于阁锡山进攻部署给各部队的指示',
        authors: ['毛泽东'],
        page_start: 304,
        page_end: 305,
        dates: [{ year: 1936, month: 3, day: 4 }],
        is_range_date: false,
      },
      {
        title: '致博古等电',
        authors: ['毛泽东'],
        page_start: 306,
        page_end: 306,
        dates: [{ year: 1936, month: 3, day: 4 }],
        is_range_date: false,
      },
      {
        title: '致曾希圣电',
        authors: ['毛泽东'],
        page_start: 307,
        page_end: 307,
        dates: [{ year: 1936, month: 3, day: 4 }],
        is_range_date: false,
      },
      {
        title: '消灭关上之敌的部署',
        authors: ['毛泽东'],
        page_start: 308,
        page_end: 308,
        dates: [{ year: 1936, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '关于对南京代表提出的谈判条件致李克农转王以哲电',
        authors: ['毛泽东'],
        page_start: 309,
        page_end: 309,
        dates: [{ year: 1936, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '复李克农电',
        authors: ['毛泽东'],
        page_start: 310,
        page_end: 310,
        dates: [{ year: 1936, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '消灭中阳一带敌军的部署',
        authors: ['毛泽东'],
        page_start: 311,
        page_end: 312,
        dates: [{ year: 1936, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '我方与东北军千以哲部订立口头协定的通报',
        authors: ['毛泽东'],
        page_start: 313,
        page_end: 314,
        dates: [{ year: 1936, month: 3, day: 5 }],
        is_range_date: false,
      },
      {
        title: '各个击破向大麦郊推进之敌',
        authors: ['毛泽东'],
        page_start: 315,
        page_end: 315,
        dates: [{ year: 1936, month: 3, day: 6 }],
        is_range_date: false,
      },
      {
        title: '消灭兑九哈之敌的部署叫',
        authors: ['毛泽东'],
        page_start: 316,
        page_end: 317,
        dates: [{ year: 1936, month: 3, day: 6 }],
        is_range_date: false,
      },
      {
        title: '以主力一部抄敌后路包围消灭之',
        authors: ['毛泽东'],
        page_start: 318,
        page_end: 318,
        dates: [{ year: 1936, month: 3, day: 6 }],
        is_range_date: false,
      },
      {
        title: '致萧劲光、朱理治电',
        authors: ['毛泽东'],
        page_start: 319,
        page_end: 319,
        dates: [{ year: 1936, month: 3, day: 10 }],
        is_range_date: false,
      },
      {
        title: '第四团应退满敌白水头进攻',
        authors: ['毛泽东'],
        page_start: 320,
        page_end: 320,
        dates: [{ year: 1936, month: 3, day: 10 }],
        is_range_date: false,
      },
      {
        title: '打破敌军进攻争取创造山西苏区',
        authors: ['毛泽东'],
        page_start: 321,
        page_end: 322,
        dates: [{ year: 1936, month: 3, day: 11 }],
        is_range_date: false,
      },
      {
        title: '稳固山西抗日根基',
        authors: ['毛泽东'],
        page_start: 323,
        page_end: 323,
        dates: [{ year: 1936, month: 3, day: 12 }],
        is_range_date: false,
      },
      {
        title: '关于周恩来为我方代表与张学良会谈问题致王以哲电',
        authors: ['毛泽东'],
        page_start: 324,
        page_end: 324,
        dates: [{ year: 1936, month: 3, day: 16 }],
        is_range_date: false,
      },
      {
        title: '给红军的作战命令',
        authors: ['毛泽东'],
        page_start: 325,
        page_end: 326,
        dates: [{ year: 1936, month: 3, day: 17 }],
        is_range_date: false,
      },
      {
        title: '十五军团乘虚北进相机袭取介休等地',
        authors: ['毛泽东'],
        page_start: 327,
        page_end: 328,
        dates: [{ year: 1936, month: 3, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致林彪、鼓荣臻电',
        authors: ['毛泽东'],
        page_start: 329,
        page_end: 329,
        dates: [{ year: 1936, month: 3, day: 19 }],
        is_range_date: false,
      },
      {
        title: '一军团十五军团应扩大占领区域',
        authors: ['毛泽东'],
        page_start: 330,
        page_end: 330,
        dates: [{ year: 1936, month: 3, day: 20 }],
        is_range_date: false,
      },
      {
        title:
          '关于阁锡山挡阻抗日红军及与东北军共同维护抗日后方等问题致张学良及东北军全体官兵电',
        authors: ['毛泽东'],
        page_start: 331,
        page_end: 332,
        dates: [{ year: 1936, month: 3, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 333,
        page_end: 333,
        dates: [{ year: 1936, month: 3, day: 21 }],
        is_range_date: false,
      },
      {
        title: '致林彪、鼓荣臻电',
        authors: ['毛泽东'],
        page_start: 334,
        page_end: 334,
        dates: [{ year: 1936, month: 3, day: 22 }],
        is_range_date: false,
      },
      {
        title: '致林彪、鼓荣臻电',
        authors: ['毛泽东'],
        page_start: 335,
        page_end: 335,
        dates: [{ year: 1936, month: 3, day: 22 }],
        is_range_date: false,
      },
      {
        title: '十五军团在普西北创造根据地的行动方针',
        authors: ['毛泽东'],
        page_start: 336,
        page_end: 341,
        dates: [{ year: 1936, month: 3, day: 22 }],
        is_range_date: false,
      },
      {
        title: '创造河东战场及加强要道工作',
        authors: ['毛泽东'],
        page_start: 342,
        page_end: 342,
        dates: [{ year: 1936, month: 3, day: 25 }],
        is_range_date: false,
      },
      {
        title: '第一军团的行动方针',
        authors: ['毛泽东'],
        page_start: 343,
        page_end: 344,
        dates: [{ year: 1936, month: 3, day: 25 }],
        is_range_date: false,
      },
      {
        title: '致任时等电',
        authors: ['毛泽东'],
        page_start: 345,
        page_end: 345,
        dates: [{ year: 1936, month: 3, day: 26 }],
        is_range_date: false,
      },
      {
        title: '中央政治局会议讨论政治军事等向题的通报',
        authors: ['毛泽东'],
        page_start: 346,
        page_end: 347,
        dates: [{ year: 1936, month: 3, day: 28 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 348,
        page_end: 348,
        dates: [{ year: 1936, month: 3, day: 29 }],
        is_range_date: false,
      },
      {
        title: '致徐海东、程子华等电',
        authors: ['毛泽东'],
        page_start: 349,
        page_end: 349,
        dates: [{ year: 1936, month: 3, day: 29 }],
        is_range_date: false,
      },
      {
        title: '为反对将介石阻拦一致联合抗日致全国同胞抗日士兵书',
        authors: ['毛泽东'],
        page_start: 350,
        page_end: 350,
        dates: [{ year: 1936, month: 3, day: 29 }],
        is_range_date: false,
      },
      {
        title: '集中全力与东西来敌打遭遇战',
        authors: ['毛泽东'],
        page_start: 351,
        page_end: 351,
        dates: [{ year: 1936, month: 3, day: 31 }],
        is_range_date: false,
      },
      {
        title: '第一方面军改编为中国人民红军抗日先锋军及其方针任务',
        authors: ['毛泽东'],
        page_start: 352,
        page_end: 353,
        dates: [{ year: 1936, month: 4, day: 1 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 354,
        page_end: 354,
        dates: [{ year: 1936, month: 4, day: 1 }],
        is_range_date: false,
      },
      {
        title: '目前阶段战略基本方针',
        authors: ['毛泽东'],
        page_start: 355,
        page_end: 355,
        dates: [{ year: 1936, month: 4, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致林彪、鼓荣臻电',
        authors: ['毛泽东'],
        page_start: 356,
        page_end: 356,
        dates: [{ year: 1936, month: 4, day: 2 }],
        is_range_date: false,
      },
      {
        title: '致林彪、鼓荣臻电',
        authors: ['毛泽东'],
        page_start: 357,
        page_end: 357,
        dates: [{ year: 1936, month: 4, day: 2 }],
        is_range_date: false,
      },
      {
        title: '故军布防及红军第十五军团之部署',
        authors: ['毛泽东'],
        page_start: 358,
        page_end: 359,
        dates: [{ year: 1936, month: 4, day: 2 }],
        is_range_date: false,
      },
      {
        title: '东征军的行动计划和陕甘部队的扩编问题',
        authors: ['毛泽东'],
        page_start: 360,
        page_end: 361,
        dates: [{ year: 1936, month: 4, day: 3 }],
        is_range_date: false,
      },
      {
        title: '各地斗争分子应加人团体',
        authors: ['毛泽东'],
        page_start: 362,
        page_end: 362,
        dates: [{ year: 1936, month: 4, day: 3 }],
        is_range_date: false,
      },
      {
        title: '给红军的作战命令叫',
        authors: ['毛泽东'],
        page_start: 363,
        page_end: 364,
        dates: [{ year: 1936, month: 4, day: 3 }],
        is_range_date: false,
      },
      {
        title: '和东北军接治、商谈统由周恩来负责',
        authors: ['毛泽东'],
        page_start: 365,
        page_end: 365,
        dates: [{ year: 1936, month: 4, day: 4 }],
        is_range_date: false,
      },
      {
        title:
          '为反对卖国贼蒋介石阁锡山档阳中国人民红军抗日先锋军东下抗日越乱抗日后方宣言',
        authors: ['毛泽东'],
        page_start: 366,
        page_end: 368,
        dates: [{ year: 1936, month: 4, day: 5 }],
        is_range_date: false,
      },
      {
        title: '致刘志丹等电',
        authors: ['毛泽东'],
        page_start: 369,
        page_end: 369,
        dates: [{ year: 1936, month: 4, day: 6 }],
        is_range_date: false,
      },
      {
        title: '致王以哲、张学良电',
        authors: ['毛泽东'],
        page_start: 370,
        page_end: 370,
        dates: [{ year: 1936, month: 4, day: 6 }],
        is_range_date: false,
      },
      {
        title: '一军团继续留在晋西南的任务',
        authors: ['毛泽东'],
        page_start: 371,
        page_end: 372,
        dates: [{ year: 1936, month: 4, day: 8 }],
        is_range_date: false,
      },
      {
        title: '七十八师应消耗敌军滞其南进',
        authors: ['毛泽东'],
        page_start: 373,
        page_end: 373,
        dates: [{ year: 1936, month: 4, day: 9 }],
        is_range_date: false,
      },
      {
        title: '自前应团结抗日，不应发讨蒋令',
        authors: ['毛泽东'],
        page_start: 374,
        page_end: 375,
        dates: [{ year: 1936, month: 4, day: 9 }],
        is_range_date: false,
      },
      {
        title: '红一军团的近期任务叫',
        authors: ['毛泽东'],
        page_start: 376,
        page_end: 376,
        dates: [{ year: 1936, month: 4, day: 10 }],
        is_range_date: false,
      },
      {
        title: '委任叶剑英、鼓荣臻、刘志丹为西北革命军事委员会委员',
        authors: ['毛泽东'],
        page_start: 377,
        page_end: 377,
        dates: [{ year: 1936, month: 4, day: 10 }],
        is_range_date: false,
      },
      {
        title: '关于和张学良谈判结果致林彪、慧荣臻电',
        authors: ['毛泽东'],
        page_start: 378,
        page_end: 379,
        dates: [{ year: 1936, month: 4, day: 11 }],
        is_range_date: false,
      },
      {
        title: '同意集中兵力在乡宁等地域作战',
        authors: ['毛泽东'],
        page_start: 380,
        page_end: 380,
        dates: [{ year: 1936, month: 4, day: 12 }],
        is_range_date: false,
      },
      {
        title: '十五军团和二十八军的行动部署叫',
        authors: ['毛泽东'],
        page_start: 381,
        page_end: 382,
        dates: [{ year: 1936, month: 4, day: 12 }],
        is_range_date: false,
      },
      {
        title: '左、中路军的战斗成果',
        authors: ['毛泽东'],
        page_start: 383,
        page_end: 383,
        dates: [{ year: 1936, month: 4, day: 13 }],
        is_range_date: false,
      },
      {
        title: '东征车近期工作成绩',
        authors: ['毛泽东'],
        page_start: 384,
        page_end: 384,
        dates: [{ year: 1936, month: 4, day: 13 }],
        is_range_date: false,
      },
      {
        title: '致刘志丹、宋任穷电',
        authors: ['毛泽东'],
        page_start: 385,
        page_end: 385,
        dates: [{ year: 1936, month: 4, day: 13 }],
        is_range_date: false,
      },
      {
        title: '外示统一，内专责成',
        authors: ['毛泽东'],
        page_start: 386,
        page_end: 386,
        dates: [{ year: 1936, month: 4, day: 14 }],
        is_range_date: false,
      },
      {
        title: '破坏河防与寻敌作战不宜兼顾',
        authors: ['毛泽东'],
        page_start: 387,
        page_end: 387,
        dates: [{ year: 1936, month: 4, day: 14 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 388,
        page_end: 388,
        dates: [{ year: 1936, month: 4, day: 15 }],
        is_range_date: false,
      },
      {
        title: '致林彪、慧荣臻电',
        authors: ['毛泽东'],
        page_start: 389,
        page_end: 389,
        dates: [{ year: 1936, month: 4, day: 16 }],
        is_range_date: false,
      },
      {
        title: '关于举行五一节全苏区赤卫队、少先队总检阅的命令',
        authors: ['毛泽东'],
        page_start: 390,
        page_end: 391,
        dates: [{ year: 1936, month: 4, day: 16 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 392,
        page_end: 392,
        dates: [{ year: 1936, month: 4, day: 17 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 393,
        page_end: 393,
        dates: [{ year: 1936, month: 4, day: 19 }],
        is_range_date: false,
      },
      {
        title: '诱大宁之敌西进消灭之',
        authors: ['毛泽东'],
        page_start: 394,
        page_end: 394,
        dates: [{ year: 1936, month: 4, day: 20 }],
        is_range_date: false,
      },
      {
        title: '第一军团和第十五军团自前休整计划与扩红问题',
        authors: ['毛泽东'],
        page_start: 395,
        page_end: 396,
        dates: [{ year: 1936, month: 4, day: 22 }],
        is_range_date: false,
      },
      {
        title: '赴苏联商谈在军事方面的任务',
        authors: ['毛泽东'],
        page_start: 397,
        page_end: 397,
        dates: [{ year: 1936, month: 4, day: 22 }],
        is_range_date: false,
      },
      {
        title: '红一方面军的行动方针和部署',
        authors: ['毛泽东'],
        page_start: 398,
        page_end: 398,
        dates: [{ year: 1936, month: 4, day: 22 }],
        is_range_date: false,
      },
      {
        title: '针对国民党军大举进攻对红军的行动部署叫',
        authors: ['毛泽东'],
        page_start: 399,
        page_end: 399,
        dates: [{ year: 1936, month: 4, day: 24 }],
        is_range_date: false,
      },
      {
        title: '致洛甫电',
        authors: ['毛泽东'],
        page_start: 400,
        page_end: 400,
        dates: [{ year: 1936, month: 4, day: 28 }],
        is_range_date: false,
      },
      {
        title: '关于西渡黄河的部署',
        authors: ['毛泽东'],
        page_start: 401,
        page_end: 401,
        dates: [{ year: 1936, month: 4, day: 28 }],
        is_range_date: false,
      },
      {
        title: '关于西渡黄河扩大陕甘苏区的命令',
        authors: ['毛泽东'],
        page_start: 402,
        page_end: 403,
        dates: [{ year: 1936, month: 4, day: 28 }],
        is_range_date: false,
      },
      {
        title: '各兵团目前的工作方针',
        authors: ['毛泽东'],
        page_start: 404,
        page_end: 404,
        dates: [{ year: 1936, month: 5, day: 5 }],
        is_range_date: false,
      },
      {
        title: '停战议和一致抗日通电',
        authors: ['毛泽东'],
        page_start: 405,
        page_end: 407,
        dates: [{ year: 1936, month: 5, day: 5 }],
        is_range_date: false,
      },
      {
        title: '致林彪、楚荣臻电',
        authors: ['毛泽东'],
        page_start: 408,
        page_end: 408,
        dates: [{ year: 1936, month: 5, day: 5 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 409,
        page_end: 409,
        dates: [{ year: 1936, month: 5, day: 6 }],
        is_range_date: false,
      },
      {
        title: '复刘鼎电',
        authors: ['毛泽东'],
        page_start: 410,
        page_end: 410,
        dates: [{ year: 1936, month: 5, day: 7 }],
        is_range_date: false,
      },
      {
        title: '在一方面军团以上干部会议上的讲话叫',
        authors: ['毛泽东'],
        page_start: 411,
        page_end: 411,
        dates: [{ year: 1936, month: 5, day: 11 }],
        is_range_date: false,
      },
      {
        title: '国际关系和我党的外交政策',
        authors: ['毛泽东'],
        page_start: 412,
        page_end: 412,
        dates: [{ year: 1936, month: 5, day: 15 }],
        is_range_date: false,
      },
      {
        title: '关于西征战役的行动命令',
        authors: ['毛泽东'],
        page_start: 413,
        page_end: 415,
        dates: [{ year: 1936, month: 5, day: 18 }],
        is_range_date: false,
      },
      {
        title: '红军大学的建立问题',
        authors: ['毛泽东'],
        page_start: 416,
        page_end: 417,
        dates: [{ year: 1936, month: 5, day: 20 }],
        is_range_date: false,
      },
      {
        title: '对外宣传口号及国内外政治形势与国寿关系',
        authors: ['毛泽东'],
        page_start: 418,
        page_end: 420,
        dates: [{ year: 1936, month: 5, day: 20 }],
        is_range_date: false,
      },
      {
        title: '苏维埃中央政府对回族人民的宣言',
        authors: ['毛泽东'],
        page_start: 421,
        page_end: 422,
        dates: [{ year: 1936, month: 5, day: 25 }],
        is_range_date: false,
      },
      {
        title: '苏维埃中央政府对回族人民的宣言',
        authors: ['毛泽东'],
        page_start: 423,
        page_end: 425,
        dates: [{ year: 1936, month: 5, day: 25 }],
        is_range_date: false,
      },
      {
        title: '自前形势与战略方针',
        authors: ['毛泽东'],
        page_start: 426,
        page_end: 428,
        dates: [{ year: 1936, month: 5, day: 25 }],
        is_range_date: false,
      },
      {
        title: '给阁锡山的信',
        authors: ['毛泽东'],
        page_start: 429,
        page_end: 429,
        dates: [{ year: 1936, month: 5, day: 25 }],
        is_range_date: false,
      },
      {
        title: '致阁红彦、蔡树落电',
        authors: ['毛泽东'],
        page_start: 430,
        page_end: 430,
        dates: [{ year: 1936, month: 5, day: 26 }],
        is_range_date: false,
      },
      {
        title: '致林彪等电',
        authors: ['毛泽东'],
        page_start: 431,
        page_end: 431,
        dates: [{ year: 1936, month: 5, day: 26 }],
        is_range_date: false,
      },
      {
        title: '关于军事行动问题的报告',
        authors: ['毛泽东'],
        page_start: 432,
        page_end: 432,
        dates: [{ year: 1936, month: 5, day: 28 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀等电',
        authors: ['毛泽东'],
        page_start: 433,
        page_end: 433,
        dates: [{ year: 1936, month: 5, day: 28 }],
        is_range_date: false,
      },
      {
        title: '争取教堂与我们建立和平关系',
        authors: ['毛泽东'],
        page_start: 434,
        page_end: 434,
        dates: [{ year: 1936, month: 5, day: 29 }],
        is_range_date: false,
      },
      {
        title: '关于当前军情变化和基本任务等问题的通知',
        authors: ['毛泽东'],
        page_start: 435,
        page_end: 437,
        dates: [{ year: 1936, month: 5, day: 29 }],
        is_range_date: false,
      },
      {
        title: '在一方面军团以上干部会议上的讲话',
        authors: ['毛泽东'],
        page_start: 438,
        page_end: 438,
        dates: [{ year: 1936, month: 5 }],
        is_range_date: false,
      },
      {
        title: '给盟克耳纪的信',
        authors: ['毛泽东'],
        page_start: 439,
        page_end: 439,
        dates: [{ year: 1936, month: 5 }],
        is_range_date: false,
      },
      {
        title: '成立野战军后方勤务部及设小后方',
        authors: ['毛泽东'],
        page_start: 440,
        page_end: 440,
        dates: [{ year: 1936, month: 6, day: 1 }],
        is_range_date: false,
      },
      {
        title: '在抗大第一期开学典礼上的演讲',
        authors: ['毛泽东'],
        page_start: 441,
        page_end: 442,
        dates: [{ year: 1936, month: 6, day: 1 }],
        is_range_date: false,
      },
      {
        title: '中华苏维埃人民共和国中央政府中国人民抗日红军革命军事委员会布告',
        authors: ['毛泽东'],
        page_start: 443,
        page_end: 444,
        dates: [{ year: 1936, month: 6, day: 1 }],
        is_range_date: false,
      },
      {
        title: '优待、训练和释放厚房',
        authors: ['毛泽东'],
        page_start: 445,
        page_end: 445,
        dates: [{ year: 1936, month: 6, day: 2 }],
        is_range_date: false,
      },
      {
        title: '一军团主力应向环县急进',
        authors: ['毛泽东'],
        page_start: 446,
        page_end: 446,
        dates: [{ year: 1936, month: 6, day: 2 }],
        is_range_date: false,
      },
      {
        title: '横山定边间的作战部署',
        authors: ['毛泽东'],
        page_start: 447,
        page_end: 448,
        dates: [{ year: 1936, month: 6, day: 6 }],
        is_range_date: false,
      },
      {
        title: '红军和国民党军东北军、第十七路军合作抗日的统战工作情况',
        authors: ['毛泽东'],
        page_start: 449,
        page_end: 449,
        dates: [{ year: 1936, month: 6, day: 6 }],
        is_range_date: false,
      },
      {
        title: '西方野战军在西征战役第一阶段中的战果',
        authors: ['毛泽东'],
        page_start: 450,
        page_end: 450,
        dates: [{ year: 1936, month: 6, day: 7 }],
        is_range_date: false,
      },
      {
        title: '关于回民工作的基本原则和政策',
        authors: ['毛泽东'],
        page_start: 451,
        page_end: 452,
        dates: [{ year: 1936, month: 6, day: 8 }],
        is_range_date: false,
      },
      {
        title: '关于两广事变的谈话',
        authors: ['毛泽东'],
        page_start: 453,
        page_end: 455,
        dates: [{ year: 1936, month: 6, day: 8 }],
        is_range_date: false,
      },
      {
        title: '通报国内外政治局势',
        authors: ['毛泽东'],
        page_start: 456,
        page_end: 456,
        dates: [{ year: 1936, month: 6, day: 9 }],
        is_range_date: false,
      },
      {
        title: '关于加强悦乐、曲子等地兵力及争取东北军工作致李富春、萧劲光等电',
        authors: ['毛泽东'],
        page_start: 457,
        page_end: 457,
        dates: [{ year: 1936, month: 6, day: 10 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 458,
        page_end: 458,
        dates: [{ year: 1936, month: 6, day: 10 }],
        is_range_date: false,
      },
      {
        title: '西南事变及整个形势发展问题',
        authors: ['毛泽东'],
        page_start: 459,
        page_end: 459,
        dates: [{ year: 1936, month: 6, day: 12 }],
        is_range_date: false,
      },
      {
        title: '为两广出师北上抗日宣言',
        authors: ['毛泽东'],
        page_start: 460,
        page_end: 462,
        dates: [{ year: 1936, month: 6, day: 12 }],
        is_range_date: false,
      },
      {
        title: '我军决定出瓦窑堡准备作战',
        authors: ['毛泽东'],
        page_start: 463,
        page_end: 465,
        dates: [{ year: 1936, month: 6, day: 14 }],
        is_range_date: false,
      },
      {
        title: '东北军活动情况和中央机关转移的部署',
        authors: ['毛泽东'],
        page_start: 466,
        page_end: 467,
        dates: [{ year: 1936, month: 6, day: 15 }],
        is_range_date: false,
      },
      {
        title: '第二第四方面军宜北出甘南',
        authors: ['毛泽东'],
        page_start: 468,
        page_end: 469,
        dates: [{ year: 1936, month: 6, day: 19 }],
        is_range_date: false,
      },
      {
        title: '中央关于东北军工作的指导原则',
        authors: ['毛泽东'],
        page_start: 470,
        page_end: 479,
        dates: [{ year: 1936, month: 6, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致朱德、张国寿电',
        authors: ['毛泽东'],
        page_start: 480,
        page_end: 480,
        dates: [{ year: 1936, month: 6, day: 25 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 481,
        page_end: 481,
        dates: [{ year: 1936, month: 6, day: 28 }],
        is_range_date: false,
      },
      {
        title: '全国抗日反蒋形势及与南京国民党政府的谈判情况',
        authors: ['毛泽东'],
        page_start: 482,
        page_end: 482,
        dates: [{ year: 1936, month: 6, day: 28 }],
        is_range_date: false,
      },
      {
        title: '红军接近苏联的道路和时机问题',
        authors: ['毛泽东'],
        page_start: 483,
        page_end: 484,
        dates: [{ year: 1936, month: 6, day: 29 }],
        is_range_date: false,
      },
      {
        title: '和同桂来的谈话',
        authors: ['毛泽东'],
        page_start: 485,
        page_end: 485,
        dates: [{ year: 1936, month: 6 }],
        is_range_date: false,
      },
      {
        title: '今后战略方针和任务',
        authors: ['毛泽东'],
        page_start: 486,
        page_end: 488,
        dates: [{ year: 1936, month: 7, day: 1 }],
        is_range_date: false,
      },
      {
        title: '庆祝二四方面军胜利会师致朱德张国寿等电',
        authors: ['毛泽东'],
        page_start: 489,
        page_end: 491,
        dates: [{ year: 1936, month: 7, day: 1 }],
        is_range_date: false,
      },
      {
        title: '致朱德等电',
        authors: ['毛泽东'],
        page_start: 492,
        page_end: 493,
        dates: [{ year: 1936, month: 7 }],
        is_range_date: false,
      },
      {
        title: '致朱德等电',
        authors: ['毛泽东'],
        page_start: 494,
        page_end: 495,
        dates: [{ year: 1936, month: 7 }],
        is_range_date: false,
      },
      {
        title: '关于西征战役的作战原则',
        authors: ['毛泽东'],
        page_start: 496,
        page_end: 497,
        dates: [{ year: 1936, month: 7, day: 14 }],
        is_range_date: false,
      },
      {
        title: '苏维埃中央政府对哥老会宣言',
        authors: ['毛泽东'],
        page_start: 498,
        page_end: 500,
        dates: [{ year: 1936, month: 7, day: 15 }],
        is_range_date: false,
      },
      {
        title: '为江锋等中共代表亲自签名盖章的介绍信',
        authors: ['毛泽东'],
        page_start: 501,
        page_end: 512,
        dates: [{ year: 1936, month: 7, day: 15 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 528,
        page_end: 528,
        dates: [{ year: 1936, month: 7, day: 20 }],
        is_range_date: false,
      },
      {
        title: '致周恩来电',
        authors: ['毛泽东'],
        page_start: 529,
        page_end: 529,
        dates: [{ year: 1936, month: 7, day: 21 }],
        is_range_date: false,
      },
      {
        title: '关于二、四方面军迅速出至甘南致朱、张、任电',
        authors: ['毛泽东'],
        page_start: 530,
        page_end: 530,
        dates: [{ year: 1936, month: 7, day: 22 }],
        is_range_date: false,
      },
      {
        title: '关于土地政策的指示',
        authors: ['毛泽东'],
        page_start: 531,
        page_end: 533,
        dates: [{ year: 1936, month: 7, day: 22 }],
        is_range_date: false,
      },
      {
        title: '致彭德怀电',
        authors: ['毛泽东'],
        page_start: 534,
        page_end: 534,
        dates: [{ year: 1936, month: 7, day: 23 }],
        is_range_date: false,
      },
      {
        title: '地方武装集中与分散并用的原则',
        authors: ['毛泽东'],
        page_start: 535,
        page_end: 536,
        dates: [{ year: 1936, month: 7, day: 23 }],
        is_range_date: false,
      },
      {
        title: '和斯诺关于特殊问题的谈话',
        authors: ['毛泽东'],
        page_start: 537,
        page_end: 542,
        dates: [{ year: 1936, month: 7, day: 23 }],
        is_range_date: false,
      },
      {
        title: '统战联络工作和上海党组织工作',
        authors: ['毛泽东'],
        page_start: 543,
        page_end: 543,
        dates: [{ year: 1936, month: 7, day: 26 }],
        is_range_date: false,
      },
      {
        title: '我军应继续执行三大战略任务',
        authors: ['毛泽东'],
        page_start: 544,
        page_end: 546,
        dates: [{ year: 1936, month: 7, day: 27 }],
        is_range_date: false,
      },
      {
        title: '东北军工作委员会工作问题',
        authors: ['毛泽东'],
        page_start: 547,
        page_end: 547,
        dates: [{ year: 1936, month: 7, day: 28 }],
        is_range_date: false,
      },
      {
        title: '询问红二、四方面军的行动情况致朱德等电',
        authors: ['毛泽东'],
        page_start: 548,
        page_end: 548,
        dates: [{ year: 1936, month: 7, day: 28 }],
        is_range_date: false,
      },
      {
        title: '百区工作的主要问题',
        authors: ['毛泽东'],
        page_start: 549,
        page_end: 549,
        dates: [{ year: 1936, month: 7, day: 30 }],
        is_range_date: false,
      },
      {
        title: '为中国抗日红军大学提前毕业学员赠词',
        authors: ['毛泽东'],
        page_start: 550,
        page_end: 550,
        dates: [{ year: 1936, month: 7 }],
        is_range_date: false,
      },
      {
        title: '和斯诺、马海德的谈话',
        authors: ['毛泽东'],
        page_start: 551,
        page_end: 551,
        dates: [{ year: 1936, month: 7 }],
        is_range_date: false,
      },
    ],
    ocr: { content_thresholds: [0.06, 0.06, 0.01, 0.01] },
  },
  parser_id: 'automation',
  path: '/archives8/maoquanji8.pdf',
};
